### ISSUE TITLE
force https

### ISSUE THREAD

**Issue by hanabadler** [WP-API/WP-API#1001]
how can i force the plugin to process only https request and not http?
my server is configured to use https but the plugin works for both
please help
thank
Hana

**Comment by hubdotcom** [comment]
Source: https://gist.github.com/fjarrett/8cd04bd33e49bbd6e3b7
`
/**
 * Force WP JSON REST API endpoints to always be served over HTTPS
 *
 * @action wp_json_server_before_serve
 *
 * @return void
 */
function fjarrett_wp_json_force_ssl() {
	if ( is_ssl() ) {
		return;
	}

	$json_url = esc_url_raw( $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] );
	$redirect = set_url_scheme( $json_url, 'https' );

	wp_safe_redirect( $redirect, 301 );

	exit;
}
add_action( 'wp_json_server_before_serve', 'fjarrett_wp_json_force_ssl' );
`

This is also available as a plugin https://github.com/fjarrett/json-rest-api-force-ssl

**Comment by johnbillion** [comment]
hubdotcom's solution works, but this is really something you should be handling at the server level, eg in your Apache or Nginx configuration. That way, you don't need to handle redirects in each application on your server.

**Comment by hubdotcom** [comment]
@johnbillion Agreed, it's much more efficient to do it this way. It's also the way that WordPress does it - by default it does not discriminate and force a user into https or http - it just handles the request. 

However, this raises another point, perhaps authenticated requests should respect the constant FORCE_SSL_ADMIN? Would a user assume having this set that authenticated requests were always being sent over SSL?

Reference: This is how core handles it upon login: https://github.com/WordPress/WordPress/blob/7c5fc2debb55f5c86d1c8b150220e4d2d139d9d4/wp-login.php#L14

**Comment by johnbillion** [comment]
The same issue was brought up in #259

**Comment by hubdotcom** [comment]
Thanks @johnbillion

**Comment by rachelbaker** [comment]
@hubdotcom There is a plugin to add this functionality: https://wordpress.org/plugins/json-rest-api-force-ssl/

**Comment by frankiejarrett** [comment]
The plugin has been updated to work on v2 of the WP REST API.
