### ISSUE TITLE
sort comments and parent comments

### ISSUE THREAD

**Issue by justvanbloom** [WP-API/WP-API#1003]
hi there,
 requesting commets on a post give all the comments with a order of creation by date.
subcomments who have a parent are listed below other if new comments added between.. 

eg. 
comment 1
comment 2
subcomment 3 with parent id 1

which is fail cause the right order is:

comment 1
subcomment 3 with parent id 1
comment 2

.. 
please how can we fix this?

**Comment by danielbachhuber** [comment]
We'll address in #924
