### ISSUE TITLE
how to retrieve more than 10 items from media, i.e /wp-json/media

### ISSUE THREAD

**Issue by kivydev** [WP-API/WP-API#1005]
Please help i want to retrieve all the items from media.
The default limit is 10, i want to load all the data's at once. I want to skip the pagination.
Please help

**Comment by zkingdesign** [comment]
/wp-json/posts?type=post_type_name&filter[posts_per_page]=-1

**Comment by kivydev** [comment]
Thanks a lot for the reply.
@zkingdesign

**Comment by mitogh** [comment]
Thanks @zkingdesign just exactly what I was looking for. :+1:

**Comment by danielbachhuber** [comment]
@kivydev On the `master` branch and v1.2, you can use `/wp-json/posts?type=attachment&filter[posts_per_page]=-1`

**Comment by kivydev** [comment]
Thanks a lot @danielbachhuber

**Comment by jasonbahl** [comment]
The solution proposed by @danielbachhuber doesn't work on v2. 

`posts/?type=attachment` doesn't return anything and `/media?posts_per_page=5` or `/media?filter[posts_per_page]=5` doesn't change the number of media items returned.

**Comment by jasonbahl** [comment]
I can confirm that  `media?filter[posts_per_page]=1` works in version 1.2.2 but not in 2.0-beta3

**Comment by orengbasha** [comment]
i want to before date all posts can be shown but its showing only 10 posts again and again canu please help me
