### ISSUE TITLE
How can i change 'wp-json' route prefix to another

### ISSUE THREAD

**Issue by zairl23** [WP-API/WP-API#1007]
How can i change 'wp-json' route prefix to another, for example change to 'api'..any ideas?

**Comment by JustinSainton** [comment]
You can filter it on `json_url_prefix`.  Something like the following would work:

```php
add_filter( 'json_url_prefix', function( $prefix ) { return 'api'; } );
```

Note: You will need to manually flush rewrite rules after adding that code.
