### ISSUE TITLE
Version 1.2: why two queries fired in server ?

### ISSUE THREAD

**Issue by dev-xiligroup** [WP-API/WP-API#1012]
With the new version  REST API 1.2, I begin deeper tests to improve compatibility with other plugins.
When requesting a simple json - .../wp-json/posts/ or more complex, we see two (2) queries fired in server, 
- one like the home query (but including json_route in query_vars)
- second with corresponding good query with query_vars according "translated" json_route...

The first is set as a main_query (is_main_query to true) like a front visitor home query.
The second is not a main query (like a feed)...
Because  filter like 'posts_where' are hook, why is the first query mandatory ???

**Comment by rmccue** [comment]
Due to the way we hook in currently, the first one is unavoidable (you can't tell WP not to run the main query). We're discussing moving it earlier to avoid this over in #764.
