### ISSUE TITLE
$query_object->is_home set to true ?

### ISSUE THREAD

**Issue by dev-xiligroup** [WP-API/WP-API#1014]
- a query fired by JSON request is like a feed request (is_feed) (background query) : it is not a main_query - in REST API = OK
- if the json-query is very simple with json_route like '/posts' :  $query_object->is_home is set to true like if main_query as a visitor - REST API is not here ok...

What do you think of that ?

**Comment by danielbachhuber** [comment]
> What do you think of that ?

Sorry, what's in context to?

**Comment by dev-xiligroup** [comment]
the most simplest context: a json basic query from a webapp to a server with wp and json rest api... in this context, it is inadequate that is_home is set to true (and so can give bad info to plugin analyzing the loop.
M.

**Comment by danielbachhuber** [comment]
> in this context, it is inadequate that is_home is set to true (and so can give bad info to plugin analyzing the loop.

Makes sense.

This is more of a concern for WP_Query, so I've created a Trac ticket documenting the issue: https://core.trac.wordpress.org/ticket/34373
