### ISSUE TITLE
json_multisite_not_implemented

### ISSUE THREAD

**Issue by hefejeff** [WP-API/WP-API#1015]
I have installed wp api and JSON REST API for Multisite.  When I test .../wp-json it works.  When I test /wp-json/sites/0/posts it works.  But when I test /wp-json/sites/ I get a json_multisite_not_implemented error.  Very confused.

**Comment by rachelbaker** [comment]
@hefejeff,

The [Multisite repo](https://github.com/WP-API/multisite) is almost two years old and incomplete.  We should really just remove it.  

That being said, we don't currently have built-in /sites/ routes.  You should be able to communicate with individual sites on a multisite installation using `{home_url}/wp-json/posts`.

**Comment by hefejeff** [comment]
Thank you very much for your response @rachelbaker.  I was able to get it to work by leaving the url as {home_url}/wp-json/sites/0/...

Thanks again

**Comment by rachelbaker** [comment]
@hefejeff You are welcome.  Closing this issue for now.
