### ISSUE TITLE
Only super admins can post

### ISSUE THREAD

**Issue by hefejeff** [WP-API/WP-API#1016]
I am trying to upload posts to a multisite using wp api and for some reason only Super admins can post.  I am not using any role management plugin.  Any ideas...?

**Comment by rmccue** [comment]
Can you give an example of the request you're sending, as well as the response from the server please?

**Comment by hefejeff** [comment]
Actually I got it working.  I think it had to do with some confusion I had with .../sites/0/...  All good now.  Amazing job on the Api Ryan!!

**Comment by hefejeff** [comment]
Actually it isn't working... Here is the request & response.

NSUserDefaults *def = [NSUserDefaults standardUserDefaults];
            NSString *uname = [def stringForKey:@"wp_username"];
            NSString *pass = [def stringForKey:@"wp_password"];
            NSString *wpURL = [def stringForKey:@"wp_url"];
            
            //now you can add it to your dictionary
            NSMutableDictionary *dict = [NSMutableDictionary dictionary];
            [dict setObject:self.titleLabel.text forKey:@"title"];
            [dict setObject:self.descText.text forKey:@"content"];
            [dict setObject:self.logTimestampLabel.text forKey:@"timestamp"];
            [dict setObject:self.logLatLabel.text forKey:@"latitude"];
            [dict setObject:self.logLongLabel.text forKey:@"longitude"];
            [dict setObject:self.categoryID forKey:@"category"];
           
            
                NSLog(@"%@", dict);
                AFHTTPRequestOperationManager *manager = [[AFHTTPRequestOperationManager alloc] initWithBaseURL:[NSURL URLWithString:wpURL]];
                
                manager.requestSerializer = [AFJSONRequestSerializer serializer];
                [manager.requestSerializer setAuthorizationHeaderFieldWithUsername:uname password:pass];
                
                [manager POST:@"/wp-json/sites/0/pods/boat_logs"
                   parameters: dict
                      success:^(AFHTTPRequestOperation *operation, id responseObject) {
                          NSLog(@"JSON: %@", [responseObject description]);
                      }
                      failure:^(AFHTTPRequestOperation *operation, NSError *error) {
                          NSLog(@"Error: %@", [error description]);
                      }
                 
                 ];

Response...

2015-03-26 08:14:48.635 WingMan[2916:1285111] Error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: internal server error (500)" UserInfo=0x174e62540 {com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x170a34b60> { URL: http://wingman.wingman.cr/wp-json/sites/0/pods/fish_log } { status code: 500, headers {
    "Cache-Control" = "no-cache, must-revalidate, max-age=0";
    Connection = close;
    "Content-Length" = 113;
    "Content-Type" = "application/json; charset=UTF-8";
    Date = "Thu, 26 Mar 2015 14:14:34 GMT";
    Expires = "Wed, 11 Jan 1984 05:00:00 GMT";
    Pragma = "no-cache";
    Server = "Apache/2.2.22 (Ubuntu)";
    "X-Content-Type-Options" = nosniff;
    "X-Pingback" = "http://wingman.wingman.cr/xmlrpc.php";
} }, NSLocalizedDescription=Request failed: internal server error (500), NSErrorFailingURLKey=http://wingman.wingman.cr/wp-json/sites/0/pods/fish_log}

**Comment by rmccue** [comment]
As mentioned in #1015, the multisite plugin isn't supported at all. On multisite, you can still access `wp-json` on each individual site; the multisite plugin was only intended to offer a "central" API domain.

**Comment by hefejeff** [comment]
Thanks for getting back to me.  Should I deactivate your Multisite plugin
then?

On Thursday, March 26, 2015, Ryan McCue <notifications@github.com> wrote:

> As mentioned in #1015 <https://github.com/WP-API/WP-API/issues/1015>, the
> multisite plugin isn't supported at all. On multisite, you can still access
> wp-json on each individual site; the multisite plugin was only intended
> to offer a "central" API domain.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WP-API/WP-API/issues/1016#issuecomment-86757123>.
>


-- 
Jeff Wells
+506-8845-5993

**Comment by hefejeff** [comment]
So I deactivated the the JSON Rest Api for Multisites plugin.  I was able to upload a post just fine still with the user being a super admin but when I removed the super admin privilege and left them with regular admin the I got the same error as before.  Any Ideas would be greatly appreciated.

**Comment by rachelbaker** [comment]
@hefejeff Is the user an admin on the site you are posting to?

**Comment by hefejeff** [comment]
Yes he is.  Just double checked to make sure.

On Fri, Mar 27, 2015 at 7:19 AM, Rachel Baker <notifications@github.com>
wrote:

> @hefejeff <https://github.com/hefejeff> Is the user an admin on the site
> you are posting to?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WP-API/WP-API/issues/1016#issuecomment-86937636>.
>



-- 
Jeff Wells
+506-8845-5993

**Comment by hefejeff** [comment]
I still have not been able to find a solution for this.

**Comment by hefejeff** [comment]
If it helps... I am able to upload media without being a super admin but post won't upload unless super admin
