### ISSUE TITLE
Quick Setup instructions 

### ISSUE THREAD

**Issue by hubdotcom** [WP-API/WP-API#1018]
Hi guys,

I'm all in with your mission to make this too good for WordPress core to refuse! 

I've started with reviewing the README.md and will work through the issues and codebase.

When running this command:
```git clone --recursive git@github.com:Chassis/Chassis.git api-tester```

This error was given:
```
Cloning into 'api-tester'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

To work as expected, this had to be adjusted to:
```git clone --recursive https://github.com/Chassis/Chassis.git api-tester```

Is this a local setup issue or should the documentation be updated? I've noticed in the testing the command is changed to use the https link instead

**Comment by rachelbaker** [comment]
@hubdotcom See #809 for our Readme improvements tracker and discussions.  Ideally we should update our "Testing" language to be less Chassis specific.

**Comment by danielbachhuber** [comment]
Chassis has been dropped from the docs.
