### ISSUE TITLE
Duplicate metas after 1.2

### ISSUE THREAD

**Issue by AndreiTelteu** [WP-API/WP-API#1019]
Hi.
I am using this plugin for about a month and it works pretty fine, but after i updated the plugin to 1.2 the posts created have the metas duplicated
I am sending the following json data / post request to /posts:
```json
{
    "status": "draft",
    "type": "post",
    "title": "Locke 2013",
    "name": "locke-2013",
    "content_raw": "Ivan Locke, a dedicated family man and successful construction manager, receives a phone call on the eve of the biggest challenge of his career that sets in motion a series of events that threaten his careful cultivated existence.",
    "post_meta": [
        {
            "key": "tip",
            "value": "f"
        },
        {
            "key": "imdb",
            "value": "2692904"
        },
        {
            "key": "poster",
            "value": "http:\/\/ia.media-imdb.com\/images\/M\/MV5BMTQ1MjE5MzU2M15BMl5BanBnXkFtZTgwNzE4OTMzMTE@._V1._SY500.jpg"
        },
        {
            "key": "gen",
            "value": "Drama"
        },
        {
            "key": "regizor",
            "value": "Steven Knight"
        },
        {
            "key": "staruri",
            "value": "Tom Hardy,Olivia Colman,Ruth Wilson,Andrew Scott,Ben Daniels"
        },
        {
            "key": "chei",
            "value": "Driving,One Person,Marital Trouble,One Word Title,Dead Father"
        },
        {
            "key": "playere",
            "value": "[]"
        }
    ]
}
```
And the new wordpress post has the meta datas i sent, but duplicated: [screenshot](http://pbrd.co/1H7rCHn)
I just pulled the latest files from this repo but it's the same thing.
What should i do ?
Thanks.

**Comment by AndreiTelteu** [comment]
I tested the same request on a fresh install of wordpress, with the 1.2 version it duplicates my metas, but on the 1.1 version there is no problem with duplicated metas.

Looking into the commits made between the 1.1 and 1.2 version, i think there is a problem in  #474.
I downloaded the plugin after the last commit of that pull request (eed73da3ac0a17015672b44dcb16fd46ce606df9), i tested it and it duplicates my metas.

So, the problem must be between the commits 9e019bbb76f905615723c1dd01bb45ff08d9c33c and eed73da3ac0a17015672b44dcb16fd46ce606df9. ( https://github.com/WP-API/WP-API/compare/9e019bbb76f905615723c1dd01bb45ff08d9c33c...eed73da3ac0a17015672b44dcb16fd46ce606df9 )

**Comment by AndreiTelteu** [comment]
I did a few more tests: https://github.com/WP-API/WP-API/compare/9e019bbb76f905615723c1dd01bb45ff08d9c33c...eed73da3ac0a17015672b44dcb16fd46ce606df9
13fde1a - plugin works fine.
eed73da - plugin duplicates all meta created.
So the problem is definetly here 13fde1a...eed73da

**Comment by danielbachhuber** [comment]
Thanks for your debugging, @AndreiTelteu

**Comment by cynex** [comment]
I am still having issues with duplication. In the short term, I hacked together a plugin that creates a sanitize function via a permalink. ie : sanitize/id=xyz 

in that function call, i run this. 

$meta = get_post_meta ($id);
foreach ($meta as $key=>$value)
{
	delete_post_meta($id, $key);
	add_post_meta($id, $key, $value[count($value)-1]);
}

where could I add this as a hook for any post that is being edited / created as a last step ? 
this works for now, but I would like a more stable solution.

**Comment by thoughtspacewebsites** [comment]
Just wanted to leave a note that I'm experiencing this issue too on version 1.2.1 of the API

**Comment by thoughtspacewebsites** [comment]
Cynex:

I used this hook and function setup to prevent the duplicate meta as a stop gap:

     add_action('json_insert_post', 'notions_prevent_duplicate_meta');
     
     function notions_prevent_duplicate_meta($post){
         $id = $post['ID'];
         $meta = get_post_meta($id);
         $existing_meta = array();
         foreach ($meta as $key=>$value){
             array_push($existing_meta, $key);
             if(in_array($key, $existing_meta)){
                 delete_post_meta($id, $key);
             }
         }
     }

**Comment by cynex** [comment]
Thank you for this. much easier way. exactly the hook I was looking for.

**Comment by thoughtspacewebsites** [comment]
No problem!

**Comment by shamshersingh** [comment]
I think I've found a fix to this problem. I think has something to with how WordPress handles revisions. Honestly I don't really know but this seems to fix the problem.

http://stackoverflow.com/questions/4934723/why-is-add-post-meta-creating-duplicate-entries

file: class-wp-json-meta-posts.php
line: 104

change 		if ( ! empty( $data['post_meta'] ) ) {
to 		if ( ! empty( $data['post_meta'] )  && $post->post_type == "post") {

	/**
	 * Add post meta on post update.
	 *
	 * Handles adding/updating post meta when creating or updating posts.
	 *
	 * @param array $post New post data
	 * @param array $data Raw submitted data
	 * @return array|WP_Error Post data on success, post meta error otherwise
	 */
	public function insert_post_meta( $post, $data ) {
		// Post meta
		if ( ! empty( $data['post_meta'] )  && $post->post_type == "post") {
			$result = $this->add_post_meta( $post['ID'], $data['post_meta'] );

			if ( is_wp_error( $result ) ) {
				return $result;
			}
		}

		return $post;
	}

**Comment by eduplessis** [comment]
Get the same bug on 1.2.2

**Comment by shamshersingh** [comment]
Do you guys get duplicates on the initial insert or every time you update?

If it's every time you update it may because you are not including the ID of the meta. Wordpress tracks meta by ID not by key. So it is possible to have multiple meta with the same key.

If it's on initial insert then try fix I posted above.

**Comment by eduplessis** [comment]
I've not tested the update

butt here my code 

    $.ajax({
            url: '/wp-json/posts',
            beforeSend:function(xhr){
                xhr.setRequestHeader('X-WP-Nonce', WP_API_Settings.nonce);
            },
            type: 'POST',
            dataType: 'json',
            data: {
                title: 'time ' ,
                content_raw: 'content' ,
                type: 'time_time',
                status: 'publish',
                post_meta: [{
                    key: 'time_time_in',
                    value: new Date()
                }]
            },
        })

I've commented plugin.php 109 
    
     add_filter( 'json_insert_post',  array( $wp_json_post_meta, 'insert_post_meta'   ), 10, 2 );
        
and its seem to fix it for now

**Comment by shamshersingh** [comment]
So based on that you are creating a new meta every time. You would frist need to pull the meta from the server and determine that key of the that particular meta and then update it.

commenting line 109 would just disable any meta update, no?

**Comment by rachelbaker** [comment]
Fixed in #1031

**Comment by Huvik** [comment]
experiencing same problem in v 1.2.3 latest wordpress i was debuging it in request and response and in response every meta is doubled

**Comment by NocheVolta** [comment]
I'm having this problem with 1.2.4 plugin version and WordPress 4.4
The workarounds posted here are not working for me. 
Have anyone any other possible solution or fix for this?
