### ISSUE TITLE
v. 1.2 Install error

### ISSUE THREAD

**Issue by dleeward** [WP-API/WP-API#1020]
When installing v1.2.0 on a fresh site, I received the following error during activation:
The plugin does not have a valid header.

**Comment by dleeward** [comment]
Although I was not using the default non-pretty permalink, I changed the type of permlink and that fixed it.

**Comment by danielbachhuber** [comment]
I'm not able to reproduce this. Can you reproduce it consistently? What theme are you running, and do you have any other plugins activated?

**Comment by rachelbaker** [comment]
I can reproduce this error when installing the plugin from the WordPress.org repository.  `The plugin does not have a valid header` error message is triggered from the `tests/helper.php` file. 
I suggest removing the `tests` from the WordPress.org repository anyway, since it is not production code.

**Comment by rachelbaker** [comment]
Fixed with https://plugins.trac.wordpress.org/changeset/1123808
