### ISSUE TITLE
"GET /posts" only return first page's posts

### ISSUE THREAD

**Issue by inix** [WP-API/WP-API#1021]
for example, "curl www.example.com/wp-json/posts" only return those posts that displayed on first page of my site.

I want get all posts of site,but I am read through the doc,I can not find any method to achieve all posts in one request.

Is it a bug?

**Comment by swissspidy** [comment]
No, this is the expected behavior.

The API respects the blog's "Posts per page" setting. You can use the `filter['posts_per_page']` parameter to change this. It basically supports everything [`WP_Query`](http://codex.wordpress.org/Class_Reference/WP_Query) does.

For example, this returns only one post: `https://example.com/wp-json/posts/?filter[posts_per_page]=1`

Have a look at the [docs](http://wp-api.org/#posts_retrieve-posts) for a list of other parameters.

**Comment by inix** [comment]
> swissspidy commented 6 hours ago
> 
> No, this is the expected behavior.
> 
> The API respects the blog's "Posts per page" setting. You can use the filter['posts_per_page'] parameter to change this. It basically supports everything WP_Query does.
> 
> For example, this returns only one post: https://example.com/wp-json/posts/?filter[posts_per_page]=1
> 
> Have a look at the docs for a list of other parameters.

@swissspidy 
Hi, thank you a lot, you save me a lot of tiime,I finnaly get all site posts through parameter "post_per_page=-1"

**Comment by kadamwhite** [comment]
@inix As a heads-up, I believe the general recommendation for getting all posts is to use the pagination data in the response header to request pages in sequence; using -1 can be taxing on your server.

**Comment by inix** [comment]
@kadamwhite 
Hi,I was reading the offcial doc and wordpress "WP_Query" doc carefully,but I still can not found how to get how much pages from this API.
Could you explain more detail for me?

By the way,it seems parameter "paged" do not work at all,I am not sure whether I miss understanding the meaning or a bug:
<pre>
curl -g 'www.example.com/wp-json/posts?filter[paged=2]'
</pre>
This CLI have exactlly same effects to:
<pre>
curl -g 'www.example.com/wp-json/posts'
</pre>
They both return posts the displayed at first page of my site.

Thank you

**Comment by kadamwhite** [comment]
To access pages beyond the first, you can use the `page` parameter, like so:

```
http://www.example.com/wp-json/posts?page=2
```

"paged" is not supported as a filter parameter. 

Hope that helps!

**Comment by inix** [comment]
> kadamwhite commented 21 hours ago
> To access pages beyond the first, you can use the `page` parameter, like so: ``` http://www.example.com/wp-json/posts?page=2 ``` "paged" is not supported as a filter parameter. Hope that helps!

@kadamwhite 
hi,thank you,it help a lot,you save me much time.I also know that I can get total pages from some headers,thanks.It seems 'page' parameter do not support filter.Is it a bug?
