### ISSUE TITLE
json_encode_error: Malformed UTF-8 characters

### ISSUE THREAD

**Issue by sasxa** [WP-API/WP-API#1025]
I'm getting the following error:

{"code":"json_encode_error","message":"Malformed UTF-8 characters, possibly incorrectly encoded"}

when I try this query:

http://localhost/wp-json/posts?
  filter[cat]=31&
  filter[lang]=en&
  filter[order]=DESC&
  filter[orderby]=date&
  filter[post_status]=publish&
  filter[post_type]=any&
  page=2

Wierd thing is it only happens sometimes, other times it works. And most of the time it happens on page=2, other pages (1-9) work fine. I thought there could be something wrong with posts I'm querying, but query sometimes works.. Any ideas what the problem might be?

**Comment by kennylyskjaer** [comment]
I seem to get same error, when trying to get some output from the API.

**Comment by johnbillion** [comment]
Are you sure the error is intermittent? If so, that would be very strange.

Can you try to determine if a particular post or posts are causing the problem? To me it sounds like you've some malformed characters in your post content which is tripping up the JSON encoding.

Are you using any four-byte characters on your site? For example, emoji? What's your database collation for the `wp_posts` and `wp_post_meta` tables?

**Comment by safm** [comment]
I am also having the same issue. I get this error always when I try to get all posts. It works fine when I try to get one post. My collation for all tables is "utf8_general_ci" and my wordpress version is 4.2.2.

**Comment by rvw** [comment]
Same problem here....

**Comment by rvw** [comment]
Tested some more. This error does not occur for me with Wordpress 4.1.1 + Rest API 1.2.2, but when upgraded to Wordpress 4.2.3 the error occurs. Tested with the /posts endpoint... 

BUT, when upgrading, I noticed that the contents of all my posts and pages were gone (luckily I tested on a development server). When requesting a page / post without content I get this error. When typing one letter in the post and saving, the error disappears. 

Hope this helps someone. 

@danielbachhuber can you maybe follow up on this? Is it only me, or does an empty post/page trigger this error?

**Comment by gmlion** [comment]
I'm having the same error and managed to isolate a custom post giving the problem.
I'm currently on a local Windows installation with IIS, problem doesn't seem to occur on Windows + Apache.
The following post content  (text editor) DOESN'T trigger the error:

    Assicura il trattamento contabile delle transazioni economiche patrimoniali e finanziarie dell'impresa, in base alle normative vigenti. Effettua le registrazioni contabili (prima nota, scritture contabili di base, tenuta dei registri obbligatori, stesura del bilancio di verifica, adempimenti fiscali) osservando gli obblighi di legge in materia civilistico – fiscale.
    I possibili ambiti di specializzazione sono: la contabilità clienti, la contabilità fornitori e la contabilità generale.
    Durata ore: 100
    Periodo: Dal 22/10/2012 - ciclicamente da ottobre a giugno (al raggiungimento del numero minimo di iscritti)
    Tipologia corso: Percorsi professionali
    Area formazione: Amministrazione contabilità Tipologia attestato: Attestato delle Competenze

The following, instead, DOES:

    Assicura il trattamento contabile delle transazioni economiche patrimoniali e finanziarie dell'impresa, in base alle normative vigenti. Effettua le registrazioni contabili (prima nota, scritture contabili di base, tenuta dei registri obbligatori, stesura del bilancio di verifica, adempimenti fiscali) osservando gli obblighi di legge in materia civilistico – fiscale.
    I possibili ambiti di specializzazione sono: la contabilità clienti, la contabilità fornitori e la contabilità generale.
    Durata ore: 100
    Periodo: Dal 22/10/2012 - ciclicamente da ottobre a giugno (al raggiungimento del numero minimo di iscritti)
    Tipologia corso: Percorsi professionali
    Area formazione: Amministrazione contabilità
    Tipologia attestato: Attestato delle Competenze

The only difference is the newline before the last line

**Comment by danielbachhuber** [comment]
@safm @rvw @gmlion Can one of you open a ticket on [core Trac](https://core.trac.wordpress.org/) with reproduction steps? WP-API is using `wp_json_encode()` now, so we'll want to fix the problem within that function. Thanks

cc @pento
