### ISSUE TITLE
Wordpress Sites Turn To 500 Internal Server Error After Few Json Request

### ISSUE THREAD

**Issue by diey** [WP-API/WP-API#1030]
I have installed the plugin in my wordpress site. 
It's working fine and I really like it. After a few request to wp-json/posts, my wordpress site turn to 500 internal server error.

I have to go to my wordpress installation directory and edit my .htaccess file.
I found that WP-API added a few lines of code in .htaccess. 

I delete that line and leave default .htaccess as wordpress installation, my wordpress site back to reachable but after that, wp-json/post will redirect to 404 not found page.

Any trick or patch on how I can make it work?

**Comment by johnbillion** [comment]
This plugin doesn't touch the `.htaccess` file.

What are the lines that are being added? Can you reproduce the problem with all your other plugins deactivated?

**Comment by diey** [comment]
I just found that there is a conflict between W3 Total Cache and WP-API.

I will try to reconfigure my W3 Total Cache and see what actually happen in between.

Thanks.

**Comment by wesleyxiao** [comment]
@diey i have same issue , wp api change htaccess files cause 500 internal error, any idea how to solve this issue?
