### ISSUE TITLE
Header Response Contain Invalid Character

### ISSUE THREAD

**Issue by putuyoga** [WP-API/WP-API#1032]
Hello, i met the problem when try access the api from windows phone (maybe other too). My app throw exception (net_WebHeaderInvalidControlChars) when try to get json from my site, after searching on google to find answer, ended up with http://stackoverflow.com/questions/19028068/illegal-characters-in-http-headers?lq=1

it said 
>HTTP header values may contain any ISO-8859-1 character, though many of them needed to be transmitted within quotes.

Then i'm trying analyze, and sniff wp-api response. And now i see weird value on response, "link" header value is like below:
></wp-json/posts?page=2>; rel="next", <http://xxx.com/wp-json/posts/26586>; rel="item"; title="Inilah Fitur dan Tampilan Spartan â Review Eksklusif", 

is the header response from wp-api contain illegal character ? yes, it's  ( â ), i think make link function must be patched to encode or strip away character like this
 *ref : http://www.ietf.org/rfc/rfc2616.txt

**Comment by danielbachhuber** [comment]
Thanks for flagging — we'll get this fixed.

**Comment by fobar21** [comment]
It this fixed? I have the same problem :(

How i can fix them?

**Comment by danielbachhuber** [comment]
We're no longer adding titles in headers, so this is a non issue.
