### ISSUE TITLE
500 error on /wp-json/posts

### ISSUE THREAD

**Issue by frogweb** [WP-API/WP-API#1045]
Hi,

I've installed the plugin and enabled the prettylink (I think so, because for example this hello world works with seo permalink: http://scrivere.azurewebsites.net/ciao-mondo/ ?)

Also using the C# Client example i managed to get all the avaliable apis (http://scrivere.azurewebsites.net/wp-json works) but once I try to fetch for

 /wp-json/posts

I get a 500 error in return with ReasonPhrase: 'Internal Server Error'

Also it can be interesting to say that I'm running Wordpress on Windows Azure (IIS) with SQL Server instead of mySql (but should not affect this problem).

Thank you

**Comment by frogweb** [comment]
Ok, I tryed installing a new wordpress on LAMP instead of Azure IIS and everything seems to work, so I think it could be my IIS web.config that is preventing me to visit /wp-json/posts?

Anyone tryed using wp-api on IIS?

**Comment by danielbachhuber** [comment]
> Anyone tryed using wp-api on IIS?

You may be the first! Can you track down the actual error from the server error logs?

**Comment by frogweb** [comment]
Sure,

Error from C#
-		postsResponse	{StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  X-Pingback: http://scrivere.azurewebsites.net/xmlrpc.php
  X-Content-Type-Options: nosniff
  Server: Microsoft-IIS/8.0
  X-Powered-By: PHP/5.4.38
  X-Powered-By: ASP.NET
  Date: Mon, 06 Apr 2015 14:11:06 GMT
  Content-Length: 0
  Content-Type: application/json; charset=UTF-8
}}	System.Net.Http.HttpResponseMessage

RAW error:
2015-04-06 14:25:57 SCRIVERE GET /wp-json/posts X-ARR-LOG-ID=2fd89316-bc9c-4f06-b837-195473845b82 80 - 87.16.58.166 - ARRAffinity=3c2f73106bf58975b6b306a4152fa0b9dc955cc2219896a1a4f3f290826c8e70 - scrivere.azurewebsites.net 500 0 0 527 595 734

Detailed error:


<failedRequest url="http://scrivere:80/wp-json/posts"
               siteId="787966241"
               appPoolId="scrivere"
               processId="31336"
               verb="GET"
               authenticationType="NOT_AVAILABLE"               activityId="{00000000-0000-0000-7E27-0080000800E3}"
               failureReason="STATUS_CODE"
               statusCode="200"
               triggerStatusCode="500"
               timeTaken="719"
               xmlns:freb="http://schemas.microsoft.com/win/2006/06/iis/freb"
               >
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
 <System>
  <Provider Name="WWW Server" Guid="{3A2A4E84-4C21-4981-AE10-3FDA0D9B0F83}"/>
  <EventID>0</EventID>
  <Version>1</Version>
  <Level>0</Level>
  <Opcode>1</Opcode>
  <Keywords>0x0</Keywords>
  <TimeCreated SystemTime="2015-04-06T14:25:57.044Z"/>
  <Correlation ActivityID="{00000000-0000-0000-7E27-0080000800E3}"/>
  <Execution ProcessID="31336" ThreadID="37316"/>
  <Computer>RD000D3AB0B1EC</Computer>
 </System>
 <EventData>
  <Data Name="ContextId">{00000000-0000-0000-7E27-0080000800E3}</Data>
  <Data Name="SiteId">787966241</Data>
  <Data Name="AppPoolId">scrivere</Data>
  <Data Name="ConnId">1610622844</Data>
  <Data Name="RawConnId">0</Data>
  <Data Name="RequestURL">http://scrivere:80/wp-json/posts</Data>
  <Data Name="RequestVerb">GET</Data>
 </EventData>
 <RenderingInfo Culture="en-US">
  <Opcode>GENERAL_REQUEST_START</Opcode>
 </RenderingInfo>
 <ExtendedTracingInfo xmlns="http://schemas.microsoft.com/win/2004/08/events/trace">
  <EventGuid>{D42CF7EF-DE92-473E-8B6C-621EA663113A}</EventGuid>
 </ExtendedTracingInfo>
</Event>

[error500](https://cloud.githubusercontent.com/assets/3228354/7005687/b27c98aa-dc7a-11e4-8097-e87d47ac6493.jpg)

**Comment by frogweb** [comment]
Still no solution. I abandoned the idea to use it on IIS. Thanks
