### ISSUE TITLE
Reconsider how schemas are exposed

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1047]
Currently, we're registering paths like `/wp/posts/schema`. I'm not a huge fan of this though, seems to be special-casing too much.

Maybe `_schema`?

**Comment by rmccue** [comment]
`_links.profile` would be the correct place to link the schema. Alternatively, we could expose it as the body on an OPTIONS request? (I think we're allowed to do that.)

**Comment by danielbachhuber** [comment]
> Alternatively, we could expose it as the body on an OPTIONS request? (I think we're allowed to do that.)

:boom: #1222
