### ISSUE TITLE
Non-json results

### ISSUE THREAD

**Issue by marklagendijk** [WP-API/WP-API#1058]
Is it possible to create a custom response handler which does not return JSON? I would like to have some endpoints which return a CSV file with the data.

I would like to create a response handler which returns either JSON or CSV. I'm not sure what the best way would be to specify which type should be returned. Some APIs use an extension (.json /.csv), and others use a GET parameter. Using accept headers would not work, since the users' browser would actually navigate to the url, instead of doing an AJAX request.

Is something like this possible with the current plugin?

**Comment by danielbachhuber** [comment]
> Is it possible to create a custom response handler which does not return JSON? I would like to have some endpoints which return a CSV file with the data.

Sure. You can hook into `json_pre_serve_request` and check for a custom `?_csv` param or similar.

>  I'm not sure what the best way would be to specify which type should be returned. Some APIs use an extension (.json /.csv), and others use a GET parameter.

I'd recommend keeping the default JSON response, and returning CSV when a `_csv` parameter is supplied.

**Comment by joehoyle** [comment]
I'd look for the `accept` header - I think that's more inline with the HTTP spec.
