### ISSUE TITLE
Retrieve posts by meta_query 

### ISSUE THREAD

**Issue by colinory** [WP-API/WP-API#1060]
I need the right format for my GET URL string to retrieve posts by meta_query where the custom field contains multiple values.

More info:
http://stackoverflow.com/questions/29459935/retrieve-posts-by-custom-field-with-wp-rest-api-in-javascript

**Comment by danielbachhuber** [comment]
This isn't currently supported without writing some custom code.

We'll do our best to address as a part of #924

**Comment by colinory** [comment]
Thanks. And what kind of custom code?

**Comment by colinory** [comment]
updated, see comment > http://stackoverflow.com/questions/29459935/retrieve-posts-by-custom-field-with-wp-rest-api-in-javascript
