### ISSUE TITLE
Ping Google question

### ISSUE THREAD

**Issue by ferranmv** [WP-API/WP-API#1067]
Dear WP Rest Api team,

We have a software that pushes from our backend automatically articles into a WP frontend but we have the following issue: we are not pinging Google when publishing the post and therefore our articles do not really get indexed.

We understand that if we switch to your WP API when we create an article you will use the regular WP procedure of creating an article and therefore you will ping Google right?

Thanks for your time and your work,

Ferran

**Comment by swissspidy** [comment]
I'd recommend asking such questions in the WordPress Slack #core-restapi channel.

AFAIK the WP-API uses `wp_insert_post()` which handles all the pinging.

**Comment by ferranmv** [comment]
Thanks for the quick and prompt answer! We will check there and dive a bit more into that function!

**Comment by rmccue** [comment]
The REST API handles pinging external services the same way that publishing a normal post via the admin works, so Google should be notified normally.

(In a technical sense: publishing a post fires off `_publish_post_hook`, which in turn calls `do_all_pings` and `generic_pings`. This sends a request off to [Pingomatic](http://pingomatic.com/) by default.)
