### ISSUE TITLE
Server side or pre-filter JSON response

### ISSUE THREAD

**Issue by kenjikato** [WP-API/WP-API#1069]
Sorry if this seems to be a newb question, but I'm looking for a simple way to pre-filter or limit the information returned in a JSON request.

I need this because I'm building a mobile app, and would like to use wordpress as the backend via the wp-api, but I can't have say 100 post with ALL their default data coming back to the user with every request.  I know about the caller side filtering to grab all the response in say a named category ```/posts?filter%5Bcategory_name%5D=```

But I want any request that comes in through the wp-api to only return a limited JSON set of data as defined by say a simple rule set, or even basic interface that lets me allow or disallow what data goes into the returned JSON file.

This means I don't have to have complex logic on the callers side to create crazy filter GETS, and I can leverage the power of my cloud server.

For example, say I wanted my JSON file to only include the Title, Categories, Date Modified, Featured_Image link, two custom fields, and nothing else for a GET that filters on say a specific category.

Having all the data is great, but if you are trying to build an efficient module app, then you need to be very selective about what data goes out from the server in a JSON file response.

Hopefully this makes sense.

Thanks!

**Comment by johnbillion** [comment]
The [`json_post_dispatch` filter](https://github.com/WP-API/WP-API/blob/develop/lib/infrastructure/class-wp-json-server.php#L248-L254) should provide what you need.

**Comment by kenjikato** [comment]
@johnbillion thanks for the response. While the description in the code sounds like this is what I'm looking for.  I have no idea of how I'm suppose to use ```json_post_dispatch``` filter other than I have to implement something around ```apply_filters``` I'm guessing.

Is there any documentation, or an example that shows how to use it?

Again sorry if this is a newb question.

Thanks!

**Comment by johnbillion** [comment]
The `apply_filters` function is part of the WordPress Plugin API. It's a one of the fundamental parts of extending WordPress. Take a look at [the Codex page]https://codex.wordpress.org/Plugin_API) for an intro to using it.

**Comment by kenjikato** [comment]
@johnbillion thanks for the info thus far, but I guess I'm completely lost in how I'm suppose to implement this right now.

After several days of trying to create my first plugin to work with the WP-API (after reading through the Codex and even taking an online course of creating WP plugins), I realized that the ```json_post_dispatch``` you pointed me to isn't in the current [WordPress.org WP REST API plugin] (https://wordpress.org/plugins/json-rest-api/) release version 1.2.1., and is only in the dev version right now. Please correct me if I'm wrong.

So I downloaded the Dev branch, and tried to install it into my WordPress install with no luck.

I'm going to keep hacking around, and see if I can get it to work, but any pointers on where to go from here are welcome.

Even a simple example of just returning the each post

**Comment by johnbillion** [comment]
> I realized that the json_post_dispatch you pointed me to isn't in the current WordPress.org WP REST API plugin release version 1.2.1., and is only in the dev version right now.

Ah, you're right there. This is a new filter in the 2.0 dev branch.

In that case you can try the [`json_serve_request` filter](https://github.com/WP-API/WP-API/blob/1.2.1/lib/class-wp-json-server.php#L265-L279). This works a little differently, in that the filter value is a boolean. The purpose of this is so you can output the JSON manually in your filter callback, and then return boolean `true` to prevent the default JSON output from happening. You'll probably want to copy the logic from [the lines below](https://github.com/WP-API/WP-API/blob/1.2.1/lib/class-wp-json-server.php#L281-L302) to use in your filter callback, and make the necessary adjustments to the amount of data that actually gets output.
