### ISSUE TITLE
Wordpress internals API endpoints

### ISSUE THREAD

**Issue by matrixik** [WP-API/WP-API#107]
Hello,

would be nice if this plug-in (or Wordpress API, in long term of course) could provide some more info about Wordpress blog as a platform:
* if there are updates to Wordpress
* what plug-ins are installed
* are there any updates to plug-ins
etc.

Some examples:
http://wordpress.org/plugins/iwp-client/
http://wordpress.org/plugins/worker/

Best regards

**Comment by matrixik** [comment]
Looks like Jetpack devs already added similar API functionality to they JSON API:
http://jetpack.me/2014/12/16/jetpack-3-3-a-single-home-for-all-your-wordpress-sites/

Why do you not cooperate in building **one** JSON API for Wordpress?

**Comment by rachelbaker** [comment]
@matrixik Thank you for the advice.  We are cooperating with the WordPress.com API developers and intend to continue to do so in hopes of merging the two APIs together in the future.

**Comment by danielbachhuber** [comment]
Closing in favor of #1500
