### ISSUE TITLE
Create README.md from readme.txt

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1083]
It's really painful to put releases together otherwise.

We can crib from https://github.com/fusioneng/Unified-Post-Types/commit/9b280f07e8ba79977f54103f938e0422ee63a1f2

**Comment by rmccue** [comment]
I'd like to keep `README.md` and `readme.txt` separate: the former is for developers, focussed on this repo, whereas the latter is our docs/marketing on dotorg. That said, we should be able to turn readme.txt into a template, and build it from our `CHANGELOG.md` reasonably nicely.

**Comment by danielbachhuber** [comment]
It's much easier to keep them one and the same, and use the Description field to point people in the right direction. I will combine the two.

**Comment by rmccue** [comment]
We don't want to show things like the `develop`/`master` distinction on the plugin repo though, and we want to push people from GitHub off to the repo unless they're intending on working on the plugin itself.

**Comment by danielbachhuber** [comment]
Fair enough.
