### ISSUE TITLE
Make security issue disclosure policy more prominent

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1084]
It's apparently not prominent enough right now :)

**Comment by johnbillion** [comment]
You know what would be great? If GitHub Issues supported the same sort of security report notices that we use on core trac when someone goes to submit a new ticket. Might be worth mentioning to GitHub as a feature request.

**Comment by chredd** [comment]
:+1:

**Comment by michaelbeil** [comment]
agreed @johnbillion. did you submit a ticket?

**Comment by michaelbeil** [comment]
FYI: 
![screen shot 2015-04-11 at 11 52 51 am](https://cloud.githubusercontent.com/assets/4752949/7102323/e5fac29a-e041-11e4-9974-a320cf076221.png)
