### ISSUE TITLE
Forcing WP-API to use https:// protocol for image URLs in responses

### ISSUE THREAD

**Issue by mellinger** [WP-API/WP-API#1085]
My site uses https:// on all of its page. It employs WP-API to fetch posts on one area of the site. The URLs returned for the featured image and thumbnails all start with http://, which makes the browser throw "X site is displaying insecure content from..." warnings. On the page templates themselves, references to the images all output with the proper protocol. I've done due diligence in trying to figure out if there is a known solution for this sort of thing and haven't come up short.

I'm using the WP-HTTPS and Amazon S3 plugins, not sure if that matters in this situation. 

Thank you!!!

**Comment by danielbachhuber** [comment]
Can you share an example request to WP-API? WP-API uses core functions to generate the image URLs, so it's likely WordPress doesn't know it needs to be returning `https` URLs.

**Comment by mellinger** [comment]
WP-API wasn't an issue, it was that my Amazon S3 plugin was overriding wp_get_attachment_url and needed to be modified to detect my SSL setup (in my case, just blunt-forcing it in the plugin source).
