### ISSUE TITLE
502 request cancelled

### ISSUE THREAD

**Issue by jdozierezell** [WP-API/WP-API#1086]
I'm using the url below to serve a large number of posts and the request is timing out. Is there a way to increase the response time to allow for more posts? It currently times out somewhere between 310 and 315 posts. There are currently just over 400 that need to be served, but that number may grow. Thanks!

http://iframe.afsp.wpengine.com/wp-json/posts?type=support_group&filter[posts_per_page]=-1

**Comment by danielbachhuber** [comment]
> Is there a way to increase the response time to allow for more posts?

This will be something you can set server side. However, I don't believe WP Engine will permit making such a change, so you'll likely need to paginate your result set.
