### ISSUE TITLE
GET /wp/posts: No navigation headers sent on empty result set

### ISSUE THREAD

**Issue by goblindegook** [WP-API/WP-API#1088]
I'm not 100% sure this is intended, but when a `GET` request yields no results, the Posts controller calls `json_ensure_response( array() )` without adding any navigation headers. Are clients to assume that no headers means `X-WP-Total` and `X-WP-TotalPages` are both 0? Isn't it better to be explicit here?

 (Alternatively, an empty result set could return a 204 No Content status code, but that's more of a design decision.)

**Comment by danielbachhuber** [comment]
This was fixed by #1209
