### ISSUE TITLE
Wrong nonce action in documentation for cookie authentication

### ISSUE THREAD

**Issue by sanderaido** [WP-API/WP-API#1092]
On http://wp-api.org/guides/authentication.html, in the Cookie Authentication paragraph there is a line saying 
> The API uses nonces with the action set to 'wp_api'.

which is incorrect. The right action is 'wp_json'.

The sample below the paragraph has the right action of `wp_create_nonce( 'wp_json' )`, took me a while to figure this out.

**Comment by danielbachhuber** [comment]
Thanks for the report! Fixed https://github.com/WP-API/WP-API.github.io/commit/10039d94a9e06efd07ccb22928d9b37045de9311
