### ISSUE TITLE
Redirection(/users/me) is not working on CORS request

### ISSUE THREAD

**Issue by pismute** [WP-API/WP-API#1093]
Redirection is not working on CORS request.

I got a following message:

>XMLHttpRequest cannot load `.../wp-json/users/me`. The request was redirected to `.../wp-json/users/2`, which is disallowed for cross-origin requests that require preflight.

Remarking some code in `class-wp-json-users.php` makes it work nicely.

```
		/*
		$data = $response->get_data();

		$response->header( 'Location', $data['meta']['links']['self'] );
		$response->set_status( 302 );
		*/
```

I think we must avoid redirection because it is transparent in browser so that users cannot handle it.

I also tried redirecting through my CORS proxy, it is not working too.

**Comment by enricodeleo** [comment]
Hi everybody, I'm experiencing this very same issue. 

I usually take advantage of [corsproxy](https://github.com/gr2m/CORS-Proxy) when I develop js-based apps locally and it works like a charme with wp-api for all the endpoints even with authentication (currently on basic auth since I'm in development mode) but /users endpoint.

I get this error on my local console
```js
XMLHttpRequest cannot load http://localhost:9292/mywebsite.com/wp-json/users/me. The request was redirected to 'http://mywebsite.com/wp-json/users/6', which is disallowed for cross-origin requests that require preflight.
``` 

Any ideas?

**Comment by pismute** [comment]
I am in ionic app. I gave up using a CORS proxy. I made a patch instead.

I added `Access-Control-Allow-Headers` headers in `json_send_cors_headers` funciton of `plugin.php`:

```
function json_send_cors_headers( $value ) {
        ...
	if ( $origin ) {
		...
		header( 'Access-Control-Allow-Headers: Authorization, Content-Type' );
	}
        ...
}
```

I need to allow two headers for CORS request, `Authorization` for basic auth, `Content-Type` for json. But I think we have to support CORS proxies.

**Comment by enricodeleo** [comment]
I'll try the same patch tomorrow, but I agree that this should be supported by design... Is there any reason not to do so?

**Comment by pismute** [comment]
No, just I am not sure about the design.

IMO, `.../wp-json/users/me` might respond the same result of `.../wp-json/users/:id`. Is it ok with HATEOS?

**Comment by rmccue** [comment]
The original design is intentional. `/users/me` isn't a real resource, it's just a pointer to the actual user. If there's something we have to do to support this better with CORS, happy to accept pull requests.

> I think we must avoid redirection because it is transparent in browser so that users cannot handle it.

If you're in an environment where you can't trust the client properly (i.e. browsers), you can use `&_envelope` to the URL and get back an enveloped response instead: #628.

**Comment by pismute** [comment]
Thank you for clarification.

**Comment by enricodeleo** [comment]
thank you @rmccue.
My app doesn't work anyway with envelope (ngResource expects a key/value pair for every parameter, I also tried the bare $http.get but I continue to get a redirection alert on my console). I'm going to  pass the bare id (I'll store it during login), it should bypass this behavior...

**Comment by pismute** [comment]
I decided to use [Wordpress OAuth server](https://wp-oauth.com/) instead of Basic Authentication. I think OAuth is mandatory under CORS. If we use Basic Authentication, we need valid certificates even in development.

When `Authentication` header exists and response code is not 2xx, browser automatically generates a preflight request. but browser(at least Chrome) disallow any preflight request under untrusted CORS connections.

Possible solutions are:

1. We have to use other authentication method instead of Basic Authentication, which doesn't cause preflight request.
2. Or make trusted CORS connections.

Self-signed certificate is considered untrusted. [Michael Cox said](http://stackoverflow.com/questions/20671619/angularjs-options-preflight-call-preceding-a-http-post-request):

>That means you're probably using some sort of self-signed SSL certificate, which may mean Chrome considers it untrusted.

#### Reference

- http://www.w3.org/TR/cors/#preflight-request
- http://stackoverflow.com/questions/20671619/angularjs-options-preflight-call-preceding-a-http-post-request
- https://github.com/WP-API/OAuth1
- https://wp-oauth.com/
