### ISSUE TITLE
How to get post meta for not logged in user using AngularJs

### ISSUE THREAD

**Issue by psychocoding** [WP-API/WP-API#1094]
var config = {headers : {'X-WP-Nonce': wpAPIData.nonce}}
		$http.get('wp-json/posts/' + $scope.post[0].ID + '/meta',config).success(function(res){
			$scope.post.meta = res;
		});

But the above code works if user is logged in, I need to fetch post meta type irrespective of user access.

**Comment by royboy789** [comment]
You'd need to bypass the authentication, you can either create a custom route & endpoint, or try tapping into the `json_authentication_errors` filter

**Comment by danielbachhuber** [comment]
Or, you can filter the metadata on to the response object. All of these approaches will require code-level access to the API, however.
