### ISSUE TITLE
Post thumbnail error

### ISSUE THREAD

**Issue by garikmmm** [WP-API/WP-API#1099]
When sending PUT request to /wp-json/posts/{{post id}} with {"featured_image": {{media_id}} }, API response is "Internal server error 500". The problem is that wp-content/plugins/json-rest-api/lib/class-wp-json-media.php on line 437 assumes that $thumbnail is a PHP array, but it is an instance of WP_JSON_Response.

error log details are: 
PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0
PHP Fatal error:  Cannot use object of type WP_JSON_Response as array in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/json-rest-api/lib/class-wp-json-media.php on line 437

My plugin version is: '1.2.1'
PHP version is: 5.6.2
Apache: 2.2.29

**Comment by danielbachhuber** [comment]
Thanks for the report — we'll have this fixed in 1.2.2
