### ISSUE TITLE
Password protected posts innaccessible to authenticated users who should have access

### ISSUE THREAD

**Issue by mnelson4** [WP-API/WP-API#1100]
I noticed today that password-protected posts can't be viewed by authenticated non-owners with the "read_private_posts" capability, even though they CAN view them in the wp admin (eg, user A has a password-protected post; user B has the "read_private_posts" capability and is logged in but cannot see that password protected post; even though user B can view it in the wp admin, and user B can also view their own password-protected posts via the API)

**Comment by danielbachhuber** [comment]
Let's discuss in #1055
