### ISSUE TITLE
Get Posts after Post with id xxx

### ISSUE THREAD

**Issue by putuyoga** [WP-API/WP-API#1101]
Hi, anyone have some clue how to get next post (no, i dont want using page query var) ? example i want get 10 post after a post with id xxx, how to achive that ? look at documentation for query variable on wp-api.org or codex wordpress, still have no clue. 

Thank you.

**Comment by swissspidy** [comment]
Not implemented yet, but there's an open issue for that: #783

**Comment by danielbachhuber** [comment]
@putuyoga Can you weigh in on #783 with more background on how you intend to use this? Thanks.
