### ISSUE TITLE
Assign a custom taxonomy term when creating a new post

### ISSUE THREAD

**Issue by federicovezzoli** [WP-API/WP-API#1102]
I know this has already been discussed in other topics, but I don't find a working solution.

I'm trying to set a custom taxonomy term to a new post.
The post saving is fine but the term is not saved.
Tried pretty much everything I could find, but nothing.

What is the current correct syntax for 1.2.1? 

thanks

**Comment by danielbachhuber** [comment]
> What is the current correct syntax for 1.2.1?

It's not supported in 1.2.1, and we won't be adding support in the 1.x branch.

**Comment by federicovezzoli** [comment]
Thanks! 
Solved using a hook.

**Comment by dleeward** [comment]
@federicovezzoli Mind sharing how you solved this?

**Comment by federicovezzoli** [comment]
I've used this hook:

```
function wp_api_add_tax($post, $data, $update){

    foreach( $data['custom_tax'] as $tax => $val ){
        wp_set_post_terms( $post['ID'], $val, 'custom_tax' );
    }
}
add_filter('json_insert_post', 'wp_api_add_tax', 10, 3);
```

try play around passing some data in that value, the data needs to be in an array too, otherwise the api removes the values.
