### ISSUE TITLE
Restrict Comment Author private details from being exposed

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#1114]
In #1103 Comment author email addresses, IP addresses, and User Agent are publically exposed.  Those details cannot be returned without a permission check.

**Comment by danielbachhuber** [comment]
> Comment author email addresses, IP addresses, and User Agent are publically exposed.

Are you sure? The fields are filtered off the object based on defined context, and there's test coverage for it

**Comment by danielbachhuber** [comment]
https://github.com/WP-API/WP-API/blob/develop/tests/test-json-comments-controller.php#L443

**Comment by rachelbaker** [comment]
Doh. I missed that. Thanks for the clarification @danielbachhuber
