### ISSUE TITLE
Bump WP REST API version to 2.0 Beta 1

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#1118]
Placeholder issue for the v2.0 Beta 1 version changes.

**Comment by Shelob9** [comment]
@rachelbaker Is there a reason why the develop branch hasn't been set to 2.0 alpha. It's confusing that develop is 1.1.1, while master is 1.1.2, but develop is the version 2 branch. More practically speaking, I can't do a version compare properly on `JSON_API_VERSION` now.

**Comment by danielbachhuber** [comment]
> Is there a reason why the develop branch hasn't been set to 2.0 alpha.

Nope. I'll fix for you #1137

**Comment by Shelob9** [comment]
@danielbachhuber Thanks for fixing this. I didn't know if I was misunderstanding something or if this was a simple oversight, but it makes things a lot more clear and version comparable.

**Comment by danielbachhuber** [comment]
> if this was a simple oversight

It was just an oversight ;)

**Comment by rachelbaker** [comment]
Closing since fixed in #1137

**Comment by danielbachhuber** [comment]
#1137 was `2.0-alpha`. We still need to bump when we hit `beta1`
