### ISSUE TITLE
json_authentication_errors filter not working

### ISSUE THREAD

**Issue by scottopolis** [WP-API/WP-API#1120]
I am using the `json_authentication_errors` filter to allow access to the API based on custom authentication. It was working with version 1.1, but appears to be ignored in 1.2.1.  Example:

    function checkApiAuth( $error ) {
    return true;
    }
    add_filter('json_authentication_errors', 'checkApiAuth');

That should allow unrestricted access to API endpoints, but I still receive an error: Sorry, you are not allowed to list users, or Sorry, you are not allowed to post on this site.

I've tested on 2 different sites, all running the latest API plugin and WordPress versions, with no conflicting plugins active.  Happy to provide more info if needed.

Thanks!

**Comment by ViktorPontinen** [comment]
Having the same issue that I have been trying to solve for day, glad to hear im not the only one. Using OAuth it seems like the authentication is working fine, but I am unable to create posts and list users amongst other things. I get an 503 Forbidden error. Just speculating here but it seems like the current_user_can() is somehow broken and is not passed to the api?

**Comment by ViktorPontinen** [comment]
Okay, the below code works without problems for me, so guess I just have some error in my OAuth configuration.

`function checkApiAuth( $error ) {
return true;
}
add_filter('json_authentication_errors', 'checkApiAuth');`

**Comment by rachelbaker** [comment]
@scottopolis What if you try to use the filter later (higher priority)?
```
function checkApiAuth( $error ) {
return true;
}
add_filter('json_authentication_errors', 'checkApiAuth', 99);
```

**Comment by scottopolis** [comment]
I guess this filter only works when already logged in, I was under the impression that it worked for logged out users.  If that's the case, then there is no issue, I just misunderstood.

**Comment by EkAndreas** [comment]
Just can't find any json_authentication_errors no more but there is a rest_authentication_errors ???

**Comment by bobdenardd** [comment]
Why was this issue closed? I mean at least you could give some explanation? From the documentation scattered in various places, it seems that this filter is the one being used for basic authentication, which would mean that it is supposed to work with log out users. Could you please at least just give us a clue about which filter to use when relying on custom authentication?

**Comment by joehoyle** [comment]
@bobdenardd this issue was closed by the reporter, remain calm :)

**Comment by rmccue** [comment]
The filter you want for v2 and WP4.4+ is `rest_authentication_errors`; see [the documentation](https://developer.wordpress.org/reference/hooks/rest_authentication_errors/) for how to use it.
