### ISSUE TITLE
Published date on posts

### ISSUE THREAD

**Issue by barclayadam** [WP-API/WP-API#1124]
Is it possible to include the date a post was actually published when retrieving posts through the /posts endpoint? We want to use this feature to show blog posts in-app by pulling through all published posts and then showing only those that have been published since the user last checked.

The modified and created dates are not quite right. Created because obviously that could be hours or days before actually publishing (therefore a user misses it) and modified because should a post be modified after publishing it would be shown as new again.

Thanks

**Comment by danielbachhuber** [comment]
The `date` field represents `date-time` for when the post was published. Why do you think this is the "created" date?

**Comment by barclayadam** [comment]
I think after having another look this may be an oddity with a post in particular that I have been looking at. 

I had set a schedule for a post to go out yesterday (20th April) but I had not actually hit 'Publish' until this morning. The `date` field shows the scheduled date, even though the post technically only went live today. Obviously not all too common but I've already done it so sure others would :)

Is this something the API is able to take care of, or is this actually an internal WordPress thing?

**Comment by danielbachhuber** [comment]
> Is this something the API is able to take care of, or is this actually an internal WordPress thing?

On the `master` branch, scheduled posts are represented as `publish`: https://github.com/WP-API/WP-API/blob/master/lib/class-wp-json-posts.php#L617

We've fixed this behavior on `develop`.

**Comment by barclayadam** [comment]
OK so that is actually a different problem, I think? That would also have broken our integration, although is not too bad for now. Any idea when that would be pushed out as a new version?

In our case, for the following scenario, what would the API use as the `date` field?

 * Post is scheduled for publishing `2015-04-20 10:30'
 * `Publish` button in admin UI pressed at `2015-04-21 11:00` (i.e. the next day)

Logically the publish date, from the end-user perspective, would be `2015-04-21 11:00` as that is when the post actually became live. In the `develop` branch (https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-json-posts-controller.php#L921), `$post->post_date_gmt` is used. I do not know the API enough to understand what this would be.

**Comment by danielbachhuber** [comment]
> Logically the publish date, from the end-user perspective, would be 2015-04-21 11:00 as that is when the post actually became live.

In the backend, what is the date you see when you've hit "Publish" on a scheduled post?

> In the develop branch (https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-json-posts-controller.php#L921), $post->post_date_gmt is used.

It actually defers to `$post->post_date` when the second argument is passed. `post_date` is the public-facing published date.

**Comment by barclayadam** [comment]
It shows `2015-04-20` which to me seems incorrect. I'm assuming this would be the date you would be retrieving from WordPress for the API? 

Is this potentially a issue in WordPress itself? Or maybe it is not common enough to even be considered a problem?

**Comment by danielbachhuber** [comment]
> It shows 2015-04-20 which to me seems incorrect. I'm assuming this would be the date you would be retrieving from WordPress for the API?

Right.

> Is this potentially a issue in WordPress itself?

Yep, I think so. It's not anything we can fix within WP-API, at the least. I did some searching in Core Trac and didn't find a specific ticket for this but, [as you can see](https://core.trac.wordpress.org/search?q=scheduled+publish+date&noquickjump=1&changeset=on&ticket=on), there are a number of hard, conceptual UX problems with scheduled posts.

**Comment by barclayadam** [comment]
Thanks for the help and doing some digging! I decided to post a new issue over at Core Trac, https://core.trac.wordpress.org/ticket/32039
