### ISSUE TITLE
Retrieve all the categories

### ISSUE THREAD

**Issue by clarenced** [WP-API/WP-API#1126]
Based on the documentation, the url to retrieve all the categories is : `http://example.com/wp-json/wp/terms/category`.

But for an unknown reason, the json returned contains only 10 categories. I have more categories in my blog. I want to retrieve all of them. How to do it? 

I don't know if this is an issue, but can anyone point to the right direction. I am still a newbie with this API.

**Comment by danielbachhuber** [comment]
@clarenced to clarify, you're using `develop` branch?

**Comment by clarenced** [comment]
I am not really sure. I cloned the repository with `git clone git@github.com:WP-API/WP-API.git` and copied it in the `plugins` directory. The current version I am using is `1.1.1`.

**Comment by danielbachhuber** [comment]
Ok. You cloned `develop`, which isn't yet stable for your needs. You should install v1.2.1 via WordPress.org plugins repo

**Comment by danielbachhuber** [comment]
With v1.2.1, you can request like this: `GET /taxonomies/category/terms?count=100`

**Comment by clarenced** [comment]
Ok thx

**Comment by matthisamoto** [comment]
So will you be able to get all categories at some point? I feel like this is still an issue, why would it only serve a max of ten?
