### ISSUE TITLE
Can we get the requests by slug instead of post id too ?

### ISSUE THREAD

**Issue by heldrida** [WP-API/WP-API#1130]
Hi, 

I'm wondering if you guys could extend this to include requesting data using the slug ? That would be great.

**Comment by nCrafts** [comment]
I think this would work:
`http://example.com/wp-json/posts?filter[name]=my-post-slug`

**Comment by heldrida** [comment]
I'm actually fine about how this works, but I've suggested a restful api for this client and the dev asked about this feature. The Post ID is immutable and the slug may change, so to be honest I'd stick with the first one. I'll have a look on the docs about the filter! Thanks dude!

**Comment by danielbachhuber** [comment]
> The Post ID is immutable and the slug may change, so to be honest I'd stick with the first one.

Exactly. See conversation in #642
