### ISSUE TITLE
Consider JSON API for formatting our responses

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1136]
It's the newest kid on the block, and [already has a good set of implementations](http://jsonapi.org/implementations/). Check out the [FAQ](http://jsonapi.org/faq/) for how it distinguishes itself from HAL.

Given our pain adding links to collections, we should consider JSON API spec.

**Comment by kadamwhite** [comment]
I've voiced support for this before, I believe&mdash;we've been getting a lot of mileage out of JSON API in our projects

**Comment by danielbachhuber** [comment]
Our consideration is no, but keep in mind for the future.

**Comment by boazsender** [comment]
I'm excited to see JSON-API considered here! Why is the consideration no for now @danielbachhuber? Is there another standard JSON data format that you are considering for WP-API?

**Comment by danielbachhuber** [comment]
> Why is the consideration no for now

There are parts of the JSON-API spec that contradict our current needs. Furthermore, it's not clear that JSON-API offers a significant advantage should we adopt it.

> Is there another standard JSON data format that you are considering for WP-API?

Nope.
