### ISSUE TITLE
Audit link relations

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#1139]
Links were always intended to follow the [IANA link relations registry](http://www.iana.org/assignments/link-relations/link-relations.xhtml#link-relations-1), but we accidentally broke this in v2 by using taxonomy slugs directly as relations.

Let's fix these up, and also rethink our approach. Rather than using custom link relations, we can restructure to match the way that Atom/RSS/etc feed discovery works by including a `type` parameter.

For example, rather than `Link: <.../meta>; rel=<http://wp-api.org/2.0/meta>`, we can do `Link: <.../meta>; rel=related; type=<http://wp-api.org/2.0/meta>`

Old-style in JSON:
```json
{
    "_links": {
        "http://wp-api.org/2.0/meta": [ {
            "href": ".../meta",
        } ]
    }
}
```

New-style in JSON:
```json
{
    "_links": {
        "related": [ {
            "href": ".../meta",
            "type": "http://wp-api.org/2.0/meta",
        } ]
    }
}
```

This should make indexing into it easier (`_links.related[0].href`), and allows us to be more flexible too. For example, something like Pods could also expose `Link: <.../pods/42/fields>; rel=related; type=<http://pods.io/1.0/fields/>` and have it grouped alongside.

(Props @rachelbaker for inspiring this.)

**Comment by rmccue** [comment]
While we're at it, we should also link to the relevant schema with `rel=profile`

**Comment by danielbachhuber** [comment]
:+1: The more we can do to clarify `_links`, the better.
