### ISSUE TITLE
Contexts for schema fields breaks embedding

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#1140]
Over in #1046, we changed to filtering the fields automatically based on the schema. However, as it turns out, this breaks embedding, which uses `context=embed`.

Should we just use `context=view` instead?

**Comment by danielbachhuber** [comment]
> Should we just use context=view instead?

Could. I think we should discuss what the appropriate paradigm should be for developers to use arbitrary / non-core contexts (e.g. I want to create my own custom context for some use).

**Comment by rmccue** [comment]
#1284 adds a bunch of data to the embed context. I'm in favour of keeping these separate so we can reduce the amount of data returned when auto-embedding from another endpoint.
