### ISSUE TITLE
Consider collapsing Meta controllers into one class

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1144]
From https://github.com/WP-API/WP-API/pull/960#issuecomment-96655335

To discuss when we add Comment and User meta.

**Comment by rachelbaker** [comment]
Punted due to dependencies on other meta support

**Comment by rmccue** [comment]
Talked about this briefly; the benefits of having these in separate classes outweighs the problems with having 4+ classes. In particular, allowing plugins to subclass and steal this code for custom table is useful.
