### ISSUE TITLE
Correct phpDoc for WP_JSON_Controller

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#1145]
There's a few things in here right now that are annoying Scrutinizer as well as my autocomplete in my editor:

* `@return mixed WP_Error or WP_JSON_Response.` uses an incorrect expression for types, this should be `WP_JSON_Response|WP_Error`
* `get_item`, `create_item`, `update_item`, `delete_item` are missing param/return doc
* `@return mixed WP_Error|bool.` shouldn't have the trailing dot (only needed with a description)

**Comment by joehoyle** [comment]
Fixed
