### ISSUE TITLE
Featured image in /posts as link instead of ID

### ISSUE THREAD

**Issue by ViktorPontinen** [WP-API/WP-API#1147]
Hi,

Would it be possible to somehow change the 'featured image' in /posts to output link to media instead of ID?
Or even better, be able to chose what image size 'featured image' will link to with a parameter or header value in the GET request.

Otherwise a lot of requests needs to be done to render a full page of posts with respective featured image. 
Same thing goes with the 'author', to output username or name instead of ID.

Or maybe I am missing something?

**Comment by danielbachhuber** [comment]
> Would it be possible to somehow change the 'featured image' in /posts to output link to media instead of ID?

It's possible, but not recommended.

On the latest version of the plugin, v1.2.1, you can use the `json_prepare_post` filter ([ref](https://github.com/WP-API/WP-API/blob/master/lib/class-wp-json-posts.php#L691)) to add the data you want.

On `develop` and in 2.0, our recommendation will be for you to navigate the `_links` on the object to access all of the data.

Keep an eye on http://v2.wp-api.org for some documentation coming soon.

**Comment by ViktorPontinen** [comment]
Thanks! Will try that.

**Comment by malfborger** [comment]
wouldn't that result in an extra http request @danielbachhuber ? wouldn't it be smarter to attach, in this case, the image object directly with width , src etc.
