### ISSUE TITLE
get_adjacent_post as a query?

### ISSUE THREAD

**Issue by denitto** [WP-API/WP-API#1155]
Any way to replicate the functionality of the wordpress function: [`get_adjacent_post`](https://codex.wordpress.org/Function_Reference/get_adjacent_post) currently?  It would be sweet to have this feature for navigation from single.

**Comment by rmccue** [comment]
Thanks for filing this issue! We already have this filed over on #783. :)

**Comment by denitto** [comment]
Thanks @rmccue!  didn't see it when I searched.  I'm going to try @petitphp's solution.
