### ISSUE TITLE
Wouldn't it make sense to combine error msg for invalid_params & missing_required params ? 

### ISSUE THREAD

**Issue by quasel** [WP-API/WP-API#1159]
@WP_REST_Request related to #1131

- because missing is the worst form of an invalid $args
- and maybe not only return a string but additonally an array of the errors? 
e.g.
```
'args' => 'error_msg',
'args' => 'error_msg'
```
thinking of an form is sent and you can display the errors accordingly - assuming no client side validation done or not possible (needs server side checks)

**Comment by danielbachhuber** [comment]
@joehoyle is a good person to comment on this.

**Comment by joehoyle** [comment]
This is on the list in https://github.com/WP-API/WP-API/issues/1143

**Comment by quasel** [comment]
ups did miss that - does this include the combination of missing&invalid ?

**Comment by joehoyle** [comment]
yeah - though not explicitly states. Thanks for flagging though
