### ISSUE TITLE
"The plugin does not have a valid header." during activation

### ISSUE THREAD

**Issue by beaulebens** [WP-API/WP-API#1161]
When attempting to activate the 2.0-beta1 on a copy of trunk, the first thing I get is the message

"The plugin does not have a valid header."

via a `wp_die()`. I got it specifically when I uploaded the plugin as a zip (using the release zip directly from Github).

After that failed, I went back to the Plugins page and clicked activate and it worked fine.

**Comment by rachelbaker** [comment]
This is caused by the `tests/helper.php` file.  Same issue as #1020, we need to remove the plugin header from this file, or remove the file completely.

Thanks for the bug report @beaulebens

**Comment by rachelbaker** [comment]
Assigning to @rmccue to resolve since it is his testing helper.

**Comment by michaelbeil** [comment]
Couldn't this be done by simply adding `test` to the .gitignore? https://github.com/WP-API/WP-API/blob/develop/.gitignore

**Comment by rmccue** [comment]
We want tests to continue to be checked in, but the test helper has turned out to be more pain than it's worth. We can just remove it.
