### ISSUE TITLE
Filter by custom tag returns 0 result

### ISSUE THREAD

**Issue by GGno** [WP-API/WP-API#1163]
Hi,
if i try to get post with certain custom tag (eg: "?json_route=/posts&type=messaggi&filter[tag]=myValue") it returns no result.
I tried also with "?json_route=/posts&type=messaggi&filter[myTagSlug]=myValue" but with no success.

Am i doing wrong ot this is an issue?

Thank you.

**Comment by quasel** [comment]
wich Version of WP-REST-API do you use?, does it wokr without the filter, ...

**Comment by GGno** [comment]
I'm using the 1.2.1, and yes, it works in many other queries.
