### ISSUE TITLE
Always 404 on Multisite

### ISSUE THREAD

**Issue by bueltge** [WP-API/WP-API#1164]
The current develop branch create only 404 on requests, if is active in a multisite installation. I tested if is network wide active and also single activation, only one site in the network. The same installs and scenarios works with the master branch.

`/wp-json/posts/`create this result: 

```json
[
    {
        "code": "rest_no_route",
        "message": "No route was found matching the URL and request method",
        "data": {
            "status": 404
        }
    }
]
```

I have also update the permalinks after each switch for test this.
WordPress version is 4.3-alpha-32329, update from github version.
PHP Version: PHPv 5.5.9-1ubuntu4.9

**Comment by danielbachhuber** [comment]
The new route is `/wp-json/wp/v2/posts`

**Comment by bueltge** [comment]
Will you leave this after release or switch back to default path?

**Comment by danielbachhuber** [comment]
> Will you leave this after release or switch back to default path?

The path will likely switch when the plugin is integrated into core, but all paths will be prefixed from this point forward.

**Comment by bueltge** [comment]
Thanks for the answer. Is the prefix `wp-json` not enough? Which goal is the string `wp` inside this path?

**Comment by rmccue** [comment]
The `wp` is the route namespace, so `wp` is for the core routes that we bundle. Something like Jetpack e.g. would use `/wp-json/jetpack/v3/...` instead

**Comment by bueltge** [comment]
Thanks a lot, now is understanding from my side.
