### ISSUE TITLE
Request Was Redirected Error

### ISSUE THREAD

**Issue by hyyan** [WP-API/WP-API#1165]
I am using [Basic-Auth](https://github.com/WP-API/Basic-Auth) plugin to login to my development server , But I keep getting the following error in chrome : 

```
 XMLHttpRequest cannot load http://testo.localhost.com/wp-json/users/me?context=edit. The request was redirected to 'http://testo.localhost.com/wp-json/users/1', which is disallowed for cross-origin requests that require preflight.
```

The problem seems to be related to the following PR https://github.com/WP-API/WP-API/pull/493 , I commented on that but I've got no response , and I opened an issue [Here](https://github.com/WP-API/Basic-Auth/issues/16) put also with no response .

Any idea will be helpfull , Thanks in advance

**Comment by danielbachhuber** [comment]
See discussion in #1093. You should just make the request directly to `http://testo.localhost.com/wp-json/users/1` if you can't figure out the necessary server-side configurations

**Comment by rmccue** [comment]
Note: you can also pass `_envelope` to always get back a 200 response, which will let you parse out redirects/etc yourself.
