### ISSUE TITLE
Rename camelCase functions to adhere to coding standards

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1169]
`WP_REST_Request` has some camelCase methods:

* `offsetExists()`
* `offsetGet()`
* `offsetSet()`
* `offsetUnset()`

For now, I've skipped them from our automated code sniffing in 7d3ed6a. They were added in 24c7383d3b4425fa0bcb812a9e472d789b2fe44a.

@rmccue Why did you camelCase these methods? Can we rename them?

**Comment by danielbachhuber** [comment]
24a8a38 is also relevant

**Comment by rmccue** [comment]
These are the method names for the [ArrayAccess](http://php.net/arrayaccess) interface in PHP core, which we use for the `$request['some_param']` handling, so we can't change them. Ditto [jsonSerialize](http://php.net/jsonserializable).

Ignoring them is the best option here which you already addressed, so closing this ticket.
