### ISSUE TITLE
Decide upon "endpoints" or "routes"

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1172]
We're using "endpoints" and "routes" interchangeably within our codebase and documentation. We should standardize on one.

**Comment by rmccue** [comment]
As noted on http://wp-api.org/guides/extending.html#designing-your-routes-and-endpoints they're two different things. Routes correspond to a URL, endpoints correspond to a callback. For example, `/wp/posts/<id>` is a single route, with 3 endpoints for GET, PUT and DELETE.

**Comment by danielbachhuber** [comment]
> they're two different things.

Ah, I wasn't aware of the distinction. I'll make sure our new documentation reflects this as well.

**Comment by rmccue** [comment]
This is now clarified in the glossary: http://v2.wp-api.org/glossary.html
