### ISSUE TITLE
Possible to hook custom endpoints as plugins?

### ISSUE THREAD

**Issue by ViktorPontinen** [WP-API/WP-API#1179]
Hello,

Finally made some progress on creating a custom endpoint but has so far only created internally.
Is it possible to create custom endpoints as separate plugins and hook to the WP_Rest_Controller or is something more needed?

```
class WP_REST_Custom_Controller extends WP_REST_Controller {
           public function register_routes(){
           }
           /**
            * Etc etc..
            */
}
```

Also, is the get_item_schema() required for it to work properly or simply just recommended?

**Comment by swissspidy** [comment]
Have a look at [the guides](http://wp-api.org/guides/extending.html) on how to register your own routes. I don't think you need to extend `WP_REST_Controller`. I always used the `json_endpoints` filter just like in the examples.

**Comment by danielbachhuber** [comment]
> Have a look at the guides on how to register your own routes.

The existing guides are for v1.x, and incorrect for v2.x.

> Is it possible to create custom endpoints as separate plugins and hook to the WP_Rest_Controller or is something more needed?

We need to write a bit of documentation on the "proper" way to register your own endpoints. Follow along on https://github.com/WP-API/docs-v2/issues/4
