### ISSUE TITLE
'/types' with edit context returns list of types with unprivileged request.

### ISSUE THREAD

**Issue by sanghviharshit** [WP-API/WP-API#1183]
It should return no data/ error when edit context is used by unprivileged user.

**Comment by sanghviharshit** [comment]
https://github.com/WP-API/WP-API/issues/702#issuecomment-66400990
> Additionally, right now setting context either succeeds (returns all data for that context) or fails (returns no data/an error), which is kind of nice in that you immediately know if you can't access the data. Returning a subset of data if you don't have full permissions means you can't necessarily be sure if there's more data to access.

**Comment by danielbachhuber** [comment]
Here's our current response:

```
local ➜  wordpress-develop.dev git:(master) http GET wordpress-develop.dev/wp-json/wp/v2/types context==edit --body
{
    "attachment": [],
    "page": [],
    "post": []
}
```

The objects are empty because of #1796. We need to resolve that issue.

We should also consider limiting fields present in `view` context to frontend, and requiring authentication for `edit` context fields.

**Comment by danielbachhuber** [comment]
Lastly, we should consider whether we include `rest_base` in the response.
