### ISSUE TITLE
'/taxonomies' response for edit/ embed context returns inconsistent response for unprivileged access

### ISSUE THREAD

**Issue by sanghviharshit** [WP-API/WP-API#1185]
https://github.com/WP-API/WP-API/issues/702#issuecomment-66400990
> Additionally, right now setting context either succeeds (returns all data for that context) or fails (returns no data/an error), which is kind of nice in that you immediately know if you can't access the data. Returning a subset of data if you don't have full permissions means you can't necessarily be sure if there's more data to access.

It should either return no data or error for consistency.

**Comment by sanghviharshit** [comment]
As of now, it returns a list of blank items which totals to actual number of taxonomies if the user was authenticated. e.g. It returns this [[],[],[],[],[],[]] if there were 6 taxonomy items on the site.

**Comment by danielbachhuber** [comment]
Same as https://github.com/WP-API/WP-API/issues/1183#issuecomment-162946347

The objects are empty because of #1796. We need to resolve that issue.

We should also consider limiting fields present in `view` context to frontend, and requiring authentication for `edit` context fields.

**Comment by danielbachhuber** [comment]
`view` will be everything but labels, and `edit` will require corresponding taxonomy capability.
