### ISSUE TITLE
Readme in master needs changes

### ISSUE THREAD

**Issue by sanghviharshit** [WP-API/WP-API#1187]
Simply following the quick setup and testing instructions from http://wp-api.org/ doesn't work.

**Comment by danielbachhuber** [comment]
What specifically doesn't work?

**Comment by sanghviharshit** [comment]
step-3 in Testing fails with the following error:
```
x$ vagrant ssh -c 'cd /vagrant/content/plugins/json-rest-api && phpunit'
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
Not running ajax tests... To execute these, use --group ajax.
PHPUnit 4.6.6 by Sebastian Bergmann and contributors.

Configuration read from /vagrant/content/plugins/json-rest-api/phpunit.xml.dist

.........................F.....S...............................  63 / 340 ( 18%)
.....S......................................................... 126 / 340 ( 37%)
.....F...F.........................F...............PHP Fatal error:  Call to undefined method WP_Test_REST_Posts_Controller::remove_added_uploads() in /vagrant/content/plugins/json-rest-api/tests/test-rest-posts-controller.php on line 942

Fatal error: Call to undefined method WP_Test_REST_Posts_Controller::remove_added_uploads() in /vagrant/content/plugins/json-rest-api/tests/test-rest-posts-controller.php on line 942
Connection to 127.0.0.1 closed.

```

**Comment by sanghviharshit** [comment]
The Chassis extension for testing has submodule wpdevel from [WordPress Git mirror](https://make.wordpress.org/core/2014/01/15/git-mirrors-for-wordpress/) which is outdated and that submodule needs to be updated (pulled to latest on master from git://develop.git.wordpress.org/)

**Comment by danielbachhuber** [comment]
@sanghviharshit Can you submit a PR to Chassis then?

**Comment by sanghviharshit** [comment]
`remove_added_uploads()` was introduced in 4.0.0 (See https://core.trac.wordpress.org/changeset/29120).

WP-API supports 3.9 and higher. Shouldn't we update the test-cases in phpunit for compatibility with 3.9?

**Comment by sanghviharshit** [comment]
I have created a pull request to update the instructions to pull to latest for wpdevel submodule.
But to make a note: using `remove_added_uploads()` in testcases makes it incompatible with 3.9.
