### ISSUE TITLE
Taxonomy term `parent` should be term taxonomy id

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1190]
Because we're doing all term references by term taxonomy id, our `parent` reference should be translated to and from as term taxonomy id, not term id.

Discovered in #1189

**Comment by joehoyle** [comment]
@danielbachhuber did this get fixed already? I'm looking through the code and it appears to already be doing this.

**Comment by danielbachhuber** [comment]
> did this get fixed already? I'm looking through the code and it appears to already be doing this.

Derp :) #wontfix
