### ISSUE TITLE
Don't link `author` when `author=0`

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1192]
![image](https://cloud.githubusercontent.com/assets/36432/7499535/297dbd16-f3dd-11e4-9095-099df32b8d96.png)

**Comment by danielbachhuber** [comment]
@rachelbaker Looks like you added the tests for this in 3159cd855b895169a0e65ea2d14dba287a753f72. What was your thinking?

**Comment by rachelbaker** [comment]
>>> Looks like you added the tests for this in 3159cd8. What was your thinking?

@danielbachhuber I didn't consider the author having an id of 0.
