### ISSUE TITLE
Nullify values when the value is 0 in the database

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1193]
We're already doing this for `parent`, but we aren't doing it for some other fields:

![image](https://cloud.githubusercontent.com/assets/36432/7499583/8e0eb438-f3dd-11e4-8fd5-76b491e79b9d.png)

We should be consistent about this.

**Comment by rachelbaker** [comment]
I agree that we should be consistent.  I would rather go the other direction and return `0` for parent instead of `null`.  This would make our return types consistent and make responses easier to handle in statically typed languages.

**Comment by rachelbaker** [comment]
Discussion in Slack: https://wordpress.slack.com/archives/core-restapi/p1431559236000326
