### ISSUE TITLE
Custom Post Types Not Filtering

### ISSUE THREAD

**Issue by sotoole** [WP-API/WP-API#1195]
Using **WP-API (v1)** I could filter the posts returned by a post type. 

**Example Request:**
http://www.mysite.com/wp-json/posts?type=my_custom_post_type
**Returns:**
Posts only in "my_custom_post_type" as expected.

Using **WP-API (v2 beta 1)** this doesn't seem to work (even if authenticated with OAuth). I've tried all these with and without OAuth (using Postman):

**Example Requests:**
http://www.mysite.com/wp-json/wp/v2/posts?type=my_custom_post_type
http://www.mysite.com/wp-json/wp/v2/posts?type[]=my_custom_post_type
http://www.mysite.com/wp-json/wp/v2/posts?post_type=my_custom_post_type
http://www.mysite.com/wp-json/wp/v2/posts?filter[type]=my_custom_post_type
http://www.mysite.com/wp-json/wp/v2/posts?filter[post_type]=my_custom_post_type
**Returns:**
All posts with type "post". No posts returned with "my_custom_post_type" or any other post type.

I believe I have OAuth working correctly because I can create new Posts, no problem. Also I can make filtering work for other items like "author". So I suspect my problem is related to post type specifically.

Is anyone else having this issue? If it's working for you did you use OAuth and could you provide an example URL for your request?

**Comment by danielbachhuber** [comment]
On `develop`, you need to have your custom post type opt-in to being present in the API with `show_in_rest=true`. See this example: https://github.com/WP-API/WP-API/blob/develop/plugin.php#L113

By default, your custom post type will be available from `http://www.mysite.com/wp-json/wp/v2/my_custom_post_type`. You can change the base with the `rest_base` argument.

We'll make sure this is captured in the documentation: https://github.com/WP-API/docs-v2/issues/4

**Comment by scottopolis** [comment]
@danielbachhuber so all custom post types are hidden from the API by default now? Developers are going to be slow to update this in their plugins and custom code, which means we won't be able to use their content in a mobile app. This is a pretty big barrier to widespread usage of the API IMO.

Is this something that's open for discussion?

**Comment by jeffikus** [comment]
@scottopolis I think the opt in approach is right here, but, @danielbachhuber would it not make sense for the default setting for 'show_in_rest' be a double check for the 'public' and  'exclude_from_search' settings in register_post_type? That way it could be opt in by intention for existing plugins. I know I really don't want some existing post types in some of our older themes suddenly becoming available by the REST API. That would suck for customers :(

**Comment by scottopolis** [comment]
I guess I can see that, it will just be a pain until plugin authors update their code, which could take a while.
