### ISSUE TITLE
Native Wordpress Functions and Cookie Authentications

### ISSUE THREAD

**Issue by saturday** [WP-API/WP-API#1198]
When testing the cookie authentication method I found it strange that some native Wordpress functions weren't behaving as expected. For example, it's possible to check if the authenticated user has certain capabilities via `current_user_can()`, however I'm not able to `get_userdata()`.

Similarly, `is_admin()` does not work as expected either. 

Why is this?

**Comment by rmccue** [comment]
These should all work normally. Make sure that you're sending the nonce with API requests, as otherwise cookie authentication won't work.

Also, important note: `is_admin()` does not check if the user is an admin, it checks if the visitor is viewing the admin screens (i.e. the dashboard).

**Comment by saturday** [comment]
I'm passing the nonce via the X-WP-Nonce header, and it's working. However, the issue remains. The user is viewing the dashboard (a custom plugin), and `is_admin()` returns false. `get_current_user()` returns an empty string. As mentioned `current_user_can()` works as expected.

**Comment by danielbachhuber** [comment]
> is_admin() returns false

This is intended.

> get_current_user() returns an empty string.

Just to confirm, the WordPress function is `wp_get_current_user()`. `get_current_user()` is something else entirely: http://php.net/manual/en/function.get-current-user.php

**Comment by saturday** [comment]
You're absolutely right. That's the brain fart of the week for me. As an aside, I'm enjoying the plugin so far.

**Comment by danielbachhuber** [comment]
> That's the brain fart of the week for me.

No worries, happens to the best of us.

> As an aside, I'm enjoying the plugin so far.

Glad to hear! As you find aspects that could benefit from documentation, please [make sure to open an issue in our docs repo](https://github.com/WP-API/docs-v2/issues)
