### ISSUE TITLE
add data to posts

### ISSUE THREAD

**Issue by OJayRobinson** [WP-API/WP-API#1201]
I cannot find documentation on how to add data that will be retrieved by [posts](http://wp-api.org/#posts_retrieve-posts).  When adding fields to a post with something like [Custom Field Suite](http://customfieldsuite.com/) I would have expected this data to be attached to posts by default.

I've added an [issue](https://github.com/mgibbs189/custom-field-suite/issues/266) to CFS as well.

Any help is appretiated, thanks.

**Comment by danielbachhuber** [comment]
We'll have this documented for v2 in https://github.com/WP-API/docs-v2/issues/4

For v1.x, you can use the `json_prepare_post` filter: https://github.com/WP-API/WP-API/blob/master/lib/class-wp-json-posts.php#L691

**Comment by OJayRobinson** [comment]
Hi Daniel, thanks for the quick response.

I'm unclear how to apply the json_prepare_post filter.  Is there related documentation or a functional example I could dig into?

**Comment by danielbachhuber** [comment]
> Is there related documentation or a functional example I could dig into?

https://css-tricks.com/using-the-wp-api-to-fetch-posts/

**Comment by OJayRobinson** [comment]
awesome thanks!
