### ISSUE TITLE
Resolve potential conflict in object type names

### ISSUE THREAD

**Issue by joehoyle** [WP-API/WP-API#1202]
Currently we have object types for all post types, comment types, taxonomies. These are not namespaced, any same named object type (for example a taxonomy called "page") will collide with `rest_prepare_page` hooks, the object type show in the schema, and the Additional Fields API.

I propose we namespace accordingly, e.g. `rest_prepare_post-page`, `rest_prepare_taxonomy-page`.

**Comment by danielbachhuber** [comment]
We can punt this to beta3 because it's not an immediate problem.

**Comment by rachelbaker** [comment]
Punted to Beta 4

**Comment by danielbachhuber** [comment]
Related #829

**Comment by danielbachhuber** [comment]
I came across some prior art for this the other day. If you register a CPT with query var 'foo' and a taxonomy with query var 'foo':

1. Both register rewrite rules which match to `foo=$matches[1]` (and subsequently interpreted by WP_Query as such). I'm not sure which would take priority.
2. Both apply a `foo_rewrite_rules` filter when generating rewrite rules.

In short, core doesn't disambiguate between colliding CPTs and taxonomies, so I don't think we need to either.

**Comment by joehoyle** [comment]
Given that core doesn't support well this scenario, I don't think we need to worry about it.

**Comment by userabuser** [comment]
@danielbachhuber @rmccue 

Why wouldn't we want to disambiguate? 

I came across this issue today whilst preparing responses for both taxonomies and post types.

It's clear as day that this is a collision problem waiting to happen, where one person's filter effects that of another object type unbeknown to the developer.

I don't see why we'd want to perpetuate bad form from core within the REST API.

Am I missing something?

**PS. was this actually punted to Beta 4 or thrown away as wont fix?**

Regards,
Adam

**Comment by danielbachhuber** [comment]
> Why wouldn't we want to disambiguate?

Because core doesn't, so it's not necessarily for us to.

> I came across this issue today whilst preparing responses for both taxonomies and post types.
> 
> It's clear as day that this is a collision problem waiting to happen, where one person's filter effects that of another object type unbeknown to the developer.

Right, and this is a problem with core too, so fixing it for the REST API won't fix it generally.

> PS. was this actually punted to Beta 4 or thrown away as wont fix?

This is wontfix.

**Comment by userabuser** [comment]
@danielbachhuber 

> Because core doesn't, so it's not necessarily for us to.

Collisions in core is one thing, filtering in context is another.

So while core wont fix (or cant due to BC) collisions, it doesn't mean the REST API needs to perpetuate the confusion.

Thanks anyway...
