### ISSUE TITLE
Comments and Terms controllers should use get_endpoint_args_for_item_schema()

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1205]
They don't yet.

Related #1135

**Comment by rachelbaker** [comment]
I will pick this one up.

**Comment by rachelbaker** [comment]
I will wrap this one up tonight for Beta 2.

**Comment by rachelbaker** [comment]
After looking more into the Comments endpoints I feel like setting the endpoint_args_from_schema is too rigid.  

1. We cannot set a default value on create.  (Which means for other endpoints where we use this method we don't set defaults).  
2. Inability to separate out create vs update arguments.  Example: you cannot set the comment `status` on create, but you can on update.  Another example: `you can set the comment `type` on create, but you cannot change it on update.  
3. Inability to set specific string sanitization like `wp_filter_post_kses` in the schema.

I thought about adding `sanitize_callback` directly into the schema but that seems very *un*schema-like.  

Some discussion @joehoyle and I had on this: https://github.com/WP-API/WP-API/pull/1245/files#r30509829

Leaving this open if someone else wants to jump in here.

**Comment by danielbachhuber** [comment]
> Example: you cannot set the comment status on create, but you can on update.

Why can't you?

**Comment by rachelbaker** [comment]
Punted to Beta 4

**Comment by rachelbaker** [comment]
Done in #1399 and #1422
