### ISSUE TITLE
Posts with pages issue with rendered content

### ISSUE THREAD

**Issue by peterigz** [WP-API/WP-API#1206]
This all refers to the posts controller.

If a post utilises the nextpage separator to paginate the post then currently you can't retrieve the content for those individual pages within the post using ?page=2. There's a couple of problems: When setup_postdata is used in the prepare_item_for_response function, the $wp_query global is not used to store the query, so some of the globals that setup_postdata sets such as $page are not set correctly (because it relies on retrieving the query vars) so the rendered content does not display properly.

Secondly, the rendered content doesn't use get_the_content to render it, so it will just render the full content of the post, rather then just the page you want.

The other issue is in the get_items function the page arg is unset and paged is used instead, but page is required as a query var to get the right page in the post.

**Comment by danielbachhuber** [comment]
Good catch. What would your _expected_ behavior be within the API? Full content in the response, or respect a `page` parameter?

**Comment by peterigz** [comment]
I think it should respect the page parameter, as it's easier to use a filter to get the whole content if you need, rather then the other way round which currently isn't possible as far as I can tell.

**Comment by rmccue** [comment]
We decided on this one that a `content.pages` should be added to contain a list of all rendered page contents. This will only show on `view` and `edit` contexts, not on `embed`. `content.rendered` will continue to be just the first page, similar to `the_content()`. `content.raw` already contains the full post content, so nothing to change there.

**Comment by danielbachhuber** [comment]
@WP-API/amigos I actually think #wontfix on this one, given we don't currently support `<!--more-->` in a similar fashion.

For reference, here's our current response:

```
salty-wordpress ➜  wp-rest-cli  wp rest post get 7 --user=daniel --fields=content --format=json | jq '.'
{
  "content": {
    "rendered": "<p>This is my first page</p>\n<p><!--nextpage--></p>\n<p>This is my second page</p>\n<p><!--nextpage--></p>\n<p>This is my third page</p>\n"
  }
}
```

`<!--nextpage-->` is present in the response, permitting the client to respect it if they wish.

**Comment by danielbachhuber** [comment]
> I actually think #wontfix on this one

Just to clarify, WordPress' current behavior is to return pagination HTML in the post content when `<!--nextpage-->` is present:

![image](https://cloud.githubusercontent.com/assets/36432/12889614/994da494-ce34-11e5-9d08-090e422a2081.png)

However, we can't return pagination HTML in our `content.rendered`, because the REST API has no understanding of how to implement pagination within the client.
