### ISSUE TITLE
Returns 404 on large queries. No timeout.

### ISSUE THREAD

**Issue by ezekg** [WP-API/WP-API#1208]
I just had a rather odd issue that caused us to have to rewrite the backend of our app. We were using the API to query user submitted posts via AJAX, but once we hit 67 posts the API no longer returned JSON and rather returned a 404 _response_ with HTML that contains every post on the site repeated. Literally, the page contains the HTML response for each post in the database all on a single page.

It responds with the 404 within just a couple seconds (so it can't be the standard 30 sec `max_execution_time` timing out). Is there a query length limit somewhere?

For example, requesting `http://site.com/wp-json/posts/?type=custom_type&filter[posts_per_page]=-1` responds with a 404 once we hit 67 posts, but querying just 66 would return the correct result (and rather quickly, like expected). We were hoping that this API could handle a large amount of posts (we're expecting ~500), so I'm kind of confused on why we're getting a 404 with no signs of a timeout.

##### Method being used to modify the return data to utilize Advanced Custom Fields:
```php
<?php
/**
 * Modify return fields for response so that we only get the data we need
 *
 * @see https://gist.github.com/rileypaulsen/9b4505cdd0ac88d5ef51
 */
add_filter( "json_prepare_post", function( $data, $post, $context ) {
  $_data = array(
    "date_tz" => $data["date_tz"],
    "date" => $data["date"],
    "link" => $data["link"]
  );

  if ( function_exists( "get_fields" ) ) {
    $_data["meta"] = @array_merge( $data["meta"], array(
      "afc" => (array) @get_fields( $post["ID"] )
    ));
  }

  return $_data;
}, 10, 3 );
```

##### Here's the site's relevant specs:
* WP version: 4.1.1
* WP-API Version: 1.2.1
* Advanced Custom Fields Pro Version: 5.2.3
* Custom Post Type UI Version: 1.0.7

Any idea on what the issue could be? Let me know if you need any more information.

**Comment by danielbachhuber** [comment]
> redirected to a 404 once we hit 67 posts

Which URL would it redirect to?

**Comment by ezekg** [comment]
The page doesn't redirect actually, sorry. Just now debugging everything thoroughly. I'll edit the above to clarify for everybody else. So, it looks like it's returning a 404 _response_ with a page that contains every post on the site repeated. Literally, the page contains the HTML response for each post in the database all on a single page.

**Comment by danielbachhuber** [comment]
> So, it looks like it's returning a 404 HTTP response (title says "Page not found") with HTML that contains every post on the site repeated. Literally, the page contains the HTML response for each post in the database all on a single page... but this only happens whenever you query over 66 posts.

Can you share an example of your request and the response in a gist? Also, just to confirm, this is with all plugins disabled, etc. ?

**Comment by ezekg** [comment]
Well, I've tried with as many plugins disabled as possible and nothing changes. I can't disable ACF/CPT-UI since the query relies on them. Here's a [gist](https://gist.github.com/ezekg/abb7d8f39913f7258e30) of the request/response using curl. It looks like the response is incomplete HTML, too.

It's also worth noting that we're requesting the data from a WP install within a subdirectory of another WP install (and both of those sites use a folder structure similar to [WP Skeleton](https://github.com/markjaquith/WordPress-Skeleton)/[Bedrock](https://github.com/roots/bedrock)), but we're receiving the response from the root site. So, that's odd. They shouldn't even know each other exist, correct?

WP-API is disabled for now, so you won't be able to make the requests yourself using that URL. Let me know if I can give you any more info.

**Comment by danielbachhuber** [comment]
I think you've got some bug in a caching plugin or similar. The request isn't being handled by WP-API at all.

**Comment by ezekg** [comment]
I'm not using a caching plugin. Why would this only happen after a certain threshold of posts is queried? If I change that request to `posts_per_page=50`, it works fine. Do you know what would cause that inconsistency?

**Comment by danielbachhuber** [comment]
Hard to say without having access to the codebase.

**Comment by ezekg** [comment]
You're right. I tested with a large amount of posts on my development env and all looks good. As snappy as ever. I'll dig into it further later on. Thanks for the help. This is an awesome project. :+1:

**Comment by luetkemj** [comment]
Similar error over here. I get a 500 error at 87+ posts but loads fine at 86. Works fine local but not on server. Strangely the feed always works if you navigate directly to it even when it's 500 on the page I'm trying use it.

**Comment by rmccue** [comment]
This appears to be the same bug as #475. :)
