### ISSUE TITLE
Error when provided query parameter isn't permitted

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1212]
Our Comments controller permits some query parameters to only be used when user can `edit_posts`. If the user can't `edit_posts` but uses the query param, we should throw a validation error.

From #1211

**Comment by danielbachhuber** [comment]
It will be nice to auto-validate once #1128 lands, and then have a validation callback for these specific arguments.

**Comment by rachelbaker** [comment]
Punted to Beta 4
