### ISSUE TITLE
Make it easier to cross call controllers by creating WP_REST_Requests

### ISSUE THREAD

**Issue by joehoyle** [WP-API/WP-API#1218]
Currently cross calling `get_item` etc is laborious and you need to know the route etc. Typically, a Request object does't need all that information, as the callback just wants to the arguments. For example, rather than internally creating a `WP_REST_Request` for `/taxonomy/post_tag/terms/123`, it would be nicer to just do `new WP_REST_Request( array( 'taxonomy' => 'post_tag', 'id' => 123 ) )` or something.

@rmccue thoughts on this?

**Comment by danielbachhuber** [comment]
Why not a utility function?

**Comment by danielbachhuber** [comment]
Another example https://github.com/WP-API/WP-API/pull/1253/files#diff-7900746e7eb16a3b53b0cb9d4070e010R315

**Comment by danielbachhuber** [comment]
Argument favor of a utility function is that the request should route through the server so we're not tightly coupled on the current controller (e.g. someone has subclassed the controller).

From https://github.com/WP-API/WP-API/pull/1253/files#r30641180

**Comment by danielbachhuber** [comment]
We also do a fair amount of

```
return $this->get_item( array(
	'id'      => $post_id,
	'context' => 'edit',
));
```

These should be proper request objects.

**Comment by danielbachhuber** [comment]
Landed #1333, now I need to do some updates across the board

**Comment by rmccue** [comment]
Let's close this one out as done in #1333; any other stuff that needs doing can have separate tickets.

**Comment by danielbachhuber** [comment]
The issue isn't done. I still need to make updates across the board. I'll move this to b4.

**Comment by danielbachhuber** [comment]
@joehoyle created a utility function for this in https://gist.github.com/joehoyle/e7321570525af6daeae2

**Comment by danielbachhuber** [comment]
@joehoyle look what's already been committed to core — `rest_do_request()` https://developer.wordpress.org/reference/functions/rest_do_request/

Introduced in #1333, and we're using it in `WP_REST_Posts_Controller::delete_item()`, So....

**Comment by danielbachhuber** [comment]
Created a core ticket to improve upon `rest_do_request()` https://core.trac.wordpress.org/ticket/35329

**Comment by danielbachhuber** [comment]
Punting on the rest of this for now. While I like the pattern implied in #1991, there's concern about the performance impact of doing more work for dubious benefit.

Slack chat https://wordpress.slack.com/archives/core-restapi/p1452557078004064
