### ISSUE TITLE
Question:How to audit each request/response?

### ISSUE THREAD

**Issue by hanabadler** [WP-API/WP-API#1225]
hi
I would like to know if there is some filter/hook i can use to send each request/response to a 3rd party application
i want to collect all request.responses and send them to a piwik server .
i addeda feew mthods of my own and started wrapping each one in call request / cal response but is "ugly coding"
is there a filter that i can use to grab the information, send it (using async way) and continue with the flow of the mecahnizm?
thanks
Hana

**Comment by danielbachhuber** [comment]
> is there a filter that i can use to grab the information, send it (using async way) and continue with the flow of the mecahnizm?

Yes, you can hook into `rest_pre_serve_request`: https://github.com/WP-API/WP-API/blob/develop/lib/infrastructure/class-wp-rest-server.php#L283

You'll want to make sure to continue to `return false;`, so the response is served through the API as expected.

**Comment by hanabadler** [comment]
Hi
Thank you.
i will try to use this filter
thanks
Hana.

**Comment by hanabadler** [comment]
Hi 
i created a repositry plugin that use piwik integration.
check this link
https://github.com/hanabadler/WP-API-Piwik-Integration
would be nie if wp-api team will add it to their repositry's
thanks
Hana
