### ISSUE TITLE
Working with comments meta

### ISSUE THREAD

**Issue by htrex** [WP-API/WP-API#1228]
Hello,
for a project I'm using a custom comment meta field, implemented as on the Gist here https://gist.github.com/htrex/dbe3e4f2547f7d8c8abc

Looking at the documentation on http://wp-api.org/ I'm not finding any reference on how to work with comment metas.
What's the status of this functionality? It's undocumented or missing from the API?

**Comment by danielbachhuber** [comment]
> What's the status of this functionality? It's undocumented or missing from the API?

Not implemented yet #1229

**Comment by htrex** [comment]
Thanks, I'll be watching #1229 and test the API eventually!
