### ISSUE TITLE
New Comments Not Returned in /comments Collection

### ISSUE THREAD

**Issue by bkirby989** [WP-API/WP-API#1230]
This is for v2.0 Beta 1

When I submit and approve a new comment it doesn't get returned in the `/comments` collection, but it does return when queried directly by its id `/comments/<id>`

**Comment by danielbachhuber** [comment]
Thanks for the report. We'll take a look at this in beta3 (and generally firm up behavior around comments through the API)

**Comment by bkirby989** [comment]
@danielbachhuber After some troubleshooting I found that if you `POST` a new comment when providing an explicit `type` of `null` then the comment gets returned in the collection as expected.

When a `type` of `comment` gets provided (which is what the API does by default) then the comment doesn't get included in the collection.

**Comment by rachelbaker** [comment]
Assigning to myself to fix this bug.

**Comment by bkirby989** [comment]
Thanks @rachelbaker !

**Comment by bkirby989** [comment]
@rachelbaker @danielbachhuber Actually #1244 doesn't completely solve the issue. Line 31 of the comments controller sets a default `type` of `comment` when posting a new comment. Comments posted in that manner still don't show up in the collection. 

Removing the `default` declaration in line 31 solves the issue.
