### ISSUE TITLE
Custom Post Type - Trying to get property of non-object in... plugin.php line 515

### ISSUE THREAD

**Issue by JSeligsohn** [WP-API/WP-API#1234]
I'm trying to GET a custom post type via 
/posts?type=type but instead of a JSON response I'm getting some errors before the JSON object.
Looks like this: 
    <br />
    <b>Notice</b>:  Trying to get property of non-object in <b>/Applications/MAMP/htdocs/keystonek/wp-content/plugins/json-rest-api/plugin.php</b> on line <b>515</b><br />
    <br />
    <b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/keystonek/wp-content/plugins/json-rest-api/plugin.php:515) in     <b>/Applications/MAMP/htdocs/keystonek/wp-content/plugins/json-rest-api/lib/class-wp-json-server.php</b> on line <b>587</b><br />
    <br />
    <b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/keystonek/wp-content/plugins/json-rest-api/plugin.php:515) in    <b>/Applications/MAMP/htdocs/keystonek/wp-content/plugins/json-rest-api/lib/class-wp-json-server.php</b> on line <b>587</b><br />
    <br />
    <b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/keystonek/wp-content/plugins/json-rest-api/plugin.php:515) in    <b>/Applications/MAMP/htdocs/keystonek/wp-content/plugins/json-rest-api/lib/class-wp-json-server.php</b> on line <b>587</b><br />
    <br />
    <b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/keystonek/wp-content/plugins/json-rest-api/plugin.php:515) in    <b>/Applications/MAMP/htdocs/keystonek/wp-content/plugins/json-rest-api/lib/class-wp-json-server.php</b> on line <b>587</b><br />
Not sure what is wrong. It works fine when just doing /posts so I assume it has to do with the response from the type parameter. How would I fix this?

**Comment by danielbachhuber** [comment]
> I'm trying to GET a custom post type via 
> /posts?type=type

Looks like your `type` argument is invalid: https://github.com/WP-API/WP-API/blob/master/plugin.php#L511

**Comment by JSeligsohn** [comment]
My fault - I didn't accurately describe what I had in my code - I have
    /posts/?type=establishment
where "establishment" is a custom post type. When I go to that route, it does show the JSON object, but above it is the code I included above ("Notice:...."). This seems to prevent my code from properly identifying and using the JSON object.
