### ISSUE TITLE
Custom post type meta not displaying

### ISSUE THREAD

**Issue by joneslloyd** [WP-API/WP-API#1238]
Hi there,

I'm using the V2 BETA API, and..

I've added a custom post type to the API as follows:

    add_action( 'init', 'add_events_to_json_api' );
    function add_events_to_json_api(){
		
		global $wp_post_types;
		$wp_post_types['my_events']->show_in_rest = true;
		$wp_post_types['my_events']->rest_base = 'my_events';
		$wp_post_types['my_events']->rest_controller_class = 'WP_REST_Posts_Controller';
	}

And then I've tried to expose some meta:

    add_filter( 'json_prepare_post', 'add_meta_to_json', 10, 3 );
    function add_meta_to_json($data, $post, $context){
		
		if ( $context !== 'view' || is_wp_error( $data ) ) {
			return $data;
		}
		
		$start = '';
		$end = '';
		$location = '';
		
		if(!empty(get_post_meta( $post['ID'], '_my_events_start', true ))){
			$start = get_post_meta( $post['ID'], '_my_events_start', true );
		}
		
		if(!empty(get_post_meta( $post['ID'], '_my_events_end', true ))){
			$end = get_post_meta( $post['ID'], '_my_events_end', true );
		}
		
		if(!empty(get_post_meta( $post['ID'], '_my_events_location', true ))){
			$location = get_post_meta( $post['ID'], '_my_events_location', true );
		}
		
		if($post['post_type'] == 'my_events'){
			$data['event_meta'] = array(
				'start' => $start,
				'end' => $end,
				'location' => $location,
			);	
		}
		
		return $data;
	}

However, what happens is that when I visit http://mysite.com/wp-json/wp/v2/my_events/6269/
I will get the custom post type, but without the meta I've added above.

Even removing the post type check in the add_meta_to_json function doesn't help, nor just visiting http://mysite.com/wp-json/wp/v2/posts/6269/

Not sure if I'm missing something, or if this is an error?

If this isn't how I should retrieve meta in the V2 API, is there any chance in letting me know how I should?

Thanks

**Comment by danielbachhuber** [comment]
The filter is unique to the post type. If the post type you're hooking into is `my_events`, then the filter will be `rest_prepare_my_events`. See https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-posts-controller.php#L1078

**Comment by joneslloyd** [comment]
Thanks for the quick response!

Just tried changing the code to this:

    add_filter( 'rest_prepare_my_events', 'add_meta_to_json', 10, 3 );
    function add_meta_to_json($data, $post, $request){
		
		if ( $request['context'] !== 'view' || is_wp_error( $data ) ) {
			return $data;
		}
		
		$start = '';
		$end = '';
		$location = '';
		
		if(!empty(get_post_meta( $post->ID, '_my_events_start', true ))){
			$start = get_post_meta( $post->ID, '_my_events_start', true );
		}
		
		if(!empty(get_post_meta( $post->ID, '_my_events_end', true ))){
			$end = get_post_meta( $post->ID, '_my_events_end', true );
		}
		
		if(!empty(get_post_meta( $post->ID, '_my_events_location', true ))){
			$location = get_post_meta( $post->ID, '_my_events_location', true );
		}
		
		if($post->post_type == 'my_events'){
			$data->event_meta = array(
				'start' => $start,
				'end' => $end,
				'location' => $location,
			);	
		}
		
		return $data;
	}

But it's not liking it for some reason.

**Comment by danielbachhuber** [comment]
> But it's not liking it for some reason.

Can you do some debugging to see if the callback is firing, etc.?

**Comment by joneslloyd** [comment]
Sorry to sound stupid, but - how would you recommend I do it in this situation?

Usually I just print_r(), but that's not giving an output (I'm guessing due to the point at which the function is called).

**Comment by danielbachhuber** [comment]
> Usually I just print_r(), but that's not giving an output (I'm guessing due to the point at which the function is called).

Try putting `print_r()` into the posts controller itself, and see if that's being fired?

**Comment by joneslloyd** [comment]
Okay, so if I print_r() in the posts controller itself, and in my custom function "add_meta_to_json", I'm getting an output.

Also if I print_r() on the $data object before adding the 'event_meta' property, it's not included (as expected) and if I do so afterwards, it is present in the $data object.

It just doesn't seem to be being kept. I've tried changing the priority to 999 but this also doesn't change anything.

**Comment by danielbachhuber** [comment]
> It just doesn't seem to be being kept. I've tried changing the priority to 999 but this also doesn't change anything.

Hm. Hard to say without having access to the codebase.

**Comment by rmccue** [comment]
Dumb question, but you're setting a property on `$data`; is that an instance of `WP_REST_Response`? `WP_REST_Response` stores the data to return to the browser in the `data` property of this, so you might need to do:

```php
$response_data = $data->get_data();
$response_data['xyz'] = 'blah';
$data->set_data( $response_data );
```

**Comment by joneslloyd** [comment]
@danielbachhuber No worries - I can't expect you to look through my code. Thanks for the help though :)

@rmccue That did it! 

Working code is:

    add_filter( 'rest_prepare_my_events', 'add_meta_to_json', 10, 3 );
    function add_meta_to_json($data, $post, $request){

    $response_data = $data->get_data();

    if ( $request['context'] !== 'view' || is_wp_error( $data ) ) {
        return $data;
    }

    $start = '';
    $end = '';
    $location = '';

    if(!empty(get_post_meta( $post->ID, '_my_events_start', true ))){
        $start = get_post_meta( $post->ID, '_my_events_start', true );
    }

    if(!empty(get_post_meta( $post->ID, '_my_events_end', true ))){
        $end = get_post_meta( $post->ID, '_my_events_end', true );
    }

    if(!empty(get_post_meta( $post->ID, '_my_events_location', true ))){
        $location = get_post_meta( $post->ID, '_my_events_location', true );
    }

    if($post->post_type == 'my_events'){
        $response_data['event_meta'] = array(
            'start' => $start,
            'end' => $end,
            'location' => $location,
        );  
    }

    $data->set_data( $response_data );

    return $data;
    }

Thanks a lot! Much appreciated!

**Comment by joneslloyd** [comment]
Just a PS,

When I was Googling for a solution to this (with the V2 API), literally everything out there uses the old API, and as far as I'm aware, there aren't any examples of adding meta with V2 API.

Feel free to use/adapt this snippet as a V2 version of the 'json_prepare_post' code snippets that are out there.

Cheers

**Comment by danielbachhuber** [comment]
> Dumb question, but you're setting a property on $data; is that an instance of WP_REST_Response?

We should probably rename the variable from `$data` to `$response`, and make sure we're always passing `WP_REST_Request` or `WP_REST_Response` to filters / actions.
