### ISSUE TITLE
Returned content is null, and there is HTML outside of the JSON data

### ISSUE THREAD

**Issue by stevenalanstark** [WP-API/WP-API#1239]
Hello,

I am excited to use this plugin with backbone, and have installed the plugin into my wordpress site and have started to look at the backbone models, however I am stuck right off the back with a malformed response from the server.

Have a look for yourself:

http://stevenstark.com/wp-json/pages
or
http://stevenstark.com/wp-json/posts

You can see that the content is at the top of the response, un-organized in plain HTML, and in the JSON the content var is null

I am assuming I am missing a step in my installation and setup perhapse? 

thank you for any help

**Comment by danielbachhuber** [comment]
> You can see that the content is at the top of the response, un-organized in plain HTML, and in the JSON the content var is null
> 
> I am assuming I am missing a step in my installation and setup perhapse?

Nope. There is some bad actor code in your install. If I had to take a guess, I suspect you have a shortcode that's echoing instead of returning.

**Comment by stevenalanstark** [comment]
I installed the plugin via the wordpress admin plugin search and installed, maybe I should install a manually downloaded version instead?

**Comment by danielbachhuber** [comment]
> I installed the plugin via the wordpress admin plugin search and installer, maybe I should install a manually downloaded version instead?

Er, shouldn't matter. The problem isn't with the plugin, but your site.

**Comment by stevenalanstark** [comment]
ok, thanks.

**Comment by stevenalanstark** [comment]
you were completely right, I needed to update the rocket theme custom plugins, they were doing the echo exactly as you said. thanks again.
