### ISSUE TITLE
Cookie Authentication Question with Nonces

### ISSUE THREAD

**Issue by ishansharma** [WP-API/WP-API#1240]
Hi, 

I am using Angular on front end. Nonce is generated using 

`wp_create_nonce('wp_json')`

The created nonce is sent as part of JSON to angular. On next request, I set X-WP-Json header using same nonce. However, I get a 403 forbidden error with following response:

`code: json_cookie_invalid_nonce
message: Cookie nonce is invalid`

The angular files are not enqueued using WP, but that shouldn't affect anything, right? Is there something I am missing? 

Thanks.

**Comment by ishansharma** [comment]
I read about nonces a bit and appears like WP will generate different nonces for logged in users and different for logged out users. 

So the issue seems to be that when I am generating nonce, it is generated without any logged in user! (I added wp_get_current_user() and get_current_user_id() around the code, both return 0). 

But since the WP API code is always executed as logged out user, how do I get a valid nonce to begin with? 

Since WP is not enqueuing the script, is there any other way?

**Comment by danielbachhuber** [comment]
Which version of the plugin are you using?

**Comment by ishansharma** [comment]
I'm using 1.1.3

**Comment by danielbachhuber** [comment]
> On next request, I set X-WP-Json header using same nonce.

The header is supposed to be `X-WP-Nonce` ?

See https://github.com/WP-API/WP-API/blob/c33f3bb5938ca00f647d7e99d948195aafd383ac/plugin.php#L314

**Comment by ishansharma** [comment]
I remember setting it up as X-WP-Nonce (above was a typo) and it wasn't working. Was discussing with a teammate and it suddenly started working. It seems to be working consistently for now. 

Closing the issue. 

Thank you.
