### ISSUE TITLE
DATA SHOW metakey

### ISSUE THREAD

**Issue by newmesiss** [WP-API/WP-API#1242]
my theme keeps private data metakey therefore in the json that data is not displayed, how can I do that the data is displayed in my json ?

try this but drop the plugin

function json_api_prepare_post( $post_response, $post, $context ) {
  if( get_fields($post['ID']) ){
    $post_response['company_website'] = get_fields($post['ID']);
    return $post_response;
  }
}
add_filter( 'json_prepare_post', 'json_api_prepare_post', 10, 3 );

**Comment by danielbachhuber** [comment]
Which version of the plugin are you using?

**Comment by newmesiss** [comment]
version 1.2.1 that is in WordPress.org

**Comment by danielbachhuber** [comment]
> dealing with this but only shows me the editor entry

What do you mean by this?

Also, it looks like your conditional is invalid.

Instead of:

```
function json_api_prepare_post( $post_response, $post, $context ) {
	if( get_fields($post['ID']) ){
		$post_response['company_website'] = get_fields($post['ID']);
		return $post_response;
	}
}
add_filter( 'json_prepare_post', 'json_api_prepare_post', 10, 3 );
```

It should be:

```
function json_api_prepare_post( $post_response, $post, $context ) {
	if( get_fields($post['ID']) ){
		$post_response['company_website'] = get_fields($post['ID']);
	}
	return $post_response;
}
add_filter( 'json_prepare_post', 'json_api_prepare_post', 10, 3 );
```

**Comment by newmesiss** [comment]
I'm wrong, but you edit the post.

with respect to the code, even still I can see the json, showing me blank

http://codelabchile.com/wp-json/posts/542

Topic you save data on meta_key to underscore that means are priovados.

**Comment by danielbachhuber** [comment]
> with respect to the code, even still I can see the json, showing me blank

Your server is returning a 500 error, which means there's a fatal occurring.

**Comment by newmesiss** [comment]
I am adding code to functions.php of my subject child, Is this right?

**Comment by danielbachhuber** [comment]
> I am adding code to functions.php of my subject child, Is this right?

Hard to say. This isn't really the place for this type of support.

**Comment by newmesiss** [comment]
and what is the correct way to get a json of an entry that includes all meta_key?

**Comment by newmesiss** [comment]
with this it succeeds, thanks

function json_api_prepare_post( $post_response, $post, $context ) {

  $field = get_post_custom($post['ID']);

  $post_response['custom_field'] = $field;

  return $post_response;
}
add_filter( 'json_prepare_post', 'json_api_prepare_post', 10, 3 );
