### ISSUE TITLE
Removing author data from result set, and possibly meta...

### ISSUE THREAD

**Issue by aryanduntley** [WP-API/WP-API#1246]
In my specific use case, I wish not to have any author data in the result set for a feed to a mobile app (attempting to send only the essential data to the requesting app so as to minimize size of string as much as possible).  I am also removing the thumbnail data and providing, custom, simple, direct links without all of the extra data.  

Instead of hooking into the individual prepare... for the media and the user, I am hooking into `wp_json_server_before_serve` with a later priority and removing the filter call.  I am doing this successfully with the media hook`remove_filter( 'json_prepare_post',    array( $wp_json_media, 'add_thumbnail_data' ), 10, 3 );` because the instantiated class `$wp_json_media` is globalized.   

However, with the user filter : `add_filter( 'json_prepare_post',    array( $wp_json_users, 'add_post_author_data'    ), 10, 3 );`  I cannot remove this because the instantiated class `$wp_json_users` is not global (and I recognize that it does not need to be otherwise) and I therefore am unable to reference this method for removal.

This issue would also occur if I were to try and remove the meta for the `json_prepare_post` filter.  

I have instead hooked into the prepare... filter (in this case `json_prepare_user`) and returned an empty result set when appropriate.

There are definitely workarounds for this by including code in the `wp_json_server_before_serve` function to allow a kill call for the various filters if needed, but I do not know whether that is something you guys feel is necessary.  I understand you have a lot to do before getting this thing into core yet, so this is a minor issue because there are ways to at least return an empty result set.  Still, it is something you should be aware of if you are not.  Also, this is all considering that I am not missing something when it comes to removing WP filters.  If I do not need access to the instantiated class in order to remove that filter that would be great, but I do not see that this is the case.

**Comment by danielbachhuber** [comment]
This is only applicable on `master`, which we are no longer taking enhancements for.

On `develop`, you can more easily decide whether or not to include embedded data.
