### ISSUE TITLE
GETTING STARTED Tutorial Error

### ISSUE THREAD

**Issue by melblum** [WP-API/WP-API#1247]
I'm new to all of this and am working through the "Getting Started" Tutorial and ran into an issue - When i was checking for the API and typed "curl -I http://example.com/" what was said was expected to return was not was I got. Instead it said 
"HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: max-age=604800
Content-Type: text/html
Date: Mon, 18 May 2015 18:33:30 GMT
Etag: "359670651"
Expires: Mon, 25 May 2015 18:33:30 GMT
Last-Modified: Fri, 09 Aug 2013 23:54:35 GMT
Server: ECS (mdw/1275)
X-Cache: HIT
x-ec-custom-error: 1
Content-Length: 1270"

Help. Thanks

**Comment by danielbachhuber** [comment]
> I'm new to all of this and am working through the "Getting Started" Tutorial and ran into an issue

Which "Getting Started" tutorial? Can you share a link?

> typed "curl -I http://example.com/" what was said was expected to return was not was I got.

You'll need to replace `example.com` with the full domain of your site running WP-API.

**Comment by rachelbaker** [comment]
@danielbachhuber This is the v1.x Getting Started tutorial: http://wp-api.org/guides/getting-started.html

@melblum You will need to have the plugin activated on your site and replace `http://example.com` with your site domain as Daniel mentioned.
