### ISSUE TITLE
Can't list get posts json.

### ISSUE THREAD

**Issue by t0t** [WP-API/WP-API#1250]
Hello,
Great plugin!

I've wp-api (last version) installed but can't list get posts json. Any idea?
thanks.

![captura de pantalla 2015-05-19 a las 14 21 33](https://cloud.githubusercontent.com/assets/6004806/7702463/92c7c6ce-fe30-11e4-8924-740be76dd709.png)

**Comment by t0t** [comment]
It only lets me enter to http://dev.caferminet.es/wp-json/
but none of posts, pages, media...

**Comment by rachelbaker** [comment]
@t0t Are you using the 2.0beta version?  If so try, dev.caferminet.es/wp-json/wp/posts

**Comment by t0t** [comment]
Using v1.2.2
