### ISSUE TITLE
Coding standards isn't running on builds at all

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1261]
Must've been bugged in a40a064f01708c55190ad31e7fe30b940e87bd96

**Comment by rmccue** [comment]
Fixed in #1268?

**Comment by danielbachhuber** [comment]
Nope. In fact, I'm not really sure what that PR did.

Our build should fail because we have a number of coding standards violations.

**Comment by danielbachhuber** [comment]
#1277 will do the trick
