### ISSUE TITLE
Help!   Full posts wont display, only excerpts display

### ISSUE THREAD

**Issue by marklovett** [WP-API/WP-API#1263]
WordPress excerpts from my site are displaying, but clicking ‘Read More’ displays a blank page! No images are displaying.

All posts have text and image content and  I dont see any javascript errors in chrome.

the config.js looks like this:

`angular.module(‘your_app_name.config’, []) .constant(‘WORDPRESS_API_URL’, ‘http://www.marklovettstudio.com/?json=get_recent_posts') .constant(‘GCM_SENDER_ID’, ‘574597432927’);`

When I click ‘Read More’ in chrome, in network tab these are the following results:

General Remote Address: 66.147.244.72:80 Request URL:http://marklovettstudio.com/?json=get_recent_postsget_post/?post_id=2026&callback=angular.callbacks._2 Request Method: GET Status Code: 200 OK Response Headers Cache-Control: no-cache, must-revalidate, max-age=0 Connection: close Content-Encoding: gzip Content-Length: 15288 Content-Type: application/javascript; charset=UTF-8 Date: Tue, 19 May 2015 02:20:42 GMT Expires: Wed, 11 Jan 1984 05:00:00 GMT Pragma: no-cache Server: Apache Vary: Accept-Encoding X-Pingback:http://marklovettstudio.com/xmlrpc.php Request Headers Accept: / Accept-Encoding: gzip, deflate, sdch Accept-Language: en-US,en;q=0.8 Connection: keep-alive Cookie: wp-settings-2=hidetb%3D1%26editor%3Dtinymce%26libraryContent%3Dbrowse%26imgsize%3Dfull%26ed_size%3D893%26unfold%3D1; wp-settings-time-2=1430001981; __utma=65956018.1986148705.1430001889.1431886310.1431913597.4; __utmz=65956018.1430001889.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _ga=GA1.2.1986148705.1430001889; wordpress_logged_in_1c85f73f1e0d11ee7598ae9e3ff6619e=marklove%7C1433123342%7CL1RQj8Ce4rf5J02QcE5143wH6y4WWdsdqq8wgssHedH%7C183ea4eb70bd8bdd8b040af58cf5a9857f61414174db72f07e3f9d717f741216 Host: marklovettstudio.com Referer: http://localhost:8100/User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 8_0 like Mac OS X) AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Mobile/12A4345d Safari/600.1.4
Query String Params json: get_recent_postsget_post/?post_id=2026 callback: angular.callbacks._2

Under Preview tab: angular.callbacks._2({status: “ok”, count: 10, count_total: 87, pages: 9, …}) count: 10 count_total: 87 pages: 9 posts: [{id: 2026, type: “post”,…}, {id: 1999, type: “post”, slug: “new-painting-by-mark-lovett-studio”,…},…] status: “ok”

Opened post 0: here is content shown for post 0 in chrome/preview: {id: 2026, type: “post”,…} attachments: [] author: {id: 2, slug: “marklove”, name: “marklove”, first_name: “mark”, last_name: “lovett”,…} categories: [{id: 1, slug: “misc”, title: “Misc”, description: ””, parent: 0, post_count: 1}] comment_count: 0 comment_status: “open” comments: [] content: “

I really enjoyed painting a portrait of three children recently. It was particularly nice because the parents were such a pleasure to deal with and they were very happy with the finished painting.

?
But every once in while it’s time to play some guitar, buy a guitar or even sell one on occasion. When it comes to pure guitar heaven, whether buying or sellin’ everyone goes toAmerican Vintage Guitar for rare vintage Fender, Gibson and Martin guitars. 1950’s and 1960’s Fender Telecasters and Stratocasters, and Gibson Les Pauls, and 1930’s Martin Guitars. American Vintage Guitar has been dealing in the finest American vintage guitars for decades. Check it out!

?
I must also put in a shameless plug for Web Experts. If you need a professional top quality web site these guys are the best around. They are very talented WordPress web developers, designers and internet marketers with some really amazing work. Be sure and check them out too!

?
.

?” custom_fields: {slide_template: [“default”]} date: “2014-12-30 01:00:23” excerpt: “
I really enjoyed painting a portrait of three children recently. It was particularly nice because the parents were such a pleasure to deal with and they were very happy with the finished painting. But every once in while it’s time to play some guitar, buy a guitar or even sell one on occasion. When it […]
?” id: 2026 modified: “2015-03-01 00:46:35” slug: “i-loved-painting-my-new-children-portraits-but-for-rare-guitars-american-vintage-guitar” status: “publish” tags: [] title: “I loved painting my new children portraits! But for rare guitars – American Vintage Guitar!” title_plain: “I loved painting my new children portraits! But for rare guitars – American Vintage Guitar!” type: “post” url: “http://marklovettstudio.com/i-loved-painting-my-new-children-portraits-but-for-rare-guitars-american-vintage-guitar/”

**Comment by rmccue** [comment]
It looks like this is a different REST API, since the format doesn't match what we return (notably `title_plain`). I'd recommend contacting whoever wrote the Angular module you're using.

**Comment by marklovett** [comment]
Thanks for your response Ryan. I deactivated WP-REST-API plugin and installed JSON API plugin and I get the same results! Any further help would be greatly appreciated.

**Comment by marklovett** [comment]
I found the solution!   My constant, ‘WORDPRESS_API_URL’ ,  in my config.js file, is not supposed to include  ‘get_recent_posts’
