### ISSUE TITLE
return all post a taxtonomy/category

### ISSUE THREAD

**Issue by newmesiss** [WP-API/WP-API#1264]
I'm trying to return all threads that are part of a category. the taxonomy is joob_category.
to collect information category tells me conto 3 post in the category, these I want to pick
 ```  
{
    ID: 50,
    name: "Deportes",
    slug: "deportes",
    description: "",
    taxonomy: "job_category",
    parent: null,
    count: 3,
    link: "http://xdev.cl/local-categoría/deportes/",
    meta: {
    links: {
    collection: "http://xdev.cl/wp-json/taxonomies/job_category/terms",
    self: "http://xdev.cl/wp-json/taxonomies/job_category/terms/50"
    }}
}
```

**Comment by nathanrice** [comment]
Normally, I'd recommend using the following URL structure:

```
/wp-json/wp/v2/posts?filter[cat]=X
```

Where X is the category ID.

Or in your case, a custom taxonomy:

```
/wp-json/wp/v2/posts?filter[taxonomy]=joob_category&filter[term]=50
```

But I'll be honest, running either of these queries doesn't work for me. It returns the same 10 posts as `/wp-json/wp/v2/posts` no matter what filters I put on it. I wonder if this is a bug, or if I'm doing something wrong?

@rmccue @rachelbaker

**Comment by danielbachhuber** [comment]
> But I'll be honest, running either of these queries doesn't work for me. It returns the same 10 posts as /wp-json/wp/v2/posts no matter what filters I put on it.

Query params for posts is WIP #1302
