### ISSUE TITLE
Run Concurrently both version 1 and 2 

### ISSUE THREAD

**Issue by pirony** [WP-API/WP-API#1265]
I there,
I'm using the WP-API v1 on a webapp I'm creating. 
Wanted to try WP-API v2 and run it concurrently with v1, but I can't get it to work.
Both run well alone but only one version at a time

i pasted the filter you mentionned here:
https://make.wordpress.org/core/2015/04/29/wp-rest-api-version-2-0-beta-1/
 in my function.php

Any idea? Thanks

**Comment by jvandijk** [comment]
@pirony I managed to resolve it by disabling the filters that are active for compatibility with V1. I've blogged about my solution here : http://jrdk.nl/blog/2015/05/running-wp-api-1-2-2-0-beta-side-by-side/

**Comment by juan-manuel-moreno** [comment]
Hello. I can't Run Concurrently both version 1 and 2. Can any body help me? Please.

**Comment by mnelson4** [comment]
Related ticket: https://core.trac.wordpress.org/ticket/34399, which is an issue when running WP API 1.2 plugin and current WP Core 4.4

**Comment by danielbachhuber** [comment]
As of WP-API v1.2.4, the WP-API plugin will take precedent over the REST API infrastructure in WordPress core. Running them concurrently isn't supported.
