### ISSUE TITLE
is_user_logged_in() always false for json api requests

### ISSUE THREAD

**Issue by anttiviljami** [WP-API/WP-API#1266]
I'm trying to use the following custom ajax request to add a comment to a post. 

![screen shot 2015-05-20 at 16 12 11](https://cloud.githubusercontent.com/assets/6105650/7726475/0423699c-ff0b-11e4-89f7-2abd4542b287.png)

The comments get added correctly, but the problem is that logged in user's comments get added as Anonymous comments.

I have this filter enabled for debug:
```php
<?php
add_filter( 'rest_pre_insert_comment', 'rest_debug_logged_in_user' );
function rest_debug_logged_in_user( $prepared_comment ) {
  echo json_encode( is_user_logged_in() ? 'yes' : 'no' );
  die();
}
```

As you can see, WordPress can't see my login from that filter, even though the comment has clearly been sent with a browser that's logged in to this WordPress instance. 

![screen shot 2015-05-20 at 16 15 19](https://cloud.githubusercontent.com/assets/6105650/7726547/a1dedcde-ff0b-11e4-8083-b5dd479ecc73.png)

What am I doing wrong? Has the default WordPress user login been disabled for API requests?

**Comment by danielbachhuber** [comment]
I suspect your nonce is incorrect, so you're being forced to logged-out context. Can you verify the nonce value is what it should be? Can you make other authorized requests?

**Comment by anttiviljami** [comment]
Thanks for the response!

I'm using this for the nonce. It's echoed out to my document where javascript can read it.

`<?php echo wp_create_nonce( 'wp_api' ); ?>`

**Comment by anttiviljami** [comment]
I found out there were two things wrong here already. :)

The nonce name isn't wp_api like in the documentation, it's wp_rest according to https://github.com/WP-API/WP-API/blob/c322c6804a86562e5a82391af8ca1ddfa835967c/extras.php#L34

Also, I was passing the nonce via POST parameter called '_wp_json_nonce' when it should've been '_wp_rest_nonce'. Again, just me reading the outdated documentation.

Thanks for pointing me to the right direction!
