### ISSUE TITLE
DELETE consistency when trash isn't available for resource

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#1271]
Across our endpoints, we should be consistent with how trashing works. (#789)

in #789, I commented:
> Ideally, we want consistent behaviour here, so that brings up the question of "what do we do for untrashable items?" - that is, core objects that don't support being trashed. I think it's possible that down the line core will support these being trashed, so we should plan with that eventuality in mind, even if it never happens.

Along these lines, I think we should be consistent with trashing. For every resource that supports either type of DELETE, `DELETE <resource>` should always trash, and `DELETE <resource>?force=true` should always permanently delete. When trash isn't available for a given resource, the bare `DELETE` should fail to do anything; ditto if permanently delete isn't available.

This gives us room to expand if core adds trash. Take terms for example. If bare `DELETE` fails, clients will code to permanently delete. If core adds trash for terms e.g., the bare `DELETE` would change from a "not supported" response to working. Clients could then update to start using this endpoint if they want to use the trash, and still fall back on sites that don't have it by checking the status code. (Eager clients could code for this from the start so they begin supporting it immediately when it's available.)

@WP-API/amigos Thoughts? I think this is a natural extension to ensure we're consistent, which along with #1260 should make our DELETEs super-awesome-sauce.

**Comment by rmccue** [comment]
Discussed briefly with @rachelbaker in [Slack](https://wordpress.slack.com/archives/core-restapi/p1432172798000969):
> **Rachel Baker:**
> can you clarify:
> > the bare DELETE should fail to do anything;
>
> so if trash isn’t available (like for terms)
> a DELETE request without force=true does nothing?
> am I correct?
>
> **Ryan McCue:**
> Yeah, it's a no-op internally, and returns an error
> [...]
>
> **Ryan McCue:**
> Actually, 501 Not Implemented would work nicely
> It implies that we will implement it some day, which I think is likely true for trashes


So: take terms, which don't support trashing. `DELETE terms/42` would take no action and return a 501 with `[ { code: "rest_trash_not_supported" } ]`; `DELETE terms/42?force=true` would permanently delete the term and return a 200 with the data (see #1254). If some day terms get trashing support, the former would change to no longer error, and would instead trash the term, and return a 200/202 (#1260) with the data.

**Comment by danielbachhuber** [comment]
> If some day terms get trashing support

We should run this up the pole and see what core is thinking in this regard.

cc @johnbillion

**Comment by rmccue** [comment]
Conferred with a few members of the core team (@dd32, @azaozz) and we generally agreed that there's no reason these wouldn't support trashing, and it's entirely likely that they will in the future to support undo-ing. (With the exception of attachments, which have technical limitations on trashing right now.)

**Comment by dd32** [comment]
Having `DELETE` no-op without the `force` parameter feels weird at present without undo implemented, but is consistent and would continue to be so if we added the feature down the line..

**Comment by rmccue** [comment]
While we're here, we should consider whether we should rename the parameter. `force` isn't the best name, can we come up with something better?
