### ISSUE TITLE
Use absolute urls for pagination links (prev/next)

### ISSUE THREAD

**Issue by mladenilic** [WP-API/WP-API#1272]
Pagination links do not use absolute urls, which makes them harder to utilize. Right now, link values are request paths, unaware of a domain on which API is.

Source: https://github.com/WP-API/WP-API/blob/master/lib/class-wp-json-response.php#L89-L100
Possible solution: `$this->link_header( 'next', json_url( $request ) );` and `$this->link_header( 'prev', json_url( $request ) );`

I'd also like to add GitHub api as a reference: https://developer.github.com/guides/traversing-with-pagination/

rev: e03725a631154657cd097e5026eb176cf61f2d6c (Issue is present in current release - v1.2.2)

**Comment by rmccue** [comment]
:+1:

**Comment by danielbachhuber** [comment]
Pagination links use full URLs in v2:

```
local ➜  wordpress-develop.dev git:(master) http GET wordpress-develop.dev/wp-json/wp/v2/posts page==2 --headers
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Authorization
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
Allow: GET
Connection: keep-alive
Content-Type: application/json; charset=UTF-8
Date: Sun, 13 Dec 2015 23:46:44 GMT
Link: <http://wordpress-develop.dev/wp-json/wp/v2/posts?page=1>; rel="prev", <http://wordpress-develop.dev/wp-json/wp/v2/posts?page=3>; rel="next"
Server: nginx/1.4.6 (Ubuntu)
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Powered-By: PHP/5.5.9-1ubuntu4.7
X-WP-Total: 111
X-WP-TotalPages: 12
```
