### ISSUE TITLE
wp-api not showing under settings menu

### ISSUE THREAD

**Issue by manuelro** [WP-API/WP-API#1282]
This is probably a quite silly question, but there is nothing under settings menu other than WP defaults. I already activated the plugin.

I'm running a local environment, in my Mac. I downloaded the wp-api plugin and activated it with two versions of WP (3.9.1 and 4.2), but with no luck. Any idea of what's going on? Is there any third-party plugin that has to be installed or anything like that?

**Comment by rmccue** [comment]
The plugin doesn't have any settings to set. :)
