### ISSUE TITLE
Comment schema needs embed context

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#1287]
The comment schema doesn't include any response fields in the `embed` context right now, which means when embedding the related data for a single post the response data is empty.

Example:

```
"_embedded": {
	...
	"replies": [
		[ 
		{ 
			"_links": {
				"self": [
					{
					"href": "http://vagrant.local/wp-json/wp/v2/comments/3"
					}
				],
				"collection": [
					{
					"href": "http://vagrant.local/wp-json/wp/v2/comments"
					}
				],
				"author": [
					{
					"embeddable": true,
					"href": "http://vagrant.local/wp-json/wp/v2/users/1"
					}
				],
				"post": [
					{
					"embeddable": true,
					"href": "http://vagrant.local/wp-json/wp/v2/posts/5"
					}
				]
			}
		}
	] ],
	...
}
```

**Comment by rachelbaker** [comment]
@WP-API/amigos Proposed response fields for the comments embed context:

  * `id`
  * `author_name`
  * `author_url`
  * `date`
  * `content[rendered]`

Thoughts?   

The embedded response would then look like this:
```
"_embedded": {
	...
	"replies": [
		[
			{
				"id": 3,
				"author_name": "admin",
				"author_url": "",
				"date": "2015-05-25T15:06:45",
				"content": {
					"rendered": "<p>Worst episode ever.</p>\n"
				},
				"link": "http://vagrant.local/2015/05/20/marge-vs-monorail/#comment-3",
				"_links": {
					"self": [
						{
							"href": "http://vagrant.local/wp-json/wp/v2/comments/3"
						}
					],
					"collection": [
						{
							"href": "http://vagrant.local/wp-json/wp/v2/comments"
						}
					],
				...
				}
	},
	...
}
```

**Comment by danielbachhuber** [comment]
> Proposed response fields for the comments embed context:

Probably need `avatar_url` and `parent` in there too.

**Comment by rachelbaker** [comment]
@danielbachhuber Good call!

**Comment by rachelbaker** [comment]
@danielbachhuber Actually `avatar_url` is not a field in the Comment item response.  I created #1290 to discuss and track adding that field.

**Comment by rmccue** [comment]
I added a basic set in dc8c14e5bce922dcf9699977b9c8931722eed12c on #1284:
* id
* author
* author_name
* author_url
* content
* date
* date_gmt
* status
* type

Probably don't need both date and date_gmt, and probably should add parent. Essentially, we should have everything we need to display comments on a post page.

**Comment by rachelbaker** [comment]
@rmccue I didn't see your comment before pushing #1291.  There I only include:

id
parent
author_name
author_url
content[rendered]
date
link
post

How should we resolve?

**Comment by rmccue** [comment]
@rachelbaker I'll add `parent` and `link` to my set, and remove `date_gmt`. I don't think we need `post` though, since the main use case for embedding comments is in the post itself, so that's not really useful.

**Comment by rmccue** [comment]
Turns out I misread and didn't actually have `date_gmt`, I had `link` anyway :)

**Comment by rachelbaker** [comment]
Closing in favor of #1284
