### ISSUE TITLE
Add author_avatar_url to the Comment item response

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#1290]
Related: https://github.com/WP-API/WP-API/issues/1287#

**Comment by danielbachhuber** [comment]
@rachelbaker Do we need to offer an array of sizes when we return avatar URLs? What should the default size be?

**Comment by rachelbaker** [comment]
Tagging for discussion because I don't have a strong opinion on @danielbachhuber's question above.

>  Do we need to offer an array of sizes when we return avatar URLs? What should the default size be?

**Comment by rachelbaker** [comment]
Punted to Beta 4

**Comment by rachelbaker** [comment]
Done in #1361
