### ISSUE TITLE
Cannot list /posts

### ISSUE THREAD

**Issue by astralmedia** [WP-API/WP-API#1292]
Hey, thank you for all the hard work!

I installed a fresh wordpress 4.2.2 and couldnt get the plugin to list /posts. going to /wp-json worked, and had the routes that should be available, but going to /wp-json/posts wouldnt list anything.

I moved back to wordpress 4.1.5 (supported version on the plugin page) but still no help.

I also installed wp-api 1.2.1 but that didn't help.

I have pretty permalinks enabled, not sure what else to try.

Any ideas?

Thank you!

**Comment by mnelson4** [comment]
I'd suggest try temporarily changing your permalink settings in order to flush them (in the wp dashboard under settings then permalinks). I once had a similar issue when I had v 2.0 of the API active and then downgraded to v 1.2.

Also other plugins can of course interfere, do you have any others active? If so try deactivating them and then deactivating.

**Comment by rachelbaker** [comment]
@astralmedia Is there a public url for your site where we can see what is going on?

**Comment by astralmedia** [comment]
I do not have a public url for this. Was just doing a dev environment locally.

Literally its a fresh install of WP with no plugins but the wp-api one and two test posts.

What is the ideal wp version to wp-api version I should be using?

**Comment by astralmedia** [comment]
Now noticing I am getting this error:

Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by astralmedia** [comment]
After checking the logs it seems I didn't have ACF plugin installed, but I did have the ACF WP-API plugin turned on, so it was trying to run get_field and it wasn't supported.

**Comment by danielbachhuber** [comment]
@astralmedia Fixed then?

**Comment by astralmedia** [comment]
Thank you for the help guys!
