### ISSUE TITLE
make it possible to query a 'page' by slug only

### ISSUE THREAD

**Issue by hirasso** [WP-API/WP-API#1300]
Hi! Loving your amazing effort!!

I'm trying to query a page using this (version 1.2.2):
```javascript
wp-json/posts?filter[name]=my-first-page&filter[post_type]=any
```
This doesn't work because of this line in class-wb-json-posts.php:
```php
// Exclude the post_type query var to avoid dodging the permission
// check above
unset( $valid_vars['post_type'] );
```
If I comment this line out, everything works fine. I don't get it... How does querying a post by post_type make problems with permissions? I would like my angular app to reflect the wordpress permalinks settings of /%postname%/ that works for both posts and pages, so I can't do it using the pages/ endpoint.

**Comment by hirasso** [comment]
Never mind, I worked it out:
```javascript
wp-json/posts?filter[name]=my-first-page&type[0]=post&type[1]=page
```
Still, I think the best behaviour would be to look in both "post" and "page" post types if filtering by name...

**Comment by danielbachhuber** [comment]
> Still, I think the best behaviour would be to look in both "post" and "page" post types if filtering by name...

This would return inconsistently-formatted data in the response collection.
