### ISSUE TITLE
"Blog pages show at most" effecting "/media" results

### ISSUE THREAD

**Issue by dominicbusinaro** [WP-API/WP-API#1307]
When querying the media attachments: /wp-json/media?filter[parent]=1
The number of results are limited by the WP Settings > Reading > Blog pages show at most

**Comment by rmccue** [comment]
Good catch! This is fixed in version 2 by coincidence, so I'd recommend using that instead, as we're not doing any more substantial changes to version 1.

Thanks for the issue!
