### ISSUE TITLE
Problem with protected API

### ISSUE THREAD

**Issue by lsantaniello** [WP-API/WP-API#1309]
Hi all,
I need to help with protected API. I use Postman Browser tool and I have already installed WP OAuth Server.

http://<<my-domain>>/wp-json/users
[
    {
        "code": "json_user_cannot_list",
        "message": "Sorry, you are not allowed to list users."
    }
]

How can I test protected API with Postman Tool?

Help me please

Thanks

**Comment by danielbachhuber** [comment]
> How can I test protected API with Postman Tool?

Make sure you're authenticating against the server with a user who has the `list_users` capability.
