### ISSUE TITLE
Client JS is broken because it's referencing the wrong API URL

### ISSUE THREAD

**Issue by nathanrice** [WP-API/WP-API#1310]
Not sure if this should be fixed in `WP_API_Settings` or if the client script should append `/wp/v2` ... but either way, the client helpers don't work in the current version.

If someone would let me know which one needs to change, I'd be happy to spin up a PR.

**Comment by danielbachhuber** [comment]
> Not sure if this should be fixed in WP_API_Settings or if the client script should append /wp/v2

Probably the latter, as the `root` is the API root. Looks like you'll just need to update each instance.

> If someone would let me know which one needs to change, I'd be happy to spin up a PR.

Go for it!

**Comment by nathanrice** [comment]
Done. #1322.

**Comment by nathanrice** [comment]
https://github.com/WP-API/client-js/commit/e278a2592ae4fa69fff49f38ad4be47e3f870a41

This seems to have never made its way back into the main plugin. I'll get a PR ready that does that.

**Comment by nathanrice** [comment]
#1310

**Comment by rmccue** [comment]
Handled in #1374.
