### ISSUE TITLE
Filter custom post types

### ISSUE THREAD

**Issue by DONSA** [WP-API/WP-API#1311]
Hi,
I want to retrieve all schedule custom post types.
I tried this without success: /wp-json/posts?type[]=lesson&filter[status]=future

I'm doing something wrong?

Thanks

**Comment by danielbachhuber** [comment]
Is your request authenticated? You'll need to authenticate your request to access future posts.

**Comment by DONSA** [comment]
Probably no. I'm using a AJAX request:
```javascript
$.ajax({
        method: "GET",
        url: "/wp-json/posts?type[]=lesson",
        success: function(response)
        {
          console.log(response)
        }
});
```

[This](https://developer.wordpress.com/docs/oauth2/) could help me or there's a simpler solution?

Thanks

**Comment by danielbachhuber** [comment]
> there's a simpler solution?

If you include a nonce with the request, you can use the user's existing authentication cookies.

Btw, what you've linked to WordPress.com authentication information. You're currently working with the WordPress REST API. They're different ;)
