### ISSUE TITLE
users/me not working show 302 found

### ISSUE THREAD

**Issue by wesleyxiao** [WP-API/WP-API#1312]
basic authorization everthing working, but when i try this link localhost/wordpress/wp-json/users/me, show blank result and on console show 302 found.

anyone have same issue?

**Comment by rmccue** [comment]
Hi! This is actually intentional behaviour, as `/users/me` is just a pointer to the real user resource. The `Location` header should point to the user resource (e.g. `/users/4`), but the user data should also be included in the body data there as well.

**Comment by wesleyxiao** [comment]
thanks for reply rmccue, is there anyway to get current login user data?

**Comment by wesleyxiao** [comment]
thanks rmccue, is there way to get current user data? without ID use the username?

is there a way like wordpress/wp-json/filter[author]=admin

i try several different way, but still not get it work

**Comment by kadamwhite** [comment]
re: @rmccue's comment:
> the user data should also be included in the body data there as well.
it sounds like what @wesleyxiao's saying is that the body of the response is empty.

@wesleyxiao what version of the plugin are you using, and with what version of WordPress? If you view the `/users/[id]` endpoint for that user, do you see the JSON data as you would expect?

**Comment by wesleyxiao** [comment]
yes, when i try /users/[id] it's does show userdata, i am using wp api 2.0 and wordpress 4.2.2
