### ISSUE TITLE
unable to post taxonomy

### ISSUE THREAD

**Issue by wesleyxiao** [WP-API/WP-API#1313]
var pData = {
			
			'title': 'hello',
			'type': 'job',
			'terms'': {
                               'ID': 10,
					'taxonomy': 'job_category'
					
				
				
			}
		}

here is my code, post is success, but terms taxonomy is empty, can anyone help please

**Comment by danielbachhuber** [comment]
Which version of the plugin is this? Can you share the response details?

**Comment by wesleyxiao** [comment]
problem solve, i hack the wp api code,
I am create the post on app, which every post come with taxonomy job_type

When i looking into code at \plugins\json-rest-api\lib\class-wp-json-meta.php

Its require meta_array['ID'] 

Which mean its only for update static post meta

So i replace update_meta to update_post_meta

So when i create new post i will do
terms
----post_meta: value,
----post_meta: value

So it doesnt need post meta id anymore

Let me know if i doing something wrong

**Comment by wesleyxiao** [comment]
Please delete the above comment i post the wrong thing

**Comment by danielbachhuber** [comment]
@wesleyxiao Deleted. Do you still need help?
