### ISSUE TITLE
Cannot hook the publish event

### ISSUE THREAD

**Issue by enricodeleo** [WP-API/WP-API#1315]
Hi!

I'm trying to do a certain action when I publish new posts in a custom post type. When I publish a new post using the WP's dashboard everything works but if I publish the new post via the APIs the event doesn't seem to be triggered.

I'm testing this simple snippet:

```php
function func_mycsutomtype_publish( $ID, $post ) {
  $registered_device = get_post($ID, 'ARRAY_A');
  error_log($registered_device); // I can see the output on my debug.log only if I publish via web.
}
add_action( 'publish_mycustomtype', 'func_mycsutomtype_publish', 10, 2 );
```

Is it a known issue? Is there any fix? I'm thinking about a cron that watches on new posts but I think it is an overkill and could lead to unpredictable behaviors.

Thank you for your help!

**Comment by danielbachhuber** [comment]
> if I publish the new post via the APIs the event doesn't seem to be triggered.

Can you share the request you're using? Also, which version of the plugin are you running?

**Comment by rachelbaker** [comment]
@enricodeleo We use the `wp_update_post()` and `wp_insert_post()` functions which trigger `wp_transition_post_status()` so your action *should* run.  As Daniel mentioned, can you provide more information so we can try to help?

**Comment by enricodeleo** [comment]
Thank you to both of you!
@danielbachhuber I use the latest stable 1.2.2.
@rachelbaker after I wrote I got that the code leads to wp_transition_post_status, I suppose (but is pure speculation) that the hook isn't triggered because the post doesn't transit from an old status (eg draft) but is published directly. Is it plausible? 

I'm posting from and angularJS with ngResource with a service:

```javascript
myapp

.factory('wpApi', ['$resource', function($resource) {
  return $resource( ApiEndpoint + '/:param1/:param2/:param3/:param4', {} );
}])

.factory('registerDevice', [
  '$rootScope', 
  'wpApi',
  function($rootScope, wpApi) {
    return { 
      add: function() {
        wpApi
        .save(
          { 
            param1: 'posts'
          }, 
          {
            'title': 'test title',
            'content_raw': 'test content',
            'excerpt_raw': 'test excerpt',
            'type': 'mycustomtype',
            'status': 'private',
            'post_meta': [
              {
                  'key': 'key1',
                  'value': 'value1'
              },
              {
                  'key': 'key2',
                  'value': 'value2'
              }
            ]
          }
        )
        .$promise
        .then(
          function(success) {
            // success;
          },
          function(error) {
            // error
          }
        );
      }
    }
}]);
```

(by the way since I use metas I get an error I reported some day ago #1294, but this is another issue)

I tried with postman also, and the call itself works (both with angular and postman) and the post is published correctly. The issue here is just with the hook that isn't triggered.
If I open my dashboard and publish a new post within the same post type from there, the hook is triggered. I'm debugging watching the debug.log, but for the sake of trials I also tried to post a json to  http://requestb.in/ and even there I can get only posts published via the web interface.

**Comment by danielbachhuber** [comment]
> I suppose (but is pure speculation) that the hook isn't triggered because the post doesn't transit from an old status (eg draft) but is published directly instead. Is it plausible?

Ohhhh. That does sound plausible. WordPress admin creates a dummy post with status `auto-draft` when you open the admin to create a new post. You might've discovered an edge case.

**Comment by enricodeleo** [comment]
@danielbachhuber you can call me the lucky man :D 
After a lot of hacking I'm stucked on the only thing I thought would be easy since I thought I just had to use a built-in function :)
I think the only way (even if ugly) at the moment could be a cron, where I have to get all posts, check for new posts from the last routine, do my business logic for each new post discovered (if any). Probably I need to figure out how to store the last cron's execution date/time somewhere because get all posts and do a comparison could be heavy with an increasing number of posts. 
Any ideas?

**Comment by rachelbaker** [comment]
@enricodeleo Instead of using a cron, you could use the `json_insert_post` action: https://github.com/WP-API/WP-API/blob/master/lib/class-wp-json-posts.php#L977

**Comment by enricodeleo** [comment]
@rachelbaker  I didn't know `json_insert_post` but yes, it works! Thank you very much for your suggestion!

**Comment by rachelbaker** [comment]
Closing this issue for now.
