### ISSUE TITLE
posts_per_page with a theme

### ISSUE THREAD

**Issue by clarenced** [WP-API/WP-API#1319]
I have problems using the parameter posts_per_page with a theme (wp-crossroad). 
I think this theme overrides the number of posts to display. In my blog, it's currently 1. 

When I submit a request to like for instance `http://myblog/wp-json/posts?filter[post_per_page]=10`, it always return only one post. 

If I change the number of posts to display from 1 to 5 for instance and if I submit the previous request, 
it will return the 5 recent posts. It seems that the number of posts returned depends of the value configured in the theme options but not with the `posts_per_page` parameter. I think somehow, I don't know the theme overrides the `posts_per_page` param. 

Is this a bug?

**Comment by rachelbaker** [comment]
@clarenced Which version of the plugin are you running?  

It does sound as though your theme is overriding the post_per_page parameter with a filter.  If you were to switch to Twenty Fifteen, do you have the same issue?

**Comment by clarenced** [comment]
I don't have the same problem with Twenty Fifteen. 

The version of the plugin that I use 1.2.2.

**Comment by rachelbaker** [comment]
@clarenced Well that narrows it down to something in your theme overriding the `posts_per_page` value.    Is your theme using a `pre_get_posts` filter?

**Comment by clarenced** [comment]
After grepping `pre_get_posts`, I found this code (in functions.php) : 
```php   
   if ( ! function_exists( 'ct_posts_per_page' ) ) {
    function ct_posts_per_page( $query ) {
        global $data;

if ( ! function_exists( 'ct_posts_per_page' ) ) {
    function ct_posts_per_page( $query ) {
        global $data;
        $blog_num_posts = stripslashes( $data['crossroad_blog_num_posts'] );

        //if ( is_home() || is_page_template('template-blog.php') || is_page_template('template-home.php') ) { 
        if ( is_home() or is_front_page() ) {
            $query->query_vars['posts_per_page'] = $blog_num_posts;
        }
        return $query;
    }/*-----------------------------------------------------------------------------------*/

    if ( !is_admin() ) add_filter( 'pre_get_posts', 'ct_posts_per_page' );
}
        $blog_num_posts = stripslashes( $data['crossroad_blog_num_posts'] );

        //if ( is_home() || is_page_template('template-blog.php') || is_page_template('template-home.php') ) { 
        if ( is_home() or is_front_page() ) {
            $query->query_vars['posts_per_page'] = $blog_num_posts;
        }
        return $query;
    }

    if ( !is_admin() ) add_filter( 'pre_get_posts', 'ct_posts_per_page' );
}

**Comment by clarenced** [comment]
@rachelbaker Why did you close the issue?

**Comment by kadamwhite** [comment]
@clarenced It may not be feasible for you to upgrade, but the latest version of the API (beta 4, at the time of this comment) supports a `per_page=n` query parameter, e.g. `http://myblog/wp-json/posts?per_page=10` (no `filter` needed). I'm not sure how much the logic has changed under the hood but you might be able to get the behavior you want by upgrading and using the new URL query parameter. If that doesn't work, you can re-open this issue with more information about the behavior you are seeing with the latest version.
