### ISSUE TITLE
Can register_api_field be better named?

### ISSUE THREAD

**Issue by kwight** [WP-API/WP-API#1321]
I understand  `register_api_field` is the best way to add any additional property to an endpoint, not just a meta field; for instance, I'm using it to [add post classes](https://github.com/kwight/wp-api-theming/blob/master/wp-api-theming.php#L26). Would a name like `register_api_property` be more appropriate, or is there a different way I should be adding non-meta-field properties?

**Comment by joehoyle** [comment]
@kwight you are using it correctly, it's not just for meta field properties. Will raise this is a discussion point in our next meeting.

**Comment by rachelbaker** [comment]
+1 to @joehoyle's comment above.  
The function is meant to add data to a given endpoint response object, so `property` may be a better fit based on the purpose of the function.  Naming things is hard.

**Comment by rachelbaker** [comment]
@rmccue and I had a quick discussion about this to see if we could resolve for Beta 3.  We agreed that naming things is hard, and couldn't come to a quick consensus.  Pushing to Beta 4.

**Comment by rmccue** [comment]
P.S. let's get `rest` into the name when we change it rather than `api`

**Comment by jamesgol** [comment]
Was going to open up an issue on this because I noticed the naming discrepancy.  Is this going to be switched to register_rest_field()?

**Comment by danielbachhuber** [comment]
Closing in favor of https://core.trac.wordpress.org/ticket/34730

**Comment by danielbachhuber** [comment]
Actually, we're going to back it out of core, as it's conceptually tied to `WP_REST_Controller`

**Comment by joehoyle** [comment]
decided on `regiister_rest_field`

**Comment by danielbachhuber** [comment]
Let's rename to `register_rest_field()`, and include a backwards compat shim for `register_api_field()` for a few releases.

**Comment by danielbachhuber** [comment]
I'm leaning back towards `register_rest_property()`... @WP-API/amigos thoughts?

**Comment by danielbachhuber** [comment]
`register_rest_field()` it will be.

**Comment by roikles** [comment]
Will `register_api_field` be used as an alias as it is still used in the documentation here: http://v2.wp-api.org/extending/modifying/

**Comment by danielbachhuber** [comment]
> Will register_api_field be used as an alias?

Nope.

> It is still used in the documentation here

Sorry about that. I've updated https://github.com/WP-API/docs-v2/pull/78
