### ISSUE TITLE
comment's content did not load as expected

### ISSUE THREAD

**Issue by helmiruza** [WP-API/WP-API#1325]
Hi,..

I tried to load the comments for a specific post, using this url (http://www.arenakereta.com/wp-json/posts/73143/comments/1503844).

it is supposed to fetch the comment as appeared in the original comment (http://www.arenakereta.com/2015/05/31/peraduan-perodua-untuk-memenangi-myvi-edisi-komemoratif/)

But from the json, the content is somehow empty. Here is the json returned -

```
{"ID":1503844,"post":73143,"content":"<div class=\"ldc-cmt-box clearfix\"><span class='ldc-ul_cont' onclick=\"alter_ul_post_values(this,'','c_like')\" >Terbaik!<img src=\"http:\/\/www.arenakereta.com\/wp-content\/plugins\/like-dislike-counter-for-posts-pages-and-comments\/images\/up.png\" \/>(<span>0<\/span>)<\/span><span class='ldc-ul_cont' onclick=\"alter_ul_post_values(this,'','c_dislike')\" >Booo~<img src=\"http:\/\/www.arenakereta.com\/wp-content\/plugins\/like-dislike-counter-for-posts-pages-and-comments\/images\/down.png\" \/>(<span>0<\/span>)<\/span><\/div>\n<div style=\"clear:both;\"><\/div>\n","status":"approved","type":"comment","parent":0,"author":{"ID":0,"name":"Bebe","URL":"","avatar":"http:\/\/0.gravatar.com\/avatar\/8d7f8f96834d152aa4f1ab35a7e8ebd4?s=96"},"date":"2015-06-02T13:20:58","date_tz":"Etc\/GMT+8","date_gmt":"2015-06-02T05:20:58","meta":{"links":{"up":"http:\/\/www.arenakereta.com\/wp-json\/posts\/73143"}}}
```

is this a plugin issue or my site's issue?
Thanks

**Comment by rmccue** [comment]
It doesn't seem like the content is empty here? There is a decent amount of HTML in it, so I suspect you might have a plugin changing the data in here in a weird way.
