### ISSUE TITLE
API V2 filter issue

### ISSUE THREAD

**Issue by jjmu15** [WP-API/WP-API#1329]
When using the filter query to get posts for a specific category for example, the filter is ignored and all posts are returned. 

Filtering the below works in V1 of the API (which I have reverted to for now) but in V2 it seems to be ignored completely.
`/wp/v2/posts?filter[cat]=3`

**Comment by manuelro** [comment]
I have the exact same problem. All filters are just ignored in V2.

**Comment by joehoyle** [comment]
v2 does not use the `filter` query var - currently you can specify the WP_Query vars directly ala `/wp/v2/posts?cat=3` however this is subject to change per https://github.com/WP-API/WP-API/issues/924

**Comment by manuelro** [comment]
Good to know. I've been reading (http://wp-api.org/#posts_retrieve-posts)[the docs] and it says you should use it as `filter[foo]=bar`.

**Comment by joehoyle** [comment]
http://wp-api.org/ is for v1, see http://v2.wp-api.org/ for v2

**Comment by manuelro** [comment]
Awesome. Thanks for the link.

**Comment by manuelro** [comment]
By the way, is there any page where I can see what filters are still available? `posts_per_page` (and many others from V1) doesn't seem to work as for `/wp/v2/posts?posts_per_page=1`.

**Comment by danielbachhuber** [comment]
> By the way, is there any page where I can see what filters are still available?

There will be soon. It's contingent on #924 and #1222
