### ISSUE TITLE
current_user_can and version 1.2.2 also 2.0-beta2

### ISSUE THREAD

**Issue by NowellVanHoesen** [WP-API/WP-API#1335]
I've added a custom capability for making sure only people with it can access certain custom endpoints. Everything was working fine with using current_user_can for the custom capability until recently. I wish I could specify which version last worked.

I can remove the check for the capability, but would like to have that added bit of security.

**Comment by rmccue** [comment]
Without seeing the code that you're using here, it's kinda impossible to diagnose. I'm not sure what you mean by the custom capability: are you running a `current_user_can` check on a hook? Or is this in a custom endpoint?

**Comment by NowellVanHoesen** [comment]
I'm using the `current_user_can` as the first code in a custom endpoint. 
Dumping `wp_get_current_user()` from within the same custom endpoint returns an empty array:
`{"data":{},"ID":0,"caps":[],"cap_key":null,"roles":[],"allcaps":[],"filter":null}`

Here's the code adding the custom capability

```
	add_action( 'admin_init', 'nvog_hartzelprop_roles' );
	function nvog_hartzelprop_roles() {
		$admin_role = get_role( 'administrator' );
		if ( ! $admin_role->has_cap( 'hartzel_manager' ) ) {
			$admin_role->add_cap( 'hartzel_manager' );
		}
	}
```

**Comment by NowellVanHoesen** [comment]
where's the proper place to upload the files?

**Comment by samwilson** [comment]
Could this be because you're not setting the `X-WP-Nonce` header?

**Comment by NowellVanHoesen** [comment]
It's added to each ajaxSend:
```javascript
	// add nonce to the ajaxSend url
	$(document).ajaxSend(function(event, XMLHttpRequest, ajaxOptions) {
		XMLHttpRequest.setRequestHeader( 'X_WP_NONCE', WP_API_Settings.nonce );
	});
```

the custom route where I found the issue:
```php
		/* get customer list, create new customer */
		$routes['/hartzell/customer'] = array(
			array( array( $this, 'getCustomers' ), WP_JSON_Server::READABLE ),
			array( array( $this, 'newCustomer' ), WP_JSON_Server::CREATABLE | WP_JSON_Server::ACCEPT_JSON ),
		);
```

the function for readable
```php
	public function getCustomers() {
		if ( ! current_user_can( 'hartzel_manager' ) ) {
			return "User Can't";
		}
		$db_conn = hdb_connect();

		$offset = ( isset( $_GET['skip'] ) ) ? ( int ) $_GET['skip'] : 0;
		$limit = ( isset( $_GET['top'] ) ) ? ( int ) $_GET['top'] : 20;

		$whereValue = ( ! empty( $_GET['filter'] ) ) ? '%' . $db_conn->esc_like( $_GET['filter'] ) . '%' : NULL;
		if ( empty( $whereValue ) ) {
			$customerQuery = $db_conn->prepare( "SELECT * FROM customer ORDER BY company LIMIT %d, %d", array( $offset, $limit ) );
			$countQuery = "SELECT * FROM customer ORDER BY company";
		} else {
			$customerQuery = $db_conn->prepare( "SELECT * FROM customer WHERE company LIKE %s ORDER BY company LIMIT %d, %d", array( $whereValue, $offset, $limit ) );
			$countQuery = $db_conn->prepare( "SELECT * FROM customer WHERE company LIKE %s ORDER BY company", $whereValue );
		}

		$allCustomers = $db_conn->get_results( $countQuery, ARRAY_A );
		$totalCustomers = count( $allCustomers );
		$totalPages = ceil( $totalCustomers / $limit );

		$customers = $db_conn->get_results( $customerQuery, ARRAY_A );
		wp_send_json( array( 'totalItems' => $totalCustomers, 'totalPages' => $totalPages, 'data' => $customers, 'query' => $customerQuery ) );
	}
```

If I comment out the current_user_can check it works. I would like to limit it to a specific capability.

**Comment by NowellVanHoesen** [comment]
I started a new branch and rewrite the custom endpoints for wp-api beta 2 and am having the same issue. Using a permission_callback that checks the user current_user_can returns an error
```
[{"code":"rest_forbidden","message":"You don't have permission to do this.","data":{"status":403}}]
```

comment out the permission_callback, and the expected data is returned.

```php
		/* get customer list, create new customer */
		register_rest_route( 'hartzell/v1', '/customer', array(
			array(
				'callback' => array( $this, 'getCustomers' ),
				'methods' => WP_REST_Server::READABLE,
				'permission_callback' => array( $this, 'get_customer_permission_check' ),
			),
			array(
				'callback' => array( $this, 'createCustomer' ),
				'methods' => WP_REST_Server::CREATABLE,
				'permission_callback' => array( $this, 'create_customer_permission_check' ),
				'args' => array(),
			),
		) );
```
the permission callback
```php
	public function get_customer_permission_check() {
		return $this->check_hartzell_manager();
	}
	private function check_hartzell_manager() {
		return current_user_can( 'hartzel_manager' );
	}
```
I've tried  dumping the results of ```wp_get_current_user()```, it returns the array expected when the user isn't logged in. I assume when logged in as admin and this code is running from an admin page, the cookie auth would work as it did in the past.

header info for the request

```
Accept:application/json, text/javascript, */*; q=0.01
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Cache-Control:max-age=0
Connection:keep-alive
Cookie:wp-settings-1=ed_size%3D333%26hidetb%3D1%26editor%3Dtinymce%26urlbutton%3Dfile%26libraryContent%3Dbrowse%26align%3Dnone%26imgsize%3Dmedium%26mfold%3Df%26post_dfw%3Doff; wp-settings-time-1=1433801357; wordpress_test_cookie=WP+Cookie+check; wordpress_logged_in_d3e2991717750a8faf2bc5899cc2edfd=nvwd%40hp%7C1435704003%7ClNtKnr941Ivp5vWkWsgXCCdaVLgDD3rnCBFuI8ULYAj%7C7bfa8e81b15ac18decbbd55f7e8b2c19dc0a09ed75e199990666bc26e43c24e4; optimizelyEndUserId=oeu1391445626588r0.6266358359716833; km_ai=YJfW4nx28sSvV3M7dCbBhzOwmsQ%3D; km_lv=x; optimizelySegments=%7B%7D; optimizelyBuckets=%7B%7D; kvcd=1418869904552; km_uq=; __utma=11364459.1941289271.1389835812.1432130440.1433115236.34; __utmc=11364459; __utmz=11364459.1407362725.19.2.utmcsr=nvwebdev.bidsketch.com|utmccn=(referral)|utmcmd=referral|utmcct=/account; PIWIK_SESSID=gh0o44jlj5ttpears4mp9rj3h2
DNT:1
Host:test.nvwebdev.com
Referer:http://test.nvwebdev.com/hartzell/wp-admin/admin.php?page=hartzel-subscriptions
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36
X-Requested-With:XMLHttpRequest
X_WP_NONCE:31a71f732f
```

what else can I provide to help track this down?

**Comment by NowellVanHoesen** [comment]
While logged in as and admin I tried wp-json/wp/v2/users and received the same error:
```
[{"code":"rest_forbidden","message":"You don't have permission to do this.","data":{"status":403}}]
```

Seems to be the same issue I'm seeing.
currently using WP 4.2.2 and WP-API Beta 2

**Comment by NowellVanHoesen** [comment]
@rmccue what else can I provide to help track this down?

**Comment by rmccue** [comment]
It could be that your header naming is wrong; it should be `X-WP-Nonce`. Capitalisation doesn't matter, but the underscores vs dashes might be.

Just to confirm, you're generating the nonce fresh on the site while logged in? Nonces are time- and user-based.

In `extras.php` for v2, can you try checking values in `rest_cookie_check_errors` to see what's happening in there? That's the part where authentication with nonces is checked, so seems like there must be an issue in there.

**Comment by NowellVanHoesen** [comment]
Thanks @rmccue.
I will try that once I get back to my computer, and report back.

**Comment by NowellVanHoesen** [comment]
@rmccue That seems to have been the issue.
Thank you!
