### ISSUE TITLE
Post__not_in filter not working

### ISSUE THREAD

**Issue by gthaniotis** [WP-API/WP-API#1338]
Hello,

I'm trying to exclude certain posts and after following the instructions in #921, this is still not working.
I have created a plugin which uses shortcodes to specify parameters (e.g. category name, excluded posts) to be passed to a remote url and fetch the results. No matter how I pass the params array, I can never bet the posts to be excluded.
Any ideas as to what might be happening? Is this a pending issue?

Thanks!

**Comment by rachelbaker** [comment]
@gthaniotis what version of the plugin are you using?

**Comment by mdunbavan** [comment]
What is the outcome of this then?

**Comment by gthaniotis** [comment]
Hello,

I'm using the plugin version 1.1.1.

Thanks,

George

**Comment by mdunbavan** [comment]
@gthaniotis but what does that mean? Does it work with 1.1.1?

**Comment by gthaniotis** [comment]
No, it does not work with this version. I have installed the plugin from the WordPress plugins repository.

**Comment by mdunbavan** [comment]
@gthaniotis and does it work with that version?

**Comment by rmccue** [comment]
Both in v1 and v2, the parameter is only available for authenticated users. See #1357.
