### ISSUE TITLE
pagination has some issue

### ISSUE THREAD

**Issue by iffifan** [WP-API/WP-API#1341]
I downloaded this plugin from Wordpress Plugins Repository, installed it on my wordpress website but never got it working with pagination. I tried every possible way to get it working.

Then I thought about searching for the reason and I jumped into the code of plugin.

I edited code a little and found something strange

url: http://jetsfansunited.com/wp-json/posts?filter[posts_per_page]=3&page=5&filter[orderby]=post_date&filter[order]=asc

Wordpress version: 4.1.5

I used this code:
in public function get_posts
$response->set_data( $post_query );

and i got this result:

"query": {
"post_type": [
"post"
],
"order": "asc",
"orderby": "post_date",
"posts_per_page": "3",
"paged": 5
},
"query_vars": {
"post_type": [
"post"
],
"order": "ASC",
"orderby": "post_date",
"posts_per_page": 3,
"paged": 1,
"error": "",
"m": "",
"p": 0,
"post_parent": "",
"subpost": "",
"subpost_id": "",
"attachment": "",
"attachment_id": 0,
"name": "",
"static": "",
"pagename": "",
"page_id": 0,
"second": "",
"minute": "",
"hour": "",
"day": 0,
"monthnum": 0,
"year": 0,
"w": 0,
"category_name" 

So in "query" array paged = 5, and in "query_vars" it is 1. That is why pagination was not working..
Now I need your help about what to do with this? change code? use any other version?

please help

**Comment by iffifan** [comment]
no one?

**Comment by joehoyle** [comment]
@iffifan it sounds possible that you have a plugin (or otherwise) overwriting the `posts_per_page` via a filter. Do you still see this behaviour with all plugins disabled using the default 2015 theme?

**Comment by mkiisoft** [comment]
Yep @joehoyle looks like @iffifan has some other plugin or snippet overwriting posts_per_page. I use the same end point on my website and pagination works.

@iffifan try to make a fresh install of WP-API and desactivate all plugin (the activate 1 by 1).

**Comment by rmccue** [comment]
Closing, seems like a plugin issue.
