### ISSUE TITLE
Retrieving a term with term_id

### ISSUE THREAD

**Issue by storynory** [WP-API/WP-API#1342]
If I list categories with /wp-json/taxonomies/category/terms/

The response gives an ID for each term,  for example ID: 16

But if I then try to retrieve that term with 

/wp-json/taxonomies/category/terms/16

I get a different term from the one  expected. 

I think this is a confusion between term_id and taxonomy_term_id . 

Is there a way round this? How can we find out the term_id instead of the taxonomy_term_id?

**Comment by mackensen** [comment]
This sounds like #729, which is fixed on develop but not (near as I can tell) on stable.

**Comment by danielbachhuber** [comment]
v2.x uses `taxonomy_term_id`. If you need to use `term_id`, you'll need to write your own custom endpoint.
