### ISSUE TITLE
Assigning alt_text for attachment

### ISSUE THREAD

**Issue by ayublin** [WP-API/WP-API#1343]
Upon creating an attachment, `title`, `caption` and `description` can be set:

https://github.com/WP-API/WP-API/blob/3035bdf630f8d65a9e7564f8eae2298827ece6d0/lib/endpoints/class-wp-rest-attachments-controller.php#L125-L141

But not `alt_text`, it's supported only via update method:

https://github.com/WP-API/WP-API/blob/3035bdf630f8d65a9e7564f8eae2298827ece6d0/lib/endpoints/class-wp-rest-attachments-controller.php#L105-L107

Is it not going to be supported to assign `alt_text` upon creation?

**Comment by rachelbaker** [comment]
Fixed in 2289c1f
