### ISSUE TITLE
JS Client: Can't filter CPT collection by ID after creation

### ISSUE THREAD

**Issue by joneslloyd** [WP-API/WP-API#1344]
Hi there,

In a previous issue (now resolved) I successfully created a Custom Post Type Model and Custom Post Type collection in the WP-API JS Client:
https://github.com/WP-API/WP-API/issues/1299#issuecomment-105624493

However, I'm now trying to filter my existing Custom Post Type collection based on an ID of a particular custom post type, like so:

    self.events.fetch({
            ID: the_id,
        }).done( function() {
            //EXPECTING ONLY ONE EVENT HERE
            console.log(self.events);
        });

And / or:

    //EXPECTING ONLY ONE EVENT HERE
    var the_event = self.events.where({ID : the_id});
    console.log(the_event);

However neither of these are filtering the Custom Post Types (events in my case), so I get the full collection, rather than a single event.

Do you know if I'm doing this wrong or whether there's an error / issue?

**Comment by joneslloyd** [comment]
Also, doing this also doesn't work (filter in the fetch) :

    self.events.fetch({
        filter: {ID: the_id},
    }).done( function() {
        //EXPECTING ONLY ONE EVENT HERE
        console.log(self.events);
    });

**Comment by rmccue** [comment]
Possibly `ID` should be `id`? Not sure here without more about your actual data and code.

**Comment by joneslloyd** [comment]
Hi @rmccue - No that doesn't make any difference.

I've simplified the code both in the previous github issue and this one to make it more generic and user friendly for others viewing it. My actual code is as follows:

    render: function() {
	    
	  self = this;
	  
	  var template_type = self.template_type;

      if(template_type == 'event'){
	      
	    var event_id = self.data;
	    
	    self.the_events.fetch({
		    filter: {
			    ID : event_id,
			},
	    }).done(function(){
		    console.log(self.the_events);
	    });

		if(the_event.length > 0){
			self.template = _.template(jQuery("#template-" + template_type).html(),{event: the_event});
			jQuery(self.el).html(self.template);	
		}
		else{
			self.renderError();
		}
      }
      else{
	    self.template = _.template(jQuery("#template-" + template_type).html());
	   	jQuery(self.el).html(self.template);   
      }
      
      self.$el.fadeIn('500');
      
      self.ev.trigger('sidebar:sizechanged', {width: this.$el[0].scrollWidth, height: this.$el[0].scrollHeight, leftoffset: this.$el.offset().left});
      
      self.delegateEvents();
      
      return this;
    },

**Comment by joneslloyd** [comment]
Hi, Just wondering if this is solved in the new BETA 4?

I've not re-tested my code yet, but wanted to ask you guys first.

Cheers

**Comment by joneslloyd** [comment]
Just to update you, I've checked the above, and the current JS client can still not filter custom post types by any criteria.

For example, this doesn't work:


    self.the_events.fetch({
        filter: {
            ID : event_id,
        },
    }).done(function(){
        console.log(self.the_events);
    });

**Comment by danielbachhuber** [comment]
There's some work happening on the JS client currently. Expect an update soon!

**Comment by joneslloyd** [comment]
That is extremely exciting news! Thanks for the update!
