### ISSUE TITLE
How to correctly search using the V2 javascript client

### ISSUE THREAD

**Issue by joneslloyd** [WP-API/WP-API#1350]
Hello,

How do I correctly perform a search on a collection of Posts using the JS API in V2?

Currently I have:
    
    var The_Event = wp.api.models.Post.extend({
				urlRoot: WP_API_Settings.root + '/the_event',
				defaults: {
					type: 'the_event'
				}
			});

    var The_Events = wp.api.collections.Posts.extend({
				url: WP_API_Settings.root + '/the_events',
				model: The_Event,
			});

    var my_events = new The_Events({
		    data: {
			    filter: {
				    s: 'happy',
			    },
		    },
	    });

However, all posts of my CPT are returned, rather than just those with the word 'happy' in (presumably) their title / content.

I've tried replacing this:

    var my_events = new The_Events({
		    data: {
			    filter: {
				    s: 'happy',
			    },
		    },
	    });

With this:

    var my_events = new The_Events({
		    filter: {
		         s: 'happy',
		     },
	    });

Or this:

    var my_events = new The_Events({
		    s: 'happy',
	    });

But nothing seems to return my filtered search results.

**Comment by rmccue** [comment]
`s` should work in v2, and appears to work on the demo site: http://demo.wp-api.org/wp-json/wp/v2/posts?s=libero

Right now, the JS SDK doesn't work with v2. See #1374

**Comment by joneslloyd** [comment]
You're right - it's working in V2, just not the JS SDK.

The JS SDK does otherwise seem to be working though - just this isn't. I'll watch the updates.

**Comment by Jany-M** [comment]
Any updates on this? http://demo.wp-api.org/wp-json/wp/v2/posts?s=libero does not work actually.
It just shows all posts, regardless the `search`string.
