### ISSUE TITLE
Get rid of wpautop in responses?

### ISSUE THREAD

**Issue by enricodeleo** [WP-API/WP-API#1351]
Hi everyone,

I just noticed that if I query for a custom post type I get both content and excerpt wrapped between &lt;p&gt; tags and with a final \n at the end even if the actual content of the post is text-only.
At the moment I fixed this behavior by using a .replace(/<[^>]+>/gm, '') within my javascript app, but I think it would be tidier to avoid wpautop (I suppose there is wpautop behind the scenes) when not need (e.g. in the excerpt). Is there a way to accomplish so?

Thank you in advance!

**Comment by rmccue** [comment]
This is intentional. If you want the raw content without `wpautop`, `wptexturize`, shortcodes, etc, then you need to use `content.raw` (`content_raw` in v1). However, it does require authentication, as the pre-filtered content might have shortcodes/etc with private data in them.

**Comment by enricodeleo** [comment]
Thank you for the hint! :)
