### ISSUE TITLE
Author filter returns no data

### ISSUE THREAD

**Issue by TheeBryanWhite** [WP-API/WP-API#1356]
WordPress ver. 4.2.2, Plugin ver. 1.2.2

A simple request to the API via:

http://example.com/wp-json/posts?filter[author]=2

No data is returned. Posts retrieved with no filter as well as the author_name filter but using the author filter returns an empty object.

**Comment by federicovezzoli** [comment]
I've the same issue with the v2 api, insted it returns all the posts.
my request is like this:

http://italyprodiet:8888/wp-json/wp/v2/paziente?filter%5Bauthor%5D=2
