### ISSUE TITLE
Make post__not_in available for unauthenticated requests

### ISSUE THREAD

**Issue by doodirock** [WP-API/WP-API#1357]
Is there anyway to exclude a post from posts without needing to authenticate?  I have a simple ajax call set up, but don't want to set up auth for one simple request.  Not sure if its doable within the API

**Comment by rmccue** [comment]
You need to add the `post__not_in` filter, which alas, is only available on authenticated responses right now. I'm not sure as to why it's marked as private in WordPress, but we could potentially look at making this public instead.

In the meantime, if you control the server, you can add this to a plugin or theme:
```php
add_filter( 'query_vars', function ( $vars ) {
	$vars[] = 'post__not_in';
	return $vars;
} );
```

**Comment by danielbachhuber** [comment]
This will be handled in #1668
