### ISSUE TITLE
V1: is there any way to filter /posts/types?

### ISSUE THREAD

**Issue by manuelro** [WP-API/WP-API#1358]
Is there any way to filter types the same way we filter posts? Say, I want to get only type with slug `foo`, I would then do something like `/posts/types?filter[slug]=foo`. Any thoughts?

**Comment by oskarrough** [comment]
Yea, you can do something like:

`/posts?type=customPostType&filter[name]=my-slug`

Notice how it's called `name` and not `slug`. Not sure why but it works for me!
