### ISSUE TITLE
post update with featured image did not work until ...

### ISSUE THREAD

**Issue by eflatz** [WP-API/WP-API#1359]
Hi,

I had error sending update (PUT) request for posts to attach featured image which is uploaded in the request before. Wordpress would return 500 internal server error. After debugging the process I discovered in the class-wp-json-media.php ( function attach_thumbnail( $post, $data, $update ) ) wrong parameter passing to set_post_thumbnail function.

Currently in the source code:
set_post_thumbnail( $post['ID'], $thumbnail['ID'] );
-> this throws error because $thumbnail does not have ID property but its child data property instead

So after putting:
set_post_thumbnail( $post['ID'], $thumbnail->data['ID'] );
-> you can pass json {"featured_image":(int) post id } on wp-json/post/post_id and featured image is attached to post

Can this be updated in the next release?

Thanks,
Emil

**Comment by tomaslieven** [comment]
I had same issue with this fix:
set_post_thumbnail( $post['ID'], $thumbnail->data['ID'] );
i dont get any more 500 on PUT. Thanks!

**Comment by tommedema** [comment]
I'm using the stable version of the API and get the following when I do a PUT /posts/id with `"featured_image": 48`:


        Fatal error: Cannot use object of type WP_JSON_Response as array in /home/tom/projects/chambeng/chambeng-scms/wordpress/wp-content/plugins/json-rest-api/lib/class-wp-json-media.php on line 437

**Comment by tommedema** [comment]
This seems to be fixed when changing from stable to `master` branch. However, I still cannot set a featured image when doing a POST /posts. It can only be set using PUT.

**Comment by danielbachhuber** [comment]
@rachelbaker was this closed in 1.2.3?
