### ISSUE TITLE
multiple taxonomy param filter possible?

### ISSUE THREAD

**Issue by wesleyxiao** [WP-API/WP-API#1362]
/posts?type=job&filter[taxonomy]=job_category&filter[term]=waiter&filter[taxonomy]=location_state&filter[term]=california

try to get   

taxonomy : job_category
term: waiter

and 

taxonomy: locaiton_state
term: carlifornia

but my test result only get the second taxonomy which is location_state, not taxonomy job_category and location_state

**Comment by msankar1991** [comment]
@wesleyxiao , Did you got solution for above problem for filter with multiple taxonomies. Could please post the solution for this problem it will helpful to me also.

I'm having issue with /posts/?lang=en&filter[taxonomy]=property_category&filter[term]=houses&filter[taxonomy]=property_type_category&filter[term]=for-sale
