### ISSUE TITLE
/users/me route redirects, losing nonce

### ISSUE THREAD

**Issue by Arlen22** [WP-API/WP-API#1365]
I have version 1.2.2 of the WP REST API, and when I do a get request in angular to `/users/me?wp_json_nonce=mynonce`, it redirects me to `/users/{current_user}` and loses the nonce. Whereupon the browser redirects to the new url (without the nonce) and gets a 403 error. This is line 112 of class-wp-json-users.php. If I comment out these two lines, it works as expected.

    $response->header( 'Location', $data['meta']['links']['self'] );
    $response->set_status( 302 );

**Comment by rmccue** [comment]
As noted on #1394, this is intentional. If you're using a client that follows redirects without the ability to disable this (such as a browser), send `?_envelope` to get the header and status in the body instead.

**Comment by Arlen22** [comment]
So the redirect is intentional, but what about the nonce getting dropped (or rather the query string)?

**Comment by Arlen22** [comment]
@rmccue, is the `?_envelope` parameter in v1.2.3? Or only in v2? I am using v1.2.3.
