### ISSUE TITLE
Is there any info about user registration?

### ISSUE THREAD

**Issue by wesleyxiao** [WP-API/WP-API#1373]
I want user can register over mobile app, but i am search around didnt find any tutorial or information about this, can someone prviode some information thanks

**Comment by wesleyxiao** [comment]
ok i try post user data over to users, to create a new user

$http.post(SITE_INFO.siteURL+'/users/', data).success(function(data){
			console.log(data);
		})

but it callback error show [Object { code="json_cannot_create",  message="Sorry, you are not allowed to create users."}]

**Comment by mkiisoft** [comment]
For the research I've made... you need this little babies:

https://wordpress.org/plugins/json-api-auth

https://wordpress.org/plugins/json-api-user/

Looks like WP API doesn't have all the user Auth thing. Didn't test it yet but also need it for mobile apps.

**Comment by rachelbaker** [comment]
@wesleyxiao When making the request to create a new user, you need to authenticate as a user that has permission to create a new user.  Here is where you can find out more about the authentication options: http://wp-api.org/guides/authentication.html

Closing this issue for now. Feel free to re-open or create a new issue as needed.
