### ISSUE TITLE
Find Post by Slug

### ISSUE THREAD

**Issue by yanismydj** [WP-API/WP-API#1375]
A common use case is to find a Post by its slug, in fact, I don't know many cases where finding by ID is as helpful as finding by slug in the real world.  It'd be great if this functionality could be added.  Otherwise, this plugin is so much better than the alternatives -- great work to all those involved! :+1:

**Comment by swissspidy** [comment]
This question has been answered multiple times already here on GitHub, please try a search.

You can manage to do that using the `filter` parameter, i.e. `/posts?filter[name]=my-slug` looks for posts with the slug `my-slug`

**Comment by danielbachhuber** [comment]
And for the history as to why it's not an endpoint, check out #642

**Comment by analytik** [comment]
What about v2 beta? Since the documentation is incomplete, and `?s=slug-name` just doesn't work. I have to use `/?s=slug+name`, and that works *occasionally*.

**Comment by royboy789** [comment]
I created a custom endpoints for this:
`function register_routes( $routes ) {
		
		register_rest_route( 'wp/v2', 'post_by_slug', array(
			'methods' => 'GET',
			'callback' => array( $this, 'get_post_by_slug' ),
			'args' => array(
				'slug' => array (
					'required' => false
				)
			)
		) );
		
	}
	
	function get_post_by_slug( WP_REST_Request $request ) {
		
		$slug = $request['slug'];
		$return['slug'] = $slug;
		
		$return['post'] = get_page_by_path( $slug, ARRAY_A, 'post' );
		$return['post']['comments'] = get_comments( array( 'ID' => $return['post']['ID'] ) );
		
		$response = new WP_REST_Response( $return );
		return $response;
			
	}`

**Comment by analytik** [comment]
Thanks! Very helpful.
