### ISSUE TITLE
Not working on Wordpress 4.2.2?

### ISSUE THREAD

**Issue by Adagal** [WP-API/WP-API#1376]
I cannot get the API working in wordpress 4.2.2, when I access /wp-json/posts I get a 404 error.

**Comment by Kaz-** [comment]
You have to change your permalink parameter, to enable URL rewrite.

**Comment by rachelbaker** [comment]
It appears as though this issue was resolved.  Closing this issue for now, feel free to re-open or file another issue as needed.
