### ISSUE TITLE
/posts/ID – content/post_content is empty

### ISSUE THREAD

**Issue by CodeBrauer** [WP-API/WP-API#1377]
This is the route I call:

http://wp2.dev.local/wp-json/posts/417

I expected the json result would contain the `post_content` but it is an empty string.

This is the row from the database:
```
ID  post_author post_date           post_date_gmt       post_content                post_title  post_excerpt    post_status comment_status  ping_status post_password   post_name   to_ping pinged  post_modified   post_modified_gmt   post_content_filtered   post_parent guid    menu_order  post_type   post_mime_type  comment_count
417 1           2015-07-01 12:52:06 2015-07-01 10:52:06 Lorem Ipsum Dolor Sit Amet. A test      publish closed  closed      a-test          2015-07-01 15:19:53 2015-07-01 13:19:53     0   http://wp2.dev.local/?post_type=products&#038;p=417 0   products        0
```

It's a custom post type - I also use the [themosis framework](https://github.com/themosis/framework)

Anything else looks fine. I also checked any hooks like `the_content` ...

Do I have to add something special to `register_post_type` to make it work?

Currently my args are:

```php
'public' => true,
'supports' => ['title', 'editor']
```

**Comment by rachelbaker** [comment]
@CodeBrauer I assume you using the 1.x version of the plugin.  If you are receiving the post object response for your custom post type, but just the `content` value is an empty string then something must be hooking into the `the_content`.   

Do you receive the expected `content` value for posts and pages requests?

**Comment by CodeBrauer** [comment]
Sorry, forget to post it here, just found a dynamic built hook for `the_content` (so searching for `the_content` wasn't showing up that one) that was generating an `@`-suppressed error.
