### ISSUE TITLE
filter by post__not_in needs to be available when looking for similar posts to current post

### ISSUE THREAD

**Issue by mdunbavan** [WP-API/WP-API#1378]
Hi,

I am trying to use the wp rest api to get similar posts on a post page.

The post__not_in needs to be available so I can do this. If this is not possible, how can I achieve the same thing above without post__not_in when retrieving similar posts to current post?

Cheers

**Comment by rachelbaker** [comment]
@mdunbavan Assuming you are using version 1.x, you can add the `post__in` query parameter using the `json_query_vars` filter: https://github.com/WP-API/WP-API/blob/master/lib/class-wp-json-posts.php#L148

Closing this issue for now, feel free to re-open or file another issue as needed.
