### ISSUE TITLE
Associating terms to posts on creation incredibly cumbersome

### ISSUE THREAD

**Issue by jdolan** [WP-API/WP-API#1379]
I've poured over a handful of tickets here regarding support for simply passing an array of term names or term IDs when creating a post in order to associate them. It's a very reasonable request, and yet some of these issues are over a year old. There have even been numerous patches and plugins made to add this functionality, but nothing as been adopted because the developers apparently want a grand engineering solution instead.

So the current `develop` HEAD offers the following path:

 1. Create the post.
 1. Retrieve the list of terms for each taxonomy in question. While `get_terms` offers handy criterion like `name` and `slug` (both supporting arrays), its REST counterpart `get_items` offers only the more esoteric `search` criterion. The documentation for this function is not encouraging. Is it even possible to ask the endpoint to return a set of terms from an array of names?
 1. Reconcile the returned, paginated, and possibly exhaustive list of terms against the terms the client wishes to associate to the post.
 1. For terms that do not yet exist in Wordpress, create each term in a separate request.
 1. Finally, post the merged list of term IDs to associate them.
 1. Repeat steps 3-5 for each taxonomy in question.

Really? This isn't a code smell for the team? Being a little dogmatic, are we?

We're talking about _tags on a blog post_. Not only a trivial technical problem, but also core functionality for a blog API. So why go to great lengths to over-complicate the problem and over-engineer what, at the end of the day, should be [10 lines of code](http://plugins.svn.wordpress.org/json-rest-api-wp-api-categories-and-tags/trunk/json-rest-api-patch.php) (now stale)?

I apologize for the tone of this bug report but, man, where is the thought leadership here? REST, yay. HATEOAS, yay. But don't abandon common sense and pragmatism.

**Comment by danielbachhuber** [comment]
> developers apparently want a grand engineering solution instead.
>
> [...]
>
> We're talking about tags on a blog post. Not only a trivial technical problem, but also core functionality for a blog API. So why go to great lengths to over-complicate the problem and over-engineer what, at the end of the day, should be 10 lines of code (now stale)?

There are more problems to solve than just associating tags with a post, as documented in #561. We welcome your suggestions as to how we solve the problem in the abstract.

Given we are talking about a work in progress, and we have a [number of technically-challenging issues to solve](https://github.com/WP-API/WP-API/issues?q=is%3Aopen+is%3Aissue+label%3ADiscussion), I think it's fair to say we haven't committed on a direction yet, because we don't yet have a direction we all feel comfortable living with for the next 10+ years.

Your comment seems to be discounting the _thousands_ of developer hours that have gone into this project. If it seems like an easy decision for you to make, then there's probably a reason why we haven't made it yet.

> While get_terms offers handy criterion like name and slug (both supporting arrays)

This seems reasonable enough to add.

**Comment by jdolan** [comment]
I guess my point is that not everything warrants a grand abstraction. Or, if that abstraction can't be delivered soon, consider offering folks a convenient and functional alternative for the time being.

Anyway, another bug to report with term associations: I'm getting HTTP 403 when trying to associate tags to a Post. I'm issuing the request with an authenticated administrator account.

![screen shot 2015-07-02 at 6 23 44 pm](https://cloud.githubusercontent.com/assets/643118/8489247/8b67cc7e-20e7-11e5-8e4e-292030e29773.png)

The Post is in draft status. The term exists.

**Comment by danielbachhuber** [comment]
> I guess my point is that not everything warrants a grand abstraction.

I agree — and this is also a project needing design decisions to last us years. If you're working on a bespoke project, it's completely possible for you to write a bit of additional code to handle the implementation however you'd like.

> I'm getting HTTP 403 when trying to associate tags to a Post. I'm issuing the request with an authenticated administrator account.

Are you using cookie-based authentication? If so, are you including a nonce in the request?

**Comment by jdolan** [comment]
Permissions issue was on my end. Thanks.

Feel free to close this issue out. I admit that it was more of a rant than a bug report.

**Comment by danielbachhuber** [comment]
> Permissions issue was on my end. Thanks.

Glad you got it sorted.

> Feel free to close this issue out. I admit that it was more of a rant than a bug report.

No worries — no offense taken. What you're frustrated about is 100% on our radar. I'm confident we'll come up with a solution we don't hate by the time this ends up in core.

**Comment by kosso** [comment]
+1 

Very eager to have a solution to this.

**Comment by alexciarlillo** [comment]
So currently the only way to accomplish this is by extending the API? Even for already existing terms?

**Comment by jdolan** [comment]
No, it's possible with the existing API (git), it's just not particular efficient. For existing terms, you can simply `POST` to `wp/v2/posts/{post_id}/terms/{tax_slug}/{term_id}` for each term. For new or unknown terms, you must first `POST` to `/wp/v2/terms/{tax_rest_base}`. Note that `tax_rest_base` is not necessarily the Taxonomy slug, which is a bug in my opinion. See #1381.
