### ISSUE TITLE
?_embed flag doesn't work on collections

### ISSUE THREAD

**Issue by Zelgod** [WP-API/WP-API#1384]
Hi,

I'm currently working from the php client side using v2 (previously using v1 but was lacking support for adding comments). I don't know if this has be already been suggested or addressed but when accessing a post endpoint it would be nice to be able to hydrate that post with common things like the featured image, author info etc (v1 does this). Is there a recommended way to achieve this or anything in the pipeline?

Thanks Matt.

**Comment by joehoyle** [comment]
@Zelgod you can pass `?_embed` to the URL and it will include all the related objects in the response.

**Comment by Zelgod** [comment]
Awesome. Ill try this monday when I'm back @work. Great job with the API by the way.

**Comment by Zelgod** [comment]
@joehoyle can you post an example url? I've tryed ``http://wordpress.app/wp-json/wp/v2/posts?_embed&orderby=date`` expecting the posts results to be hydrated but I get the feeling I'm doing this wrong.

**Comment by joehoyle** [comment]
@Zelgod ah so currently this is only supported on a single resource endpoint, for example http://demo.wp-api.org/wp-json/wp/v2/posts/111?_embed

**Comment by Zelgod** [comment]
@joehoyle Thanks for the heads up. Ill manually embed the collections for now (lots of requests, yuck) until we see embedded collections.

**Comment by joehoyle** [comment]
Reopening to try fix in the future.

**Comment by rachelbaker** [comment]
Issue already being tracked in #865 and #1196.  Closing this as a duplicate.
