### ISSUE TITLE
Question about authentication

### ISSUE THREAD

**Issue by theones** [WP-API/WP-API#1385]
Hi! I got one question about authentication.
I'm teaching programming now and i write small appliaciton in c# what connect with wordpress and get some information.
User need to login in appliaction and i got question about that..
We can do cookie login validator? If we login we can get cookies and headers with HttpWebRequest but how we can get right none id for request to api?

**Comment by rachelbaker** [comment]
@theones Thank you for using the plugin.  We have more information about how to use authentication with our plugin on our documentation site: http://wp-api.org/guides/authentication.html
