### ISSUE TITLE
wp api with oauth1

### ISSUE THREAD

**Issue by wesleyxiao** [WP-API/WP-API#1386]
can anyone tell me after i got the access_token from the wordpress.

what do i do next?

how do i use access_token?

i try $http({methoid: 'GET', headers: {'Authorization' : 'Token Kdsfauidf343daasdfasewr '}
})

but it return 403 Forbidden error

**Comment by romuloctba** [comment]
try as a header named x-access-token

**Comment by wesleyxiao** [comment]
$http.defaults.headers.common['Authorization'] = 'x-access-token Kyh3Z7nfdpbs2GW8BYfgKcOQ';
		$http({method:'GET',
			url: SITE_INFO.siteURL+'/users/'
		}).success(function(data){
			
		});
			
	    }).error(function(data, status) {
	        console.log(data);
	        console.log(status);
	    });

still show [{"code":"json_user_cannot_list","message":"Sorry, you are not allowed to list users."}]

**Comment by wesleyxiao** [comment]
console.log(data);
			$http.get(SITE_INFO.siteURL+'/users/', {
			    headers: {
			        'Authorization':
					
					'Oauth oauth_version = "1.0",' +
					'oauth_consumer_key = "TMP9ozBJUMwF",' +
					'oauth_token = "Kyh3Z7nfdpbs2GW8BYfgKcOQ",' +
					'oauth_timestamp = "1435984397",' +
					'oauth_nonce = "r6xLV1hSFP2",' +
					'oauth_signature_method = "HMAC-SHA1",' +
					'oauth_signature = "VU%2FUGz12lp%2BlkDNCDhzjFL2r6q0%3D"'

			    }
			}).success(function(data, status){
				console.log(data);
			}).error(function(data, status){
				
				console.log(data);
				console.log(status);
			})

this also show [{"code":"json_user_cannot_list","message":"Sorry, you are not allowed to list users."}]

**Comment by wesleyxiao** [comment]
@romuloctba  hi, romuloctba, do you know is access token never expire? or it will be expire ?

**Comment by romuloctba** [comment]
I'm not able to test right now, b ut I'd send x-access-token outside the
authorization headers, something like:

$http.defaults.headers.common['x-access-token']

2015-07-06 0:13 GMT-03:00 wesleyxiao <notifications@github.com>:

**Comment by wesleyxiao** [comment]
yes i also try
	url: SITE_INFO.siteURL+'/users/', headers: {
			        'X-Auth-Token': 'Kyh3Z7nfdpbs2GW8BYfgKcOQ'

			    }
console.log invalid token, is that mean my access token is expire?

**Comment by kosso** [comment]
I provided a PHP test in my fork of the OAuth plugin. https://github.com/kosso/OAuth1 which might help. (Though, some part might not work, since it was built pre-version 2 of the WP-API plugin)

**Comment by wesleyxiao** [comment]
@kosso          thanks kosso, can you please tell me, after i getting access token, in my clienside

i am using angularjs try to get user data

here is my code

$http.get('http://192.168.1.103/wordpress/wp-json/users/', {
        headers: {
            'Authorization':
                'OAuth oauth_consumer_key = "aHzRikUJcuLI", ' +
                'oauth_signature_method="HMAC-SHA1", ' +
                'oauth_timestamp="1436244848", ' +
                'oauth_nonce="hZHucbMqOgW", ' +
                'oauth_version="1.0", ' +
                'oauth_token="W2NILogo2yynwwlzTIlDAb1Q", ' +
                'oauth_signature="03yY8vZ7zM6kllGtiHAZn%2FjECD8%3D"'
        }
    }).then(function (data) {
        $scope.data = data.data;
        console.log(data);
    });






which i am seem inside your oauth1 plugin which show
public function parse_header( $header ) {
		if ( substr( $header, 0, 6 ) !== 'OAuth ' ) {
			return false;
		}
		// From OAuth PHP library, used under MIT license
		$params = array();
		if ( preg_match_all( '/(oauth_[a-z_-]*)=(:?"([^"]*)"|([^,]*))/', $header, $matches ) ) {
			foreach ($matches[1] as $i => $h) {
				$params[$h] = urldecode( empty($matches[3][$i]) ? $matches[4][$i] : $matches[3][$i] );
			}
			if (isset($params['realm'])) {
				unset($params['realm']);
			}
		}
		return $params;
	}


that's mean oauth is getting oauth access token from the header, that's mean i am doing right

is there something more that i missing?

**Comment by wesleyxiao** [comment]
ok problem solve, 

headers: {
'Authorization':
'OAuth oauth_consumer_key="aHzRikUJcuLI", ' +
'oauth_signature_method="HMAC-SHA1", ' +
'oauth_timestamp="1436244848", ' +
'oauth_nonce="hZHucbMqOgW", ' +
'oauth_version="1.0", ' +
'oauth_token="W2NILogo2yynwwlzTIlDAb1Q", ' +
'oauth_signature="03yY8vZ7zM6kllGtiHAZn%2FjECD8%3D"'
}

on header we send remember, don't put space between equal sign
 oauth_consumer_key="aHzRikUJcuLI"  this will be ok
oauth_consumer_key = "aHzRikUJcuLI" this will show error

**Comment by ahusj** [comment]
@wesleyxiao hi, how do you get the access_token? could you give me step by step to get it? thx
