### ISSUE TITLE
Showing Empty result & Error 

### ISSUE THREAD

**Issue by kdpuvvadi** [WP-API/WP-API#1387]
After installing i tried to goto /wp-jason on browser and showed empty page and tried in xcode not result at all and i tried to get the detailes of a page ID and it showed the error 

[{"code":"json_user_cannot_read","message":"Sorry, you cannot read this post."}]

Using Wordpress 4.2.2, running on ubuntu 14.04 on Azure with Apache2

**Comment by rachelbaker** [comment]
@kdpuvvadi Which version of the plugin are you using?

**Comment by kdpuvvadi** [comment]
1.2.2 from WordPress plugin directory

**Comment by rmccue** [comment]
Is the post published? Only publicly visible posts are visible with non-authenticated access.
