### ISSUE TITLE
how to disable some methods to make API working partially?

### ISSUE THREAD

**Issue by KagamiChan** [WP-API/WP-API#1388]
I want to provide a rest api of my wordpress but I don't think I need POST, DELETE or PUT methods according to my usage. Since I'm not very familiar with wordpress nor PHP, I'm also worry about brute force attacks via this API and decide to disable these methods.
So my questions are:
1. Is there an option to set or disable methods?
2. Does editing $method_map in class-wp-rest-server help?
3. Is this API strong enough against brute-force attacks after disabling there methods or I need to modify authentication part?

**Comment by jdolan** [comment]
The GET methods, for published content, do not require authentication. So if that's all you need, don't bother setting up a WP-API auth mechanism and you should be all set. Anyone who attempts an API request requiring authentication will be denied. If you _do_ need to access e.g. unpublished content via the API, then create a "read-only" user account, and use those credentials for your API authentication.

**Comment by KagamiChan** [comment]
@jdolan Thanks. So it should be sufficient to set up an auth mechanism that never works. I really like this idea. 
And do you have any suggestions on disabling some methods?

**Comment by jdolan** [comment]
By not explicitly setting one up, you should be okay. OAuth requires that you register a provider for your site / API instance. So .. don't do that, heh ;) Basic Auth requires installing a separate plugin, so again, don't do that. For cookie-based auth.. someone could gain access to the API methods that their legitimate WP account would allow them to invoke, but I'm not sure that's really a problem, either. Again, I think you're okay by simply taking no action.

**Comment by rachelbaker** [comment]
@KagamiChan Assuming you are using the `master` branch, you can unhook the registered routes like so:

```
function rb_unset_some_default_endpoints( $routes ) {
	$accepted_paths = array( '/', '/posts', '/media', '/media/(?P<id>\\d+)' );
	$new_routes = array();
	foreach ( $routes as $path => $endpoint ) {
		if ( in_array( $path, $accepted_paths ) ) {
			$new_routes[ $path ] = $endpoint;
		}
	}
	return $new_routes;
}
add_filter( 'json_endpoints', 'rb_unset_some_default_endpoints', 11 );
```

**Comment by rachelbaker** [comment]
Closing this issue for now.  Feel free to re-open if you are having an issue filtering out the endpoints.

**Comment by KagamiChan** [comment]
After some tests and reading codes and documents I realize that I've made a mistake. By default (not setting auth) there's no option for passing user account and password information, so there's no possibility for brute force attack through API. 
Thank you very much @jdolan @rachelbaker
