### ISSUE TITLE
404 when passing args to the API

### ISSUE THREAD

**Issue by webline** [WP-API/WP-API#1389]
Hi,

I defined a custom route with register_routes - works fine. Now I can access the REST API with:

mydomain.com/wphhv/test

The API returns JSON too. So far no problems.

But when I add a parameter to my URL - like:

mydomain.com/wphhv/test?val1=1234&val2=abcd

The API returns an 404 error all the time (checked with http://jsonformatter.curiousconcept.com - just entering the URL into a browser shows no error, but the correct data. When I access the API from an iOS client, I run into the 404 error too).

The wordpress permalink structure is set to "Post name".

Any idea what’s going wrong?

Best regards,

Detlef

P.S.: with
curl -I http://mydomain.com/wphhv/test?val1=1234&val2=abcd
I get
HTTP/1.1 404 Not Found

with
curl -I http://mydomain.com/wphhv/test

I get
HTTP/1.1 200 OK

P.P.S.: here is my htaccess setup:

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

P.P.S.: it is not the GET parameter syntax in general because mydomain.com/wp-json/posts?type[]=project works fine.

All facts:
- WordPress 4.2.2
- the PlugIn is up and running
- basic functions work
- custom routes work
- passing get parameters to a custom route return the HTTP status 404

(this is a re-post of a support forum entry at wordpress.org - don't know what's the better place)

**Comment by rachelbaker** [comment]
@webline which version of the plugin are you using?  Do the built-in routes work correctly?

**Comment by webline** [comment]
Version 1.2.2

As I wrote: "mydomain.com/wp-json/posts?type[]=project" works fine.

My custom route delivers the data, only the status header is wrong.

**Comment by webline** [comment]
Is the reason maybe a missing endpoint for the "?val1=xyz&val2=123" syntax?
This is my definition of a route and endpoint so far:

    public function register_routes( $routes ) {
        $routes['/wphhv/login'] = array(
            	array( array( $this, 'wphhv_check_login' ), WP_JSON_Server::READABLE ),
             );

        return $routes;
    }

As I wrote, this route returns the data, but the wrong HTTP status code when there are GET parameters in the URL.

**Comment by rachelbaker** [comment]
@webline Are you defining the parameters in the route method?

Example:

```
public function wphvv_check_login( $val1, $val2 ) {
    // route logic
}
```

**Comment by webline** [comment]
yes:
public function wphhv_check_login( $name = '', $kw = '' ) {

**Comment by webline** [comment]
this one works:
$routes['/wphhv/login/(?P<name>\w+)/(?P<kw>\w+)'] = array(

using mydomain.com/wphhv/login/1234/abcd instead of mydomain.com/wphhv/login?val1=1234&val2=abcd
