### ISSUE TITLE
Docs for using the included JS client?

### ISSUE THREAD

**Issue by alexciarlillo** [WP-API/WP-API#1392]
I cannot find documentation on using the included JS (backbone) client. In the client repo it says it is included with the plugin by default. I found an issue response somewhere saying I need to use wp_enqueue_script to load it, with underscore and backbone listed as dependencies. Do I need to register underscore and backbone myself? Am I just missing the docs on this? Also looking for how to localize WP_API_Settings. I know this info must be out there but it does not seem to be in an obvious place.

**Comment by WraithKenny** [comment]
I couldn't find any docs on this either, but to answer some of your questions:
https://github.com/WP-API/WP-API/blob/develop/extras.php#L31

This means that the script is already registered, and the backbone and underscore libs are marked as dependancies, and data localized, so all you'd do is enqueue the script with the handle ''wp-api''

**Comment by alexciarlillo** [comment]
Thanks. I guess its straightforward enough to not need much documentation.
