### ISSUE TITLE
Is somehow custom data possible?

### ISSUE THREAD

**Issue by Arth95** [WP-API/WP-API#1396]
Hi!
Is it possible to make some custom fields for custom pages? For example, about_me_description etc.
I found there is plugin called advanced custom fields, but I don't know how it gonna work with WP-API.

**Comment by colinhowells** [comment]
Simplest option: https://wordpress.org/plugins/acf-to-wp-api/

Further reading: http://support.advancedcustomfields.com/forums/topic/json-rest-api-and-acf/
