### ISSUE TITLE
Confused. Post tags and categories. 

### ISSUE THREAD

**Issue by kosso** [WP-API/WP-API#1403]
I'm a bit confused why the JSON data of posts at `/wp-json/wp/v2/posts` and also the data of an individual post `/wp-json/wp/v2/posts/[post_id]` doesn't also show the tags or categories associated with a post. 

Am I missing something? Or is this information something still being worked on?

**Comment by CodeBrauer** [comment]
I don't what version you're using but I can see all that information in the last stable release
http://mllnm.de/wp-api/wp-json/posts/
http://mllnm.de/wp-api/wp-json/posts/125

**Comment by kosso** [comment]
Hmm.. odd. 

I'm running Version 2.0 Beta 3: "Disco Stu Doesn't Advertise" on Wordpress 4.2.2 

How about you?

**Comment by jdolan** [comment]
@kosso You can get the terms associated to a post at `/wp/v2/posts/{post_id}/terms/{tax_slug}`. When in doubt, just open up the endpoints.php file you're interested in.

**Comment by kosso** [comment]
@jdolan Thanks. But that's still not very useful. 

When I get /wp-json/wp/v2/posts  I expect to get a list of the latest posts with any associated tags and categories available in each post object.  I don't have expect to have to call various other endpoints to get them. 

I am now running WP-API version 2.0 Beta 3 on  Wordpress 4.3-beta3-33321  - I see no meta or terms property in each post. I do see the `_links` to be able to go and get them though. But this is totally unusable when building a simple list of posts where most clients/app will want to show this info up front. 

This surely must be something coming (back) to the WP-API - held up by something else perhaps? 
@danielbachhuber @rachelbaker ?

**Comment by joehoyle** [comment]
@kokarn the reason is that the terms / meta etc are different objects, and in typical REST design going a GET on a single resource, will give you that resource, not that resource and a bunch of other ones too. However, you can pass `_embed` to the request which will include the linked resources in the response, for example see http://demo.wp-api.org/wp-json/wp/v2/posts/111?_embed

**Comment by kokarn** [comment]
Shouldn't that be @kosso ? Or am i totally missing something? :D

**Comment by kosso** [comment]
Ahah! Adding ?_embed was what I needed. Thanks @joehoyle 

@kokarn autocomplete fail ;) 

thx.

**Comment by beatelite** [comment]
This should be included in the documentation. I spent hours trying to roll my own solution only to discover this when searching for something else. 

I'd update a wiki for everyone but it's not editable. ;)
