### ISSUE TITLE
double-escaped content

### ISSUE THREAD

**Issue by mbakaitis** [WP-API/WP-API#1406]
On a test server running Wordpress 4.2.2, Twenty-Fifteen version 1.2, and version WP-API 1.2.2 with nothing else (no other plugins), we getting JSON responses with double-escaped content.  

In the example from the docs, I believe the JSON response should look like this:

```javascript
"meta":{
            "links":{
                "self":"http:\/\/localhost\/wptrunk\/wp-json\/users\/1",
                "archives":"http:\/\/localhost\/wptrunk\/wp-json\/users\/1\/posts"
            }
        }
```

...however, in the response body, I'm getting this...

```javascript
"meta": {
        "links": {
          "self": "http:\\/\\/mydomain.example.com\\/wp-json\\/users\\/5",
          "archives": "http:\\/\\/mydomain.example.com\\/wp-json\\/users\\/5\\/posts"
        }
      }
```

I've seen this before when accidentally double-escaping, but by going back to the default theme and having no other plugins running...I'm not sure what could be causing this that I control.  

Searches here and via search engine are also stumped.  The content in the database looks correct, we don't have magic quotes enabled, and to my knowledge we aren't doing anything else.

Any suggestions on what I can do to fix this issue so we only get single-escaped content?

One note -- in the `content` field in the JSON, even the markup that WordPress injects is also double escaped.  An example:

```javascript
"content": "<p>Here is some content that we are getting from wordpress.<\\/p>"
```

Note the forward slash in the closing tag is also double-escaped.

**Comment by mbakaitis** [comment]
Sorry for the clutter...user error.  :(

**Comment by danwatt** [comment]
@mbakaitis - Im encountering the same issue from a Java client. I've event looked at the raw bytes that are flowing to Wordpress, and they look fine. However, GET requests, as well as looking a a Post in the Wordpress Admin show double backslashes. What was the problem?

**Comment by mbakaitis** [comment]
Sorry for the delayed request...you've probably already fixed this but...

My problem was the tool I was using to look at the incoming results was escaping slashes as it handled the data stream from WP-API.  When I switched to a quick-written script that didn't do anything but throw the data to a console, the slashes were gone.  This was totally a problem of me not realizing the testing tool we were using was not presenting the exact data it received.  :(
