### ISSUE TITLE
Which Wordpress version for 2.0 Beta 3?

### ISSUE THREAD

**Issue by kosso** [WP-API/WP-API#1407]
The 2.0 docs page says "4.3+" http://v2.wp-api.org/

Where do I get this?  

Thx.

**Comment by Shelob9** [comment]
The current development version of WordPress is 4.3-beta3. You can get the latest version using the beta tester plugin -- https://wordpress.org/plugins/wordpress-beta-tester/ or by checking out WordPress via Git (https://make.wordpress.org/core/2014/01/15/git-mirrors-for-wordpress/ or github.com/wordpress/wordpress) or from the official SVN.

**Comment by kosso** [comment]
Perfect. Thank you.
