### ISSUE TITLE
Sending Nonce over cURL Fails

### ISSUE THREAD

**Issue by kenanfallon** [WP-API/WP-API#1408]
I am building a PHP application and trying to set the `X-WP-Nonce` header and sending it over cURL to an endpoint, however it is failing.

I am using the native Wordpress 'edit_post' function to obtain the post content and send it to the API endpoint which in turn sends the data to another API. When I use [php-curl-class](https://github.com/php-curl-class/php-curl-class)'s `->setHeader` call as such:

    $nonce = wp_create_nonce( 'wp_json' );
    $curl->setHeader('X-WP-Nonce', $nonce );

and then `wp_die` the API's response, I get the error

    json_cookie_invalid_nonce

I am trying to lockdown the API so only requests from the 'edit_post' function inside WP-Admin (with the Nonce) attached are allowed to perform the API request.

**Comment by kosso** [comment]
What happens if you try `$curl->setHeader('WP-Nonce', $nonce );` 

I have a feeling that you use the `X-` part when getting a custom header, not when setting it.

**Comment by kenanfallon** [comment]
I tried setting the header as:

    $nonce = wp_create_nonce( 'wp_json' );
    $curl->setHeader('WP-Nonce', $nonce );

and verifying on the endpoint as:

    $nonce = $_headers['WP_NONCE'];
        if ( ! wp_verify_nonce( $nonce, 'wp_json' ) ) {
            return array( 
                "nonce-status" => "Not verified",
                "nonce" => $nonce,
                );
        } else { 
            return array (
                "nonce-status" => "Verified",
                "nonce" => $nonce,
                );
        }

Which failed. When I return the `$_headers` on the endpoint, I can see the nonce in the headers, and it matches the one being returned in the array.

I reread the authentication docs and it also says 
> These can then be passed to the API via the _wp_json_nonce data parameter

 So I tried sending the nonce in $data to the endpoint and it still fails.

**Comment by rmccue** [comment]
This isn't how the nonce works. :)

Essentially, the authentication you're trying to use is regular username and password authentication, which needs the user's cookies. When you send this request, you're presumably not sending the cookies as well, so there's no authentication to check.

When you are sending the cookies, you need to *also* send the nonce as a cross-site request forgery token. This stops the cookies from being used by other sites to falsely authenticate as you.

If you're doing server-to-server communication as you are here, you need to use a different authentication system. OAuth is the recommended way to do that, but there are alternatives. :)
