### ISSUE TITLE
Accessing WP_JSON from backend

### ISSUE THREAD

**Issue by nharlow89** [WP-API/WP-API#1409]
Is it possible to access the wp-api from the backend? I would like to do something similar to `WP_JSON_Posts::get_posts()` so that I can get data in the same exact format ( pre-populating a web app that uses wp-api on the front-end). 

Should also note that I am using v1.2.2

**Comment by Shelob9** [comment]
@nharlow89 I don't see a great way to do this in v1, but that doesn't mean there isn't, besides just making an HTTP request, and then outputting the results.

If you look in the test for v2 -- and I suspect you'll find the same thing in the V1 tests, you can see how to inject a request into the post response controller. For example, you could something like this, which is cobbled together from the post controller tests.

```
<?php
$server = new WP_REST_Server;
$request = new WP_REST_Request( 'GET', '/wp/v2/posts' );
$response = $server->dispatch( $request );
$response = rest_ensure_response( $response );
return $response;
```



I bet if you were slick, you coul

**Comment by nharlow89** [comment]
Yeah I am currently using the method you just mentioned (simply making the request server side) but was hoping there was a more efficient method =(

Thanks for your response though.

**Comment by rmccue** [comment]
Note that the code is running the request internally, not sending a loopback HTTP request or anything to do that :)

If you just want to format post data, without all the rest, you can do...
```php
function get_post_data( $posts = null ) {
	// Default to current query
	if ( $posts === null ) {
		$posts = $GLOBALS['wp_query']->posts;
	}

	$data = array();

	$request = new WP_REST_Request();
	$request['context'] = 'view';
	foreach ( $posts as $post ) {
		$controller = new WP_REST_Posts_Controller( $post->post_type );
		$data[] = convert_data( $controller->prepare_item_for_response( $post, $request ) );
	}

	return $data;
}

function convert_data( $data ) {
	$server = get_server();
	$data = $server->response_to_data( $data, true );

	// Hackity hack hack: Ensures we're only dealing with arrays
	$data = json_decode( json_encode( $data ), true );

	return $data;
}
```

Working on making this easier in the future. :)

**Comment by nharlow89** [comment]
Great! This is what I was looking for to avoid the http request. Would be nice to expose a backend API at some point!

**Comment by Koosmann** [comment]
This would definitely be a great feature!  I've almost got this working in v1, but fields like author, featured_image, and terms are either int ids or left out entirely.

Here is my current implementation for fetching posts:
```php
$server = new WP_JSON_Server;
$posts = new WP_JSON_Posts( $server );
$response = $posts->get_posts();
$response = json_ensure_response( $response );
echo json_encode($response->data); 
```

Is it possible in v1 to get the content with those fields populated (similar to when fetched through an http call)?

**Comment by rmccue** [comment]
@Koosmann It's not possible to get those in v1, and we recommend you use v2 instead :)
