### ISSUE TITLE
/media endpoint not returning alt, caption, description

### ISSUE THREAD

**Issue by jasonbahl** [WP-API/WP-API#1416]
When retrieving media items, there's no alt, caption or description returned for the items. 

It shows up in the "content" but that's not ideal as they should be their own pieces of data that can be used without having to parse the content.

**Comment by jasonbahl** [comment]
I should clarify, this is for version 1.2.2. It looks like (in the documentation) that this might be getting addressed in 2.0, but I can't use 2.0 for media because 2.0 doesn't support posts_per_page for /media. . .

**Comment by danielbachhuber** [comment]
> I should clarify, this is for version 1.2.2

We aren't adding any enhancements to `v1.x.x` at this time.

> but I can't use 2.0 for media because 2.0 doesn't support posts_per_page for /media. . .

The argument is actually `per_page`

**Comment by jasonbahl** [comment]
Sweet! did I miss this in the documentation somewhere? I was beating my head for an hour trying to get things to work with media and the rest-api.

**Comment by danielbachhuber** [comment]
> did I miss this in the documentation somewhere?

It hasn't made it to the documentation yet :( We're working on exposing it so we can automatically pull it in to v2.wp-api.org: #1415

**Comment by jasonbahl** [comment]
Sweet! Great work on things. Loving the api and can't wait to see where it goes from here.
