### ISSUE TITLE
Unable to use $_REQUEST['_wp_rest_nonce'] with DELETE method

### ISSUE THREAD

**Issue by petenelson** [WP-API/WP-API#1428]
Because PHP does not populate the $_REQUEST superglobal with DELETE methods, validating the nonce this way will not work. Not necessarily broken, but probably something we should note to the documentation (which I've been meaning to contribute to).

May bring up a bigger issue though (not related to nonces) if someone is trying to send multiple parameters via a DELETE method and using a custom endpoint outside of the typical /object/id endpoints for the native WordPress objects.

**Comment by rmccue** [comment]
Hmm, what's your server setup here? I'm seeing PHP populate `$_REQUEST` with the query variables (`$_GET`) for a DELETE.

**Comment by petenelson** [comment]
I was trying to pass _wp_rest_nonce in the data field of a jQuery.ajax call (https://github.com/petenelson/extending-wp-rest-api/blob/master/admin/admin-hello-world.js#L51).  

Example:
```
$.ajax( {
	url: WP_API_Settings.root + '/api-extend/v1/hello-world',
	data: { _wp_rest_nonce:WP_API_Settings.nonce },
	type: 'DELETE',
	success: function() {
	}
} ).always( function ( response ) {
	$.extend_rest_api.display_response( response );
});
```

Since jQuery passes the data fields for a DELETE method as form fields, it wasn't showing up on the server.  Building the URL with the nonce in the query string would probably still work.  Ex:  '/api-extend/v1/hello-world?_wp_rest_nonce=abcd1234'.  

Not an issue with the API, but it's likely something we'll need to make note of in the documentation.

**Comment by rmccue** [comment]
Aha, yeah, up until recently most things didn't support data for DELETE (in fact, it wasn't really allowed), so PHP doesn't pull out the request body into data.

Definitely something we should document. Sending in the headers always works, and is less likely to break things.

**Comment by danielbachhuber** [comment]
Capturing these details here https://github.com/WP-API/docs-v2/pull/75
