### ISSUE TITLE
On Version 1.2.2 setting timezone to UTC-0:30 causes fatals

### ISSUE THREAD

**Issue by jeichorn** [WP-API/WP-API#1438]
[27-Jul-2015 19:52:39 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone (Etc/GMT-0.5)' in /dom7859/wp-content/plugins/json-rest-api/plugin.php:672

It looks like this is caused by the timezone list in wordpress not matching what is actually supported in php.
http://php.net/manual/en/timezones.others.php

**Comment by danielbachhuber** [comment]
This is still a problem in v2.x:

```
salty-wordpress ➜  wp-api  wp eval 'echo rest_get_timezone();'
PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone (Etc/GMT-0.5)' in /srv/www/wordpress-develop.dev/src/wp-content/plugins/wp-api/extras.php:98
```

However, `rest_get_timezone()` isn't used anywhere in the v2.x codebase. We _only_ used it in v1.x to include the timezone when preparing a comment date. https://github.com/WP-API/WP-API/blob/master/lib/class-wp-json-comments.php#L190-L191

At this point, I think we should trigger `_doing_it_wrong()` if someone calls `rest_get_timezone()`.
