### ISSUE TITLE
Current User data WP API V2

### ISSUE THREAD

**Issue by Lawless55** [WP-API/WP-API#1439]
For a logged in subscriber I am unable to retrieve any user data. 

The end point, i.e. wp-json/wp/v2/users/2, always returns a 403 with status "rest_user_cannot_view", is this correct? Signed in Admins appears to work perfectly. Is it not possible for that user (Subscriber without published posts and list_user capability) to retrieve their own data? or must this be handled by Wordpress? Using wp-json/wp/v2/users/me returns a 401 with status "rest_not_logged_in" - this is apparent for all roles including Admins.

I'm a little confused on how to retrieve a current users data using the API, some direction would be awesome :)

**Comment by rmccue** [comment]
Are you sending the nonce correctly? Check the [authentication documentation](http://v2.wp-api.org/guide/authentication/).

**Comment by Lawless55** [comment]
Hi @rmccue, Thanks for getting back to me. 

I am using cookie authentication via _wp_json_nonce param and everything else seems to work - Getting; posts, pages, comments and creating comments via the API but only as an Admin. I did try using the X-WP-Nonce, but kept on getting a "rest_cookie_invalid_nonce" when requesting a user even though the request header was being sent:

GET /mydomain.com/wp-json/wp/v2/users/2 HTTP/1.1
Host: localhost
Connection: keep-alive
Cache-Control: max-age=0
X-WP-Nonce: 8ec80811d5
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36
Accept: */*
Referer: http://localhost/mydomain.com/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,fr;q=0.6
Cookie: wp-settings-1=hidetb%3D1; wp-settings-time-1=1436949655; wp-settings-time-3=1437225425; comment_author_490c36b75ee40d61d9ba640260309907=Lawless; comment_author_email_490c36b75ee40d61d9ba640260309907=git%40trm.com; wordpress_test_cookie=WP+Cookie+check; wp-settings-time-2=1438072726; wordpress_logged_in_490c36b75ee40d61d9ba640260309907=lawless%7C1439288787%7CMYI9Ebb5IjMHgWgOmXZd2wSHbKDiNh4NV2ObaW4wm0L%7C52e8a1b49b2a370f0652a12b0ff2c05c7366d6d88bb6380329c4790f024f1dcb; _ga=GA1.1.852923100.1435820745; PHPSESSID=0unalog0o21l245uicqo4b4ao7; bp-activity-oldestpage=1

Using this method broke all other end points for me, so I decided to stick with using _wp_json_nonce  param.

**Comment by raphaelnikson** [comment]
This happens because of the check that happens in the get_item_permissions_check function of class class-wp-rest-users-controller.php

There is the user’s post count. If it does not create any post it is not possible to see user details by api ..
