### ISSUE TITLE
Cannot modify additional registered fields when updating an Attachment

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#1440]
In the `create_item()` method we call `$this->update_additional_fields_for_object( $attachment, $request );` but it is missing from the `update_item()` method.

**Comment by rmccue** [comment]
Are you sure we need this? We call `parent::update_item`, which internally calls `$this->update_additional_fields_for_object( get_post( $post_id ), $request );`

**Comment by rachelbaker** [comment]
I don't remember exactly what I was thinking here.  Closing this issue, and will re-open if my memory returns.
