### ISSUE TITLE
Getting Featured Image

### ISSUE THREAD

**Issue by dhrod5** [WP-API/WP-API#1450]
I've combed through the documentation and I can't quite figure out how to get the featured image url. 

I can get the post, and on there there is a field called "featured_image".  However, that field is an integer.  I tried looking at the attachments, but they don't have the featured image in them.  How would I get info for an image_id and then render the image?

**Comment by dhrod5** [comment]
I figured it out, sorry.  I'm still learning how WP stores it's data.  For those wondering, you can use the featured_image id on the /wp-json/wp/v2/media/<featured_image_Id> endpoint to get the information about the featured_image.  It's not part of the attachments

**Comment by acorncom** [comment]
You can also use `_embed` per #1779
