### ISSUE TITLE
<p> elements printing with JSON feeds

### ISSUE THREAD

**Issue by dosstx** [WP-API/WP-API#1452]
When I consume the JSON feed, the HTML < p > element is posted along with the string value from the "content" key: e.g.: "< p >Some text here < /p >".

is there a reason for this? how do I disable?

**Comment by bigandy** [comment]
You can turn it off with a filter. (I am using v2 of the plugin, so I have not tested it with v1). 
```
function ah_use_raw_post_content( $data, $post, $request ) {
    $data->data['content']['plaintext'] = $post->post_content;
    return $data;
}
add_filter( 'rest_prepare_post', 'ah_use_raw_post_content', 10, 3 );
```
Source: [this tutorial](https://deliciousbrains.com/creating-mobile-app-wp-api-react-native/).

**Comment by rmccue** [comment]
This is intentional, the content inside the `content` value _is_ HTML.
