### ISSUE TITLE
Retrieve related posts

### ISSUE THREAD

**Issue by nonla** [WP-API/WP-API#1456]
Hello, 

Looking at the guide (http://wp-api.org/) I don't see any document for retrieving the related posts list. Is this API supported retrieve the related post?. 
The wordpress API support this (/sites/$site/posts/$post/related). How can I achieve the same using this WP-API.
Thanks

**Comment by rmccue** [comment]
WordPress has nothing built in to get related posts, so we don't expose this over the API. This is up to plugins to provide, and hook into the API. :)

**Comment by nonla** [comment]
So there is no easy way to get the related post?

**Comment by rmccue** [comment]
The functionality doesn't exist in WordPress, so you'll need a plugin. I'm not aware of any that work with the API, but there may be one out there.

**Comment by nonla** [comment]
ah, I got it, thanks for your support. :)

**Comment by djahmednawaz** [comment]
Hi, How did you get related posts? can you share the method or plugin?

**Comment by nonla** [comment]
Hi djah, currently, I have not implemented the related posts using API because It does not support. :3
