### ISSUE TITLE
Is there a way to get all users from the database?

### ISSUE THREAD

**Issue by kaveiros** [WP-API/WP-API#1458]
I am trying to get all users from the wp database through the rest api in order to insert them in another database on a web app that I have created. The idea is, that they first register to wordpress, their information is migrated automatically to the web app database and then they can login with the credentials they have entered during wordpress registration. I am using wz tools client to test the api , but  when I try to get all users, I get a 403 forbidden status code. What I am missing? Basic auth plugin is installed . Here is a picture

![screen shot 2015-08-05 at 11 29 52](https://cloud.githubusercontent.com/assets/6780064/9081483/53a17e1e-3b65-11e5-8e24-1b69b84c9a92.png)

Help please

**Comment by studioraygun** [comment]
You'll need the basic auth plugin: https://github.com/WP-API/Basic-Auth

(Download and extract into plugins folder as you would from the WP site)

**Comment by kaveiros** [comment]
No It doesn't in my case.... :-(

**Comment by danielbachhuber** [comment]
Getting a list of users who haven't published posts requires the `list_users` capability for the authenticated user: https://github.com/WP-API/WP-API/blob/8017f609c3237c3154b41150e398370bf75096b7/lib/endpoints/class-wp-rest-users-controller.php#L94
