### ISSUE TITLE
How to correctly use 'date_query' with v2 API

### ISSUE THREAD

**Issue by jacktech24** [WP-API/WP-API#1461]
Hi I am unable to get to work 'date_query' argument with v2 /posts api, what is to correct way to get it working? (I need to filter posts that are modified after specific date)

**Comment by enejb** [comment]
It looks like date_query is currently not supported. 
Here is some documentation on how to use what filters are supported
https://github.com/WP-API/WP-API/blob/develop/docs/routes/routes.md

**Comment by danielbachhuber** [comment]
`date_query` isn't yet supported. You can track progress with #924

**Comment by fschroiff** [comment]
@enejb I got `date_query` to work with this code in functions.php

``` php
function my_rest_query_vars( $valid_vars ) {
    $valid_vars = array_merge( $valid_vars, array( 'date_query' ) );
    return $valid_vars;
}
add_filter( 'rest_query_vars', 'my_rest_query_vars' );
```

Read about it here: https://github.com/WP-API/WP-API/issues/389#issuecomment-149210813

**Comment by arikogan** [comment]
Hi guys,
I've run into this myself and found it a little bit cumbersome to add that piece of code to the functions.php of my theme. Also, if the theme changes or gets upgraded, you can loose the functionality. This is why I wrote a very small plugin that does this for you. Simply install the plugin and start using date_query filtering. Any feedback and suggestion will be highly appreciated.

[https://wordpress.org/plugins/date-query-enabler/](https://wordpress.org/plugins/date-query-enabler/)

**Comment by arikogan** [comment]
Hi guys,
I've run into this myself and found it a little bit cumbersome to add that piece of code to the functions.php of my theme. Also, if the theme changes or gets upgraded, you can loose the functionality. This is why I wrote a very small plugin that does this for you. Simply install the plugin and start using date_query filtering. Any feedback and suggestion will be highly appreciated.

[https://wordpress.org/plugins/date-query-enabler/](https://wordpress.org/plugins/date-query-enabler/)

**Comment by natyca** [comment]
Hi @arikogan, will this make it able to combine before & after filters? I can't seem to get it to work.

**Comment by arikogan** [comment]
@natyca, you need to install and enable the plugin and then you should be able to hit the API with requests like the below,

```
/wp-json/wp/v2/posts?filter[date_query][after]=2016-02-26T00:00:00&filter[date_query][before]=2016-02-28T12:34:56
```

**Comment by natyca** [comment]
@arikogan thats exactly what im doing and it gets worse when i add more filters. oh well, something else must be happening. thanks!

**Comment by 8ctopotamus** [comment]
The Date Query Enabler plugin does not seem to work anymore.

**Comment by kadamwhite** [comment]
@8ctopotamus please open an issue with that plugin's maintainer
