### ISSUE TITLE
V1.2.2 : How to filter tag with post-type ?

### ISSUE THREAD

**Issue by l2aelba** [WP-API/WP-API#1463]
Example , I have **2 pages** with same **tag** but different **post-type** like..

----

- Title : "Page One"
- Post-type : "Yellow"
- Tag : "Hello"

----

- Title : "Page Two"
- Post-type : "Green"
- Tag : "Hello"

----

I want to get result just **Page Two**

By : `/wp-json/posts?type=green&filter[tag]=hello`

Why this get resuit both **Page One** and **Page Two**

Im missing something ?

**Comment by danielbachhuber** [comment]
v1.x is no longer supported, aside from emergency fixes.
