### ISSUE TITLE
String could not be parsed as XML

### ISSUE THREAD

**Issue by KLVTZ** [WP-API/WP-API#1468]
> Tested: v1 && v2

Problem
-----------
If we make a request to the endpoint `/wp-json/posts` we receive the following before actual JSON:
```
Caught exception: String could not be parsed as XML
Caught exception: String could not be parsed as XML
[{"ID":83,"title":"What If? &#8211; ... (etc)
```

Cause
---------
This is due to how editors handle media items within links, for example, to replicate the following look, with two images without spaces between:
![screen shot 2015-08-09 at 10 35 08 am](https://cloud.githubusercontent.com/assets/3615935/9156064/56e82184-3e82-11e5-8899-db4204a01b35.png)

One would generate the following layout:
![screen shot 2015-08-09 at 10 37 06 am](https://cloud.githubusercontent.com/assets/3615935/9156071/9ec3422c-3e82-11e5-92f5-5ca230e2f444.png)
```
<a href="http://offgrid1.wpengine.com/wp-content/uploads/2015/07/Blackhawk-Ultralight-Side-Zip-Boot-01.jpg"><img class="aligncenter size-medium wp-image-81" src="http://offgrid1.wpengine.com/wp-content/uploads/2015/07/Blackhawk-Ultralight-Side-Zip-Boot-01-300x200.jpg" alt="Blackhawk-Ultralight-Side-Zip-Boot-01" width="300" height="200" /></a><a href="http://offgrid1.wpengine.com/wp-content/uploads/2015/07/Blackhawk-Ultralight-Side-Zip-Boot-02.jpg"><img class="aligncenter size-medium wp-image-82" src="http://offgrid1.wpengine.com/wp-content/uploads/2015/07/Blackhawk-Ultralight-Side-Zip-Boot-02-300x200.jpg" alt="Blackhawk-Ultralight-Side-Zip-Boot-02" width="300" height="200" /></a>
```

Fix
----
The initial fix is to modify the above markup so that it is not interpreted as XML. This can be done by removing the self-closing tag from the `img` tag. Just like example 2 from Mozilla:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Example_2.3A_Image_link

If we wanted to maintain the self-closing tag, essentially ignoring it's output, we could:

```
define('WP_DEBUG_DISPLAY', false);
```

This of course ignores the issue.

Question
------------
Whose responsibility is this to resolve. In other words, should we simply ask the editor to remove any image inserts with self-closing tags? Or is this an issue with how this plugin interprets post and their inserted media item? Lastly, is this Wordpress Core issue in how they use self-closing image tags? 

I'm unsure as to the best way to resolve this properly while digesting the API. Any feedback is appreciated!

**Comment by rmccue** [comment]
Hmm, I'm not sure where the original error is from here. What's causing this exception when you're trying to parse as XML?

**Comment by KLVTZ** [comment]
@rmccue from what I see, I am only making a request via postman to `/wp-json/posts`. Whatever is sent back int the body of the text is there. Do you believe something else is causing this exception? I'll look more into this.

**Comment by KLVTZ** [comment]
Disabled all plugins but this one and still seeing the exception. I'll have to do some digging into what is causing this. Would we assume that this error is being caught from the plugin?

**Comment by rmccue** [comment]
As far as I know, there's nothing in either WordPress core or the API that could be causing that error, nor that would catch it and display that text. If not a plugin, it could be something in your theme.
