### ISSUE TITLE
Is there a way to search custom field information (meta data)?

### ISSUE THREAD

**Issue by siasjustin** [WP-API/WP-API#1474]
Hi. I love this plugin! However, I recently became aware that the search functionality is only searching the content/excerpts and ignoring all meta data. If I get /wp-json/posts?filter[s]=example - it works fine as long as the term "example" is in the content of the post. However, if I have a custom field that is part of that post containing the term "example" it does not show up in that response.

So, I am wondering if anyone knows how I can make sure the meta data for each post is part of that search. If this is not possible, is it possible to search all meta data in the site to see if it shows up, and at that point I could at least gain access to this information and figure out how to display the post with relevant post_id after running a meta search? That seems like overkill but it is vital that I am able to access this information. Thanks for any pointers that help me figure this out.

**Comment by rmccue** [comment]
The search functionality we expose here is the regular WP search functionality; as far as I know, there's no way to change what that searches, alas.

Your best bet is to write your own search query and expose it as a custom filter variable.
