### ISSUE TITLE
rest_api_init not firing

### ISSUE THREAD

**Issue by dubunin** [WP-API/WP-API#1475]
Using the latest build I'm not seeing the rest_api_init action being fired. Looks like this code in the plugin.php is always empty and returns, never allowing the rest_api_init action to be fired:

	if ( empty( $GLOBALS['wp']->query_vars['rest_route'] ) ) {
		return;
	}

**Comment by joehoyle** [comment]
@dubunin are you visiting `/wp-json/`? If so, do you have pretty permalinks turned on?

**Comment by dubunin** [comment]
Ughh. That was it. Thanks!
