### ISSUE TITLE
Collection filter by name broken

### ISSUE THREAD

**Issue by mattheu** [WP-API/WP-API#1477]
I updated WP-API to the latest revision and doing something like this: 

`wp/v2/posts?name=test` no longer works, it just returns the full collection the same as `wp/v2/posts`

It worked fine before. Looks like the bug was introduced here: 11487fecf9703160a076644050e012810dd0dc10

**Comment by joehoyle** [comment]
@mattheu since #1420 all WP_Query params have to be in the `filter` array, e.g. 

http://demo.wp-api.org/wp-json/wp/v2/posts/?filter[name]=sint-aperiam-autem-molestiae-debitis
