### ISSUE TITLE
serialize php response can't be easily parsed (unserialize need it before response)

### ISSUE THREAD

**Issue by mkiisoft** [WP-API/WP-API#1478]
EDIT: I'm using some theme that serialize data and I get serialize php responses. Something like this:

"map": [ "a:3:{s:7:\"address\";s:0:\"\";s:3:\"lat\";s:11:\"-39.5642XXX\";s:3:\"lng\";s:19:\"-51.4915600XXX\";}" ]

How can I "unserialize" before the print response??? There is any way? Or I have to change the theme code to achieve that? It should be getting something like this: 

"map": {
"address": "some adress here",
"lat": "-39.5642XXX",
"lng": "-51.4915600XXX"
}

Any help???? Please!!! Thanks in advance! PS: BTW I'm using v1 1.2.3

**Comment by rmccue** [comment]
I'm not sure what's adding the `map` parameter, but you need to handle unserialising there. (Nowhere in the core REST API will return serialised strings.)
