### ISSUE TITLE
No users are allowed to add Posts

### ISSUE THREAD

**Issue by james-molloy-vgh** [WP-API/WP-API#1479]
I'm having the same issue with both v1 and v2 (beta) of WP-API, my users are allowed to post. Calling *wp-json/wp/v2/posts* just returns the following:
```
    "code": "rest_forbidden",
    "message": "You don't have permission to do this.",
    "data": {
      "status": 403
    }
```
Despite the fact that the user in question is an admin. I get similar results with things like trying to view users, etc.

The same issue happens with either Postman or with my application, both are authenticating via Basic Auth (and I'm not logged in to the Dashboard in the same browser so it's not the cookie issue).

*Edit:*
I tried creating a custom role that explicitly has the publish_posts and edit_posts permissions and am still getting the issue.

**Comment by joehoyle** [comment]
@james-molloy-vgh can you confirm you are auth'ed by visiting `/wp/v2/users/me`

**Comment by james-molloy-vgh** [comment]
@joehoyle aha, it's telling me I'm not logged in even though I have *Authorization: Basic* ***base64encode(username . ':' . password)*** in my header. Any advice?

**Comment by joehoyle** [comment]
@james-molloy-vgh are you using the basic auth plugin?

**Comment by james-molloy-vgh** [comment]
@joehoyle Yep, [this one](https://github.com/WP-API/Basic-Auth).

**Comment by james-molloy-vgh** [comment]
@joehoyle after some digging I found that basic auth wasn't working because my *htaccess* file was being ignored. If you're using a bitnami-based WordPress instance you need to change *conf/htaccess.conf* instead.

In the `USE_PHP_FPM` definition adding `RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]` fixed the issue.

**Comment by joehoyle** [comment]
Good stuff!

**Comment by oldcwj** [comment]
cool!
