### ISSUE TITLE
How to register a custom field for the list of categories

### ISSUE THREAD

**Issue by abhishek1234321** [WP-API/WP-API#1481]
I tried to register a custom field by name `custom_meta` using the below code

	register_api_field( 'terms', 'custom_fields', array(
		'get_callback' => array(
			$this,
			'ui_add_extra_data_to_response'
		) ,
		'update_callback' => null,
		'schema' => null,
	) );

Is this the right way of doing it?

I want the custom field to appear in this route `/terms/category`

I tried figuring out by passing `terms/category` and `terms` in the register_api_field but couldn't get it to work.

I am on WordPress 4.3-RC2-33619 and using 2.0 beta 3 version of the plugin.

Any help is appreciated.

Thanks

**Comment by joseaplwork** [comment]
@abhishek1234321 
Hi man,
I was working on this to, and finally i found the correct way to register.
You have to register in singular like 'term' instead of 'terms'

register_api_field( 'term',
    'custom_fields', array(
    'get_callback' => array(
        $this,
        'ui_add_extra_data_to_response'
    ) ,
    'update_callback' => null,
    'schema' => null,
) );
