### ISSUE TITLE
stripping short codes not working

### ISSUE THREAD

**Issue by storynory** [WP-API/WP-API#1484]
I am trying to strip the shortcodes from json posts:

    add_filter( 'json_prepare_post', 'strip_json_shortcodes', 10, 1 );
        function strip_json_shortcodes( $content ) {
	    return strip_shortcodes( $content );
        };

But this does not work and instead an error warning comes back : 
    strpos() expects parameter 1 to be string.

Is there a way to strip shortcodes from posts?

**Comment by petitphp** [comment]
I'm assuming you use version 1 of the WP-API.
The `json_prepare_post` param is an array (you can look at the documentation : http://wp-api.org/#entities_post), hence the error. The correct way of stripping shortcodes would be :
```php
add_filter( 'json_prepare_post', 'strip_json_shortcodes' );
function strip_json_shortcodes( $post_arr ) {
    if ( ! empty( $post_arr['content'] ) {
         $post_arr['content'] = strip_shortcodes( $post_arr['content'] );
    }
    return $post_arr;
}
```
_Note that this would strip shortcodes in all posts types (post, page etc) content not just the 'post' one_

**Comment by storynory** [comment]
Thank you !

**Comment by storynory** [comment]
Actually I've tried the above with  Version 1.2.3 (the lastest stable in the plugin directory) and it does not throw an error but it does not strip the codes out out either... just returns the content as normal...
