### ISSUE TITLE
How to remove or exclude fields from a response? (v2)

### ISSUE THREAD

**Issue by sdsanders** [WP-API/WP-API#1485]
The documentation mentions that it's not a good idea to remove fields:

> The API exposes many fields on API responses, including things you might not need, or might not fit into how your site works. While it's tempting to modify or remove fields from responses, this will cause problems with API clients that expect standard responses. This includes things like mobile clients, or third party tools to help you manage your site.

My project is only going to be accessed by one client (mine), so I'm totally fine with removing some unused fields to bring down the response file size. The documentation never actually demonstrates how to remove fields, though. All of the previous examples I found are related to the v1 API.

**Comment by mkiisoft** [comment]
I'm searching the same thing and we need some examples. I'm using a plugin for that on v1 API... but it doesn't work for custom meta data.

Remove/exclude fields from response is the best feature I can imaging... Sometimes I only need a really small 3 fields by array and not 30 meta keys. 120kb against 15kb it's not the same... and mostly for mobile phones (with terrible network connectivity sometimes) 

The plugin I was using for v1 is https://wordpress.org/plugins/wp-rest-api-filter-fields/ and you pass it like: &fields=ID,title (at the end... perfect!)

**Comment by rmccue** [comment]
For v2, if you want to permanently remove fields, you can filter `rest_prepare_{$type}` for posts.

**If at all possible though, don't do this.** Instead, subclass the controller and make your own endpoint that returns just the data you need, and make that available at `/wp-json/sdsanders/v1/posts` or similar. It's possible that WP itself will rely on these endpoints, such as in the admin, so changing it may break in the future.

@mkiisoft Nothing similar exists for v2 yet I think, but keeping it in a separate plugin is the approach we would take.

**Comment by mkiisoft** [comment]
@rmccue I've been helping with v1 support for the couple of weeks and there is a lot of repeat questions. I'm not a crazy "ninja" coder in PHP and SQL (almost 1.5 years both) but I'll love to help.

I can make great documentations, code examples, snippets (I have tons made it with great queries, endpoints, etc) more "official" if you want... or helping with code.
