### ISSUE TITLE
No rewrites leading to 404

### ISSUE THREAD

**Issue by mcgwebdesign** [WP-API/WP-API#1486]
I've installed WP-API at www.apploi.com but whenever I try to hit an endpoint I end up with a 404 error. I've flushed the permalinks and used Debug This to check the existing rewrites but there aren't any for /wp-json/. Any thoughts on what could be preventing this from working or any steps I can take to troubleshoot?

**Comment by rmccue** [comment]
Try disabling and re-enabling the plugin to see if this helps, since this should cause the permalinks to get flushed again.

**Comment by mcgwebdesign** [comment]
Hi @rmccue. Thanks for the feedback. I disabled, deleted, re-uploaded and re-enabled the plugin to no avail. Still can't access the endpoints

**Comment by mcgwebdesign** [comment]
I used rewrite Rules Inspector to flush out everything manually and that seemed to resolve it.
