### ISSUE TITLE
Query parameters being ignored

### ISSUE THREAD

**Issue by mcgwebdesign** [WP-API/WP-API#1487]
If I request a tag endpoint such as:
https://www.apploi.com/wp-json/wp/v2/posts/?tag=retail

it completely ignores the ?tag=retail part and just returns the unfiltered https://www.apploi.com/wp-json/wp/v2/posts/

Same goes if I try to request by ID or Category, it doesn't get filtered down. using ?filter[tag]=retail works as expected though

**Comment by colinhowells** [comment]
[filter] returned in 2.0b4:
https://github.com/WP-API/WP-API/issues/1477#issuecomment-130667544
https://github.com/WP-API/WP-API/releases/tag/2.0-beta4
