### ISSUE TITLE
Use short CURIEs instead of full URIs

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#1488]
One small annoyance in the API right now is that link relations are full URIs. In JavaScript, this means that while you have  `_links.self` and `_links.author`, you have to do `_links["http://v2.wp-api.org/term"]`. This is a bit ugly, and can be confusing.

We should instead switch to [CURIEs](https://en.wikipedia.org/wiki/CURIE). These are an abbreviated form of the full URI that's easier to work with, but can be expanded out to the full URI if needed. They look like this:

```json
{
    "_links": {
        "curies": [
            {
                "name": "wp",
                "href": "http://v2.wp-api.org/{rel}",
                "templated": true
            }
        ],

        "wp:term": [
            {
                "taxonomy": "category",
                "href": "..."
            },
            {
                "taxonomy": "post_tag",
                "href": "..."
            }
        ]
    }
}
```

**Comment by malfborger** [comment]
+1 !

**Comment by scottopolis** [comment]
+1

**Comment by danielbachhuber** [comment]
Closing in favor of https://core.trac.wordpress.org/ticket/34729

**Comment by danielbachhuber** [comment]
Actually, I just realized this will only affect our endpoints.

**Comment by danielbachhuber** [comment]
We should handle this magically in the server: https://core.trac.wordpress.org/ticket/34729

**Comment by danielbachhuber** [comment]
Re-opening, because we need to add a shim to the plugin when the server code lands.

**Comment by danielbachhuber** [comment]
@rmccue @joehoyle thoughts on how we can shim this into the plugin?

**Comment by joehoyle** [comment]
So I've been looking into doing this, we don't have good hooks in place to modify the response links, best I can see is to either run a subclass of the server class in the plugin, or filter the server response and look for links recursively (bit of a hack).

**Comment by danielbachhuber** [comment]
> best I can see is to either run a subclass of the server class in the plugin

I think subclassing seems like the cleanest implementation at this point
