### ISSUE TITLE
/wp-json/wp/v2/posts url throws a 404?

### ISSUE THREAD

**Issue by TDNewtonian** [WP-API/WP-API#1489]
Dumb question --

I've got my wordpress blog up and am trying to get the posts at my blog using the /wp-json/wp/v2/posts address.  It's throwing a 404.  I've triple checked and the address should be right. 

Any thoughts on why this is happening?  I'm running WP 4.3.

**Comment by jaredcobb** [comment]
Are you using pretty permalinks on your blog? (Any structure other than the default) https://codex.wordpress.org/Using_Permalinks#Choosing_your_permalink_structure

**Comment by jamietanna** [comment]
Not OP, but also seeing the same issue on 4.3.

I'm running the default permalink settings, and when browsing to `http://$siteurl/wp-json/wp/v2/posts` I also get a 404.

**Comment by jjeaton** [comment]
@jamietanna you aren't able to use the default permalink settings with the WP-API plugin, you must choose from one of the "pretty permalink" settings.

**Comment by joehoyle** [comment]
If you are using default permalinks (query params) you can access the API at `?rest_route=/`, for example http://demo.wp-api.org/?rest_route=/

**Comment by jamietanna** [comment]
Thanks both - looks like I've got an issue with rewriting as all I get is 404s when I change permalink settings.

**Comment by TDNewtonian** [comment]
Yep!  Pretty permalinks were the problem.  Thanks for the tip!

**Comment by joshrouwhorst** [comment]
For anyone else who might run into this...

I suddenly ran into this issue when I updated my UI. I realized I sent a new version of the .htaccess file. To fix, I went into the Permalinks section, switched my settings from "Post name" to "Plain", saved, then switch back and saved again. It started working at that point.
