### ISSUE TITLE
Psr fig standards and rest api

### ISSUE THREAD

**Issue by hasannawaz** [WP-API/WP-API#1490]
I know this is not a general QA channel, But am new and question is for core leads, might have been asked before but i was wondering why wordpress does not implement psr0, psr2 or psr4 and now psr7 will be adopted for restapi, as it is still in dev ?

Am still new to wordpress code base but i have an idea about it being quite procedural…but any specific reason not to move towards oop ?

Thank you

**Comment by rmccue** [comment]
Answered [in the WordPress Slack](https://wordpress.slack.com/archives/core/p1440122453000183)
