### ISSUE TITLE
Can't delete Media

### ISSUE THREAD

**Issue by thiago-negri** [WP-API/WP-API#1493]
When I try to delete a Media (`DELETE /wp/v2/media/{id}`), server returns 501 with the following JSON:

```json
[ { "code": "rest_trash_not_supported",
    "message": "The post does not support trashing.",
    "data": { "status": 501 } } ]
```

If I try to force it (`DELETE /wp/v2/media/{id}?force=true`), server returns 403:

```json
[ { "code": "rest_cannot_delete",
    "message": "Sorry, you are not allowed to delete posts.",
    "data": { "status": 403 } } ]
```

I'm using admin credentials.

**Comment by rachelbaker** [comment]
@thiago-negri You can add `define( 'MEDIA_TRASH', true );` to your wp-config.php file or

**Comment by thiago-negri** [comment]
@rachelbaker By adding `define( 'MEDIA_TRASH', true );` to the wp-config file I could trash the Media (delete without force).

But, I still get 403 when trying to force-delete.

I'm using the current tip of "develop" branch.

**Comment by thiago-negri** [comment]
The problem was at the OAuth library I was using. It didn't generate correct signatures for URLs with query strings.

Sorry.
