### ISSUE TITLE
Can't delete Meta for a Post

### ISSUE THREAD

**Issue by thiago-negri** [WP-API/WP-API#1495]
Same as #1493, but for Meta.

```javascript
// DELETE https://localhost/trunk/wp-json/wp/v2/posts/6/meta/36
[ { code: 'rest_trash_not_supported',
    message: 'Meta does not support trashing.',
    data: { status: 501 } } ]
```

```javascript
// DELETE https://localhost/trunk/wp-json/wp/v2/posts/6/meta/36?force=true
[ { code: 'rest_forbidden',
    message: 'Sorry, you cannot delete the meta for this post.',
    data: { status: 403 } } ]
```

Using admin credentials.

**Comment by thiago-negri** [comment]
The problem was at the OAuth library I was using. 

Sorry.

**Comment by amjad** [comment]
I keep getting this issue. How did you solve it?

**Comment by thiago-negri** [comment]
@amjad The OAuth library I was using didn't correctly generate signature strings considering query parameters. Check if the query parameter `force=true` is being considered in the signature.
