### ISSUE TITLE
Deleting a post (move to trash) does not return 202 Accepted

### ISSUE THREAD

**Issue by sogko** [WP-API/WP-API#1496]
Hi guys,

I understand that the documentation for v2 API at http://v2.wp-api.org/ is still rough, 
so I'm using [routes.md](https://github.com/WP-API/WP-API/blob/df3c3847c96627c38f9060957fc3fe20427aa6eb/docs/routes/routes.md#response-4) and http://wp-api.org/#posts_delete-a-post for references, so correct me if I'm looking at the wrong places.

From what I understand from the documentation that `DELETE /post/<id>` should return:
- `202 Accepted` if post is moved to trash (`force=false`)
- `200 OK` if post is deleted permanently (`force=true`)

Currently, both of them return `200 OK`.

Thanks!

**Comment by rachelbaker** [comment]
@sogko In v2, if the delete action is completed successfully we return a status of 200.
