### ISSUE TITLE
Actions before and after dispatching a request

### ISSUE THREAD

**Issue by pento** [WP-API/WP-API#1503]
Actions triggered immediately before and after dispatching a request would be quite useful.

For example, if a Multisite install were to set up a single domain for handling API requests (ie, api.wordpress.com), there's currently no nice way to switch the site when dispatching the request.

It's possible to switch the site before the request is dispatched using one of the filters available, but there's nothing afterwards to switch back. Being able to switch back is important for handling batch requests (#561) under these circumstances.

**Comment by danielbachhuber** [comment]
@pento are `rest_pre_dispatch` and `rest_post_dispatch` sufficient for your needs now?

**Comment by pento** [comment]
Yep, they should do the job. Thanks for the pointer. :)
