### ISSUE TITLE
Separate out the namespace from the path in rest_url/get_rest_url functions

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#1504]
Quoting @staylor:

> Why are namespace + path combined as the $path args in register_rest_route() and get_rest_url()?  Why not: get_rest_route_url( $ns, $path, $scheme, $blog_id = 0 )?

The current args for `get_rest_url( $blog_id = null, $path = '/', $scheme = 'json' )` and `rest_url( $path = '', $scheme = 'json' )` use a single `$path` argument to set the namespace and route.  This is inconsistent with `register_rest_route( $namespace, $route, $args = array(), $override = false )` where we expect separate arguments for the namespace and path/route arguments.

Based on the team discussion via [Slack](https://wordpress.slack.com/archives/core-restapi/p1440457792000107)

**Comment by rachelbaker** [comment]
Per [discussion in Slack](https://wordpress.slack.com/archives/core-restapi/p1445296367000082) ...
add `$namespace` param
rename `$path` param -> `$route`

**Comment by rachelbaker** [comment]
Also related to #1505

**Comment by rmccue** [comment]
Moved to [Trac](https://core.trac.wordpress.org/ticket/34416).

**Comment by rmccue** [comment]
Accidentally had the wrong ticket here before; [filed correctly on Trac now](https://core.trac.wordpress.org/ticket/34707).
