### ISSUE TITLE
Require the $namespace argument in register_rest_route()

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#1505]
Per discussion on [Slack](https://wordpress.slack.com/archives/core-restapi/p1440458533000138), we should return `true` on success, and add a `_doing_it_wrong()` and return `false` if the `$namespace` parameter is empty.
 
Related: #1355

**Comment by danielbachhuber** [comment]
Continued with https://core.trac.wordpress.org/ticket/34416
