### ISSUE TITLE
Add /themes endpoint

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#1507]
Based on the feedback from the Automattic team passed along by @pento:

> Themes
> Nothing in themes has been implemented.
> In particular, there’s no way to retrieve or set add_theme_support() type things. Featured image, registered nav menus, content_width, etc.

Related #632 and #1500 

This new resource still needs to be defined.

**Comment by danielbachhuber** [comment]
Theme management is now WIP in a separate plugin https://github.com/WP-API/wp-api-plugins-themes-endpoints
