### ISSUE TITLE
How do I add a custom query var to the `/terms/category` endpoint?

### ISSUE THREAD

**Issue by ptrckvzn** [WP-API/WP-API#1510]
Hi, this is more of a support request.

I'd like to allow a custom query var `lang` to `/wp-json/wp/v2/terms/category`, so that I can send my json request as : `/wp-json/wp/v2/terms/category?lang=fr` or `/wp-json/wp/v2/terms/category?filter[lang]=fr`.

I got this working in two different way by adding a few lines of code to the `get_items` function of `class-wp-rest-terms-controller.php` (WP-API 2.0-beta4). See lines between `begin`and `end`.

For `/wp-json/wp/v2/terms/category?lang=fr` :
```
	public function get_items( $request ) {
		$prepared_args = array( 'hide_empty' => false );

		$prepared_args['number']  = $request['per_page'];
		$prepared_args['offset']  = ( $request['page'] - 1 ) * $prepared_args['number'];
		$prepared_args['search']  = $request['search'];
		$prepared_args['order']   = $request['order'];
		$prepared_args['orderby'] = $request['orderby'];

		//== begin
		$prepared_args['lang'] = $request['lang'];
		//== end
```

or this way for `/wp-json/wp/v2/terms/category?filter[lang]=fr` :
```
	public function get_items( $request ) {
		$prepared_args = array( 'hide_empty' => false );

		$prepared_args['number']  = $request['per_page'];
		$prepared_args['offset']  = ( $request['page'] - 1 ) * $prepared_args['number'];
		$prepared_args['search']  = $request['search'];
		$prepared_args['order']   = $request['order'];
		$prepared_args['orderby'] = $request['orderby'];

		//== begin
		if ( isset( $request['filter'] ) ) {
			$prepared_args = array_merge( $prepared_args, $request['filter'] );
			unset( $prepared_args['filter'] );
		}
		//== end
```

Is there a way I could achieve the same result (add `lang` query var to `/wp-json/wp/v2/terms/category`) without modifying the json-rest-api files itself? Maybe in a plugin of its own?

**Comment by danielbachhuber** [comment]
You can filter `rest_post_dispatch` to adapt the response to your custom query variable: https://github.com/WP-API/api-core/blob/99648ad7ce9f5c811e8dd0a908a630e321b90c60/wp-includes/rest-api/class-wp-rest-server.php#L327

**Comment by equatorapps** [comment]
Sorry, how do we use this filter to limit or modify the query statement?

**Comment by jasonhjohnson** [comment]
Do we have an example of how to do this (besides what's in the class-wp-rest-server file)?

**Comment by rmccue** [comment]
For `filter`, this is a WP Query variable that you want to add, so you should use the existing WP infrastructure for this:
```php
add_action( 'init', function () {
	global $wp;
	$wp->add_query_var( 'lang' );
});
add_action( 'parse_query', function ( WP_Query $query ) {
	if ( $query->query['lang'] ) {
		$query->set( 'post_type', $query->get( 'post_type' ) . '__' . $query->query['lang'] );
	}
});
```

This will work with everything in WP (e.g. `?lang=...` on a normal page), not just the API.

For custom parameters to endpoints, this is more advanced, and depends on what you're trying to do. Generally, avoid this approach unless you have to.

**Comment by jasonhjohnson** [comment]
@rmccue Basically I have custom post type called "documents" and it has a custom field attached called "document_description." That's the field I'm trying to include in the filter[s] search, so, I'm not sure how to adapt the "lang" filter example accordingly. Any help is appreciated.

**Comment by rmccue** [comment]
@jasonhjohnson Changing WP's search is significantly different, but more to the point, this is unrelated to the REST API. Everything in `filter` gets passed through to WP Query directly (for whitelisted keys, which is what `$wp->add_query-var` is for), so if you can get your field included in normal WP Query's search, it'll work automatically in the API.
