### ISSUE TITLE
API description for user creation

### ISSUE THREAD

**Issue by thiago-negri** [WP-API/WP-API#1514]
To create a user, the [code handles a 'url' property](https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-users-controller.php#L549) that is not listed in the API description (['args' of endpoint](https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-users-controller.php#L24)).

Also, the 'args' of endpoint lists the property 'capabilities' that aren't handled.

**Comment by danielbachhuber** [comment]
This is a bug. `url` is marked `readonly=>true` ([ref](https://github.com/WP-API/WP-API/blob/8017f609c3237c3154b41150e398370bf75096b7/lib/endpoints/class-wp-rest-users-controller.php#L729)), which means it isn't exposed as an argument ([ref](https://github.com/WP-API/WP-API/blob/8017f609c3237c3154b41150e398370bf75096b7/lib/endpoints/class-wp-rest-controller.php#L378-L380))

**Comment by nullvariable** [comment]
so the solution here then is to update the schema?
