### ISSUE TITLE
Builds are failing thanks to WPCS

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#1518]
Looks like from WordPress-Coding-Standards/WordPress-Coding-Standards#417 the builds have started failing. You can see this in unrelated pull requests like #1511.

We should do two things:

1. Fix the violations, obviously
2. Stick to a fixed version of WPCS, so we can control updates instead.

Having builds fail for unrelated reasons is pretty shit. We just need a fixed version instead of `dev-develop` in our composer.json.

**Comment by thiago-negri** [comment]
I tried to fix the warnings in #1508.
Should I remove that commit (3a7873ed) from the PR?
