### ISSUE TITLE
Issues with is_numeric validator

### ISSUE THREAD

**Issue by ChrisWiegman** [WP-API/WP-API#1520]
When testing with a parameter using the is_numeric function to validate I'm getting the following:

Warning: is_numeric() expects exactly 1 parameter, 3 given in [...]/plugins/rest-api/lib/infrastructure/class-wp-rest-request.php on line 684

The odd thing is this hadn't happened in previous testing and seems to be a new problem. Thoughts?

**Comment by joehoyle** [comment]
I've experienced this issue with `floatval` too, even though it doesn't document any more than one param, passing too many arguments makes it return false. I'm not sure of the best way to solve this.

**Comment by danielbachhuber** [comment]
@joehoyle @ChrisWiegman where is `is_numeric()` being called with three params?

**Comment by joehoyle** [comment]
yeah I've run into this too, not sure if there is much we can do. The API will pass `$value, $param, $request` to the validate / sanitize callbacks, this causes issues with inbuilt functions like `is_numeric`. My work around has been to do: `validate_callback => function( $v ) { return is_numeric( $v ); }`

**Comment by danielbachhuber** [comment]
I'd like to address this in the infrastructure https://core.trac.wordpress.org/ticket/34659

**Comment by BE-Webdesign** [comment]
https://core.trac.wordpress.org/ticket/34659 With the diff looks good to me.

**Comment by danielbachhuber** [comment]
Closing in favor of the core ticket. `is_numeric()` doesn't affect the plugin itself at the moment.
