### ISSUE TITLE
Delete Post Terms, strange error on force parameter

### ISSUE THREAD

**Issue by itibook** [WP-API/WP-API#1522]
Hello,

when deleting a category from a post I get the following error:

```json
[{
    "code": "rest_trash_not_supported",
    "message": "Terms do not support trashing.",
    "data": {
      "status": 501
    }}]
```
as soon as I set the "force" parameter to false the error goes away and the category is deleted from the post as expected...

My expectation was that the "force" parameter was optional and anyway defaulted to "false". Let me know if I missed something.

**Comment by itibook** [comment]
I think the issue is in the following file class-wp-rest-posts-terms-controller.php

the ```if( ! $force)``` should be ```if($force)```

```php
public function delete_item( $request ) {
		$post     = get_post( absint( $request['post_id'] ) );
		$term_id  = absint( $request['term_id'] );
		$force = isset( $request['force'] ) ? (bool) $request['force'] : false;
		// We don't support trashing for this type, error out
		if ( ! $force ) {
			return new WP_Error( 'rest_trash_not_supported', __( 'Terms do not support trashing.' ), array( 'status' => 501 ) );
		}
```

**Comment by rachelbaker** [comment]
@itibook The logic here is correct.  To be consistent across each resource you have to specify the force parameter to delete a resource, otherwise the item is just trashed.  Not all resources support trashing at this time.  See #1304

**Comment by itibook** [comment]
ok, so the "force" parameter is mandatory and if not set in the call it is then defaulted to true (i.e. trashing)...

do I understand correctly?

ciao

Luca
