### ISSUE TITLE
/plugins resource

### ISSUE THREAD

**Issue by dankrause** [WP-API/WP-API#1523]
I'm proposing a `/plugins` resource, for managing plugin activation/deactivation, uninstall, and upgrade.

Following the discussion on the proposed `/core` endpoint (#1500), I'll lay this out in a similar fashion for discussion.

`GET /plugins` - Retrieve a list of all plugins
* *No parameters*
* *Return*
  * array of plugin objects

`GET /plugins/{plugin_name}` - Retrieve a single plugin
* *No parameters*
* *Return*
  * A single plugin object,

`PUT /plugins/{plugin_name}` - Upgrade, activate, or deactivate a single plugin
* *Parameters*
  * "active" (bool, optional): activate or deactivate the plugin
  * "latest" (bool, optional): set to true to upgrade the plugin
* *Return*
  * The updated plugin object

`DELETE /plugins/{plugin_name}` - Uninstall a single plugin
* *No parameters*
* *No return*

The structure of a plugin object is taken directly from the results of [get_plugins](https://developer.wordpress.org/reference/functions/get_plugins/), with two additional fields:
* "latest" (bool): indicates whether or not this plugin is currently the latest version available
* "active" (bool): indicates whether or not this plugin is active

An implementation of this is available in #1482.

Some thoughts for discussion:
* Should plugin updates be broken into a separate resource, for example, at `/plugins/{plugin_name}/update`? This might be more consistent with the proposed `/core` endpoint.
* Plugins don't seem to have a unique identifier, other than the path. This looks strange in URLs. Is there a better way to do this?
* The need to find and install new plugins via the API is out of scope of this proposal.

**Comment by swissspidy** [comment]
Regatding the unique identifier for plugins, I think there was a core ticket to add something like that.

**Comment by silverbux** [comment]
+1

**Comment by danielbachhuber** [comment]
Plugin management through the API is now happening as a dedicated plugin https://github.com/WP-API/wp-api-plugins-themes-endpoints

**Comment by matrixik** [comment]
Great, thank you.
