### ISSUE TITLE
Change nonce name to `_wpnonce`

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#1524]
Currently we use `_wp_rest_nonce` or something, which is a) too verbose, b) doesn't match the prefixing of other meta-parameters (like `_envelope`, `_embed`, etc). If we change it to `_wpnonce` instead, it's much shorter, and also gains compatibility with existing stuff like `wp_nonce_field`

(This is from a very old planning doc, totally missed it.)

**Comment by danielbachhuber** [comment]
Created a core ticket for this one: https://core.trac.wordpress.org/ticket/34375
