### ISSUE TITLE
featured_image throwing 401 error: json_user_cannot_read

### ISSUE THREAD

**Issue by dhruvlbb** [WP-API/WP-API#1526]
When hitting the api for a specific post, all the data is getting returned, except the featured image, which is giving this error:

"featured_image":{"errors":{"json_user_cannot_read":["Sorry, you cannot read this post."]},"error_data":{"json_user_cannot_read":{"status":401}}}

Auth has been tested and working fine, and the user sending the request is a super-admin. This is happening intermittently, with no common factor between the posts where the error is coming up.

**Comment by tommedema** [comment]
Same here

**Comment by rmccue** [comment]
Make sure you're sending the nonce along with the request. In addition, we recommend upgrading from v1 to v2 :)

**Comment by oppodeldoc** [comment]
Hi there, I was also having this issue, it seemed random and I then I noticed the pattern causing it. If something is set to be a featured image on a post *and isn't actually attached to that post*, the error occurs. This would seem to be a permissions issue disallowing the WP-API from returning information about the featured image of a post unless that post is the parent of the attachment. 

This is just a theory based upon observation, I haven't had time to delve into the plugin code here. Also, I'm still using V1 (we're in production) and I wonder if this has been resolved already in the V2 beta. Any thoughts? I feel like we should be able to query featured images whether they are attached to the post or not.

**Comment by danielbachhuber** [comment]
> I feel like we should be able to query featured images whether they are attached to the post or not.

The current behavior is that we require the image to be attached to the post, or not attached to any post.

**Comment by danielbachhuber** [comment]
But, I'll start a new thread in a bit about reconsidering this behavior.

**Comment by oppodeldoc** [comment]
Got it, that wasn't super clear. This is obviously edge case, but nice to know it isn't "Random".  I don't actually see any reason where I couldn't work around this in the rare instances it comes up. 

I can confirm it's working as expected, but for anyone else who stumbles on this issue, if you're authenticating properly, it's probably due to the fact that the featured image is actually attached to a different post.  Cheers, and thanks again for all your work!
