### ISSUE TITLE
Set appropriate HTTP status when passing through WP_Error

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#153]
As noted by @tobych in #146, core functions that return `WP_Error`s currently all have a 500 status code. However, we should be able to parse out a better status code based on the code in the error.

**Comment by danielbachhuber** [comment]
I skimmed through all instances where we're checking `is_wp_error()`. Here are the places we're looking at the return value of core PHP APIs:
- [x] `wp_insert_post()` https://github.com/WP-API/WP-API/blob/1d70d3958270ff2e46bb894033ad56ba1b91bd48/lib/endpoints/class-wp-rest-attachments-controller.php#L69-L71
- [x] `wp_insert_post()` https://github.com/WP-API/WP-API/blob/1d70d3958270ff2e46bb894033ad56ba1b91bd48/lib/endpoints/class-wp-rest-posts-controller.php#L192-L202
- [ ] `wp_set_object_terms()` https://github.com/WP-API/WP-API/blob/1d70d3958270ff2e46bb894033ad56ba1b91bd48/lib/endpoints/class-wp-rest-posts-terms-controller.php#L136-L140
- [ ] `wp_remove_object_terms()` https://github.com/WP-API/WP-API/blob/1d70d3958270ff2e46bb894033ad56ba1b91bd48/lib/endpoints/class-wp-rest-posts-terms-controller.php#L182-L186
- [ ] `get_term()` https://github.com/WP-API/WP-API/blob/1d70d3958270ff2e46bb894033ad56ba1b91bd48/lib/endpoints/class-wp-rest-terms-controller.php#L161-L167
- [ ] `wp_insert_term()` https://github.com/WP-API/WP-API/blob/1d70d3958270ff2e46bb894033ad56ba1b91bd48/lib/endpoints/class-wp-rest-terms-controller.php#L206-L218
- [ ] `wp_update_term()` https://github.com/WP-API/WP-API/blob/1d70d3958270ff2e46bb894033ad56ba1b91bd48/lib/endpoints/class-wp-rest-terms-controller.php#L269-L273
- [ ] `WP_User_Query()` https://github.com/WP-API/WP-API/blob/1d70d3958270ff2e46bb894033ad56ba1b91bd48/lib/endpoints/class-wp-rest-users-controller.php#L117-L120
- [ ] `wpmu_validate_user_signup()` https://github.com/WP-API/WP-API/blob/1d70d3958270ff2e46bb894033ad56ba1b91bd48/lib/endpoints/class-wp-rest-users-controller.php#L225-L228
- [ ] `wp_update_user()` https://github.com/WP-API/WP-API/blob/1d70d3958270ff2e46bb894033ad56ba1b91bd48/lib/endpoints/class-wp-rest-users-controller.php#L237-L240
- [ ] `wp_insert_user()` https://github.com/WP-API/WP-API/blob/1d70d3958270ff2e46bb894033ad56ba1b91bd48/lib/endpoints/class-wp-rest-users-controller.php#L242-L245
- [ ] `wp_update_user()` https://github.com/WP-API/WP-API/blob/1d70d3958270ff2e46bb894033ad56ba1b91bd48/lib/endpoints/class-wp-rest-users-controller.php#L309-L312

**Comment by danielbachhuber** [comment]
Conversation in Slack: https://wordpress.slack.com/archives/core-restapi/p1452555784003945

> rmccue [3:45 PM] Yeah, but more to the point, no need to handle it separately in our code, it's better to sprinkle through core

Going forward, we should make sure core functions that return `WP_Error` include a status code.

**Comment by danielbachhuber** [comment]
> Going forward, we should make sure core functions that return WP_Error include a status code.

I've started a core ticket for this: https://core.trac.wordpress.org/ticket/35425
