### ISSUE TITLE
Multisite Sub Site Authentication

### ISSUE THREAD

**Issue by hefejeff** [WP-API/WP-API#1531]
As far as I can tell there are no oauth server plugins that handle multisite authentication which leaves my only option being cookies I believe.  Does WP REST API include endpoints for retrieving and using authentication cookies?

**Comment by joehoyle** [comment]
@hefejeff could you clarify what you mean by multisite authentication? You want to get authentication tokens (using oauth 1 perhaps) that you can use on any of the networks sites?

We don't have a way to issue Cookies for auth currently, @rmccue could probably weigh in on the implications of that.

**Comment by hefejeff** [comment]
Yes the idea is to obtain a token that can be used on sites a user is registered on on a multisite system.  We have no problem getting and using tokens on the main site but no luck on any sub sites.  

I am currently building an endpoint that will return an authentication cookie seeing that I can not figure out how to get/use auth tokens for the subsites.
