### ISSUE TITLE
CPT filter timeframe

### ISSUE THREAD

**Issue by joneslloyd** [WP-API/WP-API#1534]
Hello,

I know this is unorthodox, so I apologise in advance for this, but - I was wondering if you have a rough / vague / guesstimate timeframe with regards to when this functionality may be working:
https://github.com/WP-API/WP-API/issues/1344

I've got a WordPress / Backbone app almost ready to launch, apart from that feature.

Sorry for my insolence!!

**Comment by danielbachhuber** [comment]
There's no timeline as to when the JS client will be updated to fully support v2.x.
