### ISSUE TITLE
oauth creation

### ISSUE THREAD

**Issue by LudovicFauchet** [WP-API/WP-API#1535]
Hello,

I'm a newbie and i would like some help PLEASE :)
I added wp-api on a website to use posts in an  Android and iOS app.

I added OAuth Server, and i create a token with wp-cli on localhost. After i push to my server with wordmove.

But the http://mywesite.com/wp-json/posts is always viewable by anyone. I have done something wrong ?

Best regards

Ludovic

**Comment by joehoyle** [comment]
@LudovicFauchet many of the wp-api endpoints are public (such as `/posts`) but like the RSS feed shows posts at `/feed` publicly. 

If you want to disable all non-authenticated requests to the API you could hook into the `rest_pre_dispatch` checking permissions for the current logged in user and returning a `WP_Error`.

**Comment by LudovicFauchet** [comment]
@joehoyle So what is the utility of oauth authentification i had done ?

The many public endpoints are not a security problem ?

**Comment by joehoyle** [comment]
@LudovicFauchet many things in the API require authentication, for example, creating a post. If you just want to read your published posts, you don't need authentication, just like you don't need authentication to view the posts on your website.

All the public information available through the API is available on the website via URL / Feed access.

**Comment by LudovicFauchet** [comment]
@joehoyle Ok thank you very much for those informations and the rapidity of answer ;)
