### ISSUE TITLE
Add wp-json to the blacklist for new ms sites

### ISSUE THREAD

**Issue by chriscct7** [WP-API/WP-API#1542]
When a patch is made for WP core (not something to worry about now), the endpoint wp-json should be added to the blacklist for new ms sites. See https://core.trac.wordpress.org/ticket/33615#comment:7

**Comment by austinginder** [comment]
Since the referenced ticket has been already been added, I opened a new ticket with patch here: https://core.trac.wordpress.org/ticket/33789 for discussion and inclusion.

**Comment by austinginder** [comment]
This has been merged into core: https://core.trac.wordpress.org/changeset/34375
