### ISSUE TITLE
Make the "Method not implemented" message specific

### ISSUE THREAD

**Issue by stephywells** [WP-API/WP-API#1546]
It was a bit of a headache to extend the WP_REST_Controller class when I was seeing the "Method not implemented. Must be over-ridden in subclass." message. While developing, I had to add  __FUNCTION__ to the message so I could tell which functions I was missing.

**Comment by wibwradio** [comment]
unsubscribe

**Comment by rachelbaker** [comment]
@wibwradio I removed your reply to this issue assuming it was an error.
