### ISSUE TITLE
Approving a comment deletes content and author

### ISSUE THREAD

**Issue by scottopolis** [WP-API/WP-API#1548]
*Bug:* Changing comment status from hold to approved using a PUT request deletes the comment author and comment content. I am using the basic auth plugin and an $http request in AngularJS.

*How to replicate:* Add an unapproved comment to your site with the WP API v2 and basic auth plugins installed. Using Postman, send a PUT request with a basic auth header to a comment endpoint, such as mysite.com/wp-json/wp/v2/comments/54

In the form data, send along status=approved.  The comment will be approved, but the comment author and comment content are deleted.

**Comment by scottopolis** [comment]
Sending a POST instead of PUT seems to retain the comment author, but the content is still deleted.

**Comment by rachelbaker** [comment]
@scottopolis Thank you for reporting this.  Looks like the default values from the schema are causing this issue.  I started going down this rabbit hole and ran out of energy for the evening.  I will pick it back up tomorrow.

**Comment by scottopolis** [comment]
I think I figured out the issue here, will send a PR shortly.

**Comment by joehoyle** [comment]
@scottopolis I have a fix in #1557 already, just need to clean a couple things up before merging

**Comment by scottopolis** [comment]
@joehoyle ok cool. Just FYI I'll report what I found here in case it's helpful:

Line 218 of class-wp-rest-comments-controller.php $prepared_args is not empty, so the next line `if ( empty( $prepared_args ) && isset( $request['status'] ) ) ` is false when it should be true.

Going down to `$this->prepare_item_for_database( $request )` I found that `$request['parent']` is 0 instead of empty, and `$request['author_name']` is "" instead of null.  That is why $prepared_args is not empty.

Hope that helps!

**Comment by rachelbaker** [comment]
Fixed in #1557
