### ISSUE TITLE
v2 - List custom posts types

### ISSUE THREAD

**Issue by piotrkulpinski** [WP-API/WP-API#1550]
Hi there,
I'm having trouble with getting list of posts with custom type. I was trying to get it by using the code from the old API but without any luck.

```
http://example.com/wp-json/wp/v2/posts?type=event
```

Also, I'm not sure how to get posts only with given custom meta fields. I was trying the code below but also without any luck:
```
http://example.com/wp-json/wp/v2/posts?type=event&filter[meta_key]=event_date&filter[meta_value]=20150917
```

Any ideas? 
Thanks

**Comment by joneslloyd** [comment]
I've been having the same issue:
https://github.com/WP-API/WP-API/issues/1534

**Comment by scottopolis** [comment]
CPTs are opt-in only in v2 apparently.  You have to add show_in_rest = true to your CPT registration function for it to show in the API. You could also use the code here: https://github.com/WP-API/WP-API/issues/1299

**Comment by rmccue** [comment]
As @scottopolis said, they're opt-in only in v2. If you want to see what types are available, `/wp/v2/types` shows what's exposed via the API.
