### ISSUE TITLE
Can i use the wordpress official api endpoints by install this plugin?

### ISSUE THREAD

**Issue by Ting-y** [WP-API/WP-API#1561]
Is the plugin support the official wordpress api endpoints on https://developer.wordpress.com/docs/api/ ?

If not, is there any plans to implement that in the future releases?

**Comment by Shelob9** [comment]
@Ting-y That documentation is for the WordPress.com API, not this API, which is confusing. That API is available on non-WordPress.com sites when using the Jetpack JSON API module.
