### ISSUE TITLE
Add some hooks where missing.

### ISSUE THREAD

**Issue by adamsilverstein** [WP-API/WP-API#1571]
Recently I worked on adding/cleaning up hook docs, see: https://github.com/WP-API/WP-API/issues/1549.

During the hook audit, I noticed several hooks that seemed to missing, see https://github.com/WP-API/WP-API/issues/1549#issuecomment-141571410. I'm using this issue to track additional hooks added.

**Comment by adamsilverstein** [comment]
Started working on this, here is a current inventory of hooks:

https://docs.google.com/spreadsheets/d/1XP6r-XDq60_cgeR-my4B_VUUrMw5B_C1lMXc-5AylII/edit?usp=sharing

**Comment by danielbachhuber** [comment]
As a part of this issue, we should draft https://github.com/WP-API/docs-v2/issues/61

I'm not opposed to adding more actions and filters. I just want to have some semblance of sanity for where we add them vs. where we don't.

**Comment by adamsilverstein** [comment]
Closing this since we added the hooks. Agree about documenting philosophy, thanks.
