### ISSUE TITLE
Basic Authentication not working for doing new post

### ISSUE THREAD

**Issue by JimClermonts** [WP-API/WP-API#1572]
I'm using:
Wordpress 4.3.1
WP BASIC Auth 1.1.3
WP REST API 2.0-beta4

I've added below code to my htaccess.conf file, because [this thread told me so](https://github.com/WP-API/WP-API/issues/1335):
```
<IfModule !php5_module>
    Define USE_PHP_FPM
	RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
</IfModule>
```

Type in command line:
```
curl --data-binary "@updated-post.json" -H "Content-Type: application/javascript" --user "my_admin_user_name":"my_admin_password" http://www.mysite.nu/wp-json/wp/v2/posts
```

Contents of **updated-post.json**:
```
{
    "title": "Hello Updated World!",
    "content_raw": "<p>Howdy updated content.<\/p>",
    "date": "2013-04-01T14:00:00+10:00"
}
```

Error code:
```
[{"code":"rest_forbidden","message":"You don't have permission to do this.","data":{"status":403}}]
```

The GET request does work. Some help would be much appreciated!

**Comment by jaredcobb** [comment]
This may or may not be the issue, but I've never used double quotes in the `--user` flag. Does is work with:
```
curl --data-binary "@updated-post.json" -H "Content-Type: application/javascript" --user my_admin_user_name:my_admin_password http://www.mysite.nu/wp-json/wp/v2/posts
```

**Comment by JimClermonts** [comment]
The reason I'm using double quotes is because the password contains a (. And If I don't do it, it says

syntax error near unexpected token `('

**Comment by jaredcobb** [comment]
Ah. Try escaping your `(` with a backslash like so: `\(`.

**Comment by JimClermonts** [comment]
Yeah, already tried that, also changed my password, same problem:

```
[{"code":"rest_forbidden","message":"You don't have permission to do this.","data":{"status":403}}] 
```

**Comment by jaredcobb** [comment]
Do the credentials belong to a user with Editor or Administrator privileges in WordPress?

**Comment by JimClermonts** [comment]
Administrator rights!

**Comment by jaredcobb** [comment]
Hmm, sort of difficult to guess anything else. I would probably attempt to use xdebug or var_dump the request headers (as they're seen by the server) as a starting point. It definitely seems like the authentication headers aren't being sent as you expect them to be.

**Comment by JimClermonts** [comment]
The whole reason to do basic auth is because it was quick and dirty. So I guess it's better to implement OAuth and see if that works. I'm not a PHP programmer so not sure how to do var_dump.

**Comment by jaredcobb** [comment]
I agree Basic Auth is easier. I guess I'm saying I would eliminate the
command line cURL as the issue by just testing real quick with Postman.

**Comment by JimClermonts** [comment]
After doing this, the whole site stopped working.

**Comment by jaredcobb** [comment]
Sending a `POST` request with Postman caused your site to go down?

**Comment by JimClermonts** [comment]
The frontpage now shows a popup 

"Please enter your password".

Doesn't make any sense to me....  I'm gonna SSH and delete the WP-API plugin.

**Comment by JimClermonts** [comment]
I've gone into the plugins directory and done:

```
rm -rf json-rest-api/
rm -rf rest-api/
rm -rf wp-basic-auth/
rm -rf oauth2-provider/
```

Now my site works again. But still same problem :)

**Comment by JimClermonts** [comment]
This is unresolved. I've opened a [new thread](https://github.com/WP-API/WP-API/issues/1573) here, trying the same with OAuth1.0. Which also doesn't work.

**Comment by rmccue** [comment]
For the `--user` bit, try with `--user="username:password"` with the colon _inside_ the quotes. Let me know if that works.

**Comment by danielbachhuber** [comment]
You should use the [WP-API Basic Auth](https://github.com/WP-API/Basic-Auth) plugin, not [WP Basic Auth](https://wordpress.org/plugins/wp-basic-auth/).

**Comment by roshredbull** [comment]
how to update,delete wordpress comments in postman. i am getting "Sorry, you are not allowed to edit this comment" -authenication error ...please help me....thank you....
