### ISSUE TITLE
Changing a taxonomy name breaks the filter

### ISSUE THREAD

**Issue by damienoneill2001** [WP-API/WP-API#1578]
Hello,

From what I can tell, using v1.2.3, when a term has had it's name changed, the filters no longer work.

In my  site, a number of my terms included hyphens, so `first-term`.  I ran into problems accessing the data with the hyphens, so I renamed the terms so they displayed as camel case.  So `first-term` became `firstTerm`.

I reset my permalinks so all the posts/terms were up to date and then tried to access the filter, however, now all the posts show rather than the filtered posts.

Perviously, I would filter by doing the following and one result would be found: 
`http://www.adoptapet.ie/wp-json/posts/?type=cats&filter[location-cats]=cavan`

Now, it is the following and all results are displayed:
`http://www.adoptapet.ie/wp-json/posts/?type=cats&filter[locationCats]=cavan` 

It is as if the filter is completely ignored now.

Hopefully this is something that can be looked into.

Damien

**Comment by damienoneill2001** [comment]
Looks like the issue turned out to be with the camel case name.  Changing the taxonomy name from `locationCats` to `locationcats` resolved the issue.

Thanks to @modemlooper for the help with this.

Damien

**Comment by modemlooper** [comment]
taxonomy filter is the slug and that is lower case.

**Comment by rmccue** [comment]
Sounds like this is resolved, so closing out.
