### ISSUE TITLE
rest_invalid_param if post slug is empty string

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#1585]
> Invalid parameter(s): slug (slug is not of type string)

This should use the automatically generated one instead.

**Comment by rmccue** [comment]
Turns out this is because we're using `sanitize_title` here, which is then using `$fallback_title`, which we have set to the request object.

**Comment by joehoyle** [comment]
Essentially the same issue in https://github.com/WP-API/WP-API/issues/1520

**Comment by danielbachhuber** [comment]
Discussion on how to address this in https://wordpress.slack.com/archives/core-restapi/p1446505675001052

**Comment by danielbachhuber** [comment]
Couple more options:

> danielbachhuber [12:50 PM] 3. have some abstraction for being able to supply a validation callback like `is_numeric()`, and ensure it’s only called with one argument `validate_callback_pass_context=false`
> wonderboymusic [12:50 PM] I, personally, would whitelist some PHP global funcs that they get passed their expected # of args

**Comment by danielbachhuber** [comment]
I think we should actually address this in the infrastructure: https://core.trac.wordpress.org/ticket/34659

**Comment by rmccue** [comment]
This has an infrastructure ticket, closing here.
