### ISSUE TITLE
GET multiple pages by id

### ISSUE THREAD

**Issue by danielpina** [WP-API/WP-API#1587]
Trying to retrieve multiple authors works fine (```author=2,6,17,38```) as the string is exploded and fits into the query
 ```
 [author__in] => Array
                (
                    [0] => 2
                    [1] => 6
                    [2] => 17
                    [3] => 38
                )
```
__or__
```
wp_posts.post_author IN (2,6,17,38)
```
but trying to retrieve multiple pages does not work. The string is not exploded. I tried 
```
page_id=14,12
p=14,12
post__in=14,12
```
Is there anything I'm missing?

**Comment by joehoyle** [comment]
@danielpina we only support the WordPress `public_query_vars` which doesn't include `post__in` is not a public query var.

Retrieving multiple objects by ID is not something that is very RESTful to do at this level, a cleaner REST way would be to just request all the resources separately. I've also toyed with the idea of a `/multi` endpoint to retrieve multiple resources in a single HTTP request, see https://gist.github.com/joehoyle/44a71a2e458b05c22a10 

@WP-API/amigos any thoughts on allowing an `include` param (or similar) on all collections endpoints to retrieve multiple of that resource?

**Comment by danielbachhuber** [comment]
> any thoughts on allowing an include param (or similar) on all collections endpoints to retrieve multiple of that resource?

Dig it https://github.com/WP-API/WP-API/issues/1668
