### ISSUE TITLE
Meta doesn't DELETE and PUT doesn't work

### ISSUE THREAD

**Issue by andrewahead4** [WP-API/WP-API#1594]
![screen shot 2015-09-23 at 17 27 37](https://cloud.githubusercontent.com/assets/9017231/10051297/ca656950-6218-11e5-94a0-b25917270742.png)
As you can see from the screenshot using Postman and it tells me delete isn't supported.
Also in meta I can't update meta data using a PUT but it does update with a POST method and the metaID.

**Comment by rmccue** [comment]
> As you can see from the screenshot using Postman and it tells me delete isn't supported.

You need to pass `force=true` to permanently delete meta, as it doesn't support trashing. :)

> Also in meta I can't update meta data using a PUT but it does update with a POST method and the metaID.

Hmm, that's weird, it should definitely work. Will look into it.

**Comment by andrewahead4** [comment]
Thanks Ryan that works :)
Re the POST/PUT issue here are similar screenshots 
![screen shot 2015-09-24 at 09 35 47](https://cloud.githubusercontent.com/assets/9017231/10068951/9b67c980-62a0-11e5-9133-c0f738c78f9e.png)
![screen shot 2015-09-24 at 09 35 10](https://cloud.githubusercontent.com/assets/9017231/10068952/a12e5c58-62a0-11e5-99a0-00e5cf766977.png)

**Comment by danielbachhuber** [comment]
I can't reproduce the `PUT` bug:

Request:
```
PUT /wp-json/wp/v2/posts/1/meta/9 HTTP/1.1
Authorization: Basic ZGFuaWVsOmRhbmllbA==
Content-Type: application/x-www-form-urlencoded
Host: wordpress-develop.dev
Connection: close
User-Agent: Paw/2.2.6 (Macintosh; OS X/10.10.5) GCDHTTPRequest
Content-Length: 19

key=foo&value=apple
```

Response:
```
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Tue, 08 Dec 2015 17:10:20 GMT
Content-Type: application/json; charset=UTF-8
Transfer-Encoding: chunked
Connection: close
X-Powered-By: PHP/5.5.9-1ubuntu4.7
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
Access-Control-Allow-Headers: Authorization
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Cache-Control: no-cache, must-revalidate, max-age=0
Pragma: no-cache
Last-Modified: 
Allow: GET, POST, PUT, PATCH, DELETE

{"id":9,"key":"foo","value":"apple","_links":{"about":[{"embeddable":true,"href":"http:\/\/wordpress-develop.dev\/wp-json\/wp\/posts\/1"}]}}
```
