### ISSUE TITLE
how do I get post_metas on custom post type

### ISSUE THREAD

**Issue by lgt** [WP-API/WP-API#1595]
I just started again to use this plugin and I face an issue on retrieving  post_metas attached to my custom post type. I already have enabled the route in my plugin and I get datas on endpoint 

`/wp-json/wp/v2/estates`

but this one does not contain any related meta datas. Is there a way to get those?

**Comment by Shelob9** [comment]
Just like with default post types, you will need to add custom meta fields as custom fields to the response. See this section of the docs: http://v2.wp-api.org/extending/modifying/

**Comment by lgt** [comment]
thank you for feedback. Hovewer I have problems to use the callback inside class
Having the following example which registers desidered meta field, how do I use the callback with OOP?

Referencing function `slug_get_starship()` method as `array($this, 'slug_get_starship')` would not work

```
class myClass{

public function __construct(){
     add_action( 'rest_api_init',array( $this, 'slug_register_starship' ) );
}

function slug_register_starship() {
    register_api_field( 'post',
        'starship',
        array(
            'get_callback'    => array($this, 'slug_get_starship'),
            'update_callback' => null,
            'schema'          => null,
        )
    );
}

public function slug_get_starship( $object, $field_name, $request ) {
    return get_post_meta( $object[ 'id' ], $field_name, true );
}
}
```

**Comment by Shelob9** [comment]
Why wouldn't it work? Your code looks fine to me. For a working and unit
tested example, see:

https://github.com/CalderaWP/seo-rest-api-fields/blob/master/seo-rest-api-fields.php

thank you for feedback. Hovewer I have problems to use the callback inside
class
Having the following example which registers desidered meta field, how do I
use the callback with OOP?

Referencing function slug_get_starship() method as array($this,
'slug_get_starship') would not work

class myClass{

public function __construct(){
     add_action( 'rest_api_init',array( $this, 'slug_register_starship' ) );
}

function slug_register_starship() {
    register_api_field( 'post',
        'starship',
        array(
            'get_callback'    => array($this, 'slug_get_starship'),
            'update_callback' => null,
            'schema'          => null,
        )
    );
}

public function slug_get_starship( $object, $field_name, $request ) {
    return get_post_meta( $object[ 'id' ], $field_name, true );
}
}

—
Reply to this email directly or view it on GitHub
<https://github.com/WP-API/WP-API/issues/1595#issuecomment-142837959>.

**Comment by nicdford** [comment]
@Shelob9 I was having this same issue last night, the fields don't seem to register properly with custom post types. I was able to get it work with normal posts though.
