### ISSUE TITLE
get registration - attendee details

### ISSUE THREAD

**Issue by msyadav88** [WP-API/WP-API#1598]
I have setup the oauth authentication from referring below link
https://www.youtube.com/watch?v=pRFCmjiRNco

I am just stuck in a issue.
Below code is working properly
$client->setAccessToken('myaccesstoken');
$url = 'http://v2.iregister.ie/wp-json/ee/v4.6/registrations';
$response = $client->fetch($url);
But below code giving error
$client->setAccessToken('myaccesstoken');
$url = 'http://v2.iregister.ie/wp-json/ee/v4.6/registrations?';
$response = $client->fetch($url);

Error: Sorry, you are not allowed to list registrations. Missing permissions: ee_read_registrations,ee_read_others_registrations

Actually, i want the attendee email id from this
http://v2.iregister.ie/wp-json/ee/v4.6/registrations?include=Attendee.ATT_email

But its not working

Is the query string is creating the issue?

**Comment by danielbachhuber** [comment]
This is a support question better suited for EventEspresso.
