### ISSUE TITLE
Example how to set category in WP REST API 1.2.3

### ISSUE THREAD

**Issue by JimClermonts** [WP-API/WP-API#1600]
Since WP REST API 2.0 wasn't working for my site, I've downgraded to 1.2.3 and that works fine. So my question is for 1.2.3.

```
{"title": "Gezocht","content_raw":"testing","status":"publish"}
```

Above JSON string works fine. I want to set the category also:
```
"category_name":"bijbaan" 
```
Adding the above string doesn't work. I've looked in the [documentation](http://wp-api.org/#posts_create-a-post). That's how I found **category_name**. Do you guys have suggestions?

Best,
Jim

**Comment by joehoyle** [comment]
@JimClermonts `category_name` is a filter parameter, not an attribute of the post object. To update / set the category I believe you'd do `{ "terms" : { "category": [ 45 ] } }` if the given category ID is 45. I don't think there's a way to assign categories based off names.

I'd also strongly encourage you to try v2 again, and work with us (or do more debugging :) ) to find out why it isn't working, as there's no development effort going into v1.

**Comment by JimClermonts** [comment]
Okay thanks, will try it out tonight. Switching to v2 is on our backlog tasks :).
