### ISSUE TITLE
Golang client for WP-API v2

### ISSUE THREAD

**Issue by sogko** [WP-API/WP-API#1606]
Hey guys, I wrote a Golang client library for WP-API v2 about month ago. I needed it for a client project and wrote one since I couldn't find an existing library for it.  We have been using it internally since.

**Status** (as of 28 Sept 2015)
- Authentication: currently only supports Basic Authentication, but I might add OAuth support if there is a demand for it (or anyone is welcomed to contribute a PR for it, I'll gladly accept it)
- [List of implemented v2 endpoints](https://github.com/sogko/go-wordpress/blob/master/endpoints.md)

Anyway, its at https://github.com/sogko/go-wordpress

Cheers!

**Comment by joehoyle** [comment]
Fantastic! I wonder if some kind of auto discovery from http://demo.wp-api.org/wp-json/?context=help would be possible so you wouldn't need to hardcode the endpoints, that may not be so simple though!

@WP-API/amigos do we (or should we) have a list of clients somewhere?

**Comment by kadamwhite** [comment]
@joehoyle We do! See http://wp-api.org/resources.html, created in WP-API/WP-API.github.io#19 after original discussion in #264.

**Comment by kadamwhite** [comment]
@sogko Took a look at your client, very cool! It looks like you adopted a comparatively similar API to my [wordpress-rest-api](https://github.com/kadamwhite/wordpress-rest-api) Node project, and I've also struggled with OAuth—I'm not extraordinarily familiar with Go, but if you want to work through implementations I'd still be up for being a sounding board, just let me know.

**Comment by danielbachhuber** [comment]
I've filed an issue in the docs repo for when we get to reproducing the clients page for v2: https://github.com/WP-API/docs-v2/issues/62

Thanks for the contribution, @sogko
