### ISSUE TITLE
Limit number of requested items for collection queries

### ISSUE THREAD

**Issue by Toddses** [WP-API/WP-API#1609]
No way to query for all terms. With `get_terms()` from WordPress you can pass the `number` arg as 0, or it defaults to 0, to get all the terms with the associated taxonomy. The terms controller uses `per_page` to fill out the `number` arg. The default for `per_page` is 10, and you can't pass 0 to this argument (or any negative numbers, because it sanitizes the value with `absint`). This effectively makes it impossible to query for all terms in a taxonomy.

**Comment by donaldallen** [comment]
Can't figure this one out either.

**Comment by donaldallen** [comment]
How are you using filtering on this request?

I've tried:

```
wp-json/wp/v2/terms/community_area?filter[per_page]=100
```

And I'm still only getting back 10 results. Is per_page incorrect usage? I tried this as well:

```
wp-json/wp/v2/terms/community_area?filter[number]=100
```

**Comment by Toddses** [comment]
'....?per_page=100'

Asssuming you're using v2.0. Don't need the filter on this one.

**Comment by donaldallen** [comment]
So even if I do that, I only get back 10 results. If I go into ```class-wp-rest-terms-controller.php``` and change:

```
$prepared_args['number']  = $request['per_page'];
```

to:

```
$prepared_args['number']  = 100;
```

That works. When I var_dump the $request, I'm not seeing per_page or anything else I pass through.

**Comment by Toddses** [comment]
Strange - I don't seem to be having this issue. I can pass per_page and get the expected results. What version of the API are you running?

**Comment by donaldallen** [comment]
Args for my custom post type:

```
    $args = [
        'label'               => __('community', 'something'),
        'description'         => __('Community', 'something'),
        'labels'              => $labels,
        'supports'            => ['title', 'thumbnail', 'editor', 'excerpt'],
        'hierarchical'        => false,
        'public'              => true,
        'show_in_rest'        => true,
        'show_ui'             => true,
        'show_in_menu'        => true,
        'show_in_nav_menus'   => false,
        'show_in_admin_bar'   => false,
        'menu_position'       => 31,
        'menu_icon'           => 'dashicons-admin-multisite',
        'can_export'          => true,
        'has_archive'         => true,
        'exclude_from_search' => false,
        'publicly_queryable'  => true,
        'capability_type'     => 'page',
    ];
```

And the args for my taxonomy:

```
    $args = [
        'labels'                     => $labels,
        'hierarchical'               => true,
        'public'                     => true,
        'show_in_rest'               => true,
        'show_ui'                    => true,
        'show_admin_column'          => true,
        'show_in_nav_menus'          => true,
        'show_tagcloud'              => true,
        'query_var'                  => true,
        'rewrite' => [
            'hierarchical' => true,
        ]
   ];
```

Running 2.0-beta4.

**Comment by joehoyle** [comment]
This is working on the Demo site at: http://demo.wp-api.org/wp-json/wp/v2/terms/category?per_page=100

In regards to getting all terms at once (rather than paged) we are currently trying to make all the collections consistant, so `/posts` for example, doesn't allow fetching on unlimited data sets but instead implements paging. This is pretty typically of most REST apis, however I'm not staunchly against that. Will flag at the next meeting or feedback welcome from the @WP-API/amigos

**Comment by donaldallen** [comment]
Thanks @joehoyle. Any ideas why it wouldn't be working with my setup? Bare-bone WP install, with WP REST API 2.0-beta4. My custom post type and taxonomy args are above. No matter what I enter in per_page, I only get 10 results.

My URL looks similar to the one you shared: http://mysite.dev/wp-json/wp/v2/terms/community_area?per_page=100

**Comment by joehoyle** [comment]
I think you were probably close with `var_dump`ing the request object where you were before. I'm not sure why it wouldn't pick up your query param there - unless there's some odd server config with forwarding those. Could you maybe also var_dump `$_GET` and `$request` where you were debugging before?

**Comment by Toddses** [comment]
Maybe try to add these args to the taxonomy creation

```
'rest_base'         => 'community_area',
'rest_controller_class' => 'WP_REST_Terms_Controller'
```

**Comment by donaldallen** [comment]
Weird, when I dump $_GET, it's empty. I wonder if it's related to any of my rewrites. Going to check it out.

**Comment by Toddses** [comment]
@joehoyle Well let me ask what's better for performance - querying for all terms and getting a large dataset, or hitting the server with a whole bunch of requests in a row? I don't mind adding the complexity of getting a paginated result set when I want everything, but if that negatively affects the performance we're going to see, obviously that's a different story.

**Comment by joehoyle** [comment]
@Toddses yes in that case getting more at once is better, however that also depends on preventing attacks where you'd have some throttling on requests etc, so in terms of defence I'd still prefer the fewer at a time approach. This breaks down given that we support `per_page=9999999` now anyway, so this is just inconvenient right now with us not letting a `0` query through. I'm going to flag this for discussion so we can talk about what the general approach though be to paginated / unlimited queries.

**Comment by danielbachhuber** [comment]
> In regards to getting all terms at once (rather than paged) we are currently trying to make all the collections consistant, so /posts for example, doesn't allow fetching on unlimited data sets but instead implements paging.

Requesting thousands of entities at once can let an unauthorized client easily overload a server. I think we need to limit by default. If you have access to the server, you could always change the limit.

**Comment by Toddses** [comment]
But couldn't said client just as easily overload the server regardless? If they can ping the page over and over, requesting thousands of entities at once, couldn't they just ping the page over and over, requesting ten entities at once, thousands of times?

**Comment by Toddses** [comment]
What about when someone requests a hundred entities thousands of times? Wouldn't that overload the server just as quickly? Is it possible to only allow nonced requests to succeed?

**Comment by joehoyle** [comment]
@Toddses see my comment about rate limiting above.

**Comment by Toddses** [comment]
Right on, missed that. I kind of wonder if that will have unintended side effects. For instance I have 1000 terms, but the API only allows me to make 5 requests in some small time frame, then starts rejecting requests, and the entity limit per request is say 100. To me this situation seems like the complexity of getting all the data at once becomes high, when getting all those terms is a very common use case. Could a nonced request get a different set of limits? Seems like it would be safe to let an authorized request get more data, and any unauthorized request could follow stricter limits, potentially avoiding the problem of an unauthorized client bringing the server to its knees.

**Comment by danielbachhuber** [comment]
After some discussion, we're going to set a lower bound on `per_page` to 1, and a default upper bound of 100

**Comment by kadamwhite** [comment]
:+1:

**Comment by chrishaff** [comment]
Hm, this breaks my app, so I haven't installed 2.0 Beta 12.0 yet.  What is the mechanism for changing the upper bound?  Edit source or something prettier?

**Comment by rmccue** [comment]
You should be able to filter `rest_endpoints` and change the `maximum` value there. This should potentially be easier, but ideally you shouldn't be changing this.

**Comment by jtosey** [comment]
This breaks our app too.  Can you explain in more detail how to change this?  I've manually changed our first install, but will fork if we have to.  We need to get all items, not a page.  Perhaps an option to get all, with a requirement that the invoker is authenticated?

**Comment by danielbachhuber** [comment]
@jtosey You should paginate through the collection in your app. Querying for all items at once has performance issues and could crash the website.

**Comment by jtosey** [comment]
Okay, we'll try to find a way to work within the current constraints.

**Comment by ghost** [comment]
Just wanted to mention this was easily fixable by adding a line into the function thats creating the taxonomy as an argument.
```
'per_page' => array(
	'default' => 100
),
```

I had the same issue with a website that features a lot of communities and I was only getting 10 results back through the REST API. Changing that allowed me to show more json results

My code example:
```
function create_posttype() {
	register_post_type( 'properties',
	// CPT Options
		array(
			'labels' => array(
				'name' 			=> __( 'Properties' ),
				'singular_name' => __( 'Property' )
			),
			'description'				=> __( 'Description.', 'create_posttype' ),
			'public'					=> true,
			'has_archive' 				=> true,
			'hierarchical'  			=> false,
			'show_in_rest'       		=> true,
			'per_page' 					=> array(
											'default' => 100
										),
			'supports' 					=> array('title','editor','thumbnail','revisions'),
			'rest_base'         	 	=> 'properties-api',
			'rest_controller_class'	 	=> 'WP_REST_Posts_Controller',
			'rewrite' 					=> array('slug' => 'properties')
		)
	);
}
add_action( 'init', 'create_posttype' );
```

**Comment by jgangso** [comment]
@steamsynthetic do you know if there are any similar argument for custom taxonomies?
