### ISSUE TITLE
How to implement comment threading using `GET /comments` ?

### ISSUE THREAD

**Issue by southp** [WP-API/WP-API#1612]
I'm working on a plugin featuring viewport-based infinite scrolling of comments using WP API v2.
As the endpoint `GET /comments` responds paged data in descending order of date (which is reasonable), I am wondering how could I display comment threads properly before everything is loaded? For example, like the hierarchical looks of the theme twenty-fifteen.

For example, suppose there are 5 comments in descending order: c4, c3, c2, c1, c0, and the parent of c4 is c0. If I set `page=1, per_page=4`, there is no way I can show c4 as a reply of c0 before c0 is actually loaded.

Currently I only have thought of two possible ways:

* Do not use viewport-based infinite scrolling. Load new pages automatically instead, and refresh the comment hierarchy as needed.
    * I think this can solve the problem, but what if users' prefer viewport-based way, like I do? 
* Add a `child` field in the response data.
    * I think this might be the weirdest, because there is no such a data in WP database. Also, the thread setting might be changed.

I'm wondering, is there any other way? Do I miss any helpful feature of WP API for this?

Thanks.

**Comment by joehoyle** [comment]
Hmm interesting, so this is how I see it working:

`GET http://demo.wp-api.org/wp-json/wp/v2/comments?post=49&parent=0?_embed` and I think we could then add a `replies` link to each comment which would basically link to  `http://demo.wp-api.org/wp-json/wp/v2/comments?parent={comment_id}`. Passing `_embed` would then allow all the replies to load in (recursively). The only issue I see with this is it would be potentially a lot of data to load at once (if say a given comment has 200 replies) but that may be an edge case.

You'd probably want to also only embed the replies, not the rest of the embeddable links (see `up`), which we don't currently support in the API. This kind of hierarchical stuff isn't super simple in REST, but I think the use case is a valid one. I can see that we are 90% of the way there to have a good way to do this. I'd say the immediate todos:

1. Add a `replies` link to each comment that is `embeddable`
1. Discuss how we can to recursive whitelisted embedding

**Comment by southp** [comment]
Hi @joehoyle ,
Thanks for taking this further.

I think adding an `parent` query parameter is a good way. I was thinking about how to do thread collapsing like Facebook does and it was not an easy thing with the current API. With it, I think both use cases can be fulfilled.

As I am quite new to this, I would like to ask for some clarifications:

> Passing _embed would then allow all the replies to load in (recursively)  
>

Would you mind to explain this in more details? e.g. What's the difference in behavior of with / without `_embed`? A pseudo example to demonstrate the usage will be extremely helpful for me.

> not the rest of the embeddable links (see up).  
>

Sorry that I failed to figure out the `up` you mentioned. Would you please refer a link or explain this for me? Also, what is `embeddable`?

Right now, I am not quite sure about the `replies` links. I think it is because I don't understand the questions above :smile: 

With the `parent` parameter present, I could do the following pseudo code:

```
// Return the response of GET /comments?post=<id>&parent=cid, 
// paging is handled recursively, or just stop at the page which is visible by the current viewport.
get_comment_with_parent( cid ) ; 
update_comment_thread_view();

// Wooo... a big NONO to mixing of data & view code. Just demonstrate the idea.
get_comments( root_cid ) {
    root = get_comment_with_parent( root_cid );
    update_comment_thread_view();

    foreach comment in root {
        get_comments( comment.id );
    }
}
get_comments( 0 );
```
Since `GET /comments?post=<id>` endpoint is paged with `page` & `per_page`, maybe the edge case you mentioned could be addressed via the same paging functionality?

**Comment by danielbachhuber** [comment]
We should add a link when a comment has children.
