### ISSUE TITLE
WP-API-2.0-beta4: Combine embed & context=edit

### ISSUE THREAD

**Issue by steefaan** [WP-API/WP-API#1615]
Not sure if this is a bug or works as designed but if I do a request like `/posts/1?_embed&context=edit` I expected a complete response in `edit` context but only the response of the post itself is in `edit` context. The embedded records are still in `view` context.

**Comment by joehoyle** [comment]
hmmm yeah I think it should do what you want here, probably needs some discussion though.

**Comment by BrunoWinck** [comment]
My sugegstion would be to have context as an array and allow to ask for combination of edit, view and embed fields. In my case I would love to have the leanest edit context but faster and larger result sets.

**Comment by danielbachhuber** [comment]
Related #1845

**Comment by danielbachhuber** [comment]
In the interest of simplicity, the `context` argument will always apply to the requested resource. `?_embed` is a magical argument to get the embedded representation of linked resources. Should you want the full representation, you'll need to make an additional request.
