### ISSUE TITLE
register_api_field not working with custom post types

### ISSUE THREAD

**Issue by nicdford** [WP-API/WP-API#1616]
The register_api_field code doesn't seem to work with custom post types. It works fine with 'post' however both 'client' and 'book' (custom post types I setup with custom endpoints) don't add the field 'starship' to the response. Is there an extra step i'm missing to get the register_api_field to work with custom post types or is this a bug?

``````
add_action( 'rest_api_init', function () {

    register_api_field( array( 'post', 'client', 'book' ) ,
        'starship',
        array(
            'get_callback'    => 'get_field_starship',
            'update_callback' => null,
            'schema'          => null,
        )
    );

} );

function get_field_starship( $object, $field_name, $request ) {
    return get_post_meta( $object[ 'id' ], 'starship', true );
}
``````

**Comment by Shelob9** [comment]
Are client & book registered with REST support? See this docs PR for more information?

**Comment by nicdford** [comment]
That was the missing piece, thank you!
