### ISSUE TITLE
class-wp-json-server.php Fatal error

### ISSUE THREAD

**Issue by Amjadf** [WP-API/WP-API#1617]
I got this issue when I run it. 
<br />
<b>Fatal error</b>:  Call to undefined function wp_json_encode() in <b> /wp-content/plugins/rest-api/lib/infrastructure/class-wp-rest-server.php</b> on line <b>360</b><br />

**Comment by danielbachhuber** [comment]
`wp_json_encode()` was added in WP 4.1, so you're likely on an older version than that. 

The `develop` branch, and corresponding beta releases, of WP-API require WordPress trunk.
