### ISSUE TITLE
Need to detect if the Infrastructure is being loaded by core in plugin

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#1618]
Once https://core.trac.wordpress.org/ticket/33982 is merged, we will need to allow the plugin to be installed and use the core infrastructure instead.

**Comment by danielbachhuber** [comment]
Couple of options:

1. `class_exists()`. It's not very glamorous, but it does the job.
2. Register an autoloader which will pull classes from our plugin when they don't exist in core. Potentially more precise, but subject to whatever SPL compatibility issues we might be subject to.

**Comment by rmccue** [comment]
As of 52a80281c8b51e92b99a2ef76fb4f88af0722c5c we're now loading api-core as a submodule if there's no infrastructure loaded. We check for the presence of the `REST_API_VERSION` constant, which will be `2.0` in core.

Right now, `api-core` has a few extra bits for compatibility that means it doesn't exactly match the patch; fixing those up nowish.

**Comment by rmccue** [comment]
And, we have an API in core. :) https://core.trac.wordpress.org/changeset/34928

Everything seems to be going OK over here.
