### ISSUE TITLE
GET for posts returns one extra result up to per_page=15

### ISSUE THREAD

**Issue by andrewahead4** [WP-API/WP-API#1623]
I have found that posts endpoint is returning one extra result for all requests up to and including setting the per_page param to 15, change this to 16 or greater and it returns the number requested. If you add the param page=n where n is 2 or greater then it returns what you would expect.

For the sake of explanation I made a video showing this in action in the postman chrome extension but unfortunately I can't upload that to here. If you want it let me know

**Comment by rachelbaker** [comment]
@andrewahead4 do you have any sticky posts?  Just curious if that could be the issue.

**Comment by andrewahead4** [comment]
@rachelbaker You have it, that seems to be the issue.

I have been using the sample data to see what happens and there is a sticky post in that and it is the first item that is returned with the next n being the results as per a standard search.

Just thought I would see if it took the sticky out of the results and it does if it would have been one of the first page, i.e. it appears once. If it is on a subsequent page it does get included.

**Comment by bilalvirgo10** [comment]
Be sure to include `filter[ignore_sticky_posts]` in the request to ignore sticky posts. Like the following:

`/wp-json/wp/v2/posts?filter[ignore_sticky_posts]`

**Comment by danielbachhuber** [comment]
Flagging this for discussion in 2.0, as I think we should decide whether `ignore_sticky_posts` is enabled by default or not — and, to what degree we support sticky posts in the API.

**Comment by danielbachhuber** [comment]
We could also reverse core behavior and ignore sticky posts by default, unless a `respect_sticky_posts` flag is passed.

**Comment by joehoyle** [comment]
I'm strongly in favour of removing sticky posts by default, I don't think it makes sense as the API doesn't have the concept of list pages etc



Joe Hoyle
Technical Lead
humanmade

e joe@humanmade.co.uk
t +44 (0) 7891 685613
skype joe-hoyle
w humanmade.co.uk

**Comment by joehoyle** [comment]
Also `respect_sticky_posts` is.... weird, out of context. +1 for `include_sticky_posts`

**Comment by danielbachhuber** [comment]
[Some chats](https://wordpress.slack.com/archives/core-restapi/p1448926578000866):

> rmccue ​[3:38] I've been thinking about that for a while, there's no solution I like really
> joehoyle [3:38 PM] I don't think I understand any argument for including sticky posts(edited)
> joehoyle ​[3:39] just like we dnt respect the posts_per_page admin option(edited)
> rmccue [3:39 PM] Sticky exists for a reason though
> rmccue ​[3:40] posts_per_page is just a default/display setting, which is different
> joehoyle [3:40 PM] isn't sticky that?
> danielbachhuber [3:40 PM] sticky posts exist for a templating-specific context
> danielbachhuber ​[3:40] you can replicate sticky posts by getting the post ids for sticky posts, and making a request for just those posts
> danielbachhuber ​[3:40] and then making another request which excludes those posts
> joehoyle [3:41 PM] I think given they are (lets be honest) a pretty naff feature, we can ​_support_​ them (just about) as daniel suggests above, and be done with it
> danielbachhuber [3:42 PM] I wonder what WPcom does
> rmccue [3:42 PM] Mmm, I think we need support
> joehoyle [3:42 PM] that is "support" :simple_smile:
> rmccue [3:42 PM] I'd be OK with `/posts?sticky=true` or something

**Comment by danielbachhuber** [comment]
We're going to ignore sticky posts by default, and only permit them when `filter[ignore_sticky_posts]=>false` is present.
