### ISSUE TITLE
Some limitations from WP-API V2

### ISSUE THREAD

**Issue by rebelholic** [WP-API/WP-API#1624]
I have some problem when making an ionic app for [my blog](http://unity3dindonesia.com/) like below:

* How I can retrieve a post with raw text without mixed any html codes like below:
![wpapi2](https://cloud.githubusercontent.com/assets/6254876/10261760/c3796550-69d0-11e5-8fba-374a33eafc5f.jpg)
 
I am using a "JSON Callback" method like this http://unity3dindonesia.com/wp-json/wp/v2/posts/156?_jsonp=JSON_CALLBACK to retrieve a post

* How I can make pagination and retrieve the featured image for posts list?
![wpapi](https://cloud.githubusercontent.com/assets/6254876/10261766/fe228a38-69d0-11e5-97a7-622266cfae2c.jpg)

My API URL: http://unity3dindonesia.com/wp-json/wp/v2

**Comment by therajanmaurya** [comment]
textview.setText(Html.fromHtml("Your Content String Return From Api"));
Using This, it will show in TextView Like Raw text

**Comment by rebelholic** [comment]
@therajanmaurya thanks for your answer.

What's WP-API code to show a featured image on posts list?

What's WP-API code to make pagination for post lists?

**Comment by therajanmaurya** [comment]
For featured image, use the "featured_image" key of the post and go here: 

    http://<domain>/wp-json/wp/v2/media/<featured_image>

For pagination:

    http://<domain>/wp-json/wp/v2/posts?page=<page_number>

**Comment by therajanmaurya** [comment]
For featured image, use the "featured_image" key of the post and go here: 

    http://<domain>/wp-json/wp/v2/media/<featured_image>

For pagination:

    http://<domain>/wp-json/wp/v2/posts?page=<page_number>

**Comment by joehoyle** [comment]
@rebelholic reopen if you need more guidance. Also, check out http://v2.wp-api.org/

**Comment by rebelholic** [comment]
@therajanmaurya @joehoyle 
ok. What's WP-API code to get youtube link?
