### ISSUE TITLE
rest_invalid_param when registering schema of any type other than string with register_api_field()

### ISSUE THREAD

**Issue by bilalvirgo10** [WP-API/WP-API#1625]
I'm using the `register_api_field()` method to register a custom field `post_views` on `post` object with the following code:
```php
$schema = array(
		'description'	=> 'A description for this custom field',
		'type'			=> 'integer',
		'context'		=>	array( 'view', 'edit' )
	);

	register_api_field(
		'post',
		'post_views',
		array(
			'get_callback'		=> 'get_post_views_meta',
			'update_callback'	=> 'update_post_views_meta',
			'schema'			=> $schema
		)
	);
```
When an `OPTIONS` request is sent to `/posts`, the schema property value shows the following:
```javascript
"post_views": {
	"description": "A description for this custom field",
	"type": "integer",
	"context": [
		  "view",
		  "edit"
	]
}
```
Meaning that the field has been added successfully with the type `integer`.
However, when a `POST` or `PUT` request is sent to update the `post_views` meta using the following JSON object:
```javascript
{
    "key": "post_views",
    "value": 1234567890
}
```
It returns a `400 - Bad Request` with the following response:
```javascript
[
    {
        "code": "rest_invalid_param",
        "message": "Invalid parameter(s): value (value is not of type string)",
        "data": {
            "status": 400,
            "params": [
                "value (value is not of type string)"
            ]
        }
    }
]
```
I think the `register_api_field()` method is not checking the schema properly.

**Comment by joehoyle** [comment]
@bilalvirgo10 I may be missing something, but I don't understand your request data format of `key: string, value: string` you should be posting `{ "post_views": 1234567890 }` as the JSON blob to `/posts/{id}`

**Comment by bilalvirgo10** [comment]
@joehoyle I'm using `{key: string, value: anyvalue}` format since it's mentioned [here](http://wp-api.org/#posts_create-meta-for-a-post) to update the post meta. Using `{ "post_views": 1234567890 }` as you have mentioned, is having no affect on the post.

The point is that when I send meta value as a `string` it gets updated successfully. But when I try to send an integer in the value, it returns me the `400 - Bad Request` error that I've mentioned in my issue.

**Comment by joehoyle** [comment]
@bilalvirgo10 ah you have the wrong documentation there, as you are using v2, the docs are at http://v2.wp-api.org/ see http://v2.wp-api.org/extending/modifying/ there. You don't pass the data how you are here.

> The point is that when I send meta value as a string it gets updated successfully. But when I try to send an integer in the value, it returns me the 400 - Bad Request error that I've mentioned in my issue.

I'm a little confused by this - I don't understand how sending the data `{key: string, value: anyvalue}` to the single post endpoint is working, at best that should only work on the meta endpoint, but even then, `register_api_field` has nothing to do with the meta endpoints.

Perhaps you could create a gist of your code along with example CURL requests, as there is a good amount which isn't making sense to me about what you are saying you are doing.

Thanks!

**Comment by bilalvirgo10** [comment]
Hey @joehoyle 

Sorry for not mentioning the `posts/<id>/meta/<id>` endpoint :+1:  I was sending the request to the `posts/<id>/meta/<id>` endpoint and was therefore getting the `type` issue.

Sending a `POST` request to the `posts/<id>` endpoint is working as intended and is updating the `post_views` meta using the `{"post_views": 123456789}` format. So far so good.

However, this meta value is being inserted as a `string` rather than an `integer`.

So my question is that is the `$schema` property just for defining the schema or does it actually validates the value against the given type? If it does, than it's not working as it's not giving me any error when I send the a `string` value for `post_views`.

Here is the gist for the code: https://gist.github.com/bilalvirgo10/f916580d4b01a18d7c78

Thanks

**Comment by kjbenk** [comment]
@bilalvirgo10 I would have a look at using the meta endpoints laid out in this [feature plugin](https://github.com/WP-API/wp-api-meta-endpoints).  With that plugin you do not need to register new fields to a post object.

**Comment by BE-Webdesign** [comment]
Not sure if this is a bug still, unless I am misunderstanding the issue.  The type should be object or array not integer, for post_views.  I tried using `register_rest_field()` for all different schema types and I did not run into any request errors at all. I also would get matching errors for when they did occur i.e. is not of type integer for integers etc.
