### ISSUE TITLE
PUT acts like a GET for terms

### ISSUE THREAD

**Issue by andrewahead4** [WP-API/WP-API#1627]
Similar to the issue for the meta I have found that a PUT for the terms does not work except in this case it seems to be acting like a GET.

Changing the method to a POST with the termid set updates the term.

**Comment by danielbachhuber** [comment]
Can you share the exact request you're making, and its response?

**Comment by andrewahead4** [comment]
Sure, when I was looking at terms and wanting to create some custom ones I did so using the route /wp-json/wp/v2/terms/blogtag (blogtag being a custom taxonomy surfaced to the rest api) with a POST method, all good and had returned the new term with it's id. Then trying to change the term using a PUT method with the id added to the end point /wp-json/wp/v2/terms/blogtag/37 came back with response code 200 but nothing had changed, see the postman screenshot

![screen shot 2015-10-23 at 14 24 31](https://cloud.githubusercontent.com/assets/9017231/10693751/1f1c9b86-7992-11e5-81da-e4ee84367cb8.png)

Changing the method to POST updates the term, again see screenshot

![screen shot 2015-10-23 at 14 27 38](https://cloud.githubusercontent.com/assets/9017231/10693783/537aeb62-7992-11e5-905b-7649877709d4.png)

I think that this is dangerous since if you use a PUT and get back response code 200 you would expect it to have updated the entry, which it has not. Instead it merely sends back what is already there, i.e. acts like a GET
