### ISSUE TITLE
ID mismatch between categories in WP-API and DB terms/terms_taxonomy table

### ISSUE THREAD

**Issue by stonetip** [WP-API/WP-API#1628]
When I run a query for categories, e.g. http://<mysite>/wp-json/wp/v2/terms/category the ids and parent ids don't match what's in the MySQL tables. Yet when I run a query like /wp-json/wp/v2/posts?cat=566 (which is the DB id for the category vs. the API reporting it as 569) I get the posts under the proper category. If I use the id from the API I get none. (The posts retrieved using the DB id are the same as those retrieved using wp-json/wp/v2/posts?category_name=<slug>

**Comment by joehoyle** [comment]
@stonetip the IDs you are seeing in the WP API is the `term_taxonomy_id` not the `term_id`, though WordPress core recently split all shared terms (see https://make.wordpress.org/core/2015/02/16/taxonomy-term-splitting-in-4-2-a-developer-guide/) term_ids are not unique so it makes more sense to use the `term_taxonomy_id` in the API

**Comment by stonetip** [comment]
Okay, I see that now after modifying my SQL query. However, if /wp-json/wp/v2/terms/category is returning term_taxonomy_id, yet posts uses /wp-json/wp/v2/posts?cat={term_id} it seems like the API consumer is stuck plucking out the category_name (slug) and using that. Is there a way to get all the categories' term_ids? Or is that just going to run into potential duplicates?

I understand that even the slugs might be duplicated because they're under different taxonomical parents. Seems like ultimately, you need to use the term_taxonomy_id to determine the right one. Would it make sense then to have term_taxonomy_id be what API users feed in with the intention of retrieving all posts under that category? (/wp-json/wp/v2/posts?cat={term_taxonomy_id})

<b>All the hard work that has gone into WP-API is appreciated, along with the reasoning behind it.</b> I'm not familiar with the internal workings of WordPress. However, I don't think it's lazy or unsound to say <i>I don't want to become familiar with it.</i> The value of the API to my organization is that we can work with an intuitive, unsurprising interface in Swift, C# and javascript.

**Comment by joehoyle** [comment]
@stonetip right, so you would query by term taxonomy ID on posts - however we should provide a link to that in the term object (e.g. http://demo.wp-api.org/wp-json/wp/v2/terms/category/4) however, most of these decisions were made pre term splitting, so we could feasibly switch back to using IDs rather than TT id, as TT id is actually going to go away.

Also, you point about not wanting to know internals of WordPress is spot on, we definitely don't want you to need to either!

@WP-API/amigos now term splitting is done across the board, we could switch all the taxonomy stuff to use `term_id` now instead, as from what I understand `term_taxonomy_id` is the one that's going to be phased out.

**Comment by stonetip** [comment]
If I understand correctly, as mentioned in the "splitting in 4.2" link and @joehoyle's most recent reply, the term_id will be the "canonical" id going forward. If so, that would help us. Thanks.

**Comment by joehoyle** [comment]
@stonetip it will be in WordPress core yes, which should influence our direction on the REST API, however I'd like to get thoughts of other members of the team first there.

**Comment by rmccue** [comment]
@joehoyle I'm happy with that. Using `term_taxonomy_id` was to prepare ourselves for the term split, but seeing as they're equivalent now, shouldn't matter either way.

If WP_Query uses `term_id`, makes sense to use it there, so long as we're not making the situation worse.

(I'd love to hear @boonebgorges' take on this too.)

**Comment by boonebgorges** [comment]
Howdy all :)

To clarify a few points from above:

* `term_taxonomy_id` will never go away. The few places where WordPress uses it internally - such as in `WP_Tax_Query::transform_query()` - will go away over the next few versions, in favor of `term_id`. The one place where `term_taxonomy_id` is unlikely ever to be eliminated is as the `JOIN` condition for relationship queries. The `term_relationships` table has a `term_taxonomy_id` column, and moving it over to `term_id` would be a very large lift for very little benefit. That said, it'll be an internal tool that WP will generally stop passing around in its internals.

* `term_id` and `term_taxonomy_id` will generally be equivalent for all terms created after the 4.3 upgrade routine. `term_id` and `term_taxonomy_id` for all terms created prior to 4.3 - whether the terms were shared between taxonomies or not - cannot be assumed to be the same.

That being said, as of WP 4.4, `term_id` alone (ie, without specifying a taxonomy) should be assumed to be a sufficiently unique identifier. `get_term()` and the new `WP_Term` assume this. Not having dug into your term endpoints, I'd assume that the REST API can safely use `term_id` as the canonical reference too.

**Comment by joehoyle** [comment]
Ok, going to switch to term_id

**Comment by danielbachhuber** [comment]
:ship:

**Comment by tollmanz** [comment]
Just stopping in to say that I was bit by this bug and thanks to everyone taking the time to document this so well. My intuition of using `term_id` was validated. Thanks!
