### ISSUE TITLE
Trailing slash on WP_API_Settings.root?

### ISSUE THREAD

**Issue by samwilson** [WP-API/WP-API#1629]
With the current develop branch (45d2ce319f57a905a5dc3a6fb9561cfb540709e0) the `WP_API_Settings.root` ends in a slash, regardless of the permalink settings (`http://example.org/wp-json/` and `http://example.org/?rest_route=/`).

But with version 1.2.3 there seems to be a bug, and the URLs are `http://example.org/wp-json` and `http://example.org/?rest_route=/` respectively.

I'm just wondering if I should handle this discrepency in my client code (it's not hard) or if version 2 of json-rest-api is going to be released soonish? :)

**Comment by rmccue** [comment]
Version 2 is [available on repo](https://wordpress.org/plugins/rest-api/), but it's `rest-api` instead, as we broke compatibility. :)

**Comment by samwilson** [comment]
Oh cool! Thanks. I didn't even register that. I'll switch to it.
