### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by MannusEtten** [WP-API/WP-API#1631]
Hello,

is it possible to add documentation about the create_post/ create_media on the website?

**Comment by gtamas** [comment]
I would like to see this too. For example, how do I create an image attachment? 

@MannusEtten As for post, you can simply put together an object using the non-readonly fields described here:

http://v2.wp-api.org/reference/posts/

Then POST the data to /wp-json/wp/v2/posts. That's it, this will create the post for you.

**Comment by danielbachhuber** [comment]
Yep, we'll get it added https://github.com/WP-API/docs-v2/issues/59
