### ISSUE TITLE
only allow authenticated requests

### ISSUE THREAD

**Issue by Toddses** [WP-API/WP-API#1635]
I dug around but couldn't find anything on this. I'd like to force all API requests to be authenticated, even GET requests. Right now you don't have to pass a nonce in order to request posts, etc. But I'd like to force all requests to require authentication..

**Comment by joehoyle** [comment]
@Toddses you should use the `rest_pre_dispatch` filter like so:

```PHP
add_filter( 'rest_pre_dispatch', function() {
     if ( ! is_user_logged_in() ) {
        return new WP_Error( 'not-logged-in', 'API Requests are only supported for authenticated requests', array( 'status' => 401 ) );
    }
} );
```

However, I'd stress that if you want to lock down the API, you'll probably want to use a capability check rather than `is_user_logged_in` (such as `current_user_can( 'edit_posts' )`) as being logged in doesn't meant much if they are logged in as a user with no capabilities.

**Comment by Toddses** [comment]
Thanks Joe!

**Comment by Toddses** [comment]
@joehoyle This may not be a workable solution as is. The `rest_pre_dispatch` hook doesn't seem to know anything about the user. With this example, `is_user_logged_in()` returns nothing - not true or false, just nothing.

Did a little digging into the `is_user_logged_in()` function, and it is definitely getting called correctly, its just that WP doesn't know anything about the user in the `rest_pre_dispatch` filter. Essentially the same issue with `current_user_can()`.

**Comment by joehoyle** [comment]
@Toddses what kind of authentication are you using?

**Comment by Toddses** [comment]
Not doing anything special. Authenticating POST requests with the nonce (using `wp_create_nonce( 'wp_rest' )`). No authentication for GET requests - this is where I am seeing the issue.

I'll see if I can reproduce it on another site.

**Comment by Toddses** [comment]
Same results on another site with no application code, just the rest api and vanilla twentyfifteen.

**Comment by joehoyle** [comment]
Hmm that's certainly odd - are you able to create posts (POST /wp/v2/posts) or do you get an auth error for that?

**Comment by Toddses** [comment]
Same results.

Oddly enough, and its confusing that this works, but if I hook into `init` and test if the user is logged in there, I can add the `rest_pre_dispatch` filter if they are not logged in and just return the error. This seems to work as expected, but I have no idea why. You'd think if it was too early to know about the user in `rest_pre_dispatch`, hooking into `init` would be too late to get the filter working.

**Comment by joehoyle** [comment]
This sounds to me like the nonce is perhaps invalid, as that check is on `rest_authentication_errors` (after init) which will unset the current user if the nonce fails. Are you sending the nonce via the `_wp_rest_nonce` GET param or the `HTTP_X_WP_NONCE` header?

**Comment by Toddses** [comment]
For GET requests, I'm not sending the nonce at all.

For POST, its coming from `X-WP-Nonce` header.

If I remove the filter altogether, I have no issues GETting or POSTing.

**Comment by joehoyle** [comment]
For GET requests you'll need to send the nonce, otherwise you won't be authenticated (which is exactly what you are trying to do here). However, if you are sending it on POST and that's not working either then I'm not totally sure why that would be.

**Comment by Toddses** [comment]
You win. I set up a test POST on the tester site and wasn't sending the nonce like a fool.

I think this is worked out now - thanks for the help, Joe.

**Comment by joehoyle** [comment]
@Toddses good stuff!

**Comment by bcrigler** [comment]
Thanks this helped me a lot in my current project where I needed to force authentication for all GET requests.  Please consider adding this information to the WP Rest API documentation for all to find.  Was difficult to track down online.

**Comment by danielbachhuber** [comment]
> Please consider adding this information to the WP Rest API documentation for all to find.

I'm not sure the best place to put it at the moment, so I've filed an issue for it https://github.com/WP-API/docs-v2/issues/83
