### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by johnbillion** [WP-API/WP-API#1636]
52a8028 was a significant change, and prevents the plugin from fatal erroring when a user updates to latest WordPress trunk now that the REST API infrastructure is in core.

A new version of the REST API plugin should be tagged and released so that a user can update the plugin before they update core.

One of my sites fataled and it took me a while to realise what the problem was, considering the plugin was up to date according to its version number.

**Comment by danielmilner** [comment]
+1 - Ran into the same problem on my site.

**Comment by danielbachhuber** [comment]
Some discussion in Slack: https://wordpress.slack.com/archives/core-restapi/p1445528550000387

We'll be releasing beta5 as exclusively trunk compatibility for beta4. Everything else since beta4 will be going in beta6

**Comment by joehoyle** [comment]
See https://github.com/WP-API/WP-API/compare/2.0-beta4...beta-5 for the diff, was a little more tricky that picking a single commit

**Comment by danielbachhuber** [comment]
:ship:
