### ISSUE TITLE
post_meta field on submitting custom post type

### ISSUE THREAD

**Issue by isvaljek** [WP-API/WP-API#1637]
In the routes.md there's mention of post_meta property on the json object submitted to /posts endpoint.
Is the same valid for custom post types? I manage to submit the json but only the title sticks, no meta values are taken.
Here is my raw request:
POST http://mydomain/wp-json/wp/v2/file-action HTTP/1.1
Authorization: Basic anVyYToeMmYaxmo3eGtBOHJsTW5t
Accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml
User-Agent: RestSharp/105.2.3.0
Content-Type: application/json
Host: mydomain
Content-Length: 89
Accept-Encoding: gzip, deflate

{"title":"/home/korakinf/.lastlogin","post_meta":{"time":"2015-10-09T16:34:03.7983022Z"}}

**Comment by danielbachhuber** [comment]
> In the routes.md there's mention of post_meta property

`routes.md` is applicable for WP-API v1.x, and not 2.x. The request you're making is against a 2.x endpoint.

If your custom post type supports `custom-fields`, then the meta endpoint will be registered automatically: https://github.com/WP-API/WP-API/blob/52a80281c8b51e92b99a2ef76fb4f88af0722c5c/plugin.php#L143-L146

If you didn't add post type support for custom fields, you'll need to register the endpoints manually:

```
add_action( 'rest_api_init', function() {
	$meta_controller = new WP_REST_Meta_Posts_Controller( 'my-post-type-rest-base' );
	$meta_controller->register_routes();
});
```

**Comment by isvaljek** [comment]
I've added the custom-fields supports to register_post_type.
But how should the json request be formed for multiple meta values insertion?

**Comment by danielbachhuber** [comment]
> But how should the json request be formed for multiple meta values insertion?

The REST API doesn't support submitting multiple meta values at once.

You'd be better off using `register_api_field` for your post type: http://v2.wp-api.org/extending/modifying/#how-to-use-register_api_field
