### ISSUE TITLE
Show posts based on category

### ISSUE THREAD

**Issue by rebelholic** [WP-API/WP-API#1642]
What's WP-API code to Show posts based on a category?

**Comment by stonetip** [comment]
If you're asking what the routing should be it's either:

   wp-json/wp/v2/posts?category_name=
   (textual)
or:

   wp-json/wp/v2/posts?cat=
   (id)

**Comment by rebelholic** [comment]
@stonetip I already tried with my website (http://unity3dindonesia.com/wp-json/wp/v2/posts?cat=news) but show all posts

**Comment by stonetip** [comment]
Use an id number with cat. Use "news" with category_name, e.g:

http://unity3dindonesia.com/wp-json/wp/v2/posts?category_name=news

**Comment by rebelholic** [comment]
@stonetip Yeah I already tried everything what you said but still not luck

**Comment by Toddses** [comment]
Try

```
?filter[category_name]=news
```

**Comment by rebelholic** [comment]
@Toddses Thanks its worked
