### ISSUE TITLE
Distinction between page and post a bit arbitrary

### ISSUE THREAD

**Issue by BrunoWinck** [WP-API/WP-API#1647]
Although most users will see a radical difference between pages and posts from API pov it's very much the same object. The more so that WP allows to create new types. This prefigure the evolution toward composite documents (subposts) and multimedia documents (svg being both a post and a picture). It's more of the CMS usage of WP then on the pure blogging use case.

XMLRPC abandonned the distinction between posts and pages and gives only one endpoint.

WP-API reestablish this distinction. This causes all calls to posts to test the type at the very last moment and redirect calls to /pages or /posts with of course increasing the cost of ownership (more tests, documentation) on both ends.

Almost all the fields are common.

We could argue if the same holds for medias. IMHO in this last case the different of available fields could justify a distinction.

Suggestion: drop /pages endpoint

**Comment by danielbachhuber** [comment]
> API pov it's very much the same object.

Posts and Pages are actually two different entities with two different attributes from the API point of view. You can you compare their schemas here:

* http://v2.wp-api.org/reference/posts/
* http://v2.wp-api.org/reference/pages/

**Comment by BrunoWinck** [comment]
Double checked your links again and I maintain my view. Pages are adding some fields like any post_type would. Since the type can be passed as an argument, other post_type may have extra fields. From programming POV there is little benefit of maintaining two endpoints. It all depends on applications, in my case i'm mostly concerned with title , content, dates and they are all common. If the app is target at implementing a UI front end to WP distinction makes sense, if it is another purpose (content analyze, indexing for example) distinction makes no sense. IMHO the API should be as broard as possible.

**Comment by danielbachhuber** [comment]
> Double checked your links again and I maintain my view.

Ok. You're welcome to your opinion.

**Comment by BrunoWinck** [comment]
Actually the callback for extending the schema exists already: register_api_field
