### ISSUE TITLE
Make endpoints for custom types plural

### ISSUE THREAD

**Issue by oskarrough** [WP-API/WP-API#1648]
Hi, coming from JSONAPI and Ember I'm used to seeing endpoints in plural like `wp-json/v2/projects` but for custom post types the WP-API v2 seems to take a singular name such as as `wp-json/v2/project`.

To make it consistent, shouldn't custom post types use their plural name by default as endpoint?

This way it would follow the same logic as `posts` and `pages`.

**Comment by Toddses** [comment]
You should just register your custom post types using the plural.

**Comment by oskarrough** [comment]
Right, cheers.

**Comment by rmccue** [comment]
If you want the plural in your REST API slug, but not in your post type, you can set `rest_base`:
```php
register_post_type( 'project', array(
    // Your other args here...
    'rest_base' => 'projects',
) );
```

Hope that helps!

**Comment by oskarrough** [comment]
Ah right, even better (for us). Thanks @rmccue.

Where would this fit into the documentation?

**Comment by rmccue** [comment]
Probably something like http://v2.wp-api.org/extending/adding/ - but maybe a new page just for CPTs?
