### ISSUE TITLE
DELETE user

### ISSUE THREAD

**Issue by PyNApo** [WP-API/WP-API#1649]
I'm trying to delete a user.
$http({
	method: 'DELETE',
	url: xxx + 'wp/v2/users/'+ID,
	data: {
		force : false,
		reassign : null,
	}
});

but i'm getting 501 (Not Implemented) error

what's wrong ?

Thanks

**Comment by timnashcouk** [comment]
You need to append ?force=true to the URL, as by default Delete puts the resource into the trash status rather then a hard delete but only posts, CPT and pages have a trash, hence the error.

**Comment by danielbachhuber** [comment]
Related https://github.com/WP-API/docs-v2/issues/24
