### ISSUE TITLE
API path

### ISSUE THREAD

**Issue by kkai316** [WP-API/WP-API#1650]
Hello everyone,
I was trying to get api from specific wp page. However, /wp-json/pages/[my-page-title] doesn't work (return [0]) but /wp-json/posts works fine to retrieve posts. I researched a lot but with no luck...Is it something wrong with my path or setting ?
Thank you so much!

**Comment by joehoyle** [comment]
@kkai316 the path for a single page is referenced by it's ID, such as http://demo.wp-api.org/wp-json/wp/v2/pages/10

**Comment by kkai316** [comment]
Awesome! It really helps.
