### ISSUE TITLE
Using WP as a "true" api

### ISSUE THREAD

**Issue by villeristi** [WP-API/WP-API#1651]
Is there a way to use WordPress headless / themeless and use a TLD www.domain.com root `/`, `/posts`, `/pages`, `/insert-wp-json-endpoint-here` as the endpoints to WP-API?

Maybe some combination like (obviously just a dummy example):

```
add_filter( 'json_url_prefix', function ( $prefix ) {
	return null;
} );

function custom_api() {
	add_rewrite_rule( '$', 'index.php?json_route=/', 'top' );
	add_rewrite_rule( '(.*)?$', 'index.php?json_route=$matches[1]', 'top' );
	flush_rewrite_rules();
}

add_action( 'init', 'custom_api' );
```

**Comment by danielbachhuber** [comment]
There isn't an officially-supported way to customize the path at which the REST API is served at this time.
