### ISSUE TITLE
GET comments without assigned posts

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1652]
Core permits comments without post IDs. The API should permit this too: https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-comments-controller.php#L127

Related https://core.trac.wordpress.org/ticket/34106

**Comment by rachelbaker** [comment]
Core is really inconsistent here: https://core.trac.wordpress.org/ticket/23931

**Comment by danielbachhuber** [comment]
Related #1805

**Comment by danielbachhuber** [comment]
Closing in favor of #1832
