### ISSUE TITLE
How to upload featured image using v2?

### ISSUE THREAD

**Issue by gtamas** [WP-API/WP-API#1653]
Hi

I know I can upload an attachment and then make a PUT /posts/ID request which updates the article and sets its featured_image key to the id of the attachment.

But is this the proper way to do this using v2?

Btw, the API just uploads image attachments, it doesn't resize them, right? So if I need to resize the featured image then I have to add custom endpoint, correct?

**Comment by danielbachhuber** [comment]
> But is this the proper way to do this using v2?

Yes, it's a two-step process:

1. Upload the image with `POST /wp/v2/media`
2. Assign the image as featured with `PUT /wp/v2/posts/<id> featured_image==<image-id>`

> Btw, the API just uploads image attachments, it doesn't resize them, right? So if I need to resize the featured image then I have to add custom endpoint, correct?

The API doesn't do any resizing... but when you create a new image in WordPress, WordPress will resize the image according to any defined image sizes. Custom functionality beyond this will need a custom endpoint (or whatever else you deem necessary).
