### ISSUE TITLE
wp-api.js not enqueued

### ISSUE THREAD

**Issue by acha5066** [WP-API/WP-API#1654]
For some reason wp-api.js never gets enqueued. I have disabled all plugins apart from wp-api but that javascript file is never in the source. WordPress 4.3.1 and WP-API 1.2.3

**Comment by rmccue** [comment]
You need to enqueue it yourself with `wp_enqueue_script( 'wp-api' )` (or have it as a dependency of your script)

The script is only registered for you, but unless you're using it, it won't be output :)
