### ISSUE TITLE
Can't figure out how to filter by post type

### ISSUE THREAD

**Issue by itsravenous** [WP-API/WP-API#1655]
`GET /posts` returns a list of standard posts
`GET /posts?type=warranty`, `GET /posts?post_type=warranty`, `GET /posts?filter[type]`, `GET /posts?filter[post_type]=warranty`,  all return the same list (of standard posts, not warranty posts). I feel like I'm missing something really basic, but can't find anything in the documentation.

I'm using the download from the plugin page, which I believe is the master branch, i.e. beta.

Fresh WP 4.3 install with warranty post type scaffolded via WP-CLI

**Comment by danielbachhuber** [comment]
You'll need to add `show_in_rest=>true` to your post type registration. You can also use `rest_base=warranties` to make your base plural. Once you've done so, your custom post type will be available at `wp-json/wp/v2/warranties`

> I feel like I'm missing something really basic, but can't find anything in the documentation.

The page was just added https://github.com/WP-API/docs-v2/pull/40 :)

> Fresh WP 4.3 install with warranty post type scaffolded via WP-CLI

I'll make sure scaffolding is updated to include the rest registration arguments.

**Comment by itsravenous** [comment]
Oh thanks goodness - I thought I was losing it! Thanks for the lightning response.
