### ISSUE TITLE
Filtering Users 

### ISSUE THREAD

**Issue by timnashcouk** [WP-API/WP-API#1657]
'/wp/v2/users/?filter[per_page]=1' 
Returns the default 10 not 1 result on the page.

Issue appears to be that the per_page is stored inside the filter array so get_param() can't locate it as it's mapping to ['get']['per_page'] as opposed to ['get']['per_page']['filter']

Supplied a simple patch based on the posts work around.

**Comment by danielbachhuber** [comment]
Per discussion on the pull request, the correct query parameter is `per_page`:

```
/wp/v2/users?per_page=1
```

You can specify offset with the `page` parameter. Functionally, you can achieve the same effect as using `number` and `offset`.
