### ISSUE TITLE
Duplicate Meta When Creating a New Post

### ISSUE THREAD

**Issue by koarng** [WP-API/WP-API#1658]
When creating a new post with post meta, it always create 2 times(duplicated) of the meta.

**Comment by danielbachhuber** [comment]
@koarng Can you share the request you're making? Which version of the API are you using?

**Comment by koarng** [comment]
API Version 1.2.3. 
Request:
{"title":"Test Post 1","content_raw":"Content","excerpt_raw":"Excerpt","post_meta":[{"key":"Test","value":"test"}]}

Response:
{
    "ID": 612,
    "title": "Test Post 1",
   "post_meta": [
        {
            "ID": 1170,
            "key": "Test",
            "value": "test"
        },
        {
            "ID": 1171,
            "key": "Test",
            "value": "test"
        }
    ],
......
}

**Comment by rachelbaker** [comment]
Fixed in #1031
