### ISSUE TITLE
WP REST API (WP API) : using latest wp version

### ISSUE THREAD

**Issue by krishnenduvp** [WP-API/WP-API#1672]
The API url http://pay4mb.com/sample4/wp-json/posts still returns incorrect json string :(.

The response string must always be a JSON object, not a JSON array. It must start with a "{" and end with "}".

how can I correct this ??

https://wordpress.org/plugins/json-rest-api/

**Comment by danielbachhuber** [comment]
> The response string must always be a JSON object, not a JSON array. It must start with a "{" and end with "}".

In WP-API v1.x, the response format for a collection is a JSON array, not a JSON object. I'm not sure why you're saying it _must_ be an object.

In WP-API v2.x, we will likely change the response for collections to a JSON object. See #1196

> how can I correct this ??

You'd need to hijack the response at the `json_serve_request` filter, and wrap the array with an object: https://github.com/WP-API/WP-API/blob/master/lib/class-wp-json-server.php#L279
