### ISSUE TITLE
Unable to authenticate with nonce

### ISSUE THREAD

**Issue by JasonTheAdams** [WP-API/WP-API#1674]
I'm attempting to do the following:

```
sendNonce: function(xhr) {
  xhr.setRequestHeader( 'X-WP-Nonce', WP_API_Settings.nonce );
},

retrievePosts: function() {
  $.ajax({
    url: WP_API_Settings.root + 'wp/v2/posts/35',
    method: 'GET',
    beforeSend: this.sendNonce,
    dataType: 'json',
    success: this.postsReceived,
  });
},

postsReceived: function(data) {
  console.log(data);
}
```

I initially tried without the _wp_rest_nonce, but no matter what I do I continue to get a 403 forbidden in response. Am I missing something?

**Comment by danielbachhuber** [comment]
Which WordPress version are you using?

**Comment by JasonTheAdams** [comment]
Thanks for the quick reply! I'm on 4.3.1, using the 2.0 beta4.

**Comment by Toddses** [comment]
For the record, I wouldn't send the nonce twice. Not sure which method is better, per se, the header or the parameter... personally I prefer in the header, but that's not based on any sort of logic other than a preference in the code.

Also, you shouldn't need the nonce for a GET request. Unless your site is set up to specifically require a nonce for all requests, GET requests don't require authentication.

Are there any other error messages in the response? Usually `WP-API` sends an error message back along with that 403 status. Digging into that response message may help track down the issue.

**Comment by JasonTheAdams** [comment]
@Toddses: Thanks! Please ignore the data property, I only added that once the header form wasn't working.

I get the feeling I'm doing something incorrectly. I want to query some posts on the front-end of the site without the need to be logged in. Aside from installing and activating the plugin, I haven't changed a thing. I've normally just made my own api endpoints, but wanted to try using WP-API since it will ultimately be in core.

Also, aside from the call stack, I'm not getting any error messages. I adjusted the code above to reflect all I'm doing.

**Comment by eliorivero** [comment]
@JasonTheAdams 

<blockquote>
I'm on 4.3.1, using the 2.0 beta4.
</blockquote>

for proper testing your setup should be

Latest build of WP 4.4
https://wordpress.org/nightly-builds/wordpress-latest.zip

Latest REST API in development
https://github.com/WP-API/WP-API/archive/develop.zip

The following (a reduced version of the code you initially posted) works for me when I enter it in Dev Tools console:
```js
jQuery.ajax({
    url: WP_API_Settings.root + 'wp/v2/posts/1',
    method: 'GET',
    beforeSend: function(xhr) {
        xhr.setRequestHeader( 'X-WP-Nonce', WP_API_Settings.nonce );
    },
    dataType: 'json',
    success: function(data) {
      console.log(data);
    }
});
```
so maybe the issue is somewhere else in your code.

Remember you can always use the Backbone JS client which is described here https://github.com/WP-API/client-js

**Comment by JasonTheAdams** [comment]
Hi @eliorivero 

Unfortunately that means I really shouldn't be using this, as I was hoping the beta was stable enough for production (a gamble, of course, but not uncommon with a v2). I did try pulling the dev branch of the WP API, but when I use the jQuery.ajax method I get `GET http://oaklawn.dev/wp-json/wp/v2/posts/25 404 (Not Found)`, and when I do use the client-js I get the following:
```
var post = new wp.api.models.Post({ID: 25});
undefined
post.fetch();
Object {readyState: 1}
jquery.js:5 GET http://oaklawn.dev/wp-json//posts 404 (Not Found)
```

I did not test that on the WP nightly build, however, so it's possible there's dependencies there. But if that's what's required to get this working, it's apparently not at the point I was hoping it was. Not to say I'm not excited for when this gets introduced to core!

**Comment by Toddses** [comment]
Well, I'm a risk taker and we're currently using WP-API for a production app. I am having no problems with GET requests. I built a prototype using jQuery ajax as you do here. The production app is using angular. Both versions work as expected, and we are using the stable branches of both WP and WP-API.

That said, I feel like there's another issue here that isn't related to the API. As you say, the project is still in beta, so there's always an inherent risk there. But my experience shows its stable enough to handle a production app. The thing that confuses me here is that whenever the API rejects a request, I **always** got back an error message in the response with more information on the rejection. So I guess I'm saying if you'd like to continue down the WP-API path, I'd start by doing sanity checks that everything is set up properly, and verifying that WP itself is having no issues grabbing posts.

**Comment by eliorivero** [comment]
@JasonTheAdams note that this
`
http://oaklawn.dev/wp-json//posts
`
is missing the base, it should be
`
http://oaklawn.dev/wp-json/wp/v2/posts
`
I think it is stable for production. It's rapidly evolving now, so to keep up with changes you probably want to work with the very latest releases. And like Toddses, I've also used it successfully on production.

Do you receive something when you paste
`
http://oaklawn.dev/wp-json/wp/v2/posts/25
`
in the browser address bar and access it directly? You should keep Dev Tools open and inspect the request and its response in the Network tab. Maybe that will help you figuring out where the issue in your installation is.

**Comment by JasonTheAdams** [comment]
Thanks for the input! Glad to hear you're going for it, that is encouraging. I think I need to setup a barebones environment -- no plugins and default theme -- and test this out. Once I test that out, I'll see if I'm still having issues. I have the feeling I have a conflict somewhere, and I need to work my way up to it.

Thanks, guys!
