### ISSUE TITLE
Attempt to create a new comment as the current user seems always create an anonymous one.

### ISSUE THREAD

**Issue by southp** [WP-API/WP-API#1676]
## Environment
WordPress: 4.3.1
WP REST API: 2.0-beta 4
Machine: Chassis with VirtualBox 4.3.28 as its VM backend

## How to
According to the test [test_create_item_current_user](https://github.com/WP-API/WP-API/blob/develop/tests/test-rest-comments-controller.php#L406), it seems that the minimum data one need to provide are `post` and `content`, the rest are filled automatically according to the current user.

I built a simple plugin to demonstrate my issue here: [simple-submit](https://github.com/southp/simple-submit).

Install and active the plugin, log in as any registered user. Open a post of your WordPress site, and you should see something like:
![2015-10-22 2 03 29](https://cloud.githubusercontent.com/assets/1842898/10658052/babffd3a-78c5-11e5-8fc8-52ab83035bd2.png)

Press the button 'GO!' will simply do `POST /wp/v2/comments` with the json data showed.

After pressing:
![2015-10-22 2 05 42](https://cloud.githubusercontent.com/assets/1842898/10658087/074c6116-78c6-11e5-8796-7bd1ae0af475.png)
In my case, even if I did the POST as a logged-in user, the comment created is an anonymous one( `author: 0` ).

I am not sure if this is a bug or I misunderstood how the endpoint work.

**Comment by rmccue** [comment]
This is already fixed in the upcoming beta 5: #1580 :)
