### ISSUE TITLE
WP API validate_callback issue

### ISSUE THREAD

**Issue by laviniadan** [WP-API/WP-API#1677]
Hello,

I've currently started using WP API in a project.
I'm currently using `2.0-beta4`
I've started by creating a custom endpoint, put it in a separate plugin. 
As I was working on this I've noticed that if for a numeric argument I pass a string I get a `rest_no_route` code instead of an invalid parameter message. 
I've looked in the documentation to see if I can customize this ass well and then I've noticed that validation callbacks should be available, so I tried to use 
```
'args' => array(
            'id' => array(
                'validate_callback' => 'is_numeric'
            ),
 )
```
but for some reason this does not work.
In order to make sure it was not because of my custom endpoint, I've added this validation callback in WP_REST_Posts_Controller and it still displayed the same `rest_no_route` error code. Now I may be doing something wrong, but I'm not sure what. 
I would appreciate if you could help me solve this problem, or point me in the right direction.

my plugin.php
```
/*
Plugin Name: Test API EndPoint
Description: Adds API endpoints for Quiz History
Depends: WP REST API, Plugin Dependencies
Version: 0.1
*/
include_once dirname( __FILE__ ) . '/endpoints/class-wp-quiz-history-api-endpoint-controller.php';

function quiz_history_init() {
    global $quiz_history;
    $quiz_history = new WP_REST_Quiz_History_API_Endpoint_Controller();
    $quiz_history->register_routes();
}

add_action('rest_api_init', 'quiz_history_init');
```

class-wp-quiz-history-api-endpoint-controller.php
```
class WP_REST_Quiz_History_API_Endpoint_Controller extends WP_REST_Controller 
{

    private $uploadDir;
    private $version        = 1;
    private $namespace = 'test/v';
    private $base            = 'quiz-history';

    public function __construct()
    {
        $this->namespace = $this->namespace . $this->version;
        $this->base;
    }

    public function register_routes() {
        register_rest_route( $this->namespace, '/' . $this->base . '/user/(?P<id>[\d]+)', array(
            array(
                'methods'  => WP_REST_Server::READABLE,
                'callback' => array( $this, 'get_quiz_history' ),
                'args'     => array(
                    'id' => array(
                        'validate_callback' => 'is_numeric'
                    )
                )
            )
        ));
    }

     **
     * @param WP_REST_Request $request
     * @return null|WP_Error|WP_REST_Response
     */
    public function get_quiz_history( $request ) {
       //get quiz history implementation
       //I've removed the actual implementation for this example
    }

}
```

this is the response I get if I pass a string instead of an integer in the API call
```
[
  {
    "code": "rest_no_route",
    "message": "No route was found matching the URL and request method",
    "data": {
      "status": 404
    }
  }
]
```
I would rather have something like
```
[
  {
    "code": "rest_invalid_argument",
    "message": "Invalid argument. Expected <argument type>",
    "data": {
      "status": 404
    }
  }
]
```
Thank you!

**Comment by eliorivero** [comment]
Hi, I had to modify your code a bit since there's a missing slash before that block comment, the class WP_REST_Controller isn't found at the time you're extending it, and the is_numeric admits only one parameter but 3 when it's called from call-wp-rest-request.php are sent so it throws a warning.
The main plugin file:
```php
<?php
/*
Plugin Name: Test API EndPoint
Description: Adds API endpoints for Quiz History
Depends: WP REST API, Plugin Dependencies
Version: 0.1
*/

function quiz_history_init() {
	global $quiz_history;
	require_once 'wp-rest-quiz-history-controller.php';
	$quiz_history = new WP_REST_Quiz_History_API_Endpoint_Controller();
	$quiz_history->register_routes();
}

add_action('rest_api_init', 'quiz_history_init');
```
The wp-rest-quiz-history-controller.php file:
```php
<?php

class WP_REST_Quiz_History_API_Endpoint_Controller extends WP_REST_Controller {

	private $uploadDir;
	private $version = 1;
	private $namespace = 'test/v';
	private $base = 'quiz-history';

	public function __construct() {
		$this->namespace = $this->namespace . $this->version;
		$this->base;
	}

	public function register_routes() {
		register_rest_route(
			$this->namespace, '/' . $this->base . '/user/(?P<id>[\d]+)', array(
			array(
				'methods'  => WP_REST_Server::READABLE,
				'callback' => array( $this, 'get_quiz_history' ),
				'args'     => array(
					'id' => array(
						'validate_callback' => array( $this, 'validate_numeric' )
					)
				)
			)
		)
		);
	}

	/**
	 * @param WP_REST_Request $request
	 *
	 * @return null|WP_Error|WP_REST_Response
	 */
	public function get_quiz_history( $request ) {
		return $request;
		//get quiz history implementation
		//I've removed the actual implementation for this example
	}

	/**
	 * Checks that value is numeric.
	 *
	 * @param $param
	 *
	 * @return bool
	 */
	public function validate_numeric( $param ) {
		return is_numeric( $param );
	}

}
```

So now the issue is the error message. Since it's defined as `/user/(?P<id>[\d]+)`, expecting a number at the end, if a string comes in, like
`
wp-json/test/v1/quiz-history/user/hello
`
it doesn't match the route, so the REST server looks for another, thus throwing that `rest_no_route` error.

If you want to expect an a to z lowercase string at the end and manage the validation yourself, rewrite
```php
/user/(?P<id>[\d]+)
````
to
```php
/user/(?P<id>[a-z\d]+)
```
The request `wp-json/test/v1/quiz-history/user/hello` now throws
```json
[{"code":"rest_invalid_param","message":"Invalid parameter(s): Invalid param.","data":{"status":400,"params":{"id":"Invalid param."}}}]
```
as you wanted.

**Comment by laviniadan** [comment]
Thank you very much!
As a side note, I had no problem with extending the WP_REST_Controller, it worked as expected for a successful request. I only wanted to get it to throw an invalid parameter request. 
The solution was very simple from your example, simply adjusting the regex expression. 
Thank you again!
