### ISSUE TITLE
Update post slug?

### ISSUE THREAD

**Issue by beatelite** [WP-API/WP-API#1678]
Hi, 

I have been trying to figure out a way to update the post slug from the api but I'm not having much luck and can't find anything online about it. Is there anything special I have to do?

I can update post title, excerpt & content just fine.

**Comment by danielbachhuber** [comment]
Can you share the request you're making, and its response?

**Comment by beatelite** [comment]
I think you mean this: 

Request URL:http://site.dev/wp-json/wp/v2/posts/243
Request Method:PUT
Status Code:200 OK

The weird thing is, when I go to payload, I don't show the slug in the object passed. it's like I can pass everything but the slug.

**Comment by beatelite** [comment]
I figured this out. I am using angular and was not using $scope in my call to my CRUD factory for the api. updated it to $scope.post.slug and all is right with the world. Thanks a mill for creating this API

**Comment by danielbachhuber** [comment]
Glad you figured it out!
