### ISSUE TITLE
PUT to post status?

### ISSUE THREAD

**Issue by beatelite** [WP-API/WP-API#1680]
I have an authenticated user that's creating a post and I want to list out the post status to choose from in an html selector. I see I'm not getting anything back in the json object that says "status" but the docs say I can retrieve them. 
http://wp-api.org/misc/comparison.html#post-related-data

Is this possible and if so, how?

**Comment by eliorivero** [comment]
Hi @beatelite try using this:

```php
// Include post status when requesting a post.
add_action( 'rest_api_init', 'wp_json_wp_v2_register_post_status_field' );

/**
 * Registers the post_status field for post returned in response.
 */
function wp_json_wp_v2_register_post_status_field() {
	register_api_field( 'post',
		'post_status',
		array(
			'get_callback'    => 'wp_json_wp_v2_get_post_status',
			'update_callback' => null,
			'schema'          => null,
		)
	);
}

/**
 * Get post status of post in response currently being served.
 *
 * @param array $object Response with post data as defined in schema in WP_REST_Posts_Controller.
 * @param string $field_name Name of field to add to response.
 * @param WP_REST_Request $request Current request.
 *
 * @return mixed
 */
function wp_json_wp_v2_get_post_status( $object, $field_name, $request ) {
	$post = get_post( $object[ 'id' ] );
	return $post->post_status;
}
```

Also, the link to current documentation is http://v2.wp-api.org/

**Comment by danielbachhuber** [comment]
Here is the (incomplete) documentation for getting post statuses: http://v2.wp-api.org/reference/statuses/

You can `GET domain.com/wp-json/wp/v2/statuses` to get all statuses, but the request will need to be authenticated to retrieve private statuses.

**Comment by beatelite** [comment]
Thanks Daniel, However, what if I want to retrieve the status of a specific post and PUT back to it with a change?

The link above looks to retrieve a list of status used across the site.

**Comment by beatelite** [comment]
BTW, the code above didn't work for me.

**Comment by danielbachhuber** [comment]
> Thanks Daniel, However, what if I want to retrieve the status of a specific post and PUT back to it with a change?

Retrieving the status of unpublished content requires authorization to view that post, and making a `PUT` request on the resource requires authorization to update the resource.

**Comment by beatelite** [comment]
OK, that makes sense to me. I am in fact authenticated when making a PUT to any post, for example, updating the title. However, what I'm trying to understand is how I change the status of a post from, let's say, "publish" to "draft".

How does it work? It doesn't seem to have the status listed anywhere in the object when I GET mydomain.com/wp-json/wp/v2/posts/143

143 being the post that i'm working on. 

So, forgive me if I'm being dense, but how do I alter the status of a post using the api? If I want to change the status from draft to publish, how do I go about doing that, specifically?

The docs don't really have much on this, that i've seen. Any help is appreciated.

**Comment by brianhogg** [comment]
@beatelite: you need to add "context=edit" in order to retrieve the status in the GET request return value, in addition to being authenticated for the request.  I did a demo of fetching and updating the post status + title at WordCamp Ann Arbor last weekend here:

https://github.com/brianhogg/wp-backbone-view-rest-api-demo

Just do an authenticated GET request to:

/wp-json/wp/v2/posts/143?context=edit

and you'll get the status value.  PUT it back with the "status" value included and you're all set.

I didn't see it in the documentation anywhere, heard about it from the friendly people in the #core-restapi slack channel :)

**Comment by beatelite** [comment]
Wow, Brian! Thank you so much for chipping in with the answer. I'm going to give this a shot tomorrow and see what happens. Again, super helpful of you to chime in.

**Comment by beatelite** [comment]
Ok, i'm using that as a logged in administrator and keep getting: 

[{"code":"rest_forbidden_context","message":"Sorry, you are not allowed to edit this post","data":{"status":403}}]

I'm logged in so I'm authenticated. Any idea why?

**Comment by brianhogg** [comment]
You also need to pass in the X-WP-Nonce header as described here:

http://v2.wp-api.org/guide/authentication/

The plugin I linked to above also shows a way to do this.

**Comment by beatelite** [comment]
Awesome, thanks Brian. I was trying to just access the url while logged in. Forgot about the nonce. 

For anyone else using angular, using $resource as a dependency to however you are setting up your REST api factory/ service just pass in the param like so:

	    	'get':{
				method:'GET',
				headers: {
					'X-WP-Nonce': ajaxInfo.nonce
				},
				params: {
				    context: 'edit'
				},
				isArray: false
			},

https://docs.angularjs.org/api/ngResource/service/$resource
