### ISSUE TITLE
Fatal error: Call to undefined function get_page_templates()

### ISSUE THREAD

**Issue by bigandy** [WP-API/WP-API#1681]
Getting this error message when I go to /wp-json: 

WordPress 4.4-beta-1 and latest plugin, both from Github.

Fatal error: Call to undefined function get_page_templates() in <siteurl>/content/plugins/wp-api/lib/endpoints/class-wp-rest-posts-controller.php on line 1532

**Comment by Toddses** [comment]
Are you just hitting `wp-json/` directly or is this a code issue? 

That actually is probably not a valid endpoint. Try hitting `site.url/wp-json/wp/v2/posts`.

**Comment by eliorivero** [comment]
@bigandy this is a currently known issue. See
https://wordpress.slack.com/archives/core-restapi/p1445543436000517

and https://github.com/WP-API/WP-API/pull/1679

If you're just testing, for the time being you can probably do as this PR
https://github.com/WP-API/WP-API/pull/1679/files

**Comment by danielbachhuber** [comment]
@joehoyle maybe we should just load all of the admin files to solve this problem for beta5. Given the plugin has been loading all of the admin files already, I think it's an acceptable short-term fix

**Comment by bigandy** [comment]
@eliorivero yes I did see it on slack after I posted the bug. I'll wait until they merge the PR as I am using this plugin as a git submodule.

**Comment by rachelbaker** [comment]
Confirming a fix is being worked on in #1679 and will be included in our version 2.0 beta-5 release.

**Comment by danielbachhuber** [comment]
This was fixed by #1682
