### ISSUE TITLE
Basic_Auth does not work  with wp-api 

### ISSUE THREAD

**Issue by leizhiyuan** [WP-API/WP-API#1688]
wordpress version: WordPress 4.3.1
wp-api version:2.0-beta5
WP BASIC Auth version:1.1.3

I can visit http://mysite/wp-json/wp/v2/posts/ to see all post json data.

but when I want to create a new post use basic auth and postman,I add Authorization,and request header is ok.

```
[
  {
    "code": "rest_forbidden",
    "message": "You don't have permission to do this.",
    "data": {
      "status": 403
    }
  }
]
```

also, I use curl 
```
curl --user user:pass  -H "Content-Type: application/json" -sd '{"title":"Hello World!","content_raw":"Content","excerpt_raw":"Excerpt"}' http://mysite/wp-json/wp/v2/posts/
```

I get this error
```
[{"code":"rest_forbidden","message":"You don't have permission to do this.","data":{"status":403}}]
```

**Comment by danielbachhuber** [comment]
You'll want to use this basic auth plugin to properly authenticate: https://github.com/WP-API/Basic-Auth

[WP BASIC Auth](https://wordpress.org/plugins/wp-basic-auth/) is only tested up to WP 4.1.8, and likely doesn't work with REST API

**Comment by leizhiyuan** [comment]
thanks, @danielbachhuber

**Comment by younes0** [comment]
So, if OAuth doesn't work either with Rest API 2.0, we do need to downgrade to 1.2.3, problem is: I can't install this specific version through Composer
