### ISSUE TITLE
Retrieve wordpress private pages

### ISSUE THREAD

**Issue by kkai316** [WP-API/WP-API#1691]
Can anyone give me a direction if there is a way to retrieve wordpress private pages?
Thank you

**Comment by danielbachhuber** [comment]
You'll need to make an authenticated request to:

```
GET /wp-json/wp/v2/pages?status=private
```

**Comment by kkai316** [comment]
Thanks your fast reply! I have one more question... You mentioned "authenticated request", does that mean I need to go through Oauth Authentication to get the ID, key and secret? I tried the api you provide then I got only public pages json return.

**Comment by danielbachhuber** [comment]
> does that mean I need to go through Oauth Authentication to get the ID, key and secret?

Yes, you'll need to use some form of authentication.
