### ISSUE TITLE
Endpoint for creating multiple comments

### ISSUE THREAD

**Issue by gtamas** [WP-API/WP-API#1692]
Does the /comments accept POST requests? Can I create multiple comments by posting an an array of comment data to this endpoint?

If this only serves GETs, is there a way to create multiple comments using V2 API?

**Comment by joehoyle** [comment]
@gtamas there's no way to create multiple comments in a single HTTP request, though I'm not sure of the use case for that! `/comments` does accept POST requests, but only for creating a single comment.
