### ISSUE TITLE
OAuth Authentication

### ISSUE THREAD

**Issue by kkai316** [WP-API/WP-API#1693]
Hi everyone,
I am stuck at working on making wp pages content authentication api for few days... Can anyone point me a direction what is the next steps after creating the consumer? Or a reference url/keywords I can research?
Thank you so much

**Comment by danielbachhuber** [comment]
@kkai316 Did you see [this documentation](https://github.com/WP-API/OAuth1/blob/master/docs/spec.md) ?

**Comment by kosso** [comment]
Here's a test script I put together quite some time ago.  vmmv. 

https://github.com/kosso/OAuth1/blob/master/php_test/wp_oauth_test_auth_flow.php

**Comment by jpopesculian** [comment]
Does v2 this support oauth2? I tried attaching `access_token` as a get parameter but it didn't work

**Comment by radenui** [comment]
Same thing for me: I couldn't access the api with access_token as a get parameter

**Comment by kosso** [comment]
OAuth2 is not supported, since it requires https. 

See here for the reasoning : https://github.com/WP-API/OAuth1/issues/2
