### ISSUE TITLE
Can't get posts via taxonomy term

### ISSUE THREAD

**Issue by donaldallen** [WP-API/WP-API#1704]
I've tried:

```
/wp-json/wp/v2/properties?filter[taxonomy]=property_type&filter[term]=industrial
```

```
/wp-json/wp/v2/properties?property_type=industrial
```

No dice. What might I be doing wrong?

**Comment by danielbachhuber** [comment]
What response do you get?

**Comment by danielbachhuber** [comment]
`WP_Query` requires the taxonomy to be registered post type, I believe: https://core.trac.wordpress.org/browser/trunk/src/wp-includes/query.php#L2820

**Comment by donaldallen** [comment]
The response I get back is:

```
[{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}]
```

Is this not possible to get all posts via a taxonomy term?

**Comment by donaldallen** [comment]
Perhaps if I create my own endpoint I can work around this issue. I'll give that a go.

**Comment by shprink** [comment]
@donaldallen you need to enable the taxo to be listed by the api first: https://gist.github.com/scottopolis/997b86d8afa7825bc942 

I have activated it and I can now list and filter by `post_format` which is a custom taxo

wp-json/wp/v2/terms/post_format
wp-json/wp/v2/posts?filter%5Bpost_format%5D=post-format-gallery

**Comment by donaldallen** [comment]
@shprink I already have 'show_in_rest' set to true when I register my taxonomy. Thanks though!

**Comment by devlesedi** [comment]
Set *show_in_rest* to true as one of the args to *register_post_type* when registering your custom post type 'properties'. Do the same for your taxonomy.
