### ISSUE TITLE
Consistently show the `context` param as an endpoint argument for GET requests

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#1706]
In `WP_REST_Controller->get_collection_params()` we define the top-level collection params:
 * `page`
 * `per_page`
 * `search`

We should add to that the `context` param as well, so we have it consistently in the collection params.  

Additionally, I don't think we define the params for our single item endpoints.  We should communicate the context param there as well.

**Comment by danielbachhuber** [comment]
Bumping to Beta 7. This bug isn't a regression, so it doesn't need to be addressed before we land Beta 6.
