### ISSUE TITLE
Cannot PUT a new Post

### ISSUE THREAD

**Issue by Mange** [WP-API/WP-API#1716]
From reading the documentation, it would appear like it's possible to PUT posts using `PUT /wp-json/wp/v2/posts/5`, but it'll respond with "Post ID is invalid" in case a post with that ID does not exist.

The code is clear: `PUT`, `PATCH` and `POST` are all calling `update_post`, which always look for an existing post.

This is the wrong application of the `PUT` verb from how I understand them.

* `POST` (add/create) – Create a resource and return where it was created. Think auto-incremented IDs. Repeating this will create more resources.
* `PATCH` (update) – Change something about a resource.
* `PUT` (replace) – Put a full resource at a specific URI. If it already existed, replace with the body, otherwise create it.

Is it your intention to have some way to create articles on a given ID, and allow API users to replace them?

---

**Request:**
```
PUT /wp-json/wp/v2/posts/4567
Content-Type: application/json; charset=utf-8

{"title":"A replaced post","status":"published"}
```

**Response:**
```
[{"code":"rest_post_invalid_id","message":"Post ID is invalid.","data":{"status":400}}]
```

**Comment by WraithKenny** [comment]
The use of `PUT` to a specific ID that doesn't exist is to either respond with an error or  *optionally* treat as a `POST` with the requested ID... It's not really "wrong" to pick the option with the error... And for WordPress that's the best, most correct choice.

WordPress itself doesn't really have APIs for inserting entries with new specific IDs (except in doing imports, and that's only a "suggestion" and shouldn't be used here), so I'd think that the REST version certainly would not either. See https://codex.wordpress.org/Function_Reference/wp_insert_post

Essentially, trying to update (`PUT`) a non existing resource should error here. You should `POST` to create (but ignore the ID field).

**Comment by danielbachhuber** [comment]
> WordPress itself doesn't really have APIs for inserting entries with new specific IDs (except in doing imports, and that's only a "suggestion" and shouldn't be used here), so I'd think that the REST version certainly would not either.

This is correct.

If being able to insert posts with arbitrary IDs is functionality you need in your custom application of WordPress, you'd be best off writing your own endpoint. However, be aware the `ID` column in the posts table is auto-increment, so there's the chance the ID you're supplying will conflict with an existing record.

**Comment by Mange** [comment]
Thanks. I'll look into alternatives, then.
