### ISSUE TITLE
does it work with woocommerce

### ISSUE THREAD

**Issue by longxianlin** [WP-API/WP-API#1717]
can work for woocommerce?
then can provide data to ios app or android app

**Comment by danielbachhuber** [comment]
WooCommerce will need to produce its own endpoints to be compatible with WP-API.

**Comment by longxianlin** [comment]
it mean   can't get data from WooCommerce right now

**Comment by danielbachhuber** [comment]
> it mean can't get data from WooCommerce right now

Correct

**Comment by longxianlin** [comment]
http://woothemes.github.io/woocommerce-rest-api-docs/

just google it, find this.

**Comment by JulienMelissas** [comment]
^ as far as I know Woo's API doesn't not use the WP-API, at least not yet. But yeah, they provide their own JSON API and have since 2.1
