### ISSUE TITLE
Retrieve tags for posts under a category

### ISSUE THREAD

**Issue by arikogan** [WP-API/WP-API#1718]
Hi guys,
I'm posting here as I haven't been able to find information on this anywhere else.
I'm trying to retrieve the tags that have been used for the posts under a certain category. For instance, if there is a category "Education" and some posts have been written under it and tagged with "high-school", "university" and "kindergarten", I would like to make a call to the API and ask for the tags used for the posts under the Education category.
I thought of doing something like the below,
`http:///wp.server.com/wp-json/wp/v2/posts?filter[category_name]=education&_embed`
and somehow do field expansion only on nodes that satisfy `taxonomy: "post_tag"`.
I don't really know if this is possible and I'd very much appreciate any ideas.
Thanks,
Ariel

**Comment by danielbachhuber** [comment]
> I thought of doing something like the below,

What do you get when you make that request? When I reproduce the request locally, I get all posts with category slug `education` and all embeddable nodes expanded.

**Comment by arikogan** [comment]
Yes, that's right @danielbachhuber 
My approach is pretty brute force: Browsing through all posts and retrieving the tags I find in order to build the final list. It's quite rudimentary so I was hoping there is a better way to do it.
Thanks!

**Comment by danielbachhuber** [comment]
> It's quite rudimentary so I was hoping there is a better way to do it.

None that I can think of, unfortunately, other than writing a custom endpoint to execute this logic under the hood.

**Comment by arikogan** [comment]
Thanks @danielbachhuber, will give that a try.
