### ISSUE TITLE
Category and featured image not available in /posts

### ISSUE THREAD

**Issue by enjikaka** [WP-API/WP-API#1719]
Category and feature images should be defined in /posts to avoid 2 extra request for this crucial data.

**Comment by swissspidy** [comment]
I don't think that makes sense _by default_. What should this include? The URL (which image size?)? The name?.

Here's a snippet how you can include this: https://gist.github.com/scottopolis/04c48e46e5f36930a626

**Comment by danielbachhuber** [comment]
`?_embed` will also embed the featured image in 2.x.

**Comment by enjikaka** [comment]
I think it does make sense. Making extra requests for necessary data is evil agains mobile users. 

If you want to display a feed of posts, you're going to use /posts, and you are going to want to display the posts category and the featured image in the feed.

I encountered this need here: http://codepen.io/enjikaka/pen/ojpqMG/left
