### ISSUE TITLE
WordPress login.

### ISSUE THREAD

**Issue by pkhutal** [WP-API/WP-API#1720]
Hello,
      I am Developing Android Application For WordPress Website.I want to login to WordPress Website From Mobile Application Using WebView i.e I call URL in WebView and it login to website and website is Opened.Basically its Open Website for Specific Login Credential.I have been searching for this but didn't got an any solution also using rest API i can get JSON data  but how can i open Website. Please guide me for same.
Thank you.

**Comment by rmccue** [comment]
I'm sorry, I don't understand what you're asking for?

**Comment by pkhutal** [comment]
I Want Open and Login  wordPress Website From Mobile.

**Comment by pkhutal** [comment]
How can I open wordPress Website and Login into it from Mobile Application
using webView

**Comment by AstonBraham** [comment]
Just load http:// <YOUR WEBSITE URL> /wp-login.php in your webview as a normal website
AFAIK, this API is for REST purposes

**Comment by pkhutal** [comment]
ok....thank you :)
