### ISSUE TITLE
cant get v2 to work

### ISSUE THREAD

**Issue by glenfordwilliams** [WP-API/WP-API#1724]
hi i have v2 beta5 installed on my dev server and for some strange reason i cant seem to get it work 
http://www.dev.stlucianewsonline.com/wp-json/wp/v2
reroutes to the main site .

i previously had v1 installed which i removed in my attempts to get this to work . any help would be appreciated

**Comment by Shelob9** [comment]
@glenfordwilliams Did you install from WordPress.org or from the Git repo? If you installed via Git, you must checkout the submodule.

If you have the submodule, which is bundled when you install from WordPress.org, try flushing permalinks.

BTW http://www.dev.stlucianewsonline.com/wp-json works just fine, but none of the default routes are there...

**Comment by glenfordwilliams** [comment]
i installed from the wordpress site. gonna try installing from the git repo

**Comment by danielbachhuber** [comment]
> question what could cause the default routes not to be there?

Did you flush your rewrite rules after you activated the plugin?

**Comment by glenfordwilliams** [comment]
Not sure how to do that

**Comment by danielbachhuber** [comment]
Here's some documentation I googled: https://typerocket.com/flushing-permalinks-in-wordpress/

**Comment by glenfordwilliams** [comment]
did that but now im getting [{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}]

**Comment by ryanbeymer** [comment]
@danielbachhuber worked for me, I was getting a 404 until I did that.

**Comment by danielbachhuber** [comment]
> did that but now im getting [{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}]

It's hard to know where you're getting that error when you don't share the request you made.

The API on your site works as expected for me:

```
local ➜  ~  http GET http://www.dev.stlucianewsonline.com/wp-json/wp/v2/posts per_page==5 | jq -r '.[] | [.title.rendered]'
[
  "Trouya Beach Hotel Development Project rejected"
]
[
  "Gov’t provides support for alleged human trafficking victims"
]
[
  "zarif"
]
[
  "test press"
]
[
  "wai"
]
[
  "Police Shooting in Castries"
]
[
  "UPDATED: Prince granted bail"
]
```

**Comment by glenfordwilliams** [comment]
@danielbachhuber  thanks for the help.
apparently i was only using http://www.dev.stlucianewsonline.com/wp-json/wp/v2 to test if it was working
