### ISSUE TITLE
how to retrieve the email of the user registered via api json on an android app?

### ISSUE THREAD

**Issue by zouaghimariem** [WP-API/WP-API#1725]
I developped an android app and used the json api and everything is ok. But after the registration I don't find the information of the new user in the database and in the website.
how to retrieve the email of the user registered via api json on an android application?

https://wordpress.org/plugins/json-rest-api/

**Comment by danielbachhuber** [comment]
> But after the registration I don't find the information of the new user in the database and in the website.

Can you share the request you're trying to make?

> how to retrieve the email of the user registered via api json on an android application?

If the user you're authenticated with has the `list_users` capability, then you can use this request to list all users:

```
GET /wp-json/wp/v2/users
```

You won't be able to retrieve the user's email address with an authenticated request.

**Comment by zouaghimariem** [comment]
No, I said that everything is ok. I can signup and login from the app. But the problem that I don't find that a new user is created on my website or in the database.

**Comment by danielbachhuber** [comment]
> But the problem that I don't find that a new user is created on my website or in the database.

Ok. This problem is outside the scope of what we support.
