### ISSUE TITLE
filter[paged] on /posts endpoint seems got override

### ISSUE THREAD

**Issue by abdusfauzi** [WP-API/WP-API#1731]
After testing to paginate my `/posts` request, `filter[paged]` with `filter[posts_per_page]` seems not working even though I put any number.

after digging around the source code, it seems `paged` has been assigned **after** we assign request filters, thus resulting to `$query['paged']=1` on line https://github.com/WP-API/WP-API/blob/1.2.4/lib/class-wp-json-posts.php#L162.

Perhaps, changing from this:

```
// Validate post types and permissions
$query['post_type'] = array();

...
...

foreach ( $valid_vars as $var => $index ) {
	if ( isset( $filter[ $var ] ) ) {
		$query[ $var ] = apply_filters( 'json_query_var-' . $var, $filter[ $var ] );
	}
}

// Special parameter handling
$query['paged'] = absint( $page );

...
```

.. to this?

```
// Validate post types and permissions
$query['post_type'] = array();

// Special parameter handling
$query['paged'] = absint( $page );

...
...

foreach ( $valid_vars as $var => $index ) {
	if ( isset( $filter[ $var ] ) ) {
		$query[ $var ] = apply_filters( 'json_query_var-' . $var, $filter[ $var ] );
	}
}

...
```

**Comment by danielbachhuber** [comment]
Hi @abdusfauzi,

v1.x of the plugin is no longer supported, except for critical bug fixes. We'd encourage you to start working with v2.0-beta5.
