### ISSUE TITLE
Can't Modify Responses For terms

### ISSUE THREAD

**Issue by wiloke** [WP-API/WP-API#1732]
Hi <br />
I wanted to modify terms but it seems no effections. Here is my code: <br />
<pre>
add_action( 'rest_api_init', 'pi_register_terms_meta');

function pi_register_terms_meta()
{
   register_api_field( 'terms',
		        'pi_terms',
		        array(
		            'get_callback'    =>  'pi_terms_meta',
		            'update_callback' => null,
		            'schema'          => null,
		        )
   );
}
function pi_terms_meta( $object, $field_name, $request )
{
    return $object;
}
</pre>
My fetch: http://wiloke.com/wp-json/wp/v2/terms/category?_jsonp=JSON_CALLBACK <br />
Response: <br />
<pre>
_links: Object
count: 0
description: ""
id: 11
link: "http://wiloke.com/blog/category/drupal/"
name: "Drupal"
parent: 0
slug: "drupal"
taxonomy: "category"
</pre>

What might I be doing wrong?

**Comment by joehoyle** [comment]
I think the field is `term` not `terms`

**Comment by danielbachhuber** [comment]
Yep, `term` is the `title` of the resource: https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-terms-controller.php#L507

**Comment by wiloke** [comment]
Thank you so much
