### ISSUE TITLE
How to GET only top level terms (without parent)

### ISSUE THREAD

**Issue by equatorapps** [WP-API/WP-API#1735]
We are using WP-API v2 beta-5 and the following path: wp-json/wp/v2/terms/product_cat/ to get the woo commerce categories we have entered, and there are many. I have tried to use parent=0, but that does nothing. parent=xxx only seems to work for whole numbers. Is there another parameter or path to get just   terms without a parent? Thanks.

**Comment by swissspidy** [comment]
According to the docs and [the code](https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-terms-controller.php#L82) `parent=0` should work.

Perhaps the `0 === $request['parent']` check fails because it's not an int, so that would be a bug.

**Comment by Toddses** [comment]
There's a bug in the terms controller beta-5 which prevents you from making a request for only top-level terms (ie. terms with parent 0).

A fix landed in beta-6. So if you update, the `wp-json/wp/v2/terms/product_cat?parent=0` endpoint should do the trick.

**Comment by equatorapps** [comment]
Thanks guys! I have updated to beta6, but my results are the same as before. parent=0 returns all terms. parent=234 returns only terms with that parent id.

**Comment by danielbachhuber** [comment]
> Perhaps the 0 === $request['parent'] check fails because it's not an int, so that would be a bug.

This is the problem. It was introduced in #1604. We'll fix this in 2.0 Beta 6.1
