### ISSUE TITLE
Files from "core" dir are not found when installed with Composer

### ISSUE THREAD

**Issue by michaelperrin** [WP-API/WP-API#1736]
This issue may have already been reported, but I couldn't find it.

I installed WP-API using Composer:

    {
        "require": {
            "wp-api/wp-api": "2.0-beta6"
        }
    }

And I now get this error on every Wordpress page:

> PHP Fatal error:  require_once(): Failed opening required '/var/www/my-website/wordpress/wp-content/plugins/json-rest-api/core/rest-api.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/my-website/wordpress/wp-content/plugins/json-rest-api/plugin.php on line 14

I was using WP API 2.0 beta 4 berore and i didn't have the issue, I think it appeared in beta 5 when the `core` folder was moved to another repository.

**Comment by danielbachhuber** [comment]
> I think it appeared in beta 5 when the core folder was moved to another repository.

This is because the `core` directory is a Git submodule — which means it's not compatible with Composer.

We'll need some alternate way to load the `core` directory for Composer-based installs. Any suggestions?

**Comment by goblindegook** [comment]
Could the `core` directory be published as a separate package, then added to `wp-api/wp-api` as a dependency? I haven't tried it, but I suppose you could get the dependency to install in the same directory as the Git submodule using the `installer-paths` extra.

If anyone needs a painless workaround, the WPackagist package works fine: `wpackagist-plugin/rest-api`.

**Comment by danielbachhuber** [comment]
> Could the core directory be published as a separate package, then added to wp-api/wp-api as a dependency? I haven't tried it, but I suppose you could get the dependency to install in the same directory as the Git submodule using the installer-paths extra.

Hm, that might work.

**Comment by danielbachhuber** [comment]
I'm not going to spend the time fixing this right now. `core` as a submodule is a temporary thing: #1794

In the interim, you can use `"wpackagist-plugin/rest-api": "2.0-beta8"`
