### ISSUE TITLE
particluar post

### ISSUE THREAD

**Issue by menkaff** [WP-API/WP-API#1737]
how to understand requesting a particluar post /posts/1 not all of them /posts
cause i want to increase the meta of views for each posts 

is there anyway to open request protected variable to understand it in rest_prepare_post filter?

**Comment by danielbachhuber** [comment]
See documentation on modifying responses http://v2.wp-api.org/extending/modifying/

**Comment by menkaff** [comment]
it work but on listing posts too , i just want it increment on particular post or page like /posts/id not in /posts

**Comment by menkaff** [comment]
my function after register_api_init

function slug_get_views( $object, $field_name, $request ) {
	$s=get_post_meta( $object[ 'id' ], $field_name, true );
	$s++;
    	update_post_meta( $object[ 'id' ], $field_name, $s );
}

**Comment by menkaff** [comment]
in rest_prepare_post i get the rest_request and if its for particular page i increase it.
global $wp;
$route=$wp->query_vars['rest_route'];

thanks
