### ISSUE TITLE
WP_REST_Controller not a class

### ISSUE THREAD

**Issue by allurco** [WP-API/WP-API#1741]
I am not sure why, but when I try to extend it from a plugin of my own it says WP_REST_Controller not found. I don't think it would make send to include it. The WP API plugin is active and the default endpoints are working.

Here is the code:

    class Localbookups_Extended_Routes extends WP_REST_Controller
    {

    /**
     * Register the routes for the objects of the controller.
     */
    public function register_routes()
    {
        $version = '1';
        $namespace = 'localsbookups-api/v' . $version;
        $base = 'locals';
        register_rest_route($namespace, '/' . $base, array(
            array(
                'methods' => WP_REST_Server::READABLE,
                'callback' => array($this, 'get_items'),
                'permission_callback' => array($this, 'get_items_permissions_check'),
                'args' => array(),
            ),
            array(
                'methods' => WP_REST_Server::CREATABLE,
                'callback' => array($this, 'create_item'),
                'permission_callback' => array($this, 'create_item_permissions_check'),
                'args' => $this->get_endpoint_args_for_item_schema(true),
            ),
        ));
        register_rest_route($namespace, '/' . $base . '/(?P<id>[\d]+)', array(
            array(
                'methods' => WP_REST_Server::READABLE,
                'callback' => array($this, 'get_item'),
                'permission_callback' => array($this, 'get_item_permissions_check'),
                'args' => array(
                    'context' => array(
                        'default' => 'view',
                    ),
                ),
            ),
            array(
                'methods' => WP_REST_Server::EDITABLE,
                'callback' => array($this, 'update_item'),
                'permission_callback' => array($this, 'update_item_permissions_check'),
                'args' => $this->get_endpoint_args_for_item_schema(false),
            ),
            array(
                'methods' => WP_REST_Server::DELETABLE,
                'callback' => array($this, 'delete_item'),
                'permission_callback' => array($this, 'delete_item_permissions_check'),
                'args' => array(
                    'force' => array(
                        'default' => false,
                    ),
                ),
            ),
        ));
        register_rest_route($namespace, '/' . $base . '/schema', array(
            'methods' => WP_REST_Server::READABLE,
            'callback' => array($this, 'get_public_item_schema'),
        ));
    }

   ... all the sample code inbetween

    }

     // Localbookups.
    function register_custom_routes()
    {
        $controller = new Localbookups_Extended_Routes;
        $controller->register_routes();
    }

    add_action( 'rest_api_init', 'register_custom_routes', 5 );

**Comment by danielbachhuber** [comment]
> I am not sure why, but when I try to extend it from a plugin of my own it says WP_REST_Controller not found. I don't think it would make send to include it. The WP API plugin is active and the default endpoints are working.

You're likely loading the class before the WP-API plugin has loaded.

**Comment by allurco** [comment]
I am suspecting that as well, but wouldn't this do the job. I changed the priority to 5?

    add_action( 'rest_api_init', 'register_custom_routes', 5 );

**Comment by danielbachhuber** [comment]
> I am suspecting that as well, but wouldn't this do the job.

No, because you have a `require_once` loading the controller file earlier, and it's trying to extend a class that doesn't exist.

**Comment by nilesuan** [comment]
So my plugin always goes first before the wp-rest plugin, what is the solution to this?

**Comment by BE-Webdesign** [comment]
@nilesuan You can use this in your plugin file to load it after the API plugin. This will set your plugin to load last.

``` php
/**
 * Ensures that this plugin is loaded after WP REST API plugin.
 *
 * Once WP_REST_Controller is in core this will not be necessary and will be
 * possibly removed or kept for backwards compatability.
 *
 * @see add_action( 'activated_plugin' ) && add_action( 'deactivated_plugin' ) Hooked into both.
 */
function load_my_plugin_last() {
    // Ensure path to this file is via main wp plugin path.
    $wp_path_to_this_file = preg_replace( '/(.*)plugins\/(.*)$/', WP_PLUGIN_DIR . '/$2', __FILE__ );
    $this_plugin          = plugin_basename( trim( $wp_path_to_this_file ) );
    $active_plugins       = get_option( 'active_plugins' );
    $this_plugin_key      = array_search( $this_plugin, $active_plugins );

    if ( in_array( $this_plugin, $active_plugins ) && end( $active_plugins ) !== $this_plugin ) {
        array_splice( $active_plugins, $this_plugin_key, 1 );
        array_push( $active_plugins, $this_plugin );
        update_option( 'active_plugins', $active_plugins );
    }
}
add_action( 'activated_plugin', 'load_my_plugin_last' );
add_action( 'deactivated_plugin', 'load_my_plugin_last' );
```
