### ISSUE TITLE
For use in Production

### ISSUE THREAD

**Issue by karneaud** [WP-API/WP-API#1743]
Hello,

need to develop a backend rest service and chose wordpress with this plugin and saw the advisory. Unfortunately due to time constraints using this would be the most viable option. 

Are there any other limitations that I should be aware of when using in production?

**Comment by rmccue** [comment]
The API is fine for use in production in terms of code and security; the only reason we recommend against using in production is because we may break backwards compatibility in future betas as we nail everything down. As long as you keep that in mind, you'll be fine. :)

**Comment by karneaud** [comment]
Not sure if i missed this also but what about using the plugin with WordpressMU

**Comment by danielbachhuber** [comment]
WP-API is fully compatible with WordPress multisite

**Comment by karneaud** [comment]
If this is out of scope please let me know.... but because the plugin is in BETA I'm looking at creating a "proxy" api management... would the plugin be able to handle this? Also can you recommend some open source that might interact well with it?

**Comment by danielbachhuber** [comment]
> If this is out of scope please let me know

Outside the scope of what we support via Github issues.

**Comment by karneaud** [comment]
Sorry, my bad. Can you forward me to a community group to discuss such things?

**Comment by danielbachhuber** [comment]
> Can you forward me to a community group to discuss such things?

Check out http://wordpress.stackexchange.com/questions/tagged/wp-api
