### ISSUE TITLE
Easy way to disable or lockdown /posts endpoint?

### ISSUE THREAD

**Issue by jasonhjohnson** [WP-API/WP-API#1747]
I'm just curious if there's an easy way to disable or lockdown the /posts endpoint which is public out-of-the-box. I'd like to use the plugin as the basis for my own custom endpoints without exposing any of the defaults.

**Comment by danielbachhuber** [comment]
You can use some combination of this to disable core endpoints in v2.0:

```
remove_action( 'init', '_add_extra_api_post_type_arguments', 11 );
remove_action( 'init', '_add_extra_api_taxonomy_arguments', 11 );
remove_action( 'rest_api_init', 'create_initial_rest_routes', 0 );
```
