### ISSUE TITLE
v1 schema?

### ISSUE THREAD

**Issue by mwpastore** [WP-API/WP-API#1754]
The documentation at wp-api.org states that "The JSON Schema describing the entities in this document is available in schema.json" but it is not clear where to find that file. I'm looking at the 1.2.4 tag. Any suggestions?

**Comment by danielbachhuber** [comment]
Huh. Not sure where that went, unfortunately.

**Comment by danielbachhuber** [comment]
I found it committed to the v1.0 plugin release: http://plugins.svn.wordpress.org/json-rest-api/tags/1.0/docs/schema.json
