### ISSUE TITLE
2.0 Beta 7.0: Call to undefined function wp_tempnam

### ISSUE THREAD

**Issue by Mange** [WP-API/WP-API#1755]
I just tried my integration tests against beta 7.0 (I jumped from beta 5.0), but I get this error in my error log when I try to upload a file:

```
PHP Fatal error: 
Call to undefined function wp_tempnam() in /var/www/html/testapp.com/wp-content/plugins/rest-api/lib/endpoints/class-wp-rest-attachments-controller.php on line 334
```

Endpoint responds with a blank 500 response.

I'm running Wordpress in a Docker container, so literally the only thing that changed was which ZIP file was being used to unpack the plugin. Test code is the same.

Is this release broken?

**Comment by danielbachhuber** [comment]
> Is this release broken?

Yeah - sorry about that. More fallout from #1696. We'll release a beta 8 to fix this.

**Comment by Mange** [comment]
> Yeah - sorry about that.

No problem. I'll just wait with the upgrade. :-)

**Comment by tixastronauta** [comment]
When is beta8 going to be released?

**Comment by danielbachhuber** [comment]
> When is beta8 going to be released?

In the next day or two.

**Comment by Mange** [comment]
Seems beta-8 is out now, @tixastronauta.

**Comment by tixastronauta** [comment]
Thanks for the reminder @Mange!
