### ISSUE TITLE
Change post type

### ISSUE THREAD

**Issue by danwatt** [WP-API/WP-API#1758]
Is it possible to use the API to change the type of a post?

Im working on a tool to migrate from standard `posts` to a type of post offered by a plugin, but so far I am not seeing a way to use the API to do this, short of copying the post to a brand new post with new IDs.

This behavior seems to be limited in `class-wp-rest-posts-controller.php` here, but maybe I am missing something:

``` php
		// Post type.
		if ( empty( $request['id'] ) ) {
			// Creating new post, use default type for the controller.
			$prepared_post->post_type = $this->post_type;
		} else {
			// Updating a post, use previous type.
			$prepared_post->post_type = get_post_type( $request['id'] );
		}
		$post_type = get_post_type_object( $prepared_post->post_type );
```

**Comment by danielbachhuber** [comment]
> Is it possible to use the API to change the type of a post?

Nope. You'll need to write a custom endpoint for this behavior.
