### ISSUE TITLE
GET posts should expose status of a post

### ISSUE THREAD

**Issue by rmeritz** [WP-API/WP-API#1760]
When you create or update a post you can send in a status, but when you fetch a post or posts you cannot see the status of the post.

It would be very helpful to see the status of a post when you fetch it so you know if it is a draft or it has actually already been deleted and is just in the trash can. 

I'm using version 2 of the API.

**Comment by danielbachhuber** [comment]
> when you fetch a post or posts you cannot see the status of the post.

You can use `?context=edit` when authenticated to see the status of the post.

**Comment by rmeritz** [comment]
@danielbachhuber - Thanks. That worked for me.
