### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by devotox** [WP-API/WP-API#1761]
1. Is it possible to order by? i.e. likes/dislikes on a post 
2. API's to like/dislike a post?

**Comment by danielbachhuber** [comment]
Both of these questions are outside the scope of functionality for WP-API.

**Comment by devotox** [comment]
Im asking if this is possible using WP-API how is it outside the scope?

**Comment by danielbachhuber** [comment]
> Im asking if this is possible using WP-API how is it outside the scope?

Sure — it's possible. It will require custom development, however, and how to go about it isn't something we support.

**Comment by devotox** [comment]
Thank you
