### ISSUE TITLE
/posts/{id}/revisions terms key is an empty array

### ISSUE THREAD

**Issue by josiahsprague** [WP-API/WP-API#1762]
I've been using the revisions end point for a project, and I noticed that the API responses contain an empty array for terms; `"terms": []`, even though the parent post has terms, and there haven't been any changes made to the terms in the various revisions. The parent posts have a terms key that looks like;
```
"terms": {
  "category": [
    {
      "ID": 2,
      "name": "News",
      "taxonomy": "category",
      ...
    }
  ]
}
```
I'm not sure if this is a bug, or by design.

**Comment by danielbachhuber** [comment]
Which version of the plugin are you running? I can't reproduce with v2.0-beta:

![image](https://cloud.githubusercontent.com/assets/36432/11353399/a398865e-91f7-11e5-932c-f2c69e044c0f.png)

**Comment by josiahsprague** [comment]
Hi @danielbachhuber, I'm on 1.2.4. I realize that's probably not a target for non-security related bug fixes like this. Just seeking to confirm whether that's a bug or intended behavior. Since it looks like the 2.0 version just won't include that key, I'll plan to work around this behavior where we're relying on 1.2.4. Thanks!
