### ISSUE TITLE
How do i taxonomy post list

### ISSUE THREAD

**Issue by willmkt** [WP-API/WP-API#1766]
In the json api core was a function get_category_posts

http://www.example.org/api/core/get_category_posts/

How do i do the same function?

Or there is another way to get the data?

Thanks.

**Comment by rmccue** [comment]
I'm not sure what exactly you want here, but it seems like you want all posts in a category? You can use the [WP_Query category parameters](https://codex.wordpress.org/Class_Reference/WP_Query#Category_Parameters) for this; e.g. http://demo.wp-api.org/wp-json/wp/v2/posts?filter[category_name]=uncategorized

**Comment by willmkt** [comment]
Hi, i need to list all the terms with the posts that be belongs to each term.

Like on this example https://gist.github.com/jaredkc/6191133

Thanks.

**Comment by rmccue** [comment]
This is not possible in a single request. You need to first fetch the terms (`/wp/v2/terms/{taxonomy}`), then fetch posts in that term (likely `filter[{taxonomy}]={term1},{term2},...`)
