### ISSUE TITLE
?post_parent=ID is ignored on /media endpoint

### ISSUE THREAD

**Issue by scottopolis** [WP-API/WP-API#1767]
Issue: `site/wp-json/wp/v2/media?post_parent=ID` returns the same result as `site/wp-json/wp/v2/media`

There is no way to get attached images now, since _embedded['http://v2.wp-api.org/attachment'] was removed.

I am using beta7.

**Comment by rmccue** [comment]
I think this should be `filter[post_parent]={id}`, or we should add a `parent` argument to post list endpoints. I think the current URL is a holdover from when query parameters were top-level rather than being under `filter`.

Thanks for filing!
