### ISSUE TITLE
How to get post meta value,and the  first image of the post

### ISSUE THREAD

**Issue by skating507** [WP-API/WP-API#1769]
like title,How to get post meta value,and the  first image of the post.can`t work the code:
add_filter( 'json_prepare_post', function ($data, $post, $context) {
	$data['metadata'] = array(
		'price' => get_post_meta( $post['ID'], 'price', true ),
		'url' => get_post_meta( $post['ID'], 'url', true ),
	);
	return $data;
}, 10, 3 );

**Comment by danielbachhuber** [comment]
Which version of the WP-API plugin are you using?

**Comment by skating507** [comment]
v2

**Comment by rmccue** [comment]
For version 2, you should use `register_api_field` instead. See [the documentation](http://v2.wp-api.org/extending/modifying/) on doing this.

**Comment by skating507** [comment]
Use it now,but how can i get several meta  data in one function.
