### ISSUE TITLE
Searching users requires wildcards

### ISSUE THREAD

**Issue by joehoyle** [WP-API/WP-API#1771]
Unlike posts, which does wildcard search by default, `/wp/v2/users` requires an exact match on any of the searched fields, because this is the internal behaviour of `WP_User_Query`. One cal work around this by doing `/wp/v2/users?search=*ada*` to match "adam" etc.

I propose we auto add the wildcards on to the search query in users to match that of `/wp/v2/posts`

**Comment by danielbachhuber** [comment]
:+1: 

I think wildcards is expected behavior, although it might be nice to switch the query to exact match on occasion.
