### ISSUE TITLE
Some attributes in the content are stripped when creating posts.

### ISSUE THREAD

**Issue by gowthamgts** [WP-API/WP-API#1775]
Some attributes are stripped in the HTML tags while creating the post. Examples include attributes like `onclick, itemprop, etc.`

I'm using Version 2 and sending the post content through the `content` field. How can I allow those attributes and tags?

**Comment by rmccue** [comment]
This is built-in behaviour with WP: input HTML is run through `wp_kses`, which only [allows a subset of HTML](https://github.com/WordPress/WordPress/blob/master/wp-includes/kses.php#L52-L450). You can change this [via a plugin](http://wordpress.stackexchange.com/questions/17947/expanding-the-allowed-html-tags-in-comments) if needed.

Users with the `unfiltered_html` capability (that is, admins on single sites, and super admins on multisite installations) should be able to use any tags as well.

**Comment by gowthamgts** [comment]
That fixed my issue. Thanks.. :smile:

**Comment by l2aelba** [comment]
``` php
function allow_tags_content() {
    global $allowedposttags, $allowedtags;

    $allowedposttags['div']['data-hello'] = true;
    $allowedtags['div']['data-hello'] = true;

    $allowedposttags['div']['data-world'] = true;
    $allowedtags['div']['data-world'] = true;
}
add_action('init','allow_tags_content');
```
