### ISSUE TITLE
displaying posts thumbnails seems uncomfortable with WP-API

### ISSUE THREAD

**Issue by MurhafSousli** [WP-API/WP-API#1778]
Let's say we want to display the latest 10 posts from WP, `http.get('.../wp-json/wp/v2/posts')` this will return an array of posts, each post has property `post.featured_image` which contains the ID of the featured image, <b>NOT the source_url</b> of the featured image.

for displaying a single post, this might be okay to perform an extra http request just to get the source_url of the image using its id as a key `post.featured_image`

but what if we want to display 10 posts with their thumbnails, then we will have to do 10 more http requests just to get the image source_url for each post, we will have to execute this code for each post:
```
GetMedia(id: number) {
    var imageUrl; 
    var baseURL = "http://localhost/wptest/wp-json/wp/v2/";
    this.http.get(baseURL + 'media/' + id).subscribe(res => {
         var response: any = res.json();
         imageUrl = response.source_url;
    });
    return imageUrl;
}
```
So It would be very useful if we can get the 'sourceUrl' as a property just like 'featured_image'

**Comment by danielbachhuber** [comment]
You can use `?_embed` to embed the attached featured images, which include the image URLs.

**Comment by MurhafSousli** [comment]
can you tell me how to use it !!

**Comment by MurhafSousli** [comment]
@danielbachhuber can you tell me how to use it

**Comment by danielbachhuber** [comment]
```
http.get('.../wp-json/wp/v2/posts?_embed')
```
