### ISSUE TITLE
how to get feature image from post _embed response

### ISSUE THREAD

**Issue by MurhafSousli** [WP-API/WP-API#1779]
it seems impossible to get featured image from wp api with `?_embed`, if you do
```
console.log(http.get('http://localhost/wptest/wp-json/wp/v2/posts/10?_embed'));
```
and try to reach the featured image, you will see some properties' names contain url.
I used this tool to convert json response to an interface [class generator](http://jsonclassgenerator.codeplex.com/)

this simplified code is generated by the json response.
```
export interface Embedded {
        author: Author[];
        http://api.w.org/featuredmedia: HttpApiWOrgFeaturedmedia[];   //see property names
        http://api.w.org/term: any[];
        http://api.w.org/meta: HttpApiWOrgMeta[];
}

export interface Post {
       id: number;
        date: string;
        date_gmt: string;
        guid: Guid;
        modified: string;
        modified_gmt: string;
        slug: string;
        type: string;
        link: string;
        title: Title;
        content: Content;
        excerpt: Excerpt;
        author: number;
        featured_image: number;
        comment_status: string;
        ping_status: string;
        sticky: bool;
        format: string;
        _links: Links;
        _embedded: Embedded;
}
```

How am I supposed to get the featured image url! it would look like this:

` var imageUrl = post._embedded."http://api.w.org/featuredmedia".source_url; `

please show me the right way to get featured image or thumbnails urls.

**Comment by danielbachhuber** [comment]
```
var imageUrl = post._embedded.['http://api.w.org/featuredmedia'].source_url;
```

**Comment by rmccue** [comment]
(Also note: this is entirely up to your code generator and programming language, so please consult support on that end.)

**Comment by joehoyle** [comment]
All link rels are actually arrays so this would be 

```JS
var imageUrl = post._embedded.['http://api.w.org/featuredmedia'][0].source_url;
```

@rmccue's design I think, maybe he had weigh in on exactly why it's that way.

**Comment by rmccue** [comment]
> @rmccue's design I think, maybe he had weigh in on exactly why it's that way.

Per the [HAL standard](http://stateless.co/hal_specification.html), multiple links are allowed. If we don't wrap with an array, you need to do more client-side handling to determine whether there's a single link or multiple.
