### ISSUE TITLE
Update from V1, or keep both?

### ISSUE THREAD

**Issue by fgilio** [WP-API/WP-API#1781]
Hello!

We have a couple of sites running WP-API V1 to power mobile Apps. Since a couple of days we've been struggling to design a plan to transparently migrate our Apps to use WP-API V2, while keeping users with outdated Apps still happy.

And now that WP 4.4 ETA is December 8, we're a little more worried as we couldn't find any resource about this...

How should we approach the upcoming update to WP 4.4?
Or, is there a way we can migrate to V2 while keeping the V1 endpoints?

Thanks!

**Comment by danielbachhuber** [comment]
> How should we approach the upcoming update to WP 4.4?

You don't need to worry about it. If WP-API v1.2.4 is active on your sites, then the API will continue to work as expected when you upgrade to WordPress 4.4 (and indefinitely in the future). WP-API v1.2.4 takes priority over the server in WordPress 4.4.

> Or, is there a way we can migrate to V2 while keeping the V1 endpoints?

I haven't explored it at depth, but you could conceivably do some rewrite rule hacking such that all of your v1 endpoints are handled by WP API v1.2.4 indefinitely, and your other endpoints are handled by the REST API server in WordPress 4.4.

**Comment by fgilio** [comment]
Thanks @danielbachhuber !
Would you please go a little more in depth about that rewrite rule hacking?
