### ISSUE TITLE
Download text file within Media endpoint

### ISSUE THREAD

**Issue by golangninja** [WP-API/WP-API#1782]
Is it possible to download a text file using the WP REST API?  I'm using oauth1 and able to hit all the endpoints just fine.  I have the WP Plugin Media Vault installed and set a txt file to protected.  Using oauth1 I cannot download the txt file when it is protected.  I was wondering if there is another way to do this, where the file would remain secure, with no outside access and using the WP API?

**Comment by rmccue** [comment]
It sounds like the file is stored by the Media Vault plugin, so it really relies on how that plugin works. You'll need to ask the plugin developer about this. :)
