### ISSUE TITLE
Add 'HEAD' HTTP methods to 'GET' endpoints

### ISSUE THREAD

**Issue by PattaFeuFeu** [WP-API/WP-API#1783]
Currently, sending a `HEAD` request to, e.g., `/wp-json/wp/v2/posts` returns an `HTTP 404` error.

Before downloading all the posts or pages via a `GET` request, I’d like to check beforehand whether the post/page count has changed. I’d then, for example, `HEAD $BASE/wp-json/wp/v2/posts` and expect to have `X-WP-Total → 42` returned.

**Comment by rmccue** [comment]
Hmm, that's strange, HEAD requests should definitely work. Internally, they're treated as GET requests, we just never send the data back. Looks like we may have broken this though...

**Comment by danielbachhuber** [comment]
Looks like it's been broken for the entirety of the betas:

```
local ➜  wp-api git:(09fb2c1) ✗ gco 2.0-beta1
Previous HEAD position was 09fb2c1... Update stable to v1.2.4
HEAD is now at 184f576... Add 2.0 Beta 1 changes to CHANGELOG.
local ➜  wp-api git:(184f576) ✗ http HEAD wordpress-develop.dev/wp-json/
HTTP/1.1 404 Not Found
local ➜  wp-api git:(184f576) ✗ gco 1.2.4
Previous HEAD position was 184f576... Add 2.0 Beta 1 changes to CHANGELOG.
HEAD is now at 09fb2c1... Update stable to v1.2.4
local ➜  wp-api git:(09fb2c1) ✗ http HEAD wordpress-develop.dev/wp-json/
HTTP/1.1 200 OK
```

**Comment by danielbachhuber** [comment]
Oh, because 1.x has this:

```
public function dispatch() {
		switch ( $this->method ) {
			case 'HEAD':
			case 'GET':
				$method = self::METHOD_GET;
				break;
```

And 2.x checks the method explicitly:

```
foreach ( $handlers as $handler ) {
	$callback  = $handler['callback'];
	$response = null;

	if ( empty( $handler['methods'][ $method ] ) ) {
		continue;
	}
```

**Comment by danielbachhuber** [comment]
Lo and behold, this is an infrastructure bug: https://core.trac.wordpress.org/ticket/34837

We'll get this fixed in beta9. Keeping the Github issue open until the infrastructure is merged over.
