### ISSUE TITLE
403 Error When making a POST request to VVV using Basic Auth

### ISSUE THREAD

**Issue by ellm** [WP-API/WP-API#1787]
I am experimenting with WP-API and AngularJS. Please know that I am still learning many concepts in JS/Angular, however, here is my situation:

I've created a simple form and trying to send a POST request to the default VVV (Varying Vagrant Vagrants) WordPress. I have installed both WP-API and Basic Auth plugins.

My HTML file is sitting in the default WordPress folder (to avoid cross-domain issues). Here is my HTML code: https://gist.github.com/ellm/db764b2e37ae35419d17

The issue is that I receive a 403 error when making a POST request from the webform. I've tested the same request in Postman and did not receive any error.

Is this a bug in the API or am I not doing something correct? 

Thanks in advance

**Comment by danielbachhuber** [comment]
> The issue is that I receive a 403 error when making a POST request from the webform. I've tested the same request in Postman and did not receive any error.

If the request works in Postman and doesn't work with your JavaScript, then there's something incorrect about your JavaScript.
