### ISSUE TITLE
Comments: cannot send true IP address

### ISSUE THREAD

**Issue by jdigory** [WP-API/WP-API#1788]
I see that this line: 
`$prepared_comment['comment_author_IP'] = '127.0.0.1';`
from: https://github.com/WP-API/WP-API/blob/074dab5071d0a3c685a73c6b843af00b390ad771/lib/endpoints/class-wp-rest-comments-controller.php#L182

causes the IP address to be unable to be set to whomever is calling the API. This seems like a problem. If the end-user is calling the API, then their IP address should be sent. If a server is proxying the comment, then its IP address should be sent -- and possibly be able to be overridden via WP's pre_comment_user_ip hook (https://codex.wordpress.org/Plugin_API/Filter_Reference/pre_comment_user_ip).

For example, I would like to use pre_comment_user_ip to replace the REMOTE_ADDR with X_FORWARDED_FOR, since I am proxying the comment API post.

I was able to get around the API forcing localhost to be the IP by this hacked up WP filter:

```
function proxy_ip( $prepared_comment )
{
    // Use IP set in the REMOTE_ADDR server variable by default
    $CLIENT_IP = $_SERVER['REMOTE_ADDR'];
    if (!empty($_SERVER['X_FORWARDED_FOR'])) {
        $X_FORWARDED_FOR = explode(',', $_SERVER['X_FORWARDED_FOR']);
    }
    elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
        $X_FORWARDED_FOR = explode(',', $_SERVER['HTTP_X_FORWARDED_FOR']);
    }

    if (!empty($X_FORWARDED_FOR)) {
        $CLIENT_IP = trim($X_FORWARDED_FOR[0]);
        //$CLIENT_IP = preg_replace('/[^0-9a-f:\., ]/si', '', $CLIENT_IP);
    }

    $prepared_comment['comment_author_IP'] = $CLIENT_IP;
    return $prepared_comment;
}
add_filter( 'rest_pre_insert_comment', 'proxy_ip' );
```

**Comment by danielbachhuber** [comment]
> If the end-user is calling the API, then their IP address should be sent. If a server is proxying the comment, then its IP address should be sent -- and possibly be able to be overridden via WP's pre_comment_user_ip hook

This seems reasonable. I've flagged this as a bug meriting discussion. The corresponding code was introduced in 1bc96e50852fd1ac6b4d615c5467fee0db083a8a by @rachelbaker.

**Comment by danielbachhuber** [comment]
Some conversation [in Slack](https://wordpress.slack.com/archives/core-restapi/p1449531782001386).

> rmccue [3:43 PM] So on the comment IP thing, my main concern with that is IP spoofing to get around spam restrictions
> ​[3:43] That said, it's only an authenticated API
> rachelbaker [3:43 PM] I agree, but if you have IP address on your blacklist we won’t catch them
> joehoyle [3:44 PM] is the "slow down" done based off IP?
> rachelbaker [3:44 PM] Previously we couldn’t set the comment IP address (because of how comment functions worked)
> rmccue [3:44 PM] I think so.
> ​[3:44] @rachelbaker: Yeah, I think that was the original motivation for that, right?
> joehoyle [3:45 PM] ah I see
> ​[3:45] I'd be +1 for allowing the client to send the forwarded IP
> ​[3:45] I don't think we should use the IP as a security measure(edited)
> rachelbaker [3:46 PM] I am also +1 to allow clients to send the forwarded IP
> rmccue [3:46 PM] I agree, but that's not my call to make :simple_smile:
> ​[3:46] If anyone from Akismet is around, I'd love their opinion

**Comment by joehoyle** [comment]
This is now allowed in core https://core.trac.wordpress.org/ticket/35276

**Comment by mc256** [comment]
Thanks a lot!

Basically, I changed
`$prepared_comment['comment_author_IP'] = '127.0.0.1';`
to 
`$prepared_comment['comment_author_IP'] = $_SERVER['REMOTE_ADDR'];`
in file `/lib/endpoints/class-wp-rest-comments-controller.php`
for a temporary fix. For those who don't have a proxy server, this solution could be the simplest one.
