### ISSUE TITLE
Questions regarding meta data access and creating/updating records

### ISSUE THREAD

**Issue by tony1377** [WP-API/WP-API#1792]
Hi

I've had a look at the documentation and some other tutorials and I just wanted to clarify if my understanding of the v2 api features are correct or not.

I'm still new to wordpress so please correct me any incorrect assumptions I may have

I'm looking at creating a shopping cart on a wordpress blog which will be using the wp rest api js client.

I'm making an assumption that the standard way of saving custom records in wp is to use Post records and adding custom fields via the ability to add meta data to a Post record so that a Post record effectively becomes a Product record. 

It mentions here http://v2.wp-api.org/guide/problems/#protected-meta that "For meta that does not fit one of the above criteria, the data is available via the API. However, this data is only available when authenticated with permission to edit the post that the meta is attached to."

My interpretation of this is that the meta data is only available when the user is admin, so, does this mean that any product records returned would not have any custom fields available when the user is just a normal browser and not admin?

Also I've had a look through the documentation and it doesn't appear as if it's possible for a non logged in user to create/update records. In my scenario I need to be able to record the searches made on the site by non logged in users. Is this possible using the wp rest api?

Thanks

Tony

**Comment by danielbachhuber** [comment]
> My interpretation of this is that the meta data is only available when the user is admin, so, does this mean that any product records returned would not have any custom fields available when the user is just a normal browser and not admin?

Correct. You should use `register_api_field()` to register the fields you'd like to use to your Product custom post type: http://v2.wp-api.org/extending/modifying/

> Also I've had a look through the documentation and it doesn't appear as if it's possible for a non logged in user to create/update records. In my scenario I need to be able to record the searches made on the site by non logged in users. Is this possible using the wp rest api?

Correct. You'll need to write a bit of custom PHP code in order to handle the use case you've described.
