### ISSUE TITLE
Multisite redirect loop issue

### ISSUE THREAD

**Issue by ksolomon** [WP-API/WP-API#1798]
I installed the plugin on one of the child sites on my multisite dev install (MS is using the subdirectory method if that changes things), and am stuck with a redirect loop when I try to hit the API.

Looking at the server log, it appears that it's trying to redirect to the API at the root of my server (log snippet here... http://pastie.org/private/88m3n7dkzu61atsw2umqyg ) a number of times before hitting the apache redirect limit, at which point it throws a 500 error.  Is there some magic to get this to work on WPMS?

**Comment by danielbachhuber** [comment]
> Is there some magic to get this to work on WPMS?

There shouldn't be. Are you sure your `.htaccess` file is configured appropriately?

**Comment by ksolomon** [comment]
Positive.  Here's the entirety of my .htaccess... http://pastie.org/private/zjbsii3bxks5bduca6apq

**Comment by danielbachhuber** [comment]
I don't have any good ideas as to what the problem could be without being able to see it reproduce on my own.

Could there be another plugin causing the behavior? Can you try setting up a stock install of WP 4.4-rc, and see if it reproduces with the REST API infrastructure in core?

**Comment by ksolomon** [comment]
Thanks.  I'll give that a shot.

**Comment by danielbachhuber** [comment]
@ksolomon were you able to track this down?

**Comment by ksolomon** [comment]
Sorry, between trying to finish up client work, and the normal end of year stuff, I haven't had a chance to get back to this.  I'm hoping to be able to get back to it sometime in the next week or so.

**Comment by danielbachhuber** [comment]
Ok. Feel free to re-open the issue if you think you've discovered a bug.
