### ISSUE TITLE
terms issue (object/array)

### ISSUE THREAD

**Issue by pratham2003** [WP-API/WP-API#1800]
In version 1.x (I haven't tested version 2.x yet) when making a /wp-json/posts GET request the 'terms' associated with a particular post is either an empty array or an object when the post has tags/categories. Someone pointed out to me that android has getJSONArray or getJSONObject methods which expect either an array or object. I googled and came across this stackoverflow question to determine if its an array or object http://stackoverflow.com/questions/6118708/determine-whether-json-is-a-jsonobject-or-jsonarray

But can it be possible to make sure that terms is always an object by setting it to null instead of an empty array in case its empty?

**Comment by danielbachhuber** [comment]
This is fixed in v2.x. We're not making any changes to v1.x at this time, other than to fix security issues.
