### ISSUE TITLE
Wordpress 4.4 and Rest Api V1

### ISSUE THREAD

**Issue by hefejeff** [WP-API/WP-API#1812]
I am currently using REST API V1 and can't make the switch at this time.  If I install WP 4.4 will the rest api inclusion in the core conflict with the V1 plugin?

**Comment by lostfocus** [comment]
Yes-ish. It breaks the new embed functionality.

**Comment by danielbachhuber** [comment]
> f I install WP 4.4 will the rest api inclusion in the core conflict with the V1 plugin?

Please make sure you update to WP-API v1.2.4, which is compatible with WordPress 4.4 in that it takes priority over the REST API in core.

@lostfocus is correct in that activating WP-API v1.2.4 means the new embed functionality won't be available.

**Comment by wkw** [comment]
Couple questions to try and clarify what breaks:

1. By "new embedding" does that just refer to embedding WP posts? If so, is it in both directions? i.e., the site running v1.4 plugin will not be able to provide embeds to other consumer sites? or it also cannot embed WP posts from provider sites **not** running rest api 1.4 plugin?
2. do non-wp post embeds continue to work? e.g., pasting in a youtube link?

**Comment by danielbachhuber** [comment]
> i.e., the site running v1.4 plugin will not be able to provide embeds to other consumer sites?

Correct.

> or it also cannot embed WP posts from provider sites not running rest api 1.4 plugin?

No.

> do non-wp post embeds continue to work? e.g., pasting in a youtube link?

Yes.
