### ISSUE TITLE
Before I fork...

### ISSUE THREAD

**Issue by wuntusk** [WP-API/WP-API#1813]
Not sure if this is intended use but it seems the most basic.  I've been using the api for some time to provide basic content or blog data to an existing SPA web site with angular.  Recently I was trying to display posts along with the user and the tags on the posts.  Unfortunately to get this basic data for a post I end up having to do a ton of requests to the rest api.  For instance if I'm loading a page with 4 posts I have to do one GET for the 4 posts.  But then 4 more GETS to get the user for each post, and then 4 more GETS to retrieve the tags for each post.  So rather than 1 nice GET request with what I need I'm making 9 requests.  Am I missing something here?  

It's not a big deal and I can certainly fork the code and return what I want in one call but just wanted to make sure before I did the work that I wasn't just missing something.

**Comment by rmccue** [comment]
Try adding `?_embed` to the endpoint to get [the links as embedded data](http://v2.wp-api.org/extending/linking/#embedding). Does this solve it for you? :)

**Comment by wuntusk** [comment]
Boom.... well you just saved me a bunch of work :)  I knew it seemed like too obvious of an oversight..

**Comment by wuntusk** [comment]
Solved the problem.. one quick question that maybe you can answer without me digging. Any reason why every image is showing up as an attachment on every single post?  I've got 3 posts each with an image in it.. yet the api is saying every single post has 10 attachments of images.

**Comment by danielbachhuber** [comment]
> Any reason why every image is showing up as an attachment on every single post?

No idea what you're talking about. Can you share an example request, and response? Do you have any custom code which could be modifying the response unexpectedly?

**Comment by wuntusk** [comment]
Since it sounds weird I'll dig into it.

**Comment by wuntusk** [comment]
So I see the problem.. 

The attachment portion of the response has this href in it

href: "http://wp.aumscript.com/wp-json/wp/v2/media?post_parent=40"

But it appears that the post_parent is being ignored as whether I request the media link with or without the post_parent parameter I get 10 images back.  I didn't notice this until I started using the _embed flag.

I'm using the production version and not the latest source so maybe this is just some old bug floating around.

**Comment by danielbachhuber** [comment]
> But it appears that the post_parent is being ignored as whether I request the media link with or without the post_parent parameter I get 10 images back. I didn't notice this until I started using the _embed flag.

Fixed in beta8, so you should get updated :) #1777

Glad you got it sorted though.

**Comment by wuntusk** [comment]
I was beta5  yep beta8 sorted it out.  Thanks for the help Dan!
