### ISSUE TITLE
Add support for custom post fields

### ISSUE THREAD

**Issue by PattaFeuFeu** [WP-API/WP-API#1816]
Currently, custom fields added to a post don’t appear when making a `GET` call to an individual post’s url or to the list of posts.

![Screenshot of Custom Post Field](https://cloud.githubusercontent.com/assets/9012887/11688719/87903706-9e8e-11e5-8146-89d552bd70c4.png)

**Comment by danielbachhuber** [comment]
Related #1425 

For now, you should follow these instructions http://v2.wp-api.org/extending/modifying/
