### ISSUE TITLE
Transform /wp/v2/taxonomies from array to object

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1819]
Both `/wp/v2/types` and `/wp/v2/statuses` are objects. Because the taxonomy slug is a unique key, we should make `/wp/v2/taxonomies` an object as well.

**Comment by joehoyle** [comment]
Hmm I think this is an oversight for `types` and `statusus`, it seems to me they should be arrays (or did I miss that conversation). An object is inconsistant with everything else (posts, comments etc) as the `all` endpoint `/types` should return a collection of `type` objects/

**Comment by danielbachhuber** [comment]
> Hmm I think this is an oversight for types and statusus, it seems to me they should be arrays (or did I miss that conversation).

https://github.com/WP-API/WP-API/pull/914#issuecomment-76316952
