### ISSUE TITLE
getting forbidden message while being logged in as admin

### ISSUE THREAD

**Issue by tdapper** [WP-API/WP-API#1821]
I'm currently using the Basic Auth authorization plugin (I know it is discouraged, but I'm working in an environment where the full Basic Auth flow isn't feasible to implement).

At first I had server configuration problems where the authentication headers weren't passed through to PHP, but those were solved. At least I assume that, because when querying the

`wp-json/wp/v2/users/me`

endpoint, I'm getting proper information about me.

The user I am logging in as has admin rights, so I should be allowed to do pretty much everything. However, when trying to read a privately published post by accessing its post endpoint like this

`wp-json/wp/v2/posts/88556`

I'm getting a 403 forbidden error. This similarly appears to happen with other attempts that require user privileges beyond that of a regular user that isn't logged in. I also tried to explicitly include private posts in the filter rules (filter[post_status]=publish,private) both for the direct access to the posting as well as when accessing:

`wp-json/wp/v2/posts`

I faintly remember having found an article on the web that claimed there was a problem like this where the basic auth was checked first, then the regular auth overwrote the privileges again because no nonce was passen. However, I abandoned the article when I solved the configuration problem (assuming that was my only problem) and did not yet find it again. 

@rmccue asked my to post this here instead of with the basic auth plugin. You can find the original thread here: https://github.com/WP-API/Basic-Auth/issues/21#issuecomment-162119178

**Comment by danielbachhuber** [comment]
> However, when trying to read a privately published post by accessing its post endpoint like this

Can you share the full request you're making?

Also, to rule out any environmental factors, can you try to reproduce on a stock install of WordPress (without any custom themes / plugins, etc. )?

**Comment by tdapper** [comment]
Thanks @danielbachhuber for looking into this. With the full request, do you mean all the data being transmitted or the source of my call? Not sure how to recover the former, but I'm using a simple Python script for testing. It looks like this (full source, just garbage a try block and my username/password removed):

```python
#!/usr/bin/python
import urllib, urllib2, base64, json
url = 'https://www.laubwerk.com/wp-json/wp/v2/posts/88556'
usr = 'username'
pwd = 'password'
request = urllib2.Request(url)
request.add_header('Authorization', 'Basic ' + base64.b64encode(usr + ':' + pwd))
response = urllib2.urlopen(request)
print response.read()
```

I don't have a test environment ready, but I'll manage to set one up to rule out environmental factors.

**Comment by tdapper** [comment]
I did some more testing and while I still can't see that particular private post, I was able to see and even edit other privately published posts, so I must be doing something else wrong. Thanks for the quick response, @danielbachhuber!

**Comment by mikodigital** [comment]
i have the exact same problem trying to create a user from a nodejs app.

**Comment by kadamwhite** [comment]
@mikodigital if you're having an issue with basic auth, please open an issue on that plugin's repository with a test case or steps to reproduce. Thank you!
