### ISSUE TITLE
Change GET /wp/v2/taxonomies?post_type argument to ?type

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1836]
Related #924

**Comment by TimothyBJacobs** [comment]
I think we should stick to post_type. While the core endpoints only support post types for taxonomies, taxonomies could be registered for any object type. If core supported is added at some point for user taxonomies, or is added by another plugin, just the type parameter might be a bit ambiguous.

**Comment by joehoyle** [comment]
Give the `taxonomy` object has a `types` property, it should be `?type` to be consistent with that, and how `/posts` functions also. If we were to change this to `post_type` (or leave it as that, as it were) then we'd want to change the property to `post_types` on the taxonomy object.
