### ISSUE TITLE
General problem about using Javascript "Single Page App" websites with shortcodes

### ISSUE THREAD

**Issue by aunruh** [WP-API/WP-API#1843]
Hey!
I'm sure with wp-api more and more people will start building JavaScript Frontends where you don't have full page refreshs, but the new content is just loaded dynamically into a content area.

Many plugins provide shortcodes. These return markup but often the plugin executes javascript too. (For example a plugin for slideshows would return markup and initialize some slideshow js.)

However, plugins that utilize JavaScript often rely on the "document ready" event to initialize their js. But "document ready" only fires once on a "Single Page App" js website. That's why most plugins that use shortcodes don't work properly with "Single Page App" websites.

Is there a solution for this?

I'm sorry this is not a sepcific question about wp-api. I think this is a general compatibility problem with wordpress moving towards api powered javascript apps.

**Comment by danielbachhuber** [comment]
> Is there a solution for this?

Not to my knowledge. Returned inline JavaScript isn't a scope of responsibility for WP-API, so it's not something we intend to work on a global fix for. As more applications of WordPress turn into SPA based on top of the REST API, there will be a myriad of implementation issues we'll need to work out, shortcodes being one of them.

Related #576

**Comment by rmccue** [comment]
This is really more of a wider-community issue, and plugin/theme authors will need to come to some sort of consensus about how this should work. There's not much we can do in the API itself to help with this right now.
