### ISSUE TITLE
 Notice: Undefined property: stdClass::$show_in_rest 

### ISSUE THREAD

**Issue by Shelob9** [WP-API/WP-API#1850]
Occurs with WP 4.4, plugin beta9 when querying by single post:
`/lib/endpoints/class-wp-rest-posts-controller.php on line 911`

No other plugins active. Twenty Fifteen is theme.

**Comment by danielbachhuber** [comment]
Thanks for the report! We'll get this fixed in the next beta.

Are you querying a custom post type, by chance? It's not clear how `show_in_rest` could be unset for the `post` post type, as we're defining the attribute in plugin.php https://github.com/WP-API/WP-API/blob/develop/plugin.php#L104

**Comment by Shelob9** [comment]
@danielbachhuber I need to do more testing today. I was operating with out xdebug when this happened to me. It was occurring <em>when querying for posts or the post type post</em>, which made no sense, and I need to do more investigation as to how this could happen.
