### ISSUE TITLE
Intercept request to check for self defined parameters?

### ISSUE THREAD

**Issue by EugeneLiang** [WP-API/WP-API#1851]
Hi there, 

Pardon me if this sounds like a silly question, but may i know how can i intercept a GET/POST request in order to check if a self-defined parameter is available in the url ?

For example,  `/wp-json/wp/v2/posts/1712` is the usual way of performing a GET request.
And what i want to do is to do a GET request like this:

`/wp-json/wp/v2/posts/1712?myParameter=someValue` 

I want to check the someValue against my own defined table before allowing the request to continue.

May i know if there's any WP-API hooks I can use to achieve the above ? If not, is there any other simple way to achieve the above ?

Thanks!

**Comment by swissspidy** [comment]
You could probably hook into `rest_pre_dispatch`, where you have access to the current `WP_REST_Request`. The `WP_REST_Request` contains all passed parameters (see `get_params()` method).

**Comment by danielbachhuber** [comment]
Yep, `rest_pre_dispatch` is the hook you want: https://developer.wordpress.org/reference/hooks/rest_pre_dispatch/

**Comment by EugeneLiang** [comment]
yup agreed that `rest_pre_dispatch` is what i needed. 

I wrote a simple plugin that does this here: https://github.com/EugeneLiang/wp-api-secure 

Thanks!
