### ISSUE TITLE
Reactivation issue

### ISSUE THREAD

**Issue by nextpulse** [WP-API/WP-API#1855]
Seeing a strange error.
I have the plugin (v2 beta9) working.
However, if I deactivate it and reactive it - the API endpoints stops working.
Any ideas?

(I have no obvious cache set)

**Comment by Shelob9** [comment]
Are you installing from WordPress.org or cloning this git repo? If you are cloning this repo are you doing so recursively to get the submodule? Also, what version of WordPress are you using?

**Comment by nextpulse** [comment]
WP: 4.4
I am using the plugin: Version 2.0-beta9

**Comment by danielbachhuber** [comment]
> the API endpoints stops working.

What do you mean by "stops working"? Can you share an example request you're making, and the response you receive?

Also, to confirm, you've disabled all other plugins to verify the problem isn't being caused by another plugin?
