### ISSUE TITLE
Category not assigned to new post word press rest api

### ISSUE THREAD

**Issue by joseph-kuruvilla** [WP-API/WP-API#1859]
working with rest api. i can able to create a new post to wp using http://v2.wp-api.org/. problem is i cannot assign a category to newly created post new posts created are all uncategorized . my working example follows

{
"title":"My New Title",
"type":"post",
"content":"this is my new content",
"terms":{
"category":[
{
"name":"sports"
}
]
}
am i completely on the wrong path. can any one show some light on how to assign category to newly created post.thanks in advance

**Comment by danielbachhuber** [comment]
You'll need to assign the category in a second request:

`POST /wp/v2/posts/<new-post-id>/categories term_id==<term-id>`

**Comment by joseph-kuruvilla** [comment]
this works. but doesn't remove uncategorized.
my code
$response = $this->api->post('wp-json/wp/v2/posts', $headers, json_encode($data));
$id=$response['id'];  //post-id
$term_id=3;  //term-id
$response1 = $this->api->post('wp-json/wp/v2/posts/'.$id.'/categories/'.$term_id, $headers, json_encode($data));
category is working but when i go to wordpress dashboard .i also see an uncategorized along with assigned category .how should i eliminate this issue?

**Comment by danielbachhuber** [comment]
You'll need to make a `DELETE` request to remove Uncategorized from the post.

**Comment by joseph-kuruvilla** [comment]
that doesn't work. ended up on error
Array ( [code] => rest_trash_not_supported [message] => Terms do not support trashing. [data] => Array ( [status] => 501 ) )

**Comment by rmccue** [comment]
Add `?force=true`; terms don't support trashing, so you need to permanently delete them.

**Comment by joseph-kuruvilla** [comment]
thanks a million man it works.
my code $this->api->delete('wp-json/wp/v2/posts/'.$id.'/categories/1?force=true');

**Comment by JoshWobbles** [comment]
Why does it seem this bug still exists for query string access? The following in c# returns 404
`string assignCatResp = client.DownloadString("https://beta.inputmapper.com/wp-json/wp/v2/posts/" +id+ "/categories/63");`
