### ISSUE TITLE
Get Users where username 

### ISSUE THREAD

**Issue by hefejeff** [WP-API/WP-API#1863]
I am using version 1 right now and have a question if someone would be so kind.... I need to set up a service where I query users filtering users who's username starts with the letter "a".  Can't figure out the filters for this.

**Comment by danielbachhuber** [comment]
Hi @hefejeff, WP-API v1.x is deprecated, and only supported for critical security issues.

**Comment by hefejeff** [comment]
Hi @danielbachhuber, I understand this but I am stuck with V1 until we can convert in a few months after our app launches in February.  I discussed this with @rachelbaker at WCUS and understand that the transition is not going to be quick and easy.  So, I hoped that someone might have a simple answer even if the answer is that it is not possible with V1
