### ISSUE TITLE
Don't assign "Uncategorized" default category to new posts

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1868]
`wp_insert_post()` has this weird behavior where it will always assign a default category to a post. This is weird behavior that we should disable by default in the REST API.

From https://github.com/WP-API/WP-API/issues/1859#issuecomment-164688748

**Comment by rmccue** [comment]
:-1: Posts in WP always need a category; if you want to change it, you should add the category then remove the default one.

**Comment by BrekiTomasson** [comment]
Why can't you set a category during post creation? If none is selected, it could assign it to the default category, but it feels weird to be able to select last modified dates when you can't select something as basic as a category.

**Comment by joehoyle** [comment]
@BrekiTomasson because categories are not post of the post object, the relations are current access and modified separately, at `/posts/{id}/terms/{taxonomy}`. However, there may be argument for moving those relations to the post object it's self, so far we have decided that due to potentially large amounts of relations and complexity there, having them as a separate resource is easier to handle

**Comment by BrekiTomasson** [comment]
@joehoyle So the recommended procedure (at least for now) is to create the post, assign a category, then unassign the default category, as three separate steps?

**Comment by joehoyle** [comment]
@BrekiTomasson correct. I understand that's not idea right now - hence one reason why this ticket exists. I'd expect this to be easier in a later beta.

**Comment by BrekiTomasson** [comment]
@joehoyle Thanks for the update! I'll keep an eye on this ticket then. :+1:

**Comment by BrekiTomasson** [comment]
Weird. I'm not able to access the posts/{id}/terms/{taxonomy} call. the posts/{id} works fine, but anything like /terms/category or /terms/categories after that just 404:s me.

**Comment by cvyz** [comment]
I created a post, added a category to that post, and finally trying to remove the Uncategorizedcategory Uncategorized results to a 403 error.
I'm using a delete method, sending the access_token to /wp-json/wp/v2/posts/2859/categories/1
@joehoyle what is the right way of removing a category from a post, as I can't figure it out following the api documentation.

**Comment by BrekiTomasson** [comment]
@cvyz Have you tried ?force=true at the end of the URL you're calling?

**Comment by cvyz** [comment]
@BrekiTomasson still get a 403 error. I'm using chrome POSTMAN to test before implementing this to my symfony code.

**Comment by BrekiTomasson** [comment]
@cvyz That's weird. It's working fine on my end; I wrote a PHP function like so:

    function removeFromWP($endpoint) {
        include('config.php');

        $ch = curl_init($endpoint);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_USERPWD, $username . ":" . $password);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array(
            'Content-Type: application/json',
            )
        );

        return json_decode(curl_exec($ch));
    }

Which I then call by using the target endpoint, in this case:

    $endpoint = 'http://csicon.fm/wp-json/wp/v2/posts/' . $postData->id . '/categories/' . '214?force=true';
    removeFromWP($endpoint);

(Category 214 is the default category in my system)

**Comment by cvyz** [comment]
@BrekiTomasson thanx for your time. I tried both oauth2, and basic authentication to delete the category but still get a 403 error. Guess I'll have to wait for the Uncategorized bug to get fixed.

**Comment by BrekiTomasson** [comment]
@cvyz Just had a thought - are you trying to delete the category using its term_id or it's term_taxonomy_id ? I seem to remember different versions of the WP API requiring different IDs.

**Comment by cvyz** [comment]
@BrekiTomasson In my WP setup, Uncategorized had both term_id and term_taxonomy_id set to 1.
So, I guess it's still a dead end for me. Thanx for the thought.

**Comment by danielbachhuber** [comment]
As of #2063, it's much easier to just set a different category on post creation. We can punt on this for now:

> `wp_insert_post()` has this weird behavior where it will always assign a default category to a post. This is weird behavior that we should disable by default in the REST API.
