### ISSUE TITLE
Don't return products that are flagged as hidden in Woocommerce

### ISSUE THREAD

**Issue by enricodeleo** [WP-API/WP-API#1871]
Hi!
I'm using wp-rest api with Woocommerce (I know woocommerce has its own rest apis but I need to expose my endpoints to clients and extend with custom logic... wp rest api better fits these needs!).

Everything works correctly so far, except that when I ask a collection of products ( via /wp/v2/product) all products are returned even if they are flagged as hidden (the option don't show in catalogue and search).

Anyone knows if it's possible to reflect the same behavior of the frontend even on rest apis?

Thanks!

**Comment by joehoyle** [comment]
@enricodeleo you'd probably want to either implement your own `WP_REST_Controller` subclass for the Products post type so you could control the query directly. However, if you didn't want to go that far, you could filter the `rest_post_query` filter to adjust the WP_Query params. I assume Woocommerce also has the ability to filter the WP_Query to handle things like hidden products, so it may just be a case of plugging the two together.
