### ISSUE TITLE
Respect show_avatars option in user response

### ISSUE THREAD

**Issue by tharsheblows** [WP-API/WP-API#1872]
In WP_REST_Users_Controller->prepare_item_for_response would it be ok to make $data['avatar_urls'] dependent on the show_avatars option chosen in the Discussions settings?

**Comment by joehoyle** [comment]
I don't think this makes sense, the Discussion settings is a visual thing for show avatars, and we'd be better off keeping the information in the user object.

However, once we add the settings / options endpoint this value would be sent in there so you front end could chose to render the avatar based off that.

**Comment by tharsheblows** [comment]
If a site owner thinks they've disabled avatars for whatever reason (my concern is privacy), they shouldn't be publicly available. Although looking at it, would it be ok to make the embed context of avatar_urls conditional on the show_avatars option? 

I do realise it's possible to filter them out but think the general assumption is that if avatars are disabled through the settings, they're not publicly accessible.

It's also entirely possible I'm misreading the embed context! I'm taking it as "data which is publicly available and of the sort one would use when embedding bits and bobs on other sites" :)

**Comment by joehoyle** [comment]
Given the default WordPress avatar settings, I'm not convinced there is a privacy issue there, as they are just generated from known information already. However, I think it's worth discussion. I'm not sure the admin really portrays it as a user data/privacy type thing, it's more about the visual display of the comments list.

You have embed mostly right, but it's not necessarily just for public display, for example you can fetch a Private Post in the embed context, which only people with permission will be able to view.

**Comment by tharsheblows** [comment]
Oh no, sorry, I didn't mean to have a discussion about whether avatars are bad or good, just that if I decide I don't want them to be shown for whatever reason, they shouldn't be available for others to use. 

I was surprised that they are available in the public user response even after unticking the show avatars box. In the themes I do for clients, I simply don't include any code to show avatars if it's not in the design --  I assume this is what everyone else does, too! So I've never used that box to toggle visual display but did assume that I could use it to remove avatar_url from the users response. I can't think of a single case where a client doesn't have avatars on the site but would want them or even not hate them in embedded content. Users on a community site I developed would find it particularly unnerving if an avatar they never knew was associated with that account suddenly showed up somewhere else with their forum post. 

I know there is some concern about data being unexpectedly public with the API and that you're aware of it and conscious of avoiding those situations - respecting the site owner's choice for avatar visibility is something similar.

(Now that I'm thinking about it, I'm going to filter it so that it returns the site icon instead. That way there will be something there for anyone who asks for it. That might be a good alternative. :) )

**Comment by joehoyle** [comment]
Right, the main concern around removing it is client rely on that field existing and such crash when the field is not present.

One thing to compare this too would be XML RPC and the RSS feeds, I haven't checked but I'd be interested to see if either of these checks this option. Though, on a quick look it doesn't appear XML RPC give you much.

**Comment by tharsheblows** [comment]
Neither of those include avatar urls even with the show avatars box ticked.

You could fallback to the site icon then WP logo for the image. If you don't need the exact image sizes, you could do what embeds from the new oEmbed feature do eg: `esc_url( get_site_icon_url( 24, admin_url( 'images/w-logo-blue.png' ) ) )` for each of the sizes. 

If the images need to be the exact sizes, you could re-run the site icon crops on upgrade or whatever so you're sure you get them. Do they need to be the exact sizes or is it as long as there's an image url for each of the standard and any additional sizes that it's ok? I don't know how people are using that.

Thanks btw, for discussing and also for the wp api. I haven't made anything big but it's super fun to use.

**Comment by rmccue** [comment]
I think I'd expect that if I disable avatars, they'd stop being available everywhere. Depends on what the wording for this setting is as to the site owner's expectations though.

If they are disabled, I'd rather we return `null` or exclude the keys though, rather than using a default image.

**Comment by tharsheblows** [comment]
Returning `null` makes a lot more sense than returning an image as it'd be easier to tell if avatar_url is a user avatar or not. Then the api consumer could make an informed decision on what to show there. (Is there a site info endpoint with the site icon, title, tagline and that sort of thing? I realise that's possibly a Very Stupid Question™ )

The wording on the settings page is:
>An avatar is an image that follows you from weblog to weblog appearing beside your name when you comment on avatar enabled sites. Here you can enable the display of avatars for people who comment on your site.

It did surprise me that it was showing up in the user response.

**Comment by danielbachhuber** [comment]
To wrap this issue up, let's do a few things:
- [ ] Conditionally add `avatar` to the User schema based on the setting
- [ ] Only add `avatar` to the response object if present in the schema.
- [ ] Add a test to make sure the `avatar` is present by default, and not included when `show_avatars` is disabled.

**Comment by tharsheblows** [comment]
Thank you! I can do this, although perhaps not today. Definitely tomorrow though.

**Comment by danielbachhuber** [comment]
:hammer:
