### ISSUE TITLE
Post meta field POST/add array

### ISSUE THREAD

**Issue by akuljana** [WP-API/WP-API#1873]
Is it possible to add multiple values in post meta field? Using this example (http://v2.wp-api.org/extending/modifying/#examples) I added post meta field, which is array, and using Postman I tried to post multiple values to that field, but only one value is added.

**Comment by joehoyle** [comment]
@akuljana are you trying to set a single meta key to have a value which is an array, or multiple meta keys with the same name, with 1 value each?

We don't currently support the format - meta values can only be scaler values, not arrays or objects.

**Comment by akuljana** [comment]
Second, multiple meta keys with the same name, with 1 value each. How to set that?

**Comment by joehoyle** [comment]
@akuljana ok that should work, if you are having issues with that, can you send an example request you are making. This should essentially just require a new `POST /posts/<id>/meta` with the same `key` value for each POST request to add multiple.
