### ISSUE TITLE
terms/category throwing a 404. 

### ISSUE THREAD

**Issue by beatelite** [WP-API/WP-API#1874]
If I do GET wp/v2/terms/category, e.g. http://demo.wp-api.org/wp-json/wp/v2/terms/category
I get a 404 rest route not found message. 

This worked before on beta4 but when I switched to the latest, it seems to have broke on my site ( and lt looks like the demo site  too)

What am I missing here?

**Comment by joehoyle** [comment]
@beatelite categories have now moved to `/wp/v2/categories`, see `BREAKING CHANGES` on https://github.com/WP-API/WP-API/releases/tag/2.0-beta9
