### ISSUE TITLE
WP_Error returned "text/html" content

### ISSUE THREAD

**Issue by phamdacloc** [WP-API/WP-API#1875]
When defining a new REST endpoint, my function returns WP_Error on certain error conditions. However, the client (using AFNetworking) is receiving the response in `"text/html"` contents instead of the expected `"application/json"` or `"text/json"`. The http status code (404) was received correctly, but the error code is not shown either.  Here is PHP code:

```PHP
add_action( 'rest_api_init', function () {
            register_rest_route( 'bbpress_ext/v1', '/users/new', array(
                'methods' => 'POST',
                'callback' => 'my_awesome_func'
            ) );
        } );

function my_awesome_func( $data ) {
    $posts = get_posts( array(
        'author' => $data['id'],
    ) );

    if ( empty( $posts ) ) {
        return new WP_Error( 'awesome_no_author', 'Invalid author', array( 'status' => 404 ) );
    }

    return $posts[0]->post_title;
}
``` 

Response dump from iOS Client using AFNetworking:

```PHP
Printing description of response:
<NSHTTPURLResponse: 0x7fca35cea7b0> { URL: http://example.com/wp-json/bbpress_ext/v1/users/new } { status code: 404, headers {
    "Access-Control-Allow-Headers" = Authorization;
    "Access-Control-Expose-Headers" = "X-WP-Total, X-WP-TotalPages";
    Allow = POST;
    "Content-Length" = 1245;
    "Content-Type" = "text/html";
    Date = "Sat, 19 Dec 2015 02:51:27 GMT";
    Server = "Microsoft-IIS/8.0";
    "X-Content-Type-Options" = nosniff;
    "X-Powered-By" = "ASP.NET";
} }
```

I'm running WP REST API Version 2.0-beta8

**Comment by joehoyle** [comment]
@phamdacloc I imagine this is something to do with your server configuration sending it's own error page / content types for status codes > 399. Could you let me know what the response body is? is it the JSON blob, or something else?

**Comment by phamdacloc** [comment]
@joehoyle In the example above, I returned 404 statusCode with the following `header` and `body`

Header:
```PHP
Access-Control-Allow-Credentials → true
Access-Control-Allow-Headers → Authorization
Access-Control-Allow-Methods → POST, GET, OPTIONS, PUT, DELETE
Access-Control-Allow-Origin →
Access-Control-Expose-Headers → X-WP-Total, X-WP-TotalPages
Allow → POST
Content-Length → 1245
Content-Type → text/html
Date → Sun, 20 Dec 2015 17:19:24 GMT
Server → Microsoft-IIS/8.0
X-Content-Type-Options → nosniff
X-Powered-By → ASP.NET
```

Body:
```PHP
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
        <title>404 - File or directory not found.</title>
        <style type="text/css">
            <!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
        </style>
    </head>
    <body>
        <div id="header">
            <h1>Server Error</h1>
        </div>
        <div id="content">
            <div class="content-container">
                <fieldset>
                    <h2>404 - File or directory not found.</h2>
                    <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
                </fieldset>
            </div>
        </div>
    </body>
</html>
```

**Comment by joehoyle** [comment]
Ah ok, so this error page is not being generated by the wp-api or WordPress, you should look into yoru server's configuration around sending the backend output on error responses.

**Comment by phamdacloc** [comment]
@joehoyle Can you please help narrow down where/how exactly I can make this change on the server? I looked at my server configuration using ASP.NET and saw the `Error` tab but I think tab is meant to redirect user to a more error friendly page when the user encounters problem.

<img width="1008" alt="errors" src="https://cloud.githubusercontent.com/assets/6949354/11919146/4aa66d46-a77c-11e5-895d-caef29bd1eb0.png">

**Comment by joehoyle** [comment]
@phamdacloc I'm not at all familiar with the ASP.net stack and how to configure it - this repo probably isn't the best place to get assistance with that - however a quick google shows things such as http://stackoverflow.com/questions/434272/iis7-overrides-customerrors-when-setting-response-statuscode and http://stackoverflow.com/questions/19467919/internal-error-500-iis8-error-in-server-but-does-not-show-error-details-on-web which seems to be in the right ballpark for what you'd want.

**Comment by phamdacloc** [comment]
Thank you. I'll look into those.
