### ISSUE TITLE
Adding enclosures to posts

### ISSUE THREAD

**Issue by BrekiTomasson** [WP-API/WP-API#1877]
I was able to assign enclosures to posts in the 'old' WP API using (PHP) code like this when I built the array that i pushed through JSON into WP API:

    'meta' => array(
        array(
            'key'   => 'enclosure',
            'value' => $submittedMeta['enclosure']['enclosureURL']
        )
    )

But this doesn't seem to be working in v2. What changes do I need to make? Can't seem to find how to make it work at the moment.

**Comment by joehoyle** [comment]
@BrekiTomasson post meta is now accessed via it's own endpoint, see http://v2.wp-api.org/reference/posts/meta.html

Let me know if you have any issues with that.
