### ISSUE TITLE
Create a Linux Slack channel thank you

### ISSUE THREAD

**Issue by AlbertGuadan** [WP-API/WP-API#1883]
Hi Team,

I have no experience developing in a sandbox  IDE.
My only developer experience has been in Linux,  and in the
Cloud and currently running PHP 5.4

I have no experience with local sand boxes.  

https://developer.wordpress.org/themes/getting-started/setting-up-a-development-environment/

I need WP-Linux support and will support a Linux learning curve for others.

I wish to progress in the API and JavaScript in this way.

Supporting Linux: I do feel confidant some of the community can sure use Linux support.

Thank you
Team

**Comment by rmccue** [comment]
I think you want [general WordPress support](https://wordpress.org/support); this issue tracker is for the REST API feature plugin only.
