### ISSUE TITLE
Filter for category__not_in doesn't work

### ISSUE THREAD

**Issue by hrsetyono** [WP-API/WP-API#1884]
For example `mysite.com/wp-json/wp/v2/posts?filter[category__not_in]=10` will ignores the filter and show all latest posts.

Is there a way to exclude category from the API call?

**Comment by danielbachhuber** [comment]
`category__not_in` is a private query variable, meaning it's not accessible to logged-out users.

You can make it a public query var by filtering `query_vars`

**Comment by hrsetyono** [comment]
Thanks for the prompt reply. But I'm already logged in as admin and when I go to the URL, it still only showed unfiltered latest post.

Can you help me give an example about "filtering query_vars"? I can't find any info on Google nor the [documentation](http://v2.wp-api.org/extending/modifying/).

Thanks a lot :)

**Comment by joehoyle** [comment]
@hrsetyono you would need to add custom PHP code via a custom plugin or theme to enabled the use of `category__not_in`. If you are not able to do that, then there's no way to use `category__not_in` currently. This probably isn't the best repository for help with general WordPress development, if you are not familiar with writing WordPress PHP code to achieve this.

**Comment by hrsetyono** [comment]
@joehoyle Thanks for the hint. I thought "filtering query_vars" is like `/wp-json/wp/v2/posts?filter[query_vars]=something`.

Since I know it's code related, I managed to found the answer from google.

    add_filter("query_vars", function($query_vars) {
      $query_vars[] = "category__not_in";
      return $query_vars;
    });

Cheers :)

**Comment by danielbachhuber** [comment]
> Thanks for the prompt reply. But I'm already logged in as admin and when I go to the URL, it still only showed unfiltered latest post.

If you don't include a nonce in the request, it will be treated as logged out.
