### ISSUE TITLE
Include custom field in columns to search with filter[s]

### ISSUE THREAD

**Issue by jasonhjohnson** [WP-API/WP-API#1887]
Hi,

I have a custom post type 'documents' that I'd like to search using `filter[s]=expression`. By default, I think the search just hits the usual Wordpress fields (title, excerpt, content). How can I include my additional custom FIELD in the columns that are searched?

Thanks,
Jason

**Comment by danielbachhuber** [comment]
> How can I include my additional custom FIELD in the columns that are searched?

You'll need to write some underlying PHP code to search against the custom field, which is outside the scope of support for WP-API. Also, given the potential performance impact of these queries, you should likely use Elasticsearch, Solr or some other search backend to perform the queries.

**Comment by jasonhjohnson** [comment]
Is there perhaps a way to have my custom field copied into the excerpt or content field for a specific post type so that I don't have to alter the search at all?

**Comment by danielbachhuber** [comment]
> Is there perhaps a way to have my custom field copied into the excerpt or content field for a specific post type so that I don't have to alter the search at all?

That could work but, again, it's outside the scope of support in this Github issue tracker.

**Comment by Shelob9** [comment]
My SearchWP add-on allows for querying by custom fields. The latest version
on GitHub allows it to work without SearchWP installed.
https://github.com/CalderaWP/searchwp-api-route

**Comment by jasonhjohnson** [comment]
@Shelob9 Thanks. I dropped the downloaded code from github into the plugins folder and activated, but, when I try to run a query I get the following: http://take.ms/IsVFF. Any ideas?
