### ISSUE TITLE
Filter results by tag?

### ISSUE THREAD

**Issue by jasonhjohnson** [WP-API/WP-API#1890]
Hi,

How would I limit my search results to those posts that have a particular tag?

Thanks,
Jason

**Comment by danielbachhuber** [comment]
@jasonhjohnson This issue tracker isn't intended as a general-use support forum. Can you share what request you've already tried, and the result you get?

**Comment by jasonhjohnson** [comment]
@danielbachhuber Sorry about that. 

The short is, I don't know what to try to limit to only a particular tag.

Here's the base query I'm using: 
`wp-json/wp/v2/documents?filter[category_name]=manuals`

So that's giving me items from my custom post type of 'documents' that are attached to the 'manuals ' category. 

Each document may also be associated with one or more tags, so, I'm trying to further limit the results by tag(s).

-J

**Comment by danielbachhuber** [comment]
Taxonomy queries will be explored in further depth with #924. For now, your use case may not be fully supported.
