### ISSUE TITLE
Inconsistent publicness checks between types and taxonomies

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1895]
Taxonomies use `show_in_rest` to determine whether the taxonomy is accessible from `/wp/v2/taxonomies`

Types use `public` to determine whether the post type is accessible from `/wp/v2/types`.

I'd _think_ we should use `show_in_rest` to determine whether a type is exposed. `public` was introduced in fb4f59b5a4ad79e112b4770b547ca915b0d516e5

Discovered in #1894

**Comment by rmccue** [comment]
👍
