### ISSUE TITLE
How can I disable the auto-generated “Read More” text in excerpts?

### ISSUE THREAD

**Issue by brandondurham** [WP-API/WP-API#1897]
Working with a site where about 40% of the posts (hundreds) don't have an excerpt so it's auto-generated. The auto-generated versions include a “Continue reading …” link that I'd like to remove.

**Comment by rmccue** [comment]
This sounds like a plugin is adding the link automatically. We use essentially the equivalent of `the_excerpt()`, which internally runs the `the_excerpt` and `get_the_excerpt` filters; check if there's a plugin adding the links on one of these links.
