### ISSUE TITLE
POST from one multisite subsite to another 

### ISSUE THREAD

**Issue by beatelite** [WP-API/WP-API#1898]
I've looked but can't seem to track down any info on this. 

I am trying to POST as user from one subsite to the posts endpoint for another subsite. I'm a user of both sites but I keep getting Request header field X-WP-Nonce is not allowed by Access-Control-Allow-Headers in preflight response."

I do have the following in my .htaccess but no luck:

```
Header set Access-Control-Allow-Origin "*"
Header add Access-Control-Allow-Methods: "GET,POST,OPTIONS,DELETE,PUT"
```
I have a nonce localized for my app and thought it would work since I'm logged in to both sites. 

Any suggestions?

**Comment by beatelite** [comment]
after some digging, it looks like maybe just because I'm on a subsite on a multisite install, doesn't mean I get to stay authenticated on another site (even though I'm a member of that site) and therefore passing my nonce via the header fails the request. 

Does that sound like what's going on here?

**Comment by rmccue** [comment]
You can't use cookie authentication with nonces for cross-site communication, even when those sites happen to be on the same install of WP. This is an intentional limitation of the way that we work with cross-origin requests.
