### ISSUE TITLE
How to force HTTPS

### ISSUE THREAD

**Issue by kdpuvvadi** [WP-API/WP-API#1899]
I've recently moved a wordpress from http to https and changed the address in settings. and the problem here is i want rest apis to be open only in https but it is working with both, How can i change that?

**Comment by danielbachhuber** [comment]
Couple of options:

1. You could return an API error for any requests made over http, indicating requests are only fulfilled over https.
1. You could force a redirect to the https version of the API for any requests made over http. However, the client making the request would need to properly follow the redirect.
