### ISSUE TITLE
Is there one api for get posts from one post id and get count?

### ISSUE THREAD

**Issue by oldcwj** [WP-API/WP-API#1904]
I know one api is filter[paged]=2,then return the paged=2 posts,
but how can i get posts from one post id and get simple 10 posts?

**Comment by danielbachhuber** [comment]
> but how can i get posts from one post id and get simple 10 posts?

Sorry, I'm not sure I follow. Can you explain in a bit more detail?

**Comment by oldcwj** [comment]
Sorry, I don't have a clear explanation.
For example, I have 100 posts, I would like to get from the beginning of the twelfth, after the 19 posts, I do not know how to do?

**Comment by danielbachhuber** [comment]
> For example, I have 100 posts, I would like to get from the beginning of the twelfth, after the 19 posts, I do not know how to do?

You'd need to use the `offset` parameter, which isn't currently supported in the API: https://github.com/WP-API/WP-API/pull/1471#issuecomment-162622406
