### ISSUE TITLE
Reconsider schema transformation methods on WP_REST_Controller

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1911]
The goal of `WP_REST_Controller` is two-fold:

1. Offer a consistent pattern for CRUD operations on WordPress Resources (e.g. `get_items()`, `create_item()`, `get_item()`, `update_item()`, and `delete_item()`).
1. Provide a way for a WordPress Resource to self-document its schema and how it can be queried.

Since we've introduced the class, though, it's spawned a number of additional methods including:

* `filter_response_by_context()` - Filter a response based on the context defined in the schema.
* `get_public_item_schema()` - Get the item's schema for display / public consumption purposes.
* `add_additional_fields_to_object()` - Add the values from additional fields to a data object.
* `update_additional_fields_for_object()` - Update the values of additional fields added to a data object.
* `add_additional_fields_schema()` - Add the schema from additional fields to an schema array.
* `get_additional_fields()` - Get all the registered additional fields for a given object-type.
* `get_endpoint_args_for_item_schema()` - Get an array of endpoint arguments from the item schema for the controller.
* `validate_schema_property()` - Validate a parameter value that's based on a property from the item schema.
* `sanitize_schema_property()` - Sanitize a parameter value that's based on a property from the item schema.

While these methods do _relate_ to the class, I think we need to move them elsewhere for a more sane abstraction.

Related:

* #1796 because we want to validate query params for collections.
* #1905 because we need to decide in what way schemas should be filterable.
* #1135 is another outstanding issue on `get_endpoint_args_for_item_schema()`

**Comment by wpsmith** [comment]
Related: #1914

**Comment by danielbachhuber** [comment]
@joehoyle and I chatted about this over voice today. Ideally, we'll be abstracting things out a bit, and hopefully landing the changes in beta11

**Comment by kadamwhite** [comment]
@danielbachhuber @joehoyle Can either of you possibly articulate what the action here is?

**Comment by kadamwhite** [comment]
Per Daniel, action is to remove—many of these methods need to be removed into a schema transformer class.

DISCUSS.

**Comment by kadamwhite** [comment]
As [discussed in slack](https://wordpress.slack.com/archives/core-restapi/p1476714313007699) during 2016-10-17 API team meeting, closing this out -- it's not a bad concept but this :ship: has sailed.
