### ISSUE TITLE
Have a Utilities Class

### ISSUE THREAD

**Issue by wpsmith** [WP-API/WP-API#1914]
There is redundant code within the various controller implementations. One example is between the Comments controller and Users controller. There is this code (updated from PR #1913):

```
public function get_item_schema() {
	$avatar_properties = array();

	$avatar_sizes = rest_get_avatar_sizes();
	foreach ( $avatar_sizes as $size ) {
		$avatar_properties[ $size ] = array(
			'description' => 'Avatar URL with image size of ' . $size . ' pixels.',
			'type'        => 'string',
			'format'      => 'uri',
			'context'     => array( 'embed', 'view', 'edit' ),
		);
	}
```

**Comment by danielbachhuber** [comment]
> Have a Utilities Class

Do you have a proposed design for this class? How do we help keep it from becoming simply a grab bag of random, unrelated methods?

**Comment by danielbachhuber** [comment]
> There is redundant code within the various controller implementations.

Generally, I think we'll try to solve this piecemeal as we identify the instances and think of reasonable abstractions for them.

> One example is between the Comments controller and Users controller. There is this code

I think this instance of duplication is fine. I'm not sure of an elegant abstraction we could use.
