### ISSUE TITLE
Reconsider Callbacks

### ISSUE THREAD

**Issue by wpsmith** [WP-API/WP-API#1915]
In a slack conversation with @danielbachhuber: I thought we could add this issue to #1911, I thought it best to leave #1911 more generic and keep this issue pertains to callbacks only.

There are the following callbacks implemented:
* **`get_callback`** & **`update_callback`** is used for fields (cf. `register_rest_field`, `WP_REST_Controller::update_additional_fields_for_object`, `WP_REST_Controller::add_additional_fields_to_object`).
* **`permission_callback`** is used for the response as a whole (cf. `rest_send_allow_header` in rest-api.php) though I would like to see this at the property level as well.
* **`sanitize_callback`** is used to sanitize the property's value.
* **`validate_callback`** is used for validating/verifying that a property though the `WP_REST_Posts_Controller` uses it to check permissions for the status property. As a result, it appears to me that there is some cross-pollination or double work being done between sanitizing and validating, specifically the implementation of `WP_REST_Controller::validate_schema_property` and `WP_REST_Controller::sanitize_schema_property` in `WP_REST_Controller::get_endpoint_args_for_item_schema`. As a core implementation, `get_endpoint_args_for_item_schema` is called on all core REST calls. And by example, it encourages users to do the same for their own implementations.

Personally, I would like to see: 
* **`get_callback`** & **`update_callback`** usable on singular properties. By default, they would be `null`. But if a property schema contains it in `args_options`, it uses those callbacks to perform those particular REST actions (READ/EDIT). 
* **`permission_callback`** is used to check for permissions (for whole response AND a property's access, e.g., the status property on the posts controller) though this could be merged with the `validate_callback`. However, my problem with that is consistency. Since `permission_callback` is used for the whole response, why not use it for the property as well?
* **`sanitize_callback`** is used to sanitize the property's value. 
* **`validate_callback`** is used for validating/verifying that a property matches the declared schema.

NOTE: All three, `permission_callback`, `sanitize_callback` and `validate_callback` can be combined and used singularly without the implementation of the other. As noted by @danielbachhuber "you don't necessarily need to use `sanitize_callback` if you have an acceptable `validate_callback`," and "similarly, don't need to have a `validate_callback` if your `sanitize_callback` is acceptable for your needs." To me, this will cause confusion because `WP_REST_Controller::get_endpoint_args_for_item_schema` implements both `validate_callback` and `sanitize_callback`. (See also #1912). One argument for having all three is a clear separation of duties. Here is a recommended governance for the three property callbacks:
1. **`permission_callback`** => Permissions/Role: OAuth focuses here.
2. **`sanitize_callback`** => Cleanse for database and from database. This is a *sine qua non* for all data (via update REST calls) and WP VIP.
3. **`validate_callback`** => Validate that value received from user/database matches the schema type, which may or may not be declared (e.g., `null`) or even declared as a unique type.

So, really, if we are going to have a variety of `*_callback` options, then I would like to see a standardization/governance declared on the various purposes of those callbacks.

**Comment by kadamwhite** [comment]
This needs an owner

**Comment by kadamwhite** [comment]
And possibly feedback from @WP-API/amigos

**Comment by kadamwhite** [comment]
It's possible this is mixing up a few things; it might be more relevant to infrastructure code that's already committed to core, around register_rest_route. There's no sanitize callback or validate on the rest controller to my knowledge.

**Comment by rmccue** [comment]
> As a result, it appears to me that there is some cross-pollination or double work being done between sanitizing and validating

The status quo thinking on this is mostly eliminating the use of validation in favour of just the sanitization callback, per #2695.

**Comment by rmccue** [comment]
I think we're mostly settled here apart from the sanitization, and there's a pretty clear distinction between other types of callbacks. Closing out.
