### ISSUE TITLE
403 when deleting a category from a post

### ISSUE THREAD

**Issue by mjacobsen4DFM** [WP-API/WP-API#1916]
Is delete implemented for categories on a multisite domain?
I am trying to execute delete against a URL like this:
https://example.com/mysite/wp-json/wp/v2/posts/577622/terms/category/1
I have tried basic authentication and OAuth1 access. Both code and postman return:
403 Forbidden, "You don't have permission to access /mysite/wp-json/wp/v2/posts/577622/terms/category/1"
The same credentials (basic and oauth) can create and modify posts. So, it is not a permissions problem. The basic auth user is a site administrator. Otherwise I would investigate the user permission. Since I have tried 4 different methods for the delete, I have decided to post here; I appreciate any assistance. Thank you.

**Comment by danielbachhuber** [comment]
We can discuss this in your support forum thread: https://wordpress.org/support/topic/403-when-deleting-a-category-from-a-post?replies=1#post-7823976
