### ISSUE TITLE
PHP Fatal error wp_json_encode()

### ISSUE THREAD

**Issue by httpways** [WP-API/WP-API#1919]
Hi,

I have the following error in my apache server logs:
PHP Fatal error: Call to undefined function wp_json_encode() in wp-content/plugins/rest-api/core/wp-includes/rest-api/class-wp-rest-server.php on line 386

Thanks for your help

**Comment by danielbachhuber** [comment]
`wp_json_encode()` was included in WordPress 4.1, so you must be running an older version of WordPress.

WP-API Version 2.0-beta9 requires WordPress 4.3 or higher. beta10 will require WordPress 4.4
