### ISSUE TITLE
character classes in register_rest_route regexp don't honor letter case

### ISSUE THREAD

**Issue by stratboy** [WP-API/WP-API#1920]
Hi! In register_rest_route() I've just found out that using a regexp like:

`(?P<product_slug>([^A-Z ,.;\/]+))`

Will not match because of the A-Z portion: in fact, A-Z will negate also a-z, or in other words, will be interpreted like a-zA-Z.

**Comment by danielbachhuber** [comment]
Hm. I'm not sure I can reproduce:

```
salty-wordpress ➜  wordpress-develop.dev  wp shell
wp> preg_match( '#(?P<product_slug>([^A-Z ,.;\/]+))#', 'foo', $matches );
int(1)
wp> $matches
array(4) {
  [0]=>
  string(3) "foo"
  ["product_slug"]=>
  string(3) "foo"
  [1]=>
  string(3) "foo"
  [2]=>
  string(3) "foo"
}
wp> preg_match( '#(?P<product_slug>([^A-Z ,.;\/]+))#', 'FOO', $matches );
int(0)
wp> $matches
array(0) {
}
```

Can you provide a test case?

By the way, this bug report would be better suited for [Core Trac](https://core.trac.wordpress.org/), as `register_rest_route()` is a part of the infrastructure committed to WordPress 4.4 and is no tracked in this repo.

**Comment by stratboy** [comment]
Hi, thank you for your answer. I cannot link to a test case, but my code is quite bare bones:

```php
register_rest_route('mynamespace/v1', '/(?P<lang>' . $lang . ')/product/(?P<product_slug>([^A-Z ,.;\/]+))?$', array(
    'methods' => 'GET'
    ,'callback' => 'get_products_data'
    )//end options array
);
```
Where $lang will resolve to a lang slug. So it should match something like:

```
http://example.com/wp-json/mynamespace/v1/it/product/bio-2
```

But it won't, because ^A-Z will discard 'bio-2' (it shouldn't). So for now I'm using a more generic `[^ ,.;\/]+`
I'll see to open a ticket also in track, but I can see register_rest_route() even in rest-api.php in your plugin :p 

Anyway, thank you for yout attention.

**Comment by stratboy** [comment]
Why did you closed?

**Comment by danielbachhuber** [comment]
> `register_rest_route()` is a part of the infrastructure committed to WordPress 4.4 and is no tracked in this repo.
