### ISSUE TITLE
Temporarly disable authentication

### ISSUE THREAD

**Issue by bobdenardd** [WP-API/WP-API#1924]
Hello everybody. I was wondering if there was an easy way to temporarly disable all authentication in order to create posts using the rest api without having to authenticate. I fullsy do understand the security concerns, this is only for testing purposes on a local environment.
I tried using the basic authentication for days, but still didn't get it to work, and now just want something simple, like lines to comment out in the plugin code, just to be able to test some posting features.
Thanks in advance

**Comment by kadamwhite** [comment]
I'm not familiar with how one could disable authentication, but I'm curious: what sort of environment is the application from which you are accessing the API? (PHP, JavaScript in the browser like Backbone, JS in Node on the server, etc?) We might be able to point you towards some resources for getting basic auth to work; that's definitely the easiest approach

**Comment by danielbachhuber** [comment]
> I was wondering if there was an easy way to temporarly disable all authentication in order to create posts using the rest api without having to authenticate.

You could force a specific user to be logged in for each user:

```
/*
 * Automagically authorize every request
 * INSECURE! DANGER! ONLY USE IN LOCAL ENVIRONMENT.
 */
add_filter( 'rest_authentication_errors', function(){
	wp_set_current_user( 1 ); // replace with the ID of a WP user with the authorization you want
}, 101 );
```

**Comment by daninmanchester** [comment]
this is something else that would be useful as part of an admin page, the ability to set security on the various endpoints. require authorisation (yes/no) and supported auth methods, verbs, etc.

hacks for local code that then have to be removed for production are a very nasty security risk. effective configuration management is a much more robust and secure way to manage it.

**Comment by joehoyle** [comment]
I'm a very big :-1: on an admin page for managing this type of stuff. The above example should be loaded in PHP in a responsible manner that means it's not loaded in producted, by whatever means you wish. @daninmanchester I don't understand your terminology of "hack" - no one ever suggested changing the core REST api code code or WordPress core.

**Comment by daninmanchester** [comment]
hack means messing about with code between dev, test and prod rather than dealing in proper configuration management.

**Comment by danielbachhuber** [comment]
@daninmanchester you're welcome to write and publish your own plugin for managing this through the WordPress admin. It's not something that will ever be added to the core plugin.

**Comment by daninmanchester** [comment]
I don't fancy developing a plugin to handle this kind of thing, there is too much scope for security problems. I'm wondering if something like Azure API manager is the way to go. It would probably give me the capability i need to mange security, roles, rates, etc. in a more robust manner.

**Comment by cmawhorter** [comment]
For the future googlers of the world that are like me.

I have no idea the best place to put the filter but putting it in `wp-includes/plugin.php` at the end of the file worked for me.

**Comment by kadamwhite** [comment]
@cmawhorter Leaving aside that given the security implications this still isn't recommended, even on a temporary basis, you should always avoid editing WordPress core files directly. If you _must_ make this change, you can put the snippet in a "must-use plugin" file such as
```
wp-content/mu-plugins/disable-all-authentication-even-though-this-is-unwise.php
```

**Comment by cmawhorter** [comment]
good to know about mu-plugins.

security is a non-issue in my case -- internal server with no public access, and only temporary while moving content.
