### ISSUE TITLE
Add new post

### ISSUE THREAD

**Issue by BeetleTN** [WP-API/WP-API#1925]
Can I add new post in my blog ? if yes how ?

**Comment by kadamwhite** [comment]
You can add a post by sending the content you wish to add to the API, as described in the "Create a Post" section of this documentation: http://v2.wp-api.org/reference/posts/

For more information, see this page from the older, v1 documentation: http://wp-api.org/#posts_create-a-post and the [Working with Posts](http://wp-api.org/guides/working-with-posts.html) guide

**Comment by kadamwhite** [comment]
I'm going to close this issue as resolved; if you encounter any bugs while working with the API, please let us know!
