### ISSUE TITLE
Pagination/Filtering not working in VM environment

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/WP-API#1926]
This is a weird one, and I'm curious whether anybody knows what I should investigate next: Using https://github.com/kadamwhite/wpapi-vagrant-varietal/ , with a fresh checkout and `vagrant up`, I get a working site running at wpapi.loc. However, http://wpapi.loc/wp-json/wp/v2/posts, http://wpapi.loc/wp-json/wp/v2/posts?page=2, http://wpapi.loc/wp-json/wp/v2/posts?page=3 etc all display the same posts. Pagination headers are being passed and updated correctly, but the content I see is the same 10 posts on all pages. Filtering is similarly non-functional.

What configuration could I have on my server that would be preventing any of the pagination or filtering from functioning?

WP 4.4 : the only plugins running are the WordPress importer and WP-API v2 beta 9.

**Comment by adamsilverstein** [comment]
@kadamwhite no idea why; I  can however confirm that the same pagination links are working fine here in my local. No filters running in your theme that could affect results?

**Comment by kadamwhite** [comment]
It's a brand new install, with the default theme; it's working fine on all my other API-enabled sites, too, which is why I'm stumped

**Comment by danielbachhuber** [comment]
> Pagination headers are being passed and updated correctly, but the content I see is the same 10 posts on all pages.

Can you share the full response from each request?

**Comment by kadamwhite** [comment]
Yes, I'll gist the JSON responses for brevity.

**http://wpapi.loc/wp-json/wp/v2/posts**

Request headers:

```
GET /wp-json/wp/v2/posts HTTP/1.1
Host: wpapi.loc
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie: wordpress_test_cookie=WP+Cookie+check; wordpress_logged_in_588b549da8495dcdd3d5fddfcfc4f8d9=apiuser%7C1451498802%7C9OTSH4TJCikbq8g7ACKYUmykRAdWYvrhoRjipgxvBp8%7Cd6a9fe281980139b0282dcd6c121297ff84a57d89c11b241fabf0fd383fbdfd7
```

Response headers:

```
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Wed, 30 Dec 2015 21:28:01 GMT
Content-Type: application/json; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/5.5.9-1ubuntu4.14
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
Access-Control-Allow-Headers: Authorization
X-WP-Total: 38
X-WP-TotalPages: 4
Link: <http://wpapi.loc/wp-json/wp/v2/posts?page=2>; rel="next"
Allow: GET
```

Response body: https://gist.github.com/kadamwhite/9f5d73c06afa9d243399

----------------------------------
----------------------------------


**http://wpapi.loc/wp-json/wp/v2/posts?page=2**

Request headers:

```
GET /wp-json/wp/v2/posts?page=2 HTTP/1.1
Host: wpapi.loc
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie: wordpress_test_cookie=WP+Cookie+check; wordpress_logged_in_588b549da8495dcdd3d5fddfcfc4f8d9=apiuser%7C1451498802%7C9OTSH4TJCikbq8g7ACKYUmykRAdWYvrhoRjipgxvBp8%7Cd6a9fe281980139b0282dcd6c121297ff84a57d89c11b241fabf0fd383fbdfd7
```

Response headers:

```
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Wed, 30 Dec 2015 21:29:15 GMT
Content-Type: application/json; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/5.5.9-1ubuntu4.14
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
Access-Control-Allow-Headers: Authorization
X-WP-Total: 38
X-WP-TotalPages: 4
Link: <http://wpapi.loc/wp-json/wp/v2/posts?page=2>; rel="next"
Allow: GET
```

Request body: https://gist.github.com/kadamwhite/01a13ccaef5b86d7f0be

**Comment by danielbachhuber** [comment]
Oh. Look at your second response:

```
Link: <http://wpapi.loc/wp-json/wp/v2/posts?page=2>; rel="next"
```

It should contain:

```
Link: <http://wpapi.loc/wp-json/wp/v2/posts?page=3>; rel="next"
```

Query params aren't being passed through in the request. I suspect it's a problem with your server config.

**Comment by danielbachhuber** [comment]
We can continue the conversation in your repo.

**Comment by kadamwhite** [comment]
If anybody else stumbles across this, a typo in the `try_files` directive in an nginx site config can prevent query parameters from getting correctly passed through to PHP:

```diff
diff --git a/deploy/roles/nginx/templates/nginx.conf b/deploy/roles/nginx/templates/nginx.conf
index 5ab780c..5db9956 100644
--- a/deploy/roles/nginx/templates/nginx.conf
+++ b/deploy/roles/nginx/templates/nginx.conf
@@ -11,7 +11,7 @@ server {
 
 	location / {
 		index index.php index.html index.htm;
-		try_files $uri $uri/ /index.php$args;
+		try_files $uri $uri/ /index.php?$args;
 	}
 
 	location ~ \.php$ {
```
This change resolved the problem.

**Comment by rmccue** [comment]
(You might also want `$is_args` instead of the hardcoded `?`)
