### ISSUE TITLE
Getting all custom posts where parent!=0

### ISSUE THREAD

**Issue by brandondurham** [WP-API/WP-API#1927]
I have a hierarchical custom post type called Special Series. To get all top-level Special Series for a menu, I use this:

`/wp-json/wp/v2/special-series?parent=0&filter[order]=ASC`

How can I get all child Special Series posts, excluding the posts where `parent=0`?

**Comment by danielbachhuber** [comment]
> How can I get all child Special Series posts, excluding the posts where parent=0?

The REST API doesn't yet support this type of query as a public query. However, by whitelisting the `post_parent__not_in` query variable, you could use `&filter[post_parent__not_in]=0`.

```
add_filter( 'query_vars', function( $query_vars ){
	$query_vars[] = 'post_parent__not_in';
	return $query_vars;
});
```

If the request is authenticated, you can use `post_parent__not_in` without whitelisting.

Related #924 for whether we should add `parent__not_in` and `parent__in` as top-level query arguments for hierarchical post types.

**Comment by joehoyle** [comment]
I never even heard of these wp query vars!
