### ISSUE TITLE
Unable to GET  a specific Custom Post

### ISSUE THREAD

**Issue by ncc486** [WP-API/WP-API#1930]
Hey guys,
I am trying to fetch a custom post type.
I can see the list of Custom Post types available via the API here: http://magarmach.com/wp-json/wp/v2/types/

I see there is a Custom Post  "job_listing" in there. I can see all the fields of "job_listing" custom post type  at http://magarmach.com/wp-json/wp/v2/types/job_listing/

But what I cant fetch, is a listing with id: 6974. I dont know if I am messing up with the URL generation or I have to add some code to functions.php file. 
(The given id exists)
Url's I have tried:
 http://magarmach.com/wp-json/wp/v2/types/job_listing/6974
 http://magarmach.com/wp-json/wp/v2/job_listing/6974
 http://magarmach.com/wp-json/wp/v2/posts/job_listing/6974
 

I have also tried adding the following code to the functions.php file of the child theme on my website.

add_action( 'init', 'add_events_to_json_api', 30 );
function add_events_to_json_api(){

    global $wp_post_types;
    $wp_post_types['the_event']->show_in_rest = true;
    $wp_post_types['the_event']->rest_base = 'job_listing';
    $wp_post_types['the_event']->rest_controller_class = 'WP_REST_Posts_Controller';
}

Please help! It's a weird error.
API is exposed to the job_listing content type but cant seem to have knowledge about the specific id. 
Thanks in advance!
Lovely plugin. Waiting for it to be fully added to the core.

**Comment by chrisschrijver** [comment]
Which version of the WP API plugin do you use? 2 Weeks ago I had issues too, turned out I was still on beta5, but beta9 was already available. On the website (http://v2.wp-api.org/) the download button still points to beta5.

**Comment by Shelob9** [comment]
http://magarmachcom/wp-json/wp/v2/job_listing/6974 should work, if the post
type is registered before init:30. Have you set break points inside of
`add_events_to_json_api`
to ensure that it is firing and that `$wp_post_types` has the index
`the_event`? Also, how does `the_event` post type get registered? If you
registered it (versus a plugin or theme doing it) why not just set
`show_in_rest` when registering it?

--
JoshPress.net <http://joshpress.net/>
CalderaWP.com <http://calderawp.com/>
IngotHQ.com
@Josh412 <http://twitter.com/Josh412>

**Comment by ncc486** [comment]
Thank you guys. Things work now.
