### ISSUE TITLE
Server crashes when adding REST API support to more than 1 registered custom taxonomy..

### ISSUE THREAD

**Issue by ncc486** [WP-API/WP-API#1931]
Hey, guys great work with the plugin! I love it. 

However, I am running into a small issue here. I have added the custom code for giving WP API support to 1 Custom Post Type and 1 Custom Taxonomy in the functions.php file of my child theme. However, every time I add more code to support more Taxonomies (I want 4 more taxonomies to support WP API), my server crashes. 

It's a weird error. Maybe it has something to do with "isset" or the priority I have set. 

Please help!
Thank you very much and keep up the good work.

Just out of curiosity, apart from functions.php, where else can I add the custom code?

**Comment by danielbachhuber** [comment]
Can you share the code you're trying to add, and the server error you see? If it's a substantial amount of code, please [create a Gist](https://gist.github.com/) and share the link here.

> Just out of curiosity, apart from functions.php, where else can I add the custom code?

If the custom code is tied specifically to your theme, your functions.php is a great place for it. Otherwise, you could create a [MU plugin](https://codex.wordpress.org/Must_Use_Plugins) for it.

**Comment by ncc486** [comment]
Hey. I have figured it out. Thank you so much for reaching out.
Just out of curiosity, can I run search queries as well with the plugin?

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.91&pv=5.1&source=email_footer_2] On Mon, Jan 04, 2016 at 7:07 pm, Daniel Bachhuber < notifications@github.com [notifications@github.com] > wrote:
Can you share the code you're trying to add, and the server error you see? If
it's a substantial amount of code, please create a Gist [https://gist.github.com/] and share the link here.

Just out of curiosity, apart from functions.php, where else can I add the custom
code?

If the custom code is tied specifically to your theme, your functions.php is a
great place for it. Otherwise, you could create a MU plugin [https://codex.wordpress.org/Must_Use_Plugins] for it.

—
Reply to this email directly or view it on GitHub
[https://github.com/WP-API/WP-API/issues/1931#issuecomment-168677677] .[https://github.com/notifications/beacon/AHqnqhwfsGYI4iYvS9ILhrOPSewTQ5ROks5pWm0QgaJpZM4G96Mo.gif]

**Comment by danielbachhuber** [comment]
> Just out of curiosity, can I run search queries as well with the plugin?

Yes, you can use the `search` parameter.
