### ISSUE TITLE
Co-Authors-Plus integration

### ISSUE THREAD

**Issue by BrekiTomasson** [WP-API/WP-API#1943]
Like so many, I'm using the Auttomatic/Co-Authors-Plus plugin, and I'm trying to figure out a good way to build an endpoint to be able to read and write to it in the WP-API, but haven't had much luck yet. Does anybody have this up and running or have any pointers to get me moving in the right direction? I've tried asking on their own GitHub issue page, but they don't seem very talkative.

**Comment by danielbachhuber** [comment]
> Does anybody have this up and running or have any pointers to get me moving in the right direction?

Just a FYI — CAP integration with the REST API will require a non-trivial amount of development work.

**Comment by BrekiTomasson** [comment]
Yeah, that's definitely the impression I'm getting right now, as well. The simplest would be if one could rewrite the REST API to accept an array containing multiple author IDs in place of a string containing the author ID in POST, but I don't want to be rewriting core REST API files since I'll lose it on update.

**Comment by danielbachhuber** [comment]
Have you looked at [extending the API](http://v2.wp-api.org/extending/modifying/)?

**Comment by danielbachhuber** [comment]
Btw, this is going to be outside the scope of what this plugin will support.

For the next person to come across this issue, let's continue the conversation in https://github.com/Automattic/Co-Authors-Plus/issues/321
