### ISSUE TITLE
Malformed Json

### ISSUE THREAD

**Issue by mmanishh** [WP-API/WP-API#1948]
<b>Fatal error</b>:  Call to undefined function  wp_json_encode() in <b>/home/a1981499/public_html/wp-content/plugins/rest-api/core/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>386</b><br />
 Got this error

**Comment by mmanishh** [comment]
Ok got the solution changed the function from wp_json_encode() to json_encode()

**Comment by rmccue** [comment]
You need to upgrade WordPress to a newer version; `wp_json_encode` is included with WP 4.1 and newer.

**Comment by mmanishh** [comment]
Thank you very much!
