### ISSUE TITLE
"rest_no_route" with old version of plugin

### ISSUE THREAD

**Issue by drag0nman** [WP-API/WP-API#1950]
Hello everybody,
I use old version of plugin, Version1.2.3
I didn't update the plugin and until 2 week ago all works fine.
Now when I use the routes, for instance: http://www.mysite.it/wp-json/posts
the result is:
{
    "code": "rest_no_route",
    "message": "Nessun percorso fornisce una corrispondenza tra l'URL e le modalità di richiesta",
    "data": {
        "status": 404
    }
}

Can you help me?
My wordpress version is 4.4.

Thank you

**Comment by danielbachhuber** [comment]
You'll need to upgrade to WP-API v1.2.4 for compatibility with WordPress 4.4
