### ISSUE TITLE
CORS headers

### ISSUE THREAD

**Issue by daninmanchester** [WP-API/WP-API#1953]
The API really needs more configuration options as part of an admin page.

One setting would be a section to configure / list CORS headers to allow API access from another domain.

**Comment by danielbachhuber** [comment]
Given the security implications, CORS won't ever be a setting you can manage through the WordPress admin. You can more or less add headers with a bit of PHP code.

**Comment by daninmanchester** [comment]
Configurable CORS headers are not a security issue.
Misuse of CORS headers or PHP hacks are.
A simple white list  (for example) would be much more secure than a PHP hack.

**Comment by joehoyle** [comment]
CORS headers are not something that should be managed in the WordPress admin, or stored in the database, it should be managed via PHP in a plugin / theme modification. Modifying / creating a plugin is not a "PHP hack", it's code - used to manage the state of what CORS headers are allowed.

**Comment by daninmanchester** [comment]
Plenty of APIs do a nice job of it. 
The problem as it stands is you have to hack code rather than deal with configuration management.

**Comment by joehoyle** [comment]
@daninmanchester configuration management is done through code with WordPress typically, see `wp-config.php`. Once again, writing code is not a "hack".

**Comment by daninmanchester** [comment]
code is not a hack, but hard coding values that have to be changed between environments in code is a hack.
