### ISSUE TITLE
WP Multisite

### ISSUE THREAD

**Issue by crouti** [WP-API/WP-API#1956]
Hi,
I am trying to access my subsites on a folder multisite install, the exact same way i access the main site : it does not work. Is this normal ?
What would you suggest for me to use the same API on each sub site ?
I use the API v1 before and i think it worked...
Thank you very much

**Comment by danielbachhuber** [comment]
> I am trying to access my subsites on a folder multisite install, the exact same way i access the main site : it does not work. Is this normal ?

Can you share the request you're making, it's response, and tell us what you'd expect to see?

> What would you suggest for me to use the same API on each sub site ?

I'm not sure I follow this question.

**Comment by crouti** [comment]
Thank you fir your answer, with WP REST API v1, the request:

http://www.mainsite.com/sub-site/wp-json/posts/?filter[name]=post-name

works perfectly

With WP REST API v2 installed instead, the same request doesn't work. It
only works on main site, like :

http://www.mainsite.com/wp-json/posts/?filter[name]=post-name
Is this clear ?
Thank you


2016-01-06 17:09 GMT+01:00 Daniel Bachhuber <notifications@github.com>:

> I am trying to access my subsites on a folder multisite install, the exact
> same way i access the main site : it does not work. Is this normal ?
>
> Can you share the request you're making, it's response, and tell us what
> you'd expect to see?
>
> What would you suggest for me to use the same API on each sub site ?
>
> I'm not sure I follow this question.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WP-API/WP-API/issues/1956#issuecomment-169371861>.
>



-- 
Max UNGER
06.66.13.16.26

www.termel.fr

**Comment by danielbachhuber** [comment]
> With WP REST API v2 installed instead, the same request doesn't work

v2 functions a bit differently than v1. I'd encourage you to [review the v2 documentation](http://v2.wp-api.org/) to become better acquainted. 

In the example you've provided, the v2 URL would be:

`http://www.mainsite.com/wp-json/wp/v2/posts?filter[name]=post-name`

**Comment by crouti** [comment]
Thank you for your quick answer, but this request seems to target the main
site, will it reach a subsite anyway, if the post-name provided is a post
on a subsite ?

2016-01-06 18:11 GMT+01:00 Daniel Bachhuber <notifications@github.com>:

> With WP REST API v2 installed instead, the same request doesn't work
>
> v2 functions a bit differently than v1. I'd encourage you to review the
> v2 documentation <http://v2.wp-api.org/> to become better acquainted.
>
> In the example you've provided, the v2 URL would be:
>
> http://www.mainsite.com/wp-json/wp/v2/posts?filter[name]=post-name
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WP-API/WP-API/issues/1956#issuecomment-169392245>.
>



-- 
Max UNGER
06.66.13.16.26

www.termel.fr
