### ISSUE TITLE
GET request for media files results in an empty array

### ISSUE THREAD

**Issue by CapitalH** [WP-API/WP-API#1959]
Hi

I have been trying to fetch all the media files from the REST API using restangular, but no matter how I try it fails, so I decided to test the media endpoint via PostMan app and realized that although I can see the media files json object in my browsers when I browse to /wp-json/wp/v2/media but using PostMan or using restangular it always results in an empty array.

The funny part is that during the time I was pulling my hair for getting the media files, the files showed up only once, and after one refresh they were gone forever, this could be a bug in the wp rest plugin.

**Comment by danielbachhuber** [comment]
Sorry, but it's hard to say what the problem might be without more specific details.

It's most likely specific to your environment, and could be caused by your caching system or another plugin.

**Comment by CapitalH** [comment]
@danielbachhuber 
Thanks for the fast reply. I did more tests and I realized that I can only access the media endpoint object when I am logged out, the only logged in user role that would still show the media object is the subscriber user role, I tested it with admin, editor, author and contributor roles and it wouldn't work.

The result is the same either in my app or in the PostMan, so this can not be an issue with my testing environment. Could you please test again with PostMan + Authentication using JSON Basic Authentication plugin to see if you could recreate the situation on your side?

**Comment by danielbachhuber** [comment]
> Could you please test again with PostMan + Authentication using JSON Basic Authentication plugin to see if you could recreate the situation on your side?

We don't support the JSON Basic Authentication plugin. You should instead use this plugin: https://github.com/WP-API/Basic-Auth

**Comment by CapitalH** [comment]
@danielbachhuber 
This is not an issue with the authentication plugin since I have already tried cookie authentication via restangular and exactly the same thing happens as with PostMan for mac.

But I tried your recommended plugin right now and again I get the same results. This is not related to a specific environment, since I have tried it in different browsers and OSs.

Any ideas? Do you get the same results after authenticating as and admin user?

**Comment by danielbachhuber** [comment]
> Any ideas? Do you get the same results after authenticating as and admin user?

Low and behold, I can reproduce now. Sorry about that. Debugging.
