### ISSUE TITLE
Comment parent is never embedded

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#196]
I could be crazy, but it [seems like we never actually embed comment parents](https://github.com/WP-API/WP-API/blob/6f8d17473701e692c39a4e83ba036527c95e2585/lib/class-wp-json-posts.php#L1044-L1054). Whoops.

**Comment by danielbachhuber** [comment]
Reference is in `develop`: https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-comments-controller.php#L526
