### ISSUE TITLE
Apply post_where to returned posts

### ISSUE THREAD

**Issue by KuneStudio** [WP-API/WP-API#1965]
Hi all,
More a question/discussion but I don't get exactly how I can apply advanced custom meta query filters to my results.
I actually have a function that apply a where clause to my query, to get posts by geoloc.
So I have to pass as argument the lat and lon to my query.
How can this be done ? 
Thanks !

**Comment by danielbachhuber** [comment]
You can use the `rest_post_query` filter: https://github.com/WP-API/WP-API/blob/7573f8a19e36f16d8d88445b418b3108186a84d1/lib/endpoints/class-wp-rest-posts-controller.php#L90-L99
