### ISSUE TITLE
get_post_meta($post Id, $key, TRUE)  as json response

### ISSUE THREAD

**Issue by tumdav** [WP-API/WP-API#1967]
Hi all,
I am using WP REST API Version 2.0-beta 9.
Please say me how can i get get_post_meta($post Id, $key, TRUE) function result
as rest resource

**Comment by johanmynhardt** [comment]
Hi @tumdav :)

In short, it is not available by default for security reasons, but don't lose hope!

The following helped me: https://1fix.io/blog/2015/07/20/query-vars-wp-api/

For example, the following (added to the plugin's `plugin.php`)  was enough for my needs:

    function my_allow_meta_query( $valid_vars ) {
        $valid_vars = array_merge( $valid_vars, array( 'meta_key', 'meta_value', 'meta_compare' ) );
        return $valid_vars;
    }
    add_filter( 'rest_query_vars', 'my_allow_meta_query' );

**Comment by tumdav** [comment]
##### I solved problem via register_rest route function.
Code example

```php
/**
 * GET page meta tags by page id and meta name
 */
add_action('rest_api_init', function () {
    register_rest_route('api/v1/meta', '(?P<name>\w+)/(?P<id>\d+)', array(
        'methods' => 'GET',
        'callback' => 'slug_get_meta_content',
        'args' => array(
            'id' => array(
                'validate_callback' => 'is_numeric'
            )
        ),
    ));
});

/**
 * Get the page metas
 * @param $data {object} request arguments.
 */
function slug_get_meta_content($data)
{
    return ['content' => get_post_meta($data['id'], $data['name'], true)];
}
```

**Comment by danielbachhuber** [comment]
@tumdav I'm going to remove your example, because it should be considered insecure. By exposing all of your meta values publicly, you run the risk of accidentally exposing private data.

Instead, you should follow this guide: http://v2.wp-api.org/extending/modifying/
