### ISSUE TITLE
GET Terms: Drop unnecessary `term_id` from orderby enum

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1972]
`id` is the one true id for terms. But, in dropping `term_id`, we should make `orderby=>id` does what we expect it to.

**Comment by joehoyle** [comment]
:+1: do we support the same for all the other controllers too?

**Comment by danielbachhuber** [comment]
> do we support the same for all the other controllers too?

Sorry, I don't follow. Support the same, meaning?

**Comment by joehoyle** [comment]
Do all the other controllers support `orderby=>id`

**Comment by danielbachhuber** [comment]
Ah. I don't believe so, but something we can look at as a part of the audit for #924
