### ISSUE TITLE
filter category and taxonomy

### ISSUE THREAD

**Issue by esiise** [WP-API/WP-API#1974]
hi i use wp-api and i have custom post type named job_listing
it works with normal and search
http://nesh.in/wp-json/wp/v2/job_listing

now i need to see my categories posts from this custom post type
for example i have category with this properties
http://nesh.in/wp-json/wp/v2/job_listing/99991122/job_listing_category

how can i see all post in this category of job_listing

thank you for best plugin ever see...

**Comment by esiise** [comment]
i use this but it back all of post
http://nesh.in/wp-json/wp/v2/job_listing?filter[job_listing_category_name]=%D9%88%DB%8C%D9%84%D8%A7

**Comment by danielbachhuber** [comment]
@esiise We may have an encoding problem with terms.

**Comment by esiise** [comment]
ok but may i use the id of category ?
how?

**Comment by danielbachhuber** [comment]
> ok but may i use the id of category ?

You'd need to use a tax query, which isn't fully supported yet. Follow along in #924 for progress.
