### ISSUE TITLE
Querying comments by post_slug is protected

### ISSUE THREAD

**Issue by patrickgalbraith** [WP-API/WP-API#1979]
Why does querying comments by `post_slug` require authentication but by `post_id` it doesn't?

This is causing me issues for something I am building since I cannot request the post and the comments in parallel since I don't know the post's ID from the URL. So I have to wait for the post request to finish before requesting the comments. I can't see any reason why most of those arguments are protected (see code below).

```php
$prepared_args = array(
  'number'  => $request['per_page'],
  'post_id' => $request['post'] ? $request['post'] : '', // <--- Not authenticated
  'parent'  => isset( $request['parent'] ) ? $request['parent'] : '',
  'search'  => $request['search'],
  'orderby' => $this->normalize_query_param( $order_by ),
  'order'   => $request['order'],
  'status'  => 'approve',
  'type'    => 'comment',
);

$prepared_args['offset'] = $prepared_args['number'] * ( absint( $request['page'] ) - 1 );

if ( current_user_can( 'edit_posts' ) ) {
  $protected_args = array(
    'user'         => $request['user'] ? $request['user'] : '',
    'status'       => $request['status'],
    'type'         => isset( $request['type'] ) ? $request['type'] : '',
    'author_email' => isset( $request['author_email'] ) ? $request['author_email'] : '',
    'karma'        => isset( $request['karma'] ) ? $request['karma'] : '',
    'post_author'  => isset( $request['post_author'] ) ? $request['post_author'] : '',
    'post_name'    => isset( $request['post_slug'] ) ? $request['post_slug'] : '', // <--- Authenticated :(
    'post_parent'  => isset( $request['post_parent'] ) ? $request['post_parent'] : '',
    'post_status'  => isset( $request['post_status'] ) ? $request['post_status'] : '',
    'post_type'    => isset( $request['post_type'] ) ? $request['post_type'] : '',
  );

  $prepared_args = array_merge( $prepared_args, $protected_args );
}
```

On another note the comments `_embedded` in the post also can't be ordered which is a pain since I am showing the comments in `asc` order and the api doesn't take into account the discussion settings in WordPress. Which means I need to do additional api requests for the comments.

![image](https://cloud.githubusercontent.com/assets/811945/12220651/4f23c406-b7c9-11e5-8121-5f345591c01e.png)

**Comment by patrickgalbraith** [comment]
Also shouldn't attempting to use a protected argument throw some kind of error.

**Comment by danielbachhuber** [comment]
> Why does querying comments by post_slug require authentication but by post_id it doesn't?

I'm not totally sure, to be honest. Introduced in 0a24396fa469c5ae6694a8302868c16642109258. Given the inherit ambiguity with slugs (#642), I'm not sure we should support it either.

> On another note the comments _embedded in the post also can't be ordered which is a pain since I am showing the comments in asc order and the api doesn't take into account the discussion settings in WordPress.

I'm not sure we're going to support passing additional query arguments to embedded links, though worth discussing in further depth. Related #1615, #1612

Because "showing comments in the asc order" is a display configuration, I don't believe we'll support it through the API.

> Also shouldn't attempting to use a protected argument throw some kind of error.

I agree. The comments issue is #1212. Also related #1796

Thanks for the feedback!

**Comment by patrickgalbraith** [comment]
@danielbachhuber Thanks heaps for your quick reply :smiley: 

> Because "showing comments in the asc order" is a display configuration, I don't believe we'll support it through the API.

Is there any way to override this using a hook? If not no big deal just wondering.

> I'm not totally sure, to be honest. Introduced in 0a24396. Given the inherit ambiguity with slugs (#642), I'm not sure we should support it either.

I added a pull request for this. I can see why not supporting it would be an option however if you provide both the `post_type` and `post_slug` shouldn't that remove the ambiguity?

**Comment by danielbachhuber** [comment]
> Is there any way to override this using a hook? If not no big deal just wondering.

Not yet, but coming in #2007 

> I added a pull request for this. I can see why not supporting it would be an option however if you provide both the post_type and post_slug shouldn't that remove the ambiguity?

I feel inclined to remove support for `post_author`, `post_name`, `post_parent`, `post_status`, and `post_type`, and only support `post_id` because:
1. A join against the posts table has performance considerations.
2. They're inconsistent with the rest of our controllers (e.g. why can't I `GET /wp/v2/media post_name==<slug>` ?)

**Comment by patrickgalbraith** [comment]
> I feel inclined to remove support for post_author, post_name, post_parent, post_status, and post_type, and only support post_id because:

So the API uses `WP_Comment_Query` which supports the below arguments anyway. Could any of the arguments that do require joins be pushed to a filter parameter similar to the `posts` endpoint? That way it would be more consistent with the other endpoints but would still support more complex use cases. The reason I'm suggesting this is that I can think of a number of times in the past I have needed some of these arguments in PHP sites and for comments doing the filtering on the client side isn't really possible if you have 100s of comments per post.

``` php
$args = array(
      'author_email' => '',
      'author__in' => '',
      'author__not_in' => '',
      'include_unapproved' => '',
      'fields' => '',
      'ID' => '',
      'comment__in' => '',
      'comment__not_in' => '',
      'karma' => '',
      'number' => '',
      'offset' => '',
      'orderby' => '',
      'order' => 'DESC',
      'parent' => '',
      'post_author__in' => '',
      'post_author__not_in' => '',
      'post_id' => 0,
      'post__in' => '',
      'post__not_in' => '',
      'post_author' => '',
      'post_name' => '',
      'post_parent' => '',
      'post_status' => '',
      'post_type' => '',
      'status' => 'all',
      'type' => '',
      'type__in' => '',
      'type__not_in' => '',
      'user_id' => '',
      'search' => '',
      'count' => false,
      'meta_key' => '',
      'meta_value' => '',
      'meta_query' => '',
      'date_query' => null, // See WP_Date_Query
);
```

**Comment by patrickgalbraith** [comment]
So similar to querying posts by name which is `/wp-json/wp/v2/posts?filter[name]=slug` it would be like `/wp-json/wp/v2/comments?filter[post_name]=slug`

**Comment by danielbachhuber** [comment]
> Could any of the arguments that do require joins be pushed to a filter parameter similar to the posts endpoint?

Potentially, but would still require authentication.

**Comment by patrickgalbraith** [comment]
> Potentially, but would still require authentication.

Why? It doesn't require authentication for `posts` and I can't see it being a security issue.

**Comment by kadamwhite** [comment]
>  It doesn't require authentication for posts

+1, I'm also unclear on why these query parameters are (well, assuming "prior art" is _why_, but rather, why they should continue to be) treated differently for comments than for other types.
