### ISSUE TITLE
POST Posts: Call transition_post_status when creating a new Post

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1980]
In the WordPress admin, `transition_post_status` is called when creating a new post because WordPress always creates a stub post with `auto-draft` status.

Because the REST API directly calls `wp_insert_post()` with the post's status, `transition_post_status` isn't called when creating a new post.

Should we replicate the behavior of the WordPress admin in this scenario?

Reported in [the support forums](https://wordpress.org/support/topic/using-transient_post_status?replies=1#post-7864407)

Related #1749, #1820

**Comment by eyouth** [comment]
Well I think it should be added, there are times for my instance I want to send notification for every posts that status was changed to publish, and this is not applicable using the publish_{slug} hook.

Thanks

**Comment by danielbachhuber** [comment]
> Should we replicate the behavior of the WordPress admin in this scenario?

We're not going to, see https://wordpress.slack.com/archives/core-restapi/p1452554625003856. Many plugins call `wp_insert_post()` programmatically, so it's not a reasonable expectation to hook into `transition_post_status` for a new post.

**Comment by robpanes-space** [comment]
Hi Daniel, 

Ok I understand, thanks for the time.
