### ISSUE TITLE
Remove count_user_posts as condition of viewing user

### ISSUE THREAD

**Issue by Youdaman** [WP-API/WP-API#1983]
Currently if a user has no posts you cannot retreive them via GET, e.g. /wp-json/wp/v2/users/2 if user with ID = 2 has no posts.

(see lib/endpoints/class-wp-rest-users-controller.php and search for count_user_posts)

Also, users without posts aren't included in the results for /wp-json/wp/v2/users

This means if I have a social networking site where two people have signed up, they cannot find each other via the user search if I'm using WP API to get a list of all users on the site.

Having no posts does not mean a user is invalid -- checks for such things should be the responsibility of the code I'm writing that uses the API, I don't need the API restricting my results this way.

**Comment by Youdaman** [comment]
(cross-posted to https://wordpress.org/support/topic/remove-count_user_posts-as-condition-of-viewing-user?replies=1#post-7870237 also)

**Comment by TimothyBJacobs** [comment]
The reason users without published posts are excluded is not because they are invalid, but because they aren't currently accessible without the API. Being able to crawl all of a site's users is certainly unexpected, and could be an information disclosure or security problem depending on the site.

If your _logged-in_ users need to be able to find other users, consider granting them the `list_users` capability, or removing the `has_published_posts` argument via the `rest_user_query`.

Such checks are entirely the responsibility of the API. The site itself is not the only consumer of its API.

**Comment by Youdaman** [comment]
Thanks for the info and tips Tim. Another workaround I'm curently using is simply to override the number of posts being returned like so:

One workaround is to override the number of posts for every user like so:

```
add_filter( 'get_usernumposts' , 'custom_get_usernumposts');
function custom_get_usernumposts( $count, $userid, $post_type, $public_only ) {
  return 1;
}
```

This could be more sophisticated, to only return 1 in the case where there are none, but in my instance users don't ever have default posts and only custom posts anyway, and I'm not using this elsewhere.

**Comment by rmccue** [comment]
> Being able to crawl all of a site's users is certainly unexpected, and could be an information disclosure or security problem depending on the site.

This is why :)

User data is generally private, however we allow access to a restricted subset of the data for authors (users with post count > 1). This data is already public, and exposed in various other places, so it's no worse than what we currently have.

If you'd like to change it, there's a couple of options. You can subclass `WP_REST_Users_Controller` and override `get_item_permissions_check` (or have a separate, new endpoint, which is the preferred option), or you can filter `rest_endpoints` and change the callback there.

The behaviour in the API currently won't be changing though. :)

**Comment by Youdaman** [comment]
Cheers Ryan.

For anyone else reading, Tim's suggestion about overriding the rest user query is now the way I'm going:

```
add_filter( 'rest_user_query' , 'custom_rest_user_query' );
function custom_rest_user_query( $prepared_args, $request = null ) {
  unset($prepared_args['has_published_posts']);
  return $prepared_args;
}
```

I assume having $request = null is the way to go as I got a warning when not setting a default value.
