### ISSUE TITLE
Figure out how to permit publicly querying featured images when attachment is assigned to a private post

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#1987]
Given two posts, A (public) and B (private), core currently lets a user assign a featured image to A which has been uploaded to B. However, the REST API's permissions model is such that the featured image can't be queried unless B is public. A unauthenticated client expects to be able to query a featured image assigned to a published post, regardless of which post it was uploaded to.

From https://github.com/WP-API/WP-API/issues/1526#issuecomment-170121984

**Comment by joehoyle** [comment]
oh man.

**Comment by ioanlucut** [comment]
Is there a workaround for this issue ? e.g. keeping the client authenticated?

**Comment by danielbachhuber** [comment]
> Is there a workaround for this issue ? e.g. keeping the client authenticated?

Authenticated and appropriately authorized requests will be able to access all media.

**Comment by websupporter** [comment]
The question for me is, what data of a media which is attached to a private post is actually public when set as a featured image to a public post.

This would be the alt-Text and the different image-URLs/sizes. Cant we just change the `type` of the featured_image scheme to object

and return something like this:

```
featured_image : {
        "id":14,
        "URL":
            [   
                "http://.../1.jpg",
                "http://.../1-640x480.jpg",
                "http://.../1-1280x900.jpg"
            ],
        "alt":"my alternative description"
    }
```

So, you couldn't actually query the media with the ID 14 (since its attached to a private post), but still get the public accessible information in the original queried (public) post.

Downside: This whould not apply to the `_embedded` section of the response

**Comment by krogsgard** [comment]
If you have a featured image on a public post, but the featured image was previously (or is simultaneously) used on a private post, then I believe that's a bug in the interface of WordPress itself, with the limitation of singular attachment relationships. The person making the decision to put the image on the public post did so purposefully, and when that public post is queried, we should make the featured image available, including in the `_embedded` section, imo.

**Comment by kadamwhite** [comment]
Per discussion with @rmccue & @aaroncampbell in [weekly bug triage Sep. 15](https://wordpress.slack.com/archives/core-restapi/p1473950298001563), there is no good solution to this based on the current state of affairs in core. If WordPress made an image parent-less when it was assigned to a post other than that to which it was uploaded (with parent-less being a proxy for public, in our case) this would not be an issue; but that is not what WordPress does.

Short of changing the entire media attachment model the best solution may be to leave things as they are and have **the privacy of the media item's parent govern the media's visibility**. This _does_ mean that if you use a media item previously uploaded to a private post as the featured image for a new public post, this bug will _still occur_.

The workaround will be to move the attachment elsewhere (change or remove its parent) to make it public if you wish to use it more places.

**Comment by aaronjorbin** [comment]
@joemcgill @getsource As the media maintainers, can you take a look here and share your thoughts?

**Comment by joemcgill** [comment]
I spent some time over the weekend looking specifically at this issue and wanted to add a few observations.

First, on the front end, when a person without proper caps requests a URL for an attachment with a private parent, we return a 404. Currently the API endpoint returns a 403 (forbidden) instead. Is there a reason these are handled differently—the use case described by this ticket notwithstanding? The 403 makes sense if the parent is a password protected post, but that's not the case here.

For logged in users without capabilities, we already expose :alot: of information about these attachments. For example, these images still show in the media library for authors who don't have access to the parent post. The only thing we do seem to be putting effort into hiding is the title of the post that the image is attached to. That said, almost all information that we would expose through the API is readily available right now through the `wp.media` JS object, so whatever decisions we make here should be reinforced in `wp.media`.

I happen to think it's an oversight in WordPress that we allow an image attached to a private post to be set as the featured image of another post (and by an author without permission to view the private parent post). We should probably either close this loophole or detach the attachment from the private post whenever it's set as a featured image on another post.

**Comment by joemcgill** [comment]
Related – the addition of hiding the title of a private published post in the media library was only recently addressed: https://core.trac.wordpress.org/ticket/37186

**Comment by rmccue** [comment]
> First, on the front end, when a person without proper caps requests a URL for an attachment with a private parent, we return a 404. Currently the API endpoint returns a 403 (forbidden) instead. Is there a reason these are handled differently—the use case described by this ticket notwithstanding? The 403 makes sense if the parent is a password protected post, but that's not the case here.

403 is the return code for "you're authenticated, but not authorized", consistent with our other endpoints. 404 would indicate it doesn't exist at all, which isn't really accurate (although it might be what you want if you're aiming for secret attachments, we don't really cater towards that).

**Comment by joemcgill** [comment]
If that's consistent with what would be returned if someone hit a public endpoint for a private post, then that makes sense.

**Comment by kadamwhite** [comment]
Decision from [Dev Chat 2016-09-28](https://wordpress.slack.com/archives/core/p1475096902003202): continue treating media `status=inherit` as inheriting parent post status (and privacy) in the API (maintain the current state).

Core tickets will be opened to address making core's behavior more predictable; attachment privacy can more easily be opened up in future cycles than it can be tightened, so the edge case described in this issue will be documented as a "gotcha" in the API for now.
