### ISSUE TITLE
v1.x Documentation dead?

### ISSUE THREAD

**Issue by darcyclarke** [WP-API/WP-API#1988]
Hitting http://wp-api.org/ is showing me no documentation for v1.x anymore:

<img width="1694" alt="screen shot 2016-01-11 at 4 31 35 pm" src="https://cloud.githubusercontent.com/assets/459713/12247391/bbf2d604-b881-11e5-8d59-c8c21d68e3b4.png">

**Comment by danielbachhuber** [comment]
Seems to load fine for me:

![image](https://cloud.githubusercontent.com/assets/36432/12247272/16e71cb0-b868-11e5-869c-3738b75d8e38.png)

Check your console?

**Comment by darcyclarke** [comment]
Is loading fine now... weird. There were console errors when I checked but I didn't see exactly what they were. Potentially it was in the midst of building? I'm guessing the documentation is automatically generated

**Comment by rmccue** [comment]
It loads the README directly from GitHub when you hit the page, so likely an intermittent connection issue.
