### ISSUE TITLE
rest_api_init 2.0-beta10

### ISSUE THREAD

**Issue by kalebheitzman** [WP-API/WP-API#1989]
I've installed the latest update and it seems that rest_api_init has quit working in my plugin. It also looks like it's generally not working across a WP install on MAMP at the moment. Here is a link to the class I'm implementing the API in.

https://github.com/kalebheitzman/prayer/blob/master/includes/classes/Prayer_API.php

I'm not getting any php errors and in Chrome I'm getting the No data received ERR_EMPTY_RESPONSE. I've saved permalinks again thinking maybe the permalinks cache needed cleared but that didn't seem to work either. 

Any idea what is going wrong?

**Comment by danielbachhuber** [comment]
Which version of WordPress are you running?

**Comment by kalebheitzman** [comment]
4.4.1

**Comment by danielbachhuber** [comment]
Hm. I'm not sure what it could be.

To confirm, when you roll back to beta9, the API works as expected?

**Comment by kalebheitzman** [comment]
I should also add when I visit example.dev/wp-json that Chrome throws the same no response error

**Comment by rmccue** [comment]
Anything in your server error logs? Might have been a botched plugin update; empty response is often thrown when a server doesn't handle PHP fatal errors correctly.

**Comment by kalebheitzman** [comment]
I rolled back to 2.0-beta9 and it works again

**Comment by kalebheitzman** [comment]
I'm going to look through logs again but there weren't any php errors thrown. I'll enable Xdebug and see what I can find.

**Comment by kalebheitzman** [comment]
I immediately get this for 2.0-beta9 

Warning: Cannot modify header information - headers already sent by (output started at /Users/Kaleb/Clients/Created by KH/kheitzman.com/index.php:14) in /Users/Kaleb/Clients/Created by KH/kheitzman.com/wp-includes/rest-api/class-wp-rest-server.php on line 1149

**Comment by kalebheitzman** [comment]
AND... I upgraded again to 2.0-beta10 and it works fine now. I had downgraded and upgraded to no avail before. I have no idea why it's working now. This can probably be closed.

**Comment by kalebheitzman** [comment]
I'm having the same issue again. Here's some more debug info. When I enable Xdebug the plugin works fine and then eventually it stops working again. Disabling the debugger causes it to work yet again. 

_Warning: Cannot modify header information - headers already sent by (output started at index.php:14) in /wp-includes/rest-api/class-wp-rest-server.php on line 1149._

Not sure what to make of it.

**Comment by rmccue** [comment]
> output started at index.php:14

That means there's something else spitting stuff onto the page. Check your main WP index.php file to see if there's anything before the `<?php` (including invisible characters)

**Comment by kalebheitzman** [comment]
The main index.php file is fine. I suspect it's something with MAMP Pro. When I restart mamp it always works. I pushed the plugin I was developing with REST to a production server and it seems to be working fine.

**Comment by laustdeleuran** [comment]
+1 - Having the same issue on a clean WP install (v4.4.1) + beta10.

Plugins: http://cl.ly/2X151Z3y312z
Error in Chrome: http://cl.ly/0o2i3A1Z1D1W

I  get nothing in my `php_error.log`.

**Comment by laustdeleuran** [comment]
@kalebheitzman I think you're right. My issue went away as well after a (computer) MAMP restart.
