### ISSUE TITLE
'/posts' and 'pages' endpoint is missing status item

### ISSUE THREAD

**Issue by jsmith8954** [WP-API/WP-API#1996]
I'm testing out out version 2 of the API and have run into a snag.

I'm running the following:
/?rest_route=/wp/v2/posts&filter[post_status]=[draft,publish]

I currently only have 5 posts (2 in draft status, and 3 published)
The request properly returns all 5 posts; however, when looking at the json, there is no "status" item in each post object as was present in the v1 api.  

There appears to be noway to distinguish posts by the status.  Am I missing something?

I have a new WP v.4.4.1 and testing with Basic Auth.
I have tested with both API  Version 2.0-beta9  and Version 2.0-beta10.

**Comment by danielbachhuber** [comment]
> however, when looking at the json, there is no "status" item in each post object

The `status` attribute is [only available](http://v2.wp-api.org/reference/posts/) in the `edit` context. You'll need to pass `context=edit` in order to access it.
