### ISSUE TITLE
<p> wrapped content on pages

### ISSUE THREAD

**Issue by silverbux** [WP-API/WP-API#1997]
whenever i post a page on `/wp-json/wp/v2/pages` endpoint it's always wrapped on a `<p>` tag, how can i disable that?

**Comment by silverbux** [comment]
solved with `remove_filter ('the_content',  'wpautop');` and has nothing to do with the plugin

**Comment by rmccue** [comment]
The content of posts and pages in WordPress is HTML, not text. WordPress automatically adds paragraph tags to text not inside an element to ensure it's valid content. The API simply returns this.

If you want to get the "raw" saved data, you can use an authenticated request with `?context=edit`. This will allow you to get the raw value from the database back, but is only available to authenticated clients.

If you'd rather WordPress not add paragraph tags to your content, you need to disable this on the site via a filter: http://learn.wpeditpro.com/disable-wpautop/

**Comment by harshclimate** [comment]
What if you wanted to add back in the auto p tags to `get_the_content()`?
