### ISSUE TITLE
Add `offset` parameter for all collections requests

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#2001]
Each of these requests should support an `offset` parameter where the value is some integer:
- [x] `GET /wp/v2/posts`
- [x] `GET /wp/v2/comments`
- [x] `GET /wp/v2/users`
- [x] `GET /wp/v2/<taxonomy>`

Related #924, https://github.com/WP-API/WP-API/pull/1471#issuecomment-132215677

**Comment by joehoyle** [comment]
+1 from me

**Comment by danielbachhuber** [comment]
:ship:
