### ISSUE TITLE
Set category and tags to a post

### ISSUE THREAD

**Issue by pelayopc** [WP-API/WP-API#2016]
How can i set category or tags to a post?

**Comment by danielbachhuber** [comment]
Sorry about that. I've restored the documentation:
- http://v2.wp-api.org/reference/posts/categories.html
- http://v2.wp-api.org/reference/posts/tags.html

You'll want to `POST` and `DELETE` to the `/wp-json/wp/v2/posts/<post_id>/categories` and `/wp-json/wp/v2/posts/<post_id>/tags` endpoints.

**Comment by pelayopc** [comment]
Thx, but i try:

POST <blog url>/wp-json/wp/v2/posts/<post id>/categories

{
  "code": "rest_no_route",
  "message": "No se encontró la ruta que coincida con la URL y el método de la petición",
  "data": {
    "status": 404
  }
}

with a valid id post and a valid blog url

What is my mistake?

**Comment by danielbachhuber** [comment]
Are you running the latest version of the API?

**Comment by pelayopc** [comment]
Yes, 
when i send GET request to : [blog_url]/wp-json/wp/v2/posts/[post_id]/categories
I get a list of the categories assigned to the post

but when i send POST to : [blog_url]/wp-json/wp/v2/posts/[post_id]/categories
i get:
{
"code": "rest_no_route",
"message": "No se encontró la ruta que coincida con la URL y el método de la petición",
"data": {
"status": 404
}
}

**Comment by pelayopc** [comment]
What is my mistake?

**Comment by danielbachhuber** [comment]
Sorry. The request needs to be:

```
POST [blog_url]/wp-json/wp/v2/posts/[post_id]/categories/[term_id]
```

**Comment by pelayopc** [comment]
Now it works fine! thx :)

**Comment by pelayopc** [comment]
it´s works fine with categories , but don´t works with tags, 

When i POST  :[blog_url]/wp-json/wp/v2/posts/[post_id]/tags/[term_id]

I get a json of the tag, but it didn´t assing the tag to the post

**Comment by pelayopc** [comment]
Sry my mistake, it works fine with tags too, sry and thx
