### ISSUE TITLE
post_date changes on update

### ISSUE THREAD

**Issue by nikolov-tmw** [WP-API/WP-API#2019]
I'm using the REST API and the Client JS. While working with a custom controller for a custom post type, I noticed that saving a post increments it's date(and therefore sometimes changes the post's status to `scheduled`). I have managed to reproduce that with the default Posts controller as well. Here's a test case:

```
var post = new wp.api.models.Post( {id: 1} );
post.fetch().success(function(){
    // Trigger an update right away - note we don't change any of the post's properties
    _post.sync('update', post);
});
```

In the AJAX request, I see that the following date was passed: `2014-07-04T01:41:57.000Z`(which was the current `post_date` for that post).
In the response though, I see that the date is now this: `2014-07-04T04:41:57`(it has changed in the DB as well)
So the post's publish date increased by three hours.
In WordPress, I have selected Sofia as my timezone(currently UTC +2). PHP and my computer are also set-up to use the same timezone.

I traced this down to the use of `rest_get_date_with_gmt()`. Technically the API expects the `date` parameter to be in the site's timezone, however things seem to somehow get tangled up.

This might as well be a configuration error on my system, but I'm really bad with handling timezones in PHP in order to confirm where the problem lies.

I'm using WordPress 4.4.1, WP REST API 2.0-beta10, WP-API/client-js@477a49f029c6503fe680322910bef20809ec552b

OS: Ubuntu 15.10 x64
PHP: 5.6.11-1ubuntu3.1 (fpm-fcgi)

**Comment by westonruter** [comment]
I've noticed this as well. I was able to help mitigate the issue by ensuring that I [append the blog's timezone offset](https://github.com/xwp/wp-customize-rest-resources/commit/b8525bc748e91c178162f390db221a207ad138e8#diff-b41052d3952060fd6942a02c5db18317R270) to the non-GMT fields, and append `Z` to the GMT fields, if either lacks a timezone specifier to begin with. It would be helpful if the timezone specifiers were included in the response REST response to begin with.

**Comment by nikolov-tmw** [comment]
@westonruter thanks for the tip! Here's what I did to temporarily patch this up:

```
function add_timezone_to_rest_dates( $response, $post ){
    $tz_str = get_option( 'timezone_string' );
    $gmt_offset = get_option( 'gmt_offset' );

    if ( $tz_str ) {
        $tz = new DateTimeZone( $tz_str );
        $_date = new DateTime( $post->post_date, $tz );
        $offset_str = $_date->format( 'P' );
    } else if ( $gmt_offset ) {
        $gmt_offset *= 60;
        $hours = floor( abs( $gmt_offset ) / 60 );
        $minutes = ( abs( $gmt_offset ) % 60 );
        $offset_str = ( $gmt_offset < 0 ? '-' : '+' );
        $offset_str .= sprintf( '%02d:%02d', $hours, $minutes );
    } else {
        $offset_str = 'Z';
    }

    $response->data['date'] .= $offset_str;
    $response->data['date_gmt'] .= 'Z';

    return $response;
}
add_filter( 'rest_prepare_post', 'add_timezone_to_rest_dates', 10, 2 );
add_filter( 'rest_prepare_page', 'add_timezone_to_rest_dates', 10, 2 );
add_filter( 'rest_prepare_custom_pt', 'add_timezone_to_rest_dates', 10, 2 );
```

This seems to fix the problem - so I guess you're right that ignoring the timezone offset could be the root of this issue.

**Comment by nikolov-tmw** [comment]
An update to this issue - the above fix only worked when the client and server times matched(or are supposed to match). I tried using it on a site where the server(WordPress setting) time was different than my local time and things got out of whack again. What I ended-up doing(**in addition to the fix described above**) was including [moment JS](http://momentjs.com/) and [Moment Timezone](http://momentjs.com/timezone/) and overriding the individual collections and models that are created by the client JS library.
I mostly followed this article - [Dealing With Timezones in JavaScript](https://nulogy.com/who-we-are/company-blog/articles/dealing-with-timezones-in-javascript/) and adapted it to be used with the API. Note that I had to change all places where I accessed a date property of a model to use `moment()` like so: 

``` javascript
var date = moment( post.get('date').localEquivalent() ).format('D MMMM, YYYY')
```

Because the date property was no longer the native Date object.
You can find the code I used to modify the collection and model below. Just change `Post` and `Posts` to the respective names of the model and collection you want to modify.

``` javascript
var DateWithTimezone = function(moment){
    this.moment = moment;
    moment.tz(DateWithTimezone.getTimezone());
}

// WordPress time zone. I've hard-coded it, but I'm sure there's a way to get it with PHP and pass it as a global variable.
DateWithTimezone.timezone = 'America/Detroit';

_.extend(DateWithTimezone.prototype, {

    toISO: function(){
        return this.format();
    },

    format: function(format) {
        return this.moment.format(format);
    },

    localEquivalent: function(){
        return moment(this.format(), "YYYY-MM-DDTHH:mm:ss").toDate();
    },

    add: function(field, value) {
        var cloned = this.moment.clone();
        cloned.add(field, value);
        return new DateWithTimezone(cloned);
    },

    hours: function() {
        return this.moment.hours();
    },

    minutes: function() {
        return this.moment.minutes();
    },

    isLaterThan: function(compareTo) {
        return this.moment.valueOf() > compareTo.moment.valueOf();
    }
});

_.extend(DateWithTimezone, {
    fromISO: function(dateTimeString){
        return new DateWithTimezone(moment(dateTimeString));
    },

    fromLocalEquivalent: function(localEquivalent){
        var strWithoutTimezone = moment(localEquivalent).format("YYYY-MM-DDTHH:mm:ss");
        var timezone = moment.tz(DateWithTimezone.getTimezone()).format("Z");
        return new DateWithTimezone(moment(strWithoutTimezone + timezone));
    },

    getTimezone: function(){
        return DateWithTimezone.timezone || "Etc/UTC";
    },

    now: function(){
        return new DateWithTimezone(moment());
    }
});

// Override the default toJSON() and parse() methods as they don't work
// well when the client uses a different timezone than the server
wp.api.models.Post = wp.api.models.Post.extend({
    '_parseableDates': [ 'date', 'modified', 'date_gmt', 'modified_gmt' ],
    /**
     * Serialize the entity pre-sync.
     *
     * @returns {*}.
     */
    toJSON: function() {
        var attributes = _.clone( this.attributes );

        // Serialize Date objects back into 8601 strings.
        _.each( this._parseableDates, function( key ) {
            if ( key in attributes ) {

                // Don't convert null values
                if ( ! _.isNull( attributes[ key ] ) ) {
                    attributes[ key ] = moment(attributes[ key ]).format("YYYY-MM-DDTHH:mm:ss");

                    var timezone = moment.tz(DateWithTimezone.getTimezone()).format("Z");
                    attributes[ key ] = new DateWithTimezone(moment(attributes[ key ] + timezone)).toISO();
                }
            }
        } );

        return attributes;
    },

    /**
     * Unserialize the fetched response.
     *
     * @param {*} response.
     * @returns {*}.
     */
    parse: function( response ) {
        var timestamp;

        // Parse dates into native Date objects.
        _.each( this._parseableDates, function( key ) {
            if ( ! ( key in response ) ) {
                return;
            }

            // Don't convert null values
            if ( ! _.isNull( response[ key ] ) ) {
                // timestamp = wp.api.utils.parseISO8601( response[ key ] );
                response[ key ] = DateWithTimezone.fromISO( response[ key ] );
            }
        });

        return response;
    }
});

// Set the model used by the Post collection
wp.api.collections.Posts = wp.api.collections.Posts.extend({
    'model': wp.api.models.Posts
});
```

**Comment by BE-Webdesign** [comment]
Hi @nikolov-tmw,

Can you comment on this issue on the [JS repo](https://github.com/WP-API/client-js/issues/137) as well?

**Comment by rmccue** [comment]
This appears to be an issue entirely in the JS client, so closing out here. See also [my comment on the JS repo](https://github.com/WP-API/client-js/issues/137#issuecomment-249698505).

**Comment by nikolov-tmw** [comment]
@rmccue I don't think that's the case though, because for the JS client to work properly, it needs to know the timezone of the site and that needs to come from the PHP side of things.
I could be wrong, but I personally don't see a way to get the site's timezone purely in JS.

**Comment by rmccue** [comment]
> I don't think that's the case though, because for the JS client to work properly, it needs to know the timezone of the site and that needs to come from the PHP side of things.

The thing is, the site's timezone isn't really related to the times in the database. If you create a post when your site is in one timezone, then change your site's timezone, the date isn't updated to reflect that. You need to derive the offset at time of posting based on `date` and `date_gmt`.
