### ISSUE TITLE
Slow API response caused by All In One SEO Pack

### ISSUE THREAD

**Issue by ghost** [WP-API/WP-API#2020]
I'm currently developing the fritz-kola.de web site with the new json api.

I've now figured out that the All In One SEO Pack is causing my api calls to slow down 3x on a single call. This becomes an exponential problem when multiple api request are made. Any ideas? Can anyone help?

When I deactivate the plugin I get relatively good response times of around 150ms. Otherwise: 
![response](https://cloud.githubusercontent.com/assets/5802784/12299173/d443fbd0-ba15-11e5-967f-c1372cfef1c6.png)

**Comment by danielbachhuber** [comment]
> I've now figured out that the All In One SEO Pack is causing my api calls to slow down 3x on a single call. This becomes an exponential problem when multiple api request are made. Any ideas? Can anyone help?

Given this is a problem of All In One SEO Pack, and not fixable by the REST API plugin, I'd recommend opening a thread in their support forums to see if they can help with profiling.

Something worth noting in your screenshot though: I see you're using `posts_per_page=-1` in the request. Unbounded queries naturally lead to performance issues, and any request over 400 posts (I believe) fetches meta individually for each post, leading to hundreds of additional SQL calls. I'd recommend using a high upper bound like `posts_per_page=100` and paginating.

**Comment by ghost** [comment]
I will make a note of that. Thanks!
