### ISSUE TITLE
Make assigning terms to a post less wonky

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#2032]
To assign category ID 9 to post ID 1, I currently need to:

```
POST /wp/v2/posts/1/categories/9
```

This seems a bit wonky. It's also not possible to control the order of the terms, or assign more than one term at a time. See #1421

I'm not sure why we created separate endpoints for term management in the first place (I didn't search past discussion). What if, instead, we dropped the Post Terms controller, and magically registered `categories`, `tags` and other custom taxonomy-based attributes as an array of ids to the Post schema? This would be more in line with `author`, `featured_image` (which are ids that represent other resources).

cc @joehoyle 

From https://github.com/WP-API/WP-API/issues/2016#issuecomment-171392733

**Comment by joehoyle** [comment]
Yes! I'd much prefer this - I think we were thinking in the abstract when we did this, I'd be +1 for on the base object rather than a `taxonomies` prop, as a an update to the object is a bit more tricky if you only want to update a single taxonomy (which is probably more typical).

So 

```
{
    id: int,
    categories: []
    tags: [],
    $taxonomy_rest_base: []

}
```

**Comment by danielbachhuber** [comment]
Let's get this into the next beta then.

**Comment by kadamwhite** [comment]
> separate endpoints for term management

This would only impact how terms are associated with a specific post or object, then, correct—no impact to the `/wp/v2/categories` and such? If so, +1 from me; consistency in how these associated resources are managed within the API only sounds like a good thing.

**Comment by joehoyle** [comment]
I'm happy to take this on @danielbachhuber, will try to get it done on my flight tomorrow.

**Comment by danielbachhuber** [comment]
Ok. If you don't get to it, I can pick it up at the end of the week.
