### ISSUE TITLE
The "json_prepare_post" filter

### ISSUE THREAD

**Issue by reema-bhandari-jabong** [WP-API/WP-API#2045]
Complete Funstion:
function qod_remove_extra_data( $data, $post, $context ) {
// We only want to modify the 'view' context, for reading posts
if ( $context !== 'view' || is_wp_error( $data ) ) {
// Here, we unset any data we don't want to see on the front end:
unset( $data['author'] );
unset( $data['meta'] );
unset( $data['terms'] );
unset( $data['author'] ['meta'] );
// continue unsetting whatever other fields you want

return $data;

}

}

add_filter( 'json_prepare_post', 'qod_remove_extra_data', 12, 3 );

If I am using above function then it is removing values for array "0" and array "3". Rest values are same and this function is working if I am using 'rest_prepare_post' instead of 'json_prepare_post', then this is not working at all.
Output of this function is : 
![capture](https://cloud.githubusercontent.com/assets/11849485/12350699/b6463dd4-bb9e-11e5-9384-1959fc08fc74.PNG)
![capture-2](https://cloud.githubusercontent.com/assets/11849485/12350704/b7e06fb6-bb9e-11e5-860c-d55ffd3f77d4.PNG)

Please look into this if i am doing some mistake.

**Comment by rmccue** [comment]
You need to use `rest_prepare_post` with version 2, not `json_prepare_post`. The prefix here was changed early in the v2 cycle.
