### ISSUE TITLE
Change post status

### ISSUE THREAD

**Issue by pelayopc** [WP-API/WP-API#2046]
When i try to publish one post, changing its status, i send POST to:
[blog_url]/wp-json/wp/v2/posts/[post_id]

with params:
status = publish

It change post status from 'pending' to 'future', and not 'publish' the post

Can you help me?

**Comment by danielbachhuber** [comment]
WordPress is exhibiting this behavior because your `post_date` value is perceived to be in the future.

Is the date on the set to some point in the future? Can you share the full details on the request you're making (headers and body), and the full response value?

**Comment by pelayopc** [comment]
When i send the new post, as pending, and a few mins later i publish, it works fine.
I will try when i send the post pending and later, next day, i publish, i thinks this is the moment when de api returns future, i will try it this days.
Thanks for your help

**Comment by danielbachhuber** [comment]
@pelayopc were you able to get this worked out?

**Comment by pelayopc** [comment]
¨Yes, sry, it works fine now
