### ISSUE TITLE
current_user_can('list_users') always false?

### ISSUE THREAD

**Issue by j-r-t** [WP-API/WP-API#2047]
https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-users-controller.php#L98

`var_dump(current_user_can( 'list_users' ));`

Is always false? 

I'm basically unable to list all users. A user is only output if content has been published, even being logged in as an admin.

**Comment by danielbachhuber** [comment]
How are you authenticating? If you're using cookie authentication, are you including a nonce in the request?
