### ISSUE TITLE
Status handling doesn't account for edit_published_posts

### ISSUE THREAD

**Issue by JakePT** [WP-API/WP-API#2050]
I'm trying out the API for the first time, and am enjoying it greatly, but I've run into one issue that I can't seem to get around.

The issue is a mismatch between how wp-admin handles post editing capabilities and the API does.

I have a Custom Post Type, `item`, and have `map_meta_cap` set to `true`, and `capabilitiy_type` set to `array( 'item', 'items' )`. I have given the Administrator role the all the capabilities, but only given Editor `edit_items` `edit_others_items` and `edit_published_items`. 

In wp-admin it works as expected, the user can edit existing Items, even ones created by others, but cannot publish new ones (only submit them for review), and they can't delete them. This is exactly what I want.

The problem is that with the API when an Editor submits an update to an Item, if the model's status is set to `publish` the API always checks for `current_user_can( $post_type->cap->publish_posts )`, even if the post was previously published.

**Comment by danielbachhuber** [comment]
Thanks for the report, @JakePT. We'll take a look into this when we have a moment.

**Comment by kadamwhite** [comment]
This seems fairly straightforward to fix, removing "Discussion" label. @adamsilverstein has volunteered to take a crack at this.

**Comment by adamsilverstein** [comment]
@JakePT 

Thanks for the bug report. I looked into this and have some follow up questions for you...

I reviewed the capability checks for updating content in both core and the REST API and they seem consistent.  When you try to edit a post that isn't your own, the API checks for `edit_others_posts` https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-posts-controller.php#L385

Your `edit_others_items` should be mapped to `edit_others_posts`, but apparently is not at the time of the request handling.  I'm going to dig in a bit more to see if I can tell what is happening and try to work on a unit test to reproduce the issue.

Can you provide any code snippets showing how you are setting up and using your custom post type, I'd like to try to reproduce locally? Are you **certain** these edits work in wp-admin but not via the api? 

How are you sending your api requests and are they authenticated? How are you making these/authenticating? Do you get an error back from the API when trying to make an update?

Can you test giving the user edit_posts edit_others_posts and edit_published_posts to see if that changes anything?.

**Comment by kadamwhite** [comment]
Recommend this be moved to trac for triage, in case we're able to repro

**Comment by adamsilverstein** [comment]
@JakePT Can you provide a code sample that reproduces this issue?

**Comment by adamsilverstein** [comment]
I opened a trac ticket to continue discussion of this potential issue: https://core.trac.wordpress.org/ticket/38483#ticket
