### ISSUE TITLE
Deleting post category

### ISSUE THREAD

**Issue by pelayopc** [WP-API/WP-API#2051]
I want to delete a catergory from one post via API.

I send DELETE method to /wp/v2/posts/<post_id>/categories/<term_id>
and i get "405.0 - Method Not Allowed"

What´s wrong?

thx

**Comment by danielbachhuber** [comment]
Did you include `force=true` in the request?

**Comment by pelayopc** [comment]
yes

**Comment by danielbachhuber** [comment]
Can you share the full request you're making, please? And the complete response?

**Comment by pelayopc** [comment]
i use vb.net, WebRequest

http://www.creditosvip.com/blog/wp-json/wp/v2/posts/91/categories/13
method DELETE
basic auth
param: force=true

Response: its a html web, but the important part is this:

<div class="content-container"> 
  <h3>Error HTTP 405.0 - Method Not Allowed</h3> 
  <h4>No se puede mostrar la página que busca porque se está usando un método no válido (verbo HTTP).</h4> 
</div>

**Comment by danielbachhuber** [comment]
Ok. The problem is that your web server doesn't support the `DELETE` method.

I'd recommend reaching out to your web host to see if they can enable support on your server.

**Comment by pelayopc** [comment]
ahm, ok, it works fine now
thx a lot
