### ISSUE TITLE
Plans to reinstate filtering taxonomy term collections?

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/WP-API#2065]
Way back in #401 we had added the ability to use `get_terms` arguments via the `filter` parameter on taxonomy term collections. Per #924 the beta plugins have removed that support: neither `/tags` nor `/categories` is listed as having any support for the `filter` query property, which has been borne out by my own testing on beta 10.

Lacking filter support for these collections makes it cumbersome for example to search for an individual term by slug: right now it appears my best approach is to `?search=the-term-slug`, then iterate through all returned posts until I find a match (for a generic slug `search` may bring many unrelated terms along for the ride).

I'd like to know whether there are any plans to reinstate this filtering ability, and if not, how querying for individual terms is likely to be handled in upcoming releases?

**Comment by danielbachhuber** [comment]
> neither /tags nor /categories is listed as having any support for the filter query property, which has been borne out by my own testing on beta 10.

I've filed a separate issue for this, as it merits some discussion #2066

> Lacking filter support for these collections makes it cumbersome for example to search for an individual term by slug: 

Why don't we just add a `slug` param to the terms endpoint?

**Comment by kadamwhite** [comment]
> Why don't we just add a slug param to the terms endpoint?

I believe a `slug` query is an important component of any slug-supporting collection, so if we went that route I'd suggest we add it to `/posts`, etc as well, for consistency.

**Comment by danielbachhuber** [comment]
I've added `slug` to `/wp/v2/categories`, `/wp/v2/tags`, `/wp/v2/posts`, and `/wp/v2/users`
