### ISSUE TITLE
Duplicate post with meta_key and meta_value filters when using page attribute

### ISSUE THREAD

**Issue by ghost** [WP-API/WP-API#2068]
Hi all,

I'am using wp rest api V2 and when I do :

> .../wp-json/wp/v2/custom_post_type?filter[meta_value][category]=16&filter[posts_per_page]=3&**page=1**

On this first page, I have the ID : 691, **668** and 671.

> .../wp-json/wp/v2/custom_post_type?filter[meta_value][category]=16&filter[posts_per_page]=3&**page=2**

On this second page,  I have the ID : 680, 682 and 684.

> .../wp-json/wp/v2/custom_post_type?filter[meta_value][category]=16&filter[posts_per_page]=3&**page=3**

And finaly, on this **third page**, I have the ID : **668**, 647 and 649.

From this moment, I have a problem on every next page because at least one of my older post reappears on the next pages.

Am I the only one who have this problem?

Thanks for the help.

**Comment by danielbachhuber** [comment]
@redacherifi Is this still a problem?

**Comment by ghost** [comment]
@danielbachhuber At that time, I had duplicates posts in my backoffice. But in my database, each entry had a unique id. So I think there was a conflict when I getting the list of the posts, not on the id but on the content (title, content...). It's anormal but I resolve it by removing duplicates.

**Comment by danielbachhuber** [comment]
Ok, thanks for letting us know.

**Comment by ghost** [comment]
@danielbachhuber I finaly found the true issue. In my request, I have many filters. Principally "filter[date_query][before]" based on the current time and a "filter[orderby]=date". But I have many posts in my database with the **same date** and when I want to filter them with the previous parameters, the flow will change on every request  because it can't filter only on the date!
I don't know how the request is executed but if you want to display the posts ten by ten for example, the first page will return ten posts and the second page can return you one of the previous post.
Now, I use the orderby on the ID field, in my case it's ok.
