### ISSUE TITLE
$HTTP_RAW_POST_DATA error on POST request

### ISSUE THREAD

**Issue by JasonHoffmann** [WP-API/WP-API#2078]
I'm currently using just the infrastructure of this plugin on WP version 4.4.1. I'm getting a weird error when setting up a POST request: 

`Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0.`

The function that I'm using (simplified somewhat) is:

```
function init() {
    add_action( 'rest_api_init', 'add_endpoint_to_rest_api' );
}

  function add_endpoint_to_rest_api() {
    $namespace = 'me/v1';
    $enpdpoint = 'custom_type';

    register_rest_route( $namespace, '/' . $endpoint . '/', array(
        array(
            'methods' => WP_REST_Server::READABLE,
            'callback' => 'endpoint_get_all',
        ),
        array(
            'methods' => WP_REST_Server::CREATABLE,
            'callback' => 'endpoint_create_single'
        )
    ));
}

   function endpoint_create_single( $request ) {
    if ( ! empty( $request['id'] ) ) {
        return new WP_Error( 'rest_post_exists', __( 'Cannot create existing post.' ), array( 'status' => 400 ) );
    }

    $prepared_post = new stdClass;

    // Post title.
    if ( isset( $request['title'] ) ) {
        if ( is_string( $request['title'] ) ) {
            $prepared_post->post_title = wp_filter_post_kses( $request['title'] );
        }
    }

    $prepared_post->post_type = 'custom_type';
    $prepared_post->post_status = 'publish';
    $post_id = wp_insert_post( $prepared_post, true );

    $response = array(
        'update' => 'true'
        );

    $response = rest_ensure_response( $response );
    $response->set_status( 201 );
    return $response;
}
```

Even if I completely edit the callback function to just return a plain response, I still get the same error. I can fix it by editing my php.ini file and changing "always_populate_raw_post_data" to -1 like it suggests, but I'm wondering why this is an error on a default setup (locally, haven't tested it on a live server yet) and figured I should report it.

**Comment by danielbachhuber** [comment]
@JasonHoffmann This an issue with [the rest API infrastructure](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/rest-api/class-wp-rest-server.php#L1176). Can you [open a Trac ticket](https://core.trac.wordpress.org/) and we'll get it addressed? Thanks

**Comment by JasonHoffmann** [comment]
No problem, I've never submitted a Trac ticket, is the way it is formatted above okay? (just being cautious)
