### ISSUE TITLE
Unicode character U+00B0 causing 500 server error

### ISSUE THREAD

**Issue by dleeward** [WP-API/WP-API#2106]
When posting into the content field using v2beta6, Unicode character U+00B0 (degree symbol) is causing a 500 server error. Can someone else try to replicate this?

**Comment by danielbachhuber** [comment]
Can you use `wp shell` to run the character through `wp_json_encode()` and see if you reproduce the error?

**Comment by danielbachhuber** [comment]
Hm, I can't reproduce with `wp_json_encode()`:

```
wp shell
wp> $d = '°'
string(2) "°"
wp> wp_json_encode( $d );
string(8) ""\u00b0""
wp> $d = "\u00b0";
string(6) "\u00b0"
wp> wp_json_encode( $d );
string(9) ""\\u00b0""
```

I'm not sure what else would be causing it. If you could offer specific reproduction steps, and see if they replicate on a stock install of WordPress, it would be helpful for further debugging.
