### ISSUE TITLE
OAuth in 4.5 core?

### ISSUE THREAD

**Issue by dleeward** [WP-API/WP-API#2107]
Will OAuth be part of core in WP v4.5? If it is, will it work on shared hosting without access to the cli? If not, are there plans to update the plugin to be able to install on shared hosting?

Sorry for the duplicate, but never got a response in the Oauth repository.

**Comment by danielbachhuber** [comment]
Good question. I'm not sure of the current plans with regards to OAuth. I've flagged this issue for a reply from @rmccue when he has a moment.

**Comment by danielbachhuber** [comment]
> Will OAuth be part of core in WP v4.5?

At this point, the answer is no.

Generally, auth in core beyond the cookie-based auth that's already there is still TBD. When there's a reasonably certain decision on direction, you'll hear about it.

**Comment by rmccue** [comment]
One thing to note though: the plugin now has UI and does not require CLI access.
