### ISSUE TITLE
Custom Post Type - Individual Posts are not Shown getting 404 error

### ISSUE THREAD

**Issue by rajesh-h** [WP-API/WP-API#2108]
Hi Team,

Thank you for this plugin.

I have a custom post type as part of a recipe plugin used on mysite, so I used method 2. on the below link

http://v2.wp-api.org/extending/custom-content-types/

``` php

/**
  * Add REST API support to an already registered post type.
  */
  add_action( 'init', 'my_custom_post_type_rest_support', 25 );
  function my_custom_post_type_rest_support() {
    global $wp_post_types;

    //be sure to set this to the name of your post type!
    $post_type_name = 'recipe';
    if( isset( $wp_post_types[ $post_type_name ] ) ) {
        $wp_post_types[$post_type_name]->show_in_rest = true;
        $wp_post_types[$post_type_name]->rest_base = $post_type_name;
        $wp_post_types[$post_type_name]->rest_controller_class = 'WP_REST_Posts_Controller';
    }

  }
```

I am able to get custom post type in following link, CPT= "recipe"

http://totest-cscom.rhcloud.com/wp-json/wp/v2/posts   - It includes the CPT related to recipe type

but when trying to fetch individual post which belong to that custom type, i get a 404 error. 4934 is a post which has type as recipe

http://totest-cscom.rhcloud.com/wp-json/wp/v2/posts/4934

Please help me here to resolve this

**Comment by danielbachhuber** [comment]
The proper endpoint for your CPT would be `/wp/v2/recipe`, which would fully resolve to:

http://totest-cscom.rhcloud.com/wp-json/wp/v2/recipe/4934

**Comment by danielbachhuber** [comment]
Also note: if you visit http://totest-cscom.rhcloud.com/wp-json/, you'll see an index of all registered routes. You can use a browser extension like [JSONView](https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc?hl=en) to see it in a more human-friendly view.

**Comment by rajesh-h** [comment]
@danielbachhuber Thank you very much for your response. I was aware of end point /wp/v2/recipe
I will try to explain what is happening.

I am working on creating app, I get list of posts in my home page using below link
http://totest-cscom.rhcloud.com/wp-json/wp/v2/posts 

now on  my home page i have both post types listed, that is post type="post" and CPT="recipe"

when i click on any post it redirects http://totest-cscom.rhcloud.com/wp-json/wp/v2/posts/postID

so if i click on post 4906 it comes back successfully because its post type is "post", but when i click on 4934 i get error as its end point is not correct. /wp/v2/posts/4934

how do i overcome this? am I supposed to use some sort of logic to get detail view of post from home page?

```
if /wp/v2/posts/4934 is error 
then
try /wp/v2/recipe/4934
end logic
```

**Comment by danielbachhuber** [comment]
> how do i overcome this? am I supposed to use some sort of logic to get detail view of post from home page?

You could, although the _proper_ way to add recipes to your REST API is to expose them entirely on a separate endpoint (e.g. `wp-json/wp/v2/receipes`) and fetch them in a separate request. They shouldn't be exposed within `wp-json/wp/v2/posts`

**Comment by rajesh-h** [comment]
Thank you @danielbachhuber I will follow your advise.

Thank you very much

**Comment by rajesh-h** [comment]
@danielbachhuber sorry to come back on this, I know it is suggested to use wp/v2/recipes/myCPTPostId  is there a way to bring using wp/v2/posts/myCPTPostId   this was possible in wp-api v1   can it be achieved in v2 as well?  

 I am asking because i am trying to use an app which works on wp/v2/posts/postId  endPoint  making it to use recipes/postId is taking lot of time. i need to rewrite most of the things on that app :(

**Comment by danielbachhuber** [comment]
> is there a way to bring using wp/v2/posts/myCPTPostId this was possible in wp-api v1 can it be achieved in v2 as well?

It would require a fair amount of custom code as it violates the design principles of WP-API v2.
