### ISSUE TITLE
Easier way of producing `WP_REST_Request` from a full URL

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#2109]
`WP_REST_Request` expects a clean path (e.g. `/wp/v2/categories`) on instantiation. If we want to programmatically test for valid links (#1815), then we need an easier way of creating a `WP_REST_Request` object from a full URL (e.g. `http://example.org/?rest_route=%2Fwp%2Fv2%2Fcategories&post=3`). Currently, it's a bit of a nightmare.

**Comment by danielbachhuber** [comment]
This is what it took:

```
$links = $response->get_links();
foreach( $links['https://api.w.org/term'] as $link ) {
    if ( 'category' === $link['attributes']['taxonomy'] ) {
        $categories_path = $link['href'];
    }
}
$query = parse_url( $categories_path, PHP_URL_QUERY );
parse_str( $query, $args );
$request = new WP_REST_Request( 'GET', $args['rest_route'] );
unset( $args['rest_route'] );
$request->set_query_params( $args );
$response = $this->server->dispatch( $request );
```

**Comment by rmccue** [comment]
We can also reuse this in `WP_REST_Server::embed_links`, which similarly resolves the links to a request. I'd suggest we move this to Trac as an infrastructure issue.

**Comment by danielbachhuber** [comment]
> I'd suggest we move this to Trac as an infrastructure issue.

Ok. I'll assign myself this issue until I have a moment to prepare a patch for Trac.

**Comment by danielbachhuber** [comment]
Created https://core.trac.wordpress.org/ticket/35803 with a patch.
