### ISSUE TITLE
Include tags and categories string array in posts

### ISSUE THREAD

**Issue by enoliglesias** [WP-API/WP-API#2113]
I think it would be ok to add in `wp-json/wp/v2/posts/` query an entry for post tags and post categories. Something like this:
- `"tags": ["tag1", "tag2", "tag3"]`
- `"categories": ["category1", "category2"]`

In order to do some quick simple searches by them and do not have to make and extra queries once you have the posts retrieved.

Regards!

**Comment by danielbachhuber** [comment]
In Beta 11, we'll be including the ids for tags and categories in the Post response #2032

You can use `?_embed` to get the full representation of the tags and categories in `_links`. For an introduction to linking, see this doc: http://v2.wp-api.org/extending/linking/

**Comment by enoliglesias** [comment]
Maybe this information could be util for someone. I had to add in

`'tags'         => wp_get_post_tags($post->ID),
'categories'   => wp_get_object_terms($post->ID, 'category'),`

**Comment by enoliglesias** [comment]
[removed]

**Comment by danielbachhuber** [comment]
@enoliglesias We don't recommend modifying the core plugin files, as those modifications will be overwritten when you upgrade.

The particular code snippet you've added will also break the API in unexpected ways, so I've removed it.

**Comment by enoliglesias** [comment]
Okay! Sorry. I've edited and removed the comment content.

Regards! :)
