### ISSUE TITLE
Should callbacks distinguish between URL and body params?

### ISSUE THREAD

**Issue by mineralwassermedium** [WP-API/WP-API#2114]
Hello

When I make a POST request to the endpoint /users/<id> to update data of a user, I can update any user. For example: 

I have two users: 

``` javascript
{id: 1, slug: 'user1'}
{id: 2, slug: 'user2'}
```

Now I am logged in as user1 and make the post request to the endpoint /users/1 with the request body:

``` javascript
{id: 2, slug: 'user3', first_name: 'Jon'}
```

and the former user2 is now

``` javascript
{id: 2, slug: 'user3', first_name: 'Jon'}
```

Is that supposed to work?

**Comment by danielbachhuber** [comment]
Internally, our callbacks don't currently distinguish between arguments included in the URL and arguments included in the body. Because you've included `id` in the body, it overrides the `id` specified by the named group regex for the path.

I'll flag this issue for discussion as to whether we should make our internal callbacks more precise. Thanks for reporting!

**Comment by danielbachhuber** [comment]
After some discussion, our callbacks should check the 'id' in the URL to be the most precise.

However, we need to change a lot of references to the `$request['id']`, and change many of our tests, in order to handle this.

**Comment by danielbachhuber** [comment]
#2260 is another reason we need to update all of our controllers:
- [x] Attachments
- [ ] Comments
- [ ] Statuses
- [ ] Types
- [ ] Taxonomies
- [ ] Terms
- [ ] Users

**Comment by BE-Webdesign** [comment]
For the update_item and update_item_permissions_check should the $id = (int) $request['id']; be changed to $id = (int) $request->get_url_params()['id'];  If that's is the case I can help out with these and can do that on the other controllers that would need this distinction.  If I misunderstand the problem let me know.  Thank you.

**Comment by danielbachhuber** [comment]
I appreciate the offer, @BE-Webdesign. There's a lot of code churn in these changes though, so I think it would be most efficient for me to just sweep through and make all of the changes.

I'll set aside some time in the next couple of days to mark some more [good first bugs](https://github.com/WP-API/WP-API/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Bug%22) if you're looking for issues to dive in on.

**Comment by BE-Webdesign** [comment]
Okay no problem @danielbachhuber.  I will get on the good first bugs that already exist in the meantime. If you have the time to answer, was I at least on the right track with the solution? I would like to know whether I am understanding the implementation of the API better or if I am completely not understanding it.

**Comment by danielbachhuber** [comment]
> If you have the time to answer, was I at least on the right track with the solution?

Yep, you were on the right track. However, `$request->get_url_params()['id']` requires PHP 5.4 (I believe), so you need to assign to a variable first.

**Comment by BE-Webdesign** [comment]
Thank you, good to know.

**Comment by danielbachhuber** [comment]
@WP-API/amigos Ran into two severe implementation issues with this, so I'm backing out of the decision to explicitly distinguish between url, body, and query params within our callbacks. Joe [was right](https://wordpress.slack.com/archives/core-restapi/p1455122071002434), I am wrong. We will live with `WP_REST_Request` permitting ambiguity between how the request variables are assigned.

The two issues were:
1. Default values are only injected with `WP_REST_Request->get_param()`, not when calling `WP_REST_Request->get_body_params()`. When you use the latter, and there's no value, you need to get the defaults as well.
2. Whenever we call `WP_REST_Request->get_body_params()`, we also need to call `WP_REST_Request->get_json_params()`, and inspect whichever actually has data. And, if neither has data, we need to get defaults again.

While these two issues are technical fixable, I'm concerned about the ceiling continuing to fall on my head as I fix them. Given the bias of `WP_REST_Request` is to permit ambiguity, and `WP_REST_Request-> get_parameter_order()` permits control of the ambiguity, I think we just need to live with `$request[ $key ]`
