### ISSUE TITLE
Should entities be be encoded in rendered?

### ISSUE THREAD

**Issue by joehoyle** [WP-API/WP-API#2115]
This might be a silly question - but should the rendered values (say for post title) have HTML entity encoding, or should they be the UTF-8 chars themselves. It seems to be we should be HTML agnostic, but I see html entities a fair bit - which WP will often store in the DB (via other crazyness)

**Comment by danielbachhuber** [comment]
Related #1227

I'd _think_ we should convert them to UTF-8, but I don't know if it's safe to do so.

There's a core ticket somewhere about how storing HTML entities in the database is a bug in the first place.

**Comment by rmccue** [comment]
I'd be OK with decoding this so long as fields that are _actually_ HTML don't get converted; i.e. the post title is actually HTML content, so we can't decode this.

**Comment by danielbachhuber** [comment]
Closing in favor of #1227
