### ISSUE TITLE
Can´t create new post

### ISSUE THREAD

**Issue by pelayopc** [WP-API/WP-API#2116]
I did work with the api in blogs without any problem, but now i create a new blog in a new server, all plugins ok, basic auth, etc. but now when i create a new post i get this response from the api:
{
  "code": "rest_cannot_create",
  "message": "Sorry, you are not allowed to create new posts.",
  "data": {
    "status": 401
  }
}

all plugins in server are ok like in the other blogs where it works fine, user and password are ok, i don´t know what could be the problem here.

With categories, tags, etc, i get the same response from api when i try to create new one

**Comment by danielbachhuber** [comment]
> all plugins in server are ok like in the other blogs where it works fine, user and password are ok, i don´t know what could be the problem here.

It's hard to say what the issue might be without additional detail. When you open support tickets, please try to share as much detail as possible, otherwise the only help we can provide is asking follow-up questions.

Can you share the full request you're making, and all of the debugging you've done? And, to confirm, the authentication plugin is activated?

**Comment by pelayopc** [comment]
Ok Sorry, finally it was a problem in the server rewrite mod 
thx a lot

**Comment by HikmetTenis** [comment]
how did you resolve this? can you give me details please?

**Comment by dooch** [comment]
Hi there, 

I think I am experiencing the same issue. I have a self hosted site setup. And I have Wordpress oAuth Server setup on it too. The oAuth Server is setup correctly as I am able to receive tokens etc, and I can delete posts.

However when I want to create a new post using the apis, I get the same error: 

POST: 
http://streetartcritic.com/wp-json/wp/v2/posts/?access_token=c3fykfkvt14uo8dguykfc9ssgqnr8feban4xrq8h

BODY:
{
    "title": "this is my new post sent from PostMan",
    "content": "This is the content",
    "status": "publish",
    "author": 4
}

Error Message:
{
  "code": "rest_cannot_edit_others",
  "message": "You are not allowed to create posts as this user.",
  "data": {
    "status": 401
  }
}

incase you want to test it the Callback URL is https://www.getpostman.com/oauth2/callback

**Comment by Bundas** [comment]
@dooch Hi, did you resolve that? I have same problem and I have no fu**ing idea how to fix it

**Comment by rmccue** [comment]
> However when I want to create a new post using the apis, I get the same error:

You appear to be using OAuth 2. We only support OAuth 1.0a with [the OAuth 1 plugin](https://github.com/WP-API/OAuth1); if you're using a third party authentication plugin, please contact the author of that plugin.

**Comment by robtown** [comment]
I'm having the same issue.
I'm using the oauth 1.0 server plugin and angular-oauth1-client in my ionic project. 
The first part of the authentication process seems to work. 
But the wordpress API doesn't seem to think I'm a logged in user.

**Comment by der-lukas** [comment]
@pelayopc can you explain what your fix was for this issue? I'm having the same setup with basic auth - it also worked for me on another server - but now I don't get it to work and all I get are 401's...

**Comment by pelayopc** [comment]
I can´t resolve my fix.
On my server shared they do not want to change the configuration necessary for the api function properly , it is a problem of server permissions settings on verbs when the API call is made.
At least with the basic authentication method could not solve the problem , we had to move to a dedicated server where you can set these permissions without problems

**Comment by der-lukas** [comment]
okay I see - because yesterday I at least found the solution for my scenario! I had to add the following rewrite rules to .htaccess:

```
# BEGIN WP BASIC Auth
<IfModule mod_rewrite.c>
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
</IfModule>
# END WP BASIC Auth
```

Found the snippet here: http://stackoverflow.com/a/36499422/3754201

Also found this thread, where more rules are suggested concerning OAuth1: https://github.com/WP-API/OAuth1/issues/81

**Comment by 95289527** [comment]
@der-lukas  hi ,do you know the rules for nginx

**Comment by GuillaumeValadas** [comment]
@der-lukas @pelayopc Thanks guys that works for me you save my day !

**Comment by yuonoda** [comment]
Hi there,
does anyone know how to fix this problem on Nginx server ?
