### ISSUE TITLE
On new post creation, categories weren't inserted.

### ISSUE THREAD

**Issue by acdarekar** [WP-API/WP-API#2117]
Hi, When I make a POST call to `/posts` endpoint with JSON data, post is created but categories are not.

The JSON array I'm submitting is:

```
{
    "title":"This is a post",
    "status":"publish",
    "content":"This is some content",
    "excerpt":"some content",
    "categories": ["Jokes", "Humor"]
}
```

Am I doing it wrong?

**Comment by danielbachhuber** [comment]
`categories` needs to be the term ids for already created categories.

If the categories aren't created already, you can create them with `POST /wp/v2/categories`

**Comment by mjacobsen4DFM** [comment]
Having the same issue.
Here is my post:

<pre><code>{
  "date":"2016-01-26T19:39:40+00:00",
  "title":"In Oscars crisis, Chris Rock and a microphone loom large",
  "categories":["106"],
  "content":"Chris Rock first hosted the Oscars in 2005...",
  "excerpt":"Chris Rock at the Oscars"
}</code></pre>

Here is the associated category:

<pre><code>{
  "id":106,
  "count":0,
  "description":"AP-33330",
  "link":"http:\/\/example.com\/category\/ap-premium-entertainment-movies\/","name":"AP Premium Entertainment - Movies",
  "slug":"ap-premium-entertainment-movies",
  "taxonomy":"category",
  "parent":0,
  "_links":{
     "self":[{"href":"http:\/\/example.com\/wp-json\/wp\/v2\/categories\/106"}],
     "collection":[{"href":"http:\/\/example.com\/wp-json\/wp\/v2\/categories"}],
     "about":[{"href":"http:\/\/example.com\/wp-json\/wp\/v2\/taxonomies\/category"}]
  }
}</code></pre>

So...am I doing it wrong?

**Comment by danielbachhuber** [comment]
@mjacobsen4DFM Although you're passing the id as a string, it seems like it should work. Can you share the full request and response, with any debugging you've done?

**Comment by mjacobsen4DFM** [comment]
I changed the type to Integer. No joy.

Post Post:

<pre>
{
   "date":"2016-01-26T21:45:20+00:00",
   "title":"After setting iPhone record, Apple forecasts rare sales drop",
   "categories":[
      24
   ],
   "content":"<p>SAN FRANCISCO (AP) &#8212; Apple is bracing for its first sales decline in 13 years, despite selling a record 74.8 million iPhones in the final three months of 2015.</p><p>The giant tech company issued a sales forecast that says revenue could fall at least 8.6 percent during the January-March quarter, compared with a year earlier. Analysts say the latest iPhone models are selling reasonably well, but they're not providing the boost Apple needs to match the massive sales growth it enjoyed last year.</p><p>The company inched past its previous record, established when it sold 74.5 million iPhones in the holiday quarter of 2014. But its forecast implies Apple doesn't expect to match the 61 million iPhones sold in last year's January-March quarter.</p><p>Apple counts on the iPhone for two-thirds of its revenue.</p>",
   "excerpt":"SAN FRANCISCO (AP) &#8212; Apple is bracing for its first sales decline in 13 years, despite selling a record 74.8 million iPhones in the final three months of 2015.",
   "images":[
      {
      }
   ]
}
</pre>

Response:
Code=201

<pre>
{
   "id":21856,
   "date":"2016-01-26T21:45:20",
   "date_gmt":"2016-01-26T21:45:20",
   "guid":{
      "rendered":"http:\/\/example.com\/?p=21856",
      "raw":"http:\/\/example.com\/?p=21856"
   },
   "modified":"2016-01-26T21:45:20",
   "modified_gmt":"2016-01-26T21:45:20",
   "password":"",
   "slug":"",
   "status":"draft",
   "type":"post",
   "link":"http:\/\/example.com\/?p=21856",
   "title":{
      "raw":"After setting iPhone record, Apple forecasts rare sales drop",
      "rendered":"After setting iPhone record, Apple forecasts rare sales drop"
   },
   "content":{
      "raw":"<p>SAN FRANCISCO (AP) &#8212; Apple is bracing for its first sales decline in 13 years, despite selling a record 74.8 million iPhones in the final three months of 2015.<\/p><p>The giant tech company issued a sales forecast that says revenue could fall at least 8.6 percent during the January-March quarter, compared with a year earlier. Analysts say the latest iPhone models are selling reasonably well, but they're not providing the boost Apple needs to match the massive sales gro"
</pre>

(Above return is truncated, just as it is from the response object.)

GET Post:

<pre>
{
   "id":21856,
   "date":"2016-01-26T21:45:20",
   "date_gmt":"2016-01-26T21:45:20",
   "guid":{
      "rendered":"http:\/\/example.com\/?p=21856"
   },
   "modified":"2016-01-26T21:45:20",
   "modified_gmt":"2016-01-26T21:45:20",
   "slug":"",
   "type":"post",
   "link":"http:\/\/example.com\/?p=21856",
   "title":{
      "rendered":"After setting iPhone record, Apple forecasts rare sales drop"
   },
   "content":{
      "rendered":"<p>SAN FRANCISCO (AP) &#8212; Apple is bracing for its first sales decline in 13 years, despite selling a record 74.8 million iPhones in the final three months of 2015.<\/p>\n<p>The giant tech company issued a sales forecast that says revenue could fall at least 8.6 percent during the January-March quarter, compared with a year earlier. Analysts say the latest iPhone models are selling reasonably well, but they&#8217;re not providing the boost Apple needs to match the massive sales growth it enjoyed last year.<\/p>\n<p>The company inched past its previous record, established when it sold 74.5 million iPhones in the holiday quarter of 2014. But its forecast implies Apple doesn&#8217;t expect to match the 61 million iPhones sold in last year&#8217;s January-March quarter.<\/p>\n<p>Apple counts on the iPhone for two-thirds of its revenue.<\/p>\n"
   },
   "excerpt":{
      "rendered":"<p>SAN FRANCISCO (AP) &#8212; Apple is bracing for its first sales decline in 13 years, despite selling a record 74.8 million iPhones in the final three months of 2015.<\/p>\n"
   },
   "author":8,
   "featured_image":0,
   "comment_status":"open",
   "ping_status":"open",
   "sticky":false,
   "format":"standard",
   "_links":{
      "self":[
         {
            "href":"http:\/\/example.com\/wp-json\/wp\/v2\/posts\/21856"
         }
      ],
      "collection":[
         {
            "href":"http:\/\/example.com\/wp-json\/wp\/v2\/posts"
         }
      ],
      "about":[
         {
            "href":"http:\/\/example.com\/wp-json\/wp\/v2\/types\/post"
         }
      ],
      "author":[
         {
            "embeddable":true,
            "href":"http:\/\/example.com\/wp-json\/wp\/v2\/users\/8"
         }
      ],
      "replies":[
         {
            "embeddable":true,
            "href":"http:\/\/example.com\/wp-json\/wp\/v2\/comments?post=21856"
         }
      ],
      "version-history":[
         {
            "href":"http:\/\/example.com\/wp-json\/wp\/v2\/posts\/21856\/revisions"
         }
      ],
      "https:\/\/api.w.org\/attachment":[
         {
            "href":"http:\/\/example.com\/wp-json\/wp\/v2\/media?parent=21856"
         }
      ],
      "https:\/\/api.w.org\/term":[
         {
            "taxonomy":"category",
            "embeddable":true,
            "href":"http:\/\/example.com\/wp-json\/wp\/v2\/posts\/21856\/categories"
         },
         {
            "taxonomy":"post_tag",
            "embeddable":true,
            "href":"http:\/\/example.com\/wp-json\/wp\/v2\/posts\/21856\/tags"
         },
         {
            "taxonomy":"post_format",
            "embeddable":true,
            "href":"http:\/\/example.com\/wp-json\/wp\/v2\/posts\/21856\/post_format"
         }
      ],
      "https:\/\/api.w.org\/meta":[
         {
            "embeddable":true,
            "href":"http:\/\/example.com\/wp-json\/wp\/v2\/posts\/21856\/meta"
         }
      ]
   }
}
</pre>

GET Categories:

<pre>[
   {
      "id":1,
      "count":0,
      "description":"",
      "link":"http:\/\/example.com\/category\/uncategorized\/",
      "name":"Uncategorized",
      "slug":"uncategorized",
      "taxonomy":"category",
      "parent":0,
      "_links":{
         "self":[
            {
               "href":"http:\/\/example.com\/wp-json\/wp\/v2\/categories\/1"
            }
         ],
         "collection":[
            {
               "href":"http:\/\/example.com\/wp-json\/wp\/v2\/categories"
            }
         ],
         "about":[
            {
               "href":"http:\/\/example.com\/wp-json\/wp\/v2\/taxonomies\/category"
            }
         ]
      }
   }
]
</pre>

Debugging doesn't hit any errors.
Using WP-API Version 2.0-beta9
