### ISSUE TITLE
Set post tags

### ISSUE THREAD

**Issue by pelayopc** [WP-API/WP-API#2123]
Now with the last update how can i set a tag to a existing post?

before the update, this works fine:
wp-json/wp/v2/posts/-postid-/tags/-tagid-

Similar with categories

**Comment by rmccue** [comment]
All you need to do is send the tags array in the post data without the tags you want to remove. If you have `1, 2, 4` for example, you'd send just `1, 2` as the tags value to remove tag `4`.

**Comment by pelayopc** [comment]
Them now i need two requests to setone tag to a post, one to get de tags array from post, and another one to set the new one?
