### ISSUE TITLE
Inconsistent results on /categories?page=0

### ISSUE THREAD

**Issue by arsu-leo** [WP-API/WP-API#2124]
When i query to mySite.com/wp-json/wp/v2/categories?page=0
I get the same results as page 2. 
Does it make sense?
If the parameter is index 1 based, shouldn't it be ignored?

Thanks for your time.

Btw: this took me some headaches until i realized it

**Comment by danielbachhuber** [comment]
Sorry about this issue. Similar to #2209, we should validate `page` to ensure it's 1 or greater. If you supply 0, you should get an error that 1 is the minimum value.

**Comment by danielbachhuber** [comment]
Validation will be really simple with #2213
