### ISSUE TITLE
wp_api.js in 2.0-beta11

### ISSUE THREAD

**Issue by mineralwassermedium** [WP-API/WP-API#2125]
WP_API_Settings is now wpApiSettings. Should be changed in the documentation. 

http://v2.wp-api.org/guide/authentication/

**Comment by adamsilverstein** [comment]
good point @mineralwassermedium! thanks for catching that.  Can you please make a pull request against the [docs repo](https://github.com/WP-API/docs-v2) with the fixes?

Thanks!

**Comment by adamsilverstein** [comment]
Thanks again, closing this as a duplicate of https://github.com/WP-API/docs-v2/issues/101.

**Comment by mineralwassermedium** [comment]
Sorry I dont know how pull request works, I am very new to git and github

**Comment by adamsilverstein** [comment]
No worries @mineralwassermedium I will get it fixed; thanks for making the effort of opening the issue. I think in github you can click 'edit' on a file and from there lead to a pull request! I haven't used this approach as I run git locally.
