### ISSUE TITLE
Alter output of API

### ISSUE THREAD

**Issue by fschroiff** [WP-API/WP-API#2127]
Our production server is hooked up to a CDN. The rendered output of WP is rewritten to have asset urls point to the CDN.

This does not work for the output of the WP REST API. I'd like to alter the output of the WP REST API via functions.php to contain the CDN URL of an image instead of the local URL.

For my use case this only has to work for featured images of a post-type called "check".

URLs looking like this `http://example.com/wp-content/uploads/image.jpg` would have to be changed to `http://cdn.com/wp-content/uploads/image.jpg`.

I am running WordPress 4.4.1 and version 2.0-beta10 of the WP REST API plugin.

I do this request: `https://check.museumrotterdam.nl/wp-json/wp/v2/check-api?_embed`. The `source_url` value should be changed.

Which filter do I need to use?

**Comment by danielbachhuber** [comment]
There isn't a good filter for this, in fact. `rest_post_dispatch` will [let you filter the main resource](https://developer.wordpress.org/reference/hooks/rest_post_dispatch/), but it won't be applied to any thinks that are embedded.

If all you need to do is rewrite asset URLs to the CDN, I might recommend filtering a bit lower in the stack. WP-API uses all of the `wp_get_attachment_*()` functions, which offer corresponding filters.

**Comment by westonruter** [comment]
Isn't this what [#35628](https://core.trac.wordpress.org/ticket/35628) is about?

**Comment by danielbachhuber** [comment]
> Isn't this what #35628 is about?

Yep

**Comment by fschroiff** [comment]
Thanks for the info! This'll do the trick: 

``` php
add_filter('wp_get_attachment_url', 'cdn_for_attachment');
function cdn_for_attachment($url) {
  $localUrl = site_url(FALSE, 'http');
    $cdnUrl = 'https://example.com/'; //your CDN URL
    return str_replace($localUrl, $cdnUrl, $url);
}
```
