### ISSUE TITLE
GET fails for META using Basic Auth

### ISSUE THREAD

**Issue by mjacobsen4DFM** [WP-API/WP-API#2129]
Using basic auth as a site _admin_, most functions work, but GET META fails.

GET post = http://example.com/wp-json/wp/v2/posts/1522092
`{"id":1522092,"date":"2015-12-12T04:23:18","date_gmt":"2015-12-12T16:23:18","guid":{"rendered":"http:\/\/example.com?p=1522092&#038;preview_id=1522092"},"modified":"2016-01-26T16:32:41","modified_gmt":"2016-01-26T22:32:41","slug":"heres-what-it-will-take-for-ford-site-to-become-a-st-paul-neighborhood","type":"post","link":"http:\/\/example.com\/2015\/12\/12\/heres-what-it-will-take-for-ford-site-to-become-a-st-paul-neighborhood\/","title":{"rendered":"Here&#8217;s what it will take for Ford site to become a  St. Paul neighborhood"},"content":{"rendered":"<p>&nbsp;<\/p>\n<p>For nearly a century...lots of text"},"excerpt":{"rendered":"<p>&nbsp; For nearly a century...  less text"},"author":7,"featured_image":0,"comment_status":"open","ping_status":"open","sticky":false,"format":"standard","_links":{"self":[{"href":"http:\/\/example.com\/wp-json\/wp\/v2\/posts\/1522092"}],"collection":[{"href":"http:\/\/example.com\/wp-json\/wp\/v2\/posts"}],"about":[{"href":"http:\/\/example.com\/wp-json\/wp\/v2\/types\/post"}],"author":[{"embeddable":true,"href":"http:\/\/example.com\/wp-json\/wp\/v2\/users\/7"}],"replies":[{"embeddable":true,"href":"http:\/\/example.com\/wp-json\/wp\/v2\/comments?post=1522092"}],"version-history":[{"href":"http:\/\/example.com\/wp-json\/wp\/v2\/posts\/1522092\/revisions"}],"https:\/\/api.w.org\/attachment":[{"href":"http:\/\/example.com\/wp-json\/wp\/v2\/media?parent=1522092"}],"https:\/\/api.w.org\/term":[{"taxonomy":"category","embeddable":true,"href":"http:\/\/example.com\/wp-json\/wp\/v2\/posts\/1522092\/categories"},{"taxonomy":"post_tag","embeddable":true,"href":"http:\/\/example.com\/wp-json\/wp\/v2\/posts\/1522092\/tags"},{"taxonomy":"post_format","embeddable":true,"href":"http:\/\/example.com\/wp-json\/wp\/v2\/posts\/1522092\/post_format"},{"taxonomy":"post_status","embeddable":true,"href":"http:\/\/example.com\/wp-json\/wp\/v2\/posts\/1522092\/post_status"},{"taxonomy":"ad_taxonomy","embeddable":true,"href":"http:\/\/example.com\/wp-json\/wp\/v2\/posts\/1522092\/ad_taxonomy"},{"taxonomy":"feature","embeddable":true,"href":"http:\/\/example.com\/wp-json\/wp\/v2\/posts\/1522092\/feature"},{"taxonomy":"print_status","embeddable":true,"href":"http:\/\/example.com\/wp-json\/wp\/v2\/posts\/1522092\/print_status"}],"https:\/\/api.w.org\/meta":[{"embeddable":true,"href":"http:\/\/example.com\/wp-json\/wp\/v2\/posts\/1522092\/meta"}]}}`

GET tags = http://example.com/wp-json/wp/v2/posts/1522092/tags
`[{"id":238,"count":5957,"description":"News","link":"http:\/\/example.com\/tag\/ramsey-county\/","name":"Ramsey County","slug":"ramsey-county","taxonomy":"post_tag","_links":{"self":[{"href":"http:\/\/example.com\/wp-json\/wp\/v2\/tags\/238"}],"collection":[{"href":"http:\/\/example.com\/wp-json\/wp\/v2\/tags"}],"about":[{"href":"http:\/\/example.com\/wp-json\/wp\/v2\/taxonomies\/post_tag"}]}}]`

GET categories = http://example.com/wp-json/wp/v2/posts/1522092/categories
`[{"id":19,"count":401511,"description":"","link":"http:\/\/example.com\/section\/news\/","name":"News","slug":"news","taxonomy":"category","parent":0,"_links":{"self":[{"href":"http:\/\/example.com\/wp-json\/wp\/v2\/categories\/19"}],"collection":[{"href":"http:\/\/example.com\/wp-json\/wp\/v2\/categories"}],"about":[{"href":"http:\/\/example.com\/wp-json\/wp\/v2\/taxonomies\/category"}]}}]</pre>`

GET meta = http://example.com/wp-json/wp/v2/posts/1522092/meta
**`{"code":"rest_forbidden","message":"Sorry, you cannot view the meta for this post.","data":{"status":401}}`**

What is special about meta that it would complain? Or am I calling it wrong? It seems pretty straight forward here: http://v2.wp-api.org/reference/posts/meta.html
Just call a GET on the URL:

`GET /wp/v2/posts/<parent_id>/meta`
Example Request

`$ curl http://demo.wp-api.org/wp-json/wp/v2/posts/<parent_id\>/meta`

 (as I did above).

**Comment by mjacobsen4DFM** [comment]
For the record, the post does have meta data:

<pre>meta_id    post_id meta_key        meta_value
6468772 1522092 original_source     http://example.com/localnews/29237370/seo-friendly-url
6468773 1522092 original_byline     By Prolific Author
6468774 1522092 discovered_authors  (prolific-author)
6468775 1522092 original_email      aprolific@example.com
6468776 1522092 original_pubdate    12/12/2015 10:23:18 AM
6468777 1522092 original_id     29237370
6468778 1522092 original_category   news
6468779 1522092 _wpas_done_all      1
6468784 1522092 wide_assets 
6474160 1522092 _edit_lock      1453923180:7
</pre>

**Comment by danielbachhuber** [comment]
Because your response is returning `status:401`, this means the WP REST API is interpreting it as a logged out request. Accessing post meta requires both authentication (user is logged in) and authorization (user has permission to edit the post).

I'd recommend double-checking to make sure your Basic Auth header is set properly, and authentication works as expected.

**Comment by mjacobsen4DFM** [comment]
Thank you, @danielbachhuber
The odd thing then is that I do the meta call between tags and categories, and they authenticate fine, so clearly the header and authentication work as expected..

**Comment by danielbachhuber** [comment]
> The odd thing then is that I do the meta call between tags and categories, and they authenticate fine, so clearly the header and authentication work as expected..

How do you know that they authenticate fine? Getting tags and categories doesn't require authentication.

**Comment by mjacobsen4DFM** [comment]
Interesting. I assumed they all did. If the others do not, why does meta require auth?

**Comment by danielbachhuber** [comment]
> If the others do not, why does meta require auth?

See #2149
