### ISSUE TITLE
Can't filter posts by slug?

### ISSUE THREAD

**Issue by marceloemanoel** [WP-API/WP-API#2135]
Hi, guys.

First of all, congratulations. This project helped me a lot!
I'm using the demo api to try to filter posts and pages by slug. 
But when I submit a GET to 

http://demo.wp-api.org/wp-json/wp/v2/posts?slug=sunt-velit-consectetur-nobis-non or
http://demo.wp-api.org/wp-json/wp/v2/pages?slug=voluptatem-est-laborum-doloribus

I'm getting a different result than what I expect which would be to get only post with id 123 or page with id 113. Instead I'm receiving a list of posts or pages that apparently doesn't belong to the query result.

Am I doing something wrong?

Thanks in advance.

**Comment by danielbachhuber** [comment]
I think `demo.wp-api.org` is still using an older version of the API. Have you tried Beta 11 locally?

**Comment by marceloemanoel** [comment]
Hi @danielbachhuber I haven't tried on a local machine. I'll try it when I get home.

**Comment by marceloemanoel** [comment]
Hi @danielbachhuber, I've installed and tried the Beta 11 version. 
It worked fine.    

Thanks!
