### ISSUE TITLE
Support - Get Multiple Custom Fields in one rest_api_init  request

### ISSUE THREAD

**Issue by rajesh-h** [WP-API/WP-API#2137]
Hi ,

I am going through this 
http://v2.wp-api.org/extending/modifying/

Is it possible to register multiple fields in below code? The example specified uses only one custom field that is **starship**.  What if i have another custom field as **warship**, can i register in same **rest_api_init** request?

```
<?php
add_action( 'rest_api_init', 'slug_register_starship' );
function slug_register_starship() {
    register_rest_field( 'post',
        'starship',
        array(
            'get_callback'    => 'slug_get_starship',
            'update_callback' => null,
            'schema'          => null,
        )
    );
}

/**
 * Get the value of the "starship" field
 *
 * @param array $object Details of current post.
 * @param string $field_name Name of field.
 * @param WP_REST_Request $request Current request
 *
 * @return mixed
 */
function slug_get_starship( $object, $field_name, $request ) {
    return get_post_meta( $object[ 'id' ], $field_name, true );
}
```

**Comment by ekweible** [comment]
I have this same question. I'm currently using this in combination with the Advanced Custom Fields plugin to add several custom fields to the response. I can retrieve all of the custom fields with a single call to ACF's `get_fields()`, so being able to add all of these fields in a single callback would be the most performant.

**Comment by danielbachhuber** [comment]
> Is it possible to register multiple fields in below code? The example specified uses only one custom field that is starship. What if i have another custom field as warship, can i register in same rest_api_init request?

Sure, try something like this:

```
add_action( 'rest_api_init', 'slug_register_fields' );
function slug_register_fields() {
    foreach( array( 'starship', 'warship' ) as $field ) {
        register_rest_field( 'post',
            $field,
            array(
                'get_callback'    => 'slug_get_starship',
                'update_callback' => null,
                'schema'          => null,
            )
        );
    }
}

/**
 * Get the value of the "starship" field
 *
 * @param array $object Details of current post.
 * @param string $field_name Name of field.
 * @param WP_REST_Request $request Current request
 *
 * @return mixed
 */
function slug_get_starship( $object, $field_name, $request ) {
    return get_post_meta( $object[ 'id' ], $field_name, true );
}
```

**Comment by rajesh-h** [comment]
Thank you @danielbachhuber, this works as expected.
