### ISSUE TITLE
Every request returning null response

### ISSUE THREAD

**Issue by kdpuvvadi** [WP-API/WP-API#2138]
Every request i sent returning with null response expect `/wp-json/wp/v2/` and other than that i'm getting null for very endpoint on the site

**Comment by danielbachhuber** [comment]
Sorry, but it's hard to say what this issue might be without having more detail.

To debug your current environment, I might recommend deactivating all of your plugins, and switching to the Twenty Sixteen theme, and then re-activating them one by one to diagnose which might be causing it.

Alternatively, if you'd just like to start using the API, you can set up a new WordPress install for it.

**Comment by kdpuvvadi** [comment]
i've deactivated every plugin, switched to 2016 theme. and hosted on Ubuntu VPS(azure), nginx 1.8, mysql 5.5, wordpress 4.4.1, still getting the problem, as an android app using this api, they are getting errors as it is giving null for every request, and none of the changes were made to the site for the past week except publishing the posts for API
