### ISSUE TITLE
Consider returning refreshed NONCE with any nonce-auth'd request

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/WP-API#2146]
At the WP-API hack day following the Day of REST event, the auth/clients working group identified that the existing nonce auth solution for client-js would lead to an eventual auth timeout because there is no way for the backbone client to obtain an updated nonce.

@adamsilverstein to clarify

**Comment by danielbachhuber** [comment]
Oh, huh. Good idea. Should we include in a `X-WP-Nonce` header?

**Comment by adamsilverstein** [comment]
@danielbachhuber - I think returning in a header makes perfect sense. Once this is available, clients using cookie authentication can grab the new nonce and use it for subsequent requests. That way, as long as a request is made at least once every 12 hours, the application should always have a valid nonce.

**Comment by adamsilverstein** [comment]
Working up a core patch and ticket for this as this belongs in already merged infrastructure.

**Comment by danielbachhuber** [comment]
Closing in favor of https://core.trac.wordpress.org/ticket/35662
