### ISSUE TITLE
ADOR '16 Hack Day - Documentation team

### ISSUE THREAD

**Issue by ifyouwillit** [WP-API/WP-API#2147]
Questions: 
What's the best way for documentation to be presented?
We should have more examples in documentation
Should we integrate with code reference?

Areas of documentation
    Comments
    API reference
    Landing page
    Endpoints responses
    Extending the API
    Examples

Good examples of documentation
    Stripe
    Backbone
    Twilio
    Trello
    GitHub API console
    Digital Ocean

What we can do today?
    Tutorials
    Code snippets / examples
    Landing page
        Marketing
        Slack channel
        How to contribute
        Ask for feedback
    Solve general deficiencies in GitHub documentation
        Technical FAQ - Use case - answer / example
    Get V2 to the level of V1

Tom - Changing title of V1 / re-directing doc to V2
Kirsten / Jack - Make more responsive
Mendel / Vitor - Audit V1 -> V2
Aaron - Commit

**Comment by aaronjorbin** [comment]
Today, the Docs team:

1) Formally Deprecated v1 documentation
2) Removed ADoR banner on the documentation 
3) Worked on migrating examples and guides from v1 to v2
4) Started making docs responsive
5) Started listing out actual responses and filling out v2 docs

**Comment by danielbachhuber** [comment]
@ifyouwillit @aaronjorbin could be break this into some actionable issues for the docs repo?

**Comment by ifyouwillit** [comment]
@danielbachhuber good point. @aaronjorbin was there any work completed after your report?
