### ISSUE TITLE
ADOR '16 Auth/Clients team notes

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/WP-API#2148]
Action items from this discussion largely impact the individual client repos,
- [redefining/rest-api-client](https://github.com/redefining/rest-api-client)
- [kadamwhite/wordpress-rest-api](https://github.com/kadamwhite/wordpress-rest-api)
- [wp-api/client-js](https://github.com/wp-api/client-js)

or on the oauth plugin repository. The exception is #2146, which would support a authentication issue (WP-API/client-js#82) within client-js where nonce-based authentication will eventually time out within a long-lived application.
## Discussion summary:
- Auth situation is terrible
  - Need better documentation
  - OAuth server plugin could use some more work to make it user friendly, we have some ideas that we’ll open as issues
  - Client authors (Adam, KAdam, Nigel) are going to investigate OAuth1 prior art
  - Client authors are going to investigate implementing OAuth1
  - Open issue on wp-api to discuss sending refreshed nonces as a response header when responding to authenticated responses, so that client-side nonce can be refreshed
  - Investigate what actually is happening with cookie authentication?
    - Difference between wp-admin auth cookie & login cookie?
- Embedding & linking data
  - Tough to draw a line between transforming responses (usability), vs returning them directly (performance/consistency)
  - KAdam to explore providing a hook that can be used to transform embedded data into more useful structures
- Discovery
  - KAdam & Nigel exploring schema-based discovery & generation.
## Full team notes:
- In Attendance:
  - [KAdam](/kadamwhite) (USA) - node client
  - Costas (Greece) - work w/ WP themes - really interested in desktop applications, w/ electron
  - Ibon (Bilbao) - develop w/ wordpress, more int he community field, so here to learn, to talk about it in WP meetups
  - [Nigel](nb) (Bristol) - PHP developer, number of years w/ WP; interested in a PHP client, PSR7 standard (wants to write an API client that uses PSR7)
  - [Arto](/artoliukkonen) (Finland) - Front-end/fullstack dev, been doing FB apps for years, global maps api, twitter; currently looking to use WP API to replace "contentful"
  - [Adam](/adamsilverstein) (10up) - Maintainer of “client-js” bundled Backbone client
  - Nikolay (Bulgaria) - work on Automattic dev exp team
  - Andrei (Romania) - Build themes & plugins, willing to implement api in themes, want to get the most of it. Interested in auth.
- Auth is key for clients
  - how does it work for client-js?
    - Cookie-based auth, passes the nonce as part of the request (always)
      - Nikolay: How does it get refreshed?
      - Adam: Nonce injected through localization - it’ll expire at some point.
      - KAdam: client-js will effectively time out then.
  - Tangent: Ryan’s lurking. Core app passwords?
    - Team’s been working on how we make things more secure; 2FA and App Passwords. App Passwords is almost like key authentication; not sure what current status is. They’ve paused 2FA to focus on app passwords.
    - That is semi-related to how oauth works; oauth is a standard for issuing keys and having delegated access to an account. App Pass is semi-delegated auth.
    - George Stephanis’s group
  - Nikolay:
    - From auth standpoint, biggest concern: they had a few trials w/ rest api, auth was always the first roadblock. Some people implemented some of the oauth 2 flow, using oauth 1, which sucked on a few levels. Basically the same as OAuth 2 w/out https, in a hacky way.
  - Ryan:
    - OAuth 2 pushes signature stuff up to https, for security. WP does not require https, so OAuth 2 is infeasible: 14% of WP sites have SSL
    - In the meantime they need an auth flow that doesn’t need SSL
    - OAuth2 is a pretty good standard, OAuth1 is a pretty good standard wrapped in hard stuff
    - The idea of today is to discuss things, not locked in to oauth
  - Nikolay: For a lot of use cases cookie auth would be good enough
    - Ryan: you need to send the nonce along with the cookie
    - KAdam: cookies only relevant in browser usage. Have to be running in WP’s context.
  - Adam: for OAuth1 client, how do you generate keys?
    - Ryan: There’s a UI
    - Our key and secret get generated, we put them into our app
    - We use the three-legged flow
    - User, with token, get sent to the site. Either by opening browser or opening a URL.
    - Then they get authenticated, and redirected, or OOB flow
    - Key and secret you store with the app is the big point of contention: keeping that on a user’s system is a security risk.
  - Nigel - App passwords still get sent in header. but could be revoked individually.
    - Nikolay: use case was that flickr or something doesn’t need your actual username and password, as would be needed in XMLRPC.
  - KAdam: Nikolay, you indicated there are oauth2 options for WP, if you have SSL?
    - Yes. If you don’t use HTTPS, it’s the same as basic authentication with an application password.
    - Nikolay: every system other than oauth2 requires some kind of (manually) shared secret, so that you can sign all of the requests. This is not usually a very good user experience.
  - Nikolay: combination of cookie auth for themes/plugins and oauth1 for mobile/desktop may be OK in short term, given that we create enough resources and documention to show people what to do. No standard way exists for managing your keys or tokens.
    - KAdam: in what sense, “managing your keys or tokens?"
    - Nikolay: You need to generate the token via
  - Nikolay: Somebody wrote a restful command-line client for wordpress using node
    - TODO: Nikolay to provide a link to this resource
  - Weaknesses in current plugin
    - oob flow support: just from a magic string? should there be a checkbox?
    - callbacks are "magic"
    - No “view” option w/out Edit
  - TODOs:
    - Add OAuth support to client-js
    - Add OAuth support to wp-rest-api
    - Open some issues against OAuth client interface
    - investigate how wpcom handles things
    - Better-document OAuth flow
  - Nonce w/ every response?
    - Maybe send a nonce if the response contained a nonce, so that the nonce the client has could be updated
  - Nikolay: way calypso works is a REST Proxy, it’s on a public domain
    - They load something from wp-admin in an iframe, and postmessage to the iframe, which makes the actual request. It has all the cookies b/c it lives in WP Admin.
    - Normally with wpcom, the cookie which is not in wp-admin, doesn’t have much stuff. It’s just a login cookie. The actual cookie which lets you do fun things is only set in wp admin. This is an interesting problem: CORS to permit communication between domains, and difference b/w privileges of login cookie vs admin cookie. Login cookie may or may not be “enough” for the REST API.
- Embedded & Linked Resources
  - Adam: client-js
  - Nikolay: interesting problem. Where do you draw the line of decorating your objects?
    - Similar problem exists w/ ORMs
    - In different cases his experiences lead him to think of different things.
    - Performance is a concern “if decoration is not trivial"
    - If you access a post, you want to add methods to it, this adds extra memory/time;
    - Other times you want a huge, deep structure, and other times you just want the author of the post as a user object
  - KAdam: provide a hook where a method could be specified to transform response objects
  - Nigel: idea w/ PHP is the same.
- Discovery
  - Adam: client-js can either localize the schema, or if not, it will make an ajax request and parse the schema to generate models. These are cached on session storage so you don’t need to do it again
  - Adam: If you pass `context=helper` to schema you get way more information
  - Adam: parsing the defaults so you can inspect the models and know what the defaults are that you should be sending.
  - KAdam: how do you go from endpoints to making your own models?
    - Adam: you can tell if it’s a model because it ends in a regex: decides which endpoint are models and which are collections, then extends base model and base collections w/ customized nonce-injecting sync method.
    - Each endpoint provides verbs, defaults, etc in schema, which are used to extend the default model or collection. Based the name on the name of the path, so /posts becomes Posts. People didn’t like that it was called Posts that it was a singular model, so we added some mapping (manual thing) that turns Posts -> Post, Categories -> Category.

Thank you to everyone in attendance for being part of a great discussion!

**Comment by danielbachhuber** [comment]
No action needed here at this time :)
