### ISSUE TITLE
Only permit registered params to be used within our callbacks

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#2201]
To prevent issues like #2195 and generally help ensure we're only using expected data, I think it would be a better pattern to only permit registered params to be used within our callbacks.

In #2122, I included a pattern like this to prepare our data for the callback:

```
public static function prepare_query_args_from_request( $request ) {
    $prepared_args = array();
    $attributes = $request->get_attributes();
    foreach ( $attributes['args'] as $key => $args ) {
        if ( ! isset( $request[ $key ] ) ) {
            continue;
        }
        $value = $request[ $key ];
        $new_key = ! empty( $args['transform_to'] ) ? $args['transform_to'] : $key;
        $prepared_args[ $new_key ] = $value;
    }
    return $prepared_args;
}
```

Notice it creates `$prepared_args` from the args registered to the request, instead of blindly accepting request params.

Also, if we included the `transform_to` mechanism, we could essentially remove `WP_REST_Users_Controller::prepare_item_for_database()` and many other internal transformation procedures.

**Comment by danielbachhuber** [comment]
> To prevent issues like #2195 and generally help ensure we're only using expected data, I think it would be a better pattern to only permit registered params to be used within our callbacks.

@WP-API/amigos Agree or disagree?

**Comment by BE-Webdesign** [comment]
I like this idea, but it would require `register_rest_field()` have to register the param as an argument as well.  Currently for the update callbacks it just checks `$request[ $field_name ]` to see if there is a value set then it uses that value.  I don't believe it appears in the args listing.

**Comment by rmccue** [comment]
I'm 👎 on this. It can be implemented as a dev tool quite easily: https://gist.github.com/rmccue/184a2329a922f6b4350d

I don't think it makes sense for the API core itself though.

**Comment by joehoyle** [comment]
I think the ship has sailed on this one either way, as this is now in core. Also, I think we make the right decision with allows the params in the end anyway.

**Comment by rmccue** [comment]
I am going to close this out, as it hasn't had a bunch of attention, and can be implemented via plugins. In addition, it's an issue in core now, not in the endpoints.

**Comment by danielbachhuber** [comment]
> I am going to close this out, as it hasn't had a bunch of attention, and can be implemented via plugins. In addition, it's an issue in core now, not in the endpoints.

Not quite correct, see https://wordpress.slack.com/archives/core-restapi/p1475092785004369

> danielbachhuber [1:01 PM] so I can include `parent=44` in a request to a non-hierarchical post type and it will be included in the query

**Comment by BE-Webdesign** [comment]
In reference to something I said earlier, it may not be a concern.

> I like this idea, but it would require register_rest_field() have to register the param as an argument as well. Currently for the update callbacks it just checks $request[ $field_name ] to see if there is a value set then it uses that value. I don't believe it appears in the args listing.

It might actually appear from the `get_endpoint_args_for_item_schema()` transformation, but someone would need to double check that.

**Comment by BE-Webdesign** [comment]
I would be 👍 on making the registered arguments use more strict. I don't see the downside really, but could definitely be wrong.

**Comment by joehoyle** [comment]
I really don't understand why we are keeping this open, we _have_ to move forward with decisions on the API, and I frankly don't know how much more we can discuss this one. Yes, there are merits to have the param handling more strict, however just because we acknowledge there is _some_ merit doesn't mean we should keep this discussion open forever more.

I _really_ don't understand how we can change this now, as it's going to break a huge amount of code that people have already written, and even if we did want to - this is now something at the infrastructure level to be a trac ticket. 

We can discuss things until the cows come home, but we have to make a decision. As the project lead @rmccue chose to close this ticket. I consider this a massive time sink and waste of energy that would be so better off spent on things that are lacking discussion.

**Comment by danielbachhuber** [comment]
> I really don't understand why we are keeping this open, we have to move forward with decisions on the API, and I frankly don't know how much more we can discuss this one.

If `parent` isn't registered as a query parameter for `GET /wp/v2/posts`, should `WP_REST_Posts_Controller` process `parent` as a part of the collections request?

**Comment by kadamwhite** [comment]
> If parent isn't registered as a query parameter for `GET /wp/v2/posts`, should `WP_REST_Posts_Controller` process `parent` as a part of the collections request?

Does this conflate two different issues -- one being, should the API accept unregistered query params, and the other being, should the API whitelist the query params the controller considers to only include registered ones?

**Comment by danielbachhuber** [comment]
> Does this conflate two different issues -- one being, should the API accept unregistered query params, and the other being, should the API whitelist the query params the controller considers to only include registered ones?

I believe the discussion on the issue conflates two different issues, yes.

The first conversation was covered in depth with #1223

I don't believe the second conversation has been adequately answered, which is why I reopened the issue. The current behavior of the API is to:
1. Ignore the `parent` in `POST /wp/v2/posts parent=123` if `parent` isn't present in the schema.
2. Use the `parent` in `GET /wp/v2/posts?parent=123` even when `parent` isn't present in the registered query args.

I think the behavior in 2 is a bug. We should only use `parent` in our callback when it's registered as a query argument.

The reason this issue was written in broader terms originally is because we have a ton of `if ( isset( $schema['properties']['title'] ) )` in our `prepare_item_for_database()` callbacks already. I think there's an opportunity to produce a lightweight abstraction for use within our callbacks that transforms `$request` into a variable that only has the request data we want to process, based on the registered schema or collection args.

**Comment by kadamwhite** [comment]
> I think the behavior in 2 is a bug. We should only use parent in our callback when it's registered as a query argument.

I agree

> I think there's an opportunity to produce a lightweight abstraction for use within our callbacks that transforms $request into a variable that only has the request data we want to process, based on the registered schema or collection args.

This conceptually makes sense to me, and I support this idea. Diligence & explicit registration has rarely hurt me and the opposite cannot be said to be true.

**Comment by kadamwhite** [comment]
After looking through the history of this more, I think letting controllers make the call on what to do with stray properties seems sufficient. It seems like being more strict here could rule out dynamically-computed properties, and make it more onerous to register new routes. Since this is out in the wild already, if we were to change this, anybody who has written code that didn't specifically enable all of the relevant callbacks will have their code break.

I too am now convinced that "strict mode" in terms of what properties are allowed to be passed on to the controller is plugin territory. Because @joehoyle and @rmccue above concur I am going to close this out.

**Comment by danielbachhuber** [comment]
This bug still needs to be fixed:

>  The current behavior of the API is to:
> 1. Ignore the `parent` in `POST /wp/v2/posts parent=123` if `parent` isn't present in the schema.
> 2. Use the `parent` in `GET /wp/v2/posts?parent=123` even when `parent` isn't present in the registered query args.

**Comment by rmccue** [comment]
Split to #2767.
