### ISSUE TITLE
Pass WP_REST_Request to prepare_items_query in WP_REST_Posts_Controller

### ISSUE THREAD

**Issue by mgburns** [WP-API/WP-API#2207]
Use case:

I'm extending the built-in `WP_REST_Posts_Controller` class to provide extra collection parameters / `WP_Query` arguments (sort by meta field, filter by P2P connected posts, etc.) for a custom post type endpoint.

AFAICT there is no way to do this without duplicating all of the code in `WP_REST_Posts_Controller::get_items()` as I need the current `WP_REST_Request` object to add the appropriate query arguments.

**Comment by danielbachhuber** [comment]
Seems reasonable. We'll get it added in the next beta.

**Comment by mgburns** [comment]
:+1:

**Comment by ianpullens** [comment]
Could you direct me to some info on how I can call out p2p connected posts in Rest API? I've got all my custom fields working, but I want to show the relationships as well.
