### ISSUE TITLE
Endpoint rendering homepage

### ISSUE THREAD

**Issue by robynlarsen** [WP-API/WP-API#2217]
Any thoughts on why the endpoint would be rendering the homepage?

`http://dev-twg-express.pantheon.io/wp-json/wp/v2/posts/`

**Comment by danielbachhuber** [comment]
Have you tried flushing your rewrite rules?

**Comment by robynlarsen** [comment]
@danielbachhuber genius. Thanks for this. Why does that always fix the problem in WP?! It's a magical fix.

**Comment by robynlarsen** [comment]
Fixed with a permalink flush.
