### ISSUE TITLE
Versionning routes of api base behavior

### ISSUE THREAD

**Issue by Art2B** [WP-API/WP-API#2220]
Hi,

I'm using base function of wp rest api which allow me to get posts, pages and others stuff with `/wp/v2/posts`

But, I'd like to add some versionning to thoses routes, like `/wp/v3/posts` to add new features on api call but still allow the use of old version of api. 

Is there a way to do it ?

**Comment by danielbachhuber** [comment]
> But, I'd like to add some versionning to thoses routes, like /wp/v3/posts to add new features on api call but still allow the use of old version of api.

Please read our [docs on adding custom endpoints](http://v2.wp-api.org/extending/adding/), and pay attention to the section on namespaces. You'll want to add your endpoints to a custom namespace, instead of adding them to core's `wp` namespace.

**Comment by gabrielstuff** [comment]
Hi @danielbachhuber,
Actually we would like to know of to benefits from all the automatic `wp-json/v2/` setup and be able to maintain versionning on the the API.
For instance how would one create a route such as : 
`wp-json/` would actaually match `api/` and then being able to have `api/v1/`,  `api/v2/`, `api/v2.1/`
Should we add custom `.htaccess` rules or custom rewrite rules in php with wordpress ? 
What would you suggest for something maintainable and that would not mean rewrite a plugin to do exactly what v2 does by default and improve it.

Thanks.

**Comment by danielbachhuber** [comment]
> For instance how would one create a route such as : 
> wp-json/ would actaually match api/

You can configure the API route with the `rest_url_prefix` filter: https://developer.wordpress.org/reference/hooks/rest_url_prefix/

>  then being able to have api/v1/, api/v2/, api/v2.1/

I'm not sure I follow. Why not just register those routes?

> Should we add custom .htaccess rules or custom rewrite rules in php with wordpress ? 

You don't need custom .htaccess or rewrite rules, beyond what WordPress already does by default for you.

> What would you suggest for something maintainable and that would not mean rewrite a plugin to do exactly what v2 does by default and improve it.

Our documentation is reasonably extensive for learning how to sensibly extend the plugin. You shouldn't need to rewrite the plugin to create your own custom endpoints.
