### ISSUE TITLE
Is there any way around the 'content' in a new POST requirement?

### ISSUE THREAD

**Issue by beatelite** [WP-API/WP-API#2226]
I'm trying to create a new post using POST with just a title and status. I keep getting 404 not found when posting to the /posts endpoint. 

From what I've read, it's because wp api requires content. Will this requirement ever go away and if not, is there any way around it? I don't need content in my use case - just title and status.

**Comment by beatelite** [comment]
nerrmnd. Guess that's no longer that case. I was doing something else wrong.

**Comment by rmccue** [comment]
FWIW, I think this is because you were POSTing to /posts, whereas it's /wp/v2/posts in version 2 :)
