### ISSUE TITLE
Will we ever be able to update post terms using the same post endpoint?

### ISSUE THREAD

**Issue by beatelite** [WP-API/WP-API#2227]
Hi, I noticed the conversation that's been happening here: https://github.com/WP-API/WP-API/issues/2032

I didn't comment there since it's closed (is that proper Gitiquette?)

Does this mean we'll actually get to post terms on post creation to any taxonomy associated to the post type?

If so, when do you think this will be ready?

You wouldn't believe the code gymnastics I've employed to get multiple terms into multiple taxonomies on a post edit or creation as of now. This would make it sooooooo easy!

**Comment by rmccue** [comment]
This was fixed in #2063 for beta 11; you can now access and change terms directly on the post object. :)

(Note "danielbachhuber closed this in #2063", which indicates the issue was fixed by a pull request.)

**Comment by beatelite** [comment]
incredible! Thank you so much for the quick response. Learned a new github trick too!

**Comment by beatelite** [comment]
Sorry, is this on the master or develop branch? It's hard to tell since there's no clear mark of beta 11 (that I can see).

**Comment by rmccue** [comment]
Develop, and it's also tagged: https://github.com/WP-API/WP-API/releases/tag/2.0-beta11
