### ISSUE TITLE
Terms get_items should check post cache

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#2228]
Rather than calling `wp_get_object_terms`, we should use `get_the_terms`, or check `get_object_term_cache` ourselves. This will require doing the sorting ourselves though; we may be able to optimise for the common use case of the defaults.

**Comment by rmccue** [comment]
When hitting `/wp/v2/posts?_embed`, this reduces the number of queries by `per_page * count( taxonomies )`, which is ~30 queries for me. Super useful.

**Comment by danielbachhuber** [comment]
> This will require doing the sorting ourselves though

Yep.

**Comment by danielbachhuber** [comment]
This still needs test coverage

**Comment by rmccue** [comment]
Will-do.
