### ISSUE TITLE
non-standard Content-Disposition header required for post to wp-json/wp/v2/media

### ISSUE THREAD

**Issue by buxit** [WP-API/WP-API#2229]
`POST`ing a file in the request body to `wp-json/wp/v2/media` requires a non-standard `Content-Disposition: filename=file.ext` parameter. According to w3c the parameter should look like this: `Content-Disposition: attachment; filename="file.ext"`. This form is however not supported by wp-rest-api.

**Comment by danielbachhuber** [comment]
See #1744

We need to dive into the Attachments controller and fix it up quite a bit.
