### ISSUE TITLE
Tangential: Xdebug Help

### ISSUE THREAD

**Issue by bponghneng** [WP-API/WP-API#2238]
Hello.

I'm keen to contribute, and I'm currently looking into an issue adding date_query support for posts. Being able to run Xdebug would be a big help. But I'm at a loss--can't seem to get it flying. I'm an old-school PHP guy, and back in the day, we always went in the front door, through index.php. Is there any secret config to get it running for this new-fangled API? :)

I'm still tooling up my development environment, so the problem could be in my local webserver config or something else. But I thought I'd check here to see if I'm missing something on debugging the WP REST API.

Cheers,
Bpong

**Comment by rmccue** [comment]
Sorry to hear you're having problems!

There's nothing particularly special about the REST API in this regard, alas. `/wp-json/...` gets routed by your server (Apache/nginx) to the WordPress front controller (i.e. `index.php`), and WP then uses two types of routing: WP Rewrites parse `/wp-json/a/b/c` to `rest_route => '/a/b/c'`, then the API matches that to a callback.

Nothing here's particularly strange as far as XDebug is concerned. How did you install/configure XDebug? Is it possible you haven't activated it in your `php.ini`?

(Closing as this isn't a bug, but feel free to continue commenting.)

**Comment by bponghneng** [comment]
Ryan,

OK, good. Thanks. At least that's one less thing to configure. Tinkering with php.ini now. Problem has to be in there. Gah, tired of fiddling with config. I'd rather work on code :)
