### ISSUE TITLE
How can I get pagination to work?

### ISSUE THREAD

**Issue by MurhafSousli** [WP-API/WP-API#2247]
Hello, thanks for the great work you do on this plugin. I'm wondering why isn't there a `total_count` field in the response of getting posts. I want to make a _pagination_ or a _load more_ button which must be disabled when `loadedPostsCount = totalPostsCount`.

**Comment by rmccue** [comment]
This is available in the `X-WP-Total` header (and `X-WP-TotalPages` for the number of pages). :)
