### ISSUE TITLE
Pass $options to wp_json_encode

### ISSUE THREAD

**Issue by cjhaas** [WP-API/WP-API#2251]
It would be nice to have a filter to set the second parameter of `wp_json_encode` so that implementors could optionally provide `$options` to `json_encode`. In my specific case, while I'm debugging it would really nice to have `JSON_PRETTY_PRINT` available.

Something like changing:

```
$result = wp_json_encode( $result );
```

To:

```
$result = wp_json_encode( $result, apply_filters( 'rest_json_encode_options', 0 ) ) ;
```

Possibly adding the $depth parameter as a filter, too, and also applying this to the two other return areas.

**Comment by danielbachhuber** [comment]
Thanks for the request, @cjhaas !

Our infrastructure was committed to WordPress core in 4.4, so any feature requests or bug reports against it need to be filed in Trac: https://core.trac.wordpress.org/

**Comment by nylen** [comment]
This should be handled by your development/debug setup rather than by the API.  Depending on how you are debugging, here are some tools I've used in the past:
- Network view or console view in Chrome developer tools
- [JSONView Chrome extension](https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc)
- [httpie](https://github.com/jkbrzt/httpie) on the command line

**Comment by cjhaas** [comment]
I generally agree but although I said "while I'm debugging" I'm also including the consumers of my API, too. I was hoping to ultimately pass a `pretty` URL parameter to allow this. Actually, I'd personally prefer to "[pretty print by default](http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#pretty-print-gzip)" for my own API since compression negates whitespace for the most part which is what [Facebook](http://graph.facebook.com/me), [GitHub](https://api.github.com/users/veesahni?pretty=false), [LinkedIn](https://api.linkedin.com/v1/companies/1337/updates?start=20&count=10&format=json&pretty=0) and others do.
