### ISSUE TITLE
create user

### ISSUE THREAD

**Issue by Peravel-com** [WP-API/WP-API#2252]
hi 
i use rest api for geting post from android app
and i search every where to see the url request to create user by api in android 
and see on documentation but its not have any request format for creating user ir post 
can you help me 
thank you

**Comment by joehoyle** [comment]
Hi @esiise what version of the REST API plugin are you using?

**Comment by Peravel-com** [comment]
the latest version
last 4hours ago

**Comment by Peravel-com** [comment]
sorry v2 version

**Comment by Peravel-com** [comment]
any idea......................!!!!!!!!!!!!!!!!!!!!!!!

**Comment by danielbachhuber** [comment]
@esiise Of [this documentation](http://v2.wp-api.org/reference/users/), what's unclear about how you create a new user? We'll need you to be a bit more clear and detailed on what you've tried, and where you're getting stuck.

**Comment by Peravel-com** [comment]
hi i need create user by post method  in this url 
http://nesh.in/wp-json/wp/v2/users/?username=test&email=eee@eee.com&password=ehsanehsan
but the result is 
{
  "code": "rest_cannot_create_user",
  "message": "Sorry, you are not allowed to create resource.",
  "data": {
    "status": 401
  }
}

can you help me what is wrong

**Comment by danielbachhuber** [comment]
> can you help me what is wrong

You need to be authenticated and authorized to create new users. "Authentication" means the request is treated as a logged-in request. "Authorization" means the logged-in user has permission to create a new user. In the example you've provided, `status=401` means the request is neither authenticated, nor authorized.

You can read this documentation to learn more about authentication: http://v2.wp-api.org/guide/authentication/

Our authorization model follows that of WordPress core's capabilities system.

**Comment by rmccue** [comment]
Note also that you cannot create users while not logged in (i.e. sign up). This is intentional, and we don't plan on offering support for this.

**Comment by Peravel-com** [comment]
why ?!!  in wordpress anyone can register  why in rest have this limit 
i can remove it in plugin but its not usual

**Comment by medrockstar** [comment]
can we create user without Authentication like wordpress ?

**Comment by BE-Webdesign** [comment]
@medrockstar,

> can we create user without Authentication like wordpress ?

You will need to write a custom endpoint to do that.  It was deliberately decided to not support that feature in the WordPress REST API.

**Comment by Zhuravlev1** [comment]
Hello, please help me, I have ionic 3 project and function. I need create user on WP.
```
onSubmit(values){
    this.http.post(Config.WORDPRESS_URL + 'wp-json/jwt-auth/v1/token',{
      username: 'admin',
      password: 'pass'
    })
    .subscribe(
      res => {
        let token = res.json().token;
          let header : Headers = new Headers();
          header.append('Authorization','Basic ' + token);
        this.http.post(Config.WORDPRESS_REST_API_URL + 'users?token=' + res.json().token,{
          username: values.username,
          name: values.displayName,
          email: values.email,
          password: values.password,
        },header)
        .subscribe(
          result => {
            console.log(result.json());
          },
          error => {
            console.log(error.json());
          }
        )
      },
      err => {
        console.log(err);
      }
    )
  }
```
But I always get error:
```
code: "rest_cannot_create_user",
message: "Sorry, you are not allowed to create new users."
status: 401
```
admin:pass - this is admin on site and has a role admin. Also I added to .htaccess

```
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
```

Please help me to find a mistake

**Comment by sopedro** [comment]
Have you found the mistake?
I have similar situation but with new HttpModule:

wordpress.service.ts
```
	doLogin(data) {
		return this.http.post(this.config.wordpressApiUrl + '/jwt-auth/v1/token', data);  
	}

	doRegister(data, token) {
		let header: HttpHeaders = new HttpHeaders();
		header.append('Authorization', 'Basic ' + token);
		return this.http.post(this.config.wordpressApiUrl + '/wp/v2/users?token=' + token, data, {headers:header});  
	} 
```
wordpress-register.component.ts

```
  register() {
    let loader = this.loadingController.create({
      content: ""
    });
    loader.present();
    console.log(this.signupAcc);
    this.wordpressService.doLogin(this.adminAcc)
      .subscribe((res: any) => { 
        console.log(res.token)
        this.wordpressService.doRegister(this.signupAcc, res.token).subscribe( res => {
        console.log(res)
        loader.dismiss();
          this.navController.push(WordpressLogin, {
            user: res
          });
      }, error => {
        loader.dismiss();
        let errorMessage = error;
        if (errorMessage && errorMessage.message) {
          let message = errorMessage.message.replace(/<(?:.|\n)*?>/gm, '');
          let toast = this.toastController.create({
            message: message,
            duration: 6000,
            position: 'bottom'
          });
          toast.present();
        }
        });
    });    
  }
```
Objects adminAcc contains a valid admin user and signupAcc is the new user data.

**Comment by Zhuravlev1** [comment]
@sopedro Hi, I delete param TOKEN from URL and create options header
Try use next URL for registration
>  this.config.wordpressApiUrl + '/wp/v2/users
```
let header = new Headers({"Authorization": "Bearer "+token});
let options = new RequestOptions({headers: header});
```
I have next request, Config.REGISTER = SITE_URL + 'wp-json/wp/v2/users';
```
this.http.post(Config.REGISTER, {
            username: username,
            name: displayName,
            email: email,
            password: password,
            nonce: nonce
        }, options)
```

it is work for me.
You also need add to .htaccess

```
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
```

**Comment by sopedro** [comment]
@Zhuravlev1 Hi, you helped me a lot, I thought that i had tried this solution too.
Btw i have modified a litle because i'm using angular/common/http instead of angular/http and now RequestOptions doesn't exist anymore and it's more simple to pass the headers directly in the call.

```
	doRegister(data, token) {
		let header: HttpHeaders;
		header = new HttpHeaders({ "Authorization": "Bearer " + token });
		return this.http.post(this.config.wordpressApiUrl + '/wp/v2/users', data, {headers:header});  
	}
```

I ignored last part because I'm on Nginx

Thank one more time
