### ISSUE TITLE
Comments collection accidentally generates a search query

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#2255]
We default `search` to `null`, but internally, `WP_Comment_Query` checks that it's an empty string. This generates a search query which looks like:

``` sql
SELECT SQL_CALC_FOUND_ROWS sz_comments.comment_ID
FROM sz_comments
WHERE ( comment_approved = '1' )
AND comment_post_ID IN ( 85 )
AND comment_type IN ('')
AND (comment_author LIKE '%%'
OR comment_author_email LIKE '%%'
OR comment_author_url LIKE '%%'
OR comment_author_IP LIKE '%%'
OR comment_content LIKE '%%')
ORDER BY sz_comments.comment_date_gmt ASC, sz_comments.comment_ID ASC
LIMIT 10
```

:hear_no_evil:

Core needs to be patched to have a better check, but we should work around this in the meantime.

cc @rachelbaker our comment overlord

**Comment by danielbachhuber** [comment]
> We default search to null, but internally, WP_Comment_Query checks that it's an empty string.

We don't actually set a default `null` value for search — I'm not sure where you're getting this case from. Can you share more details?
