### ISSUE TITLE
Authenticates users and do somes requests with the api.

### ISSUE THREAD

**Issue by ghost** [WP-API/WP-API#2258]
Hi, 
I would like to create an external website with angularjs and a wordpress backend but i'm in trouble, i don't know how to authenticates users. 

Anyone can explain me what is the good way to authenticates users in a external website ( without php ) ?

**Comment by danielbachhuber** [comment]
Thanks for writing in. Fortunately, we have an [entire guide on authentication](http://v2.wp-api.org/guide/authentication/) we'd recommend taking a read through to understand the different forms of authentication.

**Comment by ghost** [comment]
I have already read this document, But the only method I've found for authenticate users with password is basic auth, and this method is unsafely.

**Comment by danielbachhuber** [comment]
> But the only method I've found for authenticate users with password is basic auth, and this method is unsafely.

Why can't you use OAuth1 or cookie auth?

**Comment by ghost** [comment]
I already tried Oauth1 but the console always return : OAuth signature does not match.
![screenshot - 10022016 - 16 45 37](https://cloud.githubusercontent.com/assets/7378894/12952161/c49dc240-d015-11e5-9f01-f11c46fbd9c5.png)

**Comment by ghost** [comment]
Is there a possibility to create his own method of identification ?

**Comment by danielbachhuber** [comment]
> I already tried Oauth1 but the console always return : OAuth signature does not match.

Ok. This seems like a fixable problem then.

> Is there a possibility to create his own method of identification ?

Yes, although you run the risk of introducing security issues.

**Comment by ghost** [comment]
> Yes, although you run the risk of introducing security issues.

Ok , what is the way to do this ?

**Comment by danielbachhuber** [comment]
> Ok , what is the way to do this ?

Creating your own authentication mechanism isn't something we can recommend or support.
