### ISSUE TITLE
Posting a comment with post id throws an error

### ISSUE THREAD

**Issue by mensch** [WP-API/WP-API#2260]
I've been experimenting with versions of the REST API for quite a while now and have recently updated to the latest beta12 (0549f8e). My application is posting comments with the `post` field set to the id of the post as per the documentation. The request payload contains the following:

```
{
  author: 1,
  author_name: "Commenter",
  content: "My comment"
  post: 1
}
```

Currently, this throws an error in the `WP_REST_Comments_Controller` on [line 73](https://github.com/WP-API/WP-API/blob/2.0-beta12/lib/endpoints/class-wp-rest-comments-controller.php#L73) after saving the comment in the database and getting the updated collection of comments. It appears the request object is checked for the post field and handled as an array, rather than an integer. The behaviour was introduced in [this commit](14ab402) to allow for multiple post ids to be checked when obtaining a collection of comments.

Is the documentation outdated in this regard, am I using the endpoint incorrectly or have I hit upon a bug? Thanks!

**Comment by danielbachhuber** [comment]
Sorry about that. I can reproduce:

![image](https://cloud.githubusercontent.com/assets/36432/12951408/15ccae00-cfc7-11e5-98ae-ae1edc1d43b5.png)

> My application is posting comments with the post field set to the id of the post as per the documentation.
> [...]
> Currently, this throws an error in the WP_REST_Comments_Controller on line 73 after saving the comment in the database and getting the updated collection of comments.

I guess we're actually calling `get_items_permissions_check()` for the `Allow` header in the infrastructure. We don't catch the error in our tests because we're calling `dispatch()` directly, and not the `rest_post_dispatch()` filter.

**Comment by danielbachhuber** [comment]
> Is the documentation outdated in this regard, am I using the endpoint incorrectly or have I hit upon a bug?

To fix your problem until the next beta, you can apply 80dcacf95140a445d262aefb55d1054ee2750108 locally.

**Comment by mensch** [comment]
Cool, that was quick! Casting `$request['post']` as an array fixes the issue. Thanks!
