### ISSUE TITLE
rest_api_init hook only registering the last one

### ISSUE THREAD

**Issue by NizarBlond** [WP-API/WP-API#2263]
I collect arguments from different classes and then register API routes arguments.
Then, at one time, I iterate over all the args and load them using add_action('rest_api_init', $cb).

**Problem**: only last args are registered as route (successfully). I checked all of them by changing orders.

See code below 

Each class calls this ApiHelper function:

``` PHP
public function registerRoute($ns, $route, $component, $cb, $method = "GET", $inc_ns_api = true)
    {
        // Modify namespace to include API_VER
        $ns = $inc_ns_api ? $ns.'/'.self::API_VER : $ns;

        // Set arguments for anonymouse rest api callback
        $args = [
            "ns"            => $ns,
            "route"         => $route,
            "component"     => $component,
            "callback"      => $cb,
            "method"        => $method
        ];

        self::$restArgs[] = $args;
    }
```

Then, the main class calls the function that loads the args, note that the args are 100% correct. I tried to spread the add_action() to multiple calls with hardcoded inputs, NOTHING!

``` PHP
static public function loadRoutes()
    {
        foreach (self::$restArgs as $args) {
            // Set current args
            self::$currArgs = $args;

            // Correct params
            // var_dump($args);

            // Define anonymouse rest api callback
            $restApiCallback = function () {
                register_rest_route(self::$currArgs["ns"], self::$currArgs["route"], array(
                    'methods'   => self::$currArgs["method"],
                    'callback'  => array(self::$currArgs["component"], self::$currArgs["callback"]),
                ));
            };

                         // Only last is successfully registered!!!!!!
            add_action( 'rest_api_init', $restApiCallback );
        }

        // Clean registered routes
        $self::$restArgs = [];
    }
```

**Comment by mAAdhaTTah** [comment]
So many reasons this could be going wrong, but none of them are WP-API related. Most likely culprit is the use of `self::$currArgs` in the Closure, which only equals the value of the last iteration of the loop. Just pass in the args with `use` and stop assigning them to a static var for no reason.

**Comment by NizarBlond** [comment]
how do i pass with use? what do you mean?

**Comment by mAAdhaTTah** [comment]
``` php
$callback = function () use ( $args ) {
  // do stuff
};
```

See here: http://php.net/manual/en/functions.anonymous.php

**Comment by NizarBlond** [comment]
Thanks, my bad
