### ISSUE TITLE
deleting or updating a meta key/value pair

### ISSUE THREAD

**Issue by jtosey** [WP-API/WP-API#2264]
I can add a meta key/value pair to an object like this:

```
curl --username 'name:password' -d 'key=agent_title&value=Insurance Specialist' -s http://aaatalks.carolinas.aaa.com/wp-json/wp/v2/pages/927/meta
```

But when I do so repeatedly, I end up with duplicate definitions of the key in the meta container.  Is there a way to delete a key/value pair, or to update an existing key/value pair without introducing duplicates?

**Comment by danielbachhuber** [comment]
There are a number of problems with managing meta through the meta endpoints.

Instead, we'd recommend you use `register_meta_field()` to register your meta to the Page object, and specify get and update callbacks http://v2.wp-api.org/extending/modifying/
