### ISSUE TITLE
Custom orderby param value

### ISSUE THREAD

**Issue by Youdaman** [WP-API/WP-API#2265]
Hi, I've got some logic in my pre_user_query and pre_get_posts that lets me use a custom value with the orderby query param.

In the latest update there's a breaking change that limits the valid request args to an enum set, and I understand I have to use rest_validate_request_arg somehow to allow my custom orderby value.

I don't know where/how to do this however, and if you could point me to the right filter or snippet that lets me merge my value with the defaults that would be great!

**Comment by Youdaman** [comment]
I managed to work out how to slot in my custom orderby param ("honey") as follows:

``` php
add_filter('rest_endpoints', 'my_modify_rest_routes');
function my_modify_rest_routes( $routes ) {
  array_push( $routes['/wp/v2/topic'][0]['args']['orderby']['enum'], 'honey' );
  array_push( $routes['/wp/v2/users'][0]['args']['orderby']['enum'], 'honey' );
  //error_log('routes = ' . print_r($routes, true));
  return $routes;
}
```

Hope this helps anyone else having the same issue since the breaking change.

**Comment by danielbachhuber** [comment]
> In the latest update there's a breaking change that limits the valid request args to an enum set, and I understand I have to use rest_validate_request_arg somehow to allow my custom orderby value.

Sorry about that :( It skipped my mind that anyone would be using a custom orderby value.

I'll make sure we get the "extending routes" aspect documented https://github.com/WP-API/docs-v2/issues/114
