### ISSUE TITLE
How can we use filter to restrict some tag?

### ISSUE THREAD

**Issue by naveen84123** [WP-API/WP-API#2267]
we want to restrict a tag by filter. 
"/wp-json/wp/v2/posts"this url shows all posts with all tags like news,culture,quiz
suppose we need news posts then  my url is "/wp-json/wp/v2/postsfilter[tag]=news"
but now we need to restrict quiz posts then what should we do?
is it a right url?
filter[tag]!=quiz
please answer this question.

**Comment by danielbachhuber** [comment]
You can use the `filter` param to build a tax query. Here are your available options: https://codex.wordpress.org/Class_Reference/WP_Query#Taxonomy_Parameters

Later on, we'll introduce top-level support for them #2145
