### ISSUE TITLE
beta12 GET /wp/v2/pages

### ISSUE THREAD

**Issue by LifetimeCode** [WP-API/WP-API#2270]
Hi,
I just installed Version 2.0-beta12, and I got some HTML output is sent before the JSON object. This affects API calls expecting JSON format.

**Comment by danielbachhuber** [comment]
> I just installed Version 2.0-beta12, and I got some HTML output is sent before the JSON object.

You'll need to disable your plugins one-by-one until you figure out which is outputting HTML before it should be. This issue, unfortunately, isn't anything we can fix.
