### ISSUE TITLE
WP REST API route request explain

### ISSUE THREAD

**Issue by vitalijm** [WP-API/WP-API#2272]
Maybe can someone explain or show additional info about "WP REST API route request" from beginning to the end.

Main questions, how handle this request in most earlier stage. For example for ajax requests, is second check:

`if (defined('DOING_AJAX') && DOING_AJAX) { /* it's an AJAX call */ }`

**What check can be most fast to handle rest api request?**

Main my approach in app logic, after route request init, immediately check what route type was and do we have saved by current request result with wp standart  set_transient function. If it is, grab result directly from database (transients), and don't generate expansive in time new object result.

**So more in global view of logic:**
1. Getted request.
2. In functions.php detected that request and disabling loading some stuff for speed up this.
3. In some "rest_api" action we handle type | url of request and checking for availability of transients.
4. If is transient result, immediately return it without generating expansive in cpu and time answer from serve

**Comment by Shelob9** [comment]
Take a look at the rest_pre_serve_request filter:

https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/class-wp-rest-server.php#L376

By default, it returns false. When it does, the API continues as normal. You could instead return the cached response there.

**Comment by vitalijm** [comment]
Thanks, Shelob9. But for now I'm using second logic to check if is setted cached result:

```
add_filter( 'rest_pre_dispatch', 'swp_filter_restapi_cached_result', 10, 3);
function swp_filter_restapi_cached_result( $result, $server, $request ){

  $result = swp_transients(array(
    'transient' => 'restapi_cached_result_' . $_SERVER['REQUEST_URI']
  ));

  return $result;
}
```

WP-API-ebook_final_09162015.pdf

On page 42 is explaned some optimisation tips.

Now in searching for action to handle, when is finally builded json response and ready to output.

Maybe someone can say what exact this action can be

**Comment by vitalijm** [comment]
Oh, Shelob9, this is You author of this book. :)
So, maybe I'm on wrong way now? When not using your proposed 'rest_pre_serve_request'
If I'm wrong, then maybe You can show example of code...

Now, want find hook, when output ready, but not send yet. I want there set transient cache.

**Comment by vitalijm** [comment]
Is this right?

```
// $result currently is not generated yet
add_filter( 'rest_pre_dispatch', 'swp_filter_restapi_is_cached', 10, 2);
// $result has been generated
add_filter( 'rest_pre_serve_request', 'swp_filter_restapi_add_cache', 10, 3);
```

Please fix me, if I'm doing some wrong

```
// $result currently is not generated yet
add_filter( 'rest_pre_dispatch', 'swp_filter_restapi_is_cached', 10, 2);
// $result has been generated
add_filter( 'rest_pre_serve_request', 'swp_filter_restapi_add_cache', 10, 3);

function swp_filter_restapi_is_cached( $result, $server ){
  $result = swp_transients(array(
    'transient' => 'swp_filter_restapi_cached_result_' . $_SERVER['REQUEST_URI']
  ));
  return $result;
}

function swp_filter_restapi_add_cache($boolean, $result, $request){
  $result = swp_transients(array(
    'transient' => 'swp_filter_restapi_cached_result_' . $_SERVER['REQUEST_URI'],
    'value' => $result->data,
    'expiration' => 12 * HOUR_IN_SECONDS
  ));

  echo wp_json_encode($result);

  return true;
}

function swp_transients($args){

    $args = array_merge(array(
        'some' => 'some'
    ), $args);

    if(!isset($args['transient'])){
        return false;
    }

    if(!isset($args['value']) && !isset($args['expiration'])){
        if (false !== ($value = get_transient($args['transient']))) {
            return $value;
        } else {
            return false;
        }
    } else {
        if (false === ($value = get_transient($args['transient']))) {
            set_transient($args['transient'], $args['value'], $args['expiration']);
        }
        return $args['value'];
    }

}
``
```

**Comment by Shelob9** [comment]
A few things here:
1) Are you sure that creating a static JSON string cache is better than just using a regular persistant object cache? If you had memchaced or redis or whatever running, it would take slightly longer to get to where WP_Query or whatever uses that cache, but is slightly longer might be a few nanoseconds. If true, why all this extra work?
2) Have you considered how you're going to handle cache invalidation? If your site is dynamic at all, this is going to be an issue.
3) I havn't set something up like this in awhile, beacuse of all of the reasons above, but if I were you, I would look at how the function `_oembed_rest_pre_serve_request()` uses the `rest_pre_serve_request` function to handle oembeds between sites.
4) BTW Your code _looks_ OK to me at a glance, I would have to set it up and place some xdebug breakpoints to see if these callbacks were running and the data was structured as expected. Not sure I have time for that right now.

**Comment by vitalijm** [comment]
1) Hm, I was not informed about this stuff))) Maybe You can provide short instructions of best practices how to implement this feature on website? If this caching automatically queried objects into RAM, then of course in transients is no need here.
2) About this, maybe some hook on posts updates or even 1 hour to update special transient cache.
3) Between sites do requests, for now I don't grow up yet. From security point view etc.
4) I was checked this on my website, seems to work. But looks like memcached for this situation, is much more smarter solution, because automatically handling objects for caching them. And not only in rest request ;)

So, If You can, show some best of your way in implementing this feature. Thanks)

**Comment by rmccue** [comment]
This isn't a bug, so closing out, but feel free to continue discussing.
