### ISSUE TITLE
How to get site data using api

### ISSUE THREAD

**Issue by masstechnologist** [WP-API/WP-API#2275]
How to get site data like title, description or other general settings data through the api?

**Comment by joehoyle** [comment]
This is not currently available in the REST API plugin, however that's being worked on in https://github.com/WP-API/wp-api-site-endpoints

**Comment by masstechnologist** [comment]
Thanks a bundle.  I guess it only supports GET and not PUT to update options?

**Comment by joehoyle** [comment]
It will, at some point! this feature plugin is currently very new / quite possible not functional yet :)

**Comment by masstechnologist** [comment]
Any suggestions if i want to extend it by my own? Is there any alternative for the time?

**Comment by kadamwhite** [comment]
I'm not in front of a computer right now but at least until recently title
and description were available in the root API response, i.e. the response
when you hit your-site.com/WP-json-- is that no longer the case? (Obviously
does not cover the full range of use cases you have, I just thought it
might help)

## 

K. Adam White
kadamwhite@gmail.com
401.575.7829

**Comment by masstechnologist** [comment]
Yes they are available to view only. They can't be updated.

**Comment by rmccue** [comment]
> Any suggestions if i want to extend it by my own? Is there any alternative for the time?

You're best off forking that feature plugin and adding the update pieces; pull requests always welcome. :)
