### ISSUE TITLE
Nonce related gotcha

### ISSUE THREAD

**Issue by PeterKnight** [WP-API/WP-API#2276]
Reading the documentation on how the api handles nonces had me a bit confused at first. I think I tried something I suspect others will too, maybe the docs can be made more clear?

If you're intentionally using nonces for requests that don't require a login, you might still  be inclined to pass _wpnonce and let the api check it for you like a logged-in request. Thing is, it does if you pass it as $_POST or send a X-WP-Nonce header containing the correct nonce. If you pass the wrong nonce you get a forbidden response as you would expect.

The easy to overlook part is that if you send the same request without the nonce, you won't get an error, it will just work. This is because the API will treat it like an unauthenticated request. If a plugin developer hasn't configured further checks and validation the response will go through when it shouldn't.

**Comment by rmccue** [comment]
This is intentional. Since cookies are always sent, if we errored when cookies were sent but nonces weren't, users would have to log out of the site to be able to send unauthenticated API requests. This would be a pain if using an external site that does simple unauthenticated requests.

**Comment by PeterKnight** [comment]
I guess my point is that developers might get confused about when they can rely on the API to check the nonce. For requests that don't require login you have to do the nonce checking yourself and that's not obvious from reading the docs.
