### ISSUE TITLE
Post from category giving all posts

### ISSUE THREAD

**Issue by kdpuvvadi** [WP-API/WP-API#2277]
I'm trying to get the posts from specific category, when i try to use `https://www.example.com/wp-json/wp/v2/posts?categories=38` it is giving all posts rather than posts from that specific category.

**Comment by LukePettway** [comment]
Try doing:

https://www.example.com/wp-json/wp/v2/posts/38

**Comment by Luciaisacomputer** [comment]
Try doing the following

https://www.example.com/wp-json/wp/v2/posts?filter[cat]=38

**Comment by kdpuvvadi** [comment]
it works but why doesn't `posts?categories="category-id"` work even though it is provided by WP REST API and `posts?tags="tag-id"` is also not working

**Comment by Luciaisacomputer** [comment]
Could you post a link to where you are seeing that? I don't think I've done it that way before so I am curious.

**Comment by kdpuvvadi** [comment]
https://www.telugushowtime.com/wp-json/wp/v2/posts?tags=165

**Comment by rmccue** [comment]
@kdpuvvadi Neither of these work; I'm not sure what indicated that they should?

You need to use `filter[cat]=...` and `filter[tag_id]=...` per the [WP Query](https://codex.wordpress.org/Class_Reference/WP_Query#Category_Parameters) documentation.

**Comment by kdpuvvadi** [comment]
i've seen them in the category and tag details api, and for category `filter[cat]=...`  is working but 'filter[tag_id]=...' is giving all posts even though the results not relevant.

**Comment by joehoyle** [comment]
I think we should add this, I'll take it on

**Comment by kdpuvvadi** [comment]
I've given my site url above, Please check with it. Thank you.

**Comment by danielbachhuber** [comment]
Landed in #2287

**Comment by kdpuvvadi** [comment]
So, how can i filter posts with tag?
