### ISSUE TITLE
create new comment

### ISSUE THREAD

**Issue by alaa-alsalehi** [WP-API/WP-API#2278]
when I create a comment as anonymous I got response with 201 status
but the response was

Warning: Invalid argument supplied for foreach() in /home/zaki/public_html/wp-content/plugins/rest-api/lib/endpoints/class-wp-rest-comments-controller.php on line 73
{"id":4309,"post":6687,"parent":0,"author":0,"author_name":"admin","author_url":"","author_avatar_urls":{"24":"http:\/\/2.gravatar.com\/avatar\/e64c7d89f26bd1972efa854d13d7dd61?s=24&d=mm&r=g","48":"http:\/\/2.gravatar.com\/avatar\/e64c7d89f26bd1972efa854d13d7dd61?s=48&d=mm&r=g","96":"http:\/\/2.gravatar.com\/avatar\/e64c7d89f26bd1972efa854d13d7dd61?s=96&d=mm&r=g"},"date":"2016-02-14T22:42:25","date_gmt":"2016-02-14T20:42:25","content":{"rendered":"
TEST new<\/p>\n"},"link":"http:\/\/www.mysite.com\/post\/6687\/%d8%b7%d8%b1%d9%8a%d9%82%d8%a9-%d8%b9%d9%85%d9%84-%d8%a7%d9%84%d8%ba%d8%b1%d9%8a%d8%a8%d8%a9-%d8%a7%d9%84%d9%86%d8%a7%d8%b9%d9%85%d8%a9-%d9%81%d9%89-%d8%a7%d9%84%d8%a8%d9%8a%d8%aa-%d9%85%d8%ab%d9%84\/#comment-4309","status":"hold","type":"comment","_links":{"self":[{"href":"http:\/\/www.mysite.com\/wp-api\/wp\/v2\/comments\/4309"}],"collection":[{"href":"http:\/\/www.mysite.com\/wp-api\/wp\/v2\/comments"}],"up":[{"embeddable":true,"post_type":"post","href":"http:\/\/www.mysite.com\/wp-api\/wp\/v2\/posts\/6687"}]}}

is that a healthy thing?

**Comment by rmccue** [comment]
See #2260 for this issue.
