### ISSUE TITLE
Basic authentication, how i made it works

### ISSUE THREAD

**Issue by greederwow** [WP-API/WP-API#2279]
This is probably silly, but the only way i found to make basic auth works was activating Json basic authentication and WP BASIC auth plugins together. I'm writing this because i often read of peoples having troubles with authentication.

**Comment by danielbachhuber** [comment]
> the only way i found to make basic auth works was activating Json basic authentication and WP BASIC auth plugins together

I suspect only one of them is performing authentication. We don't recommend activating both at the same time.
