### ISSUE TITLE
Built-in JS client woes

### ISSUE THREAD

**Issue by kaitwalla** [WP-API/WP-API#2280]
Been having some trouble getting the built-in JS client to work when working in my theme (though it's entirely possible I'm completely misunderstanding this, as I'm only passingly familiar with BackBone). I'm beginning with this assumption: Having the WP API plugin activated and including `wp_enqueue_script( 'wp-api' );` on my theme's functions page means I should be able to go to the JavaScript console and have wp.api available (with both the models and the actions). If that's incorrect, please let me know and consider the rest of this irrelevant.

That being said, I've installed the latest beta12 client on WP 4.5-alpha-36527 (from the svn trunk). The endpoint, /wp-json, appears to be working, but when regardless if I have `wp_enqueue_script( 'wp-api' );` in functions.php or not, `wp` in the JavaScript console only has a property of "emoji" — wp.api is undefined. Am I doing something wrong or am I completely misunderstanding how to use this?

Any help is appreciated. Thanks for all the hard work! The REST API client is definitely a gamechanger for WP.

**Comment by BE-Webdesign** [comment]
@zedley Is your wp_enqueue_script( 'wp-api' ) hooked properly? It should load and be a part of wp object.  **If hooked properly ignore the below** and I would have to maybe see your functions.php file.  Below is a brief example of what a hook into 'wp_enqueue_scripts' looks like.

``` php
function enqueue_wp_api() {
    wp_enqueue_script( 'wp-api' );
}
add_action( 'wp_enqueue_scripts', 'enqueue_wp_api' );
```

**Comment by kaitwalla** [comment]
I must have been hooking it wrong, because the script you provided works perfectly. 

Thanks a ton.

**Comment by BE-Webdesign** [comment]
@zedley No problem, so in your theme's functions.php look for where there is already a hook to wp_enqueue_scripts.  It looks like add_action( 'wp_enqueue_scripts', 'some_function' ); Usually the function is named insert_theme_name_scripts().  There will be stylesheets and various scripts in there. It would be best to slap the wp_enqueue_script in there with the rest of scripts and styles being loaded.  If your theme doesn't do that then just use what I pasted above.
