### ISSUE TITLE
Unset _links from post type

### ISSUE THREAD

**Issue by vitalijm** [WP-API/WP-API#2282]
How to unset _links from post type data in 'rest_prepare_post' filter? Or we must use some other place for removing it?

```
add_filter( 'rest_prepare_post', function($data, $post, $context){
  unset($data->data['_links']); // not working
  return $data;
}, 12, 3 );
```

**Comment by danielbachhuber** [comment]
> How to unset _links from post type data in 'rest_prepare_post' filter?

You'd need to call `$data->remove_link()` on each link:

```
add_filter( 'rest_prepare_post', function( $data ) {
    foreach( $data->get_links() as $rel => $link ) {
        $data->remove_link( $rel );
    }
    return $data;
});
```

Can you explain in greater detail why you want to remove links though?

**Comment by vitalijm** [comment]
Thanks.
To have the lightest as possible weight of json output data, to play with it in faceted search.
Or maybe Im on wrong way?)

**Comment by vitalijm** [comment]
For example if output will be of 1000 objects. Because I want see count of every property in faceted search. If request will have just 9 page with 10 results, then we can't see all possible results of each property. I'm saving request in transient for 24 hours, updating on new post / update.

**Comment by danielbachhuber** [comment]
> To have the lightest as possible weight of json output data, to play with it in faceted search.

Ah, makes sense. I was just curious about the use case.

**Comment by kdpuvvadi** [comment]
it is not working anymore,  why?
