### ISSUE TITLE
404 error while accessing to endpoint

### ISSUE THREAD

**Issue by matthiasbe** [WP-API/WP-API#2283]
Hi,
I'm trying for several days to get this plugin working but I don't succeed.
The problem is, when I try to access `mysite.com/wp-json/` or `mysite.com/wp-json/wp/v2/users` or whatever i get a 404 error `file not found`.

I have changed the permalinks to "postname" and it didn't resolve my problem.

I have the following wp-generated `.htacces`. Shouldn't there be a rewriting rule to take the `wp-json` url into account ?

``` xml
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
```

I believe that mod_rewrite is installed on my server and enabled (anyway wp wouldn't work if it wasn't right ?)
Am I allowed to wake some tests through firefox ? Or should I use curl ?
I've tried sending such requests with angularJS but got the same error.

Maybe this is an error message I get because I didn't do any authentication ?

Maybe my server needs special .htaccess rules for authentication ?
I've found this in my host FAQ, don't know if it's relevant ...

> access the "Authorization" headers
> 
> In the event that you would like to use authentication based on HTTP, you will need to add the >following directives in your ”.htaccess” file.
> 
> RewriteCond %{HTTP:Authorization} ^(.+)
> RewriteRule ^(.*)$ $1 [E=HTTP_AUTHORIZATION:%1,PT]

Thanks a lot for your time ! And thank you for this plugin :)

**Comment by danielbachhuber** [comment]
> The problem is, when I try to access mysite.com/wp-json/ or mysite.com/wp-json/wp/v2/users or whatever i get a 404 error file not found.

What happens when you create a page through the WordPress admin, publish it, and view the permalink? Can you share what the permalink ends up as?

> I have the following wp-generated .htacces. Shouldn't there be a rewriting rule to take the wp-json url into account ?

No, you shouldn't need an extra `.htaccess` rule.

> Maybe this is an error message I get because I didn't do any authentication ?

"file not found" probably doesn't have to do with authentication.

**Comment by matthiasbe** [comment]
Hello,
Thank you for your quick response. It seems you hit right. When i click to display one of my several pages of my site from admin, the it gives me right url like `mysite.com/example-page/` but the loaded page raises a `file not found`.

It seems it's a problem with the wp installation. Sorry for the misunderstanding.

I will tell you whether solving wp's `file not found` solves my problem with rest.

**Comment by danielbachhuber** [comment]
> It seems it's a problem with the wp installation. Sorry for the misunderstanding.

No worries, glad you've established this. Good luck tracking down the source of the problem.
