### ISSUE TITLE
comments can be send with empty values

### ISSUE THREAD

**Issue by bobsilon** [WP-API/WP-API#2284]
Hi there,
Is it good the wp-api save the comments with empty values?
If I submit a comment form with empty fields, empty `author_name`, empty  `author_email`, empty `author_url` and others except `post`, It will be submitted in database. Is it right behavior?

**Comment by danielbachhuber** [comment]
> Is it good the wp-api save the comments with empty values?

I think we're changing this behavior with #2049

I'll flag for @rachelbaker to confirm the expected behavior.

**Comment by kadamwhite** [comment]
This should be resolved now that #2741 has been merged
