### ISSUE TITLE
Creating New User via API Logs Me in as New User

### ISSUE THREAD

**Issue by beatelite** [WP-API/WP-API#2285]
**Summary**
   When creating a new user while authenticated, I am instantly logged in as that user. Not sure if this is by design or not. 

**Reproduction Steps:**
    Authenticate using nonce. 
    POST to /users endpoint
    params:
 {
   name: usertest,
   username: user1,
   email: test@test.com,
   password: test,
   role: contributor
}

**Current Result:**
    The post is successful and I'm subsequently logged in as that user instantly. This happens with every role. 

**Expected Result:**
    I stay logged in as my user and the new user is simply created.

**System Specs:**
using 2.0-beta11

**Comment by joehoyle** [comment]
Oops! My guess is `wp_new_user` or something is setting the cooke.

**Comment by danielbachhuber** [comment]
> My guess is wp_new_user or something is setting the cooke.

We're using `wp_insert_user()` and `wpmu_create_user()`, neither of which set cookies.

@beatelite Is this a single WordPress instance, or WordPress multisite? Can you try deactivating any plugins you might be running, and switching to the default WordPress theme, to see if there's another factor at play?

**Comment by AlbertGuadan** [comment]
JSON Web Token 
    could be the solution.

 JWT
