### ISSUE TITLE
API for Facebook login

### ISSUE THREAD

**Issue by sryze** [WP-API/WP-API#2289]
We're building a mobile app that uses WP REST API as a backend. There should be an option for logging with Facebook alongside with the normal username/password login. From what I was able to find on this topic on the web, it seems that there needs to be a dedicated server-side API for the Facebook login based on sending a user access token from the client app and checking it on the server.

Is this supported by the WP REST API in any way? What would be the recommended approach for implementing this?

**Comment by danielbachhuber** [comment]
> Is this supported by the WP REST API in any way?

No. Normal WordPress authentication isn't currently supported by the WP REST API, and we won't be supporting authentication with third-party identity providers.

> What would be the recommended approach for implementing this?

Sorry, that's outside the scope of this issue tracker. Adding Facebook authentication is a substantial development task.
