### ISSUE TITLE
Get 404 for /wp/v2/posts/postid/categories

### ISSUE THREAD

**Issue by mingyena** [WP-API/WP-API#2290]
Hi, I have updated the plugin for the beta12, but it gets a 404 when I GET or POST category to a post - GET blog-name/wp-json/wp/v2/posts/10102/categories`resulted in a`404 Not Found` response: {"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}

It is doing okay for the meta. So maybe I miss something or do you have any insight why I got this?

Thanks!

**Comment by kadamwhite** [comment]
Taxonomy terms collections were moved out from beneath the `/posts` endpoint in the most recent beta; try the URL `blog-name/wp-json/wp/v2/categories?post=10102`. This should also be reflected in the `_links` the post provides for its terms; for my blog, for example, the collection URL is shown in beta 12 using the new path:
![image](https://cloud.githubusercontent.com/assets/442115/13134958/0212590a-d5da-11e5-893d-0bfa52b63310.png)

**Comment by kadamwhite** [comment]
As for meta, you'll need to install the [new separate meta plugin](https://github.com/WP-API/wp-api-meta-endpoints) to keep using meta in future WP-API beta releases

**Comment by mingyena** [comment]
Thank you @kadamwhite  and @danielbachhuber ! 
May I ask the right request to send a POST?
I tried POST blog-name/wp-json/wp/v2/categories?post=10102&id=categoryID
AND
POST blog-name/wp-json/wp/v2/categories?post=10102, array(id, count,name)
But they seems not be  correct paths...
