### ISSUE TITLE
Need API to get templates and their names

### ISSUE THREAD

**Issue by jtosey** [WP-API/WP-API#2293]
We would like to be able to set the template for a page from a separate system, by presenting their names in a drop-down list, and then setting the filename through the API.  Right now we can't get that info through the API, so we have to make assumptions about the theme and the filenames in that theme.

We would like to be able to retrieve the current template names and filenames through the API.

**Comment by rmccue** [comment]
You can send an `OPTIONS` request to the `/wp/v2/pages` endpoint and check the schema; it includes an `enum` field listing the valid templates. For example:

``` sh
curl -X OPTIONS demo.wp-api.org/wp-json/wp/v2/pages
```

``` js
{
    "namespace": "wp\/v2",
    "methods": ["GET", "POST"],
    "endpoints": [ /* ... */ ],
    "schema": {
        "$schema": "http:\/\/json-schema.org\/draft-04\/schema#",
        "title": "page",
        "type": "object",
        "properties": {
            // ...
            "template": {
                "description": "The theme file to use to display the object.",
                "type": "string",
                "enum": [],
                "context": ["view", "edit"]
            }
        }
    }
}
```

This is also available in the index or namespace index (at `/wp-json/` and `/wp-json/wp/v2` respectively) if you pass `context=help`.

**Comment by danielbachhuber** [comment]
It doesn't include the names of the templates

**Comment by rmccue** [comment]
> It doesn't include the names of the templates

Good catch.

**Comment by danielbachhuber** [comment]
Sorry for the confusion, @jtosey. I had started on a code snippet for this the other day, and was distracted.

For between now and when we add formal support in the API, here's how you can register an endpoint to get the list of templates with their names:

```
add_action( 'rest_api_init', function(){
    /**
     * GET /wp-json/wpx/v1/page-templates
     */
    register_rest_route( 'wpx/v1', 'page-templates', array(
        'methods'              => 'GET',
        'callback'             => function() {
            require_once ABSPATH . '/wp-admin/includes/admin.php';
            return get_page_templates();
        },
        'permission_callback' => function() {
            return current_user_can( 'edit_posts' );
        },
    ) );
});
```

**Comment by jtosey** [comment]
That's awesome, thanks!
