### ISSUE TITLE
comment IP is always 127.0.0.1 not showing the real IP

### ISSUE THREAD

**Issue by mc256** [WP-API/WP-API#2294]
Hi there,

I don't think it is my server problem... Because other parts of my server are working fine.

I am using jQuery to post the comment
`jQuery.ajax({
            type:"POST",
            dataType:"json",
            data:{
                post:c,
                parent:b,
                content:jQuery("#cmt-textarea-p" + b).val(),
                author_name:jQuery("#cmt-name-p" + b).val(),
                author_email:jQuery("#cmt-email-p" + b).val()
            },
            url:a,
            success:function(a) {
//something
            },
            error:function() {
//something
            }
        });
`

But I can only got 127.0.0.1 from the wordpress portal.

**Comment by danielbachhuber** [comment]
This is a known problem. See #1788 for the ongoing discussion on how we might address it.
