### ISSUE TITLE
List of compatible plug-ins?

### ISSUE THREAD

**Issue by brandondurham** [WP-API/WP-API#2296]
In this particular instance I’m searching for an ad management plug-in that works seamlessly with the WP-API, but I’ve found myself previously wanting to know what plug-ins work well with it in general.

Is there a list anywhere of plug-ins that offer seamless incorporation with WP-API?

**Comment by danielbachhuber** [comment]
I don't believe we have a list going yet, but it'd be a great addition to v2.wp-api.org

**Comment by brandondurham** [comment]
Ah, okay. I agree… would be great. I’ve seen plug-ins that explicitly state they’re compatible, but I’d love to just browse a singular list when I need something specific.

Thanks!

**Comment by BE-Webdesign** [comment]
@danielbachhuber I can compile a list.  Would we put it into the readme file or should I just paste it here when complete and it can be added to v2.wp-api.org?

**Comment by danielbachhuber** [comment]
@BE-Webdesign let's start a dedicated page on v2.wp-api.org. I'll get contrib access for you, so you can create a PR directly.

**Comment by BE-Webdesign** [comment]
@danielbachhuber Very awesome!! Thank you!

**Comment by BE-Webdesign** [comment]
@danielbachhuber I think this is taken care of for now. Added a page http://v2.wp-api.org/guide/plugins/, so we can close.

@brandondurham Check out http://v2.wp-api.org/guide/plugins/ and if you have any ideas or contributions let us know.
