### ISSUE TITLE
typings for wp-api.js

### ISSUE THREAD

**Issue by MurhafSousli** [WP-API/WP-API#2302]
Is there a typing file for `wp-api.js`, I need to import it in typescript file but it's not working and I'm getting this error : `error TS2307: Cannot find module './../../assets/wp-api'.`

```

import * as WP from './../../assets/wp-api';
.
.
export class AppCmp {
  constructor(public wp: WP) {

    var allCategories = new api.collections.Categories();
    allCategories.fetch();
    console.log(allCategories);
  }
}
```

**Comment by adamsilverstein** [comment]
@MurhafSousli There is not, yet. Can you provide some more details about whats needed here? also can you please close this issue and re-open on the client repository: https://github.com/WP-API/client-js

Thanks.
