### ISSUE TITLE
Get posts by taxonomy name and term id

### ISSUE THREAD

**Issue by gerardabsi** [WP-API/WP-API#2305]
is there a way that i can retrieve the posts related to a taxonomy name and term id like:
http://example.com/wp-json/wp/v2/posts?filter[taxonomy]=newssource&filter[term]=<termid>

**Comment by BE-Webdesign** [comment]
@gerardabsi There are a couple of changes that should be landing soon regarding filtering by taxonomy ( if it is show_in_rest => true ) .  One will have a top level support for the taxonomy and one with tax_query support in the filter.  So if you wanted to search by taxonomy and term_id you would do something like:

For posts in categories 1, 2 and 3.
**GET wp/v2/posts/?categories=1,2,3**

Or using filter.
**GET wp/v2/posts/?filter[tax_query][0][taxonomy]=category&filter[tax_query][0][field]=term_id&filter[tax_query][0][terms]=1,2,3**

Filter would probably only ever be used if a complex tax_query is needed.  For right now though you could use filter to do tags and categories, so if all you need is tags and categories then the below is fine and the above will soon be in.  This should currently work:

Posts in categories id 1.
**GET wp/v2/posts/?filter[cat]=1**

Posts in tags id 1.
**GET wp/v2/posts/?filter[tag_id]=1**

**Comment by gerardabsi** [comment]
i used :
wp-json/wp/v2/posts/?filter[tax_query][0][taxonomy]=newssource&filter[tax_query][0][field]=term_id&filter[tax_query][0][terms]=1293

it didn't filter all the posts of the term_id 1293

if use the slug like this
wp-json/wp/v2/posts?filter[taxonomy]=newssource&filter[term]=newssource-16
the posts are filtered by the newssource-16.

Am I missing any args

**Comment by BE-Webdesign** [comment]
> i used :
> wp-json/wp/v2/posts/?filter[tax_query][0][taxonomy]=newssource&filter[tax_query][0][field]=term_id&filter[tax_query][0][terms]=1293
> it didn't filter all the posts of the term_id 1293

Yes, because they are not in the API yet, as stated above.

> if use the slug like this
> wp-json/wp/v2/posts?filter[taxonomy]=newssource&filter[term]=newssource-16
> the posts are filtered by the newssource-16.

If that works go for it.

**Comment by gerardabsi** [comment]
Sorry i thought they were added
My question was is there any way to use the term_id right now because i don't want to use the slug.
or shall i wait till the update is released.

**Comment by BE-Webdesign** [comment]
@gerardabsi I believe you will need to wait till the update not sure when it's slated to go in either.

**Comment by danielbachhuber** [comment]
@gerardabsi You could also just [download the ZIP](https://github.com/WP-API/WP-API/archive/develop.zip) for the develop branch if you're comfortable using pre-release software.
