### ISSUE TITLE
Creating New Post with single meta field

### ISSUE THREAD

**Issue by Playrom** [WP-API/WP-API#2306]
I'm trying to create a new post with a single meta named "link". I've correctly installed and configured in my functions.php, the meta feature plugin

But i just can't work out this code. The post is created without the meta

`{
    "title": "Statement by Pentagon Press Secretary Peter Cook on Submission of Guantanamo Closure Plan",
    "content_raw": "",
    "status": "publish",
    "format": "link",
    "post_meta": {
        "key": "link",
        "value": "http:\\/\\/www.defense.gov\\/News\\/News-Releases\\/News-Release-View\\/Article\\/671225\\/statement-by-pentagon-press-secretary-peter-cook-on-submission-of-guantanamo-cl"
    }
}`

Maybe i'm not correctly understand the "meta problem" ? Is it impossible to create a new meta during a post creation?

**Comment by danielbachhuber** [comment]
> Is it impossible to create a new meta during a post creation?

Yes, you'd need to assign post meta in a second request. If you want to assign a meta field in the initial request to a post, you need to use `register_meta_field()` http://v2.wp-api.org/extending/modifying/

**Comment by Playrom** [comment]
ok thanks! Didn't understand well that point :)
