### ISSUE TITLE
WP API v1 basically still conflicts with v2

### ISSUE THREAD

**Issue by mnelson4** [WP-API/WP-API#2307]
I reported on https://github.com/WP-API/WP-API/pull/1687 that WP API v2, partially included in WP 4.4, broke WP API v1. So that ticket addressed that so v1 will continue to work fine even with WP API v2 or WP 4.4 active. Great. But now WP API v2 is busted when WP API v1 is active.
The solution of course is to move one of the APIs to a different json url prefix. Eg, switch WP API v1 to live at `mysite.com/wp-json-old` instead of `mysite.com/wp-json` where it conflicts with WP API v2 (we created a plugin that does this: https://github.com/eventespresso/wp-api-v1-renamer). 
But how many users will figure that out? I thought this wouldn't be a huge issue but just yesterday a team who's working on a mobile app that integrate with our event espresso rest api, which relies on WP API in 4.4, had this issue because they activated WP API v1 plugin on their site. Yeah it was their mistake (to my knowledge we never even told them about WP API v1 plugin), but if developers are having this issue, how much more likely is it regular users will?

How about we at least add a warning that WP API v1 and WP API v2/WP API in 4.4 conflict when active side-by-side. I'd suggest some kind of persistent notice would be good. This code could be in WP API v1 or v2. If that sounds like a good suggestion I can submit a patch

**Comment by danielbachhuber** [comment]
> if developers are having this issue, how much more likely is it regular users will?

Regular users shouldn't be installing WP-API v1 directly, given there's a deprecation notice.

> How about we at least add a warning that WP API v1 and WP API v2/WP API in 4.4 conflict when active side-by-side. I'd suggest some kind of persistent notice would be good. This code could be in WP API v1 or v2. If that sounds like a good suggestion I can submit a patch

This seems like more of an annoyance than being helpful. There are perfectly valid reasons to continue to use WP API v1 with WordPress 4.4, and we shouldn't disadvantage those users.

I think this is more of user error than anything else. There's lots of ways you can accidentally misconfigure your API such that it produces cryptic results, and we can't protect the user from all of them.

**Comment by mnelson4** [comment]
> Regular users shouldn't be installing WP-API v1 directly, given there's a deprecation notice.

 Yes it says the plugin is deprecated, but it says "It's no longer supported beyond security fixes". That communicates to me "It works, but don't expect new features." It should say something like "It is incompatible with WordPress 4.4 and higher unless..."

> There are perfectly valid reasons to continue to use WP API v1 with WordPress 4.4, and we shouldn't disadvantage those users. 

for the record, I was thinking the notice would only come up when `json_url_prefix() == rest_url_prefix()`, because I agree there are valid reasons to have both active side-by-side on different url prefixes. 
And yes this is a user error, and this change would be user proofing.

> There's lots of ways you can accidentally misconfigure your API 

Yeah I agree, but every user who attempts to run WP API v1 plugin with WP 4.4 or higher will experience this. At very least a warning about this could be added onto the wordpress.org's plugin description.

**Comment by danielbachhuber** [comment]
> At very least a warning about this could be added onto the wordpress.org's plugin description.

If you want to suggest the text to include, I'd be happy to add it.

**Comment by mnelson4** [comment]
Ok great. Here's what I suggest adding:

Note about compatibility with WP API v2 and WordPress 4.4: WP API v1 breaks WP API v2 and the WP API included in WP 4.4 because they both use the same url prefix: `wp-json`. In order to run both side-by-side, you can change the URL prefix of WP API v1 with `add_filter( 'json_url_prefix', function($old_prefix){return 'wp-json-old'});`

This should probably go somewhere on the wp.org plugin description and on the wp-api documentation page.

**Comment by danielbachhuber** [comment]
I've added the following to the v1 readme.txt:

> If you activate both v1 and v2 on your website, then v1 will take priority and v2 will be inaccessible.

**Comment by mnelson4** [comment]
great thanks!
