### ISSUE TITLE
Can't get order by meta key to work.

### ISSUE THREAD

**Issue by colloquet** [WP-API/WP-API#2308]
Hi all,

I am developing a web app that display a bunch of data onto a table. Here is the code to get the data:

```
$http({
  url: '/wp-json/wp/v2/posts',
  params: {
    per_page: 20,
    order: 'asc',
    'filter[orderby]': 'meta_value_num',
    'filter[meta_key]': 'rank',
  }
}).then(function(result, status, headers, config) {
  result.data.forEach(function(obj) {
    console.log(obj.acf.rank);
  });
});
```

Where `rank` is a custom field of the post by **Advanced Custom Fields**. This gives me the result:

![screen shot 2016-02-24 at 10 24 03 am](https://cloud.githubusercontent.com/assets/6201495/13273746/c9a2d41c-dae0-11e5-8435-e1a3dec24303.png)

As you can see it's not in any particular order, I ran the same query without `'filter[meta_key]'` and I get same result again. Another weird thing is if I run a similar query on wp_query:

```
$args = array(
  'posts_per_page' => 20,
  'post_type' => 'post',
  'orderby' => 'meta_value_num',
  'order' => 'asc',
  'meta_key' => 'rank'
);
$query = new WP_Query( $args );
if ( $query->have_posts() ) {
  while ( $query->have_posts() ) {
    $query->the_post();
    echo '<li>'.get_field('rank').'</li>';
  }
} else {
  echo '<p>No result found</p>';
}

wp_reset_postdata();
```

I get the expected result:
![screen shot 2016-02-24 at 10 26 40 am](https://cloud.githubusercontent.com/assets/6201495/13273792/1dc749a6-dae1-11e5-9d7b-70fc8ba9cbb3.png)
I have been debugging this for a few hours and I am still not sure what am I missing.

Thanks in advance!

**Comment by rmccue** [comment]
Have you tried using `?orderby=meta_value_num` directly? I think the `filter[orderby]` value might be getting overridden by the top-level argument.

**Comment by colloquet** [comment]
Hi @rmccue,

Thanks for the swift reply, I tried to use `?orderby=meta_value_num` but I got an error `"Invalid parameter(s): orderby (orderby is not one of date, id, include, title, slug, menu_order)"`.

So I added the following to my functions.php (from https://github.com/WP-API/WP-API/issues/2265):

```
add_filter('rest_endpoints', 'my_modify_rest_routes');
function my_modify_rest_routes( $routes ) {
  array_push( $routes['/wp/v2/posts'][0]['args']['orderby']['enum'], 'meta_value_num' );
  return $routes;
}
```

I don't get the error anymore but I am getting the same result :(

Thanks for the suggestion anyway!

**Comment by colloquet** [comment]
I'd also like to mention that orderby `id` does not seem to work either, here's my code:

```
$http({
  url: '/wp-json/wp/v2/posts',
  params: {
    per_page: 20,
    order: 'asc',
    orderby: 'id',
  }
}).then(function(result, status, headers, config) {
  result.data.forEach(function(obj) {
    console.log(obj.id);
  });
});
```

and I get the following results:
![screen shot 2016-02-24 at 10 50 09 am](https://cloud.githubusercontent.com/assets/6201495/13274170/67c064c2-dae4-11e5-8aa3-4b9a7d2b65b1.png)

**Comment by colloquet** [comment]
Hi all,

Upon further debugging, I have found the solution, it wasn't working because meta_key was not one of the allowed query variable. I simply have to add this code into my functions.php

```
// add custom fields query to WP REST API v2
// https://1fix.io/blog/2015/07/20/query-vars-wp-api/
function my_allow_meta_query( $valid_vars ) {

    $valid_vars = array_merge( $valid_vars, array( 'meta_key', 'meta_value' ) );
    return $valid_vars;
}
add_filter( 'rest_query_vars', 'my_allow_meta_query' );
```

I hope this help others who have the same problem!

**Comment by rmccue** [comment]
Note that this causes privacy issues: anyone can query by any meta key/value, so it's possible to detect meta values on posts this way. This could also be a security issue depending on your plugins, so be extremely careful using this.

**Comment by aayler** [comment]
Hello @rmccue, do you have suggestions -- other than including 'meta_key' and 'meta_value' as allowed query_vars, mentioned above -- to query against meta values for sorting purposes? I have exactly the same issue as the OP.

**Comment by elyobo** [comment]
@aayler I wondered the same, so building on top of @colloquet's answer above I modified the existing routes to add a new `args` entry which validates the `meta_key` values which are permitted.  No need to modify the rest query vars this way either.

```php
        add_filter('rest_endpoints', function ($routes) {
            // I'm modifying multiple types here, you won't need the loop if you're just doing posts
            foreach (['some', 'types'] as $type) {
                if (!($route =& $routes['/wp/v2/' . $type])) {
                    continue;
                }

                // Allow ordering by my meta value
                $route[0]['args']['orderby']['enum'][] = 'meta_value_num';

                // Allow only the meta keys that I want
                $route[0]['args']['meta_key'] = array(
                    'description'       => 'The meta key to query.',
                    'type'              => 'string',
                    'enum'              => ['my_meta_key', 'another key'],
                    'validate_callback' => 'rest_validate_request_arg',
                );
            }

            return $routes;
        });
```

**Comment by aayler** [comment]
@elyobo : Thanks very much for sharing this! I appreciate the approach without touching the query vars.

**Comment by circlecube** [comment]
@elyobo any idea if this should work in wp4.7? I've got the code in place and it accepts these params, but they don't seem to be doing anything to the returned json. The more brute solution by @colloquet doesn't seem to work in 4.7 either. Anyone else seeing this? ideas or suggestions?

**Comment by elyobo** [comment]
@circlecube I haven't had a chance to look at it for WP 4.7 yet, but I will need to upgrade some of our sites so I'll be looking for a fix and will update here when I do.  If it's not working then I guess that they've changed the structure of the arrays that they use to define the routes; giving us a stable API that we could use to modify them instead of having to mess with the structure would be a more approach, but I don't think there is one...

**Comment by elyobo** [comment]
I looks like the posts controller does its own generation and processing of args, which doesn't include the `meta_key`, so in addition to modifying the route args you will need something like this (not tested, give it a a go @circlecube).

```php
$type = 'posts'; // or your own custom post type, etc
add_filter('rest_' . $type . '_query', function ($args, $request) {
    if ($key = $request->get_param('meta_key')) {
        $args['meta_key'] = $key;
    }
    return $args;
}, 10, 2);
```

**Comment by juergengunz** [comment]
@circlecube i have the same issue, since 4.7 this is not working anymore. @elyobo  I tested your snipped but it does not seem to work

**Comment by circlecube** [comment]
@elyobo, working for me. I have a cpt of `president` and wanted to load them via api presorted by custom fields named `took_office` and/or `number`. 

```
	//https://github.com/WP-API/WP-API/issues/2308#issuecomment-262886432
	add_filter('rest_endpoints', function ($routes) {
	    // I'm modifying multiple types here, you won't need the loop if you're just doing posts
	    foreach (['president'] as $type) {
	        if (!($route =& $routes['/wp/v2/' . $type])) {
	            continue;
	        }

	        // Allow ordering by my meta value
	        $route[0]['args']['orderby']['enum'][] = 'meta_value_num';

	        // Allow only the meta keys that I want
	        $route[0]['args']['meta_key'] = array(
	            'description'       => 'The meta key to query.',
	            'type'              => 'string',
	            'enum'              => ['took_office', 'number'],
	            'validate_callback' => 'rest_validate_request_arg',
	        );
	    }

	    return $routes;
	});

	//https://github.com/WP-API/WP-API/issues/2308#issuecomment-265875108
	add_filter('rest_president_query', function ($args, $request) {
	    if ($key = $request->get_param('meta_key')) {
	        $args['meta_key'] = $key;
	    }
	    return $args;
	}, 10, 2);

```

**Comment by elyobo** [comment]
Great, glad it helps @circlecube. @juergengunz you need my new snippet + my old one as circlecube shows in his example.

**Comment by juergengunz** [comment]
@elyobo 
I have a custom field "views" and I want to order posts by their views.

like this: /wp-json/wp/v2/posts?meta_key=views&orderby=meta_value_num

it used to work before 4.7 like this : posts?filter[meta_key]=views&filter[orderby]=meta_value_num



`
```
add_filter('rest_endpoints', function ($routes) {
	    // I'm modifying multiple types here, you won't need the loop if you're just doing posts
	    foreach (['posts'] as $type) {
	        if (!($route =& $routes['/wp/v2/' . $type])) {
	            continue;
	        }

```
	        // Allow ordering by my meta value
	        $route[0]['args']['orderby']['enum'][] = 'meta_value_num';

	        // Allow only the meta keys that I want
	        $route[0]['args']['meta_key'] = array(
	            'description'       => 'The meta key to query.',
	            'type'              => 'string',
	            'enum'              => ['views'],
	            'validate_callback' => 'rest_validate_request_arg',
	        );
	    }

	    return $routes;
	});


	add_filter('rest_posts_query', function ($args, $request) {
	    if ($key = $request->get_param('meta_key')) {
	        $args['meta_key'] = $key;
	    }
	    return $args;
	}, 10, 2);`

**Comment by GreenSunBear** [comment]
@juergengunz  Have you found a solution ? can't get @circlecube solution to work either.

**Comment by juergengunz** [comment]
@GreenSunBear  no not really. I put the data in an array and ordered it with javascript.

**Comment by GreenSunBear** [comment]
Thanks @juergengunz ! looks like this is the current solution. I am using custom routes to load only posts with the meta key for file size and parsing reasons.

**Comment by littlecouto** [comment]
I have the same problem and found this solution:

in my case, i create a meta_box 'views' to know which post are most popular. So i add her on route endpoint and add filter to know if her its on params.

`add_filter('rest_posts_query', function ($args, $request) {
    $key = 'myCustomMeta'; // add here your meta_key to compare above
    if ($key = $request->get_param('meta_key')) {
        $args['meta_key'] = $key;
        $args['orderby'] = 'meta_value_num'; // add meta_value_num to orderby to WP order right
    }
    return $args;
}, 10, 2);`

**Comment by juergengunz** [comment]
@vennyssious  can you explain what you are doing? and how does your query url looks like?
its not working properly for me

**Comment by juergengunz** [comment]
I think it is because the custom field "views" is filled with integer, maybe?

**Comment by joseska** [comment]
Hi... We are trying to order by custom field called "fecha_unix_es", but not work in Wordpress 4.7.2
in my functions.php we have the code 
`
function my_allow_meta_query( $valid_vars ) {
    $valid_vars = array_merge( $valid_vars, array( 'meta_key', 'meta_value' ) );
    return $valid_vars;
}
add_filter( 'rest_query_vars', 'my_allow_meta_query' );
`

and I use this url: https://mywebsite.com/wp-json/wp/v2/posts?categories_exclude=53571&filter[orderby]=meta_value_num&filter[meta_key]=fecha_unix_es&filter[order]=DESC

any help??? Thanks.....

**Comment by sirtawast** [comment]
My two cents and working query example, ordered by a metafield "last_name".

Thanks @elyobo @circlecube @juergengunz 

```php
// https://github.com/WP-API/WP-API/issues/2308#issuecomment-266214066
// Allow custom metafields in orderby
add_filter('rest_endpoints', function ($routes) {
  foreach (array('team_member') as $type) {
    if (!($route =& $routes['/wp/v2/' . $type])) {
      continue;
    }

    // Allow ordering by meta values
    $route[0]['args']['orderby']['enum'][] = 'last_name';

    // Allow only specific meta keys
    $route[0]['args']['meta_key'] = array(
        'description'       => 'The meta key to query.',
        'type'              => 'string',
        'enum'              => ['last_name'],
        'validate_callback' => 'rest_validate_request_arg',
    );
  }
  return $routes;
}, 10, 1);

// Manipulate query
add_filter('rest_team_member_query', function ($args, $request) {
  $order_key = $request->get_param('orderby');
  if (!empty($order_key) && $order_key === 'last_name') {
    $args['meta_key'] = $order_key;
  }

  return $args;
}, 10, 2);
```
