### ISSUE TITLE
Wrong paging when retrieving categories list

### ISSUE THREAD

**Issue by ssmagin** [WP-API/WP-API#2309]
The following requests return the same result (for per_page >10):
http://blog.lo/wp-json/wp/v2/categories?page=1&per_page=100
http://blog.lo/wp-json/wp/v2/categories?page=2&per_page=100
......
http://blog.lo/wp-json/wp/v2/categories?page=1232&per_page=100

But the following requests work correctly:
http://blog.lo/wp-json/wp/v2/categories?page=1&per_page=10
http://blog.lo/wp-json/wp/v2/categories?page=2&per_page=10
......
http://blog.lo/wp-json/wp/v2/categories?page=1232&per_page=10

**Comment by danielbachhuber** [comment]
@ssmagin Which version of the API are you using?

**Comment by ssmagin** [comment]
I use Version 2.0-beta12

**Comment by danielbachhuber** [comment]
@ssmagin and how many categories do you have total? can you more clearly communicate the response you're seeing, and the response you'd expect to see?

**Comment by danielbachhuber** [comment]
I've tried reproducing this, and I can't, so I'm keen for more details which can point me in the right direction.

**Comment by ssmagin** [comment]
I have a test blog with 18 categories.
http://blog.lo/wp-json/wp/v2/categories?page=1&per_page=100 returns me all 18 categories as I expect.
http://blog.lo/wp-json/wp/v2/categories?page=2&per_page=100 also returns me all 18 categories.
But I expect to receive an empty array []. The same problem I have for all pages greater than 1.

Requests with parameter per_page=10 works correctly:
http://blog.lo/wp-json/wp/v2/categories?page=1&per_page=10 returns first 10 categories
http://blog.lo/wp-json/wp/v2/categories?page=2&per_page=10 returns next 8 categories
http://blog.lo/wp-json/wp/v2/categories?page=3&per_page=10 returns an empty array

**Comment by danielbachhuber** [comment]
Thanks for the details, @ssmagin. I've been able to identify this as a bug with core: https://core.trac.wordpress.org/ticket/35935

It's easy for us to include a fix for, though, so we'll have it addressed in the next beta. In the interim, you could apply 4a0e3e5cf3ee1529c4694aaefa1f58c87fd24f5a locally if you need an immediate fix.
