### ISSUE TITLE
Way to remove limit on result set

### ISSUE THREAD

**Issue by stonetip** [WP-API/WP-API#2316]
In more recent versions of the API, results are limited to 100  per request. I can appreciate why this would be a good thing with a public-facing, unrestricted API. However, it means our calling code has to have paging loops written into it for every action, such as getting all the posts for a category to use in a server cache. And it means making multiple HTTP requests.

It'd be great if there was some way (other than hacking an installed copy) to remove this limit. My thought is authenticated users could be allowed to do this.

**Comment by stonetip** [comment]
If I may make a general observation: This is not like an API, such as Google Docs, where there is one company or org that hosts and controls end points. WP sites are hosted by all kinds of people in a wide variety of environments and usages. There really needs to some config options for the API settable from a dashboard or, at worst, in a config file.

**Comment by danielbachhuber** [comment]
> There really needs to some config options for the API settable from a dashboard or, at worst, in a config file.

WordPress has actions and filters for this purpose. You can filter the endpoint registration args to remove the `maximum` attribute:

```
add_filter( 'rest_endpoints', function( $endpoints ){
    if ( ! isset( $endpoints['/wp/v2/posts'] ) ) {
        return $endpoints;
    }
    unset( $endpoints['/wp/v2/posts'][0]['args']['per_page']['maximum'] );
    return $endpoints;
});
```

**Comment by stonetip** [comment]
Where would I even do that? I'm not a WP developer. And if I do, what happens when WP gets upgraded or the plugin gets rolled into Core WP? If I write custom code that gets buried in some obscure location in a WP installation then I need to document it and make sure anyone else who touches the site knows about it.

**Comment by danielbachhuber** [comment]
> Where would I even do that?

You can add it to your theme's functions.php, or create a mu-plugin for it.

> And if I do, what happens when WP gets upgraded or the plugin gets rolled into Core WP?

The code snippet will continue to work as expected.

**Comment by stonetip** [comment]
The latter seems preferable, although after reading  http://codex.wordpress.org/Must_Use_Plugins not without some issues. Unless I'm mistaken, adding code to a theme means being vulnerable to someone else switching themes. We work with designers who are rather unilateral in their actions! Thank you.

**Comment by rmccue** [comment]
You can also add it to a regular plugin if an mu-plugin is an issue.

**Comment by garubi** [comment]
Hallo,
do the snippet privided by @danielbachhuber above (https://github.com/WP-API/WP-API/issues/2316#issuecomment-188776865) is still valid? 
I tried it but the `$endpoints['/wp/v2/posts'][0]['args']['per_page']['maximum']` looks not existent...

**Comment by owenhoskins** [comment]
Hi I've just tested the snippet from https://github.com/WP-API/WP-API/issues/2316#issuecomment-188776865 and rest api calls are still limited to 10 posts. 

I found that setting the default param worked for my purposes:

```
add_filter( 'rest_endpoints', function( $endpoints ){
    if ( ! isset( $endpoints['/wp/v2/posts'] ) ) {
        return $endpoints;
    }
    $endpoints['/wp/v2/posts'][0]['args']['per_page']['default'] = 100;
    return $endpoints;
});
```

@garubi, @danielbachhuber

**Comment by willybrauner** [comment]
@owenhoskins That's a nice point, but is there a solution to set this value per page most than 100 ?

**Comment by gs8407** [comment]
I've made some workaround for making endpoint to display more than 100 posts per page. I've merged two WP endpoints in new php file and used it as a new endpoint:


header('Access-Control-Allow-Origin: *', 'Content-Type: application/json'); // Avoid cross origin block

$url1 = 'https://www.example.com/wp/v2/posts?per_page=100&page=1'; // path to your JSON file
$url2 = ''https://www.example.com/wp/v2/posts?per_page=100&page=2'; // path to your JSON file
$json1 = file_get_contents($url1); 
$json2 = file_get_contents($url2); 

$my_array1 = json_decode($json1, true);
$my_array2 = json_decode($json2, true);
$res = array_merge($my_array1, $my_array2);
$json_merge = json_encode($res);

echo $json_merge; // new json
