### ISSUE TITLE
Creating extra Json objects

### ISSUE THREAD

**Issue by Anawaz** [WP-API/WP-API#2319]
In version 2 response contains many items in form of rendered json object however they were simple key value pair in version 1 for eg.

"title":{"rendered":"How to change Country Settings on Youtube.com"}

however It can be 

"title":"How to change Country Settings on Youtube.com"

in second form it is easy to parse json using gson library.

**Comment by rmccue** [comment]
The `rendered` value is after filters have been applied; if you send `?context=edit`, it will give you back the `raw` value as well, which is directly from the database.

**Comment by Anawaz** [comment]
Okay That is great however this requires authentications and I want to use like previous version.  

Getting this error while accessing like previous version. 

{"code":"rest_forbidden_context","message":"Sorry, you are not allowed to edit these posts in this post type","data":{"status":401}}

I think there is not need of nesting in json rendered object. This is an extra overhead.

**Comment by rmccue** [comment]
If you're not authenticated, you need to use the rendered version. Revealing the raw database values is a potential privacy issue.

> I think there is not need of nesting in json rendered object

The API never changes values based on context, it only adds or removes them. `title` needs to be an object to allow adding the extra data when the context changes.
