### ISSUE TITLE
users missing when call to /users

### ISSUE THREAD

**Issue by TimeParadox89** [WP-API/WP-API#2320]
Hello, i've registered some user from my wordpress website and when i'm going to call the /wp-json/wp/v2/users endpoint i can only retrieve the first 2 users , the others won't be retrieved like they don't exist, but if i try to login to my website i can find them !

could you help me ?

**Comment by danielbachhuber** [comment]
To protect the privacy of private users, `/wp-json/wp/v2/users` only returns users who have published a post (or some other post type exposed in the REST API).

See #2300
