### ISSUE TITLE
Do we need an ability to query by gmt dates?

### ISSUE THREAD

**Issue by ssmagin** [WP-API/WP-API#2323]
For example, we have a site with "UTC -05:00" timezone, so request http://blog.lo/wp-json/wp/v2/posts?filter[hour]=22 returns post:

> {"id":1356,"date":"2013-03-05T22:29:08","date_gmt":"2013-03-06T03:29:08" .... }

Let it be, I live in "UTC +03:00" timezone and I want to get all posts for "2013-03-06" date. Unfortunately, http://blog.lo/wp-json/wp/v2/posts?filter[m]=20130306 request will not return me this post, because WordPress queries dates by post_date field (which represents site timezone).

**Comment by danielbachhuber** [comment]
You can choose a different column to run the query against with `filter[date_query][column]`:

```
wp-json/wp/v2/posts?after=2016-02-01T05:00:28&filter[date_query][column]=post_date_gmt
```

**Comment by BE-Webdesign** [comment]
@ssmagin In the filter param you can use date_query instead.  The API just added top level parameters for before and after (which query against the date).  So if you wanted to query against GMT dates you could use before and after like this:

**GET wp/v2/posts?before=2013-03-07T00:00:00Z&after=2013-03-05T23:59:59Z**

(The Z means it's GMT)
For date query if you wanted to query against gmt times you would do something like this:

**GET wp/v2/posts?filter[date_query][0][year]=2013&filter[date_query][0][month]=03&filter[date_query][0][day]=06&filter[date_query][0][column]=post_date_gmt**

**Comment by ssmagin** [comment]
I tried:
**/wp/v2/posts?filter[date_query][column]=post_date_gmt&filter[date_query][day]=6&filter[date_query][month]=3&filter[date_query][year]=2013**
and
**wp/v2/posts?filter[date_query][0][column]=post_date_gmt&filter[date_query][0][day]=6&filter[date_query][0][month]=3&filter[date_query][0][year]=2013**

But this does not work for me. I receive the latest site post (dated by 2016 year, not 2013). It looks like date_query is not in allowed params list.

**Comment by BE-Webdesign** [comment]
@ssmagin Are you using the v2 plugin or the development branch of WP API? I apologize for any confusion but I do not believe date query is in beta 12 for the v2 plugin.  However, if you want to use the latest develop branch build of WP API you will be able to use that functionality.  I think the next beta release is slated for March 8th a week from tomorrow and date query should be added if you want to wait.

**Comment by ssmagin** [comment]
I downloaded "Version 2.0 beta 12" from https://wordpress.org/plugins/rest-api/

**Comment by BE-Webdesign** [comment]
@ssmagin Yes, then Beta 13 should have it in a week or so!

**Comment by ssmagin** [comment]
Good news, thank You!
