### ISSUE TITLE
Create CPT via API

### ISSUE THREAD

**Issue by joneslloyd** [WP-API/WP-API#2325]
Hi there,

I'm unsure if this is or isn't implemented, so I wanted to ask for sure:

I've got a CPT successfully registered with WP-API. I can retrieve them (etc.) but I'd like to be able to create a new instance of my CPT via the API.

Is this currently possible?

If not, are you able to point me in the direction of how I can do this myself?

Thanks!

**Comment by Shelob9** [comment]
This is not possible. CPT are not registered in the database, but via code in WordPress, so it wouldn't really make sense, or be practical to do it via the API.

**Comment by joneslloyd** [comment]
Thanks fore getting back to me.

I don't fully understand the reasoning of your response, because, surely the same framework which allows for CPTs to be added to the API and queried (archive and individual) would also easily allow for adding (POST) ?

Also, (to follow your logic) would CPTs not be queryable via the API in any form, if the requirement were for them to be registered via the database?

I'm happy to develop this functionality myself and add to the repo if needs be, if you're able to provide some pointers.

Thanks!

**Comment by joneslloyd** [comment]
In the `prepare_item_for_database` function (in `/plugins/rest-api/lib/endpoints/class-wp-rest-posts-controller.php`, there is a check for the post type:

```
// Post type.
        if ( empty( $request['id'] ) ) {
            // Creating new post, use default type for the controller.
            $prepared_post->post_type = $this->post_type;
        } else {
            // Updating a post, use previous type.
            $prepared_post->post_type = get_post_type( $request['id'] );
        }
        $post_type = get_post_type_object( $prepared_post->post_type );
```

Why must the default post type for the controller be used, rather than a user specified value (if exists)?

**Comment by joneslloyd** [comment]
Actually, ignore this. Solved.

For anybody else with this issue:

Change the URL to `http://yoursite.com/wp-json/wp/v2/<your-cpt>` and perform the `POST`.

**Comment by rmccue** [comment]
Just to clarify what @Shelob9 misunderstood: "CPT" means Custom Post Type, which are things that need to be registered in code. What you actually meant here is items of your CPT, which are better referred to as "CPT posts" (as confusing as that can be).

Your post type just needs to have `show_in_rest => true` in the registration args, then it'll appear at `wp/v2/<name>`. To change that last part (we recommend using plural nouns), you can set `rest_base` in your registration.

Once you've got that set up, GET will give you the items, POST will create new items. You'll also have a route at `wp/v2/<name>/{id}` where you can GET to get an individual item, PUT to update it, and DELETE to remove it. :)

**Comment by joneslloyd** [comment]
Thanks for clearing that up @rmccue - I've re-read my post, and I see what @Shelob9 meant there.

I'll use "CPT posts" going forwards.

As you've said regarding CPTs, all of those things work perfectly for me now.

Thanks!
