### ISSUE TITLE
How to modify a specific route's response?

### ISSUE THREAD

**Issue by bobsilon** [WP-API/WP-API#2326]
Hi there, I want to modify the response when I get just one post with this route:

```
wp-json/wp/v2/posts/50
```

I did this:

``` php
add_action('rest_api_init', 'si_post_views_count');
function si_post_views_count()
{
    register_rest_field('post',
        'si_views_count',
        array(
            'get_callback' => 'slug_get_views_count',
            'update_callback' => 'slug_update_views_count',
            'schema' => null,
        )
    );
}
```

Where the `slug_get_views_count` is like this:

``` php
function slug_get_views_count($object, $field_name, $request)
{
    $count_key = $field_name;
    $count = get_post_meta($object[ 'id' ], $count_key, true);
    if ($count == '') {
        $count = 0;
        delete_post_meta($object[ 'id' ], $count_key);
        add_post_meta($object[ 'id' ], $count_key, '0');
    } else {
        ++$count;
        update_post_meta($object[ 'id' ], $count_key, $count);
    }

    return get_post_meta($object[ 'id' ], $field_name);
}
```

This works fine if I get one post, but in this way if I get bunch of posts with `wp-json/wp/v2/posts`, the count of all the returned posts will increased by one. How can do this modification **just** for the `wp-json/wp/v2/posts/:id` route?

**Comment by danielbachhuber** [comment]
> How can do this modification just for the wp-json/wp/v2/posts/:id route?

You can inspect `$request` for the route, and only perform the write operation when you see the route you expect.

**Comment by bobsilon** [comment]
Thanks for getting back to me. But when I return `$request` in `get_callback` function, it returns an empty object. Am I doing wrong?

**Comment by bobsilon** [comment]
Thanks

**Comment by bobsilon** [comment]
Oh yes, Thanks a lot.

**Comment by danielbachhuber** [comment]
@bobsilon get it sorted out then?

**Comment by bobsilon** [comment]
Yes Sir Daniel, I've done it by checking if the route is `posts` and the param `filter[name]`(which I get a single post by it's `slug`) has been set, like this: 

``` php
if ( end(explode('/', $request->get_route())) === 'posts' &&
     $request->get_params()['filter']['name'] )
```
