### ISSUE TITLE
Menus endpoint

### ISSUE THREAD

**Issue by krasi** [WP-API/WP-API#2328]
Hello,

Are there any plans on adding menu endpoints? I saw there was a plugin for that, but I don't like the idea to use third party plugins in such purpose. I can also help by contributing such functionality if nobody is working on it, but it's planned.

Thanks!

Best Regards,
Krasi

**Comment by rmccue** [comment]
Hi! We're working on those [in a feature plugin](https://github.com/WP-API/wp-api-menus-widgets-endpoints).
