### ISSUE TITLE
Standardize name of project/plugin

### ISSUE THREAD

**Issue by bbttxu** [WP-API/WP-API#233]
In order to make the project/plugin more consistent, I think it would be good to standardize the name. I found three different names, which seem to refer to the same project:

  - wp-api: this github project, https://github.com/WP-API/WP-API
  - json-api: http://make.wordpress.org/core/tag/json-api/
  - json-rest-api: the downloadable .zip file, http://wordpress.org/plugins/json-rest-api/

Which is the proper name?

**Comment by danielbachhuber** [comment]
Closing in favor of #850
