### ISSUE TITLE
Is the link to WP-API 1.2.5 intentional? (among other links)

### ISSUE THREAD

**Issue by mjacobsen4DFM** [WP-API/WP-API#2331]
The readme points to https://wordpress.org/plugins/json-rest-api/ within:
"The latest stable version is available from the [WordPress Plugin Directory](https://wordpress.org/plugins/json-rest-api/)." Which is the old version 1.2.5; which is really nothing like this version.

Likewise, the plugin page within WP admin points to http://wp-api.org/ for the "WP REST API Team" and "view details" points to an [information page](https://wirehub.dfmdev.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=wp-api&TB_iframe=true&width=600&height=550)  which is regarding a [WP API version 1.0.3](https://wordpress.org/plugins/wp-api/), which is entirely different!

Is that all intentional since 2.0 is still beta?

**Comment by rmccue** [comment]
Good catch, we should fix that :)

**Comment by BE-Webdesign** [comment]
I can take care of this at some point today, will have a PR tonight.

**Comment by mjacobsen4DFM** [comment]
It's always the little things. Brilliant code is fun... documentation, not so much.

**Comment by BE-Webdesign** [comment]
@mjacobsen4DFM , @rmccue So #2334 patches up a portion of this issue however there is a plugin in the WordPress.org Plugin Repo with the name WP-API so the View Details link is being auto generated to match that plugin even though the two are not the same plugin.

**Comment by rmccue** [comment]
Fixed in #2334.
