### ISSUE TITLE
Default API call rate limit

### ISSUE THREAD

**Issue by bfintal** [WP-API/WP-API#2332]
I found this quick closed discussion about this: #963

> This isn't something the API supports out of the box. You'll need to create your own rate-limiting mechanism.

Isn't it a good idea to add some sort of default rate limit for all API calls already baked in? e.g. 200/hour/IP then maybe a filter to change it.

**Comment by rmccue** [comment]
API rate limiting is pretty trivial to implement in a plugin, but there's many ways you might want to limit it. For small sites, it's unlikely to be an issue, and for large sites, they'll likely want a specialised system to store API access and such.

There's not really a need for rate limiting for the majority of sites, so building it in doesn't make sense.

**Comment by bfintal** [comment]
Alright. Thanks
