### ISSUE TITLE
Attributes names issue in embedded post

### ISSUE THREAD

**Issue by MurhafSousli** [WP-API/WP-API#2339]
Hi, I'm using the following code to get the featured image, categories and tags arrays of an embedded post. and this is the only way it worked with me.

```
 var postResponse:PostResponse;
    postResponse = post;
    postResponse.postsCats = post._embedded['https://api.w.org/term'][0]; //for cats
    postResponse.postsCats = post._embedded['https://api.w.org/term'][1]; //for tags

    /* check if the post has a featured image && check if it has a medium size */
    if (post._embedded.hasOwnProperty('https://api.w.org/featuredmedia')
      && post._embedded['https://api.w.org/featuredmedia'][0].media_details.sizes.hasOwnProperty('medium')) {

      postResponse.featuredImage = post._embedded['https://api.w.org/featuredmedia'][0].media_details.sizes.medium.source_url;
    }
```

Did anyone find an easier (more readable) way to access the data with such attributes names?

Thanks

**Comment by rmccue** [comment]
This is correct, the key is a relation, which are either registered strings or full URIs to disambiguate them.

However, we're simplifying this in #1488, so someday it'll be `wp:featuredmedia` instead :)

**Comment by MurhafSousli** [comment]
Great :+1:
