### ISSUE TITLE
Hook rest_insert_comment object does not have comment_ID

### ISSUE THREAD

**Issue by idoidone** [WP-API/WP-API#2340]
Seem the hook `rest_insert_comment` does not work as expected. It is fired after a comment is created or updated, so I expect it has a comment_ID but actually it not.

```
/**
 * Fires after a comment is created or updated via the REST API.
 *
 * @param array           $prepared_comment Inserted comment data.
 * @param WP_REST_Request $request          The request sent to the API.
 * @param boolean         $creating         True when creating a comment, false when updating.
 */
do_action( 'rest_insert_comment', $prepared_comment, $request, true );
```

[The implementation](https://github.com/WP-API/WP-API/blob/7063707a6818652a3e76acbf23e5a3307ce774e2/lib/endpoints/class-wp-rest-comments-controller.php) passes $prepared_comment in but not $comment and missing the ID.
Please correct me if I am wrong.

**Comment by danielbachhuber** [comment]
Thanks for opening this issue.

I think we should pass `$comment` from the database too. We supply the database value for Posts, Users, and Terms.
