### ISSUE TITLE
 json_no_route

### ISSUE THREAD

**Issue by miladna7** [WP-API/WP-API#2343]
i am using WP rest API v1 and everything is ok.
But now i want taste some WP rest API v2. the problem is, when i any route/path, and i mean any route, the result is:
`[{"code":"json_no_route","message":"\u0647\u06cc\u0686 \u0645\u0633\u06cc\u0631 \u062a\u0637\u0628\u06cc\u0642 URL \u0648 \u0631\u0648\u0634 \u062f\u0631\u062e\u0648\u0627\u0633\u062a \u067e\u06cc\u062f\u0627 \u0634\u062f"}]`

So i try somethings, so i find out the reason is, i use wp rest api v1 and v2 together. when i remove wp rest api v1, the v2 return the normal result.
# : i can't remove v1 because it is easy to work and i need v2 because i want to add a rote to get all the post IDs(just post IDs).

**Comment by danielbachhuber** [comment]
By default, WP-API v1 takes priority over v2. If v1 is installed and activated, then v2 routes are inaccessible.

To mitigate this, you'll need to register either v1 or v2 to a different base than `wp-json`. Both have filters to make this more or less easily possible:

```
add_filter( 'rest_url_prefix', function() {
    return 'wp-api';
});
```

**Comment by chiragjak** [comment]
v2 has same problem with me says no rout found
