### ISSUE TITLE
action/filter reference?

### ISSUE THREAD

**Issue by ghost** [WP-API/WP-API#2344]
Hi, I was just looking through the docs for a reference list of all the actions and filters provided by the API. Is there somewhere I can find them? (Apologies if I missed it somewhere.) Thanks!

**Comment by danielbachhuber** [comment]
Searching the codebase is your best bet at the moment, unfortunately.

I've [filed an issue](https://github.com/WP-API/docs-v2/issues/124) to eventually get this on the website.
