### ISSUE TITLE
Unclear on method for checking whether user is logged in or not.

### ISSUE THREAD

**Issue by brandondurham** [WP-API/WP-API#2345]
I’ve built a new site where the Wordpress install lives on one domain (`domain-a.com`) and the front-end on another (`domain-b.com`). The front-end is built entirely in JS (Node.js/React/Redux) and uses the WP-API to retrieve data. I need to build in a way for the admin users and editors to preview draft posts (and updates to published posts). In order to do this I need to know if they’re currently logged in or not.

I don’t need to allow for users to log in via the front-end… I just need to know if they’re currently logged into the system on (`domain-a.com`) or not. Where do I get started with this? Appreciate any suggestions I can get.

**Comment by rmccue** [comment]
This intentionally isn't possible. Being able to check authentication across domains could cause issues like CSRF or phishing attacks.

Can you elaborate on your specific use case? We can probably solve that without needing the authentication that way. :)

**Comment by brandondurham** [comment]
Sure thing. I built the front-end as a single-page app on a server with one URL, and the CMS on another server with a different URL (different top-level domains altogether). I want editors and admins logged into the CMS domain to be able to preview news posts and changes to published posts on the public domain.
