### ISSUE TITLE
Response contains title and json?

### ISSUE THREAD

**Issue by adams141** [WP-API/WP-API#2346]
Doing a simple get to retrieve one post, I get the post title, followed by the JSON object:

`2013 Brochure{"id":802,"date":"2013-01-01T19:51:56","date_gmt":"2013-01-01T19:51:56",...}`

Is this normal?

**Comment by rmccue** [comment]
This isn't something the API is doing, so it's likely in a plugin or theme. I'd guess it's a function hooked into `the_title` filter erroneously echoing instead of returning a string.
