### ISSUE TITLE
How to supply arrays for a filter

### ISSUE THREAD

**Issue by HamutalCohen3** [WP-API/WP-API#2348]
Hi,

I'd trying to use the [tags__and](https://codex.wordpress.org/Class_Reference/WP_Query#Tag_Parameters) filtering. It expects an array with the IDs of the tags I want to retrieve, something like the below,

`$query = new WP_Query( array( 'tag__and' => array( 37, 47 ) ) );`

How do I supply an array using the API? I'm trying to do something like,

`/wp-json/wp/v2/posts?filter[tag__and]=3677,3673`

but it doesn't work. I'd very much appreciate any help.

Many thanks,

Hamutal

**Comment by danielbachhuber** [comment]
Can you try:

```
/wp-json/wp/v2/posts?filter[tag__and][]=3677&filter[tag__and][]=3673
```

**Comment by HamutalCohen3** [comment]
It works! Thank you very much
