### ISSUE TITLE
Postman HEAD returns "Unexpected '' "

### ISSUE THREAD

**Issue by maxvanloosbroek** [WP-API/WP-API#2351]
I just started working with the API and am running into some issues.

When accessing the header in Postman of http://localhost/website/wp-json/ the body only shows:

Unexpected ' '

This is what shows on the Header tab.

Access-Control-Allow-Headers →Authorization
Access-Control-Expose-Headers →X-WP-Total, X-WP-TotalPages
Allow →GET
Connection →Keep-Alive
Content-Type →application/json; charset=UTF-8
Date →Tue, 08 Mar 2016 13:02:27 GMT
Keep-Alive →timeout=5, max=100
Server →Apache/2.4.9 (Win64) PHP/5.5.12
X-Content-Type-Options →nosniff
X-Powered-By →PHP/5.5.12

Status says: 200 OK

Thanks for your time,

Max

**Comment by danielbachhuber** [comment]
WordPress is returning unexpected output. You'll need to debug whether it's a plugin you're running, or your theme. I'd recommend disabling them one by one until you've found the culprit.
