### ISSUE TITLE
Simplifying JSON structure in _embedded section

### ISSUE THREAD

**Issue by stonetip** [WP-API/WP-API#2352]
Currently, the API returns two arrays of items under the https://api.w.org/term section, one for **category** and another for **post_tag**. However, in both cases, a taxonomy attribute is supplied. It seems un-"nest"-essary to have multiple arrays when it would require less code on the receiving end to simply filter on the taxonomy attribute.

**Comment by kadamwhite** [comment]
Not sure what the "best" solution is here, but I do agree that what we have is clunky. There's no way to determine which array is which without inspecting its contents, so we have to do some filtering already; I can see the argument that it's simpler to just always filter down a single array vs inspecting each nested array in turn.

**Comment by danielbachhuber** [comment]
Terms can have and do have different structures. For instance, category has `parent` where `post_tag` does not.
