### ISSUE TITLE
Avoid returning WP_Error in WP_REST_Posts_Controller::prepare_item_for_database()

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#2355]
For developers subclassing `prepare_item_for_database()`, it's inconsistent that request validation is happening in `prepare_item_for_database()` and that I have to check `parent::prepare_item_for_database()` for `WP_Error`

It would be better if request validation happened earlier, such that I could always expect to get the database object from `prepare_item_for_database()`

**Comment by kjbenk** [comment]
I am not sure if this is a discussion thread but I cannot seem to get the action item out of this issue.  Can you better explain what options you were considering to implement?

Maybe a new function `validate_item_for_database` can be implemented and required?

**Comment by danielbachhuber** [comment]
I need to verify this is still a valid issue.

**Comment by danielbachhuber** [comment]
@WP-API/amigos I don't have a great idea on how to unwind this mess :(

In `WP_REST_Posts_Controller->prepare_item_for_database()`, we have a number of places where a `WP_Error` can be returned:
- Status: https://github.com/WP-API/WP-API/blob/17305479fc03d69e025674a7cfc71791b798eb2c/lib/endpoints/class-wp-rest-posts-controller.php#L777
- Author: https://github.com/WP-API/WP-API/blob/17305479fc03d69e025674a7cfc71791b798eb2c/lib/endpoints/class-wp-rest-posts-controller.php#L810
- Password: https://github.com/WP-API/WP-API/blob/17305479fc03d69e025674a7cfc71791b798eb2c/lib/endpoints/class-wp-rest-posts-controller.php#L821
- Sticky: https://github.com/WP-API/WP-API/blob/17305479fc03d69e025674a7cfc71791b798eb2c/lib/endpoints/class-wp-rest-posts-controller.php#L831
- Parent: https://github.com/WP-API/WP-API/blob/17305479fc03d69e025674a7cfc71791b798eb2c/lib/endpoints/class-wp-rest-posts-controller.php#L839

On the other hand, `WP_REST_Terms_Controller` silently discards an invalid parent id: https://github.com/WP-API/WP-API/blob/0e5e8db1a94bd8b9be519aca7535edfd69b45f84/lib/endpoints/class-wp-rest-terms-controller.php#L543

My _preference_ would be that validation be handled much earlier, probably with our existing validation framework. In fact, we could create `WP_REST_Controller->validate_callback()` method, and each controller could subclass to define a switch statement validating the request values needing custom validation.

Thoughts?

**Comment by joehoyle** [comment]
Personally I don't really see much issue with the current design, having the functions be able to return a WP_Error is a good design choice, I'm sure they'll always be nitty-gritty details that these functions may do to warrant returning a WP_Error. 

I'm sure of these could be moved up to `update_item` / `create_item`, I think we didn't do that to avoid the complication. I'm 👎  on `WP_REST_Controller->validate_callback()`, I don't think we need _more_ abstraction to solve this issue, all-in-all I don't think theres much benefit to be had here, so I'm in favour of closing this as #wontfix.

**Comment by danielbachhuber** [comment]
> I'm 👎 on `WP_REST_Controller->validate_callback()`, I don't think we need more abstraction to solve this issue, all-in-all I don't think theres much benefit to be had here, so I'm in favour of closing this as #wontfix.

This would be the same abstraction we encourage plugin authors to use (e.g. use `register_rest_field()` to register a `sanitize_callback`)?

Have you subclassed this method before?

**Comment by rachelbaker** [comment]
Abstracting all of the checks that result in returning `WP_Error` from our controllers is a significant task for the sole purpose of making it easier to subclass our controllers. 
I am closing this ticket.  We do not have a clear direction to resolve this reported bug, and after WordPress 4.7 ships we will be restricted by back-compat.  
If someone is passionate enough about this ticket to submit a PR to resolve it, then by all means please re-open.
