### ISSUE TITLE
`/posts/?filter[posts_per_page]=-1` returns all posts

### ISSUE THREAD

**Issue by miya0001** [WP-API/WP-API#2357]
`per_page` must be between 1 and 100, but following request returns all posts.

```
/wp-json/wp/v2/posts/?filter[posts_per_page]=-1
```

Is it all right?

https://github.com/WP-API/WP-API/issues/1609#issuecomment-146568663

**Comment by danielbachhuber** [comment]
No, we should enforce a minimum.

**Comment by miya0001** [comment]
OK! I want to send PR, please wait couple of days. :)

**Comment by technotip** [comment]
Is it fixed?

I'm using filter[posts_per_page]=1 followed by &filter[before]=somevaliddate and it returns 1st post published on the blog &filter[after]=somevalidDate returns last/latest post published on the blog.

How can I solve this?

**Comment by deonvisser** [comment]
Have you tried ../posts?per_page=1&before="somedate"
per_page and before are arguments not parameters. You do not need to add filter.
Works for me.

**Comment by kadamwhite** [comment]
Confirmed that `/wp-json/wp/v2/posts?per_page=-1` correctly triggers validation, but `/wp-json/wp/v2/posts?filter[posts_per_page]=-1` still does return all posts.
