### ISSUE TITLE
403 Forbidden when PUT to wp-json/users/$id through OAuth/Guzzle

### ISSUE THREAD

**Issue by ghost** [WP-API/WP-API#2358]
We're using Laravel to control blog/user creation and I'm trying to create a blog and set that users nickname to their Auth first name and last name.  Creating the blog works, creating the user works. BUT when I try to modify that user to change their nickname and display_name I get a 403 forbidden error.  Has anyone else had this experience?  I know i can do a get because Laravel is receiving the proper information about that specific ID when I call it, but ONLY when I PUT or POST to users/$id do I get the 403 forbidden.  I hope this makes sense enough to someone to help.

Thanks

**Comment by ghost** [comment]
Is this too unique a case for anyone to relate to?

**Comment by BE-Webdesign** [comment]
Does the user you are authenticating as have permissions to modify the user you created and want to change?  Which 403 error message are you getting as well?

**Comment by ghost** [comment]
They DO, and for some reason, guzzle is only returning that it's a 403 and not the actual WP Error message...  I thought it would be in my Error logs on the WP site but I don't see it there.

**Comment by BE-Webdesign** [comment]
I will look into it and see if I can replicate this.  Just to verify, this is done on a user you just created via the API and then you follow up with a subsequent update on nickname and display_name?

**Comment by ghost** [comment]
That is correct.  The user is created on a Multisite instance with a new blog and then subsequent update to their nickname and display name.

**Comment by BE-Webdesign** [comment]
Okay, thank you.

**Comment by danielbachhuber** [comment]
> The user is created on a Multisite instance with a new blog and then subsequent update to their nickname and display name.

Admin users can't edit user fields in multisite. You'd need to be a super admin.

**Comment by BE-Webdesign** [comment]
He said the account had permissions so I'm assuming super admin.

**Comment by ghost** [comment]
Yes, the account oAuth/Guzzle uses is Superadmin

**Comment by ghost** [comment]
Client error response [url] https://_blogurl_/wp-json/users/6 [status code] 403 [reason phrase] Forbidden
/laravel/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php#89

This is the error I'm getting back from Guzzle and the WP logs are empty.

**Comment by BE-Webdesign** [comment]
Hi @chadsterBAM ,

Thank you for your patience.  I am unable to duplicate any errors on update requests for a user on a multisite install with super admin capabilities.  Tested with [oAutho1.0a ](https://github.com/WP-API/OAuth1) and I assume you have this installed at the network level as you were creating users fine.

> https://blogurl/wp-json/users/6

If that is the link you are using that could potentially be the problem it should be https://blogurl/wp-json/wp/v2/users/6, but I am assuming that was a typo.

> Client error response [url] https://blogurl/wp-json/users/6 [status code] 403 [reason phrase] Forbidden
> /laravel/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php#89

Seeing that an exception is being thrown by guzzle I imagine you aren't even hitting the API, which would leave the WP logs empty.  I am going to close this issue for now but we can continue to discuss it here if you would like further help or have other ideas about the problem at hand.  I however have zero experience with laravel so I don't know how much help I can offer :smiley:
