### ISSUE TITLE
How to fetch category wise project

### ISSUE THREAD

**Issue by bhagwan123** [WP-API/WP-API#2365]
I use this request for fetching the project  http://localhost/development/turner/wp-json/wp/v2/project
 this working fine.But fetching category wise project its not working http://192.168.2.8/development/turner/wp-json/wp/v2/project?filter[cat]=3

**Comment by danielbachhuber** [comment]
> But fetching category wise project its not working

Can you share more details on what you mean by "not working", including the full request you're making, the full response, and any debugging you've done?
