### ISSUE TITLE
How to add custom response headers to custom post type archive?

### ISSUE THREAD

**Issue by gwashbrook** [WP-API/WP-API#2366]
Following code works for me on a single custom post type (cpt) response, yet does not appear to be applied to the custom post type archive response. I think I have checked the possible filters, yet am more than happy to be corrected

```
add_filter( 'rest_prepare_cpt', 'my_rest_headers', 10, 1 );

function my_rest_headers( $response ) {
    $response->header( 'Cache-Control', 'max-age=3600' ); // 1 hour
    return $response;
}

```

**Comment by danielbachhuber** [comment]
You're using the wrong filter, because your callback isn't being called. If it were being called, you'd get a fatal error, because the `WP_REST_Request` method is `add_header()`, not `header()`.
