### ISSUE TITLE
The future of WP-API in light of core integration

### ISSUE THREAD

**Issue by newz2000** [WP-API/WP-API#2367]
I'm planning a project that will hopefully have a long life. This project will just be getting underway when WP 4.5 is supposed to land but done before 4.6.

I understand that features of WP-API 2 are moving into core, but something that isn't clear to me is how I should target my code. Right now, in 4.4, it looks like I'll need to use WP-API in order to get the end points I want. If I build my project with a dependency on WP-API will WP-API eventually go away as being unneeded (since it's features are in core) or will it continue to be supported?

**Comment by danielbachhuber** [comment]
> I understand that features of WP-API 2 are moving into core, but something that isn't clear to me is how I should target my code.

You should use the `wp/v2` endpoints for your project. At this point, if/when the REST API endpoints ever make it into core, they'll be namespaced to a separate path. As long as your project has this plugin enabled, it can always depend on`wp/v2` routes being available.

We're transitioning the project towards producing a stable 2.0 release of the plugin. While there are likely to be a few more breaking changes between now and then, we'll hopefully hit a stable release at some point during the course of your project.
