### ISSUE TITLE
Turkish character search and filter problem

### ISSUE THREAD

**Issue by obzc** [WP-API/WP-API#2373]
I searching "balık" but not found results. I type "balik" found results.

http://www.kiztarafi.com/wp-json/wp/v2/posts?search=balık&filter[cat]=207

Please help me.

**Comment by JPry** [comment]
@oktaybzc 

> I searching "balık" but not found results. I type "balik" found results.
> 
> http://www.kiztarafi.com/wp-json/wp/v2/posts?search=balık&filter[cat]=207
> 
> Please help me.

When I view your link above, I see results returned. What problem are you having exactly?
