### ISSUE TITLE
Get just a collection of permalinks from a parent post without the content

### ISSUE THREAD

**Issue by oivinds** [WP-API/WP-API#2374]
Is there a way to get a list of permalinks from a parent post without the content, excerpt and other fields?
I would like to display lists of anchor links on the front end, belonging to a category   

This is my current query : 
/wp-json/wp/v2/houserules/?filter[category_id]='+cat.id; 

Obviously, I got the information I need from the above query to do what I want, but I assume the load time will be shorter when just returning the data I need.

**Comment by danielbachhuber** [comment]
We may eventually offer a way to limit response fields in the request, but it isn't a part of the core plugin right now.

> I assume the load time will be shorter when just returning the data I need.

Incorrect. The load time will be the same.

**Comment by oivinds** [comment]
Allright, thanks!
