### ISSUE TITLE
Trying to get current user 

### ISSUE THREAD

**Issue by amitrathik** [WP-API/WP-API#2376]
I have an end point where I load all the posts. That works fine. 
Trying to use *_wp_get_current_user() *_to map the current user Id, but won't return the user even though I'm logged in

**Comment by JPry** [comment]
> but won't return the user even though I'm logged in

How are you authenticating with the API? Are you using cookies for authentication?

**Comment by amitrathik** [comment]
Currently, I'm not doing authentication.
The endpoint is setup for GET requests. I was hoping to be able to use the _wp_get_current_user()_ function.

**Comment by JPry** [comment]
> Currently, I'm not doing authentication.

As far as the API is concerned, a request has no user unless you [use some form of authentication](http://v2.wp-api.org/guide/authentication/). With no authentication, you can expect `wp_get_current_user()` to return a `WP_User` object with `0` for the user ID. In other words, **no** logged in user.

**Comment by amitrathik** [comment]
Thanks. I figured that was the issue. I thought I could get by without doing authentication for cookie auth.
