### ISSUE TITLE
WP Rest API v1

### ISSUE THREAD

**Issue by jamiepickett** [WP-API/WP-API#2378]
I could not find in the documentation examples of adding tags and categories to a post using the api, but it looks like inside of the class-wp-json-taxonomies.php there is a method for adding terms to a post:

/**
     \* Add term data to post data
     *
     \* @param array $data Post data
     \* @param array $post Internal post data
     \* @param string $context Post context
     \* @return array Filtered data
     */
    public function add_term_data( $data, $post, $context ) {

Is it possible to add tags to a post and if so, what does the rest URL look like for that?

Thanks,
J

**Comment by danielbachhuber** [comment]
Sorry, but v1 is no longer supported aside from security issues. We'd strongly encourage you to update to v2.

**Comment by jamiepickett** [comment]
A couple things are preventing me from using the v2 api...
1: We cannot upgrade our production instance of WP to 4.4.  We are using 4.2.7
2: Our software folks won't allow us to use a BETA plugin in our production instance.

Do you know off hand if the v1 api supports adding of tags and categories to a post or will custom end points have to be written in order to support it?

**Comment by danielbachhuber** [comment]
> Do you know off hand if the v1 api supports adding of tags and categories to a post

It does, see https://github.com/WP-API/WP-API/blob/master/lib/class-wp-json-posts.php#L224

**Comment by jamiepickett** [comment]
This is an example of the data object that I am passing into the API.  All of the values get set for the post except for the terms...  

var data = {
  "type": "pnext_recipe",
  "title" : jQuery("#title").val(),
  "content_raw" : jQuery("#content_raw").val(),
  "status" : "draft",
  "comment_status" : "closed",
  "excerpt_raw" : "its raw",
  "terms" : {
    "post_tag" : "neil,bob"
  },
  //we create blank values for these fields so we can get their meta id back
  "post_meta" : [{
    "key":"pnext_recipe_skill",
    "value" : ""
  }]
}

**Comment by danielbachhuber** [comment]
Please see the docs for `wp_insert_post()` https://developer.wordpress.org/reference/functions/wp_insert_post/

Try using `tax_input` or `tags_input`. The API docs may be wrong.
