### ISSUE TITLE
status 404 for Multisite

### ISSUE THREAD

**Issue by mantismamita** [WP-API/WP-API#2379]
When I go to mylocalsite.dev/wp-json/wp/v2/posts I get a json_no_route message ("No route was found matching the URL and request method"). 

I have the WP REST API plugin activated at the network level and have tried activating it at the site level with the same result. I am using the WP Multi-Network plugin as well. I am testing it on a local vagrant server. The site doesn't use subdomains but does use domain mapping.

**Comment by danielbachhuber** [comment]
> get a json_no_route message ("No route was found matching the URL and request method").

Do you have WP-API v1 active on the WordPress install?

**Comment by mantismamita** [comment]
So I did indeed have the wrong one active but changing it to the right version(2) didn't work either. No error message but no jason feed either. I just get my home page with the url mylocalsite.dev/wp-json/wp/v2/posts no errors either.

**Comment by danielbachhuber** [comment]
> No error message but no jason feed either.

Did you flush your rewrite rules?

**Comment by mantismamita** [comment]
Aha! Yes but for the wrong version :/ Got it now. Thanks :)

**Comment by danielbachhuber** [comment]
:+1:
