### ISSUE TITLE
Add get_items_permissions_check() method to Users controller

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#2382]
To be consistent with our other controllers, we should have a `get_items_permission_check()` method on the Users controller. If `context=edit` and the user can't edit users, it should return an error, similar to our existing controllers.

**Comment by BE-Webdesign** [comment]
I'll add this into #2372?  Or is it better to have a separation of concerns and create a separate PR?

**Comment by danielbachhuber** [comment]
> Or is it better to have a separation of concerns and create a separate PR?

Separate PR, please :)
