### ISSUE TITLE
Use more loose coupling between user visibility in the API and published posts

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#2385]
I'm subclassing the Users controller for a type of Users that I don't want publicly accessible in the API, even if they've published a 'public' post. It would be nice if `get_item_permissions_check()` was more loosely coupled to publish posts, such that I could still override the behavior of whether a user is viewable in `map_meta_cap`.

Related #2384

**Comment by BE-Webdesign** [comment]
Was this taken care of in [this PR](https://github.com/WP-API/WP-API/commit/da9da14ad12032a0297d027b811b102ad38714ba)?  Couldn't you just also override the `get_item_permissions_check()` if you are already subclassing?

**Comment by rmccue** [comment]
I think I'm OK with just overriding the whole method here; we have to strike a balance between readability/usability and customisability, and making it _too_ modular sounds problematic for forwards-compatibility as well.

The PR handled the specific case, so closing this out.
