### ISSUE TITLE
Update documentation on contributing to WP-API

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#2392]
Specifically:
- [x] How to run tests and the linter locally.
- [x] Link to CONTRIBUTING.md from README.md

**Comment by kjbenk** [comment]
Here are some other things worth noting:
1. Explanation of our continuously deployment system, [Travis CI](https://travis-ci.org/WP-API/WP-API).
2. Explain and document what `grunt` is and how to install and run it.  Maybe go over the `Gruntfile.js`.
3. Explanation of our coding standards, aka a slimmed down version of WordPress VIP. Maybe go over the `phpcs.ruleset.xml`.

Once contributors understand these topics and tools they should commit pull requests with a higher pass rate :)
