### ISSUE TITLE
WP REST API v2 filter not working

### ISSUE THREAD

**Issue by andymok221** [WP-API/WP-API#2394]
`/wp-json/wp/v2/posts?per_page=1` not working. It returns all posts instead of one.

**Comment by danielbachhuber** [comment]
Just to verify, you're using Beta 12? And you've disabled all plugins and switched to Twenty Sixteen to ensure it's not being caused by custom code?

If so, can you share your full request, and the full response?

**Comment by Kevinlearynet** [comment]
Upgrading to Beta 13 corrected this for me.

**Comment by luisfredgs** [comment]
Same problem here. I'm use 2.0-beta15.

**Comment by george-codes** [comment]
Same problem here. I'm use 2.0-beta15. No filter is recognized. It only throws 10 posts no matter what.

**Comment by luisfredgs** [comment]
Solved now! Just install this plugin and Filters will restored: https://github.com/luisfredgs/rest-filter

thanks!
