### ISSUE TITLE
Internal Server Error while accessing Custom Post Type over WP-Rest-API

### ISSUE THREAD

**Issue by manikmagar** [WP-API/WP-API#2395]
I have a custom post type Store which I access over WP Rest API endpoint wp-json/wp/v2/store. I added few more custom fields to this post type and suddenly I started getting Internal Server Error when endpoint is called.

I saw below error in logs -
`PHP Fatal error:  Call to a member function fields() on a non-object in /wp-content/plugins/pods/classes/PodsRESTHandlers.php on line 79
`

After looking at the code at that line, I guessed it must be because of relationship field so I removed that field, saved the pod and access API again. **And then I get the correct response from API**.

If I add this field back to post type, it again breaks the API response.

*_Field Configuration - *_
Field Type: Relationship
Related To: Simple (custom defined list)
Custome Defined Options: 
CB|Cashback
SR|Store Rewards
CP|Coupon Only

Allow to read on API: Yes

Can someone please take a look at this?

**Comment by manikmagar** [comment]
Update - 
Rest API tab for this field, If I choose to "Response Type = ID Only" then it works but If I choose "Response Type=Full" then it doesnt.

For me, I just need ID so I am good for now, but it would be good to have full info in response.

**Comment by rachelbaker** [comment]
@manikmagar This doesn't sound like an issue with the WP REST API itself, it sounds like an issue with Pods. More specifically with their `PodsRESTHandlers.php` file.

**Comment by manikmagar** [comment]
@rachelbaker Thanks for closing that and sorry for opening it at wrong place :). I knew it was for Pods but looks like got haunted by multiple open windows. I meant to open it on Pods Github :D. Funny thing is, after opening it here, I even copy pasted link on Pods Support forum :D.

NVM, I will open it on Pods. Thanks.
