### ISSUE TITLE
Return consistent status code on update / delete requests to invalid resource id

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#2398]
Sometimes we're returning a 404:

```
if ( ! $term ) {
    return new WP_Error( 'rest_term_invalid', __( "Resource doesn't exist." ), array( 'status' => 404 ) );
}
```

Other times, we're returning a 400:

```
$user = get_userdata( $id );
if ( ! $user ) {
    return new WP_Error( 'rest_user_invalid_id', __( 'Invalid resource id.' ), array( 'status' => 404 ) );
}
```

We should consistently return a 404 when the resource doesn't exist. 400 is less precise, and better for reporting invalid request arguments.

**Comment by rachelbaker** [comment]
For `create` or `update` requests when a given association (like `post_parent`) does not exist I think we **want** to return `400`. 

> 400 Bad Request
> 
> The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modifications.
> 
> General error when fulfilling the request would cause an invalid state. Domain validation errors, missing data, etc. are some examples.

Otherwise, I agree.  💯
