### ISSUE TITLE
merge mutiple routes

### ISSUE THREAD

**Issue by mineralwassermedium** [WP-API/WP-API#2399]
Hello

When I want to make a get request to fetch posts and also append some other data to that response. What is a good way to do it?

For example, the client makes this request

```
GET /posts/id
```

and the response should be: the post and the current user's data.

So for example for meta data, I register those fields. But what do I do when there already is a existing route to the data I want to add?
Can I do something like this?

```
register_rest_field('post', 'user', array( 'get_callback' => 'get_user');

function get_user($user, $field, $request) {
   $controller = new WP_REST_Users_Controller;
   $user = $controller->get_current_item($request);
   return $user;
}
```

Or do I have to make an extra request to 

```
/users/me
```

Or is there another/better way?

**Comment by danielbachhuber** [comment]
> Or is there another/better way?

If you have a limited amount of data you want to include that follows a consistent format, you can use `register_rest_field()`

If you want to link response objects, you should use the [linking](http://v2.wp-api.org/extending/linking/) feature in the API. Then, in your request, you can use `?_embed` to include the embedded version of the resource in your response.
