### ISSUE TITLE
permission callback runs twice

### ISSUE THREAD

**Issue by zabatonni** [WP-API/WP-API#2400]
im using permission callback to check for IP address and writing log about unauthorized activities

I have set up route like this:
`register_rest_route('expres/v1','/check-audio',array(
            'methods'=>'GET',
            'callback'=>array($endpoint,'check_audio'),
            'permission_callback'=>array($this,'permissions'),
            'args'=>array(
                'type'=>array(
                    'required'=>true,
                    'validate_callback'=>array($this,'validate'),
                ),
            ),
        ));`

Each time I call GET request /check-audio, permission_callback function runs twice, regular callback runs once as expected

**Comment by danielbachhuber** [comment]
> Each time I call GET request /check-audio, permission_callback function runs twice, regular callback runs once as expected

It's expected to have the permission callback run twice, as it's run once for the `Allows` header and then a second time for the callback itself.
