### ISSUE TITLE
Using 'prepare_item_for_response' in custom Endpoints

### ISSUE THREAD

**Issue by jdcauley** [WP-API/WP-API#2401]
I would like to normalize post data to reflect patterns in used by default in some custom endpoints.

I'm having trouble finding any information or documentation about how I could achieve this.

**Comment by danielbachhuber** [comment]
> I would like to normalize post data to reflect patterns in used by default in some custom endpoints.

Can you describe in greater detail what you're trying to do?

**Comment by mostafasoufi** [comment]
There is an example of callback function for preparing posts data:

```
/**
 * @param \WP_REST_Request $request
 * @return \WP_REST_Response
 */
public function get_custom_post_items(\WP_REST_Request $request)
{
	$args = array('posts_per_page' => 5);
	$posts = get_posts($args);
	$posts_arr = array();
	$rest_post = new WP_REST_Posts_Controller('post');

	foreach ($posts as $post) {
		$posts_arr[] = $rest_post->prepare_item_for_response($post, $request)->data;
	}

	return $posts_arr;
}
```
