### ISSUE TITLE
Is there a way to add Cache header to response for improving performance?

### ISSUE THREAD

**Issue by manikmagar** [WP-API/WP-API#2404]
I am going to use Wordpress as a backend CMS for a website built on java. I have wordpress and a java web application deployed on same VPS box. Java web application will be getting posts and other data using WP Rest API. Right now I am struggling with performance issues where WP REST API call to get posts takes 5-6 seconds. Apache HTTPClient that I am using to make api calls have cache mechanism but since there is no cache header in API response it is not caching anything.

Is there any way to add cache headers in the return response? Data on wordpress would be near-static data or can be cached for minimum a day.

**Comment by AlbertGuadan** [comment]
it does sounds like some thing,   interesting idea.
lots going on.  Maybe shut an open  Java Scripts browser running if not,
Sounds like you need some cache  Java seems a bit much seems.

**Comment by AlbertGuadan** [comment]
some times the rain drops my Java from getting to me in whole,  as some of the lmnop s may have been in rain before getting to you being weather.  Java has lots of characters in it. When the internet is slow or any thing interfering with how Java fly's in the air waves, was my other guess, and you still need cache.

**Comment by AlbertGuadan** [comment]
Is it possible to make a GET:  call to fetch your installed Cacheplugin
would be my next solution

 makes the call directly into an installed plugin s cache bucket or any other plugin/source

**Comment by danielbachhuber** [comment]
> Is there any way to add cache headers in the return response? Data on wordpress would be near-static data or can be cached for minimum a day.

Yes, you can use the `rest_post_dispatch` filter to add arbitrary data to the response: https://developer.wordpress.org/reference/hooks/rest_post_dispatch/

Keep in mind, this filter is run for both successful and failed responses, so you'll likely only want to add cache headers on the successful ones.

**Comment by manikmagar** [comment]
@danielbachhuber Cool, that is what I was looking for. I added cache headers in the response and now my client side is caching the responses. Thanks for the link.

**Comment by danielbachhuber** [comment]
@manikmagar Glad to hear it worked out :)
