### ISSUE TITLE
Working with Carbon

### ISSUE THREAD

**Issue by amitrathik** [WP-API/WP-API#2406]
I am working on a WP project where I am using the Carbon library( http://carbon.nesbot.com/) to work with dates and times.
I set up a basic callback function like 
 function test($request){
    $carbon = new Carbon();
     return 'here';
  }

When I use postman to test the endpoint, I get "Unexpected "<" " response. Not sure if the issue is Carbon related or API related, but it would be great if I could use the library inside the callback.

**Comment by danielbachhuber** [comment]
> When I use postman to test the endpoint, I get "Unexpected "<" " response.

There's likely some code producing unexpected output in the response. Can you share the full response?

**Comment by amitrathik** [comment]
Turns out it wasn't being included/found properly.
