### ISSUE TITLE
Filter all post by exclude tag

### ISSUE THREAD

**Issue by fobar21** [WP-API/WP-API#2409]
Dear, i want exclude all post which doesnt contain tags e.g. archive:

http://localhost/test-api/wp-json/wp/v2/posts?filter[tag__not_in]=archive

Can i do on some way return all post without any tags? 

Thx

**Comment by BE-Webdesign** [comment]
Hi @fobar21,

> http://localhost/test-api/wp-json/wp/v2/posts?filter[tag__not_in]=archive

`tag__not_in` expects an array of IDs as opposed to slugs, so the above query won't do anything.

> Can i do on some way return all post without any tags?

There are a ton of ways do that.  I believe the most performant method would be to fetch all posts and then strip out any posts with a tag in your app.  The only caveat is you would need to handle pagination.
