### ISSUE TITLE
categories?filter

### ISSUE THREAD

**Issue by fobar21** [WP-API/WP-API#2410]
Can i use some filter in categories request, e.g.:
/categories?filter[category__not_in]=archive

?

thx a lot

**Comment by danielbachhuber** [comment]
You can use the `exclude` parameter, but you'll need to know the term ID http://v2.wp-api.org/reference/categories/

```
GET /wp/v2/categories?exclude=22
```

**Comment by jfalcone** [comment]
OK, so do any of these filters work?  This is a pretty serious omission.

category_name (string) - use category slug.
category__and (array) - use category id.
category__in (array) - use category id.
category__not_in (array) - use category id.
