### ISSUE TITLE
Conflict with Ultimate Profile Builder

### ISSUE THREAD

**Issue by myrafletcher** [WP-API/WP-API#2411]
I cannot get this plugin to work properly with my Ultimate Profile Builder plugin, I need this plugin for the content of my site. Any suggestions would be much appreciated.

**Comment by danielbachhuber** [comment]
> I cannot get this plugin to work properly with my Ultimate Profile Builder plugin,

Can you describe in greater detail what you're trying to do, and what's not working?

**Comment by myrafletcher** [comment]
I am trying to build an app with Worona which requires rest API, when my ultimate profile builder is active it says content unavailable please check the content of /we-json if should like like this....and when I look at it, it's showing CSS from ultimate profile builder. You can see it at:
Http://allaboutwater/socialitemediamarketing.ca/wp-json

**Comment by danielbachhuber** [comment]
> when I look at it, it's showing CSS from ultimate profile builder.

Ok. You'll need to deactivate Ultimate Profile Builder, or prevent it from running when there's a REST API request. There's not much we can do from the REST API plugin perspective.

Also, you should look into updating to WP-API v2, as v1 is no longer supported except for security fixes.
