### ISSUE TITLE
Display post category name

### ISSUE THREAD

**Issue by kaito-kaito** [WP-API/WP-API#2414]
Hi everyone. How are you? hope you are great. 
I have a question about getting the name of the category that is assigned to the current post (meaning I want to display the category of the current post) in ionic. 
I tried to use {{post.categories}} but it returns 0. Also I used this {{post.categories[0]}} to get the first element in the array but it does not work. 
http://i.imgur.com/dOtov1L.png

Do I have to put something the the controller?

**Comment by BE-Webdesign** [comment]
Are you using wp-api.js or what are you using to make your requests?  Below talks about what requests you would potentially want to make.

`wp-json/wp/v2/categories/25` This returns the data for the category with 25 as its ID.  However, this second request is very specific and it is best to get more data in fewer requests so there is no network overhead.

Performance wise it is best to get data that will be initially rendered rather than making lots of individual requests. If you do a call to the categories endpoint and you can match the ids for the posts you are retrieving.

**Comment by kaito-kaito** [comment]
Thanks BE-Webdesign for reply. I am using WP-REST-API plugin. 
I don't want to get posts of category=25. I want to display the category itself just like if I want to display the title of the post and other fields.

**Comment by BE-Webdesign** [comment]
Yes, if you request `wp-json/wp/v2/categories/25` you will receive the information you are looking for i.e. the name of the category.  In your response for your post it shows `categories: [ 25 ]`.  The 25 represents the ID of the category.  So the name for `wp-json/wp/v2/categories/25` will match up with the category for the post because the IDs match.

**Comment by kaito-kaito** [comment]
The question is (How can I get the ID?) :D 
Sorry, I'm new in this field.

**Comment by BE-Webdesign** [comment]
No worries, glad to help the best I can haha.

So first you make a request to the post(s) you want to use.  In that response you will have categories: [ array of ids here ].  So you take the IDs from there and you would match it to IDs found in a wp/v2/categories request and take the name from the json you get back for the categories you want to display.

I am going to close this issue but we can continue to discuss here, if you need more help.

**Comment by kaito-kaito** [comment]
I got your point but let me explain more about my issue. 
First, In my controller I have a scope variable called (post) that store all data of the requested post. So, now if I want for example access to the title I just have to write {{post.title.rendered}} and it works. but when I type {{post.categories}} to get the category it returns 0. I know it is an array even If I type {{post.categories[0]}} it returns 0 also. So, the main question is how can I get the categories id that associated to this post?

**Comment by BE-Webdesign** [comment]
I am totally unfamiliar with Ionic and from your issue it seems more like an issue with Ionic as opposed to the WP API.  Is the post in your post object the one with the category ID of 25?  If you can provide a little bit more of your code I may be able to help you out with that.

**Comment by kaito-kaito** [comment]
This is my controller
`
.controller('postNewsDetailCtrl', function($scope, $stateParams, DataLoader, $ionicLoading, $rootScope, $sce, CacheFactory, $log, Bookmark, $timeout ) {

```
if ( ! CacheFactory.get('postCache') ) {
    CacheFactory.createCache('postCache');
}

var postCache = CacheFactory.get( 'postCache' );

$scope.itemID = $stateParams.paId;

var singlePostApi = $rootScope.url + 'posts/' + $scope.itemID;

$scope.loadPost = function() {

    // Fetch remote post

    $ionicLoading.show({
        noBackdrop: true
    });

    DataLoader.get( singlePostApi ).then(function(response) {

        $scope.post = response.data;

        $log.debug($scope.post);

        // Don't strip post html
        $scope.content = $sce.trustAsHtml(response.data.content.rendered);

        // add post to our cache
        postCache.put( response.data.id, response.data );

        $ionicLoading.hide();
    }, function(response) {
        $log.error('error', response);
        $ionicLoading.hide();
    });

}

if( !postCache.get( $scope.itemID ) ) {
    // Item is not in cache, go get it
    $scope.loadPost();
} else {
    // Item exists, use cached item
    $scope.post = postCache.get( $scope.itemID );
    $scope.content = $sce.trustAsHtml( $scope.post.content.rendered );
    // $scope.comments = $scope.post._embedded['replies'][0];
}
```

})
`

and this is post detail page
`
<ion-view view-title="{{post.title.rendered}}">
    <ion-content dir="rtl">
        <div class="padding">
            <p>{{post.title.rendered}}</p>
            <p>{{post.categories[0]}}</p> 
        </div>
    </ion-content>
</ion-view>
`

**Comment by BE-Webdesign** [comment]
And the post in question does not have a category of 0? Is there a cached post that you keep accessing that does not have categories?

**Comment by kaito-kaito** [comment]
The post has an array of categories, so if I want to access the first element in the array I will have to specify the first index which is 0, right?

**Comment by kaito-kaito** [comment]
I got it. There was some errors. I now can get the title. Thank you very much for your help.

**Comment by iammash** [comment]
Hi @BE-Webdesign , i have followed you explanations, my situation is similar to @kaito-kaito 's, where i am getting category ID, but i would like to have category names. So far I managed to create a custom plugin for my WordPress blog which allows me to get post images (of course am not a php developer, so i just pasted if from somewhere online), but what the plugin does is convert the image ID's and get featured images url's. Would you be kind to help me with a function which i add to my custom plugin to use the category ID's to get the names of the categories. My App so far,  (Am using ionic 2)

![image](https://cloud.githubusercontent.com/assets/21077222/21921254/7069b468-d96f-11e6-9740-5cdd76001849.png)

**Comment by audacitus** [comment]
@iammash I had the same issue and this is how I solved it: 

- Loaded categories list and prepped into an object with category ids as keys
- built a pipe that took the category id as values and used the category object as the filter arguement

I've written about it here: https://audacitus.com/site/2017/03/02/wordpress-rest-api-to-ionic-2-converting-category-id-to-name/

**Comment by iammash** [comment]
@audacitus thanks for the great tutorial...... I have managed to get my categories showing. However for some posts i am getting "undefined" and yet those posts actually belong to some categories. how can i resolve that?.

**Comment by audacitus** [comment]
@iammash Glad you like it. The script needs more work. The "undefined" is most likely to the http request for the categories not completed before the feed is loaded. To fix this, you would have to move the observable request into the pipe and listen for changes there.

I think that's the gist of it until I rework it.

**Comment by iammash** [comment]
@audacitus Will try that thanks. When I was reading the post you had directed me to, i noticed the MagazaWp ionic 2, how ever when i wen to the buy it link. its saying the item is no longer available. And the am getting and error when i try to request a demo from the provided form. Would provide me with a demo apk and the working link where i can purchase the source code in case it meets my needs after i try out the demo. you can email me at rkaponde@gmail.com

**Comment by audacitus** [comment]
Hi @iammash . Thanks for bringing this up. I've fixed the broken link.

I saw your email requesting for a demo. I'll send an email with an apk linked your site.
Thanks for the feedback.

**Comment by iammash** [comment]
@audacitus I am still waiting on that demo. also if you could kindly provide me with your direct email so that i don't have to use this space to get in touch with you.

**Comment by audacitus** [comment]
Hi @iammash . I sent a mail with the demo on sunday. Could you check your bulk folder?
Alternatively, my email is contact@audacitus.com. Send a mail and I'll reply with the demo.

**Comment by audacitus** [comment]
Hi. Where you able to try it out?

**Comment by iammash** [comment]
@audacitus  yes, its great. however, some images are not loading. even after all the other images are loaded. And the social share feature is not working. how much support do you offer to someone who purchases the template and will the picture issue and social share be fixed.

**Comment by audacitus** [comment]
I'm sure its something server side. Let's switch to email:
contact@audacitus.com

On 6 May 2017 4:33 p.m., "Reuben Kaponde" <notifications@github.com> wrote:

@audacitus <https://github.com/audacitus> yes, its great. however, some
images are not loading. even after all the other images are loaded. And the
social share feature is not working. how much support do you offer to
someone who purchases the template and will the picture issue and social
share be fixed.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/WP-API/WP-API/issues/2414#issuecomment-299647259>, or mute
the thread

**Comment by Shivamsharma625** [comment]
I am fetching only post. but i want that i also fetch post category name? any idea how is it possible?
post code is here.
<?php 
  /**
     *
     * Get The latest product from a category !
     * @param array $params Options for the function.
     * @return string|null product title for the latest,? * or null if none
     *
     */ 
	function get_latest_post ( $params ){
	 	$post = get_posts( array(
        'product_cat'      => $hoodies,
          'posts_per_page'  => 10,
          'offset'      => 0
        ) );

	 	  if( empty( $post ) ){
	 		  return null;
	 	  }
      return $post;
  }

	 // Register the rest route here.
   // get req

  add_action( 'rest_api_init', function () {
    register_rest_route( 'mynamespace/v1', 'latest-post',array(
      'methods'  => 'GET',
      'callback' => 'get_latest_post'
        ) );
  } );

  add_action( 'rest_api_init', function () {      
    register_rest_route( 'mynamespace/v1', 'latest-post',array(
      'methods'  => 'POST',
      'callback' => 'get_latest_post'
    ) );
  } );

  class My_Rest_Server extends WP_REST_Controller {
    //The namespace and version for the REST SERVER
    var $my_namespace = 'my_rest_server/v';
    var $my_version   = '1';

    public function register_routes() {
      $namespace = $this->my_namespace . $this->my_version;
      $base      = 'product_cat';
      register_rest_route( $namespace, '/' . $base, array(
        array(
            'methods'         => WP_REST_Server::READABLE,
            'callback'        => array( $this, 'get_latest_post' ),
            'permission_callback'   => array( $this, 'get_latest_post_permission' )
          ),
        array(
            'methods'         => WP_REST_Server::CREATABLE,
            'callback'        => array( $this, 'add_post_to_category' ),
            'permission_callback'   => array( $this, 'add_post_to_category_permission' )
          )
      )  );
    }
    public function get_latest_post_permission(){
      if ( ! current_user_can( 'edit_posts' ) ) {
        return new WP_Error( 'rest_forbidden', esc_html__( 'You do not have permissions to view this data.', 'my-text-domain' ), array( 'status' => 401 ) );
      }
      // This approach blocks the endpoint operation. You could alternatively do this by an un-blocking approach, by returning false here and changing the permissions check.
      return true;
    }
  }
?>

**Comment by Shivamsharma625** [comment]
I am fetching only post. but i want that i also fetch post category name? any idea how is it possible?
post code is here.
`<?php 
  /**
     *
     * Get The latest product from a category !
     * @param array $params Options for the function.
     * @return string|null product title for the latest,? * or null if none
     *
     */ 
	function get_latest_post ( $params ){
	 	$post = get_posts( array(
        'product_cat'      => $hoodies,
          'posts_per_page'  => 10,
          'offset'      => 0
        ) );

	 	  if( empty( $post ) ){
	 		  return null;
	 	  }
      return $post;
  }

	 // Register the rest route here.
   // get req

  add_action( 'rest_api_init', function () {
    register_rest_route( 'mynamespace/v1', 'latest-post',array(
      'methods'  => 'GET',
      'callback' => 'get_latest_post'
        ) );
  } );

  add_action( 'rest_api_init', function () {      
    register_rest_route( 'mynamespace/v1', 'latest-post',array(
      'methods'  => 'POST',
      'callback' => 'get_latest_post'
    ) );
  } );

  class My_Rest_Server extends WP_REST_Controller {
    //The namespace and version for the REST SERVER
    var $my_namespace = 'my_rest_server/v';
    var $my_version   = '1';

    public function register_routes() {
      $namespace = $this->my_namespace . $this->my_version;
      $base      = 'product_cat';
      register_rest_route( $namespace, '/' . $base, array(
        array(
            'methods'         => WP_REST_Server::READABLE,
            'callback'        => array( $this, 'get_latest_post' ),
            'permission_callback'   => array( $this, 'get_latest_post_permission' )
          ),
        array(
            'methods'         => WP_REST_Server::CREATABLE,
            'callback'        => array( $this, 'add_post_to_category' ),
            'permission_callback'   => array( $this, 'add_post_to_category_permission' )
          )
      )  );
    }
    public function get_latest_post_permission(){
      if ( ! current_user_can( 'edit_posts' ) ) {
        return new WP_Error( 'rest_forbidden', esc_html__( 'You do not have permissions to view this data.', 'my-text-domain' ), array( 'status' => 401 ) );
      }
      // This approach blocks the endpoint operation. You could alternatively do this by an un-blocking approach, by returning false here and changing the permissions check.
      return true;
    }
  }
?>`
