### ISSUE TITLE
Only include Post data on the response object when declared in schema

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#2416]
This is what our code path looks like currently:

```
setup_postdata( $post );

// Base fields for every post.
$data = array(
    'id'           => $post->ID,
    'date'         => $this->prepare_date_response( $post->post_date_gmt, $post->post_date ),
    'date_gmt'     => $this->prepare_date_response( $post->post_date_gmt ),
    'guid'         => array(
        /** This filter is documented in wp-includes/post-template.php */
        'rendered' => apply_filters( 'get_the_guid', $post->guid ),
        'raw'      => $post->guid,
    ),
    'modified'     => $this->prepare_date_response( $post->post_modified_gmt, $post->post_modified ),
    'modified_gmt' => $this->prepare_date_response( $post->post_modified_gmt ),
    'password'     => $post->post_password,
    'slug'         => $post->post_name,
    'status'       => $post->post_status,
    'type'         => $post->post_type,
    'link'         => get_permalink( $post->ID ),
);

$schema = $this->get_item_schema();

if ( ! empty( $schema['properties']['title'] ) ) {
    $data['title'] = array(
        'raw'      => $post->post_title,
        'rendered' => get_the_title( $post->ID ),
    );
}
```

If I remove `title` as a property from the schema, it's not included in the response. However, if I remove `password` from schema properties, it's still included on the response object.

I'd expect the response object would only have fields declared in the schema, or at least that WP REST API wouldn't blindly add database data to the response if was purposefully removed from the schema.

**Comment by websupporter** [comment]
I wonder about `categories` and `tags`. They are not included in `$schema` and not in the initial `$data`. Shouldn't they be part of the scheme? But I guess, this would make thinks difficult since all taxonomies with `"show_in_rest" => true` are showing up as a key.

Otherwise, I just thought of something like this:

```
foreach( $data as $key => $property )
    if( ! isset( $schema['properties'][ $key ] ) || empty( $schema['properties'][ $key ] ) )
        unset( $data[ $key ] );
```

**Comment by websupporter** [comment]
sorry, my mistake its included. perfect!

**Comment by danielbachhuber** [comment]
We also need to make sure create / update requests don't process data that's not included in the schema.
