### ISSUE TITLE
Modify Custom Post Type Response

### ISSUE THREAD

**Issue by adibnoh** [WP-API/WP-API#2419]
Hi, is that possible to modify custom post type response. I've already manage to modify response from normal post using **rest_prepare_post** filter , and it turn out great. eg:

```
function my_rest_prepare_post( $data, $post, $request ) {
    $_data = $data->data;

    $category = get_the_category ( $post->ID );
    $_data['category'] = $category[0]->name;

    $data->data = $_data;
    return $data;
}
add_filter( 'rest_prepare_post', 'my_rest_prepare_post', 10, 3 );
```

But it doesn't have any effect with custom post type I created. I've only managed to query custom post type data but it doesn't have any modification like normal post

**Comment by danielbachhuber** [comment]
The filter is dynamic: https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-posts-controller.php#L1187-L1197

If your CPT is `foo`, then the filter is `rest_prepare_foo`.

**Comment by vikash2039** [comment]
Hellow Danielbachhuber.
can you help me further with this .Em still not getting the value as it should be.
