### ISSUE TITLE
Sorry, you are not allowed to create new posts

### ISSUE THREAD

**Issue by robtown** [WP-API/WP-API#2420]
Has anybody successfully created posts from an Ionic app?
I have an ionic app successfully negotiating the first leg of the oauth 1.0a process, but when I try to actually create a post I get an rest_cannot_create error.

Response from service:

> Error creating post! {"data":{"code":"rest_cannot_create","message":"Sorry, you are not allowed to create new posts.","data":{"status":401}},"status":401,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"url":"http://service.com/wp-json/wp/v2/posts","data":{"title":"Foo title","content":"Foo content","status":"publish"},"headers":{"Accept":"application/json, text/plain, _/_","Authorization":"OAuth oauth_consumer_key=\"1fuYx4bx8EOM\", oauth_nonce=\"rGAQfWZwq4cecXlzMdQBiG7cR673I0Lx\", oauth_timestamp=\"1459875496\", oauth_signature_method=\"HMAC-SHA1\", oauth_token=\"bIDQOcdep8jf0jLg6cF1wpHX\", oauth_version=\"1.0\", oauth_signature=\"EPj%2FRCgf%2BlKXnFB9F5q0Vn7Njg8%3D\"","Content-Type":"application/json;charset=utf-8"}},"statusText":"Unauthorized"}

I'm using angular-oauth1-client in ionic.
oauth setup:
`angular.module('oauthModule', [
    'oauth1Client'
])
.config(function(oauth1ClientProvider) {
    oauth1ClientProvider.config({
        consumerKey: '1fuYx4bx8EOM',
        consumerSecret: 'LfOMpIOO8MqySE8RUpUINopGUKHRYe0wbZfk76FNCO9UvW5j',
        requestEndpoint: 'http://wp-test.local.com/oauth1/request',
        authorizeEndpoint: 'http://wp-test.local.com/oauth1/authorize',
        accessEndpoint: 'http://wp-test.local.com/oauth1/access',
        oauthCallback: 'http://wp-test.local.com/oauth1/callback/'
    });
});
`

actual call:
`$scope.doLogin = function() {
    console.log('Doing login', $scope.loginData);
    $scope.test = $scope.oauth1.authorize();
**I get to here just fine. This next call is the where i get a response error:**

```
$scope.test.then(function(authorizedHttp) {
authorizedHttp({
    method: "POST",
    url: "http://wp-test.local.com/wp-json/wp/v2/posts",       
    data: {
       title: "Foo title",
       content: "Foo content",
       status: "publish"
    }
})
.then(function(response) {
    alert(response.message);
}, function(response) {
    alert("Error creating post! " + JSON.stringify(response));
    console.log("Error creating post! " + JSON.stringify(response));
    return false;
});  
```

});

**Comment by danielbachhuber** [comment]
> when I try to actually create a post I get an rest_cannot_create error.

The error itself is because authentication fails, which means you don't have authorization for the action. Once you figure out why your application isn't authentication properly, you'll be able to create posts if your user has the correct capability.

**Comment by robtown** [comment]
You are correct sir... I believe my issue is in the angular-oauth1-client.
I have no issues creating posts from an ionic app with Basic Authentication.
