### ISSUE TITLE
Create comment with attachment at the same request

### ISSUE THREAD

**Issue by aljamzd** [WP-API/WP-API#2421]
Hi,

I want to create comment with one image attachment. i know it is possible to upload image attachment and create comment separately and then assigne attachment to the created comment meta.
but i want to know is there any way to send comment with image file together at the same request?

something like this:

``` javascript
var data = {
    author: 43
    author_email: 'ali.jamalzad@gmail.com'
    author_name: 'Ali Jamalzadeh'
    author_url: ''
    parent: 0
    post: 28100
    content: 'Comment Text...'
    attachment: FILE
}
```

Thank you

**Comment by danielbachhuber** [comment]
> but i want to know is there any way to send comment with image file together at the same request?

There isn't, without writing your own endpoint to do it. See #561 for some of the history on support for this feature.
