### ISSUE TITLE
No stable releases

### ISSUE THREAD

**Issue by maarten00** [WP-API/WP-API#2422]
Hi,

I'm using composer to install my WP plugins. I want to install this plugin, but there does not seem to be a stable release. My composer config will only allow stable releases, and I don't want to change that. 
However, on the readme it clearly states:

> The latest stable version is available from the WordPress Plugin Directory.

Yet all releases (e.g. 2.0 beta13) that have been released on WordPress.org as stable according to the quote above, are marked as 'pre-release' instead of stable. What's up with that?

**Comment by danielbachhuber** [comment]
> Yet all releases (e.g. 2.0 beta13) that have been released on WordPress.org as stable according to the quote above, are marked as 'pre-release' instead of stable. What's up with that?

See https://make.wordpress.org/core/2016/04/04/wp-rest-api-2-0-beta-13-roadmap/

The WordPress.org beta versions are "stable" in the sense that they're a formal release. They're not stable in the semver sense.
