### ISSUE TITLE
Mixed Usage of path formatting when calling rest_url for add_link

### ISSUE THREAD

**Issue by timmyc** [WP-API/WP-API#2424]
We are utilizing the `rest_url` filter for WordPress.com and encountered an issue with our logic, specifically around link results for the users endpoint.

It seems there is varying usage of the `path` param passed to `rest_url()` in the endpoint logic.  In most cases, there is a leading slash used in the path parameter [#](https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-users-controller.php#L547), but in other cases there is not [#](https://github.com/WP-API/WP-API/blob/03d3708d06f6ac9f9a6ff8e2be9af62123fdbc8b/lib/endpoints/class-wp-rest-taxonomies-controller.php#L152).

So in our filter for `rest_url` we have to sniff out if a path has a leading slash or not - not the end of the world, but it might be nice to have a consistent standard in the core endpoints when calling `rest_url()` for links.

**Comment by danielbachhuber** [comment]
Hm, good point. We could've stripped the leading slash in `rest_url()` before the value is passed to the filter, but I think that ship has since sailed.

I'm open to removing it across the board, unless there are serious objections otherwise.

**Comment by BE-Webdesign** [comment]
Yeah getting rid of the leading slash is fine, I would think. Is it worth putting that into a core patch to do ltrim on the filter?

**Comment by danielbachhuber** [comment]
> Is it worth putting that into a core patch to do ltrim on the filter?

I have concerns about backwards compat issues.

**Comment by BE-Webdesign** [comment]
I'll do a PR for it then :smile:

**Comment by danielbachhuber** [comment]
Ok. You could actually write a test for this too by adding a filter that inspects `rest_url` and indicates a failure if the value includes a leading slash. By running the assertion on every use of `rest_url()`, we can ensure leading slashes aren't used in the future.

**Comment by nylen** [comment]
A way to access the namespace and the endpoint path from within `rest_url` would also be nice.  Then the namespace would naturally not have a slash and the endpoint path would.

**Comment by timmyc** [comment]
I'm happy to fix in a PR as well - was going to do so but figured I would report it first.

**Comment by BE-Webdesign** [comment]
So from the test that I'm running it appears trivial as to whether the path has a leading slash or not as `get_rest_url()` is always doing `'/' . ltrim( $path, '/' );` and by the time it gets to the `rest_url` filter it already has a leading slash.  Are you applying `rest_url` filter in custom code? What sort of results are you getting to where you would need to do this check?

**Comment by timmyc** [comment]
@BE-Webdesign yes we have a custom filter where we are now doing `ltrim()`.  And as I stated in the OP, that obviously is a valid functional work-around - but it just seems like something that should/could be standardized in the core endpoints.

Regardless, we will likely keep the `ltrim` in place, it just kind of surprised me to see the differing usage in the core endpoints.

**Comment by BE-Webdesign** [comment]
Okay, makes sense now.  I agree this should totally be standardized.  This should probably be fixed in core too, so people won't run into compatibility issues with plugins that extend the API, but I made a PR that removes the leading slashes.  If you want to help me out with the unit test, it would be greatly appreciated!

**Comment by timmyc** [comment]
@BE-Webdesign I will pull down your branch and give it a spin.  I'm having issues getting the test suite to run locally though :sob:

**Comment by BE-Webdesign** [comment]
Thanks, @danielbachhuber helped out and I think it is fixed.  It is not entirely complete though, so your help is still appreciated!  If you need help with getting the test suite running, let me know, and I may be of assistance.
