### ISSUE TITLE
Can't authenticate using basic authentication

### ISSUE THREAD

**Issue by Shadix36** [WP-API/WP-API#2425]
Hi,

I'm having an issue with basic authentication. 

Trying to send a GET request with Postman (chrome plugin) using the following url:
**http://_MY_WEBSITE_URL_/wp-json/wp/v2/users/3**

The username and the password is filled with the site's admin user credentials.
The error I get: 

```
{
    "code": "rest_user_cannot_view",
    "message": "Sorry, you cannot view this resource.",
    "data": {
        "status": 401
    }
}
```

I tried the basic authentication using wp_remote_request from another website, and with CURL too, but the results are the same every time.  

The user with id 3 exists, I have checked it. If I want to list all of the users, I get only those who have posts created.

I have activated the required plugins: WP REST API, JSON Basic Authentication.
My wordpress version: 4.4.2

**Comment by Shadix36** [comment]
I figured out something, which can help in debugging.  I installed a fresh new wordpress on my localhost, installed only these 2 plugins and it's still not working if I use "localhost" in URL,  BUT if I use my local ip address "127.0.0.1" the authentication works.

**Comment by danielbachhuber** [comment]
Can you try with https://github.com/WP-API/Basic-Auth instead?

**Comment by Shadix36** [comment]
Im using that right now.. it's name in dashboard plugins is: JSON Basic Authentication.

**Comment by manikmagar** [comment]
I use [Application Password](http://v2.wp-api.org/guide/authentication/#application-passwords-or-basic-authentication) . I have created a custom role (eg. API Client) with the only capabilities required (using [User Role Editor](https://wordpress.org/plugins/user-role-editor/), then I created a new user (eg. API Client User) with having this role. Once user is created, I use Application Password to create a new passowrd which I use in Basic Authentication 'API Client User: application password for it'. It works for me, even tested it through Postman tool.

**Comment by Shadix36** [comment]
Finally, I figured out the solution. I had to add some new options manually to my **.htaccess** file, the plugin didn't make it.

The code:

```
# BEGIN WP BASIC Auth
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /PluginTest/
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
</IfModule>
# END WP BASIC Auth
```

**Comment by raphaelnikson** [comment]
This happens because of the check that happens in the get_item_permissions_check function of class class-wp-rest-users-controller.php

There is the user’s post count. If it does not create any post it is not possible to see user details by api ..

**Comment by eddiewebb** [comment]
@georgestephanis is the only author who has created a working auth plugin for the API.  I have tried every apache rewrite change, plugin for basic auth, plugin for oauth and they all get the same "rest_user_cannot_XXXX".

Installed George's plugin (https://github.com/georgestephanis/application-passwords) that displayed a warning, linked to https://github.com/georgestephanis/application-passwords/wiki/Basic-Authorization-Header----Missing and all endpoints immediatrely worked!
