### ISSUE TITLE
Inconsistent type returned for user capabilities.

### ISSUE THREAD

**Issue by johanmynhardt** [WP-API/WP-API#2426]
When a WP user has capabilities and a call is made to `/users/:id?context=edit`, a JSON object/map is returned (`"capabilities": {"a":"foo", "b":"bar"}`).

However, when a user has no capabilities (`- No role for this site -` selected in wp-admin), an empty array is returned (`"capabilities": []`).

**Comment by danielbachhuber** [comment]
Thanks for the report. We should either return an empty object or null when there are no capabilities present.
