### ISSUE TITLE
machine to machine communication

### ISSUE THREAD

**Issue by bdart** [WP-API/WP-API#2427]
I played a bit around with this and some additional plugins but didn't figured out a proper way to realise machine to machine communication. What I want to do is:
- write a post in wordpress and keep the status **private** that it is not displayed in between the other blog entries
- tag it with a category e.g.: **family**
- request from another IP with e.g. a node.js server those posts and get the json data

Everything is quite clear how to build the rest routes to get my information.
## setup:
- server A - wordpress installation
- server B - e.g. node.js installation --> no user interface

**But how can I authenticate the node.js server with my wordpress site without the need of an user interface - just machine to machine?**

**Comment by danielbachhuber** [comment]
> But how can I authenticate the node.js server with my wordpress site without the need of an user interface - just machine to machine?

I'm not sure I follow. You could use [Basic Auth, Application Passwords](http://v2.wp-api.org/guide/authentication/) or oAuth, depending on what authentication methods server A supported. Keep in mind each of those authentication methods will require installing a plugin, as WordPress doesn't support them out of the box.

If this doesn't answer your question, could you clarify your expectations a bit?

**Comment by bdart** [comment]
I have tried Basic Auth and Application Password but this methods didn't return private posts. Either they blocked when I tried `/wp-json/wp/v2/posts?context=view&status=private` with a 401.
For both I have installed the plugins.

As far as I understood the oAuth 1 flow here I need to authorise via an user interface. But due to the fact I just want to communicate between two servers there won't be any user interfaces. Maybe I am on the wrong track but which auth method "should" enable me to get private posts too?

**Comment by danielbachhuber** [comment]
> Either they blocked when I tried /wp-json/wp/v2/posts?context=view&status=private with a 401.

A 401 response means the authentication isn't working at all. Can you verify that you're sending the headers correctly?

**Comment by bdart** [comment]
Sorry my fault it is not 401 it is 400, I just took a look on the message with "forbidden"

```
{
  "code": "rest_invalid_param",
  "message": "Ungültige(r) Parameter: status (Status is forbidden)",
  "data": {
    "status": 400,
    "params": [
      "status (Status is forbidden)"
    ]
  }
}
```

I tried it with postman and the auth type: "Basic Auth". I can validate that username and password are correct. Header is set to: Authorization Basic [encoded string]

**Comment by danielbachhuber** [comment]
This error appears when you try to make the request with Postman? What role does the user have?

**Comment by bdart** [comment]
That's correct I wanted to try it with postman first before coding

The user's role is "Administrator"

**Comment by danielbachhuber** [comment]
> That's correct I wanted to try it with postman first before coding

Ok. The error you're receiving in Postman is ultimately the same problem — your authentication mechanism isn't working for whatever reason. The request you're making in Postman fails because the request isn't properly authentication, which means the request isn't authorized to use the `status` query arg.

**Comment by bdart** [comment]
Hm basic auth plugin disables unauthorised visitors by visiting the blog. I will investigate application password again

---

update1:

I retried all auth methods. Everytime I get the same error msg:

```
{
  "code": "rest_invalid_param",
  "message": "Ungültige(r) Parameter: status (Status is forbidden)",
  "data": {
    "status": 400,
    "params": [
      "status (Status is forbidden)"
    ]
  }
}
```

for:

`[IP]/wp-json/wp/v2/posts?context=view&status=private`

Beside when I install basic auth it locks not registered user out of the system. The other plugins are doing it quite well.

Do you have any further ideas what could be wrong configured? Or is it a problem about the status --> private param?

**Comment by danielbachhuber** [comment]
> Beside when I install basic auth it locks not registered user out of the system.

You should use [this plugin](https://github.com/WP-API/Basic-Auth) instead.

> Do you have any further ideas what could be wrong configured? 

No, sorry. You can `GET /wp-json/wp/v2/users/me` to see which user you're authenticated as. Can you verify the request is authenticated?
