### ISSUE TITLE
everything 404s

### ISSUE THREAD

**Issue by MonkRocker** [WP-API/WP-API#2430]
I'm not sure this is the correct place, but I can't find anywhere else to post.

I installed the plugin for my site, it's activated, and I set Permalinks to Post Name.

Fired up Postman and sent a GET to http://<my-site>/wp-json/wp/v2/posts

And I get a 404.  Tried other endpoints mentioned in the docs, with the same result - 404.  I'm not super familiar with WP, but in case it matters, I don't see a wp-json directory in my WP root directory. Is there a step I am missing?

Thanks.

**Comment by danielbachhuber** [comment]
> I installed the plugin for my site, it's activated, and I set Permalinks to Post Name.

Just to confirm, your post permalinks work as expected? And, if you're running Apache, the .htaccess file was generated properly?

> And I get a 404. Tried other endpoints mentioned in the docs, with the same result - 404.

Can you share the full response you're receiving?

> I'm not super familiar with WP, but in case it matters, I don't see a wp-json directory in my WP root directory. Is there a step I am missing?

No — you don't need to create a wp-json folder.

**Comment by MonkRocker** [comment]
Permalinks were NOT working, good catch.  So I got those working, and when I use the rest console, I see endpoints listed.  

But they all respond like so:

`GET
/wp/v2/posts
404 – Not Found
"code": "rest_no_route"
"message": "No route was found matching the URL and request method"
"data":
"status": 404`

I see someone else was having this same problem, and upgrading to the latest version fixed it.

I am on 2.0-beta13

**Comment by danielbachhuber** [comment]
Are you sure the plugin is active? Do you have the v1 plugin activated, by chance?

**Comment by danielbachhuber** [comment]
Are you sure the plugin is active? Do you have the v1 plugin activated, by chance?

**Comment by MonkRocker** [comment]
New development:

If I try the full REST url in a browser, it works.  i.e.:

http://[site]/wp-json/wp/v2/posts

It does not work from the console.  The WP REST API Console seems to think the base url includes /wp-admin/ so it's trying to hit http://[site]/wp-admin/wp-json/wp/v2/posts

Not a huge deal since I can use Postman.

So I guess unless there's an easy fix for that, we can close this issue.

Thanks heaps!
