### ISSUE TITLE
Restrict CRUD operations to authenticated users only

### ISSUE THREAD

**Issue by MurhafSousli** [WP-API/WP-API#2432]
Hi,
I would like to restrict CRUD operations to authenticated users only, I don't want anonymous users to access the site's contents, is this possible with WP-API?

Thank you

**Comment by danielbachhuber** [comment]
> I don't want anonymous users to access the site's contents, is this possible with WP-API?

Yes, see this code snippet: https://gist.github.com/danielbachhuber/8f92af4c6a8db784771c

**Comment by MurhafSousli** [comment]
Thank you

**Comment by MurhafSousli** [comment]
I'm always getting the following code on Postman extension

```
{
  "code": "restx_logged_out",
  "message": "Sorry, you must be logged in to make a request.",
  "data": {
    "status": 401
  }
}
```

Is this because I'm accessing the RESTful service outside wordpress?

if so what can be an alternative solution?

**Comment by BE-Webdesign** [comment]
> Is this because I'm accessing the RESTful service outside wordpress?

Yes, you need to authenticate.
