### ISSUE TITLE
Get tags for 'attachment' post_type

### ISSUE THREAD

**Issue by GuillaumeNachury** [WP-API/WP-API#2433]
Hi,
I'm using the _Media Tags_ plugin so I can set tags to files I upload from the admin and I'm using the REST api to retrieve the files.

When I query the API to grab the files I (obviously) don't have the tag associated to an attachment.
The tags are a new taxonomy called 'media-tag' so I'm wondering how I can add these to the query result.

The logic would be : Query all posts with post_type = 'attachment' and for each post grab the 'media-tags' associated. 

Any advice on how to implement this ?

Thx.

**Comment by danielbachhuber** [comment]
You can register the `media-tag` taxonomy with `show_in_rest=>true` to have it accessible through the REST API: http://v2.wp-api.org/extending/custom-content-types/#registering-a-custom-taxonomy-with-rest-api-support
