### ISSUE TITLE
Filter order/orderby doesn't work

### ISSUE THREAD

**Issue by arielweinberger** [WP-API/WP-API#2434]
Hello.
I am trying to grab posts and order them by date, in a descending order.

I tried:
`http://url.com/json/wp-json/wp/v2/posts?filter[order]=DESC`
`http://url.com/json/wp-json/wp/v2/posts?order=desc`

Neither of them work.

But this, for example, works fine:
`http://url.com/json/wp-json/wp/v2/posts?filter[cat]=3`

Any idea?

**Comment by websupporter** [comment]
I just tried it myself on a quite empty install (just two posts, no other plugins...) and it was running fine. So my first (maybe stupid) thought was just: any other plugins, which might interfere with the WP_Query the API is using?

**Comment by arielweinberger** [comment]
Hello.
I just figured out that everything is fine from WP-API's side.
The problem was unrelated, caused by JS promise anti patterns.

You are free to close this :).
