### ISSUE TITLE
support for WPML?

### ISSUE THREAD

**Issue by englishandy** [WP-API/WP-API#2437]
hi, i'm pulling the english no problem with json, but my site has WPML (french) but i dont see any french posts receieved from the API.
Is support in place for this? The french is located in a FR directorty as per WPML structure.

**Comment by BE-Webdesign** [comment]
> Is support in place for this?

My first guess would be no.  I am unfamiliar with WPML.  Does the french version show up at https://www.mysite.com/FR/ or how are the permalinks structured?  If you can tack on /wp-json/ to the domain that gives french information, see if it will access the posts in french. If not a plugin could definitely be written to do so.

**Comment by englishandy** [comment]
thank you very much for your reply.Yes the french is structureed with mysite.com/fr, i tried adding the /wp-json and unfortunatly that was not working. :(

Date: Thu, 14 Apr 2016 12:20:21 -0700
