### ISSUE TITLE
Exclude post from custom post type and custom taxonomie (category)

### ISSUE THREAD

**Issue by fobar21** [WP-API/WP-API#2444]
Please help me,

its possible exclude post from some categories in custom post type: like:

wp-json/wp/v2/my_cpt?filter[my_category__not_in]=4

**Comment by BE-Webdesign** [comment]
As long as you are using built in taxonomies (categories, tags) the answer is yes.  If you need custom taxonomies the answer is currently no but should be changed in the future.  Here is what the request would look like for category on a custom post type.  wp-json/wp/v2/my_cpt?filter[category__not_in][]=4.
