### ISSUE TITLE
Is it possible to create a new site on a multisites network with the API ?

### ISSUE THREAD

**Issue by Fab1en** [WP-API/WP-API#2446]
I was wondering if WP REST API was compatible with a multisites network, I haven't seen any documentation about this. Specifically, is it possible to request the creation of a new site in the network using the API ?

Thanks

**Comment by danielbachhuber** [comment]
> Specifically, is it possible to request the creation of a new site in the network using the API ?

It's not, no. That feature will eventually be handled in https://github.com/WP-API/wp-api-site-endpoints

**Comment by Fab1en** [comment]
Thanks @danielbachhuber for your answer. Is it possible to get involved in implementing this feature plugin ? I have a real world use case that I would like to work on.

**Comment by BE-Webdesign** [comment]
@Fab1en you can hop over to https://github.com/WP-API/wp-api-site-endpoints and start doing PRs.  One caveat is that the repo seems a bit inactive, but don't let that dissuade you.
