### ISSUE TITLE
<source> tag within <video> is lost on response

### ISSUE THREAD

**Issue by jmchauv** [WP-API/WP-API#2447]
Whenever Wordpress receives my content, I lose the entire <source> tag within my <video> tag. Should I be formatting HTML content differently when sending to Wordpress?

An example of how my [content] value looks before setting up curl post
`$qParams['content']='<video height="1440" width="1920"><source src="http://virpublisher.info/wp-content/uploads/2016/04/GOPR0241.mp4" type="video/mp4" /></video>';`

Curl post to WP
`$ch = curl_init();
        curl_setopt($ch,CURLOPT_URL,$postUrl);
        curl_setopt($ch,CURLOPT_POST, 1);
        curl_setopt($ch,CURLOPT_POSTFIELDS,http_build_query($qParams));
        curl_setopt($ch,CURLOPT_RETURNTRANSFER, true);
        $resp = curl_exec($ch);
        curl_close ($ch);`

**Comment by BE-Webdesign** [comment]
Can you post your response for the request?

**Comment by jmchauv** [comment]
Sure. You can see below within "content" where there is no `<source>` tag. I even tried traditional markup such as `<source></source>` and it still disappeared. But whenever I removed `<source>` and replaced it with a simple test like `<p>test</p>`, `<div></div>`, or `<em>test</em>`, they all remained intact.

`{"id":473,"date":"2016-04-15T20:06:30","date_gmt":null,"guid":{"rendered":"http:\/\/virpublisher.info\/2016\/04\/15\/offroad-biking\/","raw":"http:\/\/virpublisher.info\/2016\/04\/15\/offroad-biking\/"},"modified":"2016-04-15T20:06:30","modified_gmt":"2016-04-15T20:06:30","password":"","slug":"offroad-biking","status":"publish","type":"post","link":"http:\/\/virpublisher.info\/2016\/04\/15\/offroad-biking\/","title":{"raw":"Offroad Biking","rendered":"Offroad Biking"},"content":{"raw":"<p>\n<video controls=\"controls\" height=\"1440\" id=\"248\" poster=\"\" width=\"1920\"><br \/>\n<br \/>\nYour browser doesn&#039;t support the video tag<\/video>\n<\/p>\n","rendered":"<p>\n<video controls=\"controls\" height=\"1440\" id=\"248\" poster=\"\" width=\"1920\"><\/p>\n<p>Your browser doesn&#039;t support the video tag<\/video><\/p>\n"},"excerpt":{"raw":"","rendered":"<p>Your browser doesn&#039;t support the video tag<\/p>\n"},"author":1,"featured_media":0,"comment_status":"closed","ping_status":"open","sticky":false,"format":"standard","categories":[1],"tags":[],"_links":{"self":[{"href":"http:\/\/virpublisher.info\/wp-json\/wp\/v2\/posts\/473"}],"collection":[{"href":"http:\/\/virpublisher.info\/wp-json\/wp\/v2\/posts"}],"about":[{"href":"http:\/\/virpublisher.info\/wp-json\/wp\/v2\/types\/post"}],"author":[{"embeddable":true,"href":"http:\/\/virpublisher.info\/wp-json\/wp\/v2\/users\/1"}],"replies":[{"embeddable":true,"href":"http:\/\/virpublisher.info\/wp-json\/wp\/v2\/comments?post=473"}],"version-history":[{"href":"http:\/\/virpublisher.info\/wp-json\/wp\/v2\/posts\/473\/revisions"}],"https:\/\/api.w.org\/attachment":[{"href":"http:\/\/virpublisher.info\/wp-json\/wp\/v2\/media?parent=473"}],"https:\/\/api.w.org\/term":[{"taxonomy":"category","embeddable":true,"href":"http:\/\/virpublisher.info\/wp-json\/wp\/v2\/categories?post=473"},{"taxonomy":"post_tag","embeddable":true,"href":"http:\/\/virpublisher.info\/wp-json\/wp\/v2\/tags?post=473"}]}}`

**Comment by BE-Webdesign** [comment]
It's possible that `wp_kses()` is stripping out the `<source>` tag.  Not sure why it wouldn't do the same for `<video>` as well.  You can post these as `[video]` shortcodes.  But I can definitely understand that could not be what you want to accomplish.  If `wp_kses()` is the culprit, you would need to extend the allowed html to meet your requirements.

**Comment by BE-Webdesign** [comment]
Well I looked at your website and it doesn't have `<!DOCTYPE html>` declaration at the top so it makes sense that this would be your output.  Most likely it does not have to do with what I said above.

**Comment by jmchauv** [comment]
Thank you for your response I will look into this.

**Comment by BE-Webdesign** [comment]
Currently your theme is making a XHTML 1.0 Strict declaration:

`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">`

Video tag was introduced in HTML 5 so you will need to make `<!DOCTYPE html>` declaration instead.

**Comment by BE-Webdesign** [comment]
Going to double check this myself and make sure something wonky isn't going on though.

**Comment by BE-Webdesign** [comment]
Doesn't have to do with doctype declaration actually. Has to do with `wp_kses()`. Going to close again as I doubt there will be any changes to the API around this although, I do agree it is strange.  If you put `<source>` tag into WP it would get stripped and the API needs to mirror that functionality.

This should do the trick in your theme's functions.php or somewhere else relevant.  This doesn't do anything for the post excerpt though.

``` php
add_filter( 'wp_kses_allowed_html', 'prefix_add_source_tag', 10, 2 );

function prefix_add_source_tag( $tags, $context ) {
    if ( 'post' === $context ) {
        $tags['source'] = array(
            'src'  => true,
            'type' => true,
        );
    }
    return $tags;
}
```
