### ISSUE TITLE
CPU usage with beta 13

### ISSUE THREAD

**Issue by alaa-alsalehi** [WP-API/WP-API#2448]
Hi,
I upgrade to beta 13 after that mysql consumes my server CPU I stopped the api and MySQL back to normal
I use these routes
posts/id/comments?_embed
posts/id
v1/posts?filter[post_status]=publish&page=pageNo&filter[posts_per_page]=PostsPerPage&filter[order]=desc&filter[orderby]= orderBy&filter[category_name]=CategorySlug

my wordpress is 4.5
anyway I tried to back to the previous beta from git but posts/id route has some different
please help me

**Comment by danielbachhuber** [comment]
@ServeMe Were you able to figure this out?

**Comment by alaa-alsalehi** [comment]
I monitor my server when I activate the plugin mysql activity goes up
if I deactivated after while it goes down
