### ISSUE TITLE
Change (Delete/Add) Category of a Post

### ISSUE THREAD

**Issue by Mojo90** [WP-API/WP-API#2449]
I am currently still on version 1 of WP REST API (cause there were some problems with V2 Beta).
Is it possible to change the category of a post? I didn't find any hints in the docs ([http://wp-api.org/index-deprecated.html#posts_edit-a-post](url)) and on the web.

I have 2 or more categories for one post and I want to delete a specific category or add another one. Would be great if I can achieve this somehow.

**Comment by danielbachhuber** [comment]
> I have 2 or more categories for one post and I want to delete a specific category or add another one. Would be great if I can achieve this somehow.

You can include `categories=[1,2]` as an argument for `POST /wp-json/v2/posts/1` to change the categories on a post.

See http://v2.wp-api.org/reference/posts/
