### ISSUE TITLE
WP REST API doesn't pass any body parameters when using PUT

### ISSUE THREAD

**Issue by saasen** [WP-API/WP-API#2451]
Hi.

I'm struggling trying to get body parameters from the request object passed to an action. In this case, this is `update_item` as seen below.

```
register_rest_route( $this->namespace, '/' . $this->rest_base . '/(?P<id>[\d]+)', array(
        array (
            'permission_callback' => array( $this, 'is_user_logged_in') ,
            'methods'   => WP_REST_Server::READABLE,
            'callback'  => array( $this, 'get_item' )
        ),
        array (
            'methods'   => 'PUT',
            'callback'  => array( $this, 'update_item' )
        )
    ) );


public function update_item( $request ) {
    $email = $request->get_param('email');
}
```

The request is as following:

```
PUT https://dev.rest.no/wp-json/rest-api/v1/profile/110647 HTTP/1.1
Host: dev.rest.no
Connection: keep-alive
Content-Length: 23
Cache-Control: no-cache
Origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
Postman-Token: 2f5758a0-983e-cf6c-8043-e646a6ba362a
Accept: */*
Accept-Encoding: gzip, deflate, sdch
Accept-Language: nb,en-US;q=0.8,en;q=0.6,ru;q=0.4,no;q=0.2
Cookie: PHPSESSID=p0f9qm510v77a3v4m1gi2vl482

email=email%40email.com
```

However, when I'm trying to read the `email` body parameter, it's always empty.

Am I doing something wrong here or are the parameters being swallowed by the `WP_REST_Controller` somewhere? It works with POST, but not PUT.

I've tried this with `-beta12` and `-beta13`.

**Comment by rachelbaker** [comment]
@saasen Try `$request['email']`

**Comment by saasen** [comment]
This didn't work. Even when setting the `validate_callback` for the argument, it doesn't work:

```
register_rest_route( $this->namespace, '/' . $this->rest_base . '/(?P<id>[\d]+)', array(
    array(
        'methods' => 'PUT',
        'callback' => array( $this, 'update_item' ),
        'args' => array(
            'email' => array(
                'validate_callback' => function($param, $request, $key) {
                    return filter_var($param, FILTER_VALIDATE_EMAIL);
                }
            )
        )
    ),
    // Code emitted for readability.
)
```

It seems like when using 'PUT', no parameters are passed. Only query string parameters. I need the body parameters. I'm sticking around for 'POST' for now, but 'PUT' would be best in my case, since I'm updating an entity.

I've also tried with other parameter keys than 'email'. This also doesn't work.

**Comment by BE-Webdesign** [comment]
I can't duplicate this problem at all; PUT works perfectly fine for me.  Can you post your response headers and response body?  It is possible that your server does not support PUT and using WP_REST_Server::EDITABLE as your methods may be a more suitable choice.

**Comment by saasen** [comment]
I didn't want to use `WP_REST_Server::EDITABLE` as I don't want to support `POST` and `PATCH`. That's why I used `PUT` directly.

Here's the request headers:

```
PUT https://dev.rest.no/wp-json/rest-api/v1/forgot-username HTTP/1.1
Host: dev.rest.no
Connection: keep-alive
Content-Length: 27
Cache-Control: no-cache
Origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
Postman-Token: d3ed5575-3818-fafe-0de1-888376741437
Accept: */*
Accept-Encoding: gzip, deflate, sdch
Accept-Language: nb,en-US;q=0.8,en;q=0.6,ru;q=0.4,no;q=0.2
Cookie: PHPSESSID=sop6kh907ka8qs3lo9ip08pri6

email=email%40email.no
```

Here's the response headers for that request:

```
HTTP/1.1 400 Bad Request
Date: Thu, 21 Apr 2016 06:24:55 GMT
Server: Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.5.30
X-Powered-By: PHP/5.5.30
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
Access-Control-Allow-Headers: Authorization
Allow: POST, PUT, PATCH
Access-Control-Allow-Origin: 
Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE
Access-Control-Allow-Credentials: true
Content-Length: 119
Connection: close
Content-Type: application/json; charset=UTF-8

{"code":"rest_missing_callback_param","message":"Missing parameter(s): email","data":{"status":400,"params":["email"]}}
```

And my controller:

```
<?php

class Custom_REST_Forgot_Username_Controller extends WP_REST_Controller {

    public function __construct() {
        $this->namespace = "rest-api/v1";
        $this->rest_base = "forgot-username";
    }

    public function register_routes() {
        register_rest_route( $this->namespace, '/' . $this->rest_base, array(
            'methods'   => WP_REST_Server::EDITABLE,
            'callback'  => array( $this, 'update_item' ),
            'args'      => array(
                'email'     => array(
                    'validate_callback' => function($parameter, $request, $key) {
                        return filter_var($parameter, FILTER_VALIDATE_EMAIL);
                    },
                    'required'          => true
                ) 
            )
        ) );
    }

    public function update_item( $request ) {

        // For inspecting all parameters.
        var_dump($request->get_params());

        return array();
    }
}
```

This is running on Apache on my local machine on Windows 10.using XAMPP. Apache can limit HTTP verbs, but is not returning av 405 status code when using `PUT`,

**Comment by BE-Webdesign** [comment]
Yes, with those response headers you wouldn't get a 405.  Pretty strange.  How are you passing the request, CURL, Postman, or another client? My guess would be that whatever client you are using is stripping out the body params or somehow it is not sending them.  I have tested your setup on both nginx and Apache and the email body param always showed up over a PUT request.  I used curl and ARC to send the request; both worked as they should.

**Comment by saasen** [comment]
That may very well be the problem.
I'm using Postman. The body parameters are passed fine when using `POST`, as I've said before. I guess there's a bug when using `PUT`. I should begin using CURL instead of Postman I guess. I'll try with CURL and get back to you.

**Comment by saasen** [comment]
It seems like something is terribly wrong here. I don't get it. I did the following commands:

## Request number 1

### Request:

`curl -k -X PUT -d email=email@email.no https://dev.rest.no/wp-json/rest-api/v1/forgot-username`

### Response:

`{"code":"rest_missing_callback_param","message":"Missing parameter(s): email","data":{"status":400,"params":["email"]}}`

## Request number 2

### Request:

`curl -k -X PUT -H "Content-Type: application/json" -d '{"email":"email@email.no"}' https://dev.rest.no/wp-json/rest-api/v1/forgot-username`

### Response:

`{"code":"rest_missing_callback_param","message":"Missing parameter(s): email","data":{"status":400,"params":["email"]}}`

I'm not an expert with CURL, but it seems correct. What kind of CURL requests did you do, @BE-Webdesign?

**Comment by BE-Webdesign** [comment]
And doing a POST request works perfectly fine?

**Comment by saasen** [comment]
I did a quick `curl -k -X POST -d email=email@email.no https://dev.rest.no/wp-json/rest-api/v1/forgot-username` and of course changed the endpoint to `WP_REST_Server::CREATABLE` and it works fine. No problems there.

Could it really be my server setup? I double checked the `httpd.conf` on my local Apache server. There's no limitations enabled on the different HTTP verbs.

**Comment by BE-Webdesign** [comment]
I honestly have no idea, but my intuition would lead me to say yes.  However, with the response headers you have I don't understand why that would be the case. Try passing with --data-raw instead of -d and see what happens.

**Comment by saasen** [comment]
Thanks for helping me so far, @BE-Webdesign. Same problem occured.

Could it be that I'm initializing the whole plugin wrong? Currently, I'm using this to hook into the `rest_api_init`:
`add_action( 'rest_api_init', 'create_initial_winorg_rest_routes' );`

I know it's possible to pass more parameters (like order). It couldn't be this, right?

**Comment by BE-Webdesign** [comment]
> Could it be that I'm initializing the whole plugin wrong? Currently, I'm using this to hook into the rest_api_init

Most likely not because the endpoint is registering fine and working with other methods.  It is most likely a server related issue.

**Comment by rmccue** [comment]
I believe the issue is that PHP isn't receiving the raw data from the upstream server. On PUT requests, we have to parse out URL-encoded parameters ourselves; the same applies to JSON data all the time, so any JSON requests should be failing too if this is the case. (Although PHP handles POST requests specially.)

Specifically: we try using the legacy `$HTTP_RAW_POST_DATA` if it's available, otherwise we use `php://input`.

The issue I'd guess is occurring here is that on older versions of PHP (<5.6), `php://input` can only be read once, then fails on subsequent usage. I suspect you have a plugin or something on your server which is using this before the REST API tries to.

Couple of ways around that:
- If you control the code that is reading from `php://input`, save that data into `$HTTP_RAW_POST_DATA`
- If you don't control this code, you can try using `POST` instead, as well as passing a `_method=PUT` override parameter.

**Comment by saasen** [comment]
OK. That would make more sense. I'm currently running PHP v5.5.30.
Upgrading to PHP v5.6 or higher would probably resolve this issue?

I did a fast search in my code repo and excluding where WordPress itself are reading from `php://input`by `file_get_contents('php://input');`, I have one plugin which reads from it. That's the [WP OAuth Server plugin](https://wordpress.org/plugins/oauth2-provider/). I can't however, disable this plugin as I need it.

If indeed @rmccue is right, then this isn't a bug.

**Comment by rmccue** [comment]
If the OAuth Server plugin is reading from that before the REST API does (and I strongly suspect it will be), then that's the issue. The plugin should store that data into `$HTTP_RAW_POST_DATA` to ensure it's available for the API. Worth filing a bug [on the GitHub page](https://github.com/justingreerbbi/wordpress-oauth-server) if so, as they claim compatibility with the API. :)

**Comment by rmccue** [comment]
And yeah, upgrading to 5.6+ should fix it too if you have the ability to do so.

**Comment by saasen** [comment]
Thanks for the help, to all of you. I guess this isn't a real issue then.
