### ISSUE TITLE
Filter based on custom field and meta_query

### ISSUE THREAD

**Issue by LeMiira** [WP-API/WP-API#2452]
HI,
How can I get posts after start_date (custom field) ?
I can't use date_query because publish date is different than start date.

I think this is what I need, but its for WP REST API V1
http://wordpress.stackexchange.com/questions/169408/wp-json-rest-api-ryan-mccue-how-to-query-posts-with-specific-meta-data-with-a/224147#224147

what about V2?

**Comment by websupporter** [comment]
Well,
as far as I can see, right now it is not possible yet to query for meta fields with the API without some additions. The arguments, which will be passed on to the `WP_Query` are getting sanitized by `prepare_items_query` which gets the allowed query vars from `get_allowed_query_vars`. These query vars are basically the public queriable vars (if this makes sense :D ). `meta_query` is not part of the usual vars, you can type in the URL to receive a result, so it is right now not in the API.

However. There is a filter, \o/ a filter! `rest_query_vars`. So what I've tried was the following:

```
add_filter( 'rest_query_vars', 'test_query_vars' );
    function test_query_vars ( $vars ) {
        $vars[] = 'meta_query';
        return $vars;
    }
```

Now, we could form a URL like this:
`http://local.wordpress.dev/wp-json/wp/v2/posts?filter[meta_query][0][key]=start_date&filter[meta_query][0][value]=2016-01-01`

But I do not know, if there are any other plans right now concerning filter by meta fields.

**Comment by LeMiira** [comment]
ah, great :D my problem was  that  [0]

`http://local.wordpress.dev/wp-json/wp/v2/posts?filter[meta_query][key]=start_date&filter[meta_query][value]=2016-01-01`

this was mine! :D thanks.

but now, I need a way to compare that start_date value with date range that user entered!

*_Goal: *_Show projects that are in startDate and endDate range that entered by user.

is something like this maybe?

`filter[meta_query][0][key]=start_date&filter[meta_query][0][value]=[USER_START_DATE]&filter[meta_query][1][key]=end_date&filter[meta_query][1][key]=[USER_END_DATE]&filter[meta_query][compare]="BETWEEN"`

**Comment by websupporter** [comment]
So the user enters an end_date and a start_date, but the meta_field is the same:

```
filter[meta_query][0][key]=start_date&
filter[meta_query][0][value][0]=2016-01-01&
filter[meta_query][0][value][1]=2016-01-31&
filter[meta_query][0][compare]=BETWEEN&
filter[meta_query][0][type]=DATE
```

(compare [Codex](https://codex.wordpress.org/Class_Reference/WP_Query#Custom_Field_Parameters))

I am not quite sure, why you need a start_date _and_ end_date as meta fields.

**Comment by LeMiira** [comment]
@websupporter  this is exactly what I need :+1: 
Thank you so much!
Cheers.

**Comment by santoshgistto** [comment]
@websupporter i am not able get the date rage filter

**Comment by santoshgistto** [comment]
how to filter the custom post type using Between or >=
Ex:
custom_start_date = “in milliseconds”,
custom_end_date = “in milliseconds”

found int doc :The ‘type’ DATE works with the ‘compare’ value BETWEEN only if the date is stored at the format YYYY-MM-DD and tested with this format.

**Comment by mikylucky** [comment]
I'm following this approach on a CPT but is not returning the meta_query results.

Are you aware of something that could prevent this on CPTs?

I've exposed my CPT in the API v2 adding the  ` 'show_in_rest'        => true` in the CPT registration

Edit: I solved installing the [plugin](https://github.com/WP-API/rest-filter) to reactivate the `filter` argument, but I'm really curious to understand how to execute meta queries with the v2 API

**Comment by LeMiira** [comment]
After upgrade to WP 4.7 this  is not working, and if you install [this rest filter plugin](https://github.com/WP-API/rest-filter) will not work!
Just need to replace line 42 with this:
 **rest_query_vars** rather than **query_vars**

Ref: https://wordpress.org/support/topic/wordpress-4-7-custom-taxonomy-filter-stopped-working/#post-8872131

**Comment by enrico-atzeni** [comment]
thanks a lot @amindiary, this solve my problem with WP 4.7!

**Comment by steffanhalv** [comment]
@amindiary Do you know how to get it work with woocommerce rest api also?

I tried changing line 42 with woocommerce_rest_query_vars, with no luck

**Comment by LeMiira** [comment]
@steffanhalv Sorry , don't know about it.

**Comment by danielgc** [comment]
Thanks so much @amindiary !!! This should be edited there too!

**Comment by tkowalczyk** [comment]
Hi I am not a WordPress developer, but I have to call the API provided by WordPress and fetch data by custom_field. Which file I have to edit from the WordPress and what to add there to be able to do so?
