### ISSUE TITLE
Parent for Forum Custom Post type not working.

### ISSUE THREAD

**Issue by pathardepavan** [WP-API/WP-API#2453]
I have a mobile app.I am able to list the forums. Get all the threads under forum. Now i want to create a thread under a forum. I am able to create now with wp-api.
 I am not able to assign it to a parent forum.

Tried with post_parent and parent_id with no luck.

can any one help ?
Thanks,
Pavan

**Comment by BE-Webdesign** [comment]
Hi Pavan,

Thank you for using the WP REST API.  Did you create a custom endpoint for your forums and threads, or are you using the posts endpoint?  If forums and threads are independent custom post types, I think you would need to create the link between them yourself.  If they are hierarchical objects then you should be able to use `$post->post_parent` and use `menu_order` for ordering.  Check out how the forums and threads post types keep track of parent/child relations and either use `register_rest_field()` or create a custom endpoint to expose that.  You could also use `rest_prepare_{$this->post_type}` filter if you are using the posts endpoint.  Going to close this issue out but we can continue discussion here if you need assistance and clarification.

**Comment by JulianKingman** [comment]
Hi @BE-Webdesign, I'm having the exact same problem. @pathardepavan, were you able to figure this out? I'm currently able to get and post 'topic' post types by adding the 'show_in_rest' attribute to the custom post type. However, while I can set other data fields like title, content, etc..., I can't set post_parent. Any ideas?

**Comment by BE-Webdesign** [comment]
Hi @JulianKingman,

Is the `topic` post type defined as hierarchical?  If it is, you would just use the `parent` field which is a renaming of the `post_parent` property for the API.  If the relations from the `topic` are not stored in `post_parent` then you will need to use `register_rest_field()` to be able to interact with whatever meta information is creating those relationships.

**Comment by JulianKingman** [comment]
I might see what's happening here. I think I mean to make 'reply' posts that have 'topic' parents, but am trying to make 'topic' posts that have 'topic' parents. I'll try it and report back.

**Comment by JulianKingman** [comment]
OK, while that may be true, I still can't set the parent, even on a 'reply'. 

I'm also getting weird memory errors when POST-ing new replies. I can't see why, as the call is the same as the one for topics. Anyway, that's another issue.

I've tried with and without registering the rest field. I'm able to register other fields (like post meta), but I can't seem to set the parent field. Any Would i have to declate the post type as hierarchical somewhere?

**Comment by BE-Webdesign** [comment]
Post types are declared as hierarchical in `register_post_type()`, that registration is what enables the use of the `post_parent` property, which the WP REST API renames to `parent`.  Are you using a specific plugin for the `reply`, and `topic` post types?

**Comment by JulianKingman** [comment]
Yes, bbPress.

It's interesting... bbpress uses the parent_post field to reference the parent topic (for replies) or forum (for topics), but they are listed as not hierarchical. It's actually a bit of a 'catch-22', because if I set it to hierarchical (like this: `$wp_post_types['reply']->hierarchical = true;`), then I can set the field properly, but it doesn't properly navigate to the topics and posts (it adds the forum name to the URL), but if I don't set it to hierarchical, I can't set the post_parent field. Ideas? 

Registering the field as "parent" or "post_parent" just creates a new post meta field.

**Comment by BE-Webdesign** [comment]
I think the best route would be to extend `WP_REST_Posts_Controller` for the post types you want and overwrite the portions that deal with post_parent to fit your use case.

**Comment by JulianKingman** [comment]
Can you give me any hints or resources? I'm not finding how to actually do this.

**Comment by JulianKingman** [comment]
Alternately, I could perhaps set up a custom endpoint instead?

**Comment by JulianKingman** [comment]
I ended up creating a custom endpoint, like this:

``` php
function wpsd_add_reply(WP_REST_Request $data){
   $forum = $data['forum'];
   $topic = $data['topic'];
   $author = $data['author'];
   $title = $data['title'];
   $content = $data['content'];
   $reply_data = bbp_parse_args(array(), array(
    'post_parent'    => $topic, // topic ID
        'post_status'    =>  bbp_get_public_status_id(), //'published',
        'post_type'      => bbp_get_reply_post_type(),
        'post_author'    => bbp_get_current_user_id(),
        'post_password'  => '',
        'post_content'   => $content,
        'post_title'     => $title,
        'menu_order'     => 0,
        'comment_status' => 'closed'
  ), 'insert_reply' );

  $reply_meta = bbp_parse_args( array(), array(
   'author_ip' => bbp_current_author_ip(),
   'forum_id'  => $forum,
   'topic_id'  => $topic,
), 'insert_reply_meta' );
   bbp_insert_reply($reply_data, $reply_meta);
 }
 add_action( 'rest_api_init', function () {
    register_rest_route( 'wpsd/v1', '/new_reply/', array(
        'methods' => 'POST',
        'callback' => 'wpsd_add_reply',
    'permission_callback' => function () {
      //capabilities here: https://codex.bbpress.org/getting-started/before-installing/bbpress-user-roles-and-capabilities/
      // WP capabilities here: https://codex.wordpress.org/Roles_and_Capabilities
            return current_user_can( 'publish_topics' );
        }
    ) );
} );
```
