### ISSUE TITLE
Removing /wp-json/ from routes? 

### ISSUE THREAD

**Issue by simistern** [WP-API/WP-API#2454]
Not sure if this is ill-advised so I thought I would just ask. We'd like to remove /wp-json/ from our routing path names and replace it with something like /api/. How non-trivial would this be? 

I experimented a bit with changing some code in wp-api.js file but everything broke. Is there an easy, non-breaking way to do this?

Is this the (only) code that would need to be changed in this scenario? 

`if ( _.isEmpty( wpApiSettings ) ) {
        wpApiSettings.root = window.location.origin + '/wp-json/';
    }`

**Comment by websupporter** [comment]
```
<?php
    add_filter( 'rest_url_prefix', 'slug_rest_url_prefix' );
    function slug_rest_url_prefix( $old ){
        return 'api';
    }
?>
```

should be fine I guess.

**Comment by danielbachhuber** [comment]
Yes, @websupporter's suggestion works well.

**Comment by simistern** [comment]
Unfortunately I wasn't able to get this to work :/
I tried adding that to my config file but no luck...is there anything
particular I'm doing wrong?

On Wed, Apr 20, 2016 at 11:11 AM, Daniel Bachhuber <notifications@github.com

> wrote:
> 
> Yes, @websupporter https://github.com/websupporter's suggestion works
> well.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/WP-API/WP-API/issues/2454#issuecomment-212469943

## 

Kind Regards,
Simon

**Comment by danielbachhuber** [comment]
Did you flush your rewrite rules?

**Comment by simistern** [comment]
I kept my initial change as well and reset my MAMP dev environment, if
thats what you mean? Are their other specific rules I need to change?

On Wed, Apr 20, 2016 at 2:53 PM, Daniel Bachhuber notifications@github.com
wrote:

> Did you flush your rewrite rules?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/WP-API/WP-API/issues/2454#issuecomment-212556999

## 

Kind Regards,
Simon

**Comment by simistern** [comment]
do you mean the rules in my htaccess file?

On Wed, Apr 20, 2016 at 2:58 PM, Simon Stern simon160@gmail.com wrote:

> I kept my initial change as well and reset my MAMP dev environment, if
> thats what you mean? Are their other specific rules I need to change?
> 
> On Wed, Apr 20, 2016 at 2:53 PM, Daniel Bachhuber <
> notifications@github.com> wrote:
> 
> > Did you flush your rewrite rules?
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/WP-API/WP-API/issues/2454#issuecomment-212556999
> 
> ## 
> 
> Kind Regards,
> Simon

## 

Kind Regards,
Simon

**Comment by websupporter** [comment]
> flush rewrite rules

basically go in the admin to settings > permalinks and click save. this is "flushing rewrite rules" handmade.

> I kept my initial change

If this means "I experimented a bit with changing some code in wp-api.js", do not keep those changes, since this broke everything :) My code works with no need to alter the plugin itself.

Hope this helps.

**Comment by simistern** [comment]
worked perfectly, thank you!

On Wed, Apr 20, 2016 at 3:28 PM, Websupporter notifications@github.com
wrote:

> flush rewrite rules
> basically go in the admin to settings > permalinks and click save. this is
> "flushing rewrite rules" handmade.
> 
> I kept my initial change
> If this means "I experimented a bit with changing some code in wp-api.js",
> do not keep those changes, since this broke everything :) My code works
> with no need to alter the plugin itself.
> 
> Hope this helps.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/WP-API/WP-API/issues/2454#issuecomment-212569466

## 

Kind Regards,
Simon
