### ISSUE TITLE
v1 and v2 working alongside, is it possible? How do I change the endpoint path por v2?

### ISSUE THREAD

**Issue by ivanquirino** [WP-API/WP-API#2456]
I have a site with v1 and v2 installed, but only v1 is working at the moment, I tried to change the url prefix with

`add_filter( 'rest_url_prefix', function() { return 'wp-json-v2'; } );`

but it did not worked.

Also when I deactivate v1, v2 does not work in 'wp-json/wp/v2'.

**Comment by websupporter** [comment]
> Also when I deactivate v1, v2 does not work in 'wp-json/wp/v2'.

Do you still change the rest_url_prefix to `wp-json-v2`

**Comment by websupporter** [comment]
And you may need to reset the rewrite rules

admin > settings > permalinks - click save

**Comment by websupporter** [comment]
From the V1 description in the repository:

> If you activate both v1 and v2 on your website, then v1 will take priority and v2 will be inaccessible.

https://wordpress.org/plugins/json-rest-api/

**Comment by websupporter** [comment]
Sorry for being spammy. I just tried to your code (should have done this in the first place), and it worked for me. But, what you have to do, you have to flush the rewrite rules (my second comment) after you've uploaded your code.

**Comment by ivanquirino** [comment]
thank you!

**Comment by BE-Webdesign** [comment]
@ivanquirino Are you all set now?

**Comment by ivanquirino** [comment]
@BE-Webdesign yes, it is working!

**Comment by ivanquirino** [comment]
thank you
