### ISSUE TITLE
How to auth user via WP-API?

### ISSUE THREAD

**Issue by pyksid** [WP-API/WP-API#2458]
Hello,

I write an function to login a user from his ID via WP-API: 

`public function login(WP_REST_Request $request)
    {
        $user_id = $request->get_param('user_id');

```
    if ($user_id) {
        $user = get_user_by('id', $user_id);

        if ($user) {
            wp_set_current_user($user->ID);
            wp_set_auth_cookie($user->ID, true);

            return new WP_REST_Response(true, 200);
        } else {
            return new WP_Error('user-not-found', 'User not found', ['status' => 500]);
        }
    } else {
        return new WP_Error('user-id-not-found', 'User id not found', ['status' => 500]);
    }
}
```

`

But when I go back to website, user is not logged, no cookies are set :( 

How can I do this ?

Thanks!

**Comment by BE-Webdesign** [comment]
You should read this http://v2.wp-api.org/guide/authentication/ if you are trying to authenticate requests.  Are you trying to have a user logged in by a request sent with user ID?  This would be a really bad idea security wise as anybody could log into anybodies account.

The code would look like this too.

``` php
public function my_rest_login( WP_REST_Request $request ) {
    $user_id = $request->get_param( 'user_id' );

    if ($user_id) {
        $user = get_user_by('id', $user_id);

        if ($user) {
            wp_set_current_user($user->ID, $user->user_login);
            wp_set_auth_cookie($user->ID, true);

            do_action( 'wp_login', $user->user_login );

            return new WP_REST_Response(true, 200);
        } else {
            return new WP_Error('user-not-found', 'User not found', ['status' => 500]);
        }
    } else {
        return new WP_Error('user-id-not-found', 'User id not found', ['status' => 500]);
    }
}
```

Like I said before, it doesn't really make any sense to do this and using authentication for requests through the API makes a lot more sense.  You can use the existing login functionality in WordPress if people are visiting your WordPress site.  If you are creating an app tapping into WordPress then you should have a login system for that app and have authenticated requests sent to the WP REST API.  Let me know if I can clarify any of this.  Going to close the issue but we can continue discussion here.

**Comment by pyksid** [comment]
Thank you for your help.

I'll try to be more specific.

I want to make a bridge between my application and WordPress. When a user logs in to my application, it is also connected to WordPress. I have a hook in my application and I want after the user logs on my application, he is logged to WordPress too. That is why I send the user ID using the authentication WP API, to connect the user to WordPress.

Is it accurate or not? :)

**Comment by BE-Webdesign** [comment]
You want to read this http://v2.wp-api.org/guide/authentication/.  Currently there are a few methods for Authentication, with more to come I am sure.  For an external app you would want to either use some form of [Basic Authentication](https://github.com/WP-API/Basic-Auth) ( App Passwords ) or the [Oauth1.0a plugin](https://github.com/WP-API/OAuth1).  Depending on which one you choose you want one of those plugins activated on the WordPress install that you are accessing.  If you have SSL running, which I definitely recommend, there is an Oauth2 plugin to use, but I have to track that down.

**Comment by BE-Webdesign** [comment]
So for each request you will have your user who is logged into your app making authenticated requests to the API, does that make sense?

**Comment by pyksid** [comment]
```
$response = \Httpful\Request::get(WP_JSON_URL)
            ->authenticateWith('user_login', 'password')
            ->send();
```

If I do something like this, the user will be logged in his browser to WordPress session ? I understand in your link I can authenticate the request to do many things in WordPress code, but I can't see how to do to force my forum member to be logged with specific WP user session :/

**Comment by BE-Webdesign** [comment]
I don't really understand the use case at all but if you need to have a user logged into a WordPress session there would be a lot of variables at play, as far as your server config etc.  If you need help using the API for other purposes I would be glad to help, but from what I understand, what you need assistance with goes well beyond just using the WP REST API.

**Comment by pyksid** [comment]
Okay, thank you for your help :)
