### ISSUE TITLE
Why not include `meta_query` in filter args by default?

### ISSUE THREAD

**Issue by taras** [WP-API/WP-API#2459]
I just spent a bunch of time looking for a solution to this and it turns out that it was 4 lines of code. It'd be so much easier if it just worked by default. I found the solution here https://github.com/WP-API/WP-API/issues/2452

Why does it not provide this functionality by default?

**Comment by websupporter** [comment]
Hi @taras,
when I was working on this solution, my first thought was also "shouldn't this be queriable from the beginning", but now I am opposed to this idea. Currently, more or less, you can filter through the API the publicly queriable vars.
For example, you can already get all posts of a categories by
`http://example.com/?category=1`
You can do this also via the API too.

You can't query meta fields the same way with WordPress. Imagine there is a popular plugin for products and it saves in the custom field `no_of_sales` the numbers of sales for a product. This is no data, you want to necessarily expose. If `meta_query` is a default, it would be exposed in the moment the REST API hits core.

`http://example.com/wp-json/wp/v2/products?filter[meta_query][0][key]=no_of_sales&
filter[meta_query][0][value]=10000&filter[meta_query][0][compare]=%3E&filter[meta_query][0][type]=NUMERIC`

If a developer decides, "I want to expose those data and add `meta_query`", okay, but not as a default.
It would be nice, if there would be a way for the developer to say "I want to expose this meta_key", but I haven't found a solution for this yet. I think, this would be the best approach.

**Comment by websupporter** [comment]
I was playing around a bit. If you do not want to expose all custom fields by this way, you might want to have a look into this workaround:

```
<?php
    add_filter( 'rest_query_vars', 'test_query_vars' );
    function test_query_vars( $vars ){
        $vars[] = 'my_special_key';
        return $vars;
    }

    add_action( 'pre_get_posts', 'test_pre_get_posts' );
    function test_pre_get_posts( $query ){
        $args = $query->get( 'my_special_key' );
        if ( empty( $args ) ) {
            return;
        }

        $args['key'] = 'my_special_key';        
        $current_meta = $query->get( 'meta_query' );
        if ( ! is_array( $current_meta ) ) {
            $current_meta = array();
        }

        $current_meta[] = $args;
        $query->set( 'meta_query', $current_meta );
    }
?>
```

It registers an arbitrary key which can be used for example like this:
`http://example.com/wp-json/wp/v2/posts?filter[my_special_key][value]=3`

It will be passed to the WP_Query and there you can hook into `pre_get_posts` and basically you are free to do whatever you want there with your 'special_key'.

**Comment by taras** [comment]
@websupporter this is helpful. Thank you
