### ISSUE TITLE
Support adding/editing terms via the API

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/WP-API#246]
Currently all of the Taxonomy endpoints are READABLE only (see [class-wp-json-taxonomies](https://github.com/WP-API/WP-API/blob/master/lib/class-wp-json-taxonomies.php#L13-L22)). [WP.com](http://developer.wordpress.com/docs/api/) allows editing/creating terms via their API, and I would assume we'd want to provide Create/Update/Delete support for ours as well.

**Comment by danielbachhuber** [comment]
This is implemented on `develop`
