### ISSUE TITLE
v1 or v2 doesn't work on my site

### ISSUE THREAD

**Issue by davidgaldon** [WP-API/WP-API#2462]
Hi, I've tried to get working this plugin, but neither the v1 nor v2 are working.
If I activate the Version 1.2.5, I get this json with no posts or anything in it:
http://www.motiva.me/wp-json

And if I activate the latest version at the moment (Version 2.0-beta13) the mentioned URL takes me to the home page, nothing different.

I'm using permalinks (post-name), and my Wordpress version is 4.4.2.
Any idea/Has somebody experienced the same?

Thanks a lot in advance!

**Comment by swissspidy** [comment]
Looks like you're currently using v1.

http://www.motiva.me/wp-json/ shows all the available endpoints and http://www.motiva.me/wp-json/posts shows all available posts.

Looks correct to me.

**Comment by davidgaldon** [comment]
Oh, I thought it was empty, since I'm trying to build and app following a tutorial, and the /wp-json looks like this: http://dev.julienrenaux.fr/wp-json  (full of data)

Anyway it seems I will need the v2 for this app. Any idea about the reason the V2.x on my site takes me to the home page, exactly the same like if hadn't use the /wp-json in the url?

Now the Version 2.0-beta13 is activated:
http://www.motiva.me/wp-json

Thanks a lot for your help!

**Comment by BE-Webdesign** [comment]
> Any idea about the reason the V2.x on my site takes me to the home page, exactly the same like if hadn't use the /wp-json in the url?

What kind of rewrites do you have going on try going to settings > permalinks and saving first.

Originally asked about WP version then I looked at your site to see it was 4.4.2

**Comment by davidgaldon** [comment]
4.4.2. Should I update to 4.5? Could this be the reason?

**Comment by BE-Webdesign** [comment]
> 4.4.2. Should I update to 4.5? Could this be the reason?

Nope.  It most likely has to do with rewrites going on. Well you should update, but that wouldn't be the problem.

**Comment by BE-Webdesign** [comment]
Did you also deactivate the v1 plugin?

**Comment by davidgaldon** [comment]
Yes, I did. Other way I read the V1 will still having preference.
And about the rewrite problem... No idea. I didn't change anything to modify the basic configuration in this way.

**Comment by kadamwhite** [comment]
You could try installing the rewrite-rules-inspector plugin, it provides a screen to view your rewrites and to manually flush them (this can be done in code too, but the UI can make it obvious whether such action is necessary)

**Comment by davidgaldon** [comment]
I did it right now, thanks! This is what I got:
^wp-json/?$     index.php?json_route=/                          other
^wp-json/(.*)?      index.php?json_route=/$matches[1]           other

Do you see any problem here?

**Comment by BE-Webdesign** [comment]
> ^wp-json/?$ index.php?json_route=/ other
> ^wp-json/(.*)? index.php?json_route=/$matches[1] other

Those are what they should be I believe.  There are a whole lot more rewrites listed below correct?

**Comment by BE-Webdesign** [comment]
http://www.motiva.me/?rest_route=/ This works so for whatever reason your site is not doing the rewrite.

**Comment by davidgaldon** [comment]
Yes, this is the full list. Weird, I don't know why it's not doing the rewrite.
![rewrite-rules](https://cloud.githubusercontent.com/assets/16944785/14762610/423babec-0944-11e6-99d2-b6f4e5ff3f43.png)

**Comment by davidgaldon** [comment]
I just tested the app with the route you mentioned (http://www.motiva.me/?rest_route=/) and the app is working with it, so i like the solution till I find how to solve the problem of the rewrite rules.
Let me know if you find something obvious or think what could the problem be.
Thank you so much guys for your help. I really appreciate it.

**Comment by BE-Webdesign** [comment]
There could be another rewrite overriding it check through your access logs if you can and that should help out.  I would not recommend using the url that is supposed to be rewritten, I linked it to show the API is working.

**Comment by BE-Webdesign** [comment]
Going to close this but we can continue discussion here if you need assistance.
