### ISSUE TITLE
get_permalink equivalent for WP REST API

### ISSUE THREAD

**Issue by taras** [WP-API/WP-API#2464]
I'm writing a [JSONAPI serializer](https://github.com/EmberSherpa/wp-rest-jsonapi-serializer) for Pods and WP REST API. I'd like to include links information for each document but I can't seem to find any way of generating URLs for REST endpoints. 

How do I do this?

**Comment by rmccue** [comment]
You'll need to generate these links using `rest_url()` and the namespace + route for the specific route you want. For posts, this would be `rest_url( 'wp/v2/posts/42' )`

**Comment by taras** [comment]
It looks to me that something is missing from the API if I have to specify the namespace and the resource name manually. 

Is the namespace always going to remain the same? 

Is there a reliable way to retrieve the resource portion of a URL for a post type? 

In this case, I'm using Pods, so I can go look there but it would be nice if I could just specify the post type and/or ID and have the URL. 

Wouldn't you agree?
