### ISSUE TITLE
Fetching all posts returns empty result

### ISSUE THREAD

**Issue by ad-on-is** [WP-API/WP-API#2465]
When I call:
`http://project.local/wp-json/wp/v2/posts` I don't get the expected result. Instead an empty json-array is returned.

I should have permissions on doing that, because creating a new post works without any problems.
What am I doing wrong?

**Comment by websupporter** [comment]
Just gathering some possible reasons
- Do you have posts published?
- Can you see posts on your home page, when you are not logged in?
- Do you run plugins, which might corrupt the WP_Query (turn on/off)
- Do you have any other remarkable differences to a freshly installed WP instance?

> I should have permissions on doing that

Yes, you should, because actually you do not need permissions for this request.

> because creating a new post works without any problems

Do you have other posts in your installation or just posts, you've created this way (maybe there somewhere an error occured)

**Comment by ad-on-is** [comment]
> Do you have posts published?

Since my wordpress has over 4000 woocommerce products, I didn't think about creating any post entries :D
Thanks a lot.

**Comment by websupporter** [comment]
Yes, this makes sense :)

Did you try 
`http://project.local/wp-json/wp/v2/product/`

**Comment by websupporter** [comment]
If the products do not show up, you might want to filter `woocommerce_register_post_type_product` and add `show_in_rest` 

https://codex.wordpress.org/Function_Reference/register_post_type

**Comment by ad-on-is** [comment]
Currently there's no route for product or products. 
This is because woocommerce is going to implement the wp-api in release 2.6

I was also irritated that `http://project.local/wp-json/wp/v2/media` also delivered an empty array. But this was due to some permissions on the server.

> If the products do not show up, you might want to filter woocommerce_register_post_type_product and add show_in_rest

I don't need the products currently. They are handled by the WC-API right now. 

But thanks anyway ;-)

**Comment by jose-nunez** [comment]
Hey @ad-on-is I'm having the same problem with /wp-json/wp/v2/media. I'm getting an empty array. Posts and pages are being returned OK though.
How can I figure out if my server is also with permission problems?

Thanks

**Comment by ad-on-is** [comment]
Hey @jose-nunez, since this topic is a while back (1,5 years) I really don't remember what the actual permission-problem was. 

Anyways, here are some points you might consider to check:

1. Check whether the permissions of the files themselves are correct and that you can access them via browser like http://example.com/wp-content/uploads/somefile.jpg. If you can't, you might have server-side permission issues with chmod and chown. 

2. If you're using some authentication (like basicauth) to access the api, check if the user has sufficient rights to access the media endpoint.

Cheers,
Adis

**Comment by jose-nunez** [comment]
Hi @ad-on-is. Thanks for your quick answer. I guess this is a problem with WP versions. The problem comes on 4.9, now I'm testing on 4.7 and it does work. I'll keep checking.
