### ISSUE TITLE
Upload an image

### ISSUE THREAD

**Issue by alien315** [WP-API/WP-API#2466]
Hi guys,

We are working on a plugin that imports post / categories and images from another WP site.

We are moving this plug to the WP Rest API and we have succesfully use the API to create post/categories, but after a few days trying to use the API via Cookie Authentication has been imposible for me to figure out how to create/upload images to the site in the admin area using the API.

Do you have any example code for uploads in a scenario like this?

I am not planning you to help me code the solution, but just in case there is no available example I can give you an example of what we have done so far:

```
the_data = {
        'source_url' : 'http://localhost/cecropia/wp/wp-content/uploads/2016/04/test.jpg',
        'link' : 'http://localhost/cecropia/wp/wp-content/uploads/2016/04/test.jpg',
        'slug': "test"+r+"-jpg",
        'title': "test"+r+"-jpg",
        'type': "attachment",
        'media_type': "image",
        'mime_type': "image/jpeg"
};

jQuery.ajax( {
    url: 'http://localhost/cecropia/wp/index.php/wp-json/wp/v2/media/',
    method: 'POST',
    beforeSend: function ( xhr ) {
        xhr.setRequestHeader( 'X-WP-Nonce', wpApiSettings.nonce );
        xhr.setRequestHeader( 'Content-Disposition', 'attachment; filename=test.jpg' );
    },
    data: the_data
} ).done( function ( response ) {
    console.log( response );
} ).fail(function() {
    console.log( "error" );
} );
```

This piece of code creates an empty media entry but we have try a lot of ways to pass the content of the image file with no luck.

Any help would be very much appreciated

**Comment by danielbachhuber** [comment]
@red111 Were you able to work this out? If not, can you share the response you receive? And, just to confirm, you're using the most recent beta?
