### ISSUE TITLE
/wp-json/wp/v2/pages not returning all pages

### ISSUE THREAD

**Issue by aandy28** [WP-API/WP-API#2467]
I am making a call to get all of the pages in my wordpress site (16 pages) but I am not getting all returned. It is only returning 10. All pages are published. Is there a limit on the amount of pages it returns?

**Comment by websupporter** [comment]
10 is the standard amount

You can change this behavior with `?per_page=16` you would get 16. the maximum amount is 100. Or you can use pagination for the first 10 results, the second 10 results and so on.

**Comment by aandy28** [comment]
Thank you, that was my issue!

**Comment by yvanpinto** [comment]
What if I don't want pagination at all? What should I call? (yeah I know... ghostbusters is the first thing that came to my mind!!). ;-)

Thx

**Comment by kadamwhite** [comment]
The best you can do is 100 pages in a response—this upper limit is enforced to prevent a single API request from triggering too much database interaction in one go. But `?per_page=100` ought to get most pages in small to medium-sized sites.

**Comment by davidverhage** [comment]
Anyone have an explanation concerning the max 10 result - I have tried to alter the response to 'by default' return 100 per page - yet the change has not affected the API response one bit.

I am anxious to hear from you fellow developers.
