### ISSUE TITLE
Does WP-REST-API (v2) work with Advanced Custum FIelds?

### ISSUE THREAD

**Issue by arielweinberger** [WP-API/WP-API#2468]
The title says it all :).
Does it require modifications in the WordPress PHP files?

I am basically sending requests from an AngularJS application.

Regards.

**Comment by websupporter** [comment]
Hmmm.. What exactly do you want to do? Search data, expose data...

But I've heared of a plugin:
ACF To REST API
https://wordpress.org/plugins/acf-to-rest-api/

Might help.

**Comment by arielweinberger** [comment]
@websupporter That was super quick.
I guess this is what I was looking for, haha. Basically just accessing custom fields of posts.

Thanks a lot!

**Comment by websupporter** [comment]
See also
https://github.com/WP-API/wp-api-meta-endpoints

But I haven't had a deep look into both of them

**Comment by Jany-M** [comment]
@arielweinberger did you find a good solution and if so, could you share a couple examples?
