### ISSUE TITLE
WP Rest v2 - Interpret shortcode with do_shortcode

### ISSUE THREAD

**Issue by Zboule** [WP-API/WP-API#2469]
Hi,

Have an issue with Rest API v2 and shortcode interpretation.

Problem was describe on [StackOverflow](http://stackoverflow.com/questions/36873682/wp-rest-v2-interpret-shortcode-with-do-shortcode).

Have you some ideas to find a solution ?

Thanks,
Jordane

**Comment by rmccue** [comment]
This appears to be something that the plugin/theme providing the shortcode needs to handle. The "read more" text isn't something that the API will do, so it's likely either part of the same plugin or a different plugin causing that issue.
