### ISSUE TITLE
Cannot create a new post with categories or tags properly assigned

### ISSUE THREAD

**Issue by steven-chau** [WP-API/WP-API#2472]
Hi guys,

I am a user of the WP Json API. First off, thanks for the great work! 

Although I can create a new post via the API with the desired title, content, date, etc.., the newly created post never has the correct categories / tags assigned.

I tried different ways to set them in the JSON data. None of them worked.

I tried:

```
categories = [2],
tags = [3],
...
```

```
categories = ["programming"],
tags = ["php"],
...
```

Did I do something wrong? Or is there a bug in the latest beta version? Thanks!

**Comment by websupporter** [comment]
Can you provide a bit more code? Your second example wouldn't work I think, because the ID is needed. But for the first code example I am not sure.

**Comment by steven-chau** [comment]
@websupporter 

Thanks for looking at this. I found that the API actually worked when I wrote a shell script to illustrate the potential issue. It was my wrong client code that caused the issue.

Anyway, here's the shell script just in case anybody is interested:

```
#!/bin/bash

read -r -d '' jsonPayload << _EOM_
  {
    "title": "Want to set category to 6",
    "content": "Keeping my fingers crossed",
    "categories": [6],
    "status": "publish"
  }
_EOM_

curl -X POST \
     -H "Authorization: Basic Xyzxyzxyzxyzxyzxyz"  \
     -H "Content-Type: application/json" \
     -d "$jsonPayload"   \
     http://www.mywebsite.com/wp-json/wp/v2/posts
```
