### ISSUE TITLE
Client Libraries for retrofit 2 (Android)

### ISSUE THREAD

**Issue by rahulrajeevan** [WP-API/WP-API#2473]
Is there an option to generate client library (Retrofit 2 or volley)using swagger or any other tool . Or do you provide any any client library

**Comment by danielbachhuber** [comment]
Not at this time.

**Comment by rahulrajeevan** [comment]
@danielbachhuber Is there any plan to consider this later

**Comment by danielbachhuber** [comment]
We may end up supporting Swagger through some intermediate middleware. There are no plans for an Android client library at this time.

**Comment by rahulrajeevan** [comment]
Thanks for your time and support .
