### ISSUE TITLE
Cannot create new posts with content containing an iframe

### ISSUE THREAD

**Issue by steven-chau** [WP-API/WP-API#2475]
Hi guys,

I am a user of the v2 WP Json API.

I have been using the POST `/wp-json/wp/v2/posts` API to create posts with some degree of success.

I want to embed a Youtube video in the content. So, I specify the corresponding `<iframe>` in the content in the POST request. However, the blog post created will have everything in the content except the `<iframe>`. That is to say, the embedded video is gone!

If you run the following script and then look at the content of the blog post created, you will see what I mean.

Can someone tell me how I can embed an `iframe` in a blog post? Thanks!

```
#!/bin/bash

read -r -d '' jsonPayload << _EOM_
  {
    "title": "Want to include an iframe in content",
    "content": "<p>first paragraph</p> <iframe>hello world</iframe>",
    "status": "publish"
  }
_EOM_

curl -X POST \
     -H "Authorization: Basic Xyzxyzxyzxyzxyzxyz"  \
     -H "Content-Type: application/json" \
     -d "$jsonPayload"   \
     http://www.mywebsite.com/wp-json/wp/v2/posts
```

**Comment by BE-Webdesign** [comment]
I believe the iframe tag is being stripped by `wp_kses()`.  You would need to make iframe be an acceptable tag for the blog post.  You want to use the `wp_kses_allowed_html` filter with a post context.  I know it might seem strange, but this is part of how WordPress sanitizes input for post content.  Going to close this issue but we can continue discussion here.

**Comment by steven-chau** [comment]
@BE-Webdesign

Thanks very much for your prompt reply.

Strangely enough, I just created a post on my blog manually with the following content using the web interface of wordpress (i.e. not using the WP Json API). And all the html tags went through intact.

Content:

```
<p>First paragraph</p>
<iframe> testing iframe only </iframe>
```

I am not very familiar with the codebase of WP-API. But is the following code segment related to the stripping of the html tags?
https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-posts-controller.php#L736-L742

I also tried to search for a testcase / an example illustrating the use of `wp_kses_allowed_html` filter in a WP POST request but I didn't find any.

Could you shed some more light on how I can create a post with the above content with a WP API call? Thanks very much!!

**Comment by BE-Webdesign** [comment]
@steven-chau 

Thank you for using the REST API.  The following code should go in a plugin or you can put it in your themes' functions files.

add_filter( 'wp_kses_allowed_html', 'prefix_add_source_tag', 10, 2 );

``` php
function prefix_add_source_tag( $tags, $context ) {
    if ( 'post' === $context ) {
        $tags['iframe'] = array(
            'src'    => true,
            'srcdoc' => true,
            'width'  => true,
            'height' => true,
        );
    }
    return $tags;
}
```

You can add in more attributes as you need.  If this doesn't fix the problem then something else is happening.  Let me know.
