### ISSUE TITLE
Taxonomies Endpoint only returning 10 results

### ISSUE THREAD

**Issue by jglovak** [WP-API/WP-API#2481]
I have custom taxonomy endpoint that is only returning 10 results even though there are currently 54 entries. Is there a parameter to adjust this limit that I'm simply not seeing? I couldn't find anything regarding a limit for taxonomies, only on posts, pages, etc in the documentation.

**Comment by danielbachhuber** [comment]
See the `per_page` argument: http://v2.wp-api.org/reference/tags/

**Comment by jglovak** [comment]
Thank you very much, for anyone else that is looking, this is what got it working.

`Your Site Url/wp-json/wp/v2/Your Taxonomy?per_page=100`

It appears 100 is the max that you can pass into this tag, anything over that returns this error.

`{"code":"rest_invalid_param","message":"Invalid parameter(s): per_page (per_page must be between 1 (inclusive) and 100 (inclusive))","data":{"status":400,"params":["per_page (per_page must be between 1 (inclusive) and 100 (inclusive))"]}}`

**Comment by danielbachhuber** [comment]
> It appears 100 is the max that you can pass into this tag, anything over that returns this error.

Correct.
