### ISSUE TITLE
/statuses/ returns object

### ISSUE THREAD

**Issue by websupporter** [WP-API/WP-API#2482]
Hi,
is there a reason, why `wp/v2/statuses/` returns an object of all statuses and not an array?

**Comment by danielbachhuber** [comment]
Yes — to make it easier to access an individual status object, because you can simply use its key instead of having to find it within an array.

**Comment by websupporter** [comment]
Makes sense.
Just wanted to use it to create a `<select>` and wanted to easily loop through the array.

Use

```
for( var status in statuses ){
  console.log( statuses[ status ].name );
}
```

instead. Was just wondering.

Thanks @danielbachhuber

**Comment by danielbachhuber** [comment]
👍 

I've been finding [Underscore](http://underscorejs.org/) quite helpful in my JS work — you might too. It has a number of transformation functions I use frequently (e.g. `_.each()` and `_.find()` ).
