### ISSUE TITLE
Can't get profile picture url

### ISSUE THREAD

**Issue by mapodev** [WP-API/WP-API#2483]
Is it possible to get a profile picture URL instead of the Avatar URL?

**Comment by websupporter** [comment]
One option would be to extend the response object. So, if we assume, the URL is saved in a custom meta field with the key `profile_pic_url`, you could do something like this:

```
<?php
add_action( 'rest_api_init', 'slug_register_profile_pic' );
function slug_register_profile_pic() {
    register_rest_field( 'user',
        'profile_pic',
        array(
            'get_callback'    => 'slug_get_profile_pic',
            'update_callback' => null,
            'schema'          => null,
        )
    );
}
function slug_get_profile_pic( $object, $field_name, $request ) {
    return get_user_meta( $object[ 'id' ], 'profile_pic_url', true );
}
?>
```

More information on this here: http://v2.wp-api.org/extending/modifying/

**Comment by mapodev** [comment]
Added your code to plugin.php, it does now appear in the user array, but the value is empty. Can you check this?

**Comment by websupporter** [comment]
Well, I do not have a `profile_pic_url`. I quickly created one to check and it appears. Did you check, if you are using the right meta_key?

**Comment by mapodev** [comment]
It is `basic_user_avatar` on my pc. Thanks, it worked.

**Comment by AlbertGuadan** [comment]
here is another reference if help [ https://github.com/WP-API/WP-API/pull/2271 ]
having to do with Avatar.
get options Area , [https://github.com/WP-API/WP-API/pull/2271/files#r52693542]
