### ISSUE TITLE
Disable access from external domain or client

### ISSUE THREAD

**Issue by colloquet** [WP-API/WP-API#2488]
Hi all,

I would like to know how I can disable access to the API from external domain or client?

Basically I only want to allow my own site to access the API.

I saw this post [https://github.com/WP-API/WP-API/issues/144](url) and I have tried:

`add_filter( 'allowed_http_origins', '__return_false' );`

and 

`add_filter( 'allowed_http_origin', '__return_false' );`

But no luck yet.

Thanks in advance!

**Comment by danielbachhuber** [comment]
@colloquet Were you able to work this out? If not, can you provide a bit more detail into what you're trying to do?

**Comment by rachelbaker** [comment]
Closing this, as it is not a bug report and has gone without reporter feedback for over 30 days.  Support is best addressed in the WordPress.org Support Forums (https://wordpress.org/support/) or the WordPress Stack Exchange (http://wordpress.stackexchange.com/).
