### ISSUE TITLE
WP-API v2 500 (Internal Server Error)

### ISSUE THREAD

**Issue by bobsilon** [WP-API/WP-API#2489]
Hi there.
I developed a basic WordPress theme based on WP-API. It was working fine without any error on wamp localhost. Recently I moved the theme on a global server and there, when I directly request a post, **sometimes** it load the request properly and **sometimes** it gives error of `500 (Internal Server Error)`. The URL used for request is like this:
`myhost.com/blog/70/some-post/`

I'm using AngularJS and have new and modified endpoints in this theme. Deactivating this modifications also not helped. Any idea?

**Comment by bobsilon** [comment]
I just tested the theme in another server and unexpectedly there are not any `500 Internal Server Error`. So I think the reason of that error on first server could be server configurations but I actually don't know what is it. I put here both environments details that maybe should help:
- Both WordPress versions are 4.5.2
- Rest API v2.0-beta13
- 1st server (which throws 500 error):
  - php v5.5.35
  - Server API    CGI/FastCGI
- 2nd server:
  - php v5.6.18
  - Server API    LiteSpeed V6.8

**Comment by danielbachhuber** [comment]
> sometimes it gives error of 500 (Internal Server Error).

Do you have access to the PHP error log, and can you see what the actual error is there?

Or, can you enable `WP_DEBUG` so you get more verbosity when the error occurs?

**Comment by bobsilon** [comment]
No can't access to error log, that was a free host for testing.
But when I activated debug mode it returns this:

``` php
Notice: ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/.../public_html/wp-includes/functions.php on line 3549
```

Where the line 3549 is in a function as below:

``` php
function wp_ob_end_flush_all() {
    $levels = ob_get_level();
    for ($i=0; $i<$levels; $i++)
        ob_end_flush(); // ==> line 3549
}
```

**Comment by OriginalEXE** [comment]
Are you getting the error above when the server returns 500, or you just found that in the logs of this new server that is not experiencing the original issue from your ticket?

**Comment by rachelbaker** [comment]
Closing this, as it is a support question which is best addressed in the WordPress.org Support Forums (https://wordpress.org/support/) or the WordPress Stack Exchange (http://wordpress.stackexchange.com/).
