### ISSUE TITLE
Raw JSON Input via POST

### ISSUE THREAD

**Issue by raptor235** [WP-API/WP-API#2490]
Is RAW JSON in body support via post? 

I'm trying to register a new POST endpoint and pass along raw json in body but I can't seem to get at it at the other end... how do I configure the end point to accept raw json...
I see the data in the request object under request->body... full json is there but it seems to be locked down... and using $request->get_body_params() just returns a empty array... json is valid

My code is as follows

register_rest_route($namespace, '/summary/', array(
            'methods' => WP_REST_Server::CREATABLE,
            // 'WP_REST_Server::CREATABLE | WP_REST_Server::ACCEPT_JSON'
            'callback' => array(&$this, 'log_summary'),
        ));

I see V1 used to support ACCEPT_JSON not sure if this is supported in v2?

I can see my data but I can't access the $request->body variable directly while processing the response

![image](https://cloud.githubusercontent.com/assets/313825/15185601/eb68b3be-1767-11e6-9ab1-a0fa03cff286.png)

**Comment by rmccue** [comment]
`ACCEPT_JSON` is no longer required in v2. You can use `$request->get_body()` to retrieve the body, or `$request->get_json_params()` to retrieve the already-parsed parameters.
