### ISSUE TITLE
wp-rest api V 1.2.5 not work with wordpress 4.5.2

### ISSUE THREAD

**Issue by ju4nr3v0l** [WP-API/WP-API#2491]
Hi, first i want to congrats to all of you for the great job developing such a great tool like the wp-rest api. Well this team develop a web site with the wp-rest api v 1.2.5 on wordpress 4.4.3 but when we update wordpress to 4.5.2 the rest api does not respond. ¿can you tell me please if this issue will be fixed? in negative response can you tell me please how i fix this on my web site?

thank you so much and i apologize for my bad english.

**Comment by mnelson4** [comment]
So when you send a request to the index page (/wp-json) what do you see? Does it look like the wp API v1 index or the wp API v2 index (the v2 index has an entry for "namespaces", that's how I tell the difference at least).

**Comment by ju4nr3v0l** [comment]
apears 404 not found

**Comment by mnelson4** [comment]
have you tried refreshing permalinks? (ie, go to the WP dashboard/admin, then settings, then permalinks, and re-save)

**Comment by ju4nr3v0l** [comment]
yes, i did that, and also i install a previus version of wordpress and works but when update wordpres again fails, even re-updating permalinks structure.

**Comment by yadavji83** [comment]
It was not working at my localhost also, but i found that the problem was with permalink, check if your posts or pages are showing with permalink setting to anything other than **Plain**

**Comment by ju4nr3v0l** [comment]
no, there's not plain permalinks, all links are with this structure siteurl/$post-name%/

**Comment by mnelson4** [comment]
I'd suggest starting to add vardump etc to `WP_REST_Server::__construct` etc to see if the WP API is getting initialized or called etc. Maybe also use a plugin to inspect the rewrite rules.

**Comment by gonfer** [comment]
I debugged a lot and I changed the following in the file wp-content/plugins/WP-API/plugin.php

**inside json_api_loaded:**

`if ( empty( $GLOBALS['wp']->query_vars['json_route'] ) )
        return;`

to

`$route = 'json_route';
    if ( empty( $GLOBALS['wp']->query_vars['json_route'] ) ){
        if(empty( $GLOBALS['wp']->query_vars['rest_route'] )){
            return;
        }else{
            $route = 'rest_route';
        }
    }`

and

`$wp_json_server->serve_request( $GLOBALS['wp']->query_vars['json_route'] );`

to

`$wp_json_server->serve_request( $GLOBALS['wp']->query_vars[$route] );`

Also I changed all the hooks:
template_redirect to rest_api_init

and seems that is working
