### ISSUE TITLE
Status 200 vs 201

### ISSUE THREAD

**Issue by starfishmod** [WP-API/WP-API#2494]
Currently when items are created it sends back a 201.
(see $response->set_status( 201 ); in create_item)

Is there a strong reason for this to occur? The reason I ask is I'm working on a Swagger generator (https://github.com/starfishmod/WPAPI-SwaggerGenerator) and I was incorrectly listing successful responses as 200 as per most other API's I'm working with. This broke my Swagger library as it kept thinking the response was not listed in the spec.

I would like to list these as 201 (if the need to be 201) but there is no way currently looking at the endpoints to determine which calls are going to use what status.

So can we either change all the 201 to 200 
Or...
Make it so I can read the endpoint information and see the status?

I _could_ programatically say all POST calls to a url not ending in an an id is a response 201 - but that means that anyone else who comes along and writes a 3rd party API plugin has to follow these conventions and I would be in the same situation.

**Comment by danielbachhuber** [comment]
> Is there a strong reason for this to occur?

Yes. 201 [means](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) "Created", which is more precise than "OK"

> I would like to list these as 201 (if the need to be 201) but there is no way currently looking at the endpoints to determine which calls are going to use what status.

This is a good point. I don't know _if_ we can programmatically expose these, but it's worth discussion.

> I could programatically say all POST calls to a url not ending in an an id is a response 201 - but that means that anyone else who comes along and writes a 3rd party API plugin has to follow these conventions and I would be in the same situation.

It might be time for us to publish these conventions somewhere, as the pattern itself is meant to be common.

**Comment by starfishmod** [comment]
Ok so 201 is created as far as the w3 protocol spec, but I would argue that it isn't a common or even used in the wider public space. Does the WP admin panel for example return a 201 status if I add a post?

All other API's I have worked with use 200 as a success regardless of the trigger (Create, get etc) and I'm unaware of any API that returns a 201 like this. Do you know of any other API's that use this convention?

However if 201 is going to be used as the status then yes it will need to be documented (I looked but didn't see this anywhere). However that means we have to rely of third party following this convention... which I have serious doubts that people will remember to put this in. If it must be done this way then is it possible to auto set this and not rely on the 3rd party to do this?

I'm not having a go, just challenging the reasoning :)

**Comment by danielbachhuber** [comment]
> but I would argue that it isn't a common or even used in the wider public space.

Can you point to some examples?

> Does the WP admin panel for example return a 201 status if I add a post?

No, but I don't think that's a relevant example.

> All other API's I have worked with use 200 as a success regardless of the trigger (Create, get etc) and I'm unaware of any API that returns a 201 like this. Do you know of any other API's that use this convention?

Github API does: https://developer.github.com/v3/gists/#create-a-gist

**Comment by joehoyle** [comment]
In my opinion it's pretty clear we should be using 201, as that's what it's specifically for. In my experience it's not unusual to see a 201, and in cases of verifying a successful response, I've always checked for 2xx.

**Comment by BE-Webdesign** [comment]
I also agree that it should be 201.  As far as programmatically exposing potential status codes for each endpoint in documentation, I will get something going for docs-v2 and have it display underneath the example requests.

> However that means we have to rely of third party following this convention... which I have serious doubts that people will remember to put this in.

It would be good for more people to become acquainted with HTTP spec.  Having a more specific response code I think ultimately outweighs using previous conventions.

**Comment by starfishmod** [comment]
Ok fair enough 201 it is :) 
So what is the final rule? All POST/PUT/PATCH without an id return 201
Does that mean that DELETE request return 204?

**Comment by BE-Webdesign** [comment]
> So what is the final rule? All POST/PUT/PATCH without an id return 201

Any successfully created resource returns a 201, doesn't have to do with method.

> Does that mean that DELETE request return 204?

That means No Content and I believe on most delete requests the resource that was deleted (or flagged for deletion, i.e. trashing) is returned in the response.

**Comment by starfishmod** [comment]
So how do I tell what the expected successful status is going to be on an API call?
In the Swagger generator I need to know what the expected status is... Since I can't read it from the endpoint I have to determine it somehow... So i'm looking for a consistent rule that I can put into the spec generator. I would have thought that a GET is not going to create content? or am I misunderstanding this? 
Looking at various API style guides (hence why I relented on the 200 vs 201 :) ) such as https://codeplanet.io/principles-good-restful-api-design/ and the Atlassian one, 201 is only on PUT/PATCH/POST where a resource is created.... 
But say a POST which is an update returns a 200.

My bad on DELETE I thought it didn't return the deleted contents. The docs were unclear on this.

**Comment by BE-Webdesign** [comment]
> All POST/PUT/PATCH without an id return 201

This would work, but I can't guarantee all endpoints will exactly fit that.

**Comment by starfishmod** [comment]
I suppose I _could_ generate a 200 response and then duplicate a 201 which has the same data... but seems hacky to me. Swagger works off the status to determine the definition of the response. Unfortunately it's individual response description for each status.

```
responses: {
  200: {
    schema: {
      $ref: "#/definitions/post"
    }
  },
  default: {
    schema: {
      $ref: "#/definitions/error"
    }
  }
}
```

becomes

```
responses: {
  200: {
    schema: {
      $ref: "#/definitions/post"
    }
  },
  201: {
    schema: {
      $ref: "#/definitions/post"
    }
  },
  default: {
    schema: {
      $ref: "#/definitions/error"
    }
  }
}
```

**Comment by AlbertGuadan** [comment]
200 code is readable with proper formatting, after a response has been validated from it's,  resource ( time stamps, etc. )
 in your URI, the client - server responds 201. meaning it works

having an error library could be handy

**Comment by rmccue** [comment]
> So how do I tell what the expected successful status is going to be on an API call?

201 if a resource has been created, 200 if a resource has been updated. The API generally is loose with handling the methods; we allow POST or PUT for most things, but you should be using `POST` to create new resources, and `PUT` to update them.

Creating a resource is a `POST` to the collection, updating a resource is a `PUT` to the resource itself. Combining this with the general rule for statuses, a `POST` to a collection (which doesn't typically end with a numeric ID) should return a 201, and a `PUT` to a single resource (which typically ends with a numeric ID) should return a 200.
