### ISSUE TITLE
Include currently authenticated user in API responses?

### ISSUE THREAD

**Issue by mnelson4** [WP-API/WP-API#2496]
If I send a request via the API, how do I know I'm logged in?
For example, on https://github.com/WP-API/Basic-Auth/issues/1 it was revealed that some servers REMOVE the "authorization" header from the request. So if I send a request to "wp-json/v2/posts" and sent authorization data in the Authorization header (using basic auth, or application passwords plugin) but the server REMOVES the Authorization header, then the server doesn't know the request even attempted to authenticate. The server just sees a normal request with NO authentication data, so it assumes its just a request for public data.

Eg maybe I want to see all posts, and my draft posts, via the API. I send a request to wp-json/v2/posts, and use the password I generated via Application Password plugin in the "Authorization" header. But the server I send the request to is on CGI and so the "Authorization" header gets removed before the PHP code gets to handle it. So the response only includes published posts, NOT my user's draft posts.
My API client isn't told authentication failed, and it doesn't tell me it's removed draft posts from the response. For all I know, someone's deleted my draft posts! It would be nice to at least let the API client know that they're only seeing public data, and that they're not seeing data restricted to the specific user they tried to authenticate as.

It seems to me that it would be good if the API returned the currently-authenticated user's name in a header. This way API clients can easily confirm they're authenticated and who they're logged in as. (The WordPress.com API allows you to query for /users/me, which can achieve the same thing but requires another request and gets a ton of other information that isn't as critical at the moment).

Note: I'm talking about when authentication fails because authentication information is removed from the request in transit, NOT because of incorrect credentials. If a user provides incorrect credentials the WP API currently provide a nice error message pointing that out. But if the authentication data gets removed from the request in transit then there's no way for the server to know it got removed, and there's no way for the API client to know they're getting public data only.

**Comment by danielbachhuber** [comment]
@mnelson4 Given this affects the REST API infrastructure already in core, can you [open a core Trac ticket](https://core.trac.wordpress.org/) for this conversation?

I chatted with @rmccue briefly about this in person. While we like the idea somewhat, we're not sure how it should be implemented. When you open a core Trac ticket, it would be great if you could to a bit of research to see if there's any prior art we could follow.

**Comment by mnelson4** [comment]
ya good points; I'll try to make a core ticket

**Comment by mnelson4** [comment]
after looking around for a bit, I couldn't really find any "prior art" where the current username gets passed back in API responses (there's JSON Web Tokens that is A WAY to do that, but I don't know of any implementations of that, besides this https://en-ca.wordpress.org/plugins/jwt-authentication-for-wp-rest-api/, and I'm not sure if that's passing around user data or what).
It seems most APIs just provide a way to explicitly request the current user (like WordPress.com's /users/me as mentioned above). Plus I noticed the WP API v2 has a "/users/me" route too, which would do just the same thing. (The only inconvenience is that it's not part of core, so our plugin, for example, can't rely on it)

So I guess I'm retracting my suggestion. We can probably just stick with the route "/users/me" (and if our plugin, for example, needs anything not yet in WP core, we'll just build a custom solution until "/users/me" becomes part of WP core).
