### ISSUE TITLE
require authentication to all

### ISSUE THREAD

**Issue by tgaff2x** [WP-API/WP-API#2497]
I'm setting up a "private" site for a client whereby user must be authenticated to access content.

Is there a recommended approach to require authentication all end points? 

For example, attempting to access GET /wp/v2/pages without auth would return the 401/sorry type message

**Comment by danielbachhuber** [comment]
> Is there a recommended approach to require authentication all end points?

You'll just need to intercept all requests with something like this: https://gist.github.com/danielbachhuber/8f92af4c6a8db784771c
