### ISSUE TITLE
Notice: get_currentuserinfo is deprecated since version 4.5! Use wp_get_current_user() instead. in /wp-includes/functions.php on line 3658

### ISSUE THREAD

**Issue by MichaelCropper** [WP-API/WP-API#2498]
Looks like a bug in the WP API? Get the following error when debugging is turned on;

Notice: get_currentuserinfo is deprecated since version 4.5! Use wp_get_current_user() instead. in wp-includes/functions.php on line 3658

**Comment by BE-Webdesign** [comment]
Thank you for using the WP REST API!

Are you using the latest version of the plugin?  I can't find a call to `get_currentuserinfo()` anywhere in the plugin.  Are you sure the API is causing the deprecated notice and not something else?

**Comment by rmccue** [comment]
Make sure you're also using the latest version of the OAuth plugin, as previous versions had this error.
