### ISSUE TITLE
Filtering multiple custom fields with WP REST API 2

### ISSUE THREAD

**Issue by sohrabtaee** [WP-API/WP-API#2499]
I want to filter posts based on multiple acf custom fields with AND relation. Something like this:

`$args = array(
        'post_type'  => 'product',
        'meta_query' => array(
            'relation' => 'AND',
            array(
                'key'     => 'color',
                'value'   => 'blue',
                'compare' => '=',
            ),
            array(
                'key'     => 'price',
                'value'   => array( 20, 100 ),
                'type'    => 'numeric',
                'compare' => 'BETWEEN',
            ),
        ),
    );`
I might even have more filters. How can I convert these to REST API 2 filters?

**Comment by colloquet** [comment]
Hi sohrabtaee,

Have you tried something like this?

``` javascript
var args = {
    'filter[post_type]': 'product',
    'filter[meta_query][relation]': 'AND',
    'filter[meta_query][0][key]': 'color',
    'filter[meta_query][0][value]': 'blue',
    'filter[meta_query][0][compare]': '=',
    'filter[meta_query][1][key]': 'price',
    'filter[meta_query][1][value][0]': '20',
    'filter[meta_query][1][value][1]': '100',
    'filter[meta_query][1][type]': 'numeric',
    'filter[meta_query][1][compare]': 'BETWEEN'
  }
```

I believe you can also just take out `'filter[post_type]': 'product'` and change url to `/wp-json/wp/v2/product` instead.

Cheers.

Edit: You may not be able to get posts by meta field by default,  see [https://1fix.io/blog/2015/07/20/query-vars-wp-api/](url) on how to work around it, however bear in mind that they disabled it for security reasons.

**Comment by websupporter** [comment]
Related:
https://github.com/WP-API/WP-API/issues/2459
https://github.com/WP-API/WP-API/issues/2452
https://github.com/WP-API/WP-API/issues/1425

**Comment by mellinger** [comment]
@colloquet Your example works great over here provided you include...

```
add_filter( 'rest_query_vars', 'include_meta_queries' );

function include_meta_queries($vars) {
    $vars[] = 'meta_query';
    return $vars;
}
```

Example with JS:

```
                    filter: {
                        post_type: 'post',
                        meta_query: {
                            relation:"OR",
                            0: {
                                key: "hide_from_homepage",
                                value: "1",
                                compare: "!="
                            },
                            1: {
                                key: "hide_from_homepage",
                                value: "1",
                                compare: "NOT EXISTS"
                            }
                        }
                    }

```

**Comment by nicolaelitvac** [comment]
@mellinger I'd like to update your version, hope this will help someone.

```PHP
add_filter( 'rest_{your_custom_post}_query', 'include_meta_queries', 10, 2 );

function include_meta_queries($vars, $request) {
        $meta_query = json_decode($request['meta_query'], true);
        $vars['meta_query'] = $meta_query;

        return $vars;
}
```
Then in JS add this parameters to your request
```Javascript
meta_query: {
  relation: 'OR',
  0: {
    key: 'hide_from_homepage',
    value: '1',
    compare: '!='
  }
}
```
