### ISSUE TITLE
Filter params not working?

### ISSUE THREAD

**Issue by lapidus** [WP-API/WP-API#250]
I am trying to filter /posts with for example ?filter[offset]=2 but nothing seems to happen. Is this the right syntax?

**Comment by imjared** [comment]
Just got so hung up on this. `filter[page]=number` does NOT seem to work nor does `paged` or anything else. 

Simply passing `?page=3` saved me.

`/wp-json/posts?filter[order]=DESC&filter[posts_per_page]=2&page=3`. Seems like there are several issues that point to this functionality as confusing so hopefully the documentation improves over time. In the meantime, hopefully some poor soul unlike me finds this issue through the Google.

**Comment by tomconroy** [comment]
Thank you @imjared ! :raised_hands:

**Comment by jcutrell** [comment]
Question on this thread - I'm wondering if support was ever added for allowing a specific offset, rather than simply using the page param? My page starts with 2 items, and I would like to load in 6 when the user clicks a button. Doing so requires an offset, or some strange workarounds.

**Comment by pbrisson** [comment]
+1 jcutrell question! I'm in the same situation. Support for the offset variable should be properly implemented.

**Comment by pbrisson** [comment]
@jcutrell You need to be [authenticated](http://wp-api.org/guides/authentication.html) to use offset, as stated in [WP API documentation](http://wp-api.org/#posts_retrieve-posts):

> In addition, the following are available when authenticated as a user with edit_posts:
> * offset
