### ISSUE TITLE
PHP file_get_contents() returns 403 error

### ISSUE THREAD

**Issue by bobsilon** [WP-API/WP-API#2502]
Hi there,
I tried to get a post details in `wp-json/wp/v2/posts/1` using PHP `file_get_contents()` but it returns this error:
![403 error](https://cloud.githubusercontent.com/assets/2111724/15315468/075d1032-1c2d-11e6-9069-89ccdb8a75be.jpg)
I also tried it with `cURL` and the result was the same:

``` php
object(stdClass)[71]
  public 'code' => string 'rest_forbidden' (length=14)
  public 'message' => string 'You don't have permission to do this.' (length=37)
  public 'data' => 
    object(stdClass)[70]
      public 'status' => int 403
```

But when I try this in `wp-json/wp/v2/` url that returns what I expected. Am I doing wrong?

**Comment by danielbachhuber** [comment]
@bobsilon Did you get this worked out?

**Comment by bobsilon** [comment]
not yet, actually using WordPress's functions to retrieve post details.

**Comment by rmccue** [comment]
Using `file_get_contents` sends a full HTTP request, but does not include either your cookies or the nonce to authorise the request.

If you simply want to get the data for internal usage, you can use the API internally like so:

``` php
$request = new WP_REST_Request( 'GET', 'wp/v2/posts/1' );
$response = rest_get_server()->dispatch( $request );
```
