### ISSUE TITLE
How to fetch YOAST SEO plugin data using WP REST API plugin ?

### ISSUE THREAD

**Issue by sumit0049** [WP-API/WP-API#2503]
I'm using WP REST API to fetch all the post data. Well, it works perfectly, but the major concern for any website is the SEO part. I'm using YOAST SEO plugin. I want to fetch all the Meta tags it creates in the Head section of HTML.

FYI im using WordPress as Backend and Nodejs in frontend.

**Comment by BE-Webdesign** [comment]
You will want to [create your own endpoint](http://v2.wp-api.org/extending/adding/) that retrieves the data you need.  The WP REST API's default endpoints will only cover resources that are a part of WordPress core.
