### ISSUE TITLE
Get site index/meta without routes.

### ISSUE THREAD

**Issue by fahrradflucht** [WP-API/WP-API#2504]
Currently the only way to retrieve the sites meta table (name, description, url, ...) is to fetch `/wp-json/` which is with around 35kb even in a setup without any additional routes pretty heavy for that information in my opinion. Thats certainly because of the `routes` object it contains.

Because of that I think it would be great to either have an argument to `/wp-json/` which omits the `routes` object or have an extra route for that let's say `/wp-json/v2/meta/`.

What do you think? Am I missing something?

**Comment by BE-Webdesign** [comment]
I believe you might be looking for [the sites endpoint](https://github.com/WP-API/wp-api-site-endpoints).  This is still in development, but a basic GET request will display the sites meta information.  If you are interested, it would be great if you can contribute to that endpoint!  If I am misunderstanding what you are asking for, let me know.

**Comment by fahrradflucht** [comment]
Yes you are right that is about what I was looking for, thanks.
