### ISSUE TITLE
Can't get JSON using search, just get []

### ISSUE THREAD

**Issue by DCCopeland** [WP-API/WP-API#2505]
Hi 

I can get JSON using the API and a post ID as below:

http://oxfordwords.staging.wpengine.com/wp-json/wp/v2/posts/38426
http://blog.oxforddictionaries.com/wp-json/wp/v2/posts/38426

But I can't seem to get any using Search

http://blog.oxforddictionaries.com/wp-json/wp/v2/posts?search=word 

Any ideas?

Search works on our test blog
http://wp.magicalbytes.co.uk/wp-json/wp/v2/posts?search=word

And I can get JSON when searching for nothing http://blog.oxforddictionaries.com/wp-json/wp/v2/posts?search=

**Comment by nitishn** [comment]
Are you doing anything to alter the search query for http://blog.oxforddictionaries.com/wp-json/wp/v2/posts/38426? Any hooks or filters? Plugins altering search perhaps?

It looks like your oxford.staging search works just fine.
http://oxfordwords.staging.wpengine.com/wp-json/wp/v2/posts?search=shakespeare

**Comment by DCCopeland** [comment]
Hi nitishn, the problem turned out to be a clash with the Relevanssi search plugin, must be disabled on the staging blog.

**Comment by lippoliv** [comment]
Why got this Topic closed? There's no solution! In case "there is", but "Disable your Search-Engine" is a bad solution. "Hey Admin, my PC has a Problem", "Then shut it down"...?

I'am too facing this Problem, like others do a lot: https://wordpress.org/support/topic/clash-with-wp-rest-api-plugin/

Can you both big plugins may talk together to figure out what the hell is going on? I will start Debugging now, to figure out how I can work around that Problem. But an real "fix" here would be nice <3

WP API is really nice. Relevanssi is really nice. Both plugins are widely known and used. They should not Crash each other.

**Comment by lippoliv** [comment]
28 minutes later and I'am done. Registered my own route. The callback function has 3 Lines of Code (could be reduced to one if you like).

WP API go ahead, talk to Relevanssi, find a solution. Really it should be simple.

**Comment by Kenshino** [comment]
@lippoliv WP API is an API now currently merged into Core.

It isn't really a plugin anymore

Other plugins should find a way to adhere to core.

**Comment by borie88** [comment]
@lippoliv, care to share your 28 minutes of code with others? =D
