### ISSUE TITLE
cache browser with plugin

### ISSUE THREAD

**Issue by ntnhan90** [WP-API/WP-API#2506]
I use plugin WP REST API v2 . Because cache broswer, xxx/wp-json/wp/v2/posts/ don’t update realtime when i publish or update a post. Help me to solve this problem? Thanks

**Comment by rmccue** [comment]
You can add a useless query parameter that the server doesn't recognise with a timestamp, which the browser will treat as a different URL. (This is how jQuery busts the cache, e.g.)

For example, `/wp-json/wp/v2/posts?_=1466501383`
