### ISSUE TITLE
new post always as outstanding

### ISSUE THREAD

**Issue by pelayopc** [WP-API/WP-API#2508]
When i publish a new post, it always publish as outstanding, how can i change this?
thx a lot

**Comment by danielbachhuber** [comment]
> When i publish a new post, it always publish as outstanding, how can i change this?

I'm sorry, but I'm not sure I follow. Can you clarify what you mean by "publish as outstanding", and what you're expecting instead?

**Comment by pelayopc** [comment]
Fixed in the index, if i have only one, fixed, it is always in the index before the other normal posts
I want to publish normal, not fixed (outstanding, important, ..)

**Comment by danielbachhuber** [comment]
> Fixed in the index, if i have only one, fixed, it is always in the index before the other normal posts

Can you share the request you're making? From this description, it sounds like the post you're creating is being marked as a sticky post.

**Comment by pelayopc** [comment]
I send "sticky" : "false", is it the problem?

2016-05-23 14:30 GMT+02:00 Daniel Bachhuber notifications@github.com:

**Comment by danielbachhuber** [comment]
> I send "sticky" : "false", is it the problem?

Yes. `"sticky": "false"` means that the string argument `"false"` is interpreted as `true`.

**Comment by pelayopc** [comment]
What must i do? "sticky" : false ?

**Comment by pelayopc** [comment]
ok, with "siticky" : "0" it works

**Comment by rmccue** [comment]
An actual `false` JSON value is the correct value, just not the string `"false"`.
