### ISSUE TITLE
There's any way to filter the GET /posts request?

### ISSUE THREAD

**Issue by joanlopez** [WP-API/WP-API#2509]
Hi mates,

I'm building a personal Wordpress. It will be accessible from a typical url: blog.example.org.

In my case, i'm using the WP-API because I wanna show a random post from my blog on another site: example.org.

So, my question is:

There is any way to get only the ids of the available (published) posts?

Of course, I could retrieve all the posts with a simply GET /posts call, but this option implies a lot of unnecessary data because it returns all the data from all the posts while I only need one post, and apart from the performance, it could be critical for mobile devices without a wifi connection.

Also another nasty solution is to have a hardcoded array on my frontend, pick one randomly and make the GET /posts/id request only for the chosen one. I'm not sure which option is worst, because this implies that I have to update my frontend on each post publication..

If there's not implemented solution yet. Are you open to my contribution for this task? Or I should make my own plugin?

Many thanks!

**Comment by danielbachhuber** [comment]
> There is any way to get only the ids of the available (published) posts?

There isn't, no.

At some point in the future, we may include a flag to include or exclude specific fields: https://github.com/WP-API/WP-API/issues/572

> If there's not implemented solution yet. Are you open to my contribution for this task? Or I should make my own plugin?

You'd be best writing your own plugin for this, at this point.
