### ISSUE TITLE
Create a comment for posts using POST/wp/v2/comments 

### ISSUE THREAD

**Issue by KaiP-598** [WP-API/WP-API#2510]
Hello,

Currently, my website is using the default COMMENT function provided by wordpress, now I am trying to create comments to posts using swift2. Then I have looked at the documentation of WP REST API V2 and found that I can use POST /wp/v2/comments to create comments, but I do not know how to use this method.
 Can anyone please provide me a real life example of using this method in general or in swift2?

Thanks!

**Comment by BE-Webdesign** [comment]
Hi @KaiP-598, thank you for using the WP REST API!

To create a comment for an existing post, you would make a POST request like this.

`POST domain.here/wp-json/wp/v2/comments?post=1&content=newComment`

This will add a comment to the post with an ID of 1.  As far as Swift, a very basic comment creation request would look like this.  Haven't tested, so there may be errors. The following is not good code. It serves as a basic idea.

```
        // Define Endpoint URL.
        let endpointUrl = "http://swiftdeveloperblog.com/my-http-get-example-script/"

        // Add two parameters.
        let urlWithParams = endpointUrl + "?post=1&content=Hello"

        // Create NSURL object.
        let myUrl = NSURL(string:urlWithParams);
        // Create URL Request.
        let request = NSMutableURLRequest(URL:myUrl!);

        // Set request HTTP method to POST for creation.
        request.HTTPMethod = "POST"

        // For Auth purposes something like this in tandem with the basic Auth plugin should be fine.
        /*
        let username = "myUserName"
        let password = "myPassword"
        let loginString = NSString(format: "%@:%@", username, password)
        let loginData: NSData = loginString.dataUsingEncoding(NSUTF8StringEncoding)!
        let base64LoginString = loginData.base64EncodedStringWithOptions(NSDataBase64EncodingOptions())
        let authValue = "Basic " + base64LoginString
        request.setValue(authValue, forHTTPHeaderField: "Authorization")
        */

        // Excute HTTP Request.
        let task = NSURLSession.sharedSession().dataTaskWithRequest(request) {
            // Request handling here.
        }
```

**Comment by KaiP-598** [comment]
Hello, @BE-Webdesign 
Thank you so much for your reply,  I will certainly try it when I get home tonight.
One more question, the v2 documentation for creating a comment requires arguments like author, author_email, author_url...etc. 
Does the request need to include all the arguments OR we can just pick some arguments, because I searched about this, some people said we can leave some arguments empty.

**Comment by BE-Webdesign** [comment]
You can leave author parameters empty.  If a user is authenticated on the request and the author_\* parameters are left empty, then the authenticated user attributes will be applied to the comment.  There are many arguments for all of the endpoints that can be left empty and if they are required, you will get a 400 response if they are not specified.

**Comment by KaiP-598** [comment]
@BE-Webdesign 
Hi,
thanks so much, I tried your code and it worked good!
I have one more question, if I have a comment meta with meta key: mobile    (I want users to enter their mobile numbers)
how would I create a comment with such meta key, I tried   myurl?post=1&mobile=123456 and it does not work.

Thanks!!

**Comment by BE-Webdesign** [comment]
I don't believe we have comment meta in place but you can help out here on the meta endpoint https://github.com/WP-API/wp-api-meta-endpoints!

> I tried your code and it worked good!

Remember that it is just a brief example and is not production code quality.

**Comment by audacitus** [comment]
@BE-Webdesign I came after reading the docs. Great work.

I know you emphasize that this isn't a production-level code, but could you give some pointers as to how to do this? I'm using Angular 2 and stringifying the arguments using http.post doesn't seem to cut it:

`let CommentData = {
    	author_name : 'Samsonite',
    	author_email : 'sams@sam.com',
    	content : 'my 3 cents',
      post : this.retrievedPostId
    }
    this.http.post('domain/wp-json/wp/v2/comments', JSON.stringify(CommentData)).subscribe(...)`

**Comment by supremesys** [comment]
Hello,

Thank you for providing code. I used your code. It's really good and working. Nice work.
