### ISSUE TITLE
Wrong rest_url when home_url contains parameters

### ISSUE THREAD

**Issue by eteubert** [WP-API/WP-API#2514]
The issue is in the implementation of [WP-API/api-core function get_rest_url](https://github.com/WP-API/api-core/blob/fba8637a3e56b82c8684ce8f1f11031bf39e1afe/wp-includes/rest-api.php#L210). The repository documentation says that I should not create issues/PR here, so I will outline the problem and solution here.

---

**Problem**

When the WordPress `home_url` contains a parameter, the URL returned by `get_rest_url()` is wrong.

Example home_url: "http://example.com/?lang=en"
Expected rest url: "http://example.com/wp-json/wp/v2/posts?lang=en"
Actual rest url: "http://example.com/wp-json?lang=en/wp/v2/posts"

**Solution**

The path has to be passed to `get_home_url` in its full form, not extended afterwards.

In `get_rest_url()`:

``` php
$url = get_home_url( $blog_id, rest_get_url_prefix(), $scheme );
$url .= '/' . ltrim( $path, '/' );
```

has to be replaced with:

``` php
$path = rtrim( rest_get_url_prefix(), '/' ) . '/' . ltrim( $path, '/' );
$url = get_home_url( $blog_id, $path, $scheme );
```

**Comment by OriginalEXE** [comment]
I can confirm that this issue is happening.

**Comment by danielbachhuber** [comment]
Thanks for the report, @eteubert. This will need to be fixed in WordPress core, so I've created a ticket as such https://core.trac.wordpress.org/ticket/37177

**Comment by LinzardMac** [comment]
Confirmed this is happening as well.
