### ISSUE TITLE
Uploading an attachment should not require the edit_posts capability

### ISSUE THREAD

**Issue by 27pchrisl** [WP-API/WP-API#2516]
Currently WP_REST_Attachments_Controller::create_item_permissions_check() checks $post_type_obj->cap->create_posts which returns the attachment-specifc "upload_files", but also $post_type_obj->cap->edit_posts which returns the general "edit_posts".

I suggest that edit_posts should not be required if the user can upload_files, as there is then no way via map_meta_cap to modify the API to allow a Subscriber (for example) to be able to submit attachments with the intention of allowing them to use a second API call to attach the attachment to a custom post type that is not 'post' (where that post type is registered using capability_type).

Unless there's a way I'm missing of submitting the attachment upload in such a way that satisfies this constraint?

**Comment by danielbachhuber** [comment]
I'm not quite sure of core's behavior in this regard, but the REST API should mirror the existing behavior of core. If core permits a subscriber with the `upload_files` capability but no `edit_posts` capability to upload a media file, then the REST API should mirror this behavior. However, if core requires `edit_posts` to upload a media file, then the REST API should keep its existing behavior.

In either case, we should add an explicit test case for this scenario.

**Comment by nullvariable** [comment]
Core appears to only test the 'edit_post' capability if a post id is involved. The core media upload files mostly start with a test `! current_user_can( 'upload_files' )` and then move on into other logic from there. The only cases in core that I could find the 'edit_posts' capability being required also required a post id:

_/wp-admin/media-upload.php:43:_
`( ! empty( $_REQUEST['post_id'] ) && ! current_user_can( 'edit_post' , $_REQUEST['post_id'] ) )`

_/wp-admin/media-new.php_
sets post id to zero if not provided or disallowed and hands the transaction to async-upload or upload.php

_/wp-admin/async-upload.php:56_
`if ( ! current_user_can( 'edit_post', $id ) )`
$id appears to be the attachment id if set

_/wp-admin/async-upload.php:87_
`if ( ! get_post( $post_id ) || ! current_user_can( 'edit_post', $post_id ) )`
post_id = 0 unless set in the request

_/wp-admin/upload.php:8_
does not test for edit_post, just delete permissions if removing/replacing attachments

_/wp-admin/includes/ajax-actions.php:2029_
`if ( isset( $_REQUEST['post_id'] ) ) {
        $post_id = $_REQUEST['post_id'];
        if ( ! current_user_can( 'edit_post', $post_id ) ) {`
also only checks if post_id is set

So as best I can tell core does not enforce 'edit_post' capability unless a post is involved.

**Comment by nullvariable** [comment]
it looks like there's a test case that covers this also `test_create_item_invalid_upload_files_capability` @ https://github.com/WP-API/WP-API/blob/develop/tests/test-rest-attachments-controller.php#L504

**Comment by danielbachhuber** [comment]
> Core appears to only test the 'edit_post' capability if a post id is involved.

Ok, we should make sure we mimic this behavior then.

**Comment by adamsilverstein** [comment]
This should be resolved by https://github.com/WP-API/WP-API/pull/2743

**Comment by kadamwhite** [comment]
Closing as assumed to be resolved by #2743, thanks @adamsilverstein !
