### ISSUE TITLE
non-authorised API client can access posts & users

### ISSUE THREAD

**Issue by lougreenwood** [WP-API/WP-API#2518]
Hi,

We're currently working through implementing the V2 of the REST API.

One thing we've noticed is that non-authorised clients can access various endpoints, for example: 

http --verbose GET http://someserver.com/wp-json/wp/v2/users/

(^ uses httpie for requests - https://github.com/jkbrzt/httpie)

It seems that this is quite a large data privacy & security issue and seems to be based on an assumption that users will always we public?

We're also seeing that CPTs are also accessible - however this is using the pods.io plugin - so i'm not sure whether that's fully their responsibility, or whether the core API makes assumptions about whether to allow access to posts/CPTs by default - without authentication.

Is this a known issue? Is there any method I can follow to lock the API down so that non-authenticated users cannot access any endpoints?

Thanks!

**Comment by websupporter** [comment]
Only users, who have published posts are supposed to show up. I did only a quick check, but this was working for me. The information about users, who have posts published are already publicly available, so I would not see a problem with this approach, but maybe your request also shows users who do not have posts published?

**Comment by websupporter** [comment]
As for the Custom Post Types, only when they register with `'show_in_rest' => true`, they are supposed to show up.

**Comment by lougreenwood** [comment]
I think you're right, I just did some more digging and it's only displaying a subset of users - I haven't confirmed it doesn't look like they have all published a post, but they are a user type created by another plugin (https://wisdmlabs.com/instructor-role-extension-for-learndash/installation-user-guide/) - perhaps this plugin is doing something funky and exposing them by default - I'll do some digging. Thanks

**Comment by lougreenwood** [comment]
Should `'show_in_rest' => true` show posts to non-authenticated clients, or only authenticated clients?

**Comment by websupporter** [comment]
as fas as I understand it to all.

**Comment by websupporter** [comment]
<strike>if you are logged in and you have the rights to edit posts of a certain post type, these show also up in the rest, even if `show_in_rest` is not set or set to false, so it is explicitly for public exposure.</strike>

read again, seems wrong.

**Comment by lougreenwood** [comment]
I'm not sure that is the case - or at least I'm not seeing that behaviour on my setup:
- I have a user (who is admin and can CRUD many post types in wp-admin)
- I am authenticating with this user with WP API
- If I try to access any CPT over API e.g
  - `http --verbose GET http://myserver.com/wp-json/wp/v2/a_cpt/ 'Authorization: Basic myT0ken'`
- I get:
  - `{`
    "code": "rest_no_route", 
    "data": {
        "status": 404
    }, 
    "message": "No route was found matching the URL and request method"
    }`
- If I enable REST support for that CPT in Pods.io, CPT endpoint begins to work for me over API - but then any client can also read it.

I took a look pods.io code and they are using show_in_rest when a CPT is REST enabled (last step above) - https://github.com/pods-framework/pods/blob/2.x/classes/PodsRESTHandlers.php#L168

**Comment by websupporter** [comment]
Yes sorry, I've read the source wrongly.

**Comment by lougreenwood** [comment]
These seem to be dangerous assumptions. For example, all of our CPTs are only accessible to logged in users, so the posts in CPTs and also the authors of these posts are not publicly available. However it seems that the current API implementation makes all of that data (user & post) available to non-authorised API clients.

Are you aware of any way I can configure the API to not return data to non-auth'd clients?

At the moment, the quickest solution I see is writing a custom plugin that blocks API URL access unless the client is auth'd (I can then also confirm they auth as a pre-defined user ID too - but that's just a bonus for us). However, this obviously wouldn't address the impact the above assumptions could have for other REST API plugin users...

Thanks :)

**Comment by websupporter** [comment]
Sorry, I have to go right now. Its an interesting question though. One more thing: Are those CPTs reachable via RSS Feeds?

**Comment by BE-Webdesign** [comment]
@lougreenwood Thanks for using the WP REST API!

When you are registering your CPTs, are they set to `public => false` or do they run a special set of capabilities for access control?  How are you handling the access control?

Are the CPTs you are trying to expose related to LearnDash?  If so, I can explain why you will want to write custom endpoints.

**Comment by rmccue** [comment]
Similar to how `show_in_admin` overrides `public` for display in the Dashboard, `show_in_rest` overrides `public` for display in the API. By setting `show_in_rest` to true, you are explicitly opting-in to allowing access to the post's data via the API.

For more granular control, you can instead subclass and check a relevant capability in your capability callbacks.

For built-in post types, we have all the capability checks mirror the rest of core, and it's not possible to access any data that's not already public somewhere else. This is why some users have publicly-available data: this is already exposed through post authorship attributes and links in themes.
