### ISSUE TITLE
Non Auth'ed requests return 400 for posts by private status instead of 401/403.

### ISSUE THREAD

**Issue by BE-Webdesign** [WP-API/WP-API#2519]
I will write a patch for this tomorrow.  Currently Non Auth'ed requests for posts by status do not return a proper error code.  Should use `rest_authorization_required_code()` but returns a 400 instead.

```
{
    "code": "rest_invalid_param"
    "message": "Invalid parameter(s): status"
    "data": {
        "status": 400
        "params": {
            "status": "Status is forbidden"
        }
    }
}
```

**Comment by BE-Webdesign** [comment]
Is `validate_user_can_query_private_statuses()` supposed to be used as a validation callback because that is currently what is changing the error from 403/401 to 400?

**Comment by danielbachhuber** [comment]
I think the current behavior is correct: `400` when one of the parameters is invalid.

We don't have prior art of using more descriptive status codes based on the way in which the parameter is invalid. Furthermore, because two parameters could need two different status codes, it's better to use the lowest common denominator.

**Comment by BE-Webdesign** [comment]
The check itself is a permissions check and even returns a 403/401 if it fails.  Because it is called as a `validate_callback` it gets changed to a 400.  Is that the desired functionality?  Doesn't make sense to me why 400 is the proper code.  The function should be called inside the `get_items_permissions_check()`, as it doesn't have to do with the validity of the parameter being passed in.  Not a big problem or anything.  If keeping it 400 is OK then that's fine.
