### ISSUE TITLE
I need get featured_image url with post object. can you help me ? Currently media object link attached with posts object _links. but i need the link of the image.

### ISSUE THREAD

**Issue by zumrywahid** [WP-API/WP-API#2520]

**Comment by BE-Webdesign** [comment]
If I am understanding correctly, all you need to do is pass _embed as a query parameter.  This will embed the linked resources into your response.  `GET my-domain.com/wp-json/wp/v2/posts/1?_embed` will  retrieve post ID of 1 with any linked resources embedded in the response.  If it has a featured image it will be in the `_embedded.wp:featuredmedia` portion of the response.

**Comment by zumrywahid** [comment]
Exactly...You saved tons of my time. Thanks

**Comment by BE-Webdesign** [comment]
No problem, thank you for using the WP REST API!
