### ISSUE TITLE
Create/Update comment meta

### ISSUE THREAD

**Issue by KaiP-598** [WP-API/WP-API#2521]
Hello, 
Here is what is happening: I am making a  iOS mobile app using swift2 that allows users to create comments, currently I am using a POST request,  POST domain.here/wp-json/wp/v2/comments?post=1&content=newComment and it works great, big thanks to @BE-Webdesign  #2510 .

I also want the user to enter their mobile numbers, so I created a comment custom field 'mobile', but currently the plugin does not have any comment meta endpoints so I can't just do POST domain.here/wp-json/wp/v2/comments?post=1&content=newComment&mobile=123456

So is there any way to add a comment meta 'mobile' to a comment?

I have read http://v2.wp-api.org/extending/modifying/, but don't see how I can do that in swift2.

**Comment by BE-Webdesign** [comment]
Comment, user and term meta aren't supported yet.  Feel free to help out here [on the meta endpoints](https://github.com/WP-API/wp-api-meta-endpoints)
