### ISSUE TITLE
"sticky" can only be set to true via "POST /wp/v2/posts/<id>"

### ISSUE THREAD

**Issue by coderkevin** [WP-API/WP-API#2522]
I'm writing example code for using the API, and have found the "sticky" property to be a little too sticky, if you will.

When I update a post, sticky can be set to true, but cannot be set to false. There's no error, the API returns a 200, but in the return data sticky is still true, even though I verified I'm sending { sticky: false } in the form data.

(EDIT: This was tested with the current release: 2.0-beta13.1 )
## To test:

Full example code here:
https://github.com/coderkevin/wp-rest-api-plugin-jquery-example/tree/sticky-bug
1. Clone the example plugin repo into your plugins directory.
2. Check out the 'sticky-bug' branch.
3. Activate the plugin.
4. Click the plugin menu item.
5. Click in the search box and hit <enter>. This will show the first 10 posts.
6. Click the "sticky" checkbox on one of the posts that is not yet sticky. It will update.
7. Click the "sticky" checkbox on the same post to make it no longer sticky. It will update as still sticky.
8. Check your network log in your JavaScript console and observe that { sticky: false } is being sent, and the resulting reply is 200, but the data is unchanged.

**Comment by almirbi** [comment]
Hello there,

I have tested this without your plugin and could not recreate the bug. Then I tried it from the plugin and noticed that you are not sending a JSON ( { sticky: false } ), you are actually sending form data. Switch to JSON and it will work.

Cheers
