### ISSUE TITLE
Filtering on multiple tax_queries

### ISSUE THREAD

**Issue by adamjv90** [WP-API/WP-API#2523]
Hello there, I am trying to duplicate the following tax_query defined under WP_Query Objects query_vars

```
[tax_query] => Array
(
    [0] => Array
        (
            [taxonomy] => blog
            [field] => slug
            [terms] => Array
                (
                    [0] => living
                )

            [operator] => IN
            [include_children] => 1
        )

    [1] => Array
        (
            [taxonomy] => living_tag
            [field] => term_id
            [terms] => 142835
            [operator] => NOT IN
        )

)
```

I have tried something like this with no success: /wp-json/wp/v2/posts?filter[tax_query][0][taxonomy]=blog&filter[tax_query][0][field]=slug&filter[tax_query][0][terms]=living&filter[tax_query][0][operator]=IN&filter[tax_query][0][include_children]=1

**Comment by BE-Webdesign** [comment]
You need to enable tax_query in the `rest_query_vars` filter.  Tax query is currently not supported. There is an open PR for it right now.  You would also need to revise your query string to match what you want.  I would suggest using something akin to `http_build_query()` to handle complex query parameters.
