### ISSUE TITLE
cookie authentication issues

### ISSUE THREAD

**Issue by necanthrope** [WP-API/WP-API#2525]
Greetings :)  Please forgive me for my low comprehension, but I'm having an issue with wp-api. According to the documentation (or at least my understanding after reading it) wp-api should be authenticating with the wordpress UI cookie by default.  However, when I install and turn on wp-api as a plugin and hit one of the REST endpoints with a browser that has no cookie, I am not prompted for any kind of authentication, and it returns the data I asked for. 

My question is, do I have to take any additional configuration steps to assure that whatever client hits the api endpoints is passing in the WP cookie?

Thank you!

Jeremy

**Comment by BE-Webdesign** [comment]
@necanthrope Thank you for using the WP REST API.

Authentication, for a lot of the basic GET endpoints with no query parameters, is not required.  The API was designed to reflect how WordPress itself works with regards to authentication.  Any public facing content by default is exposed through the WP REST API as it is in WordPress.  Actions that require authentication in WordPress will in turn require authentication over WP REST API.  With cookie authentication you will also need to pass a nonce with your requests when authenticating.

**Comment by necanthrope** [comment]
Ah, ok.  Thank you. :) 

Is there a list of endpoints that do require authentication? I'd like to replicate the logic in certain endpoints that don't.  For instance, I can query the API for information on an author just by passing in the author id.  This returns name, email, and all the other information we store.  Our author pages in the UI block this information. I'd like to replicate that in the API.

Thank you for your time. :)

**Comment by BE-Webdesign** [comment]
> Is there a list of endpoints that do require authentication?

I am pretty sure all endpoints, for certain requests, require authentication.

> I'd like to replicate the logic in certain endpoints that don't. For instance, I can query the API for information on an author just by passing in the author id. This returns name, email, and all the other information we store. Our author pages in the UI block this information. I'd like to replicate that in the API.

The name, email and public facing information appear on unauthenticated requests when the user is an author of a published public post.  All of the endpoint controllers are extensible, so you can overwrite what you need to.  You can also use the `rest_prepare_user` filter to modify the user response to fit your needs.
