### ISSUE TITLE
User capabilities

### ISSUE THREAD

**Issue by theApprentice** [WP-API/WP-API#2526]
Hello there, 
i'm developing a webapp in a multisite enviroment that from users point of view is divided in two major blocks: the standard wp-admin accessible to administrators, and the frontend admin (there is non traditional only read frontend).
I'd like to guarantee editor role the capabilities of deleting posts and create users. I've used "members" plugin to achieve that, but seems that when i use rest to do such tasks, logged in like an editor user, i can't perform them. 
Can you please help me understand how to modify users capabilities in a way that works also using rest protocol?

Many thanks,
G.

p.s.
quite disappointing is that using postman with editors credentials i can delete posts, inside the frontend admin i receive a 405 error.

**Comment by BE-Webdesign** [comment]
If you are getting a 405 for the DELETE request, your server might not support that HTTP method. You would want to try to add the ?_method=DELETE to a POST request.  So POST mydomain.com/wp-json/wp/v2/posts/1?_method=DELETE along with proper Authentication.

**Comment by theApprentice** [comment]
Hi BE-Webdesign,
thanks for the answer, looks like using codekit and rest doesn't work well! 
Now i can delete what i want, but still cant create users! I've checked the WP_User object and has the create_users capability set to true, trying to create one always return 403 error! 
Can't figure out why!!

TY,
G.

**Comment by BE-Webdesign** [comment]
403 means that you have authenticated but do not have proper permissions.  Since you are in a multisite environment, you need to check that the user has `manage_network_users` (if I recall naming correctly, you need to double check). You can hook into `rest_pre_dispatch` and send a request so you can see what user you are authenticating as in the response.  Better option is to send it out to some sort of log and return null.  My guess is that the user may not have the right multisite privileges.

``` php
add_filter( 'rest_pre_dispatch', 'my_prefix_show_user' );

function my_prefix_show_user( $response ) {
    $response = wp_get_current_user();
    return $response;
}
```

Throw that in functions.php of an active theme or into a plugin for testing purposes.

**Comment by theApprentice** [comment]
This is the response i get!
{
	"data": {
		"ID": "23",
		"user_login": "ditta",
		"user_pass": "$P$BW5gSjwVpeAtC6qL.rS.rxD.MShHGq.",
		"user_nicename": "ditta",
		"user_email": "ditta@kytrhegw.iy",
		"user_url": "",
		"user_registered": "2016-06-03 09:32:40",
		"user_activation_key": "",
		"user_status": "0",
		"display_name": "ditta",
		"spam": "0",
		"deleted": "0"
	},
	"ID": 23,
	"caps": {
		"editor": true
	},
	"cap_key": "wp_12_capabilities",
	"roles": [
		"editor"
	],
	"allcaps": {
		"moderate_comments": true,
		"manage_categories": true,
		"manage_links": true,
		"upload_files": true,
		"unfiltered_html": true,
		"edit_posts": true,
		"edit_others_posts": true,
		"edit_published_posts": true,
		"publish_posts": true,
		"edit_pages": true,
		"read": true,
		"level_7": true,
		"level_6": true,
		"level_5": true,
		"level_4": true,
		"level_3": true,
		"level_2": true,
		"level_1": true,
		"level_0": true,
		"edit_others_pages": true,
		"edit_published_pages": true,
		"publish_pages": true,
		"delete_pages": true,
		"delete_others_pages": true,
		"delete_published_pages": true,
		"delete_posts": true,
		"delete_others_posts": true,
		"delete_published_posts": true,
		"delete_private_posts": true,
		"edit_private_posts": true,
		"read_private_posts": true,
		"delete_private_pages": true,
		"edit_private_pages": true,
		"read_private_pages": true,
		"create_users": true,
		"delete_users": true,
		"editor": true
	},
	"filter": null
}

**Comment by theApprentice** [comment]
I think i got the correct response, but still 403!
// EDIT
even using postman same resoults
// EDIT

"create_users": true,
"delete_users": true,
"manage_network_users": true,

**Comment by BE-Webdesign** [comment]
Then it's possible that the user is not a site admin.  You would need to check the `site_admins` option and verify that the user is listed.

**Comment by theApprentice** [comment]
Sorry i can't find site_admins option, i've checked on google but nothing pointed me in the right direction, using phpmyadmin either!

**Comment by BE-Webdesign** [comment]
You are running a multisite install correct?  It should be in your database somewhere. It is part of the site meta I believe.

**Comment by theApprentice** [comment]
I've found it!! Searched how to add values but nothing specific showed up!
I'm sorry to continue asking for help, can you show me the proper way to insert a user?
TYSM

**Comment by BE-Webdesign** [comment]
Sorry, but I forgot your original problem through reading all of this.  If you are on a multisite install and you want editor users be able to create users, then first you would need to make sure that the network option add new users is enabled which permits regular site administrators ( who are non super-admin ) to add users.  That could potentially be the hold up in your situation.

**Comment by theApprentice** [comment]
Dont worry, in the end you help me make it work! 
Although when i sent the request, even if the response is a wonderful 200, rest gives also some warnings and the users created are counted under the voice all in the users management admin page, but they aren't shown in the list!
For the purpose of the app is not a concern, but you never know!! 
Still a generic call to the users endpoint gives the correct and complete list of the users.

Below the warning i mentioned above:
{
    "readyState": 4,
    "responseText": "
\nWarning:  Invalid argument supplied for foreach() in /Users/Home/Documents/Lavori in corso/Clienti/by Neticom/Energy Global Solutions/WebAPP/wp-content/plugins/rest-api/lib/endpoints/class-wp-rest-users-controller.php on line 632
\n
\nWarning:  array_map(): Argument #2 should be an array in /Users/Home/Documents/Lavori in corso/Clienti/by Neticom/Energy Global Solutions/WebAPP/wp-content/plugins/rest-api/lib/endpoints/class-wp-rest-users-controller.php on line 320
\n
\nWarning:  Cannot modify header information - headers already sent by (output started at /Users/Home/Documents/Lavori in corso/Clienti/by Neticom/Energy Global Solutions/WebAPP/wp-content/plugins/rest-api/lib/endpoints/class-wp-rest-users-controller.php:632) in /Users/Home/Documents/Lavori in corso/Clienti/by Neticom/Energy Global Solutions/WebAPP/wp-includes/rest-api/class-wp-rest-server.php on line 1196
\n
\nWarning:  Cannot modify header information - headers already sent by (output started at /Users/Home/Documents/Lavori in corso/Clienti/by Neticom/Energy Global Solutions/WebAPP/wp-content/plugins/rest-api/lib/endpoints/class-wp-rest-users-controller.php:632) in /Users/Home/Documents/Lavori in corso/Clienti/by Neticom/Energy Global Solutions/WebAPP/wp-includes/rest-api/class-wp-rest-server.php on line 1196
\n
\nWarning:  Cannot modify header information - headers already sent by (output started at /Users/Home/Documents/Lavori in corso/Clienti/by Neticom/Energy Global Solutions/WebAPP/wp-content/plugins/rest-api/lib/endpoints/class-wp-rest-users-controller.php:632) in /Users/Home/Documents/Lavori in corso/Clienti/by Neticom/Energy Global Solutions/WebAPP/wp-includes/rest-api.php on line 395
\n
\nWarning:  Cannot modify header information - headers already sent by (output started at /Users/Home/Documents/Lavori in corso/Clienti/by Neticom/Energy Global Solutions/WebAPP/wp-content/plugins/rest-api/lib/endpoints/class-wp-rest-users-controller.php:632) in /Users/Home/Documents/Lavori in corso/Clienti/by Neticom/Energy Global Solutions/WebAPP/wp-includes/rest-api.php on line 396
\n
\nWarning:  Cannot modify header information - headers already sent by (output started at /Users/Home/Documents/Lavori in corso/Clienti/by Neticom/Energy Global Solutions/WebAPP/wp-content/plugins/rest-api/lib/endpoints/class-wp-rest-users-controller.php:632) in /Users/Home/Documents/Lavori in corso/Clienti/by Neticom/Energy Global Solutions/WebAPP/wp-includes/rest-api.php on line 397
\n{\"id\":71,\"username\":\"2321q\",\"name\":\"Name\",\"first_name\":\"\",\"last_name\":\"\",\"email\":\"ugfsdio@sfdfs.cj\",\"url\":\"\",\"description\":\"\",\"link\":\"http:\/\/enrg.qui\/yui\/author\/2321q\",\"nickname\":\"2321q\",\"slug\":\"2321q\",\"registered_date\":\"2016-06-10T21:23:56+00:00\",\"roles\":[],\"capabilities\":[],\"extra_capabilities\":[],\"avatar_urls\":{\"24\":\"http:\/\/0.gravatar.com\/avatar\/fff25df0f8c23bca4574cb07d1fe03fd?s=24&d=mm&r=g\",\"48\":\"http:\/\/0.gravatar.com\/avatar\/fff25df0f8c23bca4574cb07d1fe03fd?s=48&d=mm&r=g\",\"96\":\"http:\/\/0.gravatar.com\/avatar\/fff25df0f8c23bca4574cb07d1fe03fd?s=96&d=mm&r=g\"},\"acf\":{\"numero_di_telefono\":\"123456778980\"},\"_links\":{\"self\":[{\"href\":\"http:\/\/enrg.qui\/yui\/wp-json\/wp\/v2\/users\/71\"}],\"collection\":[{\"href\":\"http:\/\/enrg.qui\/yui\/wp-json\/wp\/v2\/users\"}]}}",
    "status": 200,
    "statusText": "OK"
}

Many thanks for the precious help!

**Comment by theApprentice** [comment]
wtf i can not delete..
{
    "readyState": 4,
    "responseText": "{\"code\":\"rest_user_cannot_delete\",\"message\":\"Sorry, you are not allowed to delete this resource.\",\"data\":{\"status\":403}}",
    "responseJSON": {
        "code": "rest_user_cannot_delete",
        "message": "Sorry, you are not allowed to delete this resource.",
        "data": {
            "status": 403
        }
    },
    "status": 403,
    "statusText": "Forbidden"
}

**Comment by BE-Webdesign** [comment]
> Although when i sent the request, even if the response is a wonderful 200.

If you are creating users you should get a 201, are you using the latest version 2 release of the WP REST API?  How are you getting those responses, because that is not how the responses are formatted in the API.  If you have some custom code running between the API and what you are running that is most likely the source of the problem.  Closing out the issue as it is most likely not a problem with the API.

**Comment by theApprentice** [comment]
Using v2 and since i have custom fields (by ACF) even for users, i've adopted the js used in their demo  to perform the calls.
https://github.com/airesvsg/acf-to-rest-api-example#live-demo

**Comment by BE-Webdesign** [comment]
Just to double check you are using some for of Authentication for the API right?

**Comment by theApprentice** [comment]
Right now only registered users directly logged in, so should be the cookie auth, simple as user and password; i've installed JSON Basic auth for the future call via vpn; i've also installed WP REST API - Site Endpoints

**Comment by BE-Webdesign** [comment]
If you are trying to do cookie Auth you need to pass a nonce with the request.  You will want to send an X-WP-Nonce request header with the valid nonce.  You can checkout how wp-api.js does it and mimic that to suit your needs with the ACF stuff you have going on.  Look at extras.php to see how that script is handled and you can do something similar with the js you are using.

**Comment by theApprentice** [comment]
Already done:
in the js, ajax request:

```
beforeSend: function(xhr){
   xhr.setRequestHeader('X-WP-Nonce', WP_API_Settings.nonce);
},
```

in functions.php after enqueue script:
`wp_localize_script( 'trigger', 'WP_API_Settings', array( 'root' => esc_url_raw( rest_url() ), 'nonce' => wp_create_nonce( 'wp_rest' )));`

**Comment by theApprentice** [comment]
I think that the issue is really with the api since now i've got the expected 201 code, the problem was with the roles, they have to be send like an array and not a string.
Still i can't delete users created by the editor user with extended capabilities, like i can do with all the other contents.
