### ISSUE TITLE
Works fine on local but it says ERROR 404 - PAGE NOT FOUND on external php server

### ISSUE THREAD

**Issue by hamiltonnieri8755** [WP-API/WP-API#2528]
ERROR 404 - PAGE NOT FOUND

I use hostgator php server.

**Comment by BE-Webdesign** [comment]
Hi @hamiltonnieri8755,

Could you provide an example request, and do you have any other plugins installed and activated?

**Comment by aaronware** [comment]
@hamiltonnieri8755 if it's a new install on your server be sure that you have updated your permalink structure on the server so it's not using the default. I've had that happen in the past when spinning up an install real quick

**Comment by rmccue** [comment]
Closing out due to lack of response; please feel free to come back and discuss if you still need help!
