### ISSUE TITLE
Query post problem

### ISSUE THREAD

**Issue by xralphack** [WP-API/WP-API#2530]
As I made a request for posts?per_page=19 return 20 rows, and posts?per_page=25 return 24 rows. However request for posts?per_page=0 ~18 works fine. Can someone give me some help?

**Comment by BE-Webdesign** [comment]
Hi @xralphack, thank you for using the WP REST API.

Do you currently have any password protected posts?

**Comment by xralphack** [comment]
You're right. The problem comes from password. 
Thanks a lot ~
