### ISSUE TITLE
Long query time for custom post type

### ISSUE THREAD

**Issue by sylvan-d-ash** [WP-API/WP-API#2531]
I've a custom post type ["production"] that has several custom fields (gallery, review, etc). I also have another custom post type ["people"] that has no custom fields. The API query for **people** runs smoothly i.e. `/wp-json/posts?type=people` completes in ~150ms. However the API query for **production** takes a full 24 seconds i.e. `/wp-json/posts?type=production`. I'm at a loss as to why filtering the posts for **type=production** is taking so insanely long...?

**Comment by kadamwhite** [comment]
@winter7621, I am not sure what could be causing the behavior you describe, but from your URLs it looks like you are using version one of the API. V1 is being maintained for security fixes only at this time; are you in a position to attempt upgrading to the latest v2 beta plugin to see whether the much newer code might resolve the issue?

**Comment by sylvan-d-ash** [comment]
I decided to create a different post type that only contained the bare minimum of the information I needed to display, which then contained a link to the post type with the full information. But thanks for the help either way
