### ISSUE TITLE
Demo API should enable CORS

### ISSUE THREAD

**Issue by heygrady** [WP-API/WP-API#2532]
The [demo api](http://demo.wp-api.org/wp-json/wp/v2/) currently doesn't send CORS headers. This limits the ability of people to easily implement the API over AJAX. Of course this issue only affects demos. No one should be writing a real app against the demo api :)

However, for tutorial documentation it is useful to simply write code against the demo API so that a new developer can get a sense for what WP-API can do. Specifically this allows a tutorial author to leave the WP-API plugin implementation step to the user while still writing code that uses the API.

Here's a [jsbin showing the issue](http://jsbin.com/capuwokase/edit?js,console).

``` js
const url = 'http://demo.wp-api.org/wp-json/wp/v2/posts/?filter[name]=hello-world&_embed'
fetch(url)
  .then(response => response.json())
  .then(json => {
    console.log(json)
  })
  .catch(error => console.log(error.toString()))
```

```
Fetch API cannot load http://demo.wp-api.org/wp-json/wp/v2/posts/?filter[name]=hello-world&_embed.
No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://localhost:3000' is therefore not allowed access.
If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Not sure if this is the right place to file this ticket.

Also, I've seen other issues regarding CORS and WP-API. This isn't a request to change anything about WP-API itself, only to enable CORS _in the demo_.

Strangely, [it seems to work in some cases](http://jsbin.com/guwazisosu/edit?js,console).

**Comment by rachelbaker** [comment]
@heygrady I will pass along your request to @joehoyle who setup our demo site.  

I am going to close this issue, as this isn't regarding a bug or problem with the REST API endpoints plugin itself.
