### ISSUE TITLE
custom field fails on custom route

### ISSUE THREAD

**Issue by joelstransky** [WP-API/WP-API#2533]
Adding a rest field only seems to work with native routes.
The `post_link` field will exist when using native routes like:
`wp-json/wp/v2/document_cpt/` but the rest field `get_callback` callback wont even fire if I use my custom endpoint of `wp-json/docs/v1/s`

```
add_action( 'rest_api_init', function () {
  register_rest_route( 'docs/v1', '/s', array(
    'methods' => 'GET',
    'callback' => 'dcdc_doc_search',
  ) );

  register_rest_field( 'documents_cpt', 'post_link',
    array(
      'get_callback'    => 'dcdc_get_document_link',
      'update_callback' => null,
      'schema'          => null
    )
  );
});

function dcdc_get_document_link( $object, $field_name, $request ) {
  return get_permalink();
}

function dcdc_doc_search( $data ) {
  $args = array(
    's'           => isset( $data['search'] ) ? $data['search'] : "",
    'post_type'   => array( 'document_cpt' )
  );
  $doc_query = new WP_Query( $args );
  $posts = $doc_query->get_posts();
  if ( empty($posts) ) {
    return new WP_Error( 'dcdc_no_documents', 'No Documents Found', array( 'status' => 404 ) );
  }
  return $posts;
}
```

**Comment by BE-Webdesign** [comment]
Hi @joelstransky, thank you for using the WP REST API.

`WP_REST_Controller::add_additional_fields_to_object()` is the method that is used to register additional rest fields.  For your endpoint in order to use `register_rest_field()` you would need to have your endpoint extending the WP_REST_Controller class.  This is a highly recommended approach.

For what you are doing you can simply register your CPT with `show_in_rest => true`, `rest_base => 'documents'`, `rest_controller_class => 'WP_REST_Posts_Controller'` and it will show up at wp/v2/document_cpt/ and you can register rest fields the way you are trying and register the schema for your matching rest_base.  This is probably the simplest solution but not recommended.  Especially if your CPT is intended for private use.

**Comment by joelstransky** [comment]
Ok thanks. I was afraid of that. If writing custom controllers is as hard as custom nav walkers I'm in trouble. Are there any tutorials on that?
Some posts of my CPT will require certain roles of users from another WP site but no idea how to enforce that yet.
I'd really like all of the fields that are already available when using the wp/v2 namespace (which is the only namespace the acf-to-rest-api plugin exposes on) but with the ability to filter out non-public posts.
Is there an IRC room for WP-API?

**Comment by BE-Webdesign** [comment]
> Ok thanks. I was afraid of that. If writing custom controllers is as hard as custom nav walkers I'm in trouble. Are there any tutorials on that?

[The docs site has one](http://v2.wp-api.org/extending/adding/), honestly it is not entirely complete.  I am working on a tutorial which should be out soon-ish.  I'll ping you when it's done.

> Is there an IRC room for WP-API?

You can join the slack channel #core-rest-api if you have a .org account.

**Comment by joelstransky** [comment]
Thanks again! Already reading that page and just joined the channel. It seems already that a custom Controller is a better option than what little functionality I've already achieved via register_rest_field().
Looking forward to a tutorial.

**Comment by BE-Webdesign** [comment]
Did you successfully extend the controller class?  Going to close out this issue, but if you have any more questions open up a new ticket, post here, or use the slack channel.

**Comment by daltonrooney** [comment]
Sorry for bringing back a long-closed thread, but I just had a very long night trying to figure out why my callback wasn't firing on `register_rest_route`. Like @joelstransky, my fields weren't being added when using a custom namespace, and I would like to keep these CPTs private so I can't use the default namespace.

Should it be more clear in the documentation that a code example like this:

`add_action( 'rest_api_init', 'slug_register_starship' );
function slug_register_starship() {
    register_rest_field( 'post',
        'starship',
        array(
            'get_callback'    => 'slug_get_starship',
            'update_callback' => null,
            'schema'          => null,
        )
    );
}`

Would _only_ work by extending the WP_REST_Controller class, and won't work on it's own? I can submit a PR on this if that would help.

Also signing up to get a ping on that tutorial for extending WP_REST_Controller. I've got a basic one going but I can use all the help I can get. 😃

**Comment by BE-Webdesign** [comment]
Hi Dalton,

Thank you for using the WP REST API.  Making a note of this could be very helpful on the [docs website](https://github.com/WP-API/docs-v2).  I agree that the endpoint controller classes can be a bit intimidating at first, but once you get comfortable with them they offer a lot of useful functionality.  Here is [part 1 of a rest api endpoint guide](https://bewebdesign.wordpress.com/2016/06/19/demystifying-the-wordpress-rest-api-endpoints-part-i/), feel free to leave a comment.  Part 1 breaks down the methods in the controller class.  Part 2, coming in earlyish August, will focus on a coding tutorial.
