### ISSUE TITLE
Endpoints over https

### ISSUE THREAD

**Issue by fammejias1** [WP-API/WP-API#2537]
How would I go about setting up an endpoint over https.  Ideally to serve both http and https.

Thanks

**Comment by rmccue** [comment]
I'm unsure exactly what you want to achieve here. HTTPS works the same for the REST API as it does for the rest of WordPress.

You can also force the REST API to be HTTPS-only regardless of the rest of your site by using [a plugin](https://wordpress.org/plugins/json-rest-api-force-ssl/), however be aware that this will trigger cross-origin requests from HTTP to HTTPS. We support cross-origin requests, but some JS clients may not.
