### ISSUE TITLE
Basic does not show up as a valid authentication method (or work)

### ISSUE THREAD

**Issue by birds-inc** [WP-API/WP-API#2538]
Wordpress: v4.5.2
WP REST API: v2.0-beta13.1
JSON Basic Authentication (/WP-API/Basic-Auth): v0.1

I've installed and activated the WP-API and Basic-Auth plugins, however, "Basic" does not appear in the list of authentication methods when querying /wp-json.

```
...
  "namespaces": [
    "wp/v2",
    "oembed/1.0"
  ],
  "authentication": [],
  "routes": {
    "/": {
...
```

If I install the OAuth plugin, the method does appear:

```
...
  "namespaces": [
    "wp/v2",
    "oembed/1.0"
  ],
  "authentication": {
    "oauth1": {
      "request": "http://www.crucibleradio.com/oauth1/request",
      "authorize": "http://www.crucibleradio.com/oauth1/authorize",
      "access": "http://www.crucibleradio.com/oauth1/access",
      "version": "0.1"
    }
  },
  "routes": {
    "/": {
...
```

For any request I make using the Basic authentication method, I get a permissions error:

```
{
  "code": "rest_cannot_edit",
  "message": "Sorry, you are not allowed to update this post.",
  "data": {
    "status": 401
  }
}
```

Have test this behavior in Postman, cURL and in code.

What causes an authentication method to become "registered" with WP-API and show up in that list? Does "Basic" appear as an item in the authentication methods in a working installation?

**Comment by BE-Webdesign** [comment]
The Basic Authentication does not currently show up in the /wp-json/ endpoint response.  From your response this means that you are authenticating as someone but they are unauthorized to edit the post.  You need to pass an Authorization request header with a value of Basic base64encode( username:password ). 403 code means you are unauthenticated.

For a user, admin, with a password of password, it would look something like this.

`Authorization: Basic YWRtaW46cGFzc3dvcmQ=`

**Comment by birds-inc** [comment]
> The Basic Authentication does not currently show up in the /wp-json/ endpoint response.

Ok, good to know.

> From your response this means that you are authenticating as someone but they are unauthorized to edit the post. 

Hrmm.

> You need to pass an Authorization request header with a value of Basic base64encode( username:password ). 403 code means you are unauthenticated.
> 
> For a user, admin, with a password of password, it would look something like this.
> 
> Authorization: Basic YWRtaW46cGFzc3dvcmQ=

Can confirm I am currently sending a Authorization header with this format.

Attempting to update a post, I receive no error but the API has no effect:

```
POST /wp-json/wp/v2/posts/196 HTTP/1.1
Host: xxxxxxx.com
Authorization: Basic c2xhY2thZxxxxxxxxxxxxxxxxxxxxxxx
Cache-Control: no-cache
Postman-Token: fa6a3528-9892-e45d-ff19-063b612a00da

{"title": "Ep. 1 - E3 (ft. Texas Prod)"}
```

This just returns the specified post (same as a GET) with no modification and no error message.

Have verified the account specified in the Authorization header has permission to edit posts.

**Comment by BE-Webdesign** [comment]
> POST /wp-json/wp/v2/posts/196 HTTP/1.1
> Host: xxxxxxx.com
> Authorization: Basic c2xhY2thZxxxxxxxxxxxxxxxxxxxxxxx
> Cache-Control: no-cache
> Postman-Token: fa6a3528-9892-e45d-ff19-063b612a00da
> {"title": "Ep. 1 - E3 (ft. Texas Prod)"}

When updating it is technically proper to use PUT, if your server supports it.

> This just returns the specified POST (same as a GET) with no modification and no error message.

Can you share the response?  If you didn't pass any parameters to change the content, title, etc. then getting a response of the actual post with no changes means the API is working as desired.  The reason why you are not getting the desired results is because you are passing some JSON in the request body which is not compliant with how request bodies work by default.  If you passed title=urlencode( 'Ep. 1 - E3 (ft. Texas Prod)' ), then you should be getting the results you are looking for.

**Comment by birds-inc** [comment]
Ah, thank you so much for your help.

> When updating it is technically proper to use PUT, if your server supports it.

Ok, will do.  Was just following the API reference which references POST:

`POST /wp/v2/posts/<id>`
http://v2.wp-api.org/reference/posts/ 

> The reason why you are not getting the desired results is because you are passing some JSON in the request body which is not compliant with how request bodies work by default.

Again, API reference uses JSON, but no problem, can use urlencode:

`$ curl -X POST http://demo.wp-api.org/wp-json -d '{"title":"My New Title"}'`

Ok, here's my updated request:

```
PUT /wp-json/wp/v2/posts/196 HTTP/1.1
Host: xxxxxxxxxxxxx.com
Authorization: Basic c2xhY2thxxxxxxxxxxxxxxxxxx
Cache-Control: no-cache
Postman-Token: 482cbf16-aa67-c60b-0df6-82f4336aad25
Content-Type: application/x-www-form-urlencoded

title=Ep.+1+-+E3+(ft.+Texas+Prod)
```

Ok, now I get a 401!  We're getting somewhere:

```
{
  "code": "rest_cannot_edit",
  "message": "Sorry, you are not allowed to update this post.",
  "data": {
    "status": 401
  }
}
```

This I don't understand - the account I'm specifying in the Authentication header (for this test) has Administrator privileges including editing posts.

Interestingly, if I don't provide an Authentication header altogether, I get the same error:

```
{
  "code": "rest_cannot_edit",
  "message": "Sorry, you are not allowed to update this post.",
  "data": {
    "status": 401
  }
}
```

Would think it'd be a 403 in that case.

**Comment by BE-Webdesign** [comment]
> Again, API reference uses JSON, but no problem, can use urlencode:
> 
> $ curl -X POST http://demo.wp-api.org/wp-json -d '{"title":"My New Title"}'

That is a curl request, but I can definitely understand the confusion.

> Interestingly, if I don't provide an Authentication header altogether, I get the same error:

Is your WordPress install a fresh install and do you have any other plugins relating to Auth for the API running?

**Comment by birds-inc** [comment]
> That is a curl request, but I can definitely understand the confusion.

Is there a difference between the preferred request body format if you're using cURL to make the request vs Postman vs code or anything else?

> Is your WordPress install a fresh install and do you have any other plugins relating to Auth for the API running?

Fresh install, only plugins installed and active are those referenced in the OP:

WP REST API: v2.0-beta13.1
JSON Basic Authentication (/WP-API/Basic-Auth): v0.1

**Comment by BE-Webdesign** [comment]
> Is there a difference between the preferred post body format if you're using cURL to make the request vs Postman vs code or anything else?

Not sure what you mean, hopefully this helps.  HTTP itself uses body params as key value pairs similar to the way query params are attached to a url in HTTP.  cURL does a lot more than just HTTP, so it uses a different format for the data.

> Fresh install, only plugins installed and active are those referenced in the OP:
> 
> WP REST API: v2.0-beta13.1
> JSON Basic Authentication (/WP-API/Basic-Auth): v0.1

Could be something with your server configuration or you are not authenticating as the user you are trying to use.

**Comment by birds-inc** [comment]
> cURL does a lot more than just HTTP, so it uses a different format for the data.

Yes, but that's http:// in the example.. I digress.

> Could be something with your server configuration or you are not authenticating as the user you are trying to use.

Any ideas on exploring/verifying/correcting this issue?

**Comment by BE-Webdesign** [comment]
> Yes, but that's http:// in the example.. I digress.

You can send body params as JSON via HTTP if the correct Content-Type headers are being sent.  By default I believe application/x-www-form-urlencoded is the Content-Type for PUT and POST on most servers, so you would pass the data matching that instead of application/json.

> Any ideas on exploring/verifying/correcting this issue?

``` php
add_filter( 'rest_pre_dispatch', 'prefix_return_current_user' );

function prefix_return_current_user( $result ) {
    $result = wp_get_current_user();
    return $result;
}
```

Putting something like that in a plugin or functions.php of an active theme will return the current user for testing any request.

**Comment by birds-inc** [comment]
> You can send body params as JSON via HTTP if the correct Content-Type headers are being sent. By default I believe application/x-www-form-urlencoded is the Content-Type for PUT and POST on most servers, so you would pass the data matching that instead of application/json.

Ah, OK, makes sense - I'm using Postman for testing which applies the correct Content-Type, but it makes no difference to me.  Fine with urlencoded.

> Putting something like that in a plugin or functions.php of an active theme will return the current user for testing any request.

Excellent - will test and report back.

**Comment by BE-Webdesign** [comment]
Forgot one part of the code above.  I will edit it to reflect that.

**Comment by birds-inc** [comment]
> Putting something like that in a plugin or functions.php of an active theme will return the current user for testing any request.

API requests return:

```
{
  "data": {},
  "ID": 0,
  "caps": [],
  "cap_key": null,
  "roles": [],
  "allcaps": [],
  "filter": null
}
```

I've also tried creating a new user account - interestingly enough it doesn't show up when i call `/wp-json/wp/v2/users`

**Comment by birds-inc** [comment]
Just to be sure, I've created a fresh Wordpress install and this issue still reproes.

**Comment by BE-Webdesign** [comment]
> API requests return:
> 
> {
>   "data": {},
>   "ID": 0,
>   "caps": [],
>   "cap_key": null,
>   "roles": [],
>   "allcaps": [],
>   "filter": null
> }

So that means the user you are authenticating as is an anonymous user.  So somewhere in the process your server is not taking the correct Authorization header.  What server are you running your WordPress install on?

> I've also tried creating a new user account - interestingly enough it doesn't show up when i call /wp-json/wp/v2/users

That is intended functionality.  If the user posts a published public post then they should show up in the index.  Most user data is private, and the API keeps it private unless there is Auth for it.

**Comment by birds-inc** [comment]
> So somewhere in the process your server is not taking the correct Authorization header.

Was wondering about this - saw another user saying their authentication header was getting stripped, and had temporarily fixed it by modifying their .htaccess?

> What server are you running your WordPress install on?

Dreamhost - Apache on Ubuntu 12.04 LTS

> That is intended functionality. If the user posts a published public post then they should show up in the index. Most user data is private, and the API keeps it private unless there is Auth for it.

Very edifying!

**Comment by BE-Webdesign** [comment]
`SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`

You can use that, but typically a host will remove the header for security purposes specific to their implementation. If you aren't just testing the WP REST API, I highly recommend using oAuth.  [Recently released was the broker](https://apps.wp-api.org/) and I would highly recommend checking that out as it takes a lot of the detail work out.

**Comment by birds-inc** [comment]
SOLVED.

I appended this line to my site .htaccess.  Am now able to POST and PUT changes with the best of them.

@BE-Webdesign, you're a scholar and a saint.  Thanks for your patience ;)

**Comment by kish2011** [comment]
add_filter( 'rest_pre_dispatch', 'prefix_return_current_user' );
function prefix_return_current_user( $result ) {
    $user_id = get_current_user_id();
    $user = wp_set_current_user($user_id );
}

I added this code and now it is working @alexgalli @BE-Webdesign
