### ISSUE TITLE
Trouble Uploading media and assigning data 

### ISSUE THREAD

**Issue by masc145** [WP-API/WP-API#2539]
We are having trouble when uploading media to a wordpress site with the son rest api, we can upload the photos, but we can not named or assign data to it. With this code we can upload, but no info is assigned, not even the name, in fact the name is the url and name with file with out extension

```
$username = "ZX";
$password = "ZX";
$host = 'http://ZX.com/wp-json/wp/v2/media';
$data = json_encode($data);
$file = '/Users/xx.png';
$imagedata  = file_get_contents($file);
$process = curl_init($host); 
curl_setopt($process, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($process, CURLOPT_BINARYTRANSFER, TRUE);
curl_setopt($process, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($process, CURLOPT_TIMEOUT, 50);
curl_setopt($process, CURLOPT_USERPWD, $username . ":" . $password);
curl_setopt($process, CURLOPT_POSTFIELDS, $data);
curl_setopt($process, CURLOPT_HTTPHEADER, array('Content-Type:image/png','Content-Disposition:attachment;filename='.$file));
$return = curl_exec($process);
print_r($return);

```

But if we want to to assign data like this one below, we don't know how:

```
$data = array(
  "status" => "draft",
  "title" => "Photo media",       
  "description" => "Photo media1",
  "media_type" => "image",
  "alt_text" => "alternate text"
  );

```

how can we do it , we tried everything in the book, and we searched the internet without luck!

Can any one help us? Thanks in Advanced

**Comment by danielbachhuber** [comment]
Sorry, it's hard to say what the specific issue is.

**Comment by mpiraux** [comment]
As far as I understood @masc145 issue, he is simply wondering how to upload a media file using the REST API. Manipulating media objects using the API is pretty well documented but creating and uploading a file is not covered. In Javascript, after some trial and error, I ended up doing this:

```
var fd = new FormData();
fd.append("file", file);
$.ajax({
    url: wpApiSettings.root + 'wp/v2/media/',
    method: 'POST',
    processData: false,
    contentType: false,
    data: fd
}).done(function (response) {
    callback(response)
});
```

I'm not confortable enough with PHP nor with the underlying manipulations done by this script to be able to help you more than this, but finding that the `file` attribute is expected to be the binary data should be a good direction for you to head for.
