### ISSUE TITLE
Documentation - need small note on custom endpoint

### ISSUE THREAD

**Issue by nitzanb** [WP-API/WP-API#2541]
Just spent 2 hours trying to understand why after I did copy-paste to the example in http://v2.wp-api.org/extending/adding/ I kept getting a 404 (WP 404, not a Json 404) on 
http//www.example.com/myplugin/v1/author/1

well, apparently, the custom routing still requires the /wp-json/ in the URL.

So 
http//www.example.com/myplugin/v1/author/1 - Won't work.
http//www.example.com//wp-jsonmyplugin/v1/author/1 - works.

A small notice or example in the Documentation would really be great.

**Comment by danielbachhuber** [comment]
> A small notice or example in the Documentation would really be great.

Sure, I've updated https://github.com/WP-API/docs-v2/commit/5972f32778b7f3c817b6dd39339f0f1e67d9ef50
