### ISSUE TITLE
How to make my schema

### ISSUE THREAD

**Issue by eoxia-jimmy** [WP-API/WP-API#2542]
Hi,

how to define a subobject in a model ?

`{
    "id": {
        "description":  "Unique identifier for the object." ,
        "type": "integer",
        "sanitize_callback": "absint"
    },
    "options": {
        "type": "object",
        "properties": {
            "parent_id": {
                "type": "integer",
                "sanitize_callback": "absint"
            }
        }
    }
}
`

When i send this form with the "test" value in parent_id, the returned value is "test" instead of an integer : 0.
See picture.
![gigi](https://cloud.githubusercontent.com/assets/18569301/16046749/cc9660ca-324d-11e6-8ea8-a3392eff1338.JPG)

How can i do please ?
Thanks.

**Comment by rmccue** [comment]
`sanitize_callback` and `validate_callback` are only applied at the top-level of the object, and are not applied to objects beneath it.

This is part of the REST API infrastructure, so if you'd like to file an enhancement for this, please do so on the [WordPress Trac](https://core.trac.wordpress.org/newticket?component=REST+API).
