### ISSUE TITLE
Filtering with multiple values

### ISSUE THREAD

**Issue by agustina-biscayart-movile** [WP-API/WP-API#2543]
Hi all! 

I'm trying tu use filters with multiple value. For example:

`http://my.site.com/wp-json/wp/v2/posts?filter[category__not_in]=20,15`

But it is only taking the first parameter, in this case 20. It does filter those posts that belongs to the category 20 but it **does not** filter those with category 15.

Any way to solve this?

**Comment by nitishn** [comment]
How about this? You can use [cat]=-{category_id} to filter categories. 

`wp-json/wp/v2/posts?filter[cat]=-20,-15`

**Comment by nitishn** [comment]
So I was reading through the plugin code and noticed that 'category__not_in' is not part of the valid variables you can filter by. This is why you're unable to filter correctly. 

You can remedy this easily by adding 'category__not_in'  to the array of valid variables. You need to hook into the filter similar to the following...

```
add_filter( 'rest_query_vars', 'allowCustomQueryArgs' );
function allowCustomQueryArgs( $validVars )
{
    $validVars = array_merge( $validVars, array('category__not_in' ) );
    return $validVars;
}
```

**Comment by agustina-biscayart-movile** [comment]
Hi @nitishn! 

I'had already added the category__not_in as a filter but id didn't work with multiple categories either.

Anyway, I tried using `[cat]=-20,-15` and id did work perfect! So, thanks!!
