### ISSUE TITLE
How to use "categories" argument when listing posts

### ISSUE THREAD

**Issue by agustina-biscayart-movile** [WP-API/WP-API#2544]
Just that. How do I use the categories argument when I do a posts call? I tried using ?categories=name_of_category or ?categories=id and none of them worked.

![image](https://cloud.githubusercontent.com/assets/12632582/16053842/ceabbfc0-3240-11e6-9038-db9f8e3c0c9f.png)

Your plugin is very nice but you should improve your documentation.

Thanks!

**Comment by nitishn** [comment]
Just for brevity, is this the URL you are using to test? I was able to get this to work with a category ID. 

`wp-json/wp/v2/posts?categories=1`

**Comment by itzikbenh** [comment]
This would work with name
http://localhost:8888/food/wp-json/wp/v2/posts?filter[category_name]=Pizza

**Comment by agustina-biscayart-movile** [comment]
It worked using names, my mistake. Thanks!

**Comment by mrtieutien** [comment]
Hi all,
The same problem.

`
import {Injectable} from 'angular2/core';
import {Http} from 'angular2/http';

@Injectable()
export class CategoriesService {

```
constructor(private http:Http) {
}

private _wpBase = 'http://localhost/angular/wp-json/wp/v2/';

getPostsCategory(slug) {
     return this.http.get(this._wpBase + 'posts?filter[category_name]=' + slug );
}
```

}

`

This is how I took the posts of a category.  But the results returned only a first post. 
Why ???
Please help me.
Thanks you
