### ISSUE TITLE
Fluent interface for WP_REST_Response

### ISSUE THREAD

**Issue by tfrommen** [WP-API/WP-API#2545]
Hi there,

it would be really handy to give (at least) the `WP_REST_Response` class a fluent interface. This is as easy as `return $this` (as well as adapting the according PHPDoc annotation) in the following methods:
- `WP_REST_Response::add_link()`;
- `WP_REST_Response::add_links()`;
- `WP_REST_Response::link_header()`;
- `WP_REST_Response::set_matched_handler()`;
- `WP_REST_Response::set_matched_route()`.

Why?
So one can do this:

``` php
    return ( new WP_REST_Response() )->set_matched_route( /* */ )->add_links( /* */ );
```

**Comment by rmccue** [comment]
Thanks for filing this issue! `WP_REST_Response` is part of the infrastructure which is now in WordPress core, so you'll need to file an issue on [Trac](https://core.trac.wordpress.org/newticket?component=REST+API) instead.
