### ISSUE TITLE
Post status is missing from data

### ISSUE THREAD

**Issue by neonwired** [WP-API/WP-API#2547]
Tested this on the demo at https://demo.wp-api.org/ as well, it returns all post data except post_status which seems to be missing.

**Comment by joehoyle** [comment]
@neonwired `status` is only available in `context=edit` and therefore needs to be an authentication request. Would be something like `https://demo.wp-api.org/wp-json/wp/v2/posts?context=edit` (needs to be authorized)

**Comment by neonwired** [comment]
It's authenticated using cookie as the user will be logged in. Not sure how context=edit works do i just pass that as data with every request? I'm using the backbone client btw so something like this?

`this.collection.fetch({
            data: {
                context: 'edit',
                author: user_id,
                filter: {
                    post_status: ['publish', 'pending']
                }
            },
            reset: true
        });`

**Comment by rachelbaker** [comment]
@neonwired that should work.  Closing this issue
