### ISSUE TITLE
Lazy-Load Controllers

### ISSUE THREAD

**Issue by dwoldo** [WP-API/WP-API#2551]
I am attempting to implement a centralized route configuration whereby all routes are registered within a routes.php file which is then initialized using rest_api_init hook. 

Is there a good example of this? I am attempt to avoid initializing all of my controllers using rest_api_init.

Thanks!

**Comment by dwoldo** [comment]
I know there is this pull request (https://github.com/WP-API/WP-API/pull/1285) that is considering how to automatically initialize controllers with default functions. I am interested in the registering routes from a central place rather than including each controller and initializing it

**Comment by rmccue** [comment]
This is pretty easy, but you'll need to use an intermediary function as your callback:

``` php
register_rest_route( '/dwoldo/v1', '/', [
    'methods' => 'GET',
    'callback' => function ( WP_REST_Request $request ) {
        $controller = new Dwoldo_REST_Controller();
        return $controller->get_item( $request );
    }
]);
```
