### ISSUE TITLE
Using url query strings on taxonomies?

### ISSUE THREAD

**Issue by breadadams** [WP-API/WP-API#2552]
I'm attempting the following: `/wp-json/wp/v2/my_taxonomy/?filter[posts_per_page]=-1` but I get the exact same as `/wp-json/wp/v2/my_taxonomy/`, only 10 terms, when there are over 300 in the database.

Is it not supposed to work this way? Or am I doing something wrong? 😊

**Comment by kadamwhite** [comment]
@breadadams `?filter[posts_per_page]=x` has been superseded by `?per_page=x`, so try using that top-level query parameter. That said, `-1` (if supported) can end up having performance implications—that's a lot of content to ask for all at once. The approach I'd recommend would be to make several smaller requests by paging through the response data ~100 at a time, then assemble those into one collection.

**Comment by rmccue** [comment]
As @kadamwhite notes, `per_page` is the preferred query param, and it overrides the `filter` variant, even when it's just the default value.

We lock `per_page` to an integer between 1 and 100 (inclusive) for performance reasons; you don't want anyone to be able to kill your site, e.g.
