### ISSUE TITLE
All parameters on GET are being ignored

### ISSUE THREAD

**Issue by jenkma02** [WP-API/WP-API#2555]
Any parameters I pass on a GET are being ignored/deleted every time, no matter what the parameters are.  I'm not trying to get anything that would require authorization, only `filter[posts_per_page]` or `per_page` (I've tried both).  The Link that I get in the Postman results always replaces any parameters with `q&page=2`, regardless of what I'm passing. I'm really stumped on this and haven't been able to find anyone else having remotely the same problem.  If someone here has some insight, I would definitely appreciate it!

**Comment by kadamwhite** [comment]
Can you provide any information about your server configuration or what endpoints you are querying? Thanks, this is an odd one so any additional information would help!

**Comment by jenkma02** [comment]
Thanks for your fast response! I'm not in charge of the server setup, but I do know that it's nginx, possibly with Varnish (still waiting to hear back from my server admin on that).  I've tried several endpoints and they always end with the same result. I'm using Postman and using the Link param returned in the Header to test whether it's working. 

https://mysite.com/wp-json/wp/v2/posts?per_page=4&page=3
or
https://mysite.com/wp-json/wp/v2/posts?filter[posts_per_page]=4&page=3

always returns 

https://mysite.com/wp-json/wp/v2/posts?q&page=2

Just an fyi, I thought maybe this was a plugin conflict, but I deactivated every plugin on the site except for Advanced Custom Fields and WP REST API and the same issue occurred.

**Comment by rmccue** [comment]
@jenkma02 Did you ever get a response from the server admin about this? This seems like a misbehaving cache between the client and your app server.

**Comment by rmccue** [comment]
Closing out, due to no response.
