### ISSUE TITLE
_embedded object to be used for sub-resources in collections

### ISSUE THREAD

**Issue by djodjoni** [WP-API/WP-API#2559]
Normally a HAL library will only be aware of what you put in _links and _embedded.
Currently in all collections have all the items in the root as ordinary objects and the _links are hidden inside, thus a HAL library ignores them. 

ref: http://stateless.co/hal_specification.html

**Comment by rmccue** [comment]
This is a duplicate of https://core.trac.wordpress.org/ticket/37182
