### ISSUE TITLE
instead of routes in the root use _links

### ISSUE THREAD

**Issue by djodjoni** [WP-API/WP-API#2560]
when send GET request to the main wp-json URI or to wp-json/wp/v2/
we receive routes entries where information of the available resources and methods can be seen. This however is not complete (for example json-schemas are not available) and subsequent OPTIONS request has to be made.

"routes" object can be replaced with "_links" where the elements are less and some resources/links will be naturally discoverable later after accessing higher level resources for example 
"/wp/v2/posts/(?P<parent>[\d]+)/revisions" revisions doesn't make sense without a specific post i.e. cannot be directly accessed unless bookmarked.

Essentially when one starts crawling the API using a HAL library one should be able to find all possible options and links and also corresponding schemas and arguments, without the need of an extra discoverable mechanism.

**Comment by rachelbaker** [comment]
Related Trac ticket: https://core.trac.wordpress.org/ticket/37182

**Comment by maennchen** [comment]
Allthough they have some overlap, this ticket is closer to the problem described here.

https://core.trac.wordpress.org/ticket/37179

#37182 is related to collections. (For example for a list of posts)

**Comment by jeremyzahner** [comment]
@maennchen I agree.

**Comment by djodjoni** [comment]
yep me too

**Comment by kadamwhite** [comment]
If https://core.trac.wordpress.org/ticket/37179 captures this I'm going to close this one out, since I think the implementation of this would need to be on the infra side, not the plugin side.
