### ISSUE TITLE
WP API v2 url (wp-json/wp/v2/posts) doesn't work, shows main page instead

### ISSUE THREAD

**Issue by pavelsr** [WP-API/WP-API#2561]
Plugin version: 2.0-beta13.1
Tested at Wordpress versions: 4.5.3, 4.6-alpha-37801
My server configuration: 
nginx/1.4.6 (Ubuntu), PHP 5.5.9-1ubuntu4.16 (fpm-fcgi) (built: Apr 20 2016 14:34:31)

Nginx configuration:

```
server {
    listen 80;
    server_name blog.local;
    root /home/school_blog;
    index index index.php index.html index.htm;
    client_max_body_size 30M;

    location / {
        try_files $uri $uri/ /index.php?q=$uri&$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass   unix:/var/run/php5-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(.*)$;
        fastcgi_index  index.php;
        include fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
    } 
}
```

```
pavel@pavel-Inspiron-3542:~$ cat /etc/nginx/fastcgi_params
fastcgi_param   QUERY_STRING        $query_string;
fastcgi_param   REQUEST_METHOD      $request_method;
fastcgi_param   CONTENT_TYPE        $content_type;
fastcgi_param   CONTENT_LENGTH      $content_length;
fastcgi_param   SCRIPT_FILENAME     $request_filename;
fastcgi_param   SCRIPT_NAME     $fastcgi_script_name;
fastcgi_param   REQUEST_URI     $request_uri;
fastcgi_param   DOCUMENT_URI        $document_uri;
fastcgi_param   DOCUMENT_ROOT       $document_root;
fastcgi_param   SERVER_PROTOCOL     $server_protocol;
fastcgi_param   GATEWAY_INTERFACE   CGI/1.1;
fastcgi_param   SERVER_SOFTWARE     nginx/$nginx_version;
fastcgi_param   REMOTE_ADDR     $remote_addr;
fastcgi_param   REMOTE_PORT     $remote_port;
fastcgi_param   SERVER_ADDR     $server_addr;
fastcgi_param   SERVER_PORT     $server_port;
fastcgi_param   SERVER_NAME     $server_name;
fastcgi_param   HTTPS           $https if_not_empty;
# PHP only, required if PHP was built with --enable-force-cgi-redirect
fastcgi_param   REDIRECT_STATUS     200;
```

Also I tried to run WP API v1 plugin. At my local machine it works fine! But for some reason at server **wp-json/posts** route also opened main page. However files **/etc/php5/fpm/php.ini** and **/etc/php5/fpm/pool.d/www.conf** are same at local machine and server. I'm getting crazy cause I can't find out what exactly affects to WP API plugin ... 
Checked with mysql (`SELECT * FROM wp_options WHERE option_name = 'active_plugins';`) are plugins activated correctly - and they are.

**Comment by pavelsr** [comment]
I made some testing with WP API v1 plugin and noticed very strange thing that NGINX affects to plugin behaviour. When I updated NGINX from 1.4.6 to 1.10.1 (latest version available from Ubuntu PPA)  wp-json/posts/ route failed to work and also redirects to main page.

**Comment by mckernanin** [comment]
Starting with low hanging fruit, have you tried resetting your permalink settings? Make sure they're not on the default ( which is no pretty permalinks).

**Comment by pavelsr** [comment]
@mckernanin, wow, enabling permalinks totally fixed problem for **wp-json/posts** and wp-json/wp/v2/posts routes! thank you very much! seems like I missed it in documentation :)

**Comment by mckernanin** [comment]
@pavelsr as a rule, any time you install a plugin that adds new rewrites (anything after the url, like /wp-json/) you want to flush your rewrites. This is done automatically on some hosting, but other times you just need to give it a little kick.

**Comment by marcoscurvello** [comment]
thanks 👍

**Comment by tomandersen** [comment]
Resetting our permalink settings fixed things for us. We were having trouble with Contact form 7 version 4.8. and wp-json.

**Comment by mikeres0** [comment]
This needs to go into the documentation ASAP

**Comment by TAUFEEQ1** [comment]
Just had the same problem as pavelsr. Changing permalink settings from default fixed it

**Comment by ferdousulhaque** [comment]
@TAUFEEQ1 I have changed the permalink from default to Post Name and now wp-json outputs are showing up. Thank a lot.

**Comment by giona69** [comment]
I just click save under settings/permalinks and it fixes it ... but the problem is, it happens every time when the instance restard; any idea on how to apply it automatically?
