### ISSUE TITLE
Can't add categories to a post

### ISSUE THREAD

**Issue by DarkStar1973** [WP-API/WP-API#2564]
Hi all,
i'm trying to post article with API, with python, it's work but ignore categories (post appear without category).
I have trying with ID, example:

```
def wp_post_article(wp_title, wp_slug, wp_time, wp_status, wp_content, wp_author, wp_categories):
  values = {'title':wp_title, 'slug':wp_slug, 'date':wp_time, 'status':wp_status, 'content': wp_content, 'author':wp_author, 'categories':wp_categories}
  print values
  data = urllib.urlencode(values)
  print data
  req = urllib2.Request(wp_api_url + "posts", data)
  req.add_header("Authorization", "Basic %s" % wp_auth)
  try:
    handle_wp = urlopener.open(req)
  except IOError as e:
    print "Error while trying to POST on WP: {0}".format(e)
    return False
  else:
    json_wp =  json.load(handle_wp)
    return json_wp

cats = [7, 8]
wp_post_article("this is a test", "this_is_a_test" ,"2016-01-01 00:00:00", "publish", "<h1>Hello!</h1><p>This is my test</p>", "1", cats)

```

I have tried with name, slug of categories instead of ID by same result: no category for this post.

**Comment by danielbachhuber** [comment]
> I have tried with name, slug of categories instead of ID by same result: no category for this post.

Can you share the full response you're receiving? Is it an error, or a post with incorrect categories?

**Comment by azhard4int** [comment]
@danielbachhuber Having the same problem like @DarkStar1973 .

I even tried passing the categories as a string as well as by id.

Below is the response:

<pre>
{  
   "id":385,
   "date":"2016-06-28T19:33:50",
   "date_gmt":"2016-06-28T19:33:50",
   "guid":{  
      "rendered":"URL**demo-post-for-wp-api-v2\/",
      "raw":"URL**demo-post-for-wp-api-v2\/"
   },
   "modified":"2016-06-28T19:33:50",
   "modified_gmt":"2016-06-28T19:33:50",
   "password":"",
   "slug":"demo-post-for-wp-api-v2",
   "status":"publish",
   "type":"post",
   "link":"URL**demo-post-for-wp-api-v2\/",
   "title":{  
      "raw":"Demo Post for WP API v2",
      "rendered":"Demo Post for WP API v2"
   },
   "content":{  
      "raw":"Demo post content submission",
      "rendered":"<p>Demo post content submission<\/p>\n"
   },
   "excerpt":{  
      "raw":"",
      "rendered":"<p>Demo post content submission<\/p>\n"
   },
   "author":1,
   "featured_media":364,
   "comment_status":"open",
   "ping_status":"open",
   "sticky":false,
   "format":"standard",
   "categories":[  
   ],
   "tags":[  
   ],
   "_links":{  
      "self":[  
         {  
            "href":"URL**/wp-json\/wp\/v2\/posts\/385"
         }
      ],
      "collection":[  
         {  
            "href":"URL**wp-json\/wp\/v2\/posts"
         }
      ],
      "about":[  
         {  
            "href":"URL**wp-json\/wp\/v2\/types\/post"
         }
      ],
      "author":[  
         {  
            "embeddable":true,
            "href":"URL**wp-json\/wp\/v2\/users\/1"
         }
      ],
      "replies":[  
         {  
            "embeddable":true,
            "href":"URL**wp-json\/wp\/v2\/comments?post=385"
         }
      ],
      "version-history":[  
         {  
            "href":"URL**wp-json\/wp\/v2\/posts\/385\/revisions"
         }
      ],
      "wp:featuredmedia":[  
         {  
            "embeddable":true,
            "href":"URL**wp-json\/wp\/v2\/media\/364"
         }
      ],
      "wp:attachment":[  
         {  
            "href":"URL**wp-json\/wp\/v2\/media?parent=385"
         }
      ],
      "wp:term":[  
         {  
            "taxonomy":"category",
            "embeddable":true,
            "href":"URL**/wp\/v2\/categories?post=385"
         },
         {  
            "taxonomy":"post_tag",
            "embeddable":true,
            "href":"URL**wp\/v2\/tags?post=385"
         }
      ],
      "curies":[  
         {  
            "name":"wp",
            "href":"https:\/\/api.w.org\/{rel}",
            "templated":true
         }
      ]
   }
}
</pre>

**Comment by azhard4int** [comment]
Just to add more information, I tried using Update method, the title of the post has been updated, but the categories had no effect at all.

**Comment by mthomas88** [comment]
Hey mate,

Have you tried sending an array of dicts with an "id" key rather than just the ints themselves?

Like so:
`
cats = [{"id": 7}, {"id": 8}]
`

Cheers!

**Comment by DarkStar1973** [comment]
Same result with dict :(
Post is valid but category is empty.

Code:

```
def wp_post_article(wp_title, wp_slug, wp_time, wp_status, wp_content, wp_author, wp_categories):
  values = {'title':wp_title, 'slug':wp_slug, 'date':wp_time, 'status':wp_status, 'content': wp_content, 'author':wp_author, 'categories':wp_categories}
  #print values
  data = urllib.urlencode(values)
  #print data
  req = urllib2.Request(wp_api_url + "posts", data)
  req.add_header("Authorization", "Basic %s" % wp_auth)
  try:
    handle_wp = urlopener.open(req)
  except IOError as e:
    print "Error while trying to POST on WP: {0}".format(e)
    return False
  else:
    json_wp =  json.load(handle_wp)
    return json_wp


cats = [{"id": 7}, {"id": 8}]

json_response = wp_post_article("test serge", "test_serge" ,"2016-01-01 00:00:00", "publish", "<h1>toto</h1><p>Ceci est un texte</p>", "1", cats)

print json.dumps (json_response, sort_keys=True, indent=2)

```

Response:

```

{
  "_links": {
    "about": [
      {
        "href": "http://localhost/wp-json/wp/v2/types/post"
      }
    ],
    "author": [
      {
        "embeddable": true,
        "href": "http://localhost/wp-json/wp/v2/users/1"
      }
    ],
    "collection": [
      {
        "href": "http://localhost/wp-json/wp/v2/posts"
      }
    ],
    "curies": [
      {
        "href": "https://api.w.org/{rel}",
        "name": "wp",
        "templated": true
      }
    ],
    "replies": [
      {
        "embeddable": true,
        "href": "http://localhost/wp-json/wp/v2/comments?post=81258"
      }
    ],
    "self": [
      {
        "href": "http://localhost/wp-json/wp/v2/posts/81258"
      }
    ],
    "version-history": [
      {
        "href": "http://localhost/wp-json/wp/v2/posts/81258/revisions"
      }
    ],
    "wp:attachment": [
      {
        "href": "http://localhost/wp-json/wp/v2/media?parent=81258"
      }
    ],
    "wp:term": [
      {
        "embeddable": true,
        "href": "http://localhost/wp-json/wp/v2/categories?post=81258",
        "taxonomy": "category"
      },
      {
        "embeddable": true,
        "href": "http://localhost/wp-json/wp/v2/tags?post=81258",
        "taxonomy": "post_tag"
      }
    ]
  },
  "author": 1,
  "categories": [],
  "comment_status": "open",
  "content": {
    "raw": "<h1>toto</h1><p>Ceci est un texte</p>",
    "rendered": "<h1>toto</h1>\n<p>Ceci est un texte</p>\n"
  },
  "date": "2016-01-01T02:00:00",
  "date_gmt": "2016-01-01T00:00:00",
  "excerpt": {
    "raw": "",
    "rendered": "<p>toto Ceci est un texte</p>\n"
  },
  "featured_media": 0,
  "format": "standard",
  "guid": {
    "raw": "http://localhost/test_serge-4/",
    "rendered": "http://localhost/test_serge-4/"
  },
  "id": 81258,
  "link": "http://localhost/test_serge-4/",
  "modified": "2016-01-01T02:00:00",
  "modified_gmt": "2016-01-01T00:00:00",
  "password": "",
  "ping_status": "open",
  "slug": "test_serge-4",
  "status": "publish",
  "sticky": false,
  "tags": [],
  "title": {
    "raw": "test serge",
    "rendered": "test serge"
  },
  "type": "post"
}

```

**Comment by DarkStar1973** [comment]
Ok, it's not an API bug but my python script :)
Here is the solution:

```
def wp_post_article(wp_title, wp_slug, wp_time, wp_status, wp_content, wp_author, wp_categories):
  values = {'title':wp_title, 'slug':wp_slug, 'date':wp_time, 'status':wp_status, 'content': wp_content, 'author':wp_author, 'categories[]':wp_categories}
  print values
  data = urllib.urlencode(values, True)
  print data
  req = urllib2.Request(wp_api_url + "posts", data)
  req.add_header("Authorization", "Basic %s" % wp_auth)
  try:
    handle_wp = urlopener.open(req)
  except IOError as e:
    print "Error while trying to POST on WP: {0}".format(e)
    return False
  else:
    json_wp =  json.load(handle_wp)
    return json_wp


cats = [7,8]

json_response = wp_post_article("test serge", "test_serge" ,"2016-01-01 00:00:00", "publish", "<h1>toto</h1><p>Ceci est un texte</p>", "1", cats)

```
2 warnings:
- categorie**[]**: 
- urllib.urlencode(values, **True**)
(https://docs.python.org/2/library/urllib.html#urllib.urlencode)

**Comment by DarkStar1973** [comment]
Ok, it's not an API bug but my python script :)
Here is the solution:

```
def wp_post_article(wp_title, wp_slug, wp_time, wp_status, wp_content, wp_author, wp_categories):
  values = {'title':wp_title, 'slug':wp_slug, 'date':wp_time, 'status':wp_status, 'content': wp_content, 'author':wp_author, 'categories[]':wp_categories}
  print values
  data = urllib.urlencode(values, True)
  print data
  req = urllib2.Request(wp_api_url + "posts", data)
  req.add_header("Authorization", "Basic %s" % wp_auth)
  try:
    handle_wp = urlopener.open(req)
  except IOError as e:
    print "Error while trying to POST on WP: {0}".format(e)
    return False
  else:
    json_wp =  json.load(handle_wp)
    return json_wp


cats = [7,8]

json_response = wp_post_article("test serge", "test_serge" ,"2016-01-01 00:00:00", "publish", "<h1>toto</h1><p>Ceci est un texte</p>", "1", cats)

```
2 warnings:
- categorie**[]**: 
- urllib.urlencode(values, **True**)
(https://docs.python.org/2/library/urllib.html#urllib.urlencode)

**Comment by DarkStar1973** [comment]
Ok, it's not an API bug but my python script :)
Here is the solution:

```
def wp_post_article(wp_title, wp_slug, wp_time, wp_status, wp_content, wp_author, wp_categories):
  values = {'title':wp_title, 'slug':wp_slug, 'date':wp_time, 'status':wp_status, 'content': wp_content, 'author':wp_author, 'categories[]':wp_categories}
  print values
  data = urllib.urlencode(values, True)
```
