### ISSUE TITLE
Query multiple post types at once in V2

### ISSUE THREAD

**Issue by marcbacon** [WP-API/WP-API#2567]
I am having trouble understanding how to query a list of multiple post types in V2. In V1 I did something like this to get a list of posts that contained results from multiple post types:

`http://example.com/wp-json/posts?type[]=book&type[]=movie`

In V2 it seems that we need something like this:

`http://rx-360.scorrinteractive.com/wp-json/wp/v2/book+movie`

How is this handled in V2? If this is already a feature that can accomplish this can we please have it outlined in the API reference?

Thanks!

**Comment by danielbachhuber** [comment]
> How is this handled in V2? If this is already a feature that can accomplish this can we please have it outlined in the API reference?

Because each custom post type is modeled differently, it's not possible to fetch them from the same endpoint in v2. Conceptually, it's like fetching users and posts from the same end point — it doesn't make much sense.

Eventually, we'll have a batch GET endpoint https://github.com/WP-API/WP-API/issues/1506

**Comment by marcbacon** [comment]
How does this not make sense? In WordPress I can create a post type for "movie" and another for "book" and both can share the taxonomy of "genre". Using WP_Query, I can query both of these post types in one loop. Why would the REST API for WordPress not include this basic functionality, especially as it was working in V1? Without this feature I am not going to be able to update my current web applications from V1 to V2.

Shouldn't the REST API have the same functionality as WordPress' WP_Query?

What about a global search? How could I mimic the search results in WordPress without this feature? Adding a search box to my website seems useless if I can only search posts or pages but not pages and posts...

Maybe fetching posts and users from the same endpoint may not make sense, but what about posts and pages?

Please reconsider this feature. Losing this in the transition from version 1 to version 2 is a major setback and a deal-breaker for me to use V2. This is a massive oversight and it removes a great chunk of functionality from its use.

**Comment by danielbachhuber** [comment]
> How does this not make sense? In WordPress I can create a post type for "movie" and another for "book" and both can share the taxonomy of "genre". Using WP_Query, I can query both of these post types in one loop.

Sure, but the WP REST API isn't WP_Query. The WP REST API is a higher-level abstraction on top of WordPress.

> Why would the REST API for WordPress not include this basic functionality, especially as it was working in V1?

If you search through the issue backlog a bit, there's discussion you can read through.

> Without this feature I am not going to be able to update my current web applications from V1 to V2.

You're welcome to adapt your web applications to use the new implementation, or write a custom endpoint which implements the specific feature you need.

> Please reconsider this feature. Losing this in the transition from version 1 to version 2 is a major setback and a deal-breaker for me to use V2. This is a massive oversight and it removes a great chunk of functionality from its use.

We're not going to reconsider it, unfortunately. Removing support for the feature was a deliberate decision, and not unintentionally. I'm sorry the change has caused more effort than you expected it would.

**Comment by marcbacon** [comment]
Well thanks I guess...

Could you touch on the search feature a bit? One of the major reasons that I have used the API in the past is to create an instant site search that starts to display results on keyup. Why wouldn't a search query that can search multiple post types (like posts, pages, etc.) be considered important at all?

**Comment by danielbachhuber** [comment]
> Could you touch on the search feature a bit? One of the major reasons that I have used the API in the past is to create an instant site search that starts to display results on keyup. Why wouldn't a search query that can search multiple post types (like posts, pages, etc.) be considered important at all?

This particular use case just hasn't been high on the priority list. Given a headless WordPress install likely has its own search algorithm needs too, the endpoint that returns the results seems like the easy part to implement.

**Comment by marcbacon** [comment]
I guess that makes sense. Thanks Daniel! I will get to work on some custom endpoints for my applications.

**Comment by salil-elevati** [comment]
We had a similar requirement, where we only had a slug and need to query / find the post/page/article data.
We have build a wordpress api v2 plugin to query multiple post types.
Here is the plugin code https://github.com/elevati/wp-api-multiple-posttype

**Comment by rgrandi** [comment]
@salil-elevati Hey, trying to use your plugin I get a 500 error, any ideas?

**Comment by salil-elevati** [comment]
@rgrandi Updated the documentation, need to pass parameters eg: type[]=post&type[]=page

**Comment by tedc** [comment]
@salil-elevati I'm trying your plugin but activating it gives this error: "Fatal error: Class 'WP_REST_Controller' not found "
