### ISSUE TITLE
How to get User Info based on email address

### ISSUE THREAD

**Issue by jehanzebafridi** [WP-API/WP-API#2569]
Hi, 
Is there any method for getting user info based on email address instead of user id? The documentation don't have a filter option for getting user data. 

Thanks,
Jehan

**Comment by danielbachhuber** [comment]
You can use the `email` query arg:

```
GET /wp-json/v2/users email==user@example.com
```

**Comment by kadamwhite** [comment]
@danielbachuber we probably ought to make a "needs-docs" label we can use when closing these so that we can port all this Q&A over to the docs site. Thoughts?

**Comment by danielbachhuber** [comment]
> we probably ought to make a "needs-docs" label we can use when closing these so that we can port all this Q&A over to the docs site. Thoughts?

Historically, I just look through issues labeled 'support' when looking for fodder for documentation. Or, I create an [issue in the docs repo](https://github.com/wp-api/docs-v2/issues).

More directly, I don't think we need a new labeling system so much as we need someone who wants to maintain the docs.

**Comment by BE-Webdesign** [comment]
> More directly, I don't think we need a new labeling system so much as we need someone who wants to maintain the docs.

I would love to maintain the docs. If someone can outline the responsibilities of that role, it would be helpful.  I have been wanting to shift my focus towards contributing more to the docs and a redesign of the docs site soonish.

**Comment by danielbachhuber** [comment]
> I would love to maintain the docs.

Thanks for volunteering :)

> If someone can outline the responsibilities of that role, it would be helpful. I have been wanting to shift my focus towards contributing more to the docs and a redesign of the docs site soonish.

We should chat about this sometime soon. Given the eventual integration of the endpoints into core, it might make sense at this point to orient our documentation efforts to how they'll eventually live in WordPress.org. Maybe it makes sense to now an API section into https://developer.wordpress.org/ that can accommodate our different documentation needs.
