### ISSUE TITLE
Change main API route (/wp-json/wp/v2/)

### ISSUE THREAD

**Issue by adrienlamotte** [WP-API/WP-API#2570]
Hello !

I'd love to change the main API route **/wp-json/wp/v2/** to something more simple like just **/api/**.

Any way to do that ?

Thanks for your help !

**Comment by almirbi** [comment]
Hello there,

you can change the prefix with a filter

``` php
function changeRestPrefix() {
    return "api";
}
add_filter( 'rest_url_prefix', 'changeRestPrefix');
```

This will result in `/api/wp/v2/`. 

Do not forget to save permalinks after adding the filter.

As far as I can see, it is not possible to change the namespace (wp/v2).

Cheers

**Comment by adrienlamotte** [comment]
Thanks ! That's useful. 

So, no way to hide the wp/v2 ?
Maybe with a rewrite rule ?

The best I have for the moment is a visible redirection with something like (in .htaccess) :
`RewriteRule ^api/(.*)$ /wp-json/wp/v2/$1 [R=301,NC,L]`

**Comment by kadamwhite** [comment]
It's possible this could be accomplished with a re-write rule, but hiding the wp/v2 entirely would mean that any other plugin you wanted to use which registered its own routes would be inaccessible; it is generally advisable to continue exposing the namespace to make the mapping of API client to a specific version of the namespaces resources stay consistent.

**Comment by BE-Webdesign** [comment]
I second what @kadamwhite said.  It is possible, but not really a good idea.  If you want to continue discussing here feel free to.

**Comment by adrienlamotte** [comment]
Thanks guys, i'll keep the namespace :)
