### ISSUE TITLE
Is it already in Wordpress core ?

### ISSUE THREAD

**Issue by ViktorIwan** [WP-API/WP-API#2573]
Hello, this actually a support question, tried the forum and stackexchange but no-one replied

i have clean install of wordpress.. but when i check on:
mydomain.com/wp-json/wp/v2/posts
it return : "rest_no_route" error

but when i install the plugin here: https://wordpress.org/plugins/rest-api/

it works without any problem ?

so my question is if the wp-api have been integrated with core wordpress ? or i need to install the plugin?

Thanks

**Comment by almirbi** [comment]
The core logic has been integrated, but the endpoints are still in the plugin.

Yes, you still need the plugin, it will not work without it.

Cheers
