### ISSUE TITLE
Error when making authorized call

### ISSUE THREAD

**Issue by madamedefarge** [WP-API/WP-API#2574]
I am using OAuth1 to authenticate and have been able to use Postman to successfully authenticate and make an authorized call to;-
http://mydomain/wp-json/wp/v2/users/3?context=edit

Now I am trying to do the same in Objective C from an ios app. The authenticate steps all appear to be successful. So far so good.
However, when I make an authorized call as above I get this response;-
{"code":"rest_user_cannot_view","message":"Sorry, you cannot view this resource with edit context.","data":{"status":401}}
Please can you tell me what is likely to be wrong? Is my signature not matching and hence the call is not suthorized?
If I make this call instead;-
http://mydomain/wp-json/wp/v2/users/3
I get limited information about that user as expected.

**Comment by almirbi** [comment]
Hello there,

Are you passing in the _access_token_? After you authenticate the user, you get back and _access_token_ which you should then pass on with every request in order to be authed.

Cheers

**Comment by madamedefarge** [comment]
Yes, I use the oauth token and oauth token secret passed back from the 3rd leg of the oauth access call. I create an authorization header with the following parameters;-
oauth_consumer_key, oauth_nonce, oauth_signature_method, oauth_timestamp, oauth_token, oauth_version, oauth_signature

**Comment by BE-Webdesign** [comment]
Hi @madamedefarge,

Did you get this worked out?
