### ISSUE TITLE
How to return trashed posts for non-logged users ?

### ISSUE THREAD

**Issue by adrienlamotte** [WP-API/WP-API#2575]
Hi !

I'd like to know if it was possible to return the list of posts witch are in the trash ?

I saw the function _validate_user_can_query_private_statuses_, so it looks like only logged user could do that. Any clean way to change that without editing the plugin file ? 

Cheers !

**Comment by almirbi** [comment]
Hey,

there is a filter that is executed on the argument array for WP_Query before the actual execution. You can hook into it and add _post_status_ trash.

```php
function add_trashed_to_rest_posts_query($args) {
	$args['post_status'] .= ", trash";
	return $args;
}
add_filter( 'rest_post_query', 'add_trashed_to_rest_posts_query' );
```

Cheers

**Comment by almirbi** [comment]
Hey,

There is a filter on the arguments before the WP_Query gets executed. You can hook in there and add _trash_ to _post_status_ field.

``` php
function add_trashed_to_rest_posts_query($args) {
    $args['post_status'] = "trash";
    return $args;
}
add_filter( "rest_post_query", 'add_trashed_to_rest_posts_query' );
```

Additionally, you also have to hook into the allowed query vars filter, which will cause the _post_status_ field to be dropped by default for non logged in users. You can add the _post_status_ to allowed list like this:

``` php
function allow_post_status_for_public($args) {
    $args[] = "post_status";
    return $args;
}
add_filter( 'query_vars', 'allow_post_status_for_public' );
```

Cheers

**Comment by adrienlamotte** [comment]
Thanks for you answer !

I just tried that, but now the API returns nothing (empty array). I double checked, my post is in the trash. I tried with draft, same result.

Any idea ? :)

**Comment by almirbi** [comment]
Which version of WP-API are you using? I tried this on a fresh installation with the develop branch, it worked.

Cheers

**Comment by adrienlamotte** [comment]
I'm on a pretty fresh install too :
- WP : 4.5.3
- WP-API : Version 2.0-beta13.1

I juste tried deactivate all others plugins, and just your code in my function.php... But I had no luck...

**Comment by almirbi** [comment]
Which endpoint are you using?

`GET /wp-json/wp/v2/posts/` ?

**Comment by adrienlamotte** [comment]
Yes `GET /wp-json/wp/v2/posts`.

I just tried to make a WP_Query outside of the plugin, and that's working :

```
$args = array(
    'post_type' => 'post',
    'post_status' => 'trash'
);
$the_query = new WP_Query( $args );
```

If I print_r the $args in **add_trashed_to_rest_posts_query**, here is the result : 

```
Array
(
    [author__in] => Array
        (
        )

    [author__not_in] => Array
        (
        )

    [menu_order] => 
    [offset] => 
    [order] => desc
    [orderby] => date
    [paged] => 1
    [post__in] => Array
        (
        )

    [post__not_in] => Array
        (
        )

    [posts_per_page] => 10
    [name] => 
    [post_parent__in] => 
    [post_parent__not_in] => 
    [post_status] => trash
    [s] => 
    [date_query] => Array
        (
        )

    [post_type] => post
)
```

And when I try thoses parameters outside of the plugin, that works too... Strange !

**Comment by almirbi** [comment]
I found the problem, will get back to this in a few.

EDIT: 

I forgot to include another change I did. The WP-API also checks for the _post_status_ object before including it in the response. So even if the WP_Query returns the trashed items, it gets filtered out with this

``` php
// class-wp-rest-posts-controller.php, line 156
foreach ( $query_result as $post ) {
    if ( ! $this->check_read_permission( $post ) ) {
        continue;
    }
// ...
}
```

So what you have to do is make the _trash_ post status public.

``` php
function make_trash_public() {

    global $wp_post_statuses;

    $wp_post_statuses['trash']->public = true;
    $wp_post_statuses['trash']->exclude_from_search = false;
    $wp_post_statuses['trash']->publicly_queryable = true;
}
add_action( 'init', 'make_trash_public' );
```

Keep in mind this will also make the trashed posts public on your frontend. A good idea might be to [register a custom post status](https://codex.wordpress.org/Function_Reference/register_post_status) like 'trash-custom'. If your circumstances allow this.

Last but not least, you still need to include published posts besides the trashed ones, so change this

``` php
$args['post_status'] = 'trash';
```

to

``` php
$args['post_status'] = array('trash', 'publish');
```

Cheers

**Comment by adrienlamotte** [comment]
Thanks for your help ! Looks like it's working now. :)

**Comment by stellasoft-george** [comment]
Hey,
This works great for standard posts in wordpress but I can't seem to get it to work for custom post types, is there something extra I'd have to do or am I missing something?
