### ISSUE TITLE
How can I get page previews (edited but not yet saved page content)?

### ISSUE THREAD

**Issue by claudod** [WP-API/WP-API#2576]
Hi, is it possible to get the preview of a page being edited through wp-api or a compatible plugin?

Let's say that the author is editing a page with id=13 from wp admin. Clicking on the preview button he would be opening a page with url /slug?preview_id=13&preview_nonce=8191b45e14&preview=true

Is it possible to get this preview content with wp-api? It would be nice to do this simply calling something like /wp-json/wp/v2/pages/13?preview=true

I'm able to obtain this patching WP_REST_Posts_Controller, adding the following code into get_item function, at line 242. This is very ugly and insecure, but I hope you will add this feature in a clean way in the future!

```
if (isset($request['preview']) && $request['preview'] == 'true') {
    $post = _set_preview($post);
}
```

Btw, congrats for the nice plugin!

**Comment by almirbi** [comment]
Hey there,

check out this one here https://github.com/WP-API/WP-API/issues/2575. If instead of _trash_ you do the same with _draft_, you should get _draft_ posts in the response as well.

Cheers

**Comment by rachelbaker** [comment]
Closing this, as it is a support question which is best addressed in the WordPress.org Support Forums (https://wordpress.org/support/) or the WordPress Stack Exchange (http://wordpress.stackexchange.com/).

**Comment by klihelp** [comment]
iIs there a public documentation for preview post with wp-api?
