### ISSUE TITLE
/wp-json/wp/v2/posts gives 10 posts, I need more 

### ISSUE THREAD

**Issue by mister-giga** [WP-API/WP-API#2580]
how to request more posts? I mean I need to request posts from 1-10, than 11-20, 21-30 and so on, for (click to see more posts) button

**Comment by kadamwhite** [comment]
You can use the `?page=` query parameter -- `/wp-json/wp/v2/posts?page=2` will be posts 11-20, and so on. There is also a header returned for every paginated collection that includes a link to the previous and or next pages in that collection.

**Comment by mister-giga** [comment]
Thanks kadamwhite, it is what I need!

**Comment by guicunha** [comment]
Why don't pass the pagination in atribute meta, outside posts array?

**Comment by mister-giga** [comment]
That sounds like alien language :laughing:

**Comment by yvanpinto** [comment]
If I want all posts displayed, what should I do? (I don't want pagination at all).

Thanks
