### ISSUE TITLE
Term names should be HTML unescaped

### ISSUE THREAD

**Issue by 27pchrisl** [WP-API/WP-API#2581]
Similar to #2243 term names are being returned HTML escaped, as they have been saved like that in the database.

While the API is technically returning what's in the database and that makes sense for HTML pages, it doesn't make sense for a JSON REST API that might be being called by something that doesn't even use HTML.

(This is probably a discussion topic rather than a bug).

**Comment by BE-Webdesign** [comment]
Like #2243, there is kind of a lot of debate and the leads of the project will have to weigh in on this and make a decision.

**Comment by rmccue** [comment]
Term names are HTML strings, same as post titles and post content. You can technically have a term name that is `<strong>Foo</strong> Bar`. This is the actual data type, not a display filter, so the data format returned by the API is by design.

**Comment by kadamwhite** [comment]
If you post `<strong>Foo</strong>` into a term creation form in WP-Admin, it will strip the HTML on save. Is that consistent or inconsistent with what we have established here?

**Comment by kadamwhite** [comment]
Conclusion: that is just one UI, and term names are HTML conceptually so the behavior here is consistent both with WP's internals and other related issues like the slug encoding issue linked above. No further discussion needed.
