### ISSUE TITLE
how can update(Edit) User profile of Wordpress ??

### ISSUE THREAD

**Issue by dharmeshtops** [WP-API/WP-API#2584]
when i want to update users details using 
POST /wp/v2/users/<id> method then its occurs errors like  below 

```
{
    "code": "rest_cannot_edit",
    "message": "Sorry, you are not allowed to edit resource.",
    "data":
    {
        "status": 401
    }
}
```

**Comment by almirbi** [comment]
Hello,

if you did the authentication right, adding ?context=edit should do the trick.

Cheers

**Comment by dharmeshtops** [comment]
but how to authenticate ??

**Comment by dharmeshtops** [comment]
Please Send me Authentication steps for WP Rest API V2 beta 13.0

**Comment by danielbachhuber** [comment]
See http://v2.wp-api.org/guide/authentication/
