### ISSUE TITLE
"registered_date" type is "date-time"

### ISSUE THREAD

**Issue by djodjoni** [WP-API/WP-API#2587]
the schema on ...wp/v2/users returns:

  "registered_date": {
    "description": "Registration date for the resource.",
    "type": "date-time",
    "context": [
      "edit"
    ],
    "readonly": true
  },

according to json-schema v4
 "type": "date-time" is NOT a valid type and it brakes parsers.
it should be "string" with "format":"date-time"
ref: 
http://json-schema.org/latest/json-schema-core.html#anchor8
http://json-schema.org/latest/json-schema-validation.html#anchor107

example:
  "registered_date": {
    "description": "Registration date for the resource.",
    "type": "string",
    "format": "date-time",
    "context": [
      "edit"
    ],
    "readonly": true
  },

**Comment by BE-Webdesign** [comment]
Thank you for catching this.

**Comment by djodjoni** [comment]
thx for fixing it 👍
