### ISSUE TITLE
comments collection ordering: Why is default "asc"?

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/WP-API#2588]
for `/posts` collections, the most recent articles are the first ones returned: you step back through pages to step back through time. for `/comments`, the oldest comments are shown first, as the default ordering for the comments collection is `asc`. This feels inconsistent, and I wanted to raise the question to see whether all collections should follow the same default ordering by date.

**Comment by swissspidy** [comment]
Comments on a single post are by default ordered that way, so perhaps it's because of that?

**Comment by BE-Webdesign** [comment]
I believe they are ordered `asc` by default for the reason swissspidy pointed out.  The API tries to reflect how WordPress core does things by default.  Going to close this out but we can continue discussion here, if there is a strong case against following the default.

**Comment by kadamwhite** [comment]
@be-webdesign I would like to flag this for general review by the team, as well as any interested lead devs: the reason I am not comfortable closing it summarily is that the api has also repeatedly been brought up as an opportunity to standardize things, and the context of an api is I believe different from the context of a theme.

**Comment by BE-Webdesign** [comment]
I think in addition to it being WordPress's default it makes sense for the data that a comment represents.  Comments are often a discussion and if you were to read a discussion, chronological order would make the most sense, even though it differs from posts where rev-cron makes the most sense to me.  Maybe this does not apply within the context of the API though.

**Comment by rachelbaker** [comment]
The default comment collection order should either be the default value in WP_Comment_Query `desc` OR the value of the site's `comment_order` option

**Comment by BE-Webdesign** [comment]
The only thing about using the option value is that it will lead to inconsistencies across installs, as you pointed out.  The default value of `comment_order` equates to `asc` as opposed to the default value in `WP_Comment_Query`, which is `desc`.  My vote would go towards keeping it as default `asc`.

**Comment by kadamwhite** [comment]
My POV is still that if every other top level collection returns most recent resources first, it is unintuitive that comments would behave differently -- and if WP_Comment_Query defaults to `desc` then that is my vote. As a consumer of the API, I should be able to expect paginated resources to behave consistently by default; if you think of something like Facebook, where the older comments are hidden and the newest timeline posts are shown first, I think it demonstrates that our default to showing the oldest comments first is a presentational detail rooted in the historic presentation of comments within WordPress rather than anything intrinsic to comments themselves.

**Comment by BE-Webdesign** [comment]
For something functional and presentational, like this issue tracker we are posting comments on, chronological order makes sense for collection order by default (someone who is using the API comments for presentational purposes and is not explicitly passing `order`=asc, may have weird stuff happen, if we make the switch).  It's not a super big deal to me either way and from a sort of standardized API perspective, having it match the posts resource, as you are suggesting, makes a lot of sense (and sorting by rev chronological makes a lot of sense).
