### ISSUE TITLE
do not return 'rendered' properties, only 'raw'?

### ISSUE THREAD

**Issue by sebastienbarre** [WP-API/WP-API#2589]
Is it possible _not_ to get the `rendered` content when using the `posts` endpoint? This triggers any plugin that handles shortcodes for example, potentially making additional third-party API queries for those that handle media like Flickr or Instagram. I'm only interested in the `raw` property (i.e. `content.raw`, not `content.rendered`). 
Thanks.

**Comment by BE-Webdesign** [comment]
@sebastienbarre 
You could write your own endpoint to grab only the raw content.  Basically all you would have to do is copy paste the posts endpoint, take out the references to `content.rendered`, and change the endpoint namespace.  Alternatively you could hook into `the_content` filter and remove whichever functions run `do_shortcode()` during a request by checking the `REST_REQUEST` constant.

**Comment by rachelbaker** [comment]
Closing this, as it is a support question which is best addressed in the WordPress.org Support Forums (https://wordpress.org/support/) or the WordPress Stack Exchange (http://wordpress.stackexchange.com/).
