### ISSUE TITLE
SSL and admin scheme issues

### ISSUE THREAD

**Issue by johnbillion** [WP-API/WP-API#259]
Scenario: a site where the admin area is served over SSL (via `FORCE_SSL_ADMIN`) and the front end is served over HTTP.

The intent of this, of course, is to prevent credentials being sent in plain text over HTTP.

WP-API uses `home_url()` rather than `site_url()` to build its endpoint URL. This means in the scenario above, the endpoint URL shown in RSD uses HTTP rather than HTTPS. When I go to use the API and I'm submitting my user credentials, they're being sent as plain text over HTTP! Oh noes!

The solution is for WP-API to use `site_url()` (and probably `rpc` as the `$scheme` parameter) rather than using `home_url()` in `get_json_url()`. This does mean, however, that if a site's WordPress installation is in a subdirectory then this will show up in the endpoint URL too (eg. `example.com/wordpress/wp-json`).

You'll note that the XML-RPC endpoints listed at `example.com/xmlrpc.php?rsd` all use `site_url()` rather than `home_url()`. WP-API is currently the odd one out here.

Thoughts?

Marginally related core ticket: [#28424](https://core.trac.wordpress.org/ticket/28424)

**Comment by hubdotcom** [comment]
Could this be done using the following filter? Or adding the SSL check in get_json_url()?
add_filter( 'json_url', function( $url ) {
    if ( force_ssl_admin() ){
        return set_url_scheme( $url, 'https' );
    } else {
        return $url;
    }
} );

**Comment by johnbillion** [comment]
See my second point here: https://github.com/WP-API/WP-API/issues/259#issuecomment-46256247

HTTPS can't be forced on the home URL because it can be a different domain to the admin area and may not be available over HTTPS.

**Comment by hubdotcom** [comment]
A conundrum indeed. If FORCE_SSL_ADMIN cannot be used as this applies to the site url then perhaps a new flag is needed that is relevant to the home url and therefore the JSON endpoint?

Example
The constant FORCE_SSL_JSON can be set to true to force all logins and all json sessions to happen over SSL.
>define('FORCE_SSL_JSON', true);

**Comment by danielbachhuber** [comment]
We have a `rest_url` filter where you can force SSL.

**Comment by danielbachhuber** [comment]
Addressed by https://core.trac.wordpress.org/ticket/34299
