### ISSUE TITLE
Role(s) not being set when Add or Updating a user

### ISSUE THREAD

**Issue by tripflex** [WP-API/WP-API#2592]
https://github.com/WP-API/WP-API/pull/2177

It seems the param was changed from `role` to `roles` to support multiple roles, but the merge above then sets `role` to false on `wp_update_user` call, with a label stating

> "// setting roles will be handled outside of this function."

I don't see anything in that merge regarding the handling outside of that method, so i'm not really sure if this was overlooked, or forgotten about, as my debug went through entire process without any roles being updated, and I am 100% sure the value was available in the `$request` array, even tried a single string, and CSV without any luck.

**Comment by tripflex** [comment]
Just realized it is being set in the `array_map` call, must have not seen that is was called with the `$user` class instance, so I thought it was calling standard `add_role` function.

Then add that I saw

> Accepts csv list or single role.

In http://v2.wp-api.org/reference/users/#schema-roles  .... BUT that was under list, not update/add ... then add in the fact that i'm using POSTMAN and OAuth1 to test with, so in essence I was trying to use CSV instead of POST mimicking array inputs.

BUT with that said, that doesn't solve the issue if you send a POST with single, standard `roles` item, instead of sending it as an array.  

That's as easy as typecasting it as an array, but figured I would post here about it before submitting a PR:

This:

``` php
        if ( ! empty( $request['roles'] ) ) {
            array_map( array( $user, 'add_role' ), $request['roles'] );
        }
```

To this:

``` php
        if ( ! empty( $request['roles'] ) ) {
            array_map( array( $user, 'add_role' ), (array) $request['roles'] );
        }
```

**Comment by BE-Webdesign** [comment]
This issue will be fixed when array validation is introduced to the API.  As `$request['roles']` will need to be an array to even get to this point in execution.
