### ISSUE TITLE
Extend the API to support Sites

### ISSUE THREAD

**Issue by dancrumb** [WP-API/WP-API#2593]
I would like to be able to create Sites (using Multisite WP) via this API.

Thus, I'm working on a PR to do this... watch this space...

**Comment by ocean90** [comment]
Maybe it's better to focus on the plugin instead: https://github.com/WP-API/wp-api-site-endpoints

**Comment by dancrumb** [comment]
Definitely open to that... couple of things that it would be good to clear up:
- I had no idea that existed; why is it so obscure?
- I don't see any docs for it; I can help with that
- Why is this a plugin and not part of the core?

**Comment by BE-Webdesign** [comment]
> I had no idea that existed; why is it so obscure?

Not sure but we can potentially add something to the readme.md/contributing.md of the plugin and to the docs site.

> Why is this a plugin and not part of the core?

The endpoints are still under active development and are living as plugins until they are approved for core submission.  The separate plugin branches denote different projects.  Meta, sites, themes & plugins, menus & widgets need a lot more work than the "core endpoints".
