### ISSUE TITLE
rest_forbidden for media

### ISSUE THREAD

**Issue by rafal-truszkowski** [WP-API/WP-API#2596]
I am getting the following JSON object in a response for _http://localhost/wp-json/wp/v2/posts/somePostID?_embed_

```
"wp:featuredmedia":[  
   {  
      "code":"rest_forbidden",
      "message":"You don't have permission to do this.",
      "data":{  
         "status":403
      }
   }
]
```

also, _wp-json/wp/v2/media_ is an empty array.

Is this a bug, or am I doing something wrong?

**Comment by BE-Webdesign** [comment]
What user are you authenticating as, and what capabilities do they have? At the very least it is a really bad error message.

**Comment by rachelbaker** [comment]
Perhaps this is the same issue as #2571

**Comment by rafal-truszkowski** [comment]
No authentication. I am just doing a GET, not a POST.. for SOME media posts, a simple /wp-json/wp/v2/media/6639/ returns the above. Most of media posts work fine. I can't tell what the difference between them are..

**Comment by joehoyle** [comment]
@rafalSuntimes if the attachment is attached to an unpublished post, you won't be able to read it. Is that the case here perhaps?

**Comment by petersowah** [comment]
@joehoyle Thanks. That solved it in my case.

**Comment by rmccue** [comment]
Closing out, no response from the reporter in a month.

**Comment by drewhallett** [comment]
This issue is still happening with public, published posts. On my site everything is published and public. 

The 403 error when accessing certain media is seemingly random.

**Comment by kadamwhite** [comment]
@drewhallett Can you open a ticket on the WordPress support forums (at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api") or bug tracker (at https://core.trac.wordpress.org)? This repository's issues are unfortunately no longer being tracked

**Comment by woodcipher** [comment]
We are experiencing this bug as well; if a bug has been filed, can you post a link to it here so that we can follow it?

**Comment by Werewolve** [comment]
I discovered this randomly appearing bug too. 403 error when accessing media of some public published posts. Any news on this topic?

**Comment by venanciorodrigo** [comment]
Same issue here:
![bug](https://cloud.githubusercontent.com/assets/5682455/25417815/4e216186-2a1d-11e7-9969-cfae974f3543.png)

URL on my local environment: `wp-json/wp/v2/posts?_embed&categories=1`

**Comment by venanciorodrigo** [comment]
There is something weird related to the issue. I've uploaded a featured media on the "Pages" page, after that, I create a new post and pick up the same image uploaded on the "Pages" page. It causes the error that I posted above. But if you create a new post and upload a new image it works fine.

**Comment by elyobo** [comment]
Yeah, seeing the same problem here.  Public post, still not letting the media embed, but it seems to work fine most of the time.

**Comment by Paul424** [comment]
Same issue here:

    {
"code": "rest_forbidden",
"message": "Sorry, you are not allowed to do that.",
"data": {
"status": 403
}
}

What role is required at minimum to access media? Seems that when i get all media i also see a subset?

Update: Seems to be related to WP Offload S3 Lite plugin that has not yet uploaded these images....

**Comment by netdelight** [comment]
Okay, based on what I've seen in the DB, I have more input regarding this evil issue.
Actually, a media is indexed in the posts table and have only one post_parent, **even if it's featured in other posts**. I assume this `post_parent` is the first post the media was linked to. So this parent is the post that must be public, no matter the status of the other posts.
Here's the query to know if the parent post of your file is public : 
```SELECT child.ID AS child_ID, parent.ID AS parent_ID, child.guid AS featuredmedia, child.post_status AS child_status, parent.post_status AS parent_status FROM `wp_posts` child JOIN `wp_posts` parent ON (child.post_parent = parent.ID) WHERE child.post_type = 'attachment' ```

A workaround if your media is related to a `private` parent is to switch its `post_status` from `inherit` to `publish`.

Hope this helps.

**Comment by stefanledin** [comment]
I just experienced the same issue. The image was originally uploaded as a featured image to a post which has been set to draft since then. This caused the image to not showing up in the API when used as featured image for a newer post.

**Comment by elyobo** [comment]
@rmccue can we reopen?  There are plenty here that _are_ seeing this and it seems like a cause has been identified as well.

I'm seeing exactly the same thing; a featured image was uploaded with a post, then reused as the featured image on another post and the original post was moved to the trash.  The REST API refuses to embed the featured image correctly on the new post.

Somewhat related: https://core.trac.wordpress.org/ticket/30691

**Comment by rmccue** [comment]
This repo is no longer used for tracking issues. If you're still experiencing this issue, please file it on Trac, or comment on an existing issue there.

**Comment by elyobo** [comment]
Thanks, will do.  I've commented on that issue but that's not really the core focus of it, so I'll open another.

**Comment by elyobo** [comment]
Added as https://core.trac.wordpress.org/ticket/41445 if anyone else with the same issue wants to track progress on a fix.

**Comment by riobahtiar** [comment]
Hii All.. Any update for this issue.. because i get same issue.. 😢

**Comment by VictorPurMar** [comment]
Same here. I found this issue today after 1700 posts without any problem.

**Comment by VictorPurMar** [comment]
I found a solution for my case:

Its related with the media name (url) and and the special chars.
In my case was a jpg error. Some images make this error:

After a while i discover that is about the name of the pic, in my case:

PeñaNieto.jpg

The "ñ" and other special chars, could cause this error.

**Comment by elyobo** [comment]
Glad that worked for you @VictorPurMar, looks like you've found another cause for the problem.

There has been no progress on fixing the underlying issues covered in these reports

* https://core.trac.wordpress.org/ticket/41445
* https://core.trac.wordpress.org/ticket/30691

**Comment by StuartFeldt** [comment]
A patch has been submitted here: https://core.trac.wordpress.org/ticket/41445

**Comment by elyobo** [comment]
Thanks @StuartFeldt, nice to finally have a fix for this.

**Comment by besrabasant** [comment]
> I found a solution for my case:
> 
> Its related with the media name (url) and and the special chars.
> In my case was a jpg error. Some images make this error:
> 
> After a while i discover that is about the name of the pic, in my case:
> 
> PeñaNieto.jpg
> 
> The "ñ" and other special chars, could cause this error.

@VictorPurMar I agree with you. I had _underscores_ and _dashes_ in the image name. removed them and re-uploaded the image. Now its working fine.

**Comment by bengongon97** [comment]
Uh guys sorry but 

> I found a solution for my case:
> 
> Its related with the media name (url) and and the special chars.
> In my case was a jpg error. Some images make this error:
> 
> After a while i discover that is about the name of the pic, in my case:
> 
> PeñaNieto.jpg
> 
> The "ñ" and other special chars, could cause this error.

Uh this is not the one that works, sorry. It is a very strange issue. I own the site "muharrir.net" which is a Turkish website. It hosts many Turkish-character-including names of images. We are developing an Android app for it and today suddenly we experience the crash. We were OMG-ed and tried the resolve the issue. The fastest workaround we could come up with was surrounding the processing code with:

if (code == null || !code.equals("rest_forbidden")) { //java code to process }

Plus, see the uploaded images. Both contains Turkish-specific characters like "ı" and/or "ş". "ŞU TARAFA DOĞRU" has no errors or crashes, I get the images perfectly. No code or error returns.

But the latest post that caused our app to crash has the issue. It has "ı"s all over. But I don't see any difference in both. Both contain non-ASCII characters anyway. It really looks like a random issue to me. Just FYI.

![whatsapp image 2018-09-19 at 22 57 41](https://user-images.githubusercontent.com/40887002/45778146-7d4ed200-bc60-11e8-8718-9f2c2546276c.jpeg)
![whatsapp image 2018-09-19 at 22 58 08](https://user-images.githubusercontent.com/40887002/45778147-7d4ed200-bc60-11e8-818a-a45ff9803f6e.jpeg)

**Comment by elyobo** [comment]
@besrabasant the hashes and dashes are a red herring, it was the reuploading that fixed it for you - as described above, the problem is related to the permissions of the post it was originally uploaded against, uploading again to a different post will resolve the problem.

The underlying problem was identified and raised as [an issue in WP's trac](https://core.trac.wordpress.org/ticket/41445) more than a year ago now, with a patch now available (but @StuartFeldt has not responded to the comments on the patch there yet) but not yet merged.
