### ISSUE TITLE
PHP Notice:  Undefined variable: test_root when trying to run tests

### ISSUE THREAD

**Issue by dancrumb** [WP-API/WP-API#2597]
I'm trying to run `phpunit` by following the directions in CONTRIBUTING.md, but I keep seeing:

```
PHP Notice:  Undefined variable: test_root in /Users/danrumney/Projects/WP-API/tests/bootstrap.php on line 32
```

Any guidance on getting that resolved - PHP isn't a language that I'm most experienced with, but I would generally expect that getting up and running would be documented in CONTRIBUTING (and I'm happy to beef that up.

BTW: I did already run `$ ./bin/install-wp-tests.sh wordpress_test root testpwd`

**Comment by BE-Webdesign** [comment]
Hi @dancrumb,

You will need a WP_DEVELOP_DIR set in your environment or have WordPress trunk as an adjacent directory to the WordPress install that you are running. [Here is trunk which you would need to svn checkout](https://core.trac.wordpress.org/browser#trunk/src)
