### ISSUE TITLE
post.comments contains comments that does not belong to the post

### ISSUE THREAD

**Issue by exzhawk** [WP-API/WP-API#2598]
url: /wp-json/wp/v2/posts
An array of posts is returned. But weird thing is, every post has "comments" field, which is not defined in documention http://v2.wp-api.org/reference/posts/
And comments in "comments" field does not belong to this post. I can't see any meaning of these random comments

**Comment by BE-Webdesign** [comment]
Hi! Thank you for using the WP REST API.

Could you provide a sample request and response that you are sending.  I don't believe there is a comments field at all by default.  Comments are linked to in `_links` as `replies`.  Do you have any other plugins activated that are potentially modifying the response?

**Comment by exzhawk** [comment]
Oh, I just found that it's the theme who modified response. I disabled other plugins before the test but forgot the theme.
Thank you for quick response and great work on this lovely API!
