### ISSUE TITLE
create user with rest

### ISSUE THREAD

**Issue by LeonardD93** [WP-API/WP-API#2599]
Hi I try to create an user with REST so i download WP REST API and WP REST API - OAuth 1.0a Server
i follow this [guide](http://v2.wp-api.org/guide/authentication/) and i  create a client with [this](https://github.com/WP-API/api-console). When i use GET method it work but when i try to create a new user the response is that :"{"code":"rest_cannot_create_user","message":"Sorry, you are not allowed to create resource.","data":{"status":401}}"  I don't understand why

**Comment by rachelbaker** [comment]
To create a user, you have to have the `create_users` permission.  See: https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-users-controller.php#L267

**Comment by LeonardD93** [comment]
Thanks for the answer but i have root permission so i think that isn't the answer to my question... I don't find no one guide that explains how to use POST method in wordpress with OAuth autentication

**Comment by BE-Webdesign** [comment]
Hi @LeonardD93,

The 401 error code signifies that you are not authenticating with the API.  Can you break down the steps you've taken and provide a sample request. It is possible you are missing one of the steps in using OAuth. I recommend using the [example client](https://github.com/WP-API/example-client) for testing purposes and for the introduction phase to using OAuth with the WP REST API.

**Comment by LeonardD93** [comment]
i try with this example and authentication work but when i try to change code to create my POST method don't work; for example i create an other file in the same folder called create-user.php and i print this code

`<form action="http://localhost/wordpress/wp-json/wp/v2/users" method="POST">
        <h2>Create New user</h2>
    <input type="hidden" name="step" value="discover" />
    <p>
        <label>
            Username:
            <input type="text" name="username" class="username" required />       
        </label>
        <label>
            Password:
            <input type="text" name="password" class="password" required />    
        </label>
         <label>
            Email:
            <input type="text" name="email" class="email" required />    
        </label> 
        <button type="submit">Crea Utente</button>
    </p>
</form>`

in index.php i change  the return in step 4 (line140) with this 

return output_page( load_template( 'create-user' ) );
