### ISSUE TITLE
Get request on media gives blank array

### ISSUE THREAD

**Issue by vjatinl** [WP-API/WP-API#2600]
e.g. wp-json/wp/v2/media?parent=28806 gives blank array though there is attached image is there..

**Comment by vjatinl** [comment]
Hi,

I want share a case for which these kind of error occurs.

Cause Case : Consider I have create a post with one media file. Now few days latter I am creating another post but it's using same media file as I used for earlier post.

Now for above mentioned case media element only hold reference of first post from which I have uploaded media. So, media parent only works for first post not for second one or latter any post which refers same media file (in Json response).

**Comment by ph0bos** [comment]
+1 on this issue.

**Comment by rachelbaker** [comment]
@vjatinl This is a design issue within WordPress.  Attachments can only have one parent post.  Closing as this is not an issue with the API endpoints themselves.
