### ISSUE TITLE
How to list all users with administrator roles?

### ISSUE THREAD

**Issue by azhard4int** [WP-API/WP-API#2601]
Hi,

Trying to pull of the list of all users that are administrator on our website, but we are getting only one single Administrator account.

In order to do so, do we need to perform the authentication or there is some other way around?

Currently, we are sending a request to: domain.com/wp-json/wp/v2/users and it is only showing one account from our website.

**Comment by BE-Webdesign** [comment]
Hi @azhard4int,

> Currently, we are sending a request to: domain.com/wp-json/wp/v2/users and it is only showing one account from our website.

Without authentication you will see only the users who have authored public published posts.  If you have one user account that is assigned the author of your posts, then only they will show up.  If you wanted to see the other accounts you would need to authenticate as an administrator or a user who can list users.

I am going to close the issue, but feel free to continue discussion here.
