### ISSUE TITLE
Not all the data is reported..

### ISSUE THREAD

**Issue by danysz** [WP-API/WP-API#2603]
I have a WP latest version.
WP also latest.
Added REST enabler 
Added All-in-One Event Calendar by Time.ly
Now I can get the event details using the REST API.
What is missing : 
If I add an event with "repeated" the "repetition" data is missing: 

```
[
  {
    "id": 10,
    "date": "2016-07-18T15:49:47",
    "date_gmt": "2016-07-18T12:49:47",
    "guid": {
      "rendered": "http://wp.scop-sys.info/?post_type=ai1ec_event&#038;p=10"
    },
    "modified": "2016-07-18T15:49:47",
    "modified_gmt": "2016-07-18T12:49:47",
    "slug": "event-number-1",
    "type": "ai1ec_event",
    "link": "http://wp.scop-sys.info/event/event-number-1/",
    "title": {
      "rendered": "event number 1"
    },
    "content": {
      "rendered": ""
    },
    "author": 1,
    "featured_media": 0,
    "comment_status": "open",
    "ping_status": "closed",
    "_links": {
      "self": [
        {
          "href": "http://wp.scop-sys.info/wp-json/wp/v2/events/10"
        }
      ],
      "collection": [
        {
          "href": "http://wp.scop-sys.info/wp-json/wp/v2/events"
        }
      ],
      "about": [
        {
          "href": "http://wp.scop-sys.info/wp-json/wp/v2/types/ai1ec_event"
        }
      ],
      "author": [
        {
          "embeddable": true,
          "href": "http://wp.scop-sys.info/wp-json/wp/v2/users/1"
        }
      ],
      "replies": [
        {
          "embeddable": true,
          "href": "http://wp.scop-sys.info/wp-json/wp/v2/comments?post=10"
        }
      ],
      "wp:attachment": [
        {
          "href": "http://wp.scop-sys.info/wp-json/wp/v2/media?parent=10"
        }
      ],
      "curies": [
        {
          "name": "wp",
          "href": "https://api.w.org/{rel}",
          "templated": true
        }
      ]
    }
  }
]
```

>  Repeat:  
> Weekly on Friday for 4 occurrences 

I found that also the location data is missing...

**Comment by BE-Webdesign** [comment]
Hi @danysz,

Events is not a standard post type that ships with WordPress core.  If you need additional information not provided in the base responses, then you would need to create your own endpoint or find a plugin that adds special endpoints for All-in-One event calendar.  The best method would probably be to extend `WP_REST_Posts_Controller()` so you modify the functionality to fit your needs.  Another less complicate, route is to use `register_rest_field()`, [which is documented here](http://v2.wp-api.org/extending/modifying/). Going to close this issue but feel free to continue discussion here.
