### ISSUE TITLE
template php files are listed in the request 

### ISSUE THREAD

**Issue by eddr** [WP-API/WP-API#2604]
Hi
1. Please try Get on "http://www.green.org.il/wp-json"
2. Latest WP version
3. Plugins in use : WP REST API, WP REST API - OAuth 1.0a Server. 
4. Rest related plugins that were in use at some point: WP REST API Controller, ACF to REST API

More info:
- I'm not sure how I came to that. I was not able to reproduce that issue on a freshly installed WP with the same REST plugins
- Currently, it happens even if I disable all plugins except the first two (in (3))

It seems like some kind of information is stored and has some affect.

Let me know what more info is needed

**Comment by BE-Webdesign** [comment]
Can you show what the response looks like?

> It seems like some kind of information is stored and has some affect.

Probably this, if it is not happening on a fresh install.  Most likely the additional plugins in number 4 are the culprits.  The responses on http://www.green.org.il/wp-json/wp/v2/posts are not returning valid JSON, so something has run amuck in your install. It is most likely caused by the additional plugins.

**Comment by eddr** [comment]
You can see the response here
https://drive.google.com/open?id=1757t7DyETyzEBeJuXLYzjTXieKcl8GSOcgv7pJHPNpQ

Why do you say the JSON is not good? it is validated on http://jsonlint.com/ - but maybe this tool is not good enough

**Comment by BE-Webdesign** [comment]
> Why do you say the JSON is not good

I typed the wrong link meant to put in posts endpoint.  I edited the above comment.

**Comment by eddr** [comment]
Yea. Would be a problem to check it now. I guess I'll have to track it down via the source code. If it happened in my short games with these plugins, it could happen to others as well
