### ISSUE TITLE
Unable to restrict comments to a specific post id using wordpress api v2

### ISSUE THREAD

**Issue by sktzofrenic** [WP-API/WP-API#2610]
making the following request returns every single comment from the blog. It is not restricted to the post ID in the query parameters.

Is this a bug, or am I doing something wrong?

`http://anawins.com/wp-json/wp/v2/comments/?post=2986`
or

`http://anawins.com/wp-json/wp/v2/comments?post=2986`
yields:

```
HTTP/1.1 200 OK
Server: nginx/1.6.3
Date: Sat, 23 Jul 2016 15:47:47 GMT
Content-Type: application/json; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
X-Powered-By: PHP/5.4.16
Vary: Cookie
Set-Cookie: PHPSESSID=96jsfcdeg8ksnraq5aa3o1a3o7; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: oculus-unknown-switcher=1; expires=Sun, 23-Jul-2017 15:47:46 GMT
Set-Cookie: oculus-unknown-switcher=1; expires=Sun, 23-Jul-2017 15:47:46 GMT
Set-Cookie: wp_woocommerce_session_d65537f626aa4d41876f80145673898a=a4bbe5c1e08f80685e3bf383595f1ce4%7C%7C1469461666%7C%7C1469458066%7C%7C92bf547bd7e641385bb561b739e1c87a; expires=Mon, 25-Jul-2016 15:47:46 GMT; path=/
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
Access-Control-Allow-Headers: Authorization
X-WP-Total: 2549
X-WP-TotalPages: 255
Link: <http://anawins.com/wp-json/wp/v2/comments?q=%2Fwp-json%2Fwp%2Fv2%2Fcomments%2F%3Fpost%3D2986&context=view&page=2>; rel="next"
Allow: GET
```

Notice how 2500 comments are coming back, even with that post ID. Should only be five comments.

**Comment by rachelbaker** [comment]
@sktzofrenic `http://anawins.com/wp-json/wp/v2/comments?post=2986` should work.  I couldn't get your server to understand any query parameter I added.  Either there is a configuration issue with your server or a plugin hook is causing this.

**Comment by sktzofrenic** [comment]
Can you tell me a combination of wp-api and wordpress versions that are known to work together properly?

I deleted every plugin and still it did not work

**Comment by sktzofrenic** [comment]
Rachel, I looked into my server setup, and it was an NGINX issue. 

I changed:

```
        location / {
        index index.php;
        try_files $uri $uri/ /index.php?q=$request_uri;
        }
```

to:

```
        location / {
        index index.php;
        try_files $uri $uri/ /index.php?$args;
        }
```

and now it works.
