### ISSUE TITLE
Generic Error when Username or Email Already Already Registered

### ISSUE THREAD

**Issue by tristankelley** [WP-API/WP-API#2612]
Hi - First of all, thank you for the wonderful API. It has already saved me many hours of work. 

While running some testing creating new users I found that if the username or email is already registered is error response is the generic 401. If you try to register with a username already in use you get the same response as if you try to register with an email address already in use.

```
"code":"rest_cannot_create_user",
"message":"Sorry, you are not allowed to create resource.",
"data":{
"status":401
}
```

Is there a more specific error message I am missing somewhere? I would like to be able to inform the user if a) the username they picked is already taken or b) they already registered with their email and just need to log in. Right now from what I can find the response is too generic to easily differentiate between the two. 

Thanks!

**Comment by dannyb195** [comment]
when trying to register a new user with an email that is already claimed by another user in Core (i.e. _not_ using the API) the response is `ERROR: This email is already registered, please choose another one.` - this would seem to be appropriate here.

**Comment by tristankelley** [comment]
Ahh! Turns out that during my testing a got logged in as one of the users. When logged out the proper error messages are shown.  Sorry about the confusion. Thanks for the help!
