### ISSUE TITLE
author_exclude on list posts does not work

### ISSUE THREAD

**Issue by devotox** [WP-API/WP-API#2613]
Go to url https://demo.wp-api.org/wp-json/wp/v2/posts?filter[author_exclude]=1

this still shows posts from that author

**Comment by websupporter** [comment]
https://demo.wp-api.org/wp-json/wp/v2/posts?author_exclude=1
or
https://demo.wp-api.org/wp-json/wp/v2/posts?filter[author__not_in][]=1

would work.

**Comment by devotox** [comment]
should any of this work on beta 8.1 as i see the updated version is beta 13.1 at the moment?
