### ISSUE TITLE
Can we retrieve data from ANY plugin?

### ISSUE THREAD

**Issue by KaiP-598** [WP-API/WP-API#2614]
Hi!!

currently I am building a website that uses the Booked plugin to allow bookings , I will also build an iOS app, therefore the iOS app will need to get the appointment data so the user can check their bookings, and perhaps make bookings in the iOS app. 
However I've done a bit of search and there seems to be nobody has discussed about this yet, so is there a way I can do the above?

Website of the app (https://boxystudio.ticksy.com/articles/7827/)

**Comment by BE-Webdesign** [comment]
Hi KaiP-598 you would need to write your own endpoints to retrieve the appointment data from the plugin.  Check out this [guide about adding endpoints to the WP REST API](http://v2.wp-api.org/extending/adding/)
