### ISSUE TITLE
Sample CURL requests returning 301

### ISSUE THREAD

**Issue by Jonic** [WP-API/WP-API#2618]
I tried to ping `curl http://demo.wp-api.org/wp-json/wp/v2/pages/1` and got the following:

`````` <html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>CloudFront</center>
</body>
</html>```

Where have the example endpoints moved to?
``````

**Comment by rmccue** [comment]
The Location header will tell you where to get the endpoints from; `https` is required.

**Comment by Jonic** [comment]
Well is it worth updating the docs to https then?
