### ISSUE TITLE
Results should be recursive when setting 'parent' - or at least have a recursive option

### ISSUE THREAD

**Issue by danielharrison** [WP-API/WP-API#2619]
Currently searching pages without the 'parent' argument gives me **all** pages, which is fine.

Adding the 'parent' argument (eg ?parent=4) will **only** give me the direct children of that parent page, and not any grand-children pages (or deeper).

Is it possible to return a complete list of nested results, starting at the parent, or maybe provide a new argument which we can define the nesting level?

**Comment by BE-Webdesign** [comment]
Probably the best thing you can do is handle the nesting yourself in your app.  A starter method would be to make a request like `GET https://www.nest-example.com/wp-jons/wp/v2/pages?parent=4`.  This will return the child objects for the page with ID = 4.  You can then loop through that collection and run request's on `GET wp/v2/pages?parent={$child-page-id}`.  If a collection is returned you now have grandchildren pages.  You can do this recursively to get all children.  To implement this best you would want to create an endpoint and run everything internally in PHP using something like `rest_do_request()`, so you are avoiding making many HTTP requests.
