### ISSUE TITLE
Querying for posts by a parent category doesn't return posts from the category's children

### ISSUE THREAD

**Issue by epicallan** [WP-API/WP-API#2620]
Assuming a category with an id of 3 is a parent category with children, is it possible to get posts whose categories are children of that parent category.

```
http://localhost:3000/wp-json/wp/v2/posts?categories=3
```

**Comment by BE-Webdesign** [comment]
Hi @epicallan,

Thank you for using the WP REST API.  The best method is to create your own endpoint and run the requests internally in PHP.  In the links wp:post_type for categories will be the collection of posts for that category but they are not embeddable.  You can create an endpoint to grab something like `GET wp-json/wp/v2/categories?parent=3` using `rest_do_request()` from there you can use the wp:post_type links and run those through `rest_do_request()` as well to be returned the collection of posts.

Alternatively you can use the `rest_prepare_{$this->taxonomy}` filter to add in embeddable links for the collections.  If you add in the embeddable links yourself you can just run `GET wp-json/wp/v2/categories?parent={desired parent category}` and embedded in the response will be a collection of posts for the child category.

Going to close issue out but feel free to continue discussion here.
