### ISSUE TITLE
How to add parameter to existed endpoint

### ISSUE THREAD

**Issue by exzhawk** [WP-API/WP-API#2622]
I want to retrieve post by tag slug. So rather than GET post?tags=idOfTag, I want to use something like GET post?tag_slug=SlugOfTag. I know how to add a new standalone endpoint but how to add a new parameter like this to an existed endpoint?

**Comment by exzhawk** [comment]
A workaround to my request, retrieve post by tag slug, can be using WP Query by passing filter parameter. But i'm still wondering if it's possible to add parameter to existed endpoint.

**Comment by BE-Webdesign** [comment]
Hi @exzhawk,

Thank you for using the WP REST API.  At this time collection parameters are fixed per endpoint and are not extensible.  The filter param can be used as somewhat of a fill in for `WP_Query` and that is probably the easiest solution for your problem.  Alternatively, you would need to write your own endpoint and specify what you need in `get_collection_params()`.
