### ISSUE TITLE
/wp-json/wp/v2/ redirects to homepage

### ISSUE THREAD

**Issue by hoavnd** [WP-API/WP-API#2623]
Hi guys
Does anyone experience with the issue that [domain_name]/wp-json/wp/v2/ redirecting to homepage? I've tried with v2.0-beta10 to v2.0-beta13.1 but got the same problem.
Thanks

**Comment by websupporter** [comment]
Well, I haven't, but just some thoughts, which came in my mind:
- Did you try to update your permalinks ( Settings > Permalinks )?
- Do you have something extraordinary in your `.htaccess`
- Other plugins which might interfer?

Thanks for using the Rest API :)

**Comment by BE-Webdesign** [comment]
Hi @hoavnd,

Thank you for using the WP REST API.  There is a rewrite rule somewhere in your configuration that is redirecting you to the homepage.  [Rewrite Rules Inspector](https://wordpress.org/plugins/rewrite-rules-inspector/) can help save some time tracking it down.

**Comment by jerry-shao** [comment]
I got the same issue when I using the default permalink style.

My solution:
1. Setting -> Permalink
2. Pick the second format.(Date format)
3. Save changes

**Comment by hoavnd** [comment]
@jerry-shao's solution works for me. Thanks heap!

**Comment by BE-Webdesign** [comment]
For anyone who may come across this issue, essentially you need to flush your permalinks and have some form of pretty permalinks enabled to use the API the way it is intended.  Following the instructions above will work, but you can also select any of the other formats like post name etc.
