### ISSUE TITLE
Custom endroute with default schema, best way to go?

### ISSUE THREAD

**Issue by MarioFromBelgium** [WP-API/WP-API#2625]
Hi,

I have a working custom end-route that accepts longitude and latitude data. The end-route's callback function searches for the posts nearest to the given location.
Today the callback function returns a custom array containing different fields of these nearest posts. 
(All this is working perfectly)
However I want my callback function to return the default schema that a default /wp/v2/posts end-route would return.

Before going into details I would like to know what, in general, would be the best way to go. To me it seems there are two ways to do this :

In my custom class that extends WP_REST_Posts_Controller 
Option 1°  I could paste the get_Items function and alter this function.
Option 2°  I could alter my existing function so that it returns the default schema for posts
Maybe there are more/better ways?

I have tried both ways without success so I'm doing something wrong. As soon as somebody can tell me what the best option would be I would like to go into more detail.

Regards,
Mario

**Comment by BE-Webdesign** [comment]
Hi @MarioFromBelgium,

Thank you for using the WP REST API.  Can you provide a bit more information regarding how you are passing in longitude and latitude data, how it is filtering and how that is stored for your custom post type?

If you have a controller class already extending WP_REST_Posts_Controller, you can call parent::prepare_item_for_response() and parent::get_item_schema() in certain places to access the default response creation and schema for the posts controller.

I am going to close issue but feel free to continue discussion here.

**Comment by MarioFromBelgium** [comment]
Thx @BE-Webdesign ,

I created a custom endroute like this : 
http://mydomain/wp-json/my-namespace/posts/lat=(?P<lat>[+-]?[\d.]+)&lng=(?P<long>[+-]?[\d.]+)&dst=(?P<distance>\d+)

My current custom callbackfunction returns an array with the 10 nearest posts each containing an array with a few fields(title, excerpt etc..). Every post (they are not custom posts) has two custom fields lat/long.

I will check prepare_item_for_response() and parent::get_item_schema().

Although I would have thought the easiest and most logic way to do this was just call get_items right after setting the posts_in or include item in the request object?
