### ISSUE TITLE
Login as guest from mobile app

### ISSUE THREAD

**Issue by PudyJapan** [WP-API/WP-API#2631]
Hi,

I want to connect my mobile app to my wordpress site, and I think WP-API is the best. I have 2 main requirements
1) Be able to login as guest (create a guest account linked to installation id)
2) Login/sign up using google or facebook.
Number 2 is not a major issue and I created a thread about it here.
https://wordpress.org/support/topic/login-with-google-or-facebook-from-mobile-app?replies=1#post-8702001

But how to make Number 1 work?
Can I use app password to login as admin from inside the app and create the user using POST and user end point?
I think it is too risky because the admin password might be stolen.

Any help is greatly appreciated.

**Comment by rmccue** [comment]
The API only exposes functionality in WordPress, and this is not a feature of WordPress. You'll need to use a plugin to add this functionality to both WordPress and the REST API.
