### ISSUE TITLE
post comment as logged in user can't fill/get right author info

### ISSUE THREAD

**Issue by exzhawk** [WP-API/WP-API#2632]
Auth by cookie(on the site
POST /wp/v2/comments with data 

``` json
{
  "author": 1,
  "author_name": "Epix",
  "author_url": "",
  "content": "test",
  "post": "6"
}
```

Post is successful and get comment id 42. Name and avatar is correct in dashboard - comments
GET  /wp/v2/comments/42

``` json
{
  "id": 42,
  "post": 6,
  "parent": 0,
  "author": 1,
  "author_name": "Epix",
  "author_url": "",
  "content": {
    "rendered": "<p>test</p>\n"
  },
  "author_avatar_urls": {
    "24": "http://0.gravatar.com/avatar/?s=24&d=mm&r=g",
    "48": "http://0.gravatar.com/avatar/?s=48&d=mm&r=g",
    "96": "http://0.gravatar.com/avatar/?s=96&d=mm&r=g"
  },
...
}
```

Note that the author_avatar_urls are wrong.

I didn't post data with author_email as think it's not supposed to. Author id should provide enough information for author info of this comment. The author_name and other info should be filled automatically when posting the comment or retrieving the comment.

**Comment by exzhawk** [comment]
I think i found the problem. 
https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-comments-controller.php#L329
Only check if ALL author info is missing and set it to logged user. In my case, I just send author_name but no author_email, so logged user info are not set.
I think the behavior should change to, set author if the user is logged in and comment info is not VALID.
While the WP-API returns the wrong author_avatar due to empty author_email, the dashboard gives correct avatar even there is no email. I don't know how it works but it is more robust.

**Comment by BE-Webdesign** [comment]
Hi @exzhawk,

Thank you for using the WP REST API.

Check out #2049. This might take care of a lot of your concerns.

> the dashboard gives correct avatar even there is no email

With the avatar urls maybe we should go by ID if the email is not present so users without emails can still have the correct avatars.  Is that what you are suggesting?

**Comment by exzhawk** [comment]
Seems #2049 covered comment posting problems.
Yes. I suggest that avatar urls can be retrieved by existed user ID if email is not present.
Even if empty email is not caused by WP-API, this can improve robustness.

**Comment by kadamwhite** [comment]
> we should go by ID if the email is not present so users without emails can still have the correct avatars

+1

**Comment by krogsgard** [comment]
`get_avatar()` accepts ID or email. Worth exploring a more thorough check here imo.

**Comment by rmccue** [comment]
@rachelbaker Can you clarify if this is a bug or enhancement, and whether it should even be open? :)

**Comment by rachelbaker** [comment]
@rmccue confirming this is a bug in the current logic.
