### ISSUE TITLE
Include protected statuses by default when querying posts 

### ISSUE THREAD

**Issue by bartram** [WP-API/WP-API#2634]
The [documentation](https://codex.wordpress.org/Class_Reference/WP_Query#Status_Parameters) for the `post_status` argument of WP_Query states:

> Default value is 'publish', but if the user is logged in, 'private' is added. Public custom statuses are also included by default. And **if the query is run in an admin context (administration area or AJAX call)**, protected statuses are added too. By default protected statuses are 'future', 'draft' and 'pending'.

Since REST APIs don't distinguish between an admin context and a non-admin context, I believe the correct default behavior should be to return all posts with protected status (e.g. `publish`, `future`, `draft` and `pending`). Since `WP_REST_Posts_Controller::get_items` includes a call to `check_read_permission` for each post, this change would not allow users to view posts that they shouldn't- it would simply bring WP-API in line with WP's AJAX behavior.

**Comment by kadamwhite** [comment]
I support this, remembering to supply the right status or even `context=edit` has been very confusing to me while developing against the API; if I'm logged in, I'd expect to see all posts I'd normally see when logged in.

**Comment by krogsgard** [comment]
My concern with this is that it causes every front-end query w/ the REST API to have to exclude protected statuses, if they are on by default. That goes pretty well against the way default WP_Query works, and would definitely confuse me (and I bet others consuming the API as well).

I'd rather see a different filter or mechanism for including protected statuses, but I don't know the best way.

**Comment by rmccue** [comment]
We made an intentional design decision to (generally speaking) not change based on whether you're authenticated or not. This is why `context=edit` is required to be explicitly specified when you're changing what your app does.

Potentially, we could change parameter defaults based on the context parameter, but I think this would be more confusing than the current behaviour.

The key premise of this issue:

> Since REST APIs don't distinguish between an admin context and a non-admin context

...doesn't apply to this API, since we _do_ distinguish between the contexts.

**Comment by kadamwhite** [comment]
@rmccue By this logic `context=edit` should include the protected statuses in the collection response; I do not see that happening in my environment?

Edit: Ah, I see your comment about parameter defaults.

My $0.02 is that I don't like `context`, it is a partially complete (two macro-level states) solution to a complex problem (how to return a generally-useful lightweight result in the default case, and still provide full content for others) and I have trouble keeping track of when I should expect the results to change based on `context`. That ship may have sailed but I'd like to finish the conversation to prove out whether `context=edit` => "all protected statuses" before dismissing it out of hand.

**Comment by kadamwhite** [comment]
To recap some [slack conversation](https://wordpress.slack.com/archives/core-restapi/p1474554668002472) around this, the general principle followed by this API is,
- Auth controls what you can access
- Context controls what fields things have when you access them
- Query parameters control what's included in a collection
  This will be captured in a docs repo issue to make that handling explicit, and to explain how to handle this case.
