### ISSUE TITLE
Redirect doesn't include access_token for `users/me`

### ISSUE THREAD

**Issue by bartram** [WP-API/WP-API#2635]
The `users/me` callback will redirect an API request to `users/[id]` where `[id]` is the current user's id. If an access token is passed in the query string, it is not included in the redirect, so `users/[id]` results in a 401 error.

`WP_REST_Users_Controller::get_current_item` already returns the user response, so I think the redirect should be removed to avoid this issue.

**Comment by BE-Webdesign** [comment]
Hi @bartram,

Thank you for using the WP REST API. Could you please provide an example request and explain what access token you are referring to?

**Comment by bartram** [comment]
_Any_ query string that is passed to `users/me` will be stripped on redirect. In my app, an `access_token` parameter is passed for user authentication. So if a user wants to view their own profile, they GET `/wp-json/v2/users/me?access_token=sometoken`. The `access_token` identifies which user they are, and authenticates them for that request. WP-API then redirects to the user resource for that user, e.g. `/wp-json/v2/users/75`, but the app no longer knows which user is making the request, or if they have access, because the access_token is not included in the redirect request, so the the response is 403.

**Comment by BE-Webdesign** [comment]
Okay, I will look into that when I have time this week, to see what the root cause is.

**Comment by rmccue** [comment]
This is partially intentional behaviour; the API doesn't redirect with arbitrary parameters.

For access control to work properly with caches, you should be using the `Authorization` header which is specifically designed for access control. Your client should then be able to handle this correctly.

Alternatively, you can change your client to add `access_token` after the redirect.

**Comment by bartram** [comment]
I question why the API redirects `users/me` at all. What purpose does it serve? It adds another HTTP request, increasing load time. The redirect doesn't provide the user with any extra information. In fact `users/me` returns the user object AND redirects the request, which is doubly redundant.

Using the `Authorization` header is not a solution if you are using OAuth.

I'm not suggesting that the query parameters be passed in the redirect. I believe the redirect should be eliminated completely. It serves no purpose.

**Comment by kadamwhite** [comment]
@rmccue Can you shed any light on why the redirect is needed? I agree that `Authorization` header is not a guaranteed solution.

**Comment by rmccue** [comment]
The redirect indicates that the resource you're accessing (`users/me`) is not the canonical resource, but merely an alias for the canonical one (`users/{id}`). This is part of how REST works, as it's entirely resource-based.

There are multiple ways to not treat this canonical indicator (the 302 status) as a redirect. You can configure your client to not follow these (happy to provide tips on how to do so) or you can use the API's envelope mode instead (send `?_envelope` and the headers/status/body will be wrapped in an object and sent in the body, with a forced 200 status).

> Using the `Authorization` header is not a solution if you are using OAuth.

Both OAuth 1 and 2 use the Authorization header; OAuth 1 is `Authorization: OAuth oauth_...`, OAuth 2 is `Authorization: Bearer tokendata`. If the OAuth 2 plugin you're using doesn't support this, that's a violation of the [OAuth spec](https://tools.ietf.org/html/rfc6750#section-2.1):

> Clients SHOULD make authenticated requests with a bearer token using
> the "Authorization" request header field with the "Bearer" HTTP
> authorization scheme.  Resource servers MUST support this method.
