### ISSUE TITLE
Adding links in default endpoints

### ISSUE THREAD

**Issue by nakanaa** [WP-API/WP-API#2636]
I have custom metadata on some of my posts that I wanted to expose with the API. This was easy enough with the `register_rest_field` function. But I have some metadata that is actually a reference to other custom posts in the same WordPress instance. In addition to exposing the metadata itself I also want to add it to `_links` and `_embedded`. But I couldn't find any info on how to add (embeddable) links **in default endpoints** (eg. without adding a custom endpoint).

As far as I understand, the links can only be added to the response object and that object hasn't been created yet when WP runs the callbacks in `register_rest_field` so I guess it's not possible?

Maybe the code will clarify:

``` php
register_rest_field('article',
        'theme',
        array(
            'get_callback' => function ($post, $field_name, $request) {
                $theme_id = get_post_meta($post['id'], 'theme', true);
                // Can I do something like this without the actual response object available yet?
                $response->add_link('theme', rest_url('/wp/v2/themes/' . $theme_id), array('embeddable' => true));
                return $theme_id;
            },
            'schema' => null,
        )
);
```

Sorry if this is somewhere in the documentation. I couldn't find any help in there or by googling.

**Comment by BE-Webdesign** [comment]
Hi @nakanaa,

Thank you for using the WP REST API.  You can use the rest_prepare_{$this->post_type} and call add_links() on the response object.

Also important to note, having a custom post type named themes is not a good idea in the wp/v2 namespace as that will eventually collide with the themes endpoint.  I would recommend sub classing the posts_endpoint and changing its namespace for your custom needs.

Going to close out but you can continue discussion here.
