### ISSUE TITLE
wp-json/wp/v2/users/me  "status": 401

### ISSUE THREAD

**Issue by medrockstar** [WP-API/WP-API#2639]
When I put wp-json/wp/v2/users/me I get :

{
"code": "rest_not_logged_in",
"message": "You are not currently logged in.",
"data": {
"status": 401
}
}

**Comment by BE-Webdesign** [comment]
Hi @medrockstar,

Thank you for using the WP REST API.  You need to authenticate with the API in one way or another.  Please check out [the authentication guide](http://v2.wp-api.org/guide/authentication/).

**Comment by aminpaks** [comment]
I tried with basic authentication, but still not working!
Also updating the posts or pages have the same issue.

**Update:**
Apparently WordPress needs a plugin called "[Basic Authentication](https://github.com/WP-API/Basic-Auth)" to allow this happen.
You should consider mentioning this in the documentation to avoid any confusion.

Thanks.

**Comment by MeTazz1** [comment]
Hey, 
I'm facing the same issue. 

Mysite.com/wp-json/wp/v2/users/me is returning the same error (from an iOS app) : '"code":"rest_not_logged_in","message":"You are not currently logged in.","data":{"status":401}'.

I installed the Basic Authentication handler plugin, since I'm trying to use Basic Authentification, and enabled it in my wordpress.

```
 NSMutableURLRequest *requestLog = [[NSMutableURLRequest alloc] initWithURL:[NSURL URLWithString:"Mysite.com/wp-json/wp/v2/users/me"]];
    [requestLog setHTTPMethod:@"GET"];
    [requestLog addValue:@"Authorization" forHTTPHeaderField:authString];
```

authString corresponds to "Basic " + iOSVersionOfBase64("admin":"password")

Anything missing ?
Thanks !

**Comment by aminpaks** [comment]
@christophedellac Are you sending the right headers?
`Authorization: Basic YWRtaW46cGFzc3dvcmQ=`

**Comment by MeTazz1** [comment]
Yes, exactly the same header in the request. Same result with Chrome Poster

**Comment by aminpaks** [comment]
@christophedellac Mine works fine! I tried the oauth-v1 and that works too.

**Comment by MeTazz1** [comment]
Hey, 

Ok so, after installing the wp-json plugin, you just installed the Basic Authentification Plugin, activated it,  and you were able to log in into your website ?

Example :
 `curl --user admin:password Mysite.com/wp-json/wp/v2/users/me`

This was working ? Any way that another plugin is blocking the access ? Like a cache plugin or something ?

**Comment by aminpaks** [comment]
> Any way that another plugin is blocking the access ? Like a cache plugin or something ?

As I said it's working fine for me. You just have to disable all other plugins and double check this by yourself.

**Comment by BE-Webdesign** [comment]
Hi @christophedellac,

It is possible that your server config is stripping out the Authorization header as well, if you find that another plugin is not the culprit.  What server are you running?

**Comment by MeTazz1** [comment]
This is a linux shared server from 1&1 (web host). How Can i check if the headers are stripped ?
Just disabled all plugins, except WP REST API and JSON Basic Authentication, and still the same.

I don't know if it can helps, but here is the response :

```
Pragma: no-cache
Date: Sun, 14 Aug 2016 08:36:42 GMT
X-Content-Type-Options: nosniff
Last-Modified: Thu, 01 Jan 1970 00:00:00 GMT
Server: Apache
X-Powered-By: PHP/5.6.24
Allow: GET
Content-Type: application/json; charset=UTF-8
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
Cache-Control: no-cache, must-revalidate, max-age=0
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Headers: Authorization
Keep-Alive: timeout=15
Expires: Wed, 11 Jan 1984 05:00:00 GMT

{"code":"rest_not_logged_in","message":"You are not currently logged in.","data":{"status":401}}
```

**Quick update :** 

I just tried with new htaccess file, containing the following lines : 

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
RewriteBase /
RewriteRule ^index\.php$ - [E=X-HTTP_AUTHORIZATION:%{HTTP:Authorization},QSA,L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [E=X-HTTP_AUTHORIZATION:%{HTTP:Authorization},QSA,L]
</IfModule>
```

Right now, running with no other plugin than the 2 required and the follow Chrome Poster request : 
url : http://mysite.com/wp-json/wp/v2/users/me
headers : 
- Authorization -> Basic YWRtaW46cGFzc3dvcmQ=

**Comment by BE-Webdesign** [comment]
@christophedellac,

> This is a linux shared server from 1&1 (web host)

Using Basic Auth on an environment like this is not secure.

> Right now, running with no other plugin than the 2 required and the follow cURL request : 
> curl --user admin:password http://mysite.com/wp-json/wp/v2/users/me

Is it still not working?  You can check to see if the headers are being passed in by doing something like the following in a separate plugin or your active theme's functions.php.

``` php
add_filter( 'rest_pre_dispatch', 'prefix_show_request_headers', 10, 3 );

function prefix_show_request_headers( $result, $server, $request ) {
    $result = $request->get_headers();
    return $result;
}
```

That should help with tracking down your issue. Only do that if this is just a developing environment and not on any production environment.

I don't know if `mod_rewrite` is the best to use.  If you have `mod_setenvif` available then you can do this:

`SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`

Going to close out this issue as it is most likely not an implementation error in the API.  Feel free to continue discussion here.

**Comment by MeTazz1** [comment]
Thanks !

Showing headers give this 

`{
  "host": [
    "mysite.com"
  ],
  "cache_control": [
    "no-cache"
  ],
  "user_agent": [
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"
  ],
  "postman_token": [
    "cf0fb167-3f69-cd34-61f3-4fdad9e58e73"
  ],
  "accept": [
    "*/*"
  ],
  "accept_encoding": [
    "gzip, deflate, sdch"
  ],
  "accept_language": [
    "en-US,en;q=0.8,fr;q=0.6"
  ]
}`

Look likes Authorization is not here.. Since I have no other plugins enabled, I guess it comes from my host, right ?

**Comment by BE-Webdesign** [comment]
> Since I have no other plugins enabled, I guess it comes from my host, right ?

Most likely, you wouldn't ever really want to use Basic Auth on a shared hosting environment.

**Comment by aminpaks** [comment]
@christophedellac Is it necessary using that shared hosting? If not have your own server on [Vagrant](https://www.vagrantup.com/) with [scotch-box](https://box.scotch.io/) and enjoy.

**Comment by MeTazz1** [comment]
Yes, this is necessary since this will be the host of my main website. I found out that, for security reasons, my host is removing some headers parts. I guess I will check for oauth .. Thanks for responses anyway guys !

**Comment by sigaev-pro** [comment]
Hi!

I have same issue. I have installed [Basic Auth](https://github.com/WP-API/Basic-Auth) pligin, but /users/me gives me the same error.

Authorization headers are present!

{
    "cookie": [
        "wp-settings-1=libraryContent%3Dbrowse%26hidetb%3D1%26editor%3Dtinymce%26mfold%3Do%26woosidebarsshowadvanced%3D1; wp-settings-time-1=1475495114; wordpress_logged_in_33f0e8fc1bbfb1f159bcedadef4e282c=admin%7C1476444666%7CnMTdZWd79TeyfyXZ9WwHd2D4PGZoC07gqgNPAKRODgu%7C6d083cd8f513525df5f257e0ced5491470a5ad5762486fe3d6c4dcd50ed49766; wordpress_test_cookie=WP+Cookie+check; woocommerce_items_in_cart=1; woocommerce_cart_hash=39e547027da647baff338d8fc4651bc0; wp_woocommerce_session_33f0e8fc1bbfb1f159bcedadef4e282c=1%7C%7C1476315798%7C%7C1476312198%7C%7C87f2ac166c84a58e2868a0c48e28addd"
    ],
    "accept_language": [
        "ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4,bg;q=0.2,de;q=0.2,fr;q=0.2,it;q=0.2"
    ],
    "accept_encoding": [
        "gzip, deflate, sdch, br"
    ],
    "accept": [
        "_/_"
    ],
    "authorization": [
        "Basic YWRtaW46YWRtaW5hZG1pbiEhIQ=="
    ],
    "cache_control": [
        "no-cache"
    ],
    "user_agent": [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"
    ],
    "host": [
        "dosug-prostitutki.com"
    ],
    "content_length": [
        "0"
    ],
    "content_type": [
        ""
    ]
}

**Comment by saber13812002** [comment]
add this line of codes to .htaccess file in the root of your wordpress

RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
