### ISSUE TITLE
Show Private / Draft Posts via Javascript

### ISSUE THREAD

**Issue by wblaircox** [WP-API/WP-API#2642]
I'm unable to show private or draft posts via javascript. Using Postman has not worked, best I can determine it may have something to do with my server running PHP as CGI. But I can run my script from a WP page, which is fine for my usage. I've read the examples for filtering, but at this point I'm just trying to get filtering to work at all. Any suggestions?

function getpost() {
        var postsCollection = new wp.api.collections.Posts({
            data: {
                'filter': {
                    'category-slug': 'ChartData',
                    'posts_per_page': -1
                }
            }
        });
        postsCollection.fetch();
        console.log(postsCollection);
    };

**Comment by BE-Webdesign** [comment]
Hi again,

You would need to use the status param to view private and draft posts.  Check out the [API Reference for the status param](http://v2.wp-api.org/reference/posts/).  You will need to be authenticated with the API and have proper permissions to view.

Going to close but we can continue discussion here.

**Comment by wblaircox** [comment]
Thanks for the assistance. I've read this reference and tried a few times / variations. I must be doing something wrong. Some references online say it needs to be post_status. I started with the javascript example on the documentation page, then applied the parameter. This is run on a page within Wordpress, the user is admin. I just bring back the results to console.log for now. 

function getpost() {
        // Load an existing post
        var postsCollection = new wp.api.collections.Posts({
            status: 'draft'
        });
            postsCollection.fetch();

**Comment by wblaircox** [comment]
You know, I'm not sure it will matter. The JSON this pulls back for the published posts is a pain in the ass. So many fields I don't need and trying to pull back variables in the structure is proving challenging. Methods I use continually elsewhere don't seem to work as expected with this. A bit of code I use to get the index array and pull everything back doesn't even work. Love the idea, but a week on this is enough for now. I need to have a working function, not a make work project. Maybe when I get more handy with Javascript.

**Comment by kadamwhite** [comment]
@wblaircox If you want a lighter set of JSON, it's probably best to create your own [custom endpoint](http://v2.wp-api.org/extending/adding/) — but in the case of your specific question, we did _not_ document the "any" status, or even the full list of statuses available, so sincere apologies for that. I've opened a PR to add an enum of supported status types to the API, and for the time being using `status: 'any` ought to give you the full set you desire.

**Comment by kadamwhite** [comment]
Also, I'm not as familiar with the Backbone code—you might want to check in on [that repository](https://github.com/WP-API/client-js) for specifics around how this is supported from the Backbone implementation—but this JavaScript does successfully pull back all of the published, private & draft posts using [the vanilla JS client](https://github.com/WP-API/node-wpapi), so maybe it will help:

``` js
site.posts().context( 'edit' ).param( 'status', 'any' ).then(function( posts ) {
    console.log( posts );
});
```

**Comment by kadamwhite** [comment]
As in the above example you may need to pass `context: 'edit'` along with `status`; in my testing, `status` other than publish is ignored if context is not set to "edit"

**Comment by wblaircox** [comment]
@kadamwhite Most appreciated for the help. Guess I'll have to sort out exactly how Backbone is to be written. Not sure if I want to try using the JS client in something that will be live in a few months. I do have a custom endpoint setup and calling it with cURL works well and clean - if I can just get it thing to only show draft or private messages, then I have what I need. I'll give it a few more days to get figure out, would be nice in the long-run to build on this rather than going the old school php/mysql route. Cheers!

**Comment by kadamwhite** [comment]
@wblaircox :+1: great! Good luck, and don't hesitate to reach out on the #core-restapi channel in the WordPress slack if things aren't working as you expect.

**Comment by wblaircox** [comment]
@kadamwhite Will do! What you provided was enough to point me in the right direction. Can now show draft posts. Just need to figure out how I'm to call my end-point. Hoping I don't need to write a page of code in order to do it. 

```
function getpost() {
    var postsCollection = new wp.api.collections.Posts({});
    postsCollection.fetch({
        traditional: true,
        data: {
            status: ['draft']
        }
    });
    console.log(postsCollection);
};
```

**Comment by wblaircox** [comment]
Question - if I can see my custom endpoints in a URL (browser or cURL) then how do I select/define it in JS? I've read the documentation, but that all seems rather much to setup and I'm not even sure where. It works now in the browser...

**Comment by wblaircox** [comment]
What voodoo does this return? Appears to be a mixture of objects and arrays. When I attempt select elements of the structure, it changes. For example, just return everything console.log(postsCollection); and you can dig deeper into the structure, including the arrays under models. Try it with postsCollection.models[1], and what was once populated arrays, are now empty.

**Comment by wblaircox** [comment]
Wasted enough time on this. Overly complicated for little value - for a simple data save/retrieve operation. Should be dead simple if getJSON was allowable without the issues around authentication not working.

**Comment by kadamwhite** [comment]
@wblaircox I'm sorry you've been having difficulty. If JSON retrieval is all you need, and the Backbone structure is not useful to you, I'd encourage you to check out [the other JavaScript client](https://github.com/wp-api/node-wpapi), which if installed via NPM includes a `browser/` folder containing modules which can be included directly in the browser. Feel free to reach out to me about this, I'm the lead maintainer of that library.

**Comment by wblaircox** [comment]
@kadamwhite GET and POST is all I need. My apache server runs cPanel. Will have to look more into NPM.

Update: Looks like an ideal solution. I'll see if it will play nice on the box I need to use it with. Cheers!

**Comment by wblaircox** [comment]
@kadamwhite my app is not node.js - is this still going to work for me?

**Comment by kadamwhite** [comment]
@wblaircox should do; check out http://wp-api.org/node-wpapi/installation/#download-the-umd-bundle to get the browser code, then configure it as in http://wp-api.org/node-wpapi/authentication/#cookie-authentication -- open an issue on that repo if you run into trouble!
