### ISSUE TITLE
create user with custom fields

### ISSUE THREAD

**Issue by medrockstar** [WP-API/WP-API#2644]
Hi,
Can we create a user with custom fields ?
tks,

**Comment by BE-Webdesign** [comment]
Hi @medrockstar,

Currently, by default, the default endpoints do not allow you to add user meta (I think that is what you mean by custom fields) to any user resource during creation.  However you can use the `register_rest_field()` function to add select meta fields to the default endpoints; [here is the guide](http://v2.wp-api.org/extending/modifying/#read-and-write-a-post-meta-field-in-post-responses).

There are hooks and filters in the API endpoints that would enable you to add meta as well, but it is most likely better to use `register_rest_field()` for your purposes or create a separate endpoint.
