### ISSUE TITLE
Advanced `orderby` clause array allowed in `filter` args by default?

### ISSUE THREAD

**Issue by andrewmartin** [WP-API/WP-API#2646]
Hi there,

This may be a silly question, but I just spent ~3 hours trying to get this to work, and I'm confused why it's not.

I'm trying to do an advanced `orderby` call to the API, using the methods shown here:

https://make.wordpress.org/core/2014/08/29/a-more-powerful-order-by-in-wordpress-4-0

Here's a pretty solid example / walkthrough of this feature as well:
http://www.billerickson.net/wp-query-sort-by-meta/

I was wondering if the WP JSON API out of box allows for a `filter[orderby]` array object; something like this:

```
'meta_query' => array(
      'relation' => 'AND',
      'startDateClause' => array(
        'compare' => 'EXISTS',
        'key' => '_EventStartDate'
      ),
      'featuredClause' => array(
        'key' => 'featured',
        'type'    => 'NUMERIC'
      ),
      array(
        'ageClause' => array(
          'key' => 'age',
          'value' => 'Babies',
          'compare' => 'LIKE'
        )
      )
    ),
    'orderby' => array(
      'featuredClause' => 'DESC',
      'startDateClause' => 'ASC'
    )
```

I have allowed `meta_query` in using the `rest_query_vars` filter, and I'm able to get results; but the Order is not working. I'm thinking that `orderby` is probably not needed below:

```
add_filter( 'rest_query_vars', __NAMESPACE__ . '\\meta_keys_query_vars' );
function meta_keys_query_vars( $valid_vars ){
  $valid_vars = array_merge( $valid_vars, array(
    'meta_query',
    'date_query',
    'orderby'
  )
); // Omit meta_key, meta_value if you don't need them
return $valid_vars;
}
```

With a custom old fashioned `WP_Query` with the above arguments, I'm able to see the correct order.

**Comment by BE-Webdesign** [comment]
Hi @andrewmartin,

Thank you for using the WP REST API.  For a complex query like that I imagine it is faster to just pull out a whole lot of posts and then run your own sorting on top of that. If WP_Query use is necessary then you can try the following comments.

If it works correctly with an WP_Query object, it is possible the args aren't being read as you are intending in the API.  That is a complex query, so I would recommend using something like `http_build_query()` to build the query string.

You can use the `rest_{$this->post_type}_query` filter to display/log what the args are before they are filtered by `WP_REST_Posts_Controller::prepare_items_query()`.  If all of your args are being displayed correctly at that point in the chain then `prepare_items_query()` is most likely stripping something out.  To my knowledge, the WP REST API does not modify WP_Query's behavior, so I imagine it would support the array orderby clause.

**Comment by andrewmartin** [comment]
@BE-Webdesign 

Thanks for the thorough reply! I actually inspected the `WP_Query` object, and the params are, in fact, being sent through (at least they look good to me when I `var_dump`).

I think your solution actually is a nice one (to grab a bunch of posts and filter down from there), but it's not as elegant as I'd prefer. I'd think (and hope) that the `WP REST API` would ideally support (out of box) all of the default WP Query params, shouldn't it?

**Comment by rmccue** [comment]
> I'd think (and hope) that the WP REST API would ideally support (out of box) all of the default WP Query params, shouldn't it?

Not necessarily; we have support for the majority of them, but `filter` is intentionally available as an escape hatch to access the underlying query parameters if you want to. In this case, this is a significantly advanced use case that may benefit from a custom endpoint, so we only support it via the escape hatch. :)

**Comment by andrewmartin** [comment]
@rmccue 

I partially understand, and I partially don't understand––why are some of the parameters considered an "escape hatch" vs. others? 

I read up a bit and saw there were some security related concerns to exposing the meta stuff, but I think ultimately, it'd be awesome to see it function 1:1 with the default query parameters. 

I guess, if anything, to appease my own curiosity, I'm wondering these limitations to the `WP REST API` are intentional.

**Comment by kadamwhite** [comment]
"escape hash" may not be the best term, I think of `filter` as more of a _shim_: WP_Query is a powerful tool, but its parameters do not necessarily best match the circumstances of an API collection endpoint, so the API team has been selectively promoting certain types of query to first-party parameters (`slug`, `before`, `include` etc are good examples). I'd need to re-read this thread to have the full context for this particular discussion, but a long time ago we made the decision that WP_Query was better supported incrementally and mindfully than arbitrarily and broadly. I understand the frustration that some things aren't available, but I hope this helps clarify the background!

**Comment by andrewmartin** [comment]
@kadamwhite thanks man, that does help give me a little more context––but I'm still going to (kindly) hold my ground that the _end_ goal should be to have a 1:1 match with the query options provided by the WP Core. Do you agree with that? I can see the reason for incrementally adding such options (and agree that your examples probably make sense to include first), but I guess I don't understand why the ultimate goal is to simply leave some parameter options unavailable. 

Anyways, either way, I respect what you guys have done and it was a pleasure to use the plugin. I do think that @BE-Webdesign's original solution was probably the way I'd use it next time, though.

**Comment by rmccue** [comment]
> I partially understand, and I partially don't understand––why are some of the parameters considered an "escape hatch" vs. others?

Sorry, I mean specifically `filter` is an escape hatch, in that it allows access to the underlying implementation in a non-REST way. I think @kadamwhite explained it a little better than I did :)

Some day it might be nice to support this, but right now, there's no plans to support it. Meta in particular is only just being supported now, as it's quite complex to support in a safe way (serialized data, privacy, etc). We'll likely revisit this in the future, but right now, it's not on the roadmap, and I don't want to give the impression it is by leaving the issue open :)

**Comment by kadamwhite** [comment]
It's a bit of a roundabout solution, but making a custom endpoint is always a option for this too. Thank you very much @andrewmartin for using the REST API and for raising your questions; they're not going unheard, we appreciate your feedback!

**Comment by andrewmartin** [comment]
Hey, thank you guys! Building a React app using WP was a true pleasure thanks to you guys.
