### ISSUE TITLE
problem for upload image

### ISSUE THREAD

**Issue by frengo1970** [WP-API/WP-API#2648]
Hello.
i have a problem for upload an image stored on my server in media manager.

the error message is: 
**{"Code": "rest_upload_unknown_error", "message": "The file is empty. Load something more substantial. This error may be because uploads have been disabled in the php.ini file or by the fact that in php.ini post_max_size was defined less than upload_max_filesize. "," date ": {" status ": 500}}**

this is php.ini of target wp site: http://www.italyveritas.com/phpini.php but i think that the problem is not php.ini because if i use postman i don't have any problem and i can insert image in wordpress.

and this is the code that i use

```
curl_setopt_array($curl, array(
  CURLOPT_URL => "http://italyveritas.com/wp-json/wp/v2/media",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => "-----011000010111000001101001\r\nContent-Disposition: form-data; name=\"file\"; filename=\"".$pathImg."".$immagine."\"\r\nContent-Type: false\r\n\r\n\r\n-----011000010111000001101001--",
  CURLOPT_HTTPHEADER => array(
    "authorization: Basic xxxxx",
    "cache-control: no-cache",
    "content-type: multipart/form-data; boundary=---011000010111000001101001",
    "postman-token: c692cc1b-4951-e899-130d-308a85446886"
  ),
));
```

can sombody help me please?

Francesco

**Comment by rmccue** [comment]
**Important:** Your original password contained the `Authorization` header which **includes the password in plain text**. I've edited the issue, but you should regard your password as compromised and **change it immediately**.

It looks like you're trying to build a multipart request manually here, but that won't work, as multipart files have a very specific format. In particular, you're not sending the data correctly with the boundaries here, and your content-type is set to the string "false", which is not a real content type.

Instead, send the raw content of your file as the body, with a content-length header:

``` php
CURLOPT_POSTFIELDS => $imagedata,
CURLOPT_HTTPHEADER => array(
    'content-length: ' . strlen( $imagedata ),
    // Other headers as well
),
```
