### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by aminpaks** [WP-API/WP-API#2649]
What would be the best option to have access to **Post table** of Wordpress?
In that case we could fetch custom posts as well, and get posts and pages in one place.

Any thought?

**Comment by BE-Webdesign** [comment]
Hi @aminpaks,

Thank you for using the WP REST API.

Not sure what you are trying to ask.

> we could fetch custom posts as well, and get posts and pages in one place.

The posts endpoint is designed to interact with the posts table in WordPress.  The `WP_REST_Posts_Controller` class is designed to handle custom post types as well.

I am assuming you are asking something different, please try to clarify.

**Comment by aminpaks** [comment]
Hi @BE-Webdesign,

Firstly thanks for all the hard work man.
Your `WP_REST_Posts_Controller`, I assume only searches among `post` type within the `Post Table` of WordPress. I'm referring to [your documentation](http://v2.wp-api.org/reference/posts/).

If that's not the case, please advice.

Thanks.

**Comment by BE-Webdesign** [comment]
> Firstly thanks for all the hard work man.

Talking to the wrong person on that.  [These are the people who you should thank, (among others not on the list)](https://github.com/WP-API/WP-API/graphs/contributors).

You can use/extend `WP_REST_Posts_Controller` to retrieve different `post_types`.  This issue tracker is also for bug reports and enhancements.  If there is something lacking in the documentation you can leave an issue [here](https://github.com/WP-API/docs-v2).  I am going to close out this issue but feel free to leave an issue on the docs repo if something is lacking.

**Comment by aminpaks** [comment]
Actually its place is right here.
I'm talking about a new endpoint, that can retrieve all post types. I already looked into the code and its implementations, and I know it's easy to do this. What I meant is having this feature out of the box, so if someone installs the PlugIn, they take advantage of it.

Thanks again.

**Comment by BE-Webdesign** [comment]
> What I meant is having this feature out of the box, so if someone installs the PlugIn, they take advantage of it.

Any post type registered with `show_in_rest => true`, I believe, will show up in the `wp/v2` namespace by default; out of the box.  Anyone can take advantage of that without having to write custom endpoints or anything of that sort, if that is the use case you are talking about.

**Comment by kadamwhite** [comment]
Is the question, is it possible to get all different custom post types all mixed together in a single endpoint's response?

**Comment by aminpaks** [comment]
@kadamwhite Yes, what I though would be useful to get at least all posts and pages in only one endpoint.

Something like this:
`/wp-json/wp/v2/posts?type=page&slug=about`
`/wp-json/wp/v2/posts?type=post&slug=the-last-article`

**Comment by rmccue** [comment]
We used to do this in v1, but we changed the behaviour in v2 as something being a "post" doesn't really tell us much about how that data is modelled. Modelling every CPT in the same way is inaccurate and error-prone at best, and raises security and privacy issues at worst.

For these reasons, we're not going to add back a generic endpoint to access this data, sorry!
