### ISSUE TITLE
How to sort users by all fields?

### ISSUE THREAD

**Issue by Redigast13** [WP-API/WP-API#2653]
I see that I can sort by id, include, name,  registered_date in "wp/v2/users" endpoint. Tell me please how to sort by other fields, for example username. And what means "include' field ?

**Comment by joehoyle** [comment]
@Redigast13 those are the only supported orderby fields. I'm not 100% sure of the historical reasons for that. I created https://github.com/WP-API/WP-API/issues/2658 to add some more order by fields.

The `include` field to get multiple users by IDs.

**Comment by marqsitelabs** [comment]
I've managed to add user meta as and endpoint but there is no way to sort results by that endpoint.

Here's how I added a user meta endpoint:

```
add_action( 'rest_api_init', 'user_puntuacio' );

function user_puntuacio() {
    register_rest_field( 'user', 'puntuacio',
        array(
            'get_callback'    => 'get_user_puntuacio',
            'update_callback' => null,
            'schema'          => null,
        )
    );
}


function get_user_puntuacio( $object, $field_name, $request ) {
    return get_user_meta( $object[ 'id' ], 'puntuacio', true );
}
```

Please provide a solution
