### ISSUE TITLE
Support short date ISO format with before or after params

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/WP-API#2654]
I was surprised that `/wp/v2/posts?before=2013-01-08` did not work, yielding:

```
{
  "code": "rest_invalid_param",
  "message": "Invalid parameter(s): before",
  "data": {
    "status": 400,
    "params": {
      "before": "The date you provided is invalid."
    }
  }
}
```

Using the full ISO8601 date string `2013-01-08T00:00:00.000Z` works, but this seems unnecessarily verbose. Is this functioning as intended & short-format dates are explicitly disallowed, or is the API meant to softly account for the expansion?

**Comment by BE-Webdesign** [comment]
To my knowledge, the way the schema is validated for date formats requires the full ISO date-time string.  We can definitely investigate changing that however.  Thank you for bring up the issue, I am sure many others will feel the same.  I think we can label this as an enhancement as well.

If we implement this, I think a small problem arises.  If you don't specify a time string what default time are you expecting to be attached?

**Comment by kadamwhite** [comment]
That's a good question, and one to which I don't have a good answer. Defaulting to `00:00:00.000Z` would be the default solution in my mind because it mirrors e.g. JavaScript's behavior should you `new Date( '2016-08-15' ).toISOString()`, but that does not account for time zones. I'm not sufficiently familiar with PHP to know what the defaults are for time zone handling in e.g. `strtotime`

**Comment by BE-Webdesign** [comment]
I agree, the 00:00:00.000Z would be easiest to implement too. I will double check what php does by default. I just encountered this a month ago and can't even remember what the default is.  I think the `DateTime` object does work off of `now()` and depending on what timezone you have configured, it uses that timezone.  Not sure what other people would expect to happen, so whatever we decide we would need to add it to the documentation site and the schema description.

**Comment by joehoyle** [comment]
Hmm yeah I'm not sure about this. `After 2012-12-15` in english sounds like "give me posts after the 15th" however defaulting to "00:00" means that's actually saying "including the 15th. Personally, I think there's enough ambiguity here to not do this :)

**Comment by kadamwhite** [comment]
True, the question of whether to be inclusive or exclusive remains with the user if we require the full string. I guess this is something that clients can normalize, rather than making potentially invalid assumptions on the API side.
