### ISSUE TITLE
Make routes work if Wordpress Address & Site Address are different

### ISSUE THREAD

**Issue by ghost** [WP-API/WP-API#2655]
I have a AngularJS app running in /app/build/ with my Wordpress install in /app/api/ 
I've set my Wordpress address to http://dev.app/api and Site Address to http://dev.app/build and now my endpoints aren't displaying anything. Any suggestions?

**Comment by joehoyle** [comment]
@jakecolour if you havn't changed the default rest base, you'll need to append `/wp-json/` to your site's url.

**Comment by kadamwhite** [comment]
@jakecolour If that doesn't do the trick, please elaborate on "aren't displaying anything" -- are you getting empty responses, or an error? What path are you trying to hit to get at the API?

**Comment by ghost** [comment]
@joehoyle @kadamwhite I've decided to go about it another way and rewrite through .htaccess (Both Wordpress & Site address are now http://dev.app/api)

I'm still getting a 404 Not Found on http://dev.app/api/wp-json

.htaccess as follows

``` apache
    <IfModule mod_rewrite.c>
        RewriteEngine On
        # Exclude wp-admin / wp-json
        RewriteRule ^(wp) - [L]
        # Rewrite everything else to /build/
        RewriteRule (.*) /build/$1 [R=301,L]

        # BEGIN WordPress
        RewriteBase /api/
        RewriteRule (.*) [L]
        RewriteRule ^index\.php$ - [L]
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule . /api/index.php [L]
        # END WordPress
    </IfModule>
```
