### ISSUE TITLE
Should "missing" values be `null` or non-existant

### ISSUE THREAD

**Issue by joehoyle** [WP-API/WP-API#2657]
There's an issue with empty values that most recently came up in https://github.com/WP-API/WP-API/pull/2393 and https://github.com/WP-API/WP-API/pull/2303

While we've had this discussion before, I don't know if we even came to much of a decision. If a value for a property does not exist, should we either have the field as `null` or should it not exist, or should we can it to the type of the property. The best example of this is `post_date_gmt` which is not set on draft posts. Right now we return `null` for this field in the API response.

If we want to do this, we are effectively saying every field is either it's defined type, or `null`, and clients should act accordingly. Given we quite strongly avoided removing fields from the response when they won't have a value, then I think this is broadly the decision.

This leads on to: what happens when you try set a field value to `null`. This should surely be supported - as the API response has essentially legitimized the "valid" `null` value. Once suggestion in https://github.com/WP-API/WP-API/pull/2303 is to ignore any `null` values from an update, however that essentially makes `null` mean "this value doesn't exist now, but once we have a value, there will always be a value", which I think _could_ work.

The main problem I have will stripping `null` values on update requests doesn't reflect the returned object, though on second thought that already happens in plenty of instances anyway.

**Comment by kadamwhite** [comment]
I'm +1 on returning `null` if a field is unset; it keeps the shape of the response more predictable, and gives clients an easy way to take the returned object and kick it back to the API in updates without worrying that the returned values will fail validation (e.g. #2303).

That said, to dig into "this value doesn't exist now, but once we have a value, there will always be a value" — that _sounds_ right, but can anybody think of a case where that would be false?

**Comment by BE-Webdesign** [comment]
I think returning `null` works and treating it as a non existent value, kind of works.  If you want to set a value to `null` then you could pass in an empty value for its type i.e. `string: ''`, `array: []`, `object: {}`, `int: 0`, but for DB purposes and updating, I imagine we would need to save values as `null` instead of empty constructs, and by stripping out null values on update requests it could lead to problems when fetching the resource back.

When I have time, I will look and see how other APIs handle `null` cases.

**Comment by gnarf** [comment]
(@kadamwhite asked for my :eyes: on this one, so here's my $0.02)

> then you could pass in an empty value for its type

If you're giving `null` as a response, you should accept setting `null` via the API as well (when it makes sense to be able to)

Any field which can accept null should be altered to accept "string or null" or "date or null" and you should switch to `undefined` (or not at all included in the request) as your "do nothing" and `null` as your "write `null`"

Trying to pretend that posting a NULL field means "do nothing" in a JSON API is a step backwards IMO, thats why we have `undefined`.  

If you treat an API request like a database query, then saying `UPDATE foo SET field=NULL` means to set it to null, not ignore it.

**Comment by gnarf** [comment]
(to be clear, I think posting `null` to a field that doesn't accept `null` should be a validation error, not silently ignored)

**Comment by BE-Webdesign** [comment]
I think instead of returning null for some special meaning, we should not return the field in the response, if the value is not valid. In the case of slug and dates with newly created posts, those fields should maybe not appear at all. Not sure how to handle the logistics of that though.

**Comment by kadamwhite** [comment]
I believe that the input from @gnarf and @BE-Webdesign is consistent in that they suggest we omit fields or submit `undefined` when there is no or when there is invalid value; and to only use `null` when it has specific meaning. If that is a correct read then I +1 and open it to @WP-API/amigos before we finalize the decision.

**Comment by westonruter** [comment]
Field omission would be required because `undefined` is not valid JSON.

**Comment by gnarf** [comment]
Yeah, omission === undefined

**Comment by gnarf** [comment]
Or rather....

JSON.stringify({ field: undefined }) === "{}"

JSON.parse("{}").field === undefined

**Comment by kadamwhite** [comment]
From @rmccue, 

> we made the decision a long time ago`*` on this one based on `null` meaning "we know and understand this field, and it lacks a value"

`*`: the decision to return null if a field has no value

From the perspective of a typed system, this perspective does make sense; having fields sometimes exist and sometimes not does incur more overhead. Marking this as something to decide as a group on Monday. (Discussed with @brianloveswords as well, who provided input from working with APIs in Rust and Java)

**Comment by kadamwhite** [comment]
Relevant Slack discussion: https://wordpress.slack.com/archives/core-restapi/p1473800823001158

**Comment by kadamwhite** [comment]
The decision on this issue (see Slack link above) is that the philosophy of this library is to always return an object with consistent keys; if a key's value is unknown, `null` should be sent instead. `null` means "we know and understand this field, and it lacks a value". This is motivated by this project's core value of consistency (in this case consistency of keys that can be expected to be present on a returned object), and to avoid making it prohibitively difficult to specify the expected response in a less loosely-typed language than JS or PHP.

`null` is _not_ currently anticipated to ever be a value this plugin needs to expose literally (relating to @gnarf's point); a ticket will be opened on the documentation repository to clarify the precedent this issue sets to aid plugin authors in following suit.
