### ISSUE TITLE
How to search in the content

### ISSUE THREAD

**Issue by rowanjordaan** [WP-API/WP-API#2660]
Hi,

Currently I am trying to get the wp api to search in all posts content but for some reason it's only searching in the titles. Is this possible?

What I'm doing:
/wp-json/wp/v2/posts?filter[s]=some%20text (only seaches in posts titles)

Kind regards

**Comment by swissspidy** [comment]
According to the [docs](http://v2.wp-api.org/reference/posts/) you should be able to use `/wp-json/wp/v2/posts?search=some%20text` for searching in posts.

**Comment by rowanjordaan** [comment]
"/wp-json/wp/v2/posts?search=some%20text" will result in the same output. For some reason it only searches in the post titles and not in the content.

**Comment by joehoyle** [comment]
@rowanjordaan @rowanjordaan what version of the plugin are you using? This is working onthe latest, see here: https://demo.wp-api.org/wp-json/wp/v2/posts?filter[s]=This%20is%20some%20test%20post

**Comment by rowanjordaan** [comment]
I am using Version 2.0-beta13.1.

@joehoyle I just tested if the search uses excerpt and it seems in your example the search is using the excerpt and not the content. It does search the excerpt and the title but not the content unfortunally.

**Comment by websupporter** [comment]
Hi @rowanjordaan, basically with the `search` parameter the usual WordPress search gets executed. Just tested it locally on my install again and it works as expected. Could it be another plugin interfering with the WP_Query?

**Comment by rowanjordaan** [comment]
Well my default wordpress search is working as expected. So I don't know what the problem could be. The only plugin I am using next to wp-json is Themify Builder.

**Comment by websupporter** [comment]
Hmm... Right now, I am not quite sure, what could cause this. Just digging around. When using `?filer[s]` or `?search`:
- Are the missing posts maybe drafts (at least not published) and you are logged in while doing the regular search)?
- Is it like "no posts show up at all" or more like "I see 10 posts when I should see 15"?
- Can you show the complete search you are conducting. I mean something like `http://example.com/wp-json/wp/v2/posts/?filter[s]=text` (maybe the problem is not related to the search parameter)
- Are you searching for posts of the post type "post" or is it a custom post type?

Just some thoughts.

**Comment by rowanjordaan** [comment]
I am seeing no posts/pages at all. Both pages and posts are doing the exact same thing. I get the same result when logged in and when logged out. I am using default post types. It's a default wordpress installation with the plugin themify builder installed and wp json.

Example screenshot:
https://gyazo.com/bd1c0ef4ab036b0384040a9d99d14497

**Comment by websupporter** [comment]
I wonder how Themify actually saves the data. From the first glance its an page builder where you can easily add content in rows and stuff. I could imagine this information and texts are stored in custom fields and Themify checks if a (regular) search is conducted to extend the regular SQL to the custom fields. Doing so it could miss the REST API. But this is just guess work right now.

**Comment by rowanjordaan** [comment]
I expect the content gets saved in the default field. I get all themify builder generated code back in the content: rendered when I find a post (when searching for a title)

Json result when page / post found:
https://gyazo.com/2e9800d430956b588b7a7c677dca0220

**Comment by websupporter** [comment]
Yes, but for what I have in mind the actual database column would be interesting.

**Comment by rowanjordaan** [comment]
Well themify didn't create any new tables. I am looking in some of the default tables but I am not getting much wiser (seems like one big chaos with wordpress)

**Comment by websupporter** [comment]
Have a look into `wp_posts` the ID `379` do you find the searched content in the `post_content` column?

**Comment by rowanjordaan** [comment]
No post_content is empty.

https://gyazo.com/7610943072228a701ab35d11d02d05af

**Comment by websupporter** [comment]
Well, so this is what I think is going on. Usually the content is stored in `post_content`. Themify is storing it somewhere else (probably in a lot of fields in `wp_postmeta`) and is creating the content later out of this information. It is also hooked into the WP_Query (the class responsible for the search) and is listening, if a (regular) search is conducted. If so, it changes the search query so the content can be found. But it misses the search done through the REST API.

I guess in the support forums of Themify they could be more helpful, how to extend this plugin in a way it could also be used in within the REST API.

**Comment by rowanjordaan** [comment]
Ok,  Thanks for you help. Then I will contact Themify.
