### ISSUE TITLE
WP-API doesn't works in WP 4.6

### ISSUE THREAD

**Issue by albertomoral** [WP-API/WP-API#2668]
Requests to /wp-json/wp/v2/posts returns site home page HTML. It is planned to support this version of wordpress ?

**Comment by joehoyle** [comment]
@albertomoral it is supported, so I think there must be something else at play here. Have you tried disabling all other plugins to see if those are impacting this?

Thanks!

**Comment by albertomoral** [comment]
Ops, yes, I've deactivate all plugins and themes and it worked!, After reactivate all, it remains working... : / thanks so much!
