### ISSUE TITLE
Revision API content field is not rendered

### ISSUE THREAD

**Issue by pdufour** [WP-API/WP-API#2670]
Hoping to get some clarification on this, the revisions API returns "raw" content, and does not apply `the_content` filter to it. Is this a bug? The rest of the API like the posts api returns rendered content. So for instance `<p>` tags will get added.

**Comment by joehoyle** [comment]
Hmm good question, I'm not totally sure why this is the case, will look into it.

**Comment by kadamwhite** [comment]
@pdufour Can you provide an example of the sort of object you're getting back? Most objects, such as posts, will provide the content field as an object with both "raw" and "rendered" strings. "raw" contains the content as-authored, before filters; "rendered" will be post-the_content. Raw content is usually only accessible when in the "edit" context (`?context=edit`) and when authenticated.

Are you seeing "raw" data come back without the corresponding "rendered" key?

**Comment by adamsilverstein** [comment]
I think this is similar to what we have in core currently: revisions are generally retrievable only in their 'raw' form - without <p> tags or shortcode processing. This may be due in part to potential pitfalls of attempting to render a revision where the render might depend on some (non-revisioned) meta data. 

Still this does seem like it would be super useful as a feature and worth considering adding.

**Comment by pdufour** [comment]
There is no rendered field for the revisions API. The object looks like this:

```
"author": "1",
"date": null,
"date_gmt": null,
"guid": "http://localhost/1-autosave-v1/",
"id": 1,
"modified": "2015-09-06T15:01:42",
"modified_gmt": "2015-09-06T22:01:42",
"parent": 1,
"slug": "1-autosave-v1",
"title": "",
"content": "unrendered content"
```

I believe v1 provided the rendered content so is there a reason it changed in v2? Not contesting the decision, just trying to figure out if it's a bug or intended behavior.

**Comment by websupporter** [comment]
I can confirm this behavior. Right now we have `title` (string), `content` (string), `excerpt` (string). 

Will align this to the usual output

```
title:{
raw:(string),
rendered:(string)
}
```

etc.

**Comment by BE-Webdesign** [comment]
This was added in #2693.
