### ISSUE TITLE
How to attach Media properties with Post properties instead of featured_media

### ISSUE THREAD

**Issue by mister-giga** [WP-API/WP-API#2671]
As it is known, wordpress rest api works in a way that the Get request of any post gives us a post including a featured_media property, for Imaging purposes.
I have a situation where I need to get 100 Posts and I do that quite easy with 'wp-json/wp/v2/posts?per_page=100' and it works well, but the problem is that I need to get images for each post too. To do so I have to make each additional request for each post to get its Image.... so to get 100 posts, I have to send 101 requests and it is horrible waste of resources and time. 
What should I do to include image link in the Post properties to save my 100 requests and do everything with just a single request.
Thanks

**Comment by BE-Webdesign** [comment]
Hi @mister-giga,

Thank you for using the WP REST API.  I believe all you need to do is add the `?_embed` parameter to your query, so something like this `wp-json/wp/v2/posts?_embed&per_page=100` would work.  This will embed the entire featured media response, among other things, into your posts response so you will only make one HTTP request and the embedding is done internally.  I hope this satisfies your need to only make one HTTP request.

**Comment by mister-giga** [comment]
@BE-Webdesign Thank you very much! you saved hundreds of wasteful requests! WordPress Rest Api is very well done, it is very easy to do anything! Thanks

**Comment by kadamwhite** [comment]
@mister-giga Glad to hear we could be of help! If you run into any bugs let us know; for now, I'm going to close this out. Good luck with your project,
