### ISSUE TITLE
Options Endpoint

### ISSUE THREAD

**Issue by BE-Webdesign** [WP-API/WP-API#2673]
I can work on the options endpoints.  Here is how I see it breaking down.  Would love feedback on the idea as well.

There are two forms of options from my experience with WordPress site_options ( now network in 4.4 ) for multisite, and regular options, which on a multisite install are site specific.  I believe we should have two separate controller classes to handle both use cases but one class could work as well; open to ideas.

I see CRUD for single option values, which could be handled in bulk by `rest_do_request()`, being the main use of the endpoints. Currently, I do not see how collections would work or what use cases it would be necessary for.

**Comment by BE-Webdesign** [comment]
Well after thinking about this more the options endpoint pretty much has the same problem as meta used to have, regarding schema.  Maybe we should focus on the sites endpoint instead and support a couple of options like blog name, description etc.  I will start working on the site endpoint, unless someone has a good idea on how to solve the schema problem for options.

**Comment by Shelob9** [comment]
@BE-Webdesign I can't find it now, but I wrote a pass awhile back for options. DM me on WordPress slack @shelob9 if you want to brainstorm based on my attempt.

If my memory serves me correct challenges were:
- Serialization
- Choosing what to expose
- To make it RESTful, you would want to use something like `/wp/v2/options/<option-id>`, but WordPress doesn't have a function for getting an option by ID.
- Does it make sense to do it by option ID, or would you want to think of it as a way to change certain settings, like activate a theme?

**Comment by websupporter** [comment]
I think @BE-Webdesign has named the main challenges. At least the ones, I thought of too.

> support a couple of options

+1
As Jeremy Felt said in the Core chat:

> I'm not sure how much we want to get into details today, but "Create support for options" seems like a slippery slope into other admin coverage.

(https://wordpress.slack.com/archives/core/p1472071040005670)
So, to avoid this I would suggest to support only a couple of keys and leave the main part for "when admin coverage is coming".
I think a good overview to start with what options to expose can be found here: https://docs.google.com/spreadsheets/d/1vI-s8MjbEllCR0_0BmBgaGvKNm1Fa42MCoqaKCwbRyQ/edit?pref=2&pli=1#gid=0

I had a quick look into the site controller. So far, we do not restrict the access. My first thought would be `manage_options`. But probably we want to stick to the public/private-approach for coherence. `site_name` would than be readable without authentification, `admin_email` would need authentification. I guess there wouldn't be a `delete` or `create`, so only `read` and `change`, right (There is an issue for this already: https://github.com/WP-API/wp-api-site-endpoints/issues/7) ?

I would think to go with the site endpoint for now, but I was wondering how to do this in a seamless way, so once we have something like an `register_option()` (aligned to `register_meta()`), we could easily switch. Or should we work already on something like a `register_option()`?

**Comment by BE-Webdesign** [comment]
> I would think to go with the site endpoint for now, but I was wondering how to do this in a seamless way, so once we have something like an register_option() (aligned to register_meta()), we could easily switch. Or should we work already on something like a register_option()?

I think supporting a handful of base options is good for now.

The bigger question is who wants to lead the charge?  There are a lot of areas to tackle in the outline.  I am game for working on this, but if others are interested, I can focus my efforts in improving the documentation site.

**Comment by kadamwhite** [comment]
cross-linking to WP-API/wp-api-site-endpoints#13 I believe @joehoyle is leading the charge here

**Comment by kadamwhite** [comment]
[Discussed in slack 2016-10-06](https://wordpress.slack.com/archives/core-restapi/p1475762529005098): decided on `key: value` exposure of settings. Settings registry is opt-in only via `register_setting( show_in_rest => true )`; presentational attributes such as the "group" a setting belongs to, or its label, will be exposed (possibly via the schema) at a later date and in a later cycle.

**Comment by rachelbaker** [comment]
Closing with the merge of #2739
