### ISSUE TITLE
WP rest api v2 in production

### ISSUE THREAD

**Issue by nachodegrau** [WP-API/WP-API#2675]
Hi,

currently I'm working in a WordPress project. I would like to do a AngularJs frontend that consumes the data from WordPress CMS but I'm not sure it's a good idea. I have some questions about this:
1. Is wp-api v2 ready for production environment?
2. If not is ready, is good idea to use v1?
3. In the case of I will use the API, It is work fine with woocommerce?

Thanks!

**Comment by kadamwhite** [comment]
I'll start with the easy one -- don't bother with v1 :) It is severely lacking in functionality and consistency vs v2. 

Many companies are using v2 in production, and I would not personally hesitate to do so. However, as it is still not a final release there does exist the possibility of breaking changes before v2 final or before the endpoints are merged into core. That risk is increasingly minimal but I would encourage you to keep an eye on API development discussions to make sure you stay up to date. 

As for WooCommerce, I'd look at https://docs.woocommerce.com/document/woocommerce-rest-api/ -- I am not sure how tightly this will integrate with the current v2 but I believe it uses some of the same infrastructure. 

As an aside, if you're working in Angular id encourage you to check out the [documentation for my node-wpapi js client library](http://wp-api.org/node-wpapi), which can be used in the browser via webpack or browserify and may simplify some of your authentication or data retrieval needs.

**Comment by kadamwhite** [comment]
Closing the issue since it does not represent a specific bug, but please feel free to continue to discuss here in this thread!

**Comment by kosso** [comment]
I'm also interested in when v2 might hit a 'release'. 

I have a product ready and working for months. But I can't/daren't release it until this happens.
