### ISSUE TITLE
iOS app store rejection due to issues with IPv6 support

### ISSUE THREAD

**Issue by Glenncito** [WP-API/WP-API#2677]
Hi There

My iOS app was rejected from the iStore due to non-IPv6 compliance. My understanding is that the server needs to be IPv6 compatible. Would this requirement include the WP-API plugin, and if so how can I go about this?

Your response will be greatly appreciated!

**Comment by BE-Webdesign** [comment]
Hi @Glenncito,

Thank you for using the WP REST API!  The WordPress REST API has very little to do with IPv6.  IPv6 compliance has to do with the server you are running and your ISP (Internet Service Provider). You won't have to worry about the WP REST API holding your app back in that regard!
