### ISSUE TITLE
How to use encryption?

### ISSUE THREAD

**Issue by edolfuchs** [WP-API/WP-API#2679]
Has anyone implemented an encryption with wp-api? I want to know an easy way to do it

**Comment by BE-Webdesign** [comment]
The easiest way to run encryption would be to use SSL and make calls to the API over HTTPS.  Beyond that I wouldn't say any encryption implementation is easy to set up.  I am going to close this issue as it does not relate to a bug for the API, feel free to continue discussion here.

**Comment by edolfuchs** [comment]
Thanks.
