### ISSUE TITLE
Add endpoint to read and write configuration 

### ISSUE THREAD

**Issue by heiglandreas** [WP-API/WP-API#2680]
Wouldn't it be helpful to have an endpoint that can read and write WordPress-Configurations?

That way one could adapt the configuration of a website via the REST-api which would ease automation of the deployment-process. 

See https://github.com/forumone/wp-cfm/issues/65

**Comment by BE-Webdesign** [comment]
Hi @heiglandreas 

I believe maybe what you want is the [sites endpoints](https://github.com/WP-API/wp-api-site-endpoints), that would cover a bunch of the configuration for a WordPress site.   The sites endpoint isn't nearly as far along as the other endpoints, so it may not cover what you need now, but it will in the future. We are always looking for new contributors!

**Comment by kadamwhite** [comment]
@heiglandreas I suspect @BE-Webdesign is right, but can you clarify what sort of configuration you're looking to set? A description about your use-case would be helpful.

**Comment by heiglandreas** [comment]
I was thinking about a way to configure a wordpress-site from remote. For me that would also include all the configuration settings from the different plugins. That's far more than the REST-API is currently thought for (at least I believe so) but it might be an idea to keep in mind for the future. That way it would be possible to manage multiple wordpress-sites from anywhere as long as you have a browser available. And it would also allow automated management of a local wordpress-site not via the CLI but via cURL-commands.

**Comment by BE-Webdesign** [comment]
@heiglandreas,

> For me that would also include all the configuration settings from the different plugins

If the plugin authors write endpoints to handle their options, then they will show up in the API index, enabling those sort of modifications to be done through the API. However, that could and should not be handled by WordPress core.

The potential for your use case is already there and when the sites endpoint is finished, managing WordPress's core site options will be enabled through that endpoint. For individual plugin options, those would need to be registered by the plugin authors, or by someone who wants to write a plugin for that plugin.

**Comment by rmccue** [comment]
Closing in favour of #2673 instead.
