### ISSUE TITLE
how to add rest api to freely created wordpress web site?

### ISSUE THREAD

**Issue by mister-giga** [WP-API/WP-API#2681]
![image](https://cloud.githubusercontent.com/assets/7438859/18249772/630951aa-7391-11e6-9295-e95e4da7ec9a.png)

**Comment by JodiWarren** [comment]
You don't need the plugin on wordpress.com. Here are the developer docs: https://developer.wordpress.com/docs/api/

The plugin is for adding an API to self-hosted sites, which use the software from wordpress.org.

**Comment by kadamwhite** [comment]
Beat me to the punch, @JodiWarren — that's correct, this plugin cannot be added to WordPress.com but they provide a great API of their own. Over time, the two APIs are planned to be rolled in to one, so that the same interfaces can apply to both self-hosted and WordPress.com websites.
