### ISSUE TITLE
Check if REST API (V2) is disabled

### ISSUE THREAD

**Issue by joneslloyd** [WP-API/WP-API#2685]
Hi there,

I'm just wondering if there's a recommended way to check if the user has (via the provided actions, or some other means) disabled the REST API?

I know that I could try an API URL and see if 503 is returned, but is there a way, in PHP, to do this?

Thanks!

**Comment by websupporter** [comment]
If someone disabled the  REST API using the `rest_enabled` filter I think this should work:

```
$is_enabled = apply_filters( 'rest_enabled', true );
```

**Comment by joneslloyd** [comment]
Thanks a lot - I'll give that a try. 👍

**Comment by joneslloyd** [comment]
Can confirm it works a treat. Thanks!
