### ISSUE TITLE
Submit a contact form using WP REST API v2

### ISSUE THREAD

**Issue by KaiP-598** [WP-API/WP-API#2686]
Hi,
Currently my website is using contact form 7 and custom contact form, however after doing days of researching, I could not find any reference of how to submit a contact form using WP REST API, can anyone please help me??

BIG THANKS!

**Comment by BE-Webdesign** [comment]
Hi @KaiP-598,

Those are questions for the contact form 7, and custom contact form support forums.  The API is just something those plugins use. You need to get support from them on how to use the API with their plugin.
