### ISSUE TITLE
Block API without login

### ISSUE THREAD

**Issue by Sorcim** [WP-API/WP-API#2688]
Hello,

I searched on the documentation but i didn't find. 

Is it possible to block all request without oauth authentication ?

Thanx !

**Comment by kadamwhite** [comment]
You can use the gist linked in #2497 to require authentication; this is a common question and we'll try to get a solution into the docs site this week. Thanks for raising the issue!

https://gist.github.com/danielbachhuber/8f92af4c6a8db784771c

**Comment by kadamwhite** [comment]
(moved issue over to docs site)
