### ISSUE TITLE
Access to draft post forbidden with proper oauth credentials from node server

### ISSUE THREAD

**Issue by Petroochio** [WP-API/WP-API#2689]
So here's the lowdown.

We have a wordpress server and a node server running in the same domain. The node server is sending the whole website and we are rendering the content with React. The issue this caused was that an author could not preview their content without publishing. This is not ideal.

We set up a page that will guide the user through the oauth process and then form the request to get the draft post in question(we overrode the preview button to take people to this page). The current issue is that when we make the request to grab the draft post it isn't even checking our oauth credentials, and returns a `403 forbidden` error.

`{"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":403}}`
^ error in question here

I have walked through the process on postman and it all works there. I'm able to get the draft post I'm looking for with no errors.

If it helps our folder structure is this (well this is all that really matters, obviously there are more things)
/ root
- /node-app
  - the server is run from here
- /wp-admin
- /wp-content
- /wp-includes
- ...the usual wordpress stuff

Anyone know what's going on? As I said, it appears that when I make this request the wordpress api isn't even checking for my auth params, but I haven't a clue past that.

Thank you in advance!

**Comment by BE-Webdesign** [comment]
Hi @Petroochio,

Thank you for using the WP REST API.  You are getting a `403` status, which means you are authenticating, but the user you are authenticating as does not have the proper permissions.  If it is working in postman, potentially in the app, something is going wrong and the wrong user is being authenticated.  I would recommend doing some debugging to see what user is trying to make the request that gives you a `403`, if you haven't already.  Let me know if you already did that.

**Comment by Petroochio** [comment]
@BE-Webdesign So I dug around a bit more and found out that `get_current_user_id()` is returning 0, but the postman request is getting a user id of 4 (which is what I expect).

It also doesn't go into the `check_token` function at all, but it does call it when making a request from postman...

EDIT: My leading guess atm is that whatever is supposed to trigger the oauth plugin check tokens is just not happening when the AJAX request is coming from the same domain. So I'm trying to locate where the oauth plugin hooks into the rest API, but I just can't tell where that is hooking up.

**Comment by Petroochio** [comment]
Well I have some mediocre news. I found the culprit. There is a cookie that is triggering one of the `determine_current_user` filters and is preventing it from hitting oauth. Unfortunately it is not a cookie that allows the user to get the data I want, so I working on a way to clear it out. 

Also inconveniently the cookie in question is a `httponly` cookie so I can't just clear it with JS :/

**Comment by BE-Webdesign** [comment]
https://github.com/WP-API/OAuth1/issues/156 This could also be linked to your problem.

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support are no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
