### ISSUE TITLE
Capability Discovery

### ISSUE THREAD

**Issue by tlovett1** [WP-API/WP-API#2690]
It would be very nice to have a way to determine what a user can do given their credentials (or lack there of). The schema tells which HTTP methods each route supports but not what methods the current user can use.

**Comment by georgestephanis** [comment]
I'd be interested to see how the permission_callback running for each endpoint affects response time.  It also would be difficult to do in the abstract, as users may be able to edit some posts but not others, and there's really no way to tell in the permission callback without a specific post id to test against (for example)

Alternately, it's possible to maybe have an endpoint that you could pass a single cap or array of caps to find out what caps the current user can do?  That's my personal preferred way of tailoring a JS ux to what the user can actually do.

**Comment by BE-Webdesign** [comment]
@tlovett1 

That is a really cool idea. You could add the necessary schema to the API index if you wanted to already when registering routes, in addition to hooking in to the REST server's dispatch to fire additional callbacks. However, I would probably suggest against doing that for a few reasons: performance, and requests are usually contextual as georgestephanis pointed out, so it would be an unnecessary amount of work to do this well.

Maybe a better solution is to extend `wp-json/users/me` to support showing what capabilities the user has, and use that information on the client side to control your app?  I am not sure if that would be a bad idea from a security perspective though.

**Comment by georgestephanis** [comment]
> Maybe a better solution is to extend wp-json/users/me to support showing what capabilities the user has, and use that information on the client side to control your app? I am not sure if that would be a bad idea from a security perspective though.

That's the thing ... there's currently no registration system for capabilities in core.  Any plugin can make custom capabilities that they check via map_meta_cap (and many do) -- they're only defined by usage -- by default, caps derive from roles, but can be filtered in or out, up or down, whatever.  I'd much sooner have it be a prompt and response endpoint -- somewhat similar to what Jetpack has implemented in the WPCOM REST API here: https://github.com/Automattic/jetpack/blob/master/json-endpoints/jetpack/class.jetpack-json-api-check-capabilities-endpoint.php

**Comment by georgestephanis** [comment]
(that being said, if we want to reconsider how authentication permissions are calculated and have some sort of list of capabilties when registering the endpoint, in lieu of a function callback, that would be simpler to disclose on each endpoint discovery)

**Comment by BE-Webdesign** [comment]
So is the goal to have requests for the index not show certain endpoints, if the authenticated user cannot access them, or is the goal to expose a minimum capability for the endpoint, where the capability is somehow registered to the index?

By index, I mean the information you get by doing a `GET` request to /wp-json or one of the namespace routes.

**Comment by rmccue** [comment]
> I'd be interested to see how the permission_callback running for each endpoint affects response time.

It actually is running on every request already; the `Allow` header reflects the permissions. Check out `rest_send_allow_header`.

Doing more granular permission checks than this isn't easy, and the amount of work to implement the checks around this would way outweigh the benefits (and is likely not particularly useful to the user). The fields you're allowed to change depend on user capabilities (inc. roles) _and_ object state.

**Comment by rmccue** [comment]
> Alternately, it's possible to maybe have an endpoint that you could pass a single cap or array of caps to find out what caps the current user can do?

This is also available on the user object with `context=edit` already.

Going to close this ticket out, as there's already ways to get a) general capabilities available to the user, and b) the actions available on a post. There are things that aren't exposed from this but which require the app to understand the WordPress workflow (such as `edit_posts` vs `edit_published_posts` and how those interplay with the object); this is not likely to change.

**Comment by BE-Webdesign** [comment]
`rest_send_allow_header()` definitely seems like it would take care of the issue, thank you for pointing that out!

**Comment by tlovett1** [comment]
With `rest_send_allow_header` wouldn't I have to ping a route to see whether I have access or not? I'd like to ping one endpoint to find all the endpoints that I have access to use.

**Comment by BE-Webdesign** [comment]
I believe it would only work per route from the way `rest_send_allow_header()` appears to work.  You could create your own endpoint that checks every route by using `rest_do_request()` on all available routes then saving the allow header for that route as your response.  That could be a relatively easy way to get what you need all in one HTTP request.
