### ISSUE TITLE
<!-- html is corrupted --> on http://pinkfloyd.eu/wp-json

### ISSUE THREAD

**Issue by cemarbag** [WP-API/WP-API#2691]
Hello;

i have a problem on my webpage. 

why to have?
 on http://pinkfloyd.eu/wp-json

i request for your help please.
Thank you.

**Comment by kadamwhite** [comment]
@cemarbag that URL loads correctly as JSON for me -- how are you making the request that you are seeing that error? Through a web browser? Or by requesting the API index programmatically?

**Comment by cemarbag** [comment]
Developer of "https://github.com/shprink/wordpress-hybrid-client" project told me that i have this problem.

when i type his url, application works but for my url doesn't work. i tried to change my permalink to "day and post" format and deactivate my wp fastest cache plug-in but still same. i can't understand Whats wrong on my api?

**Comment by cemarbag** [comment]
When i run simulation on chrome, i see this errors on console;

ImgCache init: success!
bundle-87bc5d.js:27066 Init: success!
bundle-87bc5d.js:27066 reinit load false
bundle-87bc5d.js:27066 wphcLoader attempt: 0
bundle-87bc5d.js:25272 GET http://pinkfloyd.eu/wp-jason/wp/v2/posts?_embed=true&filter%5Border%5D=desc&filter%5Borderby%5D=date&filter%5Bpost_status%5D=publish&page=1&per_page=5 (anonymous function) @ bundle-87bc5d.js:25272sendReq @ bundle-87bc5d.js:25065serverRequest @ bundle-87bc5d.js:24775processQueue @ bundle-87bc5d.js:29399(anonymous function) @ bundle-87bc5d.js:29415$eval @ bundle-87bc5d.js:30667$digest @ bundle-87bc5d.js:30483$apply @ bundle-87bc5d.js:30775(anonymous function) @ bundle-87bc5d.js:32604completeOutstandingRequest @ bundle-87bc5d.js:19466(anonymous function) @ bundle-87bc5d.js:19742
:8080/#/public/posts:1 XMLHttpRequest cannot load http://pinkfloyd.eu/wp-jason/wp/v2/posts?_embed=true&filter%5Border%5D=desc&filter%5Borderby%5D=date&filter%5Bpost_status%5D=publish&page=1&per_page=5. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 404.

**Comment by BE-Webdesign** [comment]
Hi @cemarbag,

Thank you for using the WP REST API.

There is an HTML comment that is breaking the JSON, most likely another plugin is outputting this HTML and breaking your response. As you mentioned it is the `<!-- html is corrupted -->`. I recommend disabling plugins on a staging environment if you have one until you find which plugin is causing the problem.

From a quick google search it could potentially be your caching plugin outputting that.

**Comment by cemarbag** [comment]
i tried it on my other website and i also delete all plugin expect rest api but it didn't work. on my other website "lifecodes.net" there is only one plugin exist now. i don't know whats wrong ? :(

**Comment by websupporter** [comment]
Just to hop quickly in, although I think this is not the problem: You are using `wp-jason` instead of `wp-json` in the request above.

**Comment by cemarbag** [comment]
Hi @websupporter i am using wp-json 
<img width="382" alt="ekran resmi 2016-09-09 22 21 53" src="https://cloud.githubusercontent.com/assets/21284264/18399896/06f0b4b4-76dc-11e6-9c4a-514560e5e47a.png">

**Comment by cemarbag** [comment]
this is weird issue, my pages couldn't open on standard crome version but i downloaded Crome Canary and voila! it worked. Maybe it was a problem about cookies on my browser but everything is fine now.

**Comment by BE-Webdesign** [comment]
Yeah, maybe it is a chrome thing because the response was broken for me as well. Strange.

**Comment by cemarbag** [comment]
people who has similar problem try to download "Chrome Canary" instead of use normal chrome

**Comment by BE-Webdesign** [comment]
I use chrome all of the time with the API though and never encountered this problem so idk why your site in particular is giving that response.

**Comment by rmccue** [comment]
This HTML comment is coming from a caching plugin you have installed; see also https://github.com/wp-cli/wp-cli/issues/2167
