### ISSUE TITLE
Object type in the `$wp_rest_additional_fields` globals is misleading/problematic.

### ISSUE THREAD

**Issue by jtsternberg** [WP-API/WP-API#2692]
Object type should really be the higher order object types like `post`, `term`, `user`, `comment`, with the sub-object types (custom post types, custom taxonomies, etc) being a sub-array. The fact that post-types, taxonomies, user, etc are all mashed together causes many types of problems, but most specifically, the fact that registered `$wp_rest_additional_fields` indexes may get stomped if, say, a custom taxonomy and custom post type have the same registered slug.

**Comment by danielbachhuber** [comment]
> indexes may get stomped if, say, a custom taxonomy and custom post type have the same registered slug.

WordPress already has this problem elsewhere.

**Comment by jtsternberg** [comment]
I'm also reporting, as this type of registration makes it pretty difficult to register a generic `get_callback`/`update_callback`, as you then would need to suss out which object-type is being passed through. If you're saying this change is not necessary or will not happen, I will look into other ways (likely registering separate callbacks?) to determine this.

**Comment by jtsternberg** [comment]
by 'suss out', I mean, you may get "custom-post-type" passed to the callback, or "custom-taxonomy" but either way, I would need to take that string and determine what the master object is, 'post', 'term', 'comment', 'user', etc.

**Comment by joehoyle** [comment]
As mentioned above, there's much larger problems that arise when your have a name collision with something like a a CPT and a Taxonomy, with things like actions / filter names, rewrite rules etc so I don't think this is a new problem. Also, not all things in WordPress _do_ have sub types, for example users.

The API to a large expect does away with the "object type" grouping, one CPT is as different to another as a comment is. They are at different routes, have different fields and different capabilities. 

I'm going to close this as a #wontfix, however @jtsternberg if you strongly disagree I don't want to shut you down, so of course re-open.

**Comment by jtsternberg** [comment]
Thanks guys, and thanks for your consideration @joehoyle. I understand your perspective and makes sense to me. I think we're good.
