### ISSUE TITLE
Required custom fields not honored when registered in rest_api_init

### ISSUE THREAD

**Issue by psalz** [WP-API/WP-API#2694]
When adding a custom field inside a `rest_api_init` handler, setting `required => true` doesn't have any effect.

Example:

``` php
add_action('rest_api_init', function() {
  register_rest_field('post', 'foo', [
    'get_callback' => 'get_foo',
    'update_callback' => 'set_foo',
    'schema' => [
      'required' => true
    ]
  ]);
};
```

Requesting `POST /posts` does not return the expected `rest_missing_callback_param` error.

This is due to the call to `WP_REST_Controller::get_endpoint_args_for_item_schema` being made via `create_initial_rest_routes` (which in turn runs on `rest_api_init:0`, well before a default priority hook would run). This means the schema entry for `foo` doesn't even exist at that point, and so it isn't included in the arguments for the `POST` handler.

This issue can be circumvented by registering custom fields on `init` or `rest_api_init:-1`, but I find that to be rather unintuitive.

**Comment by websupporter** [comment]
Is handled in https://github.com/WP-API/WP-API/issues/2810
