### ISSUE TITLE
API doesn't respond after upgrading from V1 to V2

### ISSUE THREAD

**Issue by matt-bernhardt** [WP-API/WP-API#2698]
I just tried disabling/removing the v1 plugin, and enabling the v2 plugin, on a development site (a network install). After completing the upgrade, there is no API responding at the path `/wp-json/wp/v2`

This is the context:
- Wordpress 4.4.2 (multi-site network, directory setup - so `example.org/`, `example.org/site1/` etc)
- Version 2.0-beta13.1 of the WP REST API, enabled at the network level
- Other network-enabled plugins (which I'd really prefer not to disable, but can if needed): EmbedIt Pro, Media Library Assistant, W3 Total Cache, and Widget Importer & Exporter
- APC is installed, but I've cleared that cache and still get no response

Observed behavior:
- Wordpress is serving HTML documents at all expected endpoints:
- `example.org/wp-json/wp/v2/posts` (network root)
- `example.org/site1/wp-json/wp/v2/posts` (other site on the network)

Upgrade process was:
1. Upload v2 plugin to `wp-content/plugins/rest-api`
2. Disable v1 plugin via network plugin list
3. Enable v2 plugin via network plugin list
4. Clear W3 Total Cache and APC cache
5. Visit endpoints in browser

Is there something that I'm missing in this? The development network isn't publicly visible, so I can't share access to it unfortunately. I had thought that I had tested this upgrade path on localhost, but apparently I either missed something or misunderstood. The documentation for installing the v2 plugin doesn't specify any sort of special process, so I wasn't anticipating anything difficult.

Many thanks for any guidance anyone can provide...

**Comment by matt-bernhardt** [comment]
I'm not sure whether this helps, but I've managed to reproduce this error on two consecutive builds of a site on localhost. The first was done as a network, with the referenced plugins enabled. The second was a single site (no network), with just the API plugins added.

Steps to reproduce:
1. Install Wordpress (4.4.2 in my case)
2. Install v1 plugin `json-rest-api`, version 1.2.5
3. Visit `/wp-json`, note valid JSON response
4. Add v2 plugin `rest-api`
5. Reload `/wp-json`, note valid JSON response
6. Disable v1 plugin, delete from plugins directory
7. Reload `/wp-json`, note HTML response
8. Enable v2 plugin `rest-api`, version 2.0-beta13.1
9. Reload `/wp-json/wp/v2`, note HTML response

There are two related questions at this point. First, what am I doing wrong to trigger this behavior? And second, how do I repair the site to restore proper function?

**Comment by rmccue** [comment]
You may have to flush the rewrite rules; head to Options > Permalinks to flush them (you don't need to save, just visit the page). See if that helps?

**Comment by matt-bernhardt** [comment]
Yep - that seems to have allowed the v2 plugin to function. Thanks!
