### ISSUE TITLE
Add support for password-protected posts

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#2701]
Previously: #1055.

We need to re-add support for password-protected posts in a nice, sane way. I've created [a core ticket](https://core.trac.wordpress.org/ticket/38056) to do step 1 of this: allow us to control authentication.
## Step 2: Work out how to handle passing the passwords.

We still need to work out how to actually pass the passwords in. There are basically three options:
### Cookies

Something like `Cookie: wp_rest_password=xyz` or `wp_rest_password_42=xyz` maybe. This overloads the meaning of cookies, and may not actually be possible to do from in-browser JavaScript.
### Authorization Header

`Authorization: Basic ...` or potentially a custom scheme like `Authorization: WP-Post ...`. The spec says you can't have multiple authorization headers, so it wouldn't be possible to be authenticated _and_ send a per-post password.
### Query Param

Something like `password=...` in the query. Not necessarily a terrible idea.
### Things we can't do
- Custom header: these aren't guaranteed to affect caching, so if a request includes a password and gets cached, the password is rendered useless.
- Existing cookie system: the cookie name includes a hash (`COOKIEHASH`), so is unguessable. This isn't usable for API clients.

**Comment by rmccue** [comment]
I dug into this further; query parameters are the only viable option. We [discussed briefly on Slack](https://wordpress.slack.com/archives/core-restapi/p1474296851002021).

All that remains is to implement this. :)

**Comment by kadamwhite** [comment]
Resolved by #2720

**Comment by jetaro1** [comment]
thank you :)
