### ISSUE TITLE
Can I get the created `post_tag` on the create endpoint?

### ISSUE THREAD

**Issue by rafaelcneves** [WP-API/WP-API#2703]
I'm working on a project that manage wordpress blogs.
And now I'm creating tags from my app, and I need to persist this tag on my app.
But when I create a tag using wp-api, i don't get anything from created tag. 
Can I return entire tag on the create response? Or simply get a clean information from created tag?

Thanks

**Comment by BE-Webdesign** [comment]
Hi @rafaelcneves,

Thank you for using the WP REST API.  To clarify by tag you mean you are creating a new term for the `post_tag` taxonomy?

I am assuming that is what you mean, if not please let me know.  When you do a `POST` request to create a tag, you should be returned the new tag as a response object, so something is potentially going wrong.  Please post an example request and response for what you are trying to achieve.

**Comment by rafaelcneves** [comment]
Yes, it's about `post_tag`.
It's weird because I got `null` on the body of response, and it occurs with all `POST` create methods.
Here is the Guzzle debug log:

```
* Hostname was NOT found in DNS cache
*   Trying 172.17.0.1...
* Connected to rest.oconhecimento.com.br (172.17.0.1) port 8080 (#0)
> POST /wp-json/wp/v2/tags HTTP/1.1
User-Agent: GuzzleHttp/6.2.1 curl/7.38.0 PHP/5.6.15
Content-Type: application/json
Host: rest.oconhecimento.com.br:8080
Authorization: OAuth oauth_consumer_key="*****", oauth_nonce="******", oauth_signature="******", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1474029600", oauth_token="******", oauth_version="1.0"
Content-Length: 15

* upload completely sent off: 15 out of 15 bytes
< HTTP/1.1 201 Created
< Date: Fri, 16 Sep 2016 12:40:00 GMT
* Server Apache/2.4.10 (Debian) PHP/5.6.14 is not blacklisted
< Server: Apache/2.4.10 (Debian) PHP/5.6.14
< X-Powered-By: PHP/5.6.14
< X-Content-Type-Options: nosniff
< Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
< Access-Control-Allow-Headers: Authorization
< Expires: Wed, 11 Jan 1984 05:00:00 GMT
< Cache-Control: no-cache, must-revalidate, max-age=0
< Pragma: no-cache
< Last-Modified: 
< Location: http://rest.oconhecimento.com.br:8080/wp-json/wp/v2/tags/143
< Allow: GET, POST
< Content-Length: 972
< Content-Type: application/json; charset=UTF-8
< 
* Connection #0 to host rest.oconhecimento.com.br left intact
```

**Comment by rmccue** [comment]
Something appears to be wrong on the Guzzle side; note that the returned `Content-Length` header here is 972 bytes, which indicates the server is actually sending a response back.

**Comment by rafaelcneves** [comment]
I analyzed my response better and saw that I am getting a warning message which I imagine to be from PHP. This is the message:

> Unhandled Exception
> 
> Message:
> 
> Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead.
> Location:
> 
> Unknown on line 0

**Comment by rmccue** [comment]
You may need to follow the advice in that warning and set `always_populate_raw_post_data=-1` in your php.ini. We use `php://input` internally, but we check `$HTTP_RAW_POST_DATA` for compatibility with older versions of PHP, which can cause that warning.

I'm not sure why that's causing an exception though; PHP won't throw an exception on that warning normally, so you may have a custom error handler that's causing that to be sent.
