### ISSUE TITLE
Get last post after modified 

### ISSUE THREAD

**Issue by RomainGaillard** [WP-API/WP-API#2706]
Hello, 

I want get a last post after modified. 
I test multiple url, but not work:  =/ 

`/wp-json/wp/v2/posts?filter[modified_gmt][after]="2016-09-16T14:36:58" 
`

Please can you give me a solution ? 
I not use PHP, so, this solution: 

`
$args = array(
    'date_query' => array(
        array(
            'column' => 'post_modified_gmt',
            'after'  => '1 month ago',
        ),
    )
);
$query = new WP_Query( $args );
`

it's not possible for me ! 

Can you help me ? And sorry for my bad english. 
Thank you.

**Comment by rmccue** [comment]
Try `?filter[date_query][0][column]=modified_gmt&filter[date_query][0][after]=2016-09-16T14:36:58` instead.

**Comment by RomainGaillard** [comment]
Sorry your solution not work =/ 
The field "modified_gmt" no work.

**Comment by BE-Webdesign** [comment]
@RomainGaillard `/wp-json/wp/v2/posts?filter[date_query][0][column]=post_modified_gmt&filter[date_query][0][after]=1+month+ago` should work, for what you are trying.

**Comment by RomainGaillard** [comment]
@BE-Webdesign  Thank you very much ! Your solution work correctly !!! Thank you verry verry verry much.

**Comment by BE-Webdesign** [comment]
No problem thank you for using the REST API, do great things with it!

**Comment by vignesh-s** [comment]
Is this solution working now also?, I need to filter posts modified after specific date in WordPress v4.8.3

**Comment by yongzhihuang** [comment]
Wondering about @vignesh-s 's question too
