### ISSUE TITLE
Comments created via the API do not trigger 'comment_post' trigger

### ISSUE THREAD

**Issue by Critter** [WP-API/WP-API#2707]
Is there another action I can hook to catch when a comment is posted via the api or do I need to roll out my own with a custom endpoint?

**Comment by websupporter** [comment]
Right now, `wp_insert_comment()` is used instead of `wp_new_comment()`. But you could use the action hook `rest_insert_comment`:

```
        /**
         * Fires after a comment is created or updated via the REST API.
         *
         * @param array           $comment  Comment as it exists in the database.
         * @param WP_REST_Request $request  The request sent to the API.
         * @param boolean         $creating True when creating a comment, false when updating.
         */
        do_action( 'rest_insert_comment', $comment, $request, true );
```

**Comment by kadamwhite** [comment]
Closing as provisionally solved, leave a comment if it's not!

**Comment by rmccue** [comment]
We _could_ consider changing the function, but `wp_new_comment` does a lot of things we don't want, so this is unlikely to change. You could [file a ticket on Trac](https://core.trac.wordpress.org/) instead though if you'd like the filter moved into `wp_insert_comment` (or a new one added).
