### ISSUE TITLE
Keep user's privileges on accessing contents in JSON response

### ISSUE THREAD

**Issue by 1geeky** [WP-API/WP-API#2709]
Hello,

What Access manager plugin keeps the privileges on REST API responses?

I want restrict access to certain posts, categories etc for a particular role, So when the user of that role authenticates via HTTP request, could not access to that post.

Thanks

**Comment by rmccue** [comment]
The REST API uses standard WordPress capability checks, so anything that uses WordPress capabilities correctly should work.

**Comment by 1geeky** [comment]
@rmccue Thank you.
But a restricted user could get the JSON output with WP-API plugin while it works correctly with [JSON-API plugin](https://wordpress.org/plugins/json-api). I've used [Advanced Access Manager plugin ](https://wordpress.org/plugins/advanced-access-manager/) (free version) to define access rules and test that for single posts.

As you may see in the images are attached, The JSON output of **JSON-API plugin** includes access parameters while WP-API doesn't. I'm not sure this would be the reason but after all, JSON-API recognizes and applies roles and capabilities is defined in my Wordpress site.

It's a non-restricted user request on both attached images:

![wp-api-plugin](https://cloud.githubusercontent.com/assets/373027/18773654/ef8f6e96-815d-11e6-83ed-27c4917b023d.png)
WP-API plugin response

![json-api-plugin](https://cloud.githubusercontent.com/assets/373027/18773655/ef95f766-815d-11e6-979c-8fa5dfce34a8.png)
JSON-API plugin response

**Comment by rmccue** [comment]
The REST API doesn't return any post meta at the moment, which is what the field in your screenshot is. We're [adding support for that](https://github.com/WP-API/wp-api-meta-endpoints/pull/15) soon, but the plugin will need to opt-in to that support.

**Comment by 1geeky** [comment]
@rmccue Is the post meta the reason of not showing restricted content to users?

what access manager plugin do you suggest which will work will REST API plugin?

**Comment by BE-Webdesign** [comment]
@1geeky,

I don't know of any plugins yet that do content restriction via the API.  You could in the meantime use `register_rest_field()` to [add in the custom fields you need for your response](http://v2.wp-api.org/extending/modifying/).  You would still need to handle the content restriction on your end, as exposing those custom fields, on its own, will not restrict content.
