### ISSUE TITLE
If taxonomy is registered with a non-standard rest_controller_class the API response on posts is incorrect

### ISSUE THREAD

**Issue by AramZS** [WP-API/WP-API#2710]
My current implementation of the API attempts to minimize code reuse by extending existing controllers. 

My Terms controller for the custom name-spaced endpoint looks like this:

```
class PF_REST_Terms_Controller extends WP_REST_Terms_Controller {

    public function __construct( $post_type ) {
        parent::__construct($post_type);
        $this->namespace = 'pf/v1';
    }

    public function register_routes(){
        parent::register_routes();
    }

}
```

It's then registered like so:

```
        register_taxonomy( $this->tag_taxonomy, '', apply_filters( 'pf_register_feed_tag_taxonomy_args', array(
            'labels' => $labels,
            'public' => true,
            'show_admin_columns' => TRUE,
            'show_in_nav_menus' => TRUE,
            'show_ui'           => TRUE,
            'show_admin_column' => TRUE,
            'show_in_menu' => PF_MENU_SLUG,
            'hierarchical'          => TRUE,
            'update_count_callback' => '_update_post_term_count',
            #'show_in_menu' => PF_MENU_SLUG,
            'rewrite' => false,
            'show_in_rest'       => true,
            'rest_base'          => 'folders',
            'rest_controller_class' => 'PF_REST_Terms_Controller',
        ) ) );
```

But the API term response on a post object will look like: 

```
        "wp:term": [
            {
                "taxonomy": "post_tag",
                "embeddable": true,
                "href": "http://local.wordpress.dev/wp-json/wp/v2/tags?post=5766"
            },
            {
                "taxonomy": "pf_feed_category",
                "embeddable": true,
                "href": "http://local.wordpress.dev/wp-json/wp/v2/folders?post=5766"
            }
        ],
```

As you can see, it is using the wrong namespace in this situation. Is there an existing solution to this or should I examine the surrounding code and author a pull request?

**Comment by nerrad** [comment]
It looks like the `wp/v2` namespace is hardcoded in `WP_REST_Posts_Controller::prepare_item_for_response`:

```
$terms_url = add_query_arg(
                    'post',
                    $post->ID,
                    rest_url( 'wp/v2/' . $tax_base )
                );
```

I'm not sure what the best solution would be for this, but it seems either:
1. This method should grab whatever rest controller is registered for the taxonomy and use that to derive the namespace OR
2. add a `rest_namespace` arg to the `register_taxonomy` api and check for that.

**Comment by AramZS** [comment]
@nerrad Yeah, the issue is that a Post object may live under one controller and a Term attached to it may live in another controller. It seems to me that we could add a namespace arg, but the best solution would be to check the controller's namespace.

I'm concerned about performance issues though, because to get the namespace for the response would require initiating the controller a 2nd time (once to add the term to the API, once to check for it). I don't suppose there's any way to check to see if a controller has already been instantiated for that particular term and to get the namespace from there?

**Comment by AramZS** [comment]
I suppose we could also filter `apply_filters( "rest_prepare_{$this->post_type}", $response, $post, $request );`? But that seems like a non-optimal solution?

**Comment by rmccue** [comment]
A long time ago when we started v2, we spent quite a long time digging into how we could do lookups by post type and stuff like that to build URLs. As it turned out, the implementation _and_ conceptual complexity of this turned out not to be viable at all.

Instead, we decided that the API should be internally consistent, and if you want to change anything in it, it's up to you to handle changing links as well. This includes filtering things like `rest_prepare_{type}` if you need to. It sucks, but it's the optimal solution.

**Comment by AramZS** [comment]
Ok, so for the reference of future folk who encounter this issue. The taxonomy URL is under `links`, which is protected and not accessible through normal means. Instead the links entry for taxonomy has to be pulled out, manipulated and replaced. For my use case it seemed the only way to deal with it was to do this: 

```
    // Hook to filter 'rest_prepare_{post_type}' to activate
    public function filter_wp_to_pf_in_terms( $data, $post, $request  ){
        $links = $data->get_links();
        $data->remove_link("https://api.w.org/term");
        foreach ( $links["https://api.w.org/term"] as $key=>$term_link ){
            if ( 0 <= strpos($term_link["href"], 'wp/v2/folders') ){
                $term_link["href"] = str_replace('wp/v2/folders', 'pf/v1/folders', $term_link["href"] );
                $links["https://api.w.org/term"][$key] = $term_link;
            }
        }
        $data->add_links( array(
                "https://api.w.org/term" => $links["https://api.w.org/term"]
            )
        );
        return $data;
    }
```
