### ISSUE TITLE
Steps to take after a clone / fork

### ISSUE THREAD

**Issue by reekrd** [WP-API/WP-API#2711]
Could someone give me an intro on what steps to take once after cloning or forking the project? 
What is the process to make a build that is the actual wp plugin?

This I've done:
npm install -g grunt-cli
npm install
composer install

But not sure where to go from here. 

Thanks
.r

**Comment by kadamwhite** [comment]
@reekrd for development you can run the plugin in-situ with just the steps you described above; I just clone the repository to my `wp-content` directory, take the steps you described and things work as expected. I will follow up with @rmccue & others around what steps are taken to transform the repository into the form shown in the plugin directory, but what you see here should be all you need, unless I misunderstand your question?

**Comment by rmccue** [comment]
Take a look at the [release.sh](https://github.com/WP-API/WP-API/blob/develop/bin/release.sh) script to see how the plugin is transformed into the version on the plugin repository. :)
