### ISSUE TITLE
PUT to page title receives message: "Invalid parameter(s): template (template is not one of tpl-no-header-footer.php, tpl-sidebar.php)"

### ISSUE THREAD

**Issue by beatelite** [WP-API/WP-API#2713]
When I put to a page title, I get a really weird: "Invalid parameter(s): template (template is not one of tpl-no-header-footer.php, tpl-sidebar.php)"

I just updated from beta11 to the latest master ( 13 I think it is now). It worked in 11. 

When I update titles for posts or any CPT, they all work. Pages are the only issue. 

I have searched but can't seem to find anything on this. Any ideas?

**Comment by rmccue** [comment]
What is the exact data you're sending with this request?

**Comment by rmccue** [comment]
No response in a week; let us know if you need more help!
