### ISSUE TITLE
403 Forbidden problems

### ISSUE THREAD

**Issue by simonpeters** [WP-API/WP-API#2714]
Hi,

I'm using cookie authentication and on my local dev server everything works fine.

On my online web server though I have problems with PUT and DELETE requests. They always return "403 Forbidden". POST does work online.

The PUT and DELETE request return the 403 header and the resource in question. So I don't get any kind of error message.

I'f tried adding trailing slashes to the requests but I still have the same results

Anyone else come across this issue?

**Comment by rmccue** [comment]
Is the 403 generated by Apache/nginx, or by the REST API? i.e. is the response body JSON or a HTML page?

**Comment by simonpeters** [comment]
It's JSON, it just responds with the corresponding resource. But it doesn't delete or edit it.

**Comment by rmccue** [comment]
This seems like a potential misconfiguration of your server software; it should never return a 403 _and_ the resource data. 403 should cause an error description object to be added to the body instead. Try contacting your host about this.

**Comment by rmccue** [comment]
Closing out; let us know if you need anything else!
