### ISSUE TITLE
 How to replace an image in WordPress via REST API 2.0?

### ISSUE THREAD

**Issue by vsego** [WP-API/WP-API#2715]
Originally published on [Stackoverflow](http://stackoverflow.com/q/39598454/1667018).

I have some images uploaded on a WordPress site that is to be completely REST controlled and I'm having trouble updating them. Altering image data is simple, via `POST` requests to `.../media/<id>`, but I can find no way to actually replace the image **content** with another file.

Of course, I could delete such an image, `POST` the new file as new media, and re-`POST` the old data (name, alt), but this seems ugly, and will mess up my media IDs references in posts that used the old one (and should now use the new one).

So, is there a neat way to replace one image's content with another, without deleting media (i.e., without changing media's ID)?

I am using Python for this, but `curl`'s command line is also fine, easy to translate to Python.

**Comment by rmccue** [comment]
This isn't possible with WordPress generally, so the API doesn't support it either. You'll need to make a completely new media item to change the image data.
