### ISSUE TITLE
Adding Filter for using custom edit-permissions

### ISSUE THREAD

**Issue by Hendrik44** [WP-API/WP-API#2733]
Hi there,

i need the option to integrate the following custom permission for editing comments. Is there a opportunity to integrate a filter, so that can be realized without customizing the complete plugin? Or can i made a pull request?

``` php
protected function check_edit_permission( $comment ) {
        if ( 0 === (int) get_current_user_id() ) {
            return false;
        }

        $childs = get_comments(array(
            'post_id'   => $comment->comment_post_ID,
            'status'    => 'approve',
            'order'     => 'DESC',
            'parent'    => $comment->comment_ID,
        ));

        if ((int) get_current_user_id() == $comment->user_id && count($childs) == 0 )
        {
            return true;
        }
        else
        {
            return false;
        }
        // if ( ! current_user_can( 'moderate_comments' ) ) {
        //  return false;
        // }

        // return current_user_can( 'edit_comment', $comment->comment_ID );
    }
```

**Comment by rmccue** [comment]
You can hook into WordPress' permission system to change whether the user has the permissions or not, specifically the `map_meta_cap` capability.

**Comment by Hendrik44** [comment]
But with `map_meta_cap ` the permission affects the whole wordpress but i want this permission only applied for wp-api. It seems there is no chance to that, i´m right?

**Comment by BE-Webdesign** [comment]
@Hendrik44 

Thank you for using the WP REST API!  I would advise against having different permissions for your WordPress install and API.  However, if you need to have different permissions, you can put what you need done in a conditional checking for whether the `REST_REQUEST` constant is defined. 

```
if ( is_defined( 'REST_REQUEST' ) && REST_REQUEST ) {
    // Do stuff here.
}
```

**Comment by Hendrik44** [comment]
Thanks for your response. But i think the answers could not solve my  initial issue.

Ok i can use `map_meta_cap`  with conditionally if from @BE-Webdesign but how i can get the current comment which will be edited by current user, to check if a child comment exist and allow/deny editing/delete comment?
and which Hook i have to use to run my function and apply successfully my custom permission?

**Comment by Hendrik44** [comment]
So i´ve found a solution for my issue:
i am override the comments route to my custom rest_comments calls which inherit from the official `WP_REST_Comments_Controller` and override the `check_edit_permission` function.

```
function register_modified_comments_rest_controller()
{
	require_once dirname( __FILE__ ) . '/class-wp-rest-comments-controller.php';
	$controller = new WP_REST_Comments_Controller_Custom;
	$controller->register_routes();
}
add_action( 'rest_api_init', 'register_modified_comments_rest_controller', 100 );
```

```
class WP_REST_Comments_Controller_Custom extends WP_REST_Comments_Controller {

	protected function check_edit_permission( $comment ) {
		if ( 0 === (int) get_current_user_id() ) {
			return false;
		}

		$childs = get_comments(array(
		    'post_id'   => $comment->comment_post_ID,
		    'status'    => 'approve',
		    'order'     => 'DESC',
		    'parent'    => $comment->comment_ID,
		));

		if ((int) get_current_user_id() == $comment->user_id && count($childs) == 0 )
		{
			return true;
		}
		else
		{
			return false;
		}
	}
}
```

**Comment by gino8080** [comment]
Interesting,

can you give some usage example please?

is this the full code?
which is the route to call?
do i need something else?

thank you

**Comment by kadamwhite** [comment]
@gino8080 Thanks for the question; please open a post on the [WordPress forums](https://wordpress.org/support/forum/how-to-and-troubleshooting/) with the topic tag "rest-api", and somebody will try to help you out. Support is no longer conducted through this repository.
