### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by sedubois** [WP-API/WP-API#2734]
Is there an ETA on having a WordPress GraphQL API?

**Comment by BE-Webdesign** [comment]
That is very unrelated to this project, there is one partial implementation I know of at wordexpress.io.  GraphQL and REST APIs are two different things.  GraphQL is not a finalized standard either.

I am building my own implementation at the moment to help learn GraphQL, relay, sequelize, etc. If you are interested in that kind of project, I will ping you when it is open sourced.

> Is there an ETA on having a WordPress GraphQL API?

tl;dr No, that is also somewhat unrelated to this project.

**Comment by sedubois** [comment]
Thanks but I think it is related, GraphQL is a drop-in replacement for REST, which may explain why you are currently learning it and so am I 😊 

In my understanding, GraphQL is however already mature enough to be used and built incrementally upon. GitHub published their own API just a few days ago.

I'm interested in knowing where WordPress is going with this, which is surely also the case of other future-minded developers. I think this can be a big differentiator among different CMS offerings. So yes, when you have something open-source it would be nice if you could share it here! It would also be very welcome to have some kind of official statement/roadmap about this, if/whenever a decision would be made. Thanks a lot.

**Comment by BE-Webdesign** [comment]
> GraphQL is a drop-in replacement for REST

Not exactly, they are really different from what I have understood so far, but the end result is similarish.  They are obviously related, but I am speaking more to their implementation, which is quite different from what I understand. GraphQL is a query language for an API, that doesn't necessarily have anything to do with a REST API.

> In my understanding, GraphQL is however already mature enough to be used and built incrementally upon. GitHub published their own API just a few days ago.

Yeah, I am not saying it wouldn't be awesome to do this, I am saying it does not pertain to the development of the WordPress REST API.

> I'm interested in knowing where WordPress is going with this, which is surely also the case of other future-minded developers. I think this can be a big differentiator among different CMS offerings. So yes, when you have something open-source it would be nice if you could share it here! It would also be very welcome to have some kind of official statement/roadmap about this, if/whenever a decision would be made. Thanks a lot.

WordPress is a pretty open platform that you can do anything with, I am sure there are a lot of people in the community working on GraphQL stuff.

If you are talking about more formal goals and official statements from the WordPress core lead developers/a roadmap to core inclusion, I highly doubt that is anywhere on their list of priorities and the WordPress REST API project would be unrelated to that kind of discussion.  Commenting here about GraphQL won't accomplish what I think you are trying to find out.  You would want to touch base with the lead developers of WordPress to get their thoughts on GraphQL and WordPress.  Hopefully that helps clarify.

GraphQL is definitely very cool and I think it would be awesome to bring that kind of querying to WordPress.

**Comment by rmccue** [comment]
The REST API project is really a two-part project:
1. Abstraction on top of the WordPress internals to get consistency
2. Exposing the consistent abstraction via RESTful endpoints

The vast majority of the work and code is in part 1, but you can swap part 2 out pretty easily.

GraphQL is most useful when it's an enhancement to an existing REST API, and right now, we're focusing on providing a good one of those. GraphQL support is not on the roadmap for the near future, but it might be cool someday.

**Comment by BE-Webdesign** [comment]
Yeah you may have a GraphQL endpoint that is served over the REST API, but GraphQL itself essentially is a query language, type system, and service for interacting with application data.

**Comment by sedubois** [comment]
Thanks for the clarifications. I believe right now the best if for everyone of us to experiment with it. In my current view, it is a big improvement on REST, and those who understand it will have a headstart in terms of UX and DX.

**Comment by sedubois** [comment]
Drupal is now providing GraphQL (demoed with Auth0, Relay, React, CSS modules): https://www.youtube.com/watch?v=yhyoQwuSUWo

For context also see this (one year old) [article](http://buytaert.net/the-future-of-decoupled-drupal) about Drupal decoupling backend and frontend, and seeing GraphQL as instrumental in doing so.

**Comment by sedubois** [comment]
> GraphQL is not a finalized standard either

GraphQL has reached version 1.0 and has been declared "production ready".

**Comment by BE-Webdesign** [comment]
@sedubois Checkout WordExpress.io. It is a low level (in the sense that it only touches the WordPress database) GraphQL, Express, Apollo, and React application.  Creating a GraphQL API for WordPress that still uses all of the extensibility of WordPress, not just its database, would require a lot more effort and most likely it will be built on top of this project, the WordPress REST API, which is not even in core yet.  If you want to use WordPress today in a GraphQL, React application check out WordExpress.io

**Comment by sedubois** [comment]
@BE-Webdesign thanks, I still need to evaluate it properly. That would however require to maintain my own backend, not to mention that it is a single-developer effort, not backed by your organization.

I just discovered Relax CMS which is based on GraphQL, beta should be out next month but already has over 6000 stars: https://github.com/relax/relax (don't know if there are plans for a cloud service).
