### ISSUE TITLE
API Key GET requests

### ISSUE THREAD

**Issue by AaronSadlerUK** [WP-API/WP-API#2736]
Hi,

What is the best way to incorporate a API key for GET requests?

Thanks!

**Comment by t-grm** [comment]
Personally, I use [Application Passwords](https://fr.wordpress.org/plugins/application-passwords/) to generate passwords per API client, then I add the appropriate **Authorization** header to my GET requests. Hence, "**&apiKey=xxxxxxxxxxxxxxx**" effectively becomes "**Authorization: Basic xxxxxxxxxxxxxxxxxx**", with the same effect :)

**Comment by AaronSadlerUK** [comment]
Essentially i want to block access to the API unless a key is present... this plugin doesnt seem to do that?

**Comment by t-grm** [comment]
Not by itself, you then have to force all API calls to be authenticated. Here's a way to do that:

```
add_filter( 'rest_authentication_errors', function ($result) {
    if ( ! empty( $result ) ) {
        return $result;
    }

    if ( ! is_user_logged_in() ) {
        return new WP_Error( 'restx_logged_out', 'Sorry, you must be logged in to make a request.', array( 'status' => 401 ) );
    }
    return $result;
});
```

Unauthenticated clients will then get this response:

> {"code":"restx_logged_out","message":"Sorry, you must be logged in to make a request.","data":{"status":401}}

**Comment by AaronSadlerUK** [comment]
That worked just as i need thanks!

**Comment by t-grm** [comment]
You're welcome. It works alright, however it would be cool indeed to design a real "api key" feature so that we don't need headers for API authentication.

**Comment by rmccue** [comment]
The `Authorization` header is the standard for passing auth tokens, and is much more interoperable with proxies and servers than the query string.

Generally speaking, you should use [OAuth 1.0a](http://oauth1.wp-api.org/) instead of direct API keys, as they're more secure from replay attacks and don't require user interaction.
