### ISSUE TITLE
can't seem to retrieve all pages

### ISSUE THREAD

**Issue by duckfev3r** [WP-API/WP-API#2754]
Hi, 
Apologies for what's probably a very simple issue.
I am using /wp-json/wp/v2/pages?per_page=100

and the plugin doesn't seem to be returning all the pages in the response ( the site has far less then 100 pages so if it caps off at 100 - that isn't the issue )

ideally I would like to retrieve data from all pages in the site via one request to the API

does anyone have any suggestions ?

thanks a million

**Comment by kadamwhite** [comment]
Hey @duelingbanjos, thanks for using the REST API (and you have an _awesome_ username, btw). It's hard to diagnose what might be going wrong without more details; is there any consistency in which pages you're not seeing in the response? Are they published by a consistent user, or have any other common attributes? How many pages do you have total, _vs_ how many does the API return?

**Comment by duckfev3r** [comment]
Hi Kadam,
thanks for getting back to me so quickly,
after having a quick look around the wordpress backend, I realise that we have 143 pages in total.
is there a way to change the api to return more then 100 results in a query ?

cheers !

_twiddles banjo_

**Comment by duckfev3r** [comment]
aha

/wp-json/wp/v2/pages?per_page=100&page=2

_slaps forehead_

**Comment by kadamwhite** [comment]
@duelingbanjos Awesome, glad you got it worked out! To clarify the result of the conversation in case future searchers end up here, we impose a maximum of 100 records on results collections for performance reasons. Retrieving multiple pages of fewer results only adds a little HTTP latency and is much nicer to your server and database than is retrieving a single page of too many results.
