### ISSUE TITLE
Not an issue, I just love this!

### ISSUE THREAD

**Issue by dvdnhm** [WP-API/WP-API#2755]
just wanted to say.. great job guys!

**Comment by kadamwhite** [comment]
:D thanks for the kind words, @dvdnhm !

**Comment by dvdnhm** [comment]
probably you always get bad things, bugs, etc.. wanted to give something good..

Have a great day, just like I do thanks to you! :)

**Comment by kadamwhite** [comment]
Seems like most of the main team's seen this by now, so I'm going to close this (since after all, it's not an issue 😜 )
