### ISSUE TITLE
/wp-json/posts and not /wp-json/wp/v2/posts

### ISSUE THREAD

**Issue by Purus** [WP-API/WP-API#2760]
I have the permalinks changed to none and changed to my actual permalink.

The URI below works fine:

`/wp-json/posts`

But the actual URI below as documented does not work.

`/wp-json/wp/v2/posts`

**Comment by kadamwhite** [comment]
Hello @Purus and thanks for using the rest API. If you installed the plugin trough the plugin repository, can you let us know the name of the installed plugin you are using? This one is [WordPress REST API (Version 2)](https://wordpress.org/plugins/rest-api/); it sounds like you may have the older version 1 plugin installed.

**Comment by Purus** [comment]
Hi @kadamwhite,

Thanks for your time on this.

I am using the above linked v2 plugin. I am not sure what I am doing wrong.

**Comment by kadamwhite** [comment]
@Purus thanks for checking ,  that would have been the easy answer :) What version of WP are you running, and are there any other plugins or themes you might be using that could conflict? what is the output you get when you hit `/wp-json/` itself, without "posts"?

**Comment by Purus** [comment]
/wp-json/ returns meta information about the site.

/wp-json/categories does not work.

/wp-json/posts works.

**Comment by Purus** [comment]
Sorry for the trouble. Strangely it started to work when I did some changes related to Cache. some conflicts with v1 and v2 I guess.

Thanks for your support.
