### ISSUE TITLE
Storing responses in WP Object Cache? 

### ISSUE THREAD

**Issue by kosso** [WP-API/WP-API#2762]
Is there any way to specify that responses get optionally stored in WP Object Cache? 

Should this be done with a plugin script with the `rest_prepare_post`action filter? Or `rest_pre_dispatch` ?

**Comment by rmccue** [comment]
`rest_pre_dispatch` and `rest_post_dispatch` are designed for exactly this (you can store the cache in `rest_post_dispatch` and check/serve it from `rest_pre_dispatch`). The two things you'll need to check are the request object and authentication.

**Comment by kosso** [comment]
👍  perfect. thanks!
