### ISSUE TITLE
How to add Basic Auth for /wp-json/**

### ISSUE THREAD

**Issue by iegoshin** [WP-API/WP-API#2766]
I am trying to secure /wp-json so everyone has to authenticate to use the API. But I cannot figure out how to do that. I've installed and activated these two plugins:
http://v2.wp-api.org/
https://github.com/WP-API/Basic-Auth

Do I need to do something else to make it working?

**Comment by BE-Webdesign** [comment]
Hi @iegoshin,

By default everyone needs to authenticate with the API for private information. However public information, as in pieces of your site that are visible via rss or visually, will be available without authentication via the API by default as well.  If you want to lock down your whole site to only authenticated users you need to [use the `rest_authentication_errors` hook](https://developer.wordpress.org/reference/hooks/rest_authentication_errors/).

**Comment by iegoshin** [comment]
Wow, that was fast :) Thank you for quick reply! 

I will need to create a page with JSON API and looking at the reference here (close to the bottom):
http://v2.wp-api.org/reference/pages/
Not exactly sure what should be the URL (if page id doesn't exist yet)

**Comment by iegoshin** [comment]
Ah, sorry, overlooked it, no id, just POST. Thank you again!
