### ISSUE TITLE
`parent` is incorrectly used when querying posts if not in schema

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#2767]
Splitting from #2201.

**Comment by danielbachhuber** [comment]
> kadamwhite [2:18 PM]  I interpreted parameter whitelisting as something that would need to be implemented at the infrastructure level (which I admit I thought you were proposing) or at a controller level (which seems to be the origin of the `parent` bug specifically?)
> [2:19]  I think that extra parameters for GET requests should be passed through to be handled or ignored by the controller; is that in line with what you are describing, or not?
> danielbachhuber [2:20 PM]  I think the correct behavior is that `menu_order` should be ignored in `GET /wp/v2/posts menu_order=2`, unless it's explicitly registered as a supported query argument for the endpoint
> [2:20]  I think the current behavior for `GET /wp/v2/posts menu_order=2` is inconsistent, and a bug
> rmccue [2:20 PM]  Sure, and that’s another bug
> danielbachhuber [2:21 PM]  ok. the bug applies to all query arguments that `WP_REST_Posts_Controller` supports
