### ISSUE TITLE
How To Delete Some Info From API

### ISSUE THREAD

**Issue by bestony** [WP-API/WP-API#2771]
I Want to Only show title,author,id exclude content to save bandwidth for some bad network

**Comment by kosso** [comment]
See here to learn how to modify the responses with a plugin script. 

http://v2.wp-api.org/extending/modifying/

Or you could create your own namespaced endpoints and deliver what you need. 

http://v2.wp-api.org/extending/adding/

**Comment by bestony** [comment]
Well,I don't want to make a ext . i just want to hide the content for save bandwidth

**Comment by kosso** [comment]
I agree that it would be nice to filter the fields we need, but see the later comments on #446 and #572 and it seems that it's the only way to go. For now.

**Comment by bestony** [comment]
well, i can make new namespace , but i also want it can add to do list

**Comment by kosso** [comment]
I found this useful : http://boris.kuzmanov.ninja/wp-rest-api-modifying-json-response/ 

But I would recommend a custom endpoint. As they mention on the [Modifying Responses](http://v2.wp-api.org/extending/modifying/#important-note-about-changing-responses) page, it can be unwise to remove fields from the standard wp/v2 responses, as other clients might expect the fields to be present.

**Comment by kosso** [comment]
How about something like this? Using a custom `_compact` parameter: 

```
function allow_compact_post( $data, $post, $request ) {
    // return compact data when _compact GET parameter exists 
    if(isset($_GET['_compact'])){
        return [
            'id'        => $data->data['id'],
            'title'     => $data->data['title']['rendered'],
            'link'      => $data->data['link'],
        ];
    }
    return $data;
}
add_filter( 'rest_prepare_post', 'allow_compact_post', 10, 3 );
```

then hit `/wp-json/wp/v2/posts?_compact`

**Comment by kadamwhite** [comment]
@kosso @bestony I'm closing this as superseded by https://core.trac.wordpress.org/ticket/38131 which proposes a `?fields=id,title,link` query parameter that can be used to restrict results; that interface is used by the WordPress.com API and I've proposed it for inclusion here in #2773 but the change would likely need to occur in within the infrastructure already committed to core.

**Comment by kadamwhite** [comment]
Thanks for raising this, by the way; it's been weighing on my mind that we don't have an interface for it and this was a good push to try to do something about it :)

**Comment by kosso** [comment]
👍

**Comment by bestony** [comment]
:+1:
