### ISSUE TITLE
Plugin directory entry for REST API v2 says not tested with 4.6.1? 

### ISSUE THREAD

**Issue by kosso** [WP-API/WP-API#2772]
I have the latest WP 4.6.1 installed and noticed the info for the v2 REST API [2.0-beta14] says : 

"Untested with your version of WordPress"

Details pane says "Compatible up to: 4.5.4".

**Comment by rachelbaker** [comment]
@kosso Thank you for the heads up.  I will get that updated today.

**Comment by rachelbaker** [comment]
Fixed: https://cloudup.com/cpIAsbsmCpP
