### ISSUE TITLE
`$use_cache` block is (still) unused in terms controller

### ISSUE THREAD

**Issue by boonebgorges** [WP-API/WP-API#2776]
Previously: #2311, reverted in #2318.

From https://github.com/WP-API/WP-API/pull/2311#issuecomment-188549081:

> Oooooooooops! This needs reverting; the first if block there needs to check this variable, as if $use_cache is false, we need to do the full get_terms call.

I'm not sure what the cache here is intended to be. Is it related to `get_terms_for_post()`? If so, the `$use_cache` block can probably be re-removed alongside #2740.

**Comment by rachelbaker** [comment]
fixed in  #2820
