### ISSUE TITLE
Not getting content of password protected page, when passing "password" in query string

### ISSUE THREAD

**Issue by fabioduque** [WP-API/WP-API#2782]
I am new with WP-API, and I've been trying to access a password-protected page, without success.

I found [#2720](https://github.com/WP-API/WP-API/pull/2720) and I tried to make a request like this:

`http://example.com/wp-json/wp/v2/pages/11?password=thepassword`

This gives me the same result as doing the request without the query string. 
I get an empty string on content.rendered and excerpt.rendered fields:

```
  "content": {
    "rendered": "",
    "protected": true
  },
  "excerpt": {
    "rendered": "",
    "protected": true
  },
```

If I submit a bad password, I get:
`{
  "code": "rest_post_incorrect_password",
  "message": "Incorrect post password.",
  "data": {
    "status": 403
  }
}`
so it seems that this is evaluating the password, but when the password is correct, it's not filling the rendered field.

Thanks in advance for your attention!

**Comment by kadamwhite** [comment]
@fabioduque Thanks for using the REST API! I'm unable to replicate this issue at the moment -- when I create a password-protected page with password "thepassword" (using the v2 REST API plugin Beta 15, released at the end of last week), I am able to correctly see the password contents when providing the password as `/wp/v2/pages/1904?password=thepassword`.

Can you confirm which version of the plugin you're using?

**Comment by fabioduque** [comment]
Hi! 
Thank you for your response.

This is a fresh installation of Wordpress (latest version: 4.6.1) and the plugin is also at the latest version:
2.0-beta15.

I have tried multiple times, with different passwords and I'm mainly using Postman, but I've also tried with Chrome and Firefox directly (since it's a GET) and the result is the same JSON.

Just to give you more information, which I don't know if it's relevant or not, I'm using a Vagrant box, running Scotch Box 2.5 (Ubuntu 14.04LTS, with PHP 5.6.14).
The host machine is Windows 10, which should not matter at all.

I will try to re-install it or maybe install it in other Wordpress site to see if the same happens, but other than that, I'm out of ideas.

Can I give you any more information that could help you discover the bug?

Thanks a lot!

**Comment by fabioduque** [comment]
Hi @kadamwhite.

Just to let you know that I've tried to install the plugin in another Wordpress installation and the same thing happened: 
- locked the page with a password
- Made a GET request without password and the string is empty
- Made a request with ?password=thepassword and the string still comes empty
- A different password gives me an error message.

Cheers!

**Comment by kadamwhite** [comment]
I was just able to reproduce using the stable WordPress install within VVV. Debugging now.

**Comment by kadamwhite** [comment]
Turning over to @joehoyle, looks like the filter on which this functionality depends was added in 4.7 and is not present in 4.6

**Comment by joehoyle** [comment]
Yup, so, short answer, viewing the post content is only supported in 4.7, as that's when the `post_password_required` filter was added. The reason why this feature didn't exist for so long in the REST API is that it was virtually impossible to overload this functionality, hence not being able to fix it for 4.6. I don't know if we did a great job of making that clear, so apologies for that.

**Comment by kadamwhite** [comment]
I don't think we even _began_ to make that clear, https://make.wordpress.org/core/2016/10/01/wordpress-rest-api-2-0-beta-14/ made no communication about this being 4.7-only. Our apologies on that, @fabioduque, that's our miss.

**Comment by fabioduque** [comment]
@joehoyle @kadamwhite 
No problem! ;) I'll wait for the 4.7 update. 
Thank you for your help and your great work!
