### ISSUE TITLE
API should honor the `unfiltered_html` capability

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#2787]
Should we match WordPress Core's logic when users with the `unfiltered_html` capability are creating/updating Posts or Comments?

For Posts:
- Core removes the appropriate `kses` filter from sanitizing post_content and the post_title.

For Comments:
- Core changes the active `kses` filter used for sanitizing comment_content to `wp_filter_post_kses()`.

See the `kses_init()` function in WP Core for the complete logic.

**Comment by mnelson4** [comment]
So we don't all need to dig into the code, what's the current behaviour in the WP API? Assuming the user doesn't have the 'unfiltered_html' capability? I'm guessing the WP API pretends no one has the'unfiltered_html' capability, and so strips potentially-harmful html from all posts when updated, right?

I suppose it's a tradeoff between security (if we honor 'unfiltered_html' and a users' password gets intercepted by  hacker, then the hacker can add malicious javascript onto the site) and functionality (legitimate users may want to add full html to a site too). 

One significant downside to ignoring whether a user has 'unfiltered_html' or not, is if they create a post with full html (eg maybe they put a javascript snippet in it) from the wp admin, then open that edit that same post using the WP API (say just change a word), then the post's html will get unexpectedly taken out. I could see that making some people grumpy.

**Comment by kadamwhite** [comment]
Per [discussion in 2016-10-17 API team chat,](https://wordpress.slack.com/archives/core-restapi/p1476713547007670) the API should honor `unfiltered_html`; @rmccue owns documenting next steps.

**Comment by rmccue** [comment]
I think we should pursue two avenues here:
1. Let's take a look at introducing a new function into core that checks `unfiltered_html` and sanitizes the input appropriately, and this could be used in core rather than the `remove_filter` craziness. This depends on back-compat as to whether core can use it, but is a good path forward.
2. Let's also switch our behaviour ASAP, then use core's behaviour if/when it exists.

**Comment by nylen** [comment]
Migrated issue and discussion so far to https://core.trac.wordpress.org/ticket/38609; this can be closed.
