### ISSUE TITLE
Return an error when a Comment POST request is attempted for a trashed or draft Post

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#2790]
WordPress returns an error when a user tries to leave a comment on a post that is either is draft or in the trash and we should too.

See related logic in `wp_handle_comment_submission()`

**Comment by zachwills** [comment]
I looked into that function and it looks like WordPress also runs these actions:

`do_action( 'comment_on_trash', $comment_post_ID );` (line 2816 in `wp-includes/comment.php`)
`do_action( 'comment_on_draft', $comment_post_ID );` (line 2829 in `wp-includes/comment.php`)

Should we run those within the REST API response before returning the error?

**Comment by rachelbaker** [comment]
@zachwills Sorry, I missed your question last week :(  You were correct though.

**Comment by kadamwhite** [comment]
@rachelbaker Does that comment mean there's outstanding work on this issue? Didn't see those lines in the referenced commit
