### ISSUE TITLE
Add support for Comments of password-protected Posts

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#2791]
Accept the post_password via a query param in the Comments Controller to allow viewing, creating, updating, deleting comments on password protected posts if the provided `password` matches.

**Comment by diego-betto** [comment]
I think that depends on discussion settings (everyone, only registered, ecc)
Anyhow we should use the same logic of creating or reading a password-protected post, if the goal is to allow the use of the rest api.

**Comment by rachelbaker** [comment]
The Comments Controller does not have a `password` param to support viewing/editing/creating/deleting comments on password protected posts.  Attempting to interact with a comment on a password protected post returns a WP_Error because without the proper post password the permission checks fail.

Action items:
- Add the `password` param to allow users to pass the password for the related Post to a Comment.
- Modify our permission checks to support handling the `password` param
- Add unit tests

**Comment by rachelbaker** [comment]
Related discussion on Slack: https://wordpress.slack.com/archives/core-restapi/p1476713174007643

**Comment by kadamwhite** [comment]
Moved to 2.1 milestone

**Comment by nylen** [comment]
Migrated to https://core.trac.wordpress.org/ticket/38692
