### ISSUE TITLE
Updating a meta value which is the same as the current value returns error

### ISSUE THREAD

**Issue by tharsheblows** [WP-API/WP-API#2792]
I'm not sure if this is desired but it surprised me. If you try to update a meta value to the value currently in the database, the response is a 500 error. This is due to a check in update_metadata() which returns false if the values are the same. It might make a bit more sense to not return an error as you end up with the expected meta_value. [This checks and avoids the error.](https://github.com/tharsheblows/WP-API/commit/b6d986fcce6a2c16ac83beee72ea1ff7ee16b243)

**Comment by rachelbaker** [comment]
I don't remember what we used to do in this case.  We should check how this issue was handled in v1.

**Comment by kadamwhite** [comment]
I agree that it would make a lot more sense to not error in that case.
