### ISSUE TITLE
Error 500 when not logged in

### ISSUE THREAD

**Issue by bomshteyn** [WP-API/WP-API#2793]
We used the plugin successfully for last 6 months, until we updated the plugin a few days ago. (we might have been behind by few releases)

Since then when doing GET /wp-json/wp/v2/posts we get 500 error

But if i first log in into the WP admin the  the same API call works in the browser.

Is there a new requirement that all requests be authenticated, even read / get requests?

**Comment by kadamwhite** [comment]
@nathan6137 thanks for using the REST API, glad to hear it has been useful to you (and sorry not to respond to this sooner). There have been no changes to the authentication requirements for GET requests, and an authentication error would be a 40x, not a 500—sounds like something else is going on.

Some questions to try to dig in:
- What version of WordPress are you using?
- Do you have any server logs of what the error is which is occurring?
- What environment are you sending your requests from?

I'd suggest disabling your other plugins and re-enabling them one by one to see if one of them might be conflicting.

**Comment by bomshteyn** [comment]
We are on version 4.6.1
We use it in a mobile app, but we tried from browser and postman and got the same error. 
Version 2.0-beta14 works ok.

I suspect the reason the error is 500 is because we have apache behind nginx.

we are on PHP 5.5.30, could this be an issue?

**Comment by firminochangani** [comment]
@kadamwhite @nathan6137 I am having the same issue. If you have a solution already please post here, I have a product using it and my users are complaining.

**Comment by bomshteyn** [comment]
@flowck  What version of PHP do you have on your server?

The only solution i found so far is to use Version 2.0-beta14

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support are no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
