### ISSUE TITLE
REST API Cookie Authentication

### ISSUE THREAD

**Issue by mateikki** [WP-API/WP-API#2797]
Hello,
in rest-api.php (WordPress 4.6.1 core) there are these lines (lines 566-563)
`/*
     * Is cookie authentication being used? (If we get an auth
     * error, but we're still logged in, another authentication
     * must have been used).
     */
    if ( true !== $wp_rest_auth_cookie && is_user_logged_in() ) {
        return $result;
    }`

Now when i try to authenticate my REST API request using login cookies this line fails since `true === $wp_rest_auth_cookie` . Am I doing something wrong or there is typo in code ? :)

**Comment by kadamwhite** [comment]
@mateikki thank you for the question. I believe that this logic is correct -- the conditional you are highlighting is designed to short-circuit the cookie authentication verification process when a different authentication scheme is in play. To answer the second part of your question, how are you passing the NONCE value back to WordPress in your requests? It may be an issue with how the request is being put together.

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support are no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
