### ISSUE TITLE
 wp-json/wp/v2/posts  500 Internal Server  Error

### ISSUE THREAD

**Issue by rocket2046** [WP-API/WP-API#2808]
when fetching a large number of posts
wp-json/wp/v2/posts  or /pages  500 Internal Server  Error
 wp-json/wp/v2/  is well
wp-json/wp/v2/posts/id  is well 
@danielpunkass 
@kokarn

**Comment by kadamwhite** [comment]
@rocket2046 Thanks for using the REST API, and for your bug report. Can you clarify how many posts you are requesting when you see this error, and share the version of the beta plugin that you have installed?

**Comment by rocket2046** [comment]
Thank for your replay.  @kadamwhite 
today  is  2.0-beta15 ,before is  2.0-beta13.1. Upgrade today.
2.0-beta13.1  500
 2.0-beta15 still 500

Generally more than 5 articles per second,it will be 500.
1-2 seconds at the same time release, more than five articles, there will be 500

1:Remove the latest part of the article,it is restored.
2:Re-add a new category, you can also restore
 Only to restore json, but wp-json / wp / v2 / posts or / pages 500 Internal Server Error is still there, the data can be obtained.
Do not do the above two operations, can not get to the json data.

**Comment by kadamwhite** [comment]
@rocket2046 thank you for your response. I could use some more specifics around

> Generally more than 5 articles per second,it will be 500.
> 1-2 seconds at the same time release, more than five articles, there will be 500

It sounds like you're getting a 500 error if you request more than five articles in one request, and one request per second? e.g., `/wp/v2/posts?per_page=6`, then `/wp/v2/posts?per_page=6&page=2` a second later, is causing the error? That's definitely unusual, the API should be able to handle many posts in one request, and at least more than one request at once (though if you're gathering all posts it's nicer on the server to get the pages sequentially).

What do you mean by "remove the latest part of the article?" If you can share pseudocode you're using to make these requests that might help narrow things down further. What sort of server are you on, _e.g._ a dedicated VPS or a shared host?

**Comment by beatelite** [comment]
Just a heads up, I switched from beta13.1 to beta15 (develop) and i'm getting this too. I just hit the /wp-json/wp/v2/posts endpoint and get a 500 error when I didn't before. I'm not sending any pagination requests or per_page requets in the header.

I discovered that it was because I was using a wordpress version 4.4.2. When I upgraded to the latest wp (4.6.1) it worked.

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support are no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
