### ISSUE TITLE
AppAuth and BasicAuth doesn't work

### ISSUE THREAD

**Issue by jensschneider** [WP-API/WP-API#2822]
Both Authorization-Methods (App and Basic) doesn't work.

I'm using following versions:
- WordPress 4.6.1-de_DE
- WP REST API 2.0-beta15
- JSON Basic Authentication 0.1
- Application Passwords (from George Stephanis) 0.1-dev

`{
  "code": "rest_forbidden",
  "message": "Du bist leider nicht berechtigt, dies zu tun.",
  "data": {
    "status": 403
  }
}`

**Comment by kadamwhite** [comment]
@jensschneider Thanks for using the REST API, and for logging this issue. Can you share the format (although not the real credentials!) of the request you are making with Basic Auth that is failing? I'd also suggest opening an issue for Application Passwords on that project, since it's maintained separately.

**Comment by DrBGM** [comment]
Any update on this ?

**Comment by jensschneider** [comment]
@kadamwhite I'm using Postman to test it. This is for example the extracted JQuery code:

```
var settings = {
  "async": true,
  "crossDomain": true,
  "url": "https://<url>/wp-json/wp/v2/posts/<a draft number>",
  "method": "GET",
  "headers": {
    "authorization": "Basic <base64decoded>",
    "cache-control": "no-cache",
    "postman-token": "<a token generated by postman>"
  }
}

$.ajax(settings).done(function (response) {
  console.log(response);
});
```

**Comment by garubi** [comment]
@jensschneider are you using the Postman chrome app or the standalone version?
In the past I had problems with authentication with the Crhome App, now I switched to the standalone one and have no problem with basic authentication.

**Comment by riddhikhakhi** [comment]
Hello!

I have problem with basic authentication when using custom API custom end point, can anyone help me out for how to set up basic authentication for custom API endpoint.
Also I want to get user id of logged in user when I use my custom API.

**Comment by nhondong** [comment]
Hi, 
I have 4 Wordpress Sites. 2 are Hosted by different providers. 2 are running on Ubuntu 16.04.
The Hosted Sites gave me "not Authenticated", the 2 Ubuntu Systems are running and the Authentication works fine.

Any Ideas?

**Comment by BE-Webdesign** [comment]
@nhondong 

What webserver are you running.  Apache, nginx, something else?

**Comment by nhondong** [comment]
Hi, 
after searching in the issues of the basic Auth, i found a solution.
Setting php to secure mode and changing the .htaccess file to:

# BEGIN WordPress

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index.php$ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress

kind regards, Nils

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support are no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
