### ISSUE TITLE
Wp Api - Menu plugin error

### ISSUE THREAD

**Issue by omariosouto** [WP-API/WP-API#2823]
I'm trying to retrieve data from my menus, but when I install the plugin that is on the docs of Wp API for this, it's give an error in line 183. Exists another way to get data from Wp menus?

**Comment by rmccue** [comment]
Menus are not supported natively in the core REST API plugin, but are instead supported [in a separate plugin](https://github.com/WP-API/wp-api-menus-widgets-endpoints).
