### ISSUE TITLE
Why do the settings delete on null?

### ISSUE THREAD

**Issue by JasonTheAdams** [WP-API/WP-API#2827]
I was a bit confused when I came across this line: https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-settings-controller.php#L102

```
        if ( is_null( $request[ $name ] ) ) {
            delete_option( $args['option_name'] );
        } else {
            update_option( $args['option_name'], $request[ $name ] );
        }
```

Specifically the idea that an empty value means that the option ought to be deleted. There's quite a difference between an empty value (and even a null value) compared to the option being removed entirely. Shouldn't deleting be limited to the use of the DELETE request?

As a standard I don't believe the PUT/POST requests are ever intended to delete something server-side.

Curious to hear others thoughts. :)

**Comment by rmccue** [comment]
WordPress is not really able to store `null` values for options or meta. We use `null` to specifically mean "no value exists for this property"; if you set a value to `null`, that means "remove this value".

#2657 sums up our discussion and decisions on this.

> As a standard I don't believe the PUT/POST requests are ever intended to delete something server-side.

Not quite: POST/PUT are for creating and updating respectively, but only in the context of operating on _resources_. In this case, the resource is the site, which has properties that are technically stored in settings. The same applies for post/etc meta, which are properties of the post that are technically stored in the meta table. You're not actually deleting the resource here, just changing properties on the object.
