### ISSUE TITLE
Creating media - file is too small

### ISSUE THREAD

**Issue by michmzr** [WP-API/WP-API#2829]
Hi,

I would like to use Guzzle and upload a media file to Wordpress.
This is my simplified code:
`$content = $file->fread($file->getSize());

```
$file = new \SplFileObject("57e9975cfa762782d14a981f16e60748.jpg", "r");

$content = $file->fread($file->getSize());
$streamedCnt = \GuzzleHttp\Psr7\stream_for($content);
$request = new Request("POST", "http://www.michmm.kylos.pl/wp_api/wp-json/wp/v2/media", [
    "Authorization" => ['...oauth 1 parameters....'],
    "Content-Disposition":["attached;filename=57e9975cfa762782d14a981f16e60748.jpg"],"Content-Type":["multipart\/form-data"][, $streamedCnt);

$client = new GuzzleHttpClient();
$response = $client->send($request, [
                "allow_redirects":true,
                "json":[
                    "status":"publish",
                    "slug":"57e9975cfa762782d14a981f16e60748.jpg",
                    "title":"57e9975cfa762782d14a981f16e60748.jpg",
                    "media_type":true,
                    "mime_type":"image\/jpeg"]
            ]);`
```

I get a correct HTTP answer from WP. New record in media library is created, but I find a media file with json code in /uploads directory. 

How should I create a http request to create/update media on WP using Guzzle?

M.

**Comment by rmccue** [comment]
> New record in media library is created, but I find a media file with json code in /uploads directory.

Creating media is a two-step process:
1. Send the raw image data as a POST request to `/wp/v2/media`. This needs a Content-Disposition header with a filename. This returns a 201 Created with a Location header pointing to the new attachment post.
2. Update the attachment post with the relevant data.

In the above, it appears you're trying to do both of these steps at once. The file needs to be sent first as one request, then when you get the response object, you can then update that.
