### ISSUE TITLE
Can Access-Control-Allow-Headers be customized?

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/WP-API#2844]
In #1529 @rickharrison asks,

> How do you customize the `Access-Control-Allow-Headers` header? I am trying to work with a wordpress API and no methods will go through because `Content-Type` is not allowed.

**Comment by Shelob9** [comment]
@rickharrison I would use the "rest_pre_serve_request " filter. I have a post on sending cross-origin headers. The example code in that could be changed to fit your needs: 
https://joshpress.net/access-control-headers-for-the-wordpress-rest-api/

**Comment by kadamwhite** [comment]
@shelob9 thanks much for that link! Would you be interested in adapting that material for a page in the wp-api.org site about cross-domain requests?

@rickharrison I'll leave this open for now but let us know if adapting that code resolves your issue.

**Comment by kadamwhite** [comment]
@Shelob9 (cc @joehoyle et al for confirmation or clarification), Actually after skimming through the code, it looks like the [`serve_request` method in class-wp-rest-server.php](https://developer.wordpress.org/reference/classes/wp_rest_server/serve_request/) is where the `Access-Control-Allow-Headers` method is set; I was unable to affect that by filtering `rest_pre_serve_request`.

**Comment by rmccue** [comment]
You're allowed to send multiple `Access-Control-Allow-Headers` headers, last I recall, so if you just send the extra ones, should be fine:

```
add_action( 'rest_pre_serve_request', function () {
    header( 'Access-Control-Allow-Headers: Some-Other-Header', false );
});
```

**Comment by kadamwhite** [comment]
Aha, I was using `add_filter` and it wasn't working. Dropping this code in mu-plugins _switched_ the header from "Authorization" to "Content-Type", so make sure to include all headers you want to be set.

``` php
<?php
add_action( 'rest_pre_serve_request', function() {
    header( 'Access-Control-Allow-Headers: Content-Type' );
});
```

No filters need to be unhooked.

I'm going to close this since this seems to do what was asked, but @rickharrison please chime in below if that doesn't solve the issue.

**Comment by rmccue** [comment]
@kadamwhite Oops, sorry; need to set the second parameter of `header` to `false` to avoid replacing it. Updated my code.

**Comment by rickharrison** [comment]
Where do I place this code exactly? I am on a hosted wordpress currently.

**Comment by kadamwhite** [comment]
@rickharrison This would be within a plugin; for example, to permit paginated CORS requests I have the following within a plugin in my environment:

```php
<?php
function my_customize_rest_cors() {
  remove_filter( 'rest_pre_serve_request', 'rest_send_cors_headers' );
  add_filter( 'rest_pre_serve_request', function( $value ) {
    header( 'Access-Control-Allow-Origin: http://myclientappwebsite.com' );
    header( 'Access-Control-Allow-Methods: GET' );
    header( 'Access-Control-Allow-Credentials: true' );
    header( 'Access-Control-Expose-Headers: Link', false );

    return $value;
  });
}
add_action( 'rest_api_init', 'my_customize_rest_cors', 15 );
```
