### ISSUE TITLE
How i can work with child sites by REST API

### ISSUE THREAD

**Issue by apacheborys** [WP-API/WP-API#2846]
Hi everyone!

Sorry for maybe duplicate question, but i cant find answer for that. I have wordpress site what contents child blogs (different lang versions). I install wordpress plugins:
WP REST API Version 2.0-beta14 
WP REST API - OAuth 1.0a Server Version 0.2.1 
I install them in main site (parent) and child blog.

But REST API working only with main site. If i create query http://my-site.com/wp-json or http://my-site.com/oauth1/<some_request>

When i try to get posts to http://my-site.com/wp-json/wp/v2/post (GET query) i see only information posts (from standart Add Post) and main posts from Portfolio plugin i dont see. When i try get http://my-site.com/wp-json/wp/v2/post?include=<some_post_id_from_portfolio> i get:
[]

I have two questions:
1. How i can get post from differents child sites?
2. How i can set child site for any post?
Same questions i have for categories.

Thank you in advance.

**Comment by rmccue** [comment]
Each site has its own API endpoints, so you'll have `http://example.com/wp-json/` and also `http://example.com/other-site/wp-json/` or `http://other.example.com/wp-json/`

Post IDs are local to the individual sites (i.e. each site can have a post with ID 42), so you can't access them across sites.

**Comment by apacheborys** [comment]
When i send http://my-site.com/de/wp-json i get 404 error, but plugins enabled OK.
Maybe printscreens will help you for understand me...
![1](https://cloud.githubusercontent.com/assets/11578023/19430201/02cea538-945c-11e6-8dd5-21509f99ffbd.jpg)
![2](https://cloud.githubusercontent.com/assets/11578023/19430202/02cee0c0-945c-11e6-8f22-cde301b36630.jpg)
![3](https://cloud.githubusercontent.com/assets/11578023/19430204/02d326a8-945c-11e6-8307-f8dd83f224c8.jpg)
![4](https://cloud.githubusercontent.com/assets/11578023/19430203/02d0d772-945c-11e6-93c5-c7d9e732afe9.jpg)

**Comment by BE-Webdesign** [comment]
@apacheborys 

> main posts from Portfolio plugin i dont see

You might need to make sure that your Portfolio plugin's post types are enabled to be seen by the rest API.  When post types are registered they must have `show_in_rest => true`.

It is also possible that the rewrite rules you are using for your German version of the site are conflicting with the rewrite rules the API is putting out.
