### ISSUE TITLE
Avoid use of wp_filter_post_kses to prevent lossy slash handling

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/WP-API#2848]
As [discussed in slack](https://wordpress.slack.com/archives/core-restapi/p1476715005007733) following #2840, there are other places than https://github.com/WP-API/WP-API/pull/2788 where @westonruter's comments around the lossy slash handling in `wp_filter_post_kses` come into play; we should standardize these to use the underlying `wp_kses` functions.

Quoting @rachelbaker,

> if we are not trusting the slash handling of `wp_filter_post_kses()` then we should do that consistently, and switch to `wp_kses_post()` or `wp_kses()` with the {filter_name}

**Comment by nylen** [comment]
This is being addressed at https://core.trac.wordpress.org/ticket/38609 along with `unfiltered_html`
