### ISSUE TITLE
Using WP_REST_Posts_Controller directly results in empty data:[]

### ISSUE THREAD

**Issue by MartinMalinda** [WP-API/WP-API#2857]
On the first render of my web app, I'd like to render some data into a `<script>` so I'd save myself an ajax call later, resulting in faster boot of the application.

This is the code I've started with:

``` php
$request = WP_REST_Request::from_url('http://localhost:8888/wp-json/wp/v2/posts?_embed=1&page=1&per_page=5');
$controller = new WP_REST_Posts_Controller('post');
$posts = $controller->get_items($request);
echo json_encode($posts);
```

The output is, though, this:

``` json
{"data":[],"headers":{"X-WP-Total":9,"X-WP-TotalPages":2,"Link":"; rel=\"next\""},"status":200}
```

While the posts had clearly been successfully queried (X-WP-Total = 9), the data is empty.

I'm not sure if this is a bug. In either case, I'd be very grateful for any input on this.

**Comment by BE-Webdesign** [comment]
Hi @MartinMalinda,

Thank you for using the WP REST API.  Doing internal requests is inherently different from using HTTP for the API.  You don't need to invoke controller classes on your own. You only need to create a request object and use the internal routing function `rest_do_request()`.  Try the following code below:

``` php
$_GET['_embed'] = true;
$request = new WP_REST_Request( 'http://localhost:8888/wp-json/wp/v2/posts?page=1&per_page=5' );
$response = rest_do_request( $request );
unset( $_GET['_embed'] );
```

Note the setting and unsetting of super globals.  The embed param should probably not be used and instead you would iteratively call `rest_do_request()` on each link in the response.  This is just a quick example that should work.  If you need to encode it as JSON just copy the same line you had.

``` php
echo json_encode( $response );
```

**Comment by MartinMalinda** [comment]
`rest_do_request()` is just what I needed, thank you for the quick response.
It actually works now with as simple code as this:

``` php
$request = WP_REST_Request::from_url('http://localhost:8888/wp-json/wp/v2/posts?&page=1&per_page=5&_embed=1');
$response = rest_do_request( $request );
```

**Comment by rachelbaker** [comment]
Closing this issue, as the support issue has been resolved.

**Comment by CaptainN** [comment]
The `_embed` trick doesn't seem to work any more. Is there a better way?

**Comment by brock-rasmussen** [comment]
@CaptainN 
```
global $wp_rest_server;
$request = new WP_Rest_Request('GET', '/wp/v2/posts');
$request = rest_do_request($request);
$request = $wp_rest_server->response_to_data($request, true);
```

**Comment by CaptainN** [comment]
@brock-rasmussen That works - thanks!

**Comment by shahbaz-dev1** [comment]
@brock-rasmussen Works for me too - Thanks
