### ISSUE TITLE
Diff in release 2.0-beta15 on WP.org (SVN) to Tag on Github

### ISSUE THREAD

**Issue by Chrico** [WP-API/WP-API#2880]
Howdy!

It seems, that the current release (2.0-beta15) of the Plugin [0] is not "correct". 

After downloading on wp.org the Plugin or having a look at the tag on SVN [1], you can see the `WP_REST_Posts_Controller` differs to the tagged class here on Github [2]. The META-integration is completly missing. 
Same for `WP_Rest_Terms_Controller`, `Users` and `Comments`.

---

**Links**
- [0] https://wordpress.org/plugins/rest-api
- [1] https://plugins.svn.wordpress.org/rest-api/tags/2.0-beta15/lib/endpoints/class-wp-rest-posts-controller.php
- [2] https://github.com/WP-API/WP-API/blob/2.0-beta15/lib/endpoints/class-wp-rest-posts-controller.php#L13

**Comment by rachelbaker** [comment]
@Chrico thank you for reporting this.  I am fixing it now.

**Comment by rachelbaker** [comment]
@Chrico Sorry about that.  I just pushed up a fix for the missing changeset: https://plugins.trac.wordpress.org/changeset?sfp_email=&sfph_mail=&reponame=&new=1517921%40rest-api&old=1510477%40rest-api&sfp_email=&sfph_mail=

I am going to close this issue, but please re-open if you encounter another issue.  

Cheers!

**Comment by Chrico** [comment]
@rachelbaker Thanks a lot, but..erm..you only updated the Beta15-Release zip on wp.org. This means, everyone who has this version already installed, keeps the "broken" version? This is a not really "clean" solution. 🤔
