### ISSUE TITLE
Extend endpoint with POST action 

### ISSUE THREAD

**Issue by e-karlsson** [WP-API/WP-API#2888]
Hello. I'm trying to extend with an endpoint "car". I've used the documentation and got it work with the GET method and it works great. However, when I try add a POST method in the same way I doesn't succeed. I get this response:
 {"code":"rest_no_route","message":"Ingen route hittades som motsvarade webbadressen och metod f\u00f6r beg\u00e4ran","data":{"status":404}}

Theres no example in the documentation how to extend with an POST method in my function.php theme file. Have someone succeeded to extend with a POST method and want to share the code?

**Comment by websupporter** [comment]
Hi mr3k.
Thanks for using the REST API. Actually, this plugin has succeeded in doing so :smile: 

So, I guess you are registering with `register_rest_route` and you have set it to `GET` and now you need the same endpoint to accept `POST` as well.

See for example here:
https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-posts-controller.php#L40-L54

You see, how a multidimensional array is used to address the issue of multiple Methods for one endpoint? I hope, this is what you need?

**Comment by e-karlsson** [comment]
Hi websupporter and thanks for your quick reply!

Actually what I've done now is just use the POST as following:

```
function handleCarPOST( $request ){
        $this->namespace = 'wp/v2';
        $this->rest_base = '/car/';


        $prepared_term = $this->prepare_item_for_database( $request );

        $term = wp_insert_term( $prepared_term->name, $this->taxonomy, $prepared_term );

        $this->update_additional_fields_for_object( $term, $request );
        $request->set_param( 'context', 'view' );
        $response = $this->prepare_item_for_response( $term, $request );
        $response = rest_ensure_response( $response );
        $response->set_status( 201 );
        $response->header( 'Location', rest_url( '/' . $this->namespace . '/' . $this->rest_base) );
        return $response;

}

add_action( 'rest_api_init', function () {
    register_rest_route( 'wp/v2', '/car/', array(
        'methods' => 'POST',
        'callback' => 'handleCarPOST',
    ) );
} );
```

Right now I just want to make sure I can and some data through the API with POST method and see that the data is received and that I can reply with an response. Do you see any direct problems?

Thanks for your help!

**Comment by websupporter** [comment]
Hmmm... I am not quite sure what you are trying. Well, here is an example, which would work for the `POST` method:

```
    add_action( 'rest_api_init', function(){
        register_rest_route(
            'cars/v1',
            '/route/',
            array(
                'methods'  => 'POST',
                'callback' => 'cars_postHandler',
                )
        );
    } );

    function cars_postHandler( $request ) {
        $data['message'] = 'Post Request was received.';
        return $data;
    }
```

But since it looks like you want to insert a term, why don't you use the plugin? When you register taxonomies with `show_in_rest` `true` you just could use the WordPress REST API plugin to create/delete/view/edit terms.

For example: `POST wp-json/wp/v2/categories/?name=New Category`

So if the slug of your taxonomy would be cars:
`POST wp-json/wp/v2/cars/?name=Cabs`

But maybe I do not quite understand.

**Comment by e-karlsson** [comment]
websupporter ❤️  
Thank you for the example above, it was so easy and I've totally missed it. I've used the code in my example from term, I'll not use it now. 

This helped me a lot and I think your example above could be great to have in the documentation for beginners as me 😃  Thanks a lot - have a great day!

**Comment by websupporter** [comment]
Happy, I could help you.

One thing, you should return the `$data` with `rest_ensure_response( $data )`

```
function cars_postHandler( $request ) {
    $data['message'] = 'Post Request was received.';
    return rest_ensure_response( $data );
}
```

**Comment by e-karlsson** [comment]
Will do, thanks!
