### ISSUE TITLE
Cache rest api responses with Redis

### ISSUE THREAD

**Issue by mnguye08** [WP-API/WP-API#2891]
Hi,

I would like to cache the json response with Redis.
How can I put the result in json format (not the WP_REST_Response but really the final result) in a Redis key and retrieve the response if the key already exists?

Thanks!

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support are no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
