### ISSUE TITLE
Adding Square brackets in JSON Array

### ISSUE THREAD

**Issue by hieuiee** [WP-API/WP-API#2898]
Hey! How do I go about adding square brackets '[ & ]' on the beginning and ending of the JSON on a single line?

i.e.
My JSON currently shows this
{"tracking_job":"tracking_job_photography"}

and I'd like it to look like this
[ {"tracking_job":"tracking_job_photography"} ]

I've spent a few hours trying to figure it out without any luck. Any help would be much appreciated! :)

Cheers

**Comment by beatelite** [comment]
I'm personally not sure what you're referring to. You're trying to add an endpoint to the api? Where are you attempting to build this array of JSON objects exactly?

**Comment by BE-Webdesign** [comment]
Hi @hieuiee,

Thank you for using the WP REST API.  Make sure you upgrade to WordPress 4.7 if you can for the latest features!

> and I'd like it to look like this
>[ {"tracking_job":"tracking_job_photography"} ]
>I've spent a few hours trying to figure it out without any luck. Any help would be much appreciated! :)

If you are trying to create your own endpoint you would do this.

```
return rest_ensure_response( array(
    array( 'tracking_job' => 'tracking_job_photography' )
) );
```

Notice the extra `array()` call wrapping around the array with your data. In PHP associative arrays are translated to Objects in JSON as they are a key value pair. Unassociative arrays are translated to simple lists/arrays in JSON.  Most likely you just need to wrap whatever you are trying to return in another array without any keys.

**Comment by kadamwhite** [comment]
You can try using the array_values function too, I believe we use that internally to force Json array redponses

**Comment by BE-Webdesign** [comment]
Calling `array_values()` in this instance will return something like `[ 'tracking_job_photography' ]` you will lose out on the key value map.

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support are no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
