### ISSUE TITLE
Change Tags ID to Tags Names in WP-Json Api

### ISSUE THREAD

**Issue by jhonnynho** [WP-API/WP-API#2900]
I want to replace the ID of tags in the Json result on the wp-json API.

All searches what I do about posts, response a Json array with tags, but I need tags names instead tag ID

Example, this is the response.

```
    [
  {
    "id": 8774,
    "date": "2016-05-22T16:25:16",
    "date_gmt": "2016-05-22T14:25:16",
    "guid": {
      "rendered": "http://.com/?p=8774"
    },
    "modified": "2016-10-25T12:27:02",
    "modified_gmt": "2016-10-25T10:27:02",
    "slug": "compacto",
    "type": "post",
    "link": "http://.com/compacto/",
    "title": {
      "rendered": "COX"
    },
    "content": {
      "rendered": "",
      "protected": false
    },
    "excerpt": {
      "rendered": "",
      "protected": false
    },
    "tags": [
      276,
      278,
      277,
      279,
      280
    ],
    ...
  },...
```

I need the same response, but in the tag array I need

```
    [
  {
    "id": 8774,
    "date": "2016-05-22T16:25:16",
    "date_gmt": "2016-05-22T14:25:16",
    "guid": {
      "rendered": "http://.com/?p=8774"
    },
    "modified": "2016-10-25T12:27:02",
    "modified_gmt": "2016-10-25T10:27:02",
    "slug": "compacto",
    "type": "post",
    "link": "http://.com/compacto/",
    "title": {
      "rendered": "COX"
    },
    "content": {
      "rendered": "",
      "protected": false
    },
    "excerpt": {
      "rendered": "",
      "protected": false
    },
    "tags": [
      name1,
      name2,
      name3,
      name4,
      name5
    ],
    ...
  },...
```

I used conditions for each ID, but many and is more tedious this way

**Comment by beatelite** [comment]
You could create your own custom property on the object and only add the names as the array values to  your custom property. http://v2.wp-api.org/extending/adding/

I've done this a few times. It's not too hard and gives you much more control.

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support are no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
