### ISSUE TITLE
Use mysqli instead of mysql_ to be PHP 7 compatible

### ISSUE THREAD

**Issue by shaheero** [WP-API/WP-API#2901]
Extension '`mysql_`' is deprecated since PHP 5.5 and deprecated since PHP 5.6 and removed since PHP 7.0 - use `mysqli` instead.

FILE: ../wp-content/plugins/rest-api/extras.php
FILE: ../wp-content/plugins/rest-api/lib/endpoints/class-wp-rest-comments-controller.php
FILE: ../wp-content/plugins/rest-api/lib/endpoints/class-wp-rest-posts-controller.php
FILE: ../wp-content/plugins/rest-api/lib/endpoints/class-wp-rest-revisions-controller.php

**Comment by rmccue** [comment]
This is core WordPress behaviour, and is an issue with your hosting, not with the API. If you enable `mysqli` on your server, this will go away.
