### ISSUE TITLE
Upgrade MySQL to MySQLi to ensure PHP 7 Compatiblilty

### ISSUE THREAD

**Issue by haydenw** [WP-API/WP-API#2902]
See below output from WordPress' PHP Compatiblilty plugin

> ## FILE: /home/colorex/public_html/wp-content/plugins/rest-api/lib/endpoints/class-wp-rest-comments-controller.php
> ## FOUND 2 ERRORS AFFECTING 2 LINES
> 
>  588 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
> ##  589 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
> ## FILE: /home/colorex/public_html/wp-content/plugins/rest-api/lib/endpoints/class-wp-rest-posts-controller.php
> ## FOUND 2 ERRORS AFFECTING 2 LINES
> 
>  773 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
> ##  782 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
> ## FILE: /home/colorex/public_html/wp-content/plugins/rest-api/lib/endpoints/class-wp-rest-revisions-controller.php
> ## FOUND 2 ERRORS AFFECTING 2 LINES
> 
>  285 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
> ##  288 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
> ## FILE: /home/colorex/public_html/wp-content/plugins/rest-api/extras.php
> ## FOUND 1 ERROR AFFECTING 1 LINE
> ##  150 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.

**Comment by nylen** [comment]
These are false positives, all involving the WordPress function [`mysql_to_rfc3339`](https://github.com/WordPress/WordPress/blob/75535c596b35015d5392de3b4dca44d7d2365801/wp-includes/functions.php#L5426).  This issue can be closed.

**Comment by haydenw** [comment]
Thanks @nylen. All good.
