### ISSUE TITLE
Add Meta Box Data to Wordpress API

### ISSUE THREAD

**Issue by ptums** [WP-API/WP-API#2903]
Hello I have a custom post type that utilizes Meta Boxes (not done with the Meta Box plugin) and I'm trying to access that data through the WP API, but its not appearing? How do I get where these fields in my data? Any advice on this would be greatly appreciated.

Thank you,

Peter

**Comment by modemlooper** [comment]
You need to register meta fields manually

http://v2.wp-api.org/extending/modifying/#how-to-use-registerrestfield

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support are no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
