### ISSUE TITLE
Base64 Image Data Issue

### ISSUE THREAD

**Issue by ahmadawais** [WP-API/WP-API#2904]
I am trying to add a base64 image via REST API in the content of a submitted post.
Here, the request which is submitted has the image converted to base64 which starts with "data:"
take a look 

![image](https://cloud.githubusercontent.com/assets/960133/19890920/66a45328-a05f-11e6-8147-403a8dcf2a38.png)

Once the data is submitted into WP, the word "data:" vanishes in thin air, rendering the image useless
![image](https://cloud.githubusercontent.com/assets/960133/19890937/78615f5c-a05f-11e6-9b56-e9afc32891b2.png)

When I manually add "data:" to the URI it starts working.

WP is removing "data:" but there is no info on how why and where? Today, my Google fu is off 😞

I did find this 3 year old [ticket](https://core.trac.wordpress.org/ticket/19354#no0) where wp_allowed_protocols() should not contain 'data', as it is not safe was fixed.

It's like the REST API is filtering the content and when the post is inserted, the "data:" portion of the src attribute is getting stripped away.

Any help would be appreciated.

**Comment by ahmadawais** [comment]
Looks like `data` was removed and now if you try and add bas64 image data URI `data` with WP REST API it gets ignored.

I had to add it through the filter.

```
/**
 * Allow data protocol..
 *
 * @since 1.1.0
 */
if ( ! function_exists( 'aa_allow_data_protocol' ) ) {
    add_filter( 'kses_allowed_protocols' , 'aa_allow_data_protocol' );
    /**
     * aa_allow_data_protocol
     *
     * @param  array $protocols
     * @return array
     * @since  1.1.0
     */
    function aa_allow_data_protocol( $protocols ) {
        $protocols[] = 'data';
        return $protocols;
    }
}
```

Strange! I think it is an issue in the core. Since it happens only when you insert data via REST API and not in the case explained in the [ticket](https://core.trac.wordpress.org/ticket/19354#no0).

**Comment by rmccue** [comment]
Closing, as this is tracked on Trac.

**Comment by ahmadawais** [comment]
@rmccue Can you mention the ticket # where it is being tracked?
