### ISSUE TITLE
Post Filters Not Working

### ISSUE THREAD

**Issue by shaheero** [WP-API/WP-API#2905]
While listing posts, filters like `sticky=true` (which is not listed in the [docs](http://v2.wp-api.org/reference/posts/)) work fine, but others like `format=video` don't:

I tried `wp-json/wp/v2/posts?filter[format]=video` and `wp-json/wp/v2/posts?format=video` but they just list the posts.

As per https://github.com/WP-API/WP-API/issues/2683, I tried this:
```
function show_post_format_in_rest() {
	$taxonomies = get_object_taxonomies( 'post', 'objects' );
	if ( isset( $taxonomies['post_format'] ) ) {
	    $taxonomies['post_format']->show_in_rest = true;
	    $taxonomies['post_format']->rest_base = post-format;
	}
}
add_action( 'init', 'show_post_format_in_rest' );
```

But neither `wp-json/wp/v2/posts?post-format=video` nor `wp-json/wp/v2/posts?post-format=2` work. 

In my theme, I have `add_theme_support( 'post-formats', array( 'video' ) )`

Wordpress 4.6.1 and WP REST API V2 Beta 15

**Is there a way to list posts of a certain format? And in general, shouldn't the filter take any field as an argument?**

**Comment by kosso** [comment]
I had to search around for this weird parameter format, but here you go ;) 

`/wp-json/wp/v2/posts?filter[post_format]=post-format-video` 

Though interestingly, it doesn't seem to work for `post-format-standard` 
All the others seem OK for me. (eg: `post-format-audio`, `post-format-aside`, etc. )

This is also mentioned in #984

**Comment by kosso** [comment]
This will no longer work in WP 4.7.

**Comment by kadamwhite** [comment]
Closing as `filter` has been removed in 4.7, as noted above. If you encounter inconsistent behavior when using the [rest-filter](https://github.com/wp-api/rest-filter) plugin, please open an issue on that repository.
