### ISSUE TITLE
orderby author not working

### ISSUE THREAD

**Issue by beatelite** [WP-API/WP-API#2906]
This may be intentional but I just upated to the latest and sorted out the new filtering changes (I love that you got rid of [filter] btw). However, I can't sort a lists of posts by author anymore. I keep getting:

```
{
  "code": "rest_invalid_param",
  "message": "Invalid parameter(s): orderby",
  "data": {
    "status": 400,
    "params": {
      "orderby": "orderby is not one of date, relevance, id, include, title, slug"
    }
  }
}
```

Is there a way around this?

**Comment by beatelite** [comment]
I also noticed that I can't do orderby taxonomy term anymore either.

**Comment by nylen** [comment]
Migrated to https://core.trac.wordpress.org/ticket/38693.
