### ISSUE TITLE
how to enable json for api plugin

### ISSUE THREAD

**Issue by rush86999** [WP-API/WP-API#2907]
I enabled wp api plugin but i don't know how to get a json response? any instructions would help

**Comment by kadamwhite** [comment]
Thanks for trying the API! JSON is the default, and at this point only, supported response format, so if you're not receiving JSON then something must have gone wrong. May I ask what response you are trying to make, and what you're receiving instead of JSON? What version of the plugin are you using?

**Comment by rush86999** [comment]
i am trying to use the wordpress-hybrid-client that connects through your rest api; it is Version 2.0-beta15. i installed it and i can't get any data back

**Comment by BE-Webdesign** [comment]
@rush86999 

Can you link to the `wordpress-hybrid-client` that you are trying to use?  Also if you could leave a comment explaining what you are trying to accomplish and the steps you have taken so far, it could greatly help.

Thank you.

**Comment by rush86999** [comment]
https://github.com/shprink/wordpress-hybrid-client

steps taken
1. install rest api plugin
2. follow instructions on above link

# Clone and use the latest version

$ git clone https://github.com/shprink/wordpress-hybrid-client.git && cd wordpress-hybrid-client

# List all versions

$ git tag
$ git checkout <the-latest-version>

# Install

$ yarn

# Run on the browser

$ npm start

gets loading of app but no data;  try reinstalling and restarting mac using yarn and npm stop npm start, install, and refreshing browser. stuck here

**Comment by rush86999** [comment]
my website is rosevillefamilycentre.com

**Comment by rush86999** [comment]
not using https only http->change config.cson file under config for url address

**Comment by BE-Webdesign** [comment]
Hi @rush86999 

Well from looking at your website rosevillefamilycentre.com/wp-json/wp/v2/posts the API is somewhat working.  There is some sort of plugin doing something weird as it is outputting `<script>` tags in the response.  The other endpoints are working properly so my guess is that https://github.com/shprink/wordpress-hybrid-client is causing some problems for the API.  I would suggest opening an issue with them on their GitHub repository.

**Comment by kadamwhite** [comment]
I agree, this looks like an issue with that client and not the underlying API; I'm going to close this out but feel free to continue discussion below!
