### ISSUE TITLE
Empty request in custom endpoints

### ISSUE THREAD

**Issue by findshorty** [WP-API/WP-API#2908]
After creating custom endpoints, any request made using anything but GET sends an empty request object to the custom callback, regardless of sending a JSON string or an array in the body of the request.

Consider:
```
register_rest_route( 'customapi/v1', '/account', array(
	array(
		'methods' => WP_REST_Server::EDITABLE,
		'callback' => array($this, 'update_user'),
		'permission_callback' => function () {
			return current_user_can( 'edit_posts' );
		},
		'args' => array()
	),
	array(
		'methods' => WP_REST_Server::CREATABLE,
		'callback' => array($this, 'create_user'),
		'permission_callback' => function () {
			return current_user_can( 'edit_posts' );
		},
		'args' => array()
	)
));
```

The callback, for simplicity, was changed to:

```
public function update_user( WP_REST_Request $request) {
	$params = $request->get_params();
	return new WP_REST_Response( array('params' => $params), 200 );
}
```

And it's ALWAYS an empty array, regardless of using $request->get_params / get_body_params / get_json_params etc.

The request is made using wp_remote_request, PUT or POST, and basic authentication (which works fine).

**Comment by rmccue** [comment]
This is very strange. What if you try sending a GET request, but set `_method=POST` to override the method?

**Comment by findshorty** [comment]
Resolved, kind of.

I didn't realise there are such tight restrictions on what data could be sent to custom endpoints. My client wants to synchronise his back end product and user database with his WP site, so the plan was for him to send entire query results of his database to the API, and the callback function would then update or create products or users by mapping his data to the WP data structure, with a predefined mapping array.

I understand why built in endpoints have restrictions, but why on earth are there restrictions on the data sent to custom endpoints.

My custom objects are pretty complex, and I want to control the mapping of the data within WP, as there is no way for him to send a properly structured CPT object, with all the various meta fields, options etc. etc.

Is there a way of removing this restriction for custom endpoints? Is there a filter I can remove?

**Comment by BE-Webdesign** [comment]
@findshorty 

> I didn't realise there are such tight restrictions on what data could be sent to custom endpoints.

When you are building your own endpoints there aren't any restrictions, I have come across.  Could you elaborate more on what restrictions you are encountering.  The only real restrictions are restrictions that HTTP itself imposes. The restrictions imposed by HTTP can all be worked around, but you may have to format your requests differently and approach the problem differently, depending on what you are trying to do.

> so the plan was for him to send entire query results of his database to the API

You would want to do this one request at a time.  If you are trying to send a complete object you can divide each of its fields into a separate query param for update requests.  If you set up a schema for your complex object you can use the `WP_REST_Controller::get_endpoint_args_for_item_schema()` method to build out the query params from the schema.

**Comment by findshorty** [comment]
Thanks for your reply.

So it might be an HTTP restriction that is causing the errors?

My request would be a single object at a time, and triggered by the saving of a record on his back end system.

So his back end would make a PUT request to, for example, /customapi/v1/product/<sku> and the body of the request would be an array, so:

```
'body' => array(
    'productdata' => $row
)
```

My $row is approximately 40 columns, and is way below post_max_size, but I'm consistently getting a cURL 28 error from the API.

`cURL error 28: Operation timed out after 5000 milliseconds with 619 out of 3019 bytes received`

What other restrictions would HTTP be imposing on my request? I'm stumped!

**Comment by findshorty** [comment]
Seems like any field from my customer's database that includes a multiline string is breaking the API, and I receive a cURL 28 error as above.

Actually, scratch that. There's issues with all sorts of fulltext fields. For example this value breaks the request:

`ipad, ipad kiosk, ipad wall mount, ipad secure kiosk, ipad secure wall mount, ipad bracket, ipad flush mount, iPad tilting wall mount, iPad tilting kiosk, iPad tilting mount`

Any ideas??

**Comment by findshorty** [comment]
Think I've solved it. The customer's database columns are encoded cp1252 instead of UTF-8.

**Comment by BE-Webdesign** [comment]
Ah, glad to hear. It was hard to gauge what was going on, as I am sure you probably felt the same.  Character encoding gives me nightmares.

**Comment by findshorty** [comment]
Thanks for your help with working this through.

My animosity towards the WP API has reduced significantly now I know it's actually my fault!

**Comment by BE-Webdesign** [comment]
@findshorty 

There are some shortcomings for the API, but honestly it works very well and is a top notch REST API.  Glad to hear you are using it and have resolved your issue.
