### ISSUE TITLE
Make it possible for taxonomy query to include children

### ISSUE THREAD

**Issue by JasonTheAdams** [WP-API/WP-API#2909]
Greetings!

Currently when a registered taxonomy is used it's assumed that `include_children` is false. That's a bummer as a useful bit of functionality is being cut out of the WordPress query.

```php
if ( ! empty( $request[ $base ] ) ) {
	$query_args['tax_query'][] = array(
		'taxonomy'         => $taxonomy->name,
		'field'            => 'term_id',
		'terms'            => $request[ $base ],
		'include_children' => false,
	);
}
```

What about making it possible for `$request[$base]` to either be a string and work as-is for backwards-compatibility, or an array with `term_id` and `include_children` indexes?

**Comment by JasonTheAdams** [comment]
As an example:

``` php
if ( ! empty( $request[ $base ] ) ) {
    $terms = is_array($request[ $base ]) && isset($request[ $base ][ 'term_id' ]) ? (int) $request[ $base ][ 'term_id' ] : 0;
    $include_children = is_array($request[ $base ]) && isset($request[ $base ][ 'include_children' ]) ? (bool) $request[ $base ][ 'include_children' ] : false;

    $query_args['tax_query'][] = array(
        'taxonomy'         => $taxonomy->name,
        'field'            => 'term_id',
        'terms'            => $terms,
        'include_children' => $include_children,
    );
}
```

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support are no longer taking place in this repository.

For this enhancement, please post a Trac ticket at https://core.trac.wordpress.org with these details (I didn't see one after a quick search).

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!
