### ISSUE TITLE
register_meta() show_in_rest field mapping is not working.

### ISSUE THREAD

**Issue by garubi** [WP-API/WP-API#2910]
Hallo,
I'm playing with the register_meta() and the 'show_in_rest' argument.

I'm already using a custom field named 'wpcf-informazioni' that I would like to expose to the REST API with the name of 'extra'.
Following [this](https://github.com/WP-API/wp-api-meta-endpoints/blob/new-meta-new-life/README.md#apispecific-options ) I registered the field using

```
add_action( 'init', 'register_new_meta');

function register_new_meta() {
     $args = array(
        'type' => 'string',
        'description' => 'Extra information',
        'single' => false,
        'show_in_rest' =>  array(
            'name' => 'extra',
        ),
    );
    register_meta( 'post', 'wpcf-informazioni', $args );   
}
```
but in the response to my GET I get the `'extra'` field empty, while if I omit the `'name' => 'extra'` argument, setting only `show_in_rest => true` like this:

```
add_action( 'init', 'register_new_meta');

function register_new_meta() {
     $args = array(
        'type' => 'string',
        'description' => 'Extra information',
        'single' => false,
        'show_in_rest' => true,
    );
    register_meta( 'post', 'wpcf-informazioni', $args );   
}
```

 I get the 'wpcf-informazioni' filed populated with its content.

So is the "mapping" to the "name" not working (maybe the document I referenced isn't updated), or am I doing something wrong... ?

**Comment by BE-Webdesign** [comment]
Hello Garubi!

> So is the "mapping" to the "name" not working (maybe the document I referenced isn't updated), or am I doing something wrong... ?

The `show_in_rest` argument is meant to be a boolean `true` or `false`. It does not map values to new names. It's purpose is to flag whether you want the field to show up automatically in the API's meta endpoint.  If renaming the field to `extra` is critical, then stick to `register_rest_field()`. I don't believe there is a way to map names using `register_meta()`.

**Comment by BE-Webdesign** [comment]
Somehow the fields are not mapping and the documentation indicates they should, so I would say this is a bug.

**Comment by garubi** [comment]
I'll test it against WP 4.7 then I file a ticket on track

**Comment by garubi** [comment]
since I had the same issue with the trunk I opened a Ticket on Trac: https://core.trac.wordpress.org/ticket/38786

**Comment by nylen** [comment]
Closing, as this was moved to trac and then fixed in core.
