### ISSUE TITLE
wp-json/wp/v2/posts give blank

### ISSUE THREAD

**Issue by MELAS007** [WP-API/WP-API#2911]
hi!

i installed WP REST API v2 and try to access to wp-json/wp/v2/posts unfortunately gives a blank screen without errors... and then i disable WP REST API V2 then tried to go wp-json/ it opens with others informations about the website.... there is no others REST API installed...

I have wordpress 4.5.3 .

What can i do? or is it a bug from wordpress / WP REST API v2???

Any help will be appreciated?

Thanks and regards

**Comment by BE-Webdesign** [comment]
Hi @MELAS007,

Thank you for using the WP REST API.  Have you enabled debugging for the site you are on?  Try activating the plugin again with debugging on and put the error messages here and we can figure out what is going on.  Here is a good guide for [debugging wordpress](https://codex.wordpress.org/Debugging_in_WordPress)

**Comment by MELAS007** [comment]
I set up debug in wp-config.php then  i disable the plugin it shows this : 

```
{
"name": "Edu Corner",
"description": "",
"url": "http://.com",
"home": "http://.com",
"namespaces": [
"oembed/1.0",
"wc/v1",
"yoast/v1"
],
"authentication": [],
"routes": {
"/": {
"namespace": "",
"methods": [
"GET"
],
"endpoints": [
{
"methods": [
"GET"
],
"args": {
"context": {
"required": false,
"default": "view"
}
}
}
],
"_links": {
"self": "http://.com/wp-json/"
}
},
```

when i activate : it appears nothing.....
and nothing in console and debug.log file

**Comment by BE-Webdesign** [comment]
Can you access the `wp-json/wc/v1/` endpoint when the plugin is disabled?

> when i activate : it appears nothing.....
> and nothing in console and debug.log file

That is really odd. Typically you don't get white screens of death without any error reports, make sure that PHP error reporting is enabled as well.

**Comment by MELAS007** [comment]
Yes I can access wp-json/wc/v1/ endpoint when the plugin is disabled as below: 

"namespace": "wc/v1",
"routes": {

```
"/wc/v1": {
    "namespace": "wc/v1",
    "methods": [
        "GET"
    ],
    "endpoints": [
        {
            "methods": [
                "GET"
            ],
            "args": {
                "namespace": {
                    "required": false,
                    "default": "wc/v1"
                },
                "context": {
                    "required": false,
                    "default": "view"
                }
            }
        }
    ],
    "_links": {
        "self": ".com/wp-json/wc/v1"
    }
},
"/wc/v1/coupons": {
    "namespace": "wc/v1",
    "methods": [
        "GET",
        "POST"
    ],
    "endpoints": [
        {
            "methods": [
                "GET"
            ],
            "args": {
                "context": {
                    "required": false,
                    "default": "view",
                    "enum": [
                        "view",
                        "edit"
                    ],
                    "description": "Scope under which the request is made; determines fields present in response."
                },
                "page": {
                    "required": false,
                    "default": 1,
                    "description": "Current page of the collection."
                },
                "per_page": {
                    "required": false,
                    "default": 10,
                    "description": "Maximum number of items to be returned in result set."
                },
                "search": {
                    "required": false,
                    "description": "Limit results to those matching a string."
                },
                "after": {
                    "required": false,
                    "description": "Limit response to resources published after a given ISO8601 compliant date."
                },
                "before": {
                    "required": false,
                    "description": "Limit response to resources published before a given ISO8601 compliant date."
                },
                "exclude": {
                    "required": false,
                    "default": [ ],
                    "description": "Ensure result set excludes specific ids."
                },
                "include": {
                    "required": false,
                    "default": [ ],
                    "description": "Limit result set to specific ids."
                },
                "offset": {
                    "required": false,
                    "description": "Offset the result set by a specific number of items."
                },
                "order": {
                    "required": false,
                    "default": "desc",
                    "enum": [
                        "asc",
                        "desc"
                    ],
```

but this is for woocommerce and not for posts or others, can i do??

**Comment by MELAS007** [comment]
can you tell me please how to change wp-json to another name as wpmob-api ?

maybe it is confusing with others but i don't see any errors!

can we solve this together that to give you url ?

**Comment by MELAS007** [comment]
@BE-Webdesign - any news?

**Comment by WorldsEndless** [comment]
I'm having a similar problem with v2, but it isn't actually a blank page; it's just returning an empty [] when it should be returning the posts or the pages.

**Comment by toco1001** [comment]
@WorldsEndless I got same error...

**Comment by BE-Webdesign** [comment]
@MELAS007 

The best thing you can do, if possible, is to upgrade to WordPress 4.7 and uninstall the REST API plugin.  If the v2 endpoints plugin does not appear to be working when active, there is most likely another plugin conflicting with it.  White screens indicate PHP fatal errors, I am not sure why you are not having anything appearing with debugging enabled.  If you have done any extending of the WP REST API, double check that code as well.

**Comment by MELAS007** [comment]
@BE-Webdesign - I will try today to update it!

**Comment by funkeye** [comment]
in our case the blank page was because zlib.output_compression was enabled:
**wget**:
normal output
**browser**:
blank page

maybe it will help you

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support are no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

**Comment by elliott-beach** [comment]
It's a pity that WordPress uses a support forum instead of Github Issues, which tend to be more searchable on the internet. I'm still having this issue.
