### ISSUE TITLE
How to get Featured Youtube Video Url in Response from get post

### ISSUE THREAD

**Issue by Dattatraymedhane** [WP-API/WP-API#2912]
I have a call to get postwp-json/wp/v2/posts/id that display's post in mobile app.
Here I have created one post with Featured Video with youtube video url, But the response does not contain the video url or id
I added _embed to request but it returns only featured image, even get media request doesn't include video url

**Comment by BE-Webdesign** [comment]
Hi @Dattatraymedhane,

Thank you for using the WP REST API.  To add the featured video are you using a particular plugin for this functionality or how are you doing that exactly?

**Comment by Dattatraymedhane** [comment]
Hi,
Thanks for the reply.
We are using Featured Video Plus plugin.

Finally I solved that with ACF to rest plugin. I added acf field and map that to category.So in edit post of type catagory I can set youtube video id to acf field AND then access that acf field value in get post response. Hope this is a correct way of doing it.:)
