### ISSUE TITLE
How do I fetch the static front page and posts page using the REST API?

### ISSUE THREAD

**Issue by connelhooley** [WP-API/WP-API#2913]
Is there a way to write a REST API query to fetch the page I have set to be my front page? I'd also like to get the one for my posts page but that's less important.

**Comment by kosso** [comment]
Try looking in `[YOUR_DOMAIN]/wp-json/wp/v2/pages` 

And for your posts : `[YOUR_DOMAIN]/wp-json/wp/v2/posts`

**Comment by connelhooley** [comment]
I ended up using a plugin to get the WP options via rest. I was then able to locate the page that has been set as the home page via the pages endpoint.

http://wordpress.stackexchange.com/a/246035/42843
