### ISSUE TITLE
How to increase per_page limit to 200 ?

### ISSUE THREAD

**Issue by Amenocy** [WP-API/WP-API#2914]
hi
can i increase per_page limit to 200 using actions ?

**Comment by shazzygh** [comment]
I would also be interested in this!

**Comment by beatelite** [comment]
Not sure about this but you can do it via a param in the request

wp-json/wp/v2/posts/?page=1&per_page=200

**Comment by maplethorpej** [comment]
I believe you'd need to actually modify the query within the plugin itself to increase results per request.

**Comment by Amenocy** [comment]
this limit is hard coded . please developers add 2 options 
1 - remove some things from output (whiteout coding ! ) 
2- add some useful hooks

**Comment by BE-Webdesign** [comment]
Hi @Amenocy,

Thank you for using the WP REST API.  If you are on WordPress 4.7, it is possible to modify the default posts per page, though it is **not recommended**. The following code snippet will change the collection arguments for the basic posts endpoint. To handle every post type either loop through them or handle them individually.

```php
add_filter( 'rest_post_collection_params', 'my_prefix_change_post_per_page', 10, 1 );

function my_prefix_change_post_per_page( $params ) {
    if ( isset( $params['per_page'] ) ) {
        $params['per_page']['maximum'] = 200
    }

    return $params;
}
```

Didn't test it but that should work.

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support are no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
