### ISSUE TITLE
Getting media by parent bug

### ISSUE THREAD

**Issue by MurhafSousli** [WP-API/WP-API#2915]
There is a bug in getting media attachments by parent, after removing the attached files from a post, they still comes in the API response

let's say I have a post with 5 attachments in it, I get the attachments like  `/wp-json/wp/v2/media?filter[post_parent]=1413`, I went back to the dashboard and removed 3 attachments, now I should get only 2 attachments but I still get all of them.

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support are no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
