### ISSUE TITLE
Filtering by ACF

### ISSUE THREAD

**Issue by WorldsEndless** [WP-API/WP-API#2916]
I can query successfully to see a list of items like the following: 

`{

    "id": 10750,
    "date": "2016-09-08T11:08:59",
    "date_gmt": "2016-09-08T17:08:59",   
    "modified": "2016-09-08T11:52:29",
    "modified_gmt": "2016-09-08T17:52:29",
    "slug": "greg-thompson-2",
    "type": "person",
    "title": {
        "rendered": "Greg Thompson"
    },
    "excerpt": {
        "rendered": "",
        "protected": false
    },
    "featured_media": 10661,
    "acf": {
        "netid": "glt2",
        "department": {
            "ID": 214,
            "post_author": "1",
            "post_date": "2014-08-14 01:24:07",
            "post_date_gmt": "2014-08-14 01:24:07",
            "post_content": "",
            "post_title": "Spanish & Portuguese",
            "post_excerpt": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quam lorem, tincidunt quis aliquet viverra, scelerisque non ipsum. Quisque ut aliquet nisl. Nunc non arcu ipsum.",
            "post_status": "publish",
            "comment_status": "closed",
            "ping_status": "closed",
            "post_password": "",
            "post_name": "spanish-portuguese",
            "to_ping": "",
            "pinged": "",
            "post_modified": "2015-05-15 12:15:17",
            "post_modified_gmt": "2015-05-15 18:15:17",
            "post_content_filtered": "",
            "post_parent": 0,
            "guid": "http://humpreview.byu.edu/?post_type=department&#038;p=214",
            "menu_order": 18,
            "post_type": "department",
            "post_mime_type": "",
            "comment_count": "0",
            "filter": "raw"
        },
        "": false,
        "position_status": "full",
        "addresszzzzzzzzzzzzzzzz": false,
        "schedule": [ ],
        "flexible_content": false
    }
}`

What I need is the ability to filter posts based on one of their ACF fields (visible above), but I can't seem to work out what the syntax should be. Any help? This is to be a URL-based query, presumably with a filter[] argument.

**Comment by rmccue** [comment]
Hi there! We don't provide first-party support for ACF integration with the REST API, so you'll need to ask the ACF folks about this. :)

**Comment by WorldsEndless** [comment]
Ok; you provide the instructions on how to view ACF in results (http://v2.wp-api.org/extending/custom-content-types/). I see them in the overall dump, but I'm trying to get the URL args to work right. The equivalent wp_query would be like this:

```
// args
$args = array(
        'numberposts'   => -1,
        'post_type'     => 'event',
        'meta_key'      => 'location',
        'meta_value'    => 'Melbourne'
);


// query
$the_query = new WP_Query( $args );
```

Can this sort of wp_query be duplicated via the URL arguments of the rest-api?
