### ISSUE TITLE
Route `wp/v2/users/me` redirects without `content` param

### ISSUE THREAD

**Issue by edygar** [WP-API/WP-API#2917]
When trying to reach to current user with edit context, the response comes as default context. Turns out the route `wp/v2/users/me` redirects to `wp/v2/users/[id]` but misses any given param.

**Comment by nylen** [comment]
Hi @edygar - we recently discovered a related issue.  Quoting from [Slack logs](https://wordpress.slack.com/archives/core-restapi/p1479388974001559):

> Any specific reason `/users/1` is `context=view` while `/users/me` is `context=embed`? Causes it to skip at least registered meta fields from the `/me` response
> 
> `/me` was only a recently addition (used to 301) so it might have been an oversight from then

Can you move this ticket over to https://core.trac.wordpress.org/ where API development is happening going forward?

Thanks for reporting :)

**Comment by edygar** [comment]
done. https://core.trac.wordpress.org/ticket/38842#ticket

**Comment by BE-Webdesign** [comment]
Moved to trac.
