### ISSUE TITLE
Getting correct Permalink?

### ISSUE THREAD

**Issue by Beheer80** [WP-API/WP-API#2920]
Hello All,
I realy love this plugin 👍 
I only have a problem with the return links and de endpoint "/wp-json/wp/v2/posts/{POST_ID}"

on some of my site's i get a 403 responce and on some of my site's i can see evrything.
This is solved with setting "Authorization" headers.

But now the strange part.

My Permalinks settings in wordpress are "http://www.example.com/%postname%/".
What i want is to get the link from a specific POST_ID.

This is my code for getting it.

`
$endpoint = 'http://www.example.com/wp-json/wp/v2/posts/{POST_ID}'

$headers = array (
	'Authorization' => 'Basic ' . base64_encode(['Username'] . ':' . ['Password'] ),
);

$response = wp_remote_post( $endpoint, array (
	'method'  => 'GET',
	'headers' => $headers,
) );

$response = json_decode($response['body']);

$URL = $response->link;
`

Now the problem is that the returning "$response->link" on some site are ,
http://www.example.com/?p=177
or
http://www.exampe.com/test-post-to-test

What i want is that the response link is always  "http://www.example.com/%postname%/" and not http://www.example.com/?p=177

Is this a bug or how can i set it?
The site's are hosted on the same hosting.

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support are no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

If you're able to identify clear steps to reproduce the bug from a clean install of WordPress 4.7, please post a Trac ticket at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!
