### ISSUE TITLE
Is this query possible with the rest api?

### ISSUE THREAD

**Issue by dkdl** [WP-API/WP-API#2921]
Using Version 2.0-beta15 I'm trying to get the following query with the rest api:

    $args = array (
      'post_type' => 'programm',
      'meta_query' => array(
         array(
          'key'   => 'date_start',
          'compare' => '>=',
          'value'   => date('Ymd'),
        )
      ),
      'meta_key' => 'date_start',
      'orderby' => 'meta_value',
      'order' => 'ASC'
    );

in the functions.php file I added the script to allow access to the meta_queries. But I cannot get it to work. This is what I have right now:

    /wp-json/wp/v2/programm
    ?filter[meta_query][key]=date_start
    &filter[meta_query][compare]='>='
    &filter[meta_query][value]=20161118
    &meta_key=date_start
    &filter[meta_value]=on
    &order=asc

This just displays all programm posts without filtering them. Can somebody point me in a direction?

**Comment by modemlooper** [comment]
How are you adding meta_query ? for example: https://github.com/WP-API/WP-API/issues/2452#issuecomment-212387177

**Comment by modemlooper** [comment]
Just realized, filter Parm was removed prior to core merge

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support are no longer taking place in this repository.

As @modemlooper said, the `filter` functionality has been moved to a separate plugin:  https://github.com/WP-API/rest-filter

Please post future support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
