### ISSUE TITLE
Cannot get private post with Oauth1 authentication 

### ISSUE THREAD

**Issue by yangfan0356** [WP-API/WP-API#2922]
Hi WP-API team,

I have problem of getting private post with Oauth1 authenticaiton. 

I used postman desktop application, filled the "GET" request with Oauth1's client key, client secret, oauth_token and oauth_token_secret, using url such as "http://xxxxx/wp-json/wp/v2/posts?status=private"

I would expect to get a list of private posts but what I get is
{
  "code": "rest_invalid_param",
  "message": "Invalid parameter(s): status",
  "data": {
    "status": 400,
    "params": {
      "status": "Status is forbidden"
    }
  }
}

Any idea what's going on? Thanks in advance.

Best Regards,
Fan

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support are no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
