### ISSUE TITLE
Issue with line ending characters (eg \n, \u2028) within returned data

### ISSUE THREAD

**Issue by enricodeleo** [WP-API/WP-API#2923]
Hi everyone,

lately I noticed that wp rest api is returning data adding the newline character at the end of some property (namely excerpt.rendered and content.rendered). Like in:

```
"excerpt": {
      "rendered": "<p>Lorem ipsum dolor sit amet [&hellip;]</p>\n"
}
```

This lead to a big issue in javascript because even if it is recognised as valid JSON (someone alread talked about it http://timelessrepo.com/json-isnt-a-javascript-subset). 

I tried to solve this problem by adding an hook 

```
// HOT FIX
// remove all newline chars from strings
// in order to avoid breaks on JSON
function vc_fix_newlines($value) {
  $value = preg_replace('~\R~u', '', $value);
  $value = str_replace('\u2028', '', $value);
  $value = str_replace('\u2029', '', $value);
  return $value;
}
add_filter( 'get_the_content', 'vc_fix_newlines', 1000 );
add_filter( 'the_content', 'vc_fix_newlines', 1000 );
add_filter( 'get_the_excerpt', 'vc_fix_newlines', 1000 ); 
add_filter( the_excerpt', 'vc_fix_newlines', 1000 ); 
```
Is there any way of avoiding this issue _ab origines_?

Thanks!

**Comment by rmccue** [comment]
Newlines _are_ valid JSON, per both the JSON.org notes:
![](http://json.org/string.gif)

And also [per the RFC](https://tools.ietf.org/html/rfc7159):

```
char = unescaped /
    escape (
        %x22 /          ; "    quotation mark  U+0022
        %x5C /          ; \    reverse solidus U+005C
        %x2F /          ; /    solidus         U+002F
        %x62 /          ; b    backspace       U+0008
        %x66 /          ; f    form feed       U+000C
        %x6E /          ; n    line feed       U+000A
        %x72 /          ; r    carriage return U+000D
        %x74 /          ; t    tab             U+0009
        %x75 4HEXDIG )  ; uXXXX                U+XXXX
```

**Comment by enricodeleo** [comment]
Thank you for your reply @rmccue. As I wrote above, I'm saying the same thing. But when this JSON is consumed by Javascript (again please give a look at http://timelessrepo.com/json-isnt-a-javascript-subset) the problem arises. 

Here some other trace of the issue in Javascript:

http://stackoverflow.com/questions/2965293/javascript-parse-error-on-u2028-unicode-character
https://github.com/cordova/cordova-discuss/issues/57

**Comment by rmccue** [comment]
Can you use `JSON.parse` instead? That doesn't appear to suffer from this problem as far as I can see.

**Comment by enricodeleo** [comment]
In my production app I actually use:

```
if ( result.data && lodash.isObject( result.data ) ) {
      data = result.data;
    }
    else if ( result.data ) {
      data = lodash.attempt(JSON.parse.bind(null, result.data));
    }
```

The problem here is that it has been working for an year or so both with wp-api v1 and v2, but suddenly the returned data started including "\n" characters. Is it an intended behaviour?

**Comment by rmccue** [comment]
Nothing should have changed as far as I know, but it could potentially be something on your site (a plugin, e.g.).

I'd be happy to consider adding this, but it's something that should go in at a low-level in `wp_json_encode`, so should be filed in an issue on [WordPress Trac](https://core.trac.wordpress.org/) :)

**Comment by enricodeleo** [comment]
Yes I also thought that may be a filter added somewhere down the track, I'm trying to debug which one (I love wp filters but when things start to became complicated are hard to debug).

I'll follow your hint and I'll try to head to the trac. I have to admit that this is a problem limited to JS but I think it is the most common scenario.

**Comment by SotirisValogiannis** [comment]
I have the same problem as described above by @enricodeleo. Reading [here](http://stackoverflow.com/a/42073/407382) the first comment of the answer, it points out the  specs, as @rmccue did above, but saying that the proper format is `\\n`. Not sure which one is the proper interpretation, but hope to help solving this issue somehow :)
