### ISSUE TITLE
WP_API_JWT_AUTH not registering as authentication method

### ISSUE THREAD

**Issue by andrewhl** [WP-API/WP-API#2924]
I'm using the WP_API_JWT_AUTH extension ([here](https://github.com/Tmeister/wp-api-jwt-auth)), but the outputted json at `wp_json/` is not showing it as a viable authentication method.

I've successfully authenticated to `wp-json/jwt-auth/v1/token` and validated the token at `wp-json/jwt-auth/v1/token/validate`, so the plugin is working. However, my `wp-json/` endpoint returns:

```json
"namespaces": [
    "wp/v2",
    "oembed/1.0",
    "jwt-auth/v1"
  ],
  "authentication": [],
```

Nothing in "authentication". And when I try to access `wp-json/wp/v2/posts`, I get all the data without passing in an Authorization header. How can I activate this extension so that it restricts access to the API?

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support is no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
