### ISSUE TITLE
GET /posts/{id} works, but GET /posts returns empty array

### ISSUE THREAD

**Issue by afska** [WP-API/WP-API#2925]
GET `/wp-json/wp/v2/posts/`
Returns an empty array `[]`

GET `/wp-json/wp/v2/posts/32319`
Returns the post (of type **gallery_post**).

The posts are public and accessible from the webpage.
Any help?

**Comment by modemlooper** [comment]
Custom types are not added to loop. Read more here http://v2.wp-api.org/extending/custom-content-types/
