### ISSUE TITLE
Allow filterable permission checks on core controllers

### ISSUE THREAD

**Issue by davekiss** [WP-API/WP-API#2927]
Apologies if there has been a discussion around this already, I searched and was unable to find it.

Is there any reason why there isn't a filter at the bottom of the `create_item_permissions_check` method on all internal controllers? I'm building a CPT that will extend and reuse most of the `WP_REST_Posts_Controller` but will need to perform a few additional checks to ensure the user has permission to create an item of my CPT.

Cheers, and thanks for all of the great work.

**Comment by davekiss** [comment]
Reworded some search terms and found the following discussion (in case others find this thread)

https://github.com/WP-API/WP-API/issues/2733

Looks like `map_meta_cap` might be the trick here.

**Comment by nylen** [comment]
You can also override the posts controller class, add your extra permissions logic, and specify your overridden class as the controller for your CPT.
