### ISSUE TITLE
Add filter to allow modifying response *after* embedded data is added

### ISSUE THREAD

**Issue by elyobo** [WP-API/WP-API#2929]
The `rest_post_dispatch` is intended to be used for modifying responses, but the `_embedded` data is not yet available which limits the manipulations that can be done.  It would be useful to have another filter that allows us to modify the final result being sent back, immediately before it's encoded and echoed.

For context, this is a problem for me in my `wp-rest-jmespath` plugin, which allows applying a JMESPath transform to a response to limit/rewrite the fields (see https://github.com/elyobo/wp-rest-jmespath/issues/1).  It is possible to work around this limitation by adding a handler for `rest_pre_serve_request` and copying the logic that would embed the data (e.g. in [this commit](https://github.com/elyobo/wp-rest-jmespath/commit/887a638cc00c0d80a9425346e5e6d9439a096ee3)) but this is a fragile workaround - any changes to the logic for processing and sending after `rest_pre_serve_request` would not be picked up by the plugin and so responses may end up differing unexpectedly.

**Comment by elyobo** [comment]
Or should this issue be against WP itself?  It seems like the code in question is in WP core now, not here...

**Comment by BE-Webdesign** [comment]
@elyobo 

The core content endpoints are merged into core, so any issues against this repo should be opened as a [trac ticket](https://make.wordpress.org/core/reports/).

**Comment by elyobo** [comment]
Thanks, I'll raise it there.
