### ISSUE TITLE
Disallow /users collection for public users

### ISSUE THREAD

**Issue by enricodeleo** [WP-API/WP-API#2930]
Hi everyone,

I just noticed that if I try to get `wp/v2/users/1` without authentication I am unable to view details, but if I try to get the entire collection `wp/v2/users` I can see all the users with ids and metas. 

What is the right way to prevent this from happening if not admin?

-- UPDATE --

I found a reply by @danielbachhuber that suggests 

```
add_filter( 'rest_endpoints', function( $endpoints ){
    if ( isset( $endpoints['/wp/v2/users'] ) ) {
        unset( $endpoints['/wp/v2/users'] );
    }
    return $endpoints;
});
```

That's good for now, but I think we should have a filter on permission callbacks or at least allow only users with `list_users` permission to view users collection (that as far as I can see is only required for role filtering).

**Comment by enricodeleo** [comment]
I found a reply by @danielbachhuber that suggests 

```
add_filter( 'rest_endpoints', function( $endpoints ){
    if ( isset( $endpoints['/wp/v2/users'] ) ) {
        unset( $endpoints['/wp/v2/users'] );
    }
    return $endpoints;
});
```

That's good for now, but I think we should have a filter on permission callbacks or at least allow only users with `list_users` permission to view users collection (that as far as I can see is only required for role filtering).

**Comment by rmccue** [comment]
The users endpoint is publicly available with specific restrictions: only users who have authored a public post are shown, and only a subset of the data is available. This matches the existing data that's already exposed for users in themes, with name, description, URL, etc but without email addresses.

See #839 for the original ticket where we added this.

**Comment by salim-dev** [comment]
add_filter( 'rest_endpoints', function( $endpoints ){
    // remove wp/v2/users
    if ( isset( $endpoints['/wp/v2/users'] ) ) {
        unset( $endpoints['/wp/v2/users'] );
    }
   // remove exemple wp/v2/users/1
    if ( isset( $endpoints['/wp/v2/users/(?P<id>[\\d]+)'] ) ) {
        unset( $endpoints['/wp/v2/users/(?P<id>[\\d]+)'] );
    }
    return $endpoints;
});

**Comment by enricodeleo** [comment]
Yes @salim-dev apparently the only way to solve this is to completely unset the `/users` endpoint. I did not unset the `/users/<id>` endpoint since I do need to retrieve user informations from other apps and this is not a disclosure since only consumers behaving as users with `list_users` capability can get those informations (weird thing you can get the admin user by listing all users but not get that very single user).

I don't want to bother @rmccue and the other great people of this project with my concerns since there is a quick way to solve this problem in a few lines of code but from now on, while WP is becoming more and more an application framework (I personally hope so and already use it for this purpose) we should pay more attention on security-related stuffs. 

Today also [wordfence spoke about this issue](https://www.wordfence.com/blog/2016/12/wordfence-blocks-username-harvesting-via-new-rest-api-wp-4-7/) and I have to admit that even if I use this “new“ interface in production it is probably still young and we need to try and test a lot and listen from people that use it in different scenarios.
