### ISSUE TITLE
[] response when i try to get post.

### ISSUE THREAD

**Issue by sumit-youngdecade** [WP-API/WP-API#2931]
Hello sir, When i install this plugin on wordpress version 4.6.1  and want to get post from website ..its not working.I am attaching the url and screen for refrence.

http://www.srilankatourismcatalog.com/wp-json/wp/v2/posts

![p28](https://cloud.githubusercontent.com/assets/19327305/20666064/6d22ad24-b588-11e6-91c0-66237edb13e8.png)

**Comment by jchiatt** [comment]
Hey @sumit-youngdecade, this typically happens if you have no posts. Can you verify that any posts exist in your WordPress Dashboard?

**Comment by sumit-youngdecade** [comment]
Thanks for your reponse..i applogies for the ticket..yes my post was empty..now i have another issue.
I have "taxonomy" and i want to get json data from taxonomy..can you please help me how we can get rerponse in json for a taxnomy.i am url.Please check

http://www.srilankatourismcatalog.com/listingcategory/clubs/

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support is no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
