### ISSUE TITLE
Error when deployed on Azure Server

### ISSUE THREAD

**Issue by jacobokoenig** [WP-API/WP-API#2932]
Hi,

We just installed the plugin into our Wordpress site after doing some tests on a copy of the website, hosted on 1and1. On the master website however (which is hosted on Azure), we are making the following call:

GET caraotadigital.net/wp-json/wp/v2/posts

but getting the following text/html response: Make sure that no custom filters or modules restrict access to the file that you want to browse.

We have found no way of correcting this. Does anybody have an ideas?

**Comment by BE-Webdesign** [comment]
Hi @jacobo360,

Thank you for using the WP REST API.

The permalinks do not appear to be working correctly on the site.  When you do a request to caraotadigital.net/wp-json/wp/v2/posts you will be redirected to caraotadigital.net/wp-json/wp/v2/site/index.php, so my guess is somewhere in your permalink settings everything is being redirected with a /site/index.php tacked on to the end.  I am not 100% sure what problem is, but I am 100% sure it has to do with the way your server is redirecting and handling rewrites.  Once that is resolved, you may find other issues as well.  As long as other special things aren't being done by your Azure server, the API should just work.

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support is no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
