### ISSUE TITLE
List posts: `before` and `after` doesn't seem to support true ISO 8601

### ISSUE THREAD

**Issue by laustdeleuran** [WP-API/WP-API#2933]
Opening this endpoint:

http://demo.wp-api.org/wp-json/wp/v2/posts?before=2016-11-29

Tells me that `The date you provided is invalid.`. However, I _am_ providing a [ISO 8601 compliant](https://en.wikipedia.org/wiki/ISO_8601) date, as [according to](https://cl.ly/3p2G3D3f2e1T) the [documentation](http://v2.wp-api.org/reference/posts/). What format does the `before` and `after` parameters expect?

Thanks!

**Comment by laustdeleuran** [comment]
It looks like providing a full date (with time), makes the endpoint work as expected:

http://demo.wp-api.org/wp-json/wp/v2/posts?before=2016-11-29T00:00:00Z

Maybe the documentation needs to be updated to reflect that?

**Comment by BE-Webdesign** [comment]
@laustdeleuran 

Please open a ticket on https://core.trac.wordpress.org/ as the core endpoints have been merged into core.  I believe somewhere it was decided to only support the full ISO string.  I wrote the patch to add `before` and `after`, but can't remember the discussion around it too well.

**Comment by laustdeleuran** [comment]
@BE-Webdesign Reposted it here: https://core.trac.wordpress.org/ticket/38986#ticket. Closing this.

**Comment by BE-Webdesign** [comment]
@laustdeleuran 

Sorry about that there was already a patch open for it here https://core.trac.wordpress.org/ticket/38641.

**Comment by laustdeleuran** [comment]
No problem. Marked it as a duplicate in the tracker.
