### ISSUE TITLE
How to get results of all categoryies?

### ISSUE THREAD

**Issue by rushijagani** [WP-API/WP-API#2934]
how can i get all search results with entered "query"
 wp-json/wp/v2/categories/(all categories list starts with a)

how can i get categories list based on entered query?

**Comment by beatelite** [comment]
Have you tried:

`/wp-json/wp/v2/categories?s=a`

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support is no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
