### ISSUE TITLE
Trying to create a post with basic authentication - status code 401 - rest_cannot_create

### ISSUE THREAD

**Issue by Stahlisen** [WP-API/WP-API#2935]
I'm trying to create a new post through the REST API using basic authentication.

I pass Authentication as header in my request.

This is my response:
`{
  "code": "rest_cannot_create",
  "message": "Sorry, you are not allowed to create new posts.",
  "data": {
    "status": 401
  }
}`

What I've heard is that this is something to do with the .htaccess. And you can add something like this
`RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]`
in the .htaccess file and that would solve it.

Although, I've tried this without success.

**Comment by beatelite** [comment]
Just to make sure you're covering your basis, you've made sure you have the roles to create posts, yes?

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support is no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
