### ISSUE TITLE
User creation by a user with a custom role (from a role editor plugin) behaving oddly

### ISSUE THREAD

**Issue by beatelite** [WP-API/WP-API#2937]
We are using the wp rest api to allow users with admin-like roles (the roles were created by wpfront user role editor) to create and promote users via the rest api. When the admin user authenticates and creates a new user via the rest api, the new user seems to be created because I can see them in the list of users for the wordpress mulitisite->network->users->list view.

 However, there's a really weird issue where the newly created user is not showing in the users list for the site (the number is correct but they don't show in the list). see: https://drive.google.com/open?id=0B-r5llGpXi8xSmlVR0FvY0Zjd3M

Nor does the newly created user have the primary_blog or source_domain table in wp_usermeta in the db.

If I give the user (the user who's creating new users via the api) the wordpress default "site administrator" role, and they create a new user via the rest api, that new user does show in the user list for the site and are given the primary_blog and source_domain in the DB. **Everything works for the default wp admin role.**

This led me to believe it's an issue with the custom role created by wpfront. 

So as another test, I logged into the wp-admin as the user with an admin-like role created by wpfront  and then created a new user in the wp-admin (as opposed to using the rest api to create the user). Low and behold, everything worked fine. The user was created, shown in the site's users list and given all the appropriate primary_blog and source_domain tables in the DB. 

It looks like, for some reason, the wp rest api has issues with allowing custom roles to create or edit existing users. Do you have any suggestions on how to get this working?

Rest API V: 2.0-beta15
WP V: 4.6.1
WPFront: 2.13

**Comment by beatelite** [comment]
**UPDATE:** I tried to create a custom role (with no plugin) using only the native wp function add_role.

I literally gave them every capability known to humankind (see below) and when I tested editing another user via the api with a user that has the role and capabilities listed below, I got a 403 rest_cannot_edit. 

I think this has everything to do with custom roles not being recognized by the api. 

```
add_action('init', 'sds_add_role');
 
function sds_add_role() {
    add_role(
        'love-admin',
        __( 'Love Admin' ),
           array(
               'activate_plugins' => true,
        'add_users' => true,
        'assign_campaign_terms' => true,
        'copy_posts' => true,
        'create_roles' => true,
        'create_users' => true,
        'delete_campaign' => true,
        'delete_campaign_terms' => true,
        'delete_campaigns' => true,
        'delete_donation' => true,
        'delete_donations' => true,
        'delete_event_categories' => true,
        'delete_events' => true,
        'delete_forums' => true,
        'delete_funder' => true,
        'delete_locations' => true,
        'delete_others_campaigns' => true,
        'delete_others_donations' => true,
        'delete_others_events' => true,
        'delete_others_forums' => true,
        'delete_others_locations' => true,
        'delete_others_pages' => true,
        'delete_others_posts' => true,
        'delete_others_recurring_events' => true,
        'delete_others_replies' => true,
        'delete_others_topics' => true,
        'delete_pages' => true,
        'delete_plugins' => true,
        'delete_posts' => true,
        'delete_private_campaigns' => true,
        'delete_private_pages' => true,
        'delete_private_posts' => true,
        'delete_published_campaigns' => true,
        'delete_published_donations' => true,
        'delete_published_pages' => true,
        'delete_published_posts' => true,
        'delete_recurring_events' => true,
        'delete_replies' => true,
        'delete_roles' => true,
        'delete_themes' => true,
        'delete_topics' => true,
        'delete_users' => true,
        'edit_campaign' => true,
        'edit_campaign_terms' => true,
        'edit_campaigns' => true,
        'edit_dashboard' => true,
        'edit_donation' => true,
        'edit_donations' => true,
        'edit_event_categories' => true,
        'edit_events' => true,
        'edit_files' => true,
        'edit_forums' => true,
        'edit_locations' => true,
        'edit_others_campaigns' => true,
        'edit_others_donations' => true,
        'edit_others_events' => true,
        'edit_others_forums' => true,
        'edit_others_locations' => true,
        'edit_others_pages' => true,
        'edit_others_posts' => true,
        'edit_others_recurring_events' => true,
        'edit_others_replies' => true,
        'edit_others_topics' => true,
        'edit_pages' => true,
        'edit_plugins' => true,
        'edit_posts' => true,
        'edit_private_campaigns' => true,
        'edit_private_donations' => true,
        'edit_private_pages' => true,
        'edit_private_posts' => true,
        'edit_published_campaigns' => true,
        'edit_published_pages' => true,
        'edit_published_posts' => true,
        'edit_recurring_events' => true,
        'edit_roles' => true,
        'edit_theme_options' => true,
        'edit_themes' => true,
        'edit_users' => true,
        'export' => true,
        'import' => true,
        'install_plugins' => true,
        'install_themes' => true,
        'list_roles' => true,
        'list_users' => true,
        'manage_bookings' => true,
        'manage_campaign_terms' => true,
        'manage_categories' => true,
        'manage_links' => true,
        'manage_options' => true,
        'manage_others_bookings' => true,
        'moderate_comments' => true,
        'promote_users' => true,
        'publish_campaigns' => true,
        'publish_donations' => true,
        'publish_events' => true,
        'publish_forums' => true,
        'publish_locations' => true,
        'publish_pages' => true,
        'publish_posts' => true,
        'publish_recurring_events' => true,
        'read' => true,
        'read_campaign' => true,
        'read_others_locations' => true,
        'read_private_campaigns' => true,
        'read_private_donations' => true,
        'read_private_events' => true,
        'read_private_forms' => true,
        'read_private_locations' => true,
        'read_private_pages' => true,
        'read_private_posts' => true,
        'read_private_recurring_events' => true,
        'read_private_replies' => true,
        'read_private_topics' => true,
        'remove_users' => true,
        'restrict_content' => true,
        'switch_themes' => true,
        'unfiltered_html' => true,
        'unfiltered_upload' => true,
        'update_core' => true,
        'update_plugins' => true,
        'update_themes' => true,
        'upload_event_images' => true,
        'upload_files' => true,
        'ure_create_capabilities' => true,
        'ure_create_roles' => true,
        'ure_delete_capabilities' => true,
        'ure_delete_roles' => true,
        'ure_edit_roles' => true,
        'ure_manage_options' => true,
        'ure_reset_roles' => true,
            ) 
        );
 
}
```

**Comment by AlbertGuadan** [comment]
My opinion,  on this very interesting dynamic.
       is the contextual traffic passing,   thru one key, used in an alpha schema role.
 


 The API is needing a child parent structure 
 
 endpoint 

 to be added,  for your shifting role users,   users to bash.
 
The API will then be able to get the underlying roles.

 How-ever,  it may need its users user to own its' own key generated at the time of
 creating the user account,  for speaking to the API

 The API would be in breach if it were to work smoothly for you here.

**Comment by beatelite** [comment]
**Update:** I can edit/create a user as a super admin via the api but that's it. No other role can edit users via the api.

**Comment by AlbertGuadan** [comment]
true

**Comment by beatelite** [comment]
Ok, when I create a new user as a user that has the default administrator role, I can create it fine, but when I go to immediately retrieve it via a GET request, I get:

```
{code: "rest_cookie_invalid_nonce", message: "Cookie nonce is invalid", data: {status: 403}}
code
:
"rest_cookie_invalid_nonce"
data
:
{status: 403}
message
:
"Cookie nonce is invalid"
```

**Comment by AlbertGuadan** [comment]
Could there be a filter here ? 
https://github.com/WP-API/WP-API/pull/2940/files/e83e5b1089da92489f2a642d60f545567c78497a?diff=split

**Comment by beatelite** [comment]
@AlbertGuadan . That's a nice call but when I deactivate the plugin version of the api, I get a 500 error on every endpoint.

**Comment by beatelite** [comment]
I'm wondering if the invalid cookie after creating a user is related to my much earlier bug report: https://github.com/WP-API/WP-API/issues/2285

I also saw this guy had the exact same problem: https://github.com/WP-API/WP-API/issues/1439#issuecomment-125546670

Going to try all this on a fresh install. Will report back.

**Comment by AlbertGuadan** [comment]
Your correct in the correlation of these
 references #2285 and #1439

    
 My next step would be to 
  "iss" (issuer) claim,   and  "sub" (subject) claim.

https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#page-27

**Comment by nylen** [comment]
Hi @beatelite and @AlbertGuadan - development of the API has moved to Trac (https://core.trac.wordpress.org/) and this plugin should be considered deprecated with the release of the endpoints in WP 4.7.

We've made a whole bunch of fixes to all of the endpoints before the 4.7 release.  Can you please upgrade to WP 4.7 and let us know if you are still seeing the same issues?

If there are still problems in 4.7, the next step in getting them fixed is to create tickets on Trac.  Clear reproduction steps from a clean install of WordPress (and unit tests) are the most helpful things to see there.

**Comment by beatelite** [comment]
https://core.trac.wordpress.org/ticket/39155

**Comment by AlbertGuadan** [comment]
Good starting point,  @nylen  

    4.7 and the API @Core,  and so  many features,  including translation.
 How does it get any better than that.

 awesome.

**Comment by beatelite** [comment]
closing. See: https://github.com/WP-API/WP-API/issues/2944#issuecomment-265582465
