### ISSUE TITLE
Wrong result for filter[posts_per_page]

### ISSUE THREAD

**Issue by violacase** [WP-API/WP-API#2942]
**Preface:** I searched and tried all posts concerning this issue thoroughly on stackexchange and wordpress.stackexchange spending 10+hours trying without getting a solution.

After a fresh WP install on localhost:
- deleted default plugins
- set permalinks to /%postname%/
- installed and activated plugin wp rest api v2
- generated 12 posts, so the total # of posts is now 13
- gave a GET command in **Postman**: {siteURL}/wp-json/wp/v2/posts?filter[posts_per_page]=1

Result: the default 10 posts.

Headers returned:
```
Link →<http:{siteURL}/wp-json/wp/v2/posts?page=2>; rel="next"
Server →Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/7.0.13
Transfer-Encoding →chunked
X-Content-Type-Options →nosniff
X-Powered-By →PHP/7.0.13
X-Robots-Tag →noindex
X-WP-Total →13
X-WP-TotalPages →2
```
My issue: I think that filter 'posts_per_page' isn't parsed somehow.
The returned header 'Link' query part 'page=2>; rel="next' is not what I asked for I think.

What is going wrong here?

**Comment by kadamwhite** [comment]
Hey @violacase, thanks for using the REST API—I can shed some light onto this. `filter` has been removed entirely in 4.7, and the posts_per_page filter in particular was deprecated several betas earlier in favor of using a first-party per_page argument: the pagination of collections should be handled directly via `?per_page=` and `?page=` query parameters. We definitely could have done a better job of calling out this change in the release notes and I'm very sorry to hear how long this took to resolve.

**Comment by kadamwhite** [comment]
I'm going to close this out as it is likely that the plugin is behaving as designed, and that the error is our documentation lagging behind. If you find that {siteURL}/wp-json/wp/v2/posts?per_page=1 does not work, please comment below and we can help troubleshoot further. 

In other news, if everything happens according to schedule, then within 24 hours you can install WordPress 4.7 and these endpoints will be available without the need for this plugin!

**Comment by violacase** [comment]
Thanks kadamwhite! Works as a charme.

My 2 pennies:
PLEASE, PLEASE, PLEASE create an info-page dedicated for end users. For me this was (thus) a horrible journey just because of the lack of information.
It's good(!) to hear the 4.7 release is coming up but maybe you should wait untill end users documents (with LOTS of showcases!) have been published.

Keep up the good work!

**Comment by violacase** [comment]
PS: I would like to make a (final) comment on all kind of posts on *.stackexchange concerning this kind  of issues to state that proposed solutions are deprecated. What links to the state-of-now-solutions can you suggest?

**Comment by kadamwhite** [comment]
@violacase this is the best page to link to: https://developer.wordpress.org/rest-api/pagination/ I wrote it today after hearing about your difficulty. I thank you for your input, I hope this will help developers in the future!

**Comment by violacase** [comment]
Great! Your team is doing a great job making WP a worthy CMS. Keep on writing...
