### ISSUE TITLE
500 Error on Multisite

### ISSUE THREAD

**Issue by ameshkin** [WP-API/WP-API#2943]
This worked well on a fresh wordpress installation.  But I can't get it to work on a multisite installation.
Anyone else having this problem?  I get a 500 error but nothing goes into the error log

**Comment by beatelite** [comment]
I am using it a multinetwork (multiple multisite installs) and it works great. 

When you say you can't get it to work, what do you mean? can you walk us through what "work" means?

Make sure it's network active to start.

**Comment by rohitagre** [comment]
@ameshkin are you using any other plugins along with this plugin? it may be the case that something else is interfering.

**Comment by rveitch** [comment]
I've been experiencing the same issue on one of my multisite networks and have been beating my head against the wall for months trying to solve it. I've included a list of network active plugins, however I believe I have systematically deactivated each one with no success/change in behavior.

![screenshot4131](https://cloud.githubusercontent.com/assets/12876929/21157939/e89e3d56-c140-11e6-992b-8ad97823ca69.png)

EDIT: Finally found our error, it was a very old rewrite rule in htaccess.

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support is no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
