### ISSUE TITLE
403  "rest_cannot_edit" message when trying to edit user. 

### ISSUE THREAD

**Issue by beatelite** [WP-API/WP-API#2944]
Not entirely sure it's related to my other issue https://github.com/WP-API/WP-API/issues/2937 regarding  updating users via the api so I'm opening here. 

When I attempt to update the following endpoint

`/wp-json/wp/v2/users/141?context=edit`

with any change to the user, I get:

` 403 "rest_cannot_edit" `message .

I'm logged in and posting via the api as a site administrator (native wp admin role) and am authenticated via a nonce. 

What am I missing?

Rest API V: 2.0-beta15
WP V: 4.6.1

**Comment by johnbillion** [comment]
This is correct behaviour. A regular administrator on a multisite installation does not have the ability to edit users.

Does the user you're authenticating with have the ability to edit users through the admin area?

Core ticket discussing the same issue: https://core.trac.wordpress.org/ticket/39155

**Comment by beatelite** [comment]
No, they don't. I never even knew it. I figured out a way around it for now using this: https://thereforei.am/2011/03/15/how-to-allow-administrators-to-edit-users-in-a-wordpress-network/

I'm aware of the security implications but have no choice right now.
