### ISSUE TITLE
'Making your own context' & Modifying Responses

### ISSUE THREAD

**Issue by ChrisSargent** [WP-API/WP-API#2947]
Hi,

In the documentation for 'Modifying Responses' here: http://v2.wp-api.org/extending/modifying/, it suggests not modifying or removing fields from responses but to do this: 'Removing fields is never encouraged; if you need to get back a smaller subset of data, work with contexts instead, and consider making your own context.'

However, I can't find any documentation or information about creating or using a new context. Am I missing something or is there some information out there somewhere?

Thanks,

Chris

**Comment by kosso** [comment]
You could try adding your own namespace / endpoints to provide a custom dataset that fits your needs:  See here: http://v2.wp-api.org/extending/adding/

**Comment by nylen** [comment]
Now that the REST API has been merged into WordPress core, development and support is no longer taking place in this repository.

If you're still having this issue, please post a support request to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
