### ISSUE TITLE
Consistent WP_Error code naming

### ISSUE THREAD

**Issue by pkevan** [WP-API/WP-API#295]
While trying to write some unit tests for WP_JSON_Media I came across some inconsistencies in the naming of error codes:

https://github.com/WP-API/WP-API/blob/master/lib/class-wp-json-posts.php#L1247
and
https://github.com/WP-API/WP-API/blob/master/lib/class-wp-json-media.php#L35

I assume it's not a problem to have the same error names in different instances since they are both referring to the same problem?  The naming extends to Customposttype as well.

My preference would be the one used in posts

**Comment by danielbachhuber** [comment]
We'll handle WP_Error consistency for `develop` in #1166
