### ISSUE TITLE
Filtering posts based on category does not work anymore

### ISSUE THREAD

**Issue by mellevanderkolk** [WP-API/WP-API#2950]
Hello :)

Since today my filtering url does not work anymore...

https://www.myurl.nl/wp-json/wp/v2/posts?filter[category_name]=esns
This normaly gave me all the posts just from that category (wordpress) but now it just gives me all posts and it does not filter anything anymore...

Can anyone help me please :)

Thanks in advance!!!!

**Comment by joehoyle** [comment]
Hey @mellevanderkolk, this was removed in WordPress 4.7, however we have a compatibility plugin which you can add to your site to restore this functionality, see https://github.com/WP-API/rest-filter.

**Comment by kadamwhite** [comment]
@mellevanderkolk This issue was asked earlier today, here's a way to achieve the same thing using the API out-of-the-box: #2949

**Comment by mellevanderkolk** [comment]
Thanks to all! IT works great

Verstuurd vanaf mijn iPhone
