### ISSUE TITLE
How to make a WP REST API query with meta_query in WP4.7?

### ISSUE THREAD

**Issue by krusze** [WP-API/WP-API#2953]
There is no "filter" parameter in WP REST API WP 4.7 and this call doesn't work: http://domain.tld/wp-json/wp/v2/cpt_name?meta_query[0][key]=cf_name&meta_query[0][value][0]=cf_value1&meta_query[0][value][1]=cf_value2&meta_query[0][compare]=IN

**Comment by luistinygod** [comment]
I have the same issue! The `filter` argument has disappeared in 4.7.

**Comment by kadamwhite** [comment]
This change was announced on the make.wordpress.org core blog -- filter is now available via this plugin: http://github.com/wp-api/rest-filter if you need to reinstate it

**Comment by kadamwhite** [comment]
I'm going to close this issue as the removal of filter was a deliberate decision that was discussed both here on github and in the WordPress development channels, but please open an issue on the REST-filter plugin if that doesn't solve your problems!
