### ISSUE TITLE
comment issue

### ISSUE THREAD

**Issue by tree1891** [WP-API/WP-API#2954]
I can see comments with /wp/v2/comments.
but when using /wp/v2/comments/911, it respond as following. 911 is comment id.
{
    "code": "rest_cannot_read_post",
    "message": "Sorry, you cannot read the post for this comment.",
    "data": {
        "status": 403
    }
}

**Comment by rmccue** [comment]
We're no longer handling support here on GitHub, please [ask on WordPress.org](https://wordpress.org/support) instead.

This is caused by not having permission to access the post that the comment belongs to.
