### ISSUE TITLE
How to get posts results by 'search' & 'category_name'?

### ISSUE THREAD

**Issue by rushijagani** [WP-API/WP-API#2955]
`wp-json/wp/v2/posts?search=hello&category_name=uncategorize&per_page=30&order=asc`
I am not getting results based on category 'uncategorize'.
Instead I got results from all categories.

**Comment by kadamwhite** [comment]
Hello and thank you for using the REST API! Filtering by category terms should be done by ID, as slugs are a less reliable and efficient relationship: the recommended approach is to retrieve the ID of the term then query by that with `?categories=`. see #2949 for a discussion of available workarounds. 

At this time there are not plans to add first-party filtering by category term slugs, so I'm going to close this out, but if you wish to propose this as an enhancement for future versions of the API i'd encourage you to open a ticket in the core WordPress Trac issue tracker for discussion!
