### ISSUE TITLE
How to get results of subcategories also?

### ISSUE THREAD

**Issue by rushijagani** [WP-API/WP-API#2956]
We can get posts from a category using below request

                `/wp/v2/posts?categories=1&search=somequery`

How can we get results from category(1) and from all subcategories of (1) also?
Than You.

**Comment by rmccue** [comment]
Hi! We're no longer handling support here, please ask on the [WordPress forums](https://wordpress.org/support) instead.

This functionality is not possible in the API itself, you'll need to install a plugin, or fetch the IDs for subcategories yourself.
