### ISSUE TITLE
No route found

### ISSUE THREAD

**Issue by thomasmaitre** [WP-API/WP-API#2957]
Hi guys, 

I get this error when try to get my posts.
[{"code":"json_no_route","message":"No route was found matching the URL and request method"}]

Any ideas ?
Thanks

**Comment by JPry** [comment]
@thomasmaitre What's the exact endpoint you're using?

**Comment by thomasmaitre** [comment]
http://www.maddyness.com/wp-json/wp/v2/posts

**Comment by JPry** [comment]
@thomasmaitre It looks like your site is running 4.3.1 version of WordPress, and the [V1 REST API plugin](https://wordpress.org/plugins/json-rest-api/). You should deactivate the V1 plugin and update WordPress to 4.7, which includes the newest version of the REST API.

To access your posts with the current API on your site, you should use `/wp-json/posts`.

**Comment by thomasmaitre** [comment]
Hi,
It's all good on this end point : http://www.maddyness.com/wp-json/posts
Thx for your help

--

*Thomas Maitre* / Fondateur
thomas@vizir.co / +33 7 82 31 30 34

*Vizir.co*
https://vizir.co
18, sur les prés d'Ilay, 39130, Le Frasnois
Discutons => prenons RDV <https://www.vyte.in/thomas>

**Comment by JPry** [comment]
Hi @thomasmaitre,

I'm glad I could help. Please keep in mind that you really need to keep your site updated. Using the old API should be a **temporary** solution. The best permanent solution is to remove the old plugin and update WordPress.

**Comment by pritty12** [comment]
Hi,
I get this error when try to fetch data from api.
{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}
How to solve this?Any ideas ?
Thanks

**Comment by JPry** [comment]
@pritty12 This is no longer the place to receive support for the API. Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
