### ISSUE TITLE
Wordpress JSON API failing to provide results to file_get_contents

### ISSUE THREAD

**Issue by WorldsEndless** [WP-API/WP-API#2958]
Trying json_addr in the browser works and gives me the results I want; however, file_get_contents is returning only an empty array. Why is this? 

#+BEGIN_SRC php
```
$json_addr = 'http://humstaging.byu.edu/humanities/wp-json/wp/v2/people?filter[posts_per_page]=-1&filter[taxonomy]=persondepartments&filter[term]=spanish';
$json = file_get_contents($json_addr);
echo "Contents of <a href='$json_addr'>json</a> are:<br><br>";
echo $json;
```
#+END_SRC

**Comment by JPry** [comment]
@WorldsEndless I get the same result in a browser and using PHP: Just an empty array `[]`.

**Comment by WorldsEndless** [comment]
The same issue occurs with curl: 
#+BEGIN_SRC 
```
curl -g 'http://humstaging.byu.edu/humanities/wp-json/wp/v2/people?filter[posts_per_page]=-1&filter[taxonomy]=persondepartments&filter[term]=spanish'

[]
```
#+END_SRC

**Comment by WorldsEndless** [comment]
@JPry  When I attempt that URL in a browser it gives me the json result that I want, but when I try it from anywhere else I get an empty array. Are you getting the empty array all the time, or is your attempt in a browser giving a working result?

**Comment by JPry** [comment]
@WorldsEndless I get an empty array all the time, regardless of whether or not I use a browser or not. Perhaps your browser has cached the API result?

**Comment by BE-Webdesign** [comment]
@WorldsEndless,

Thank you for using the WP REST API.

I get an empty array as well from following the uri.  The filter param was removed in WordPress 4.7, are you on WP 4.7 yet?

**Comment by WorldsEndless** [comment]
**UPDATE** The problem has been identified: if I am logged in to WP as an admin at the target site (humstaing/humanities), I get the desired result. However, from any browser session in which I am not logged in on the target site, I get an empty array. Why do I need to be logged in for this public data?

**Comment by BE-Webdesign** [comment]
@WorldsEndless 

It is possible that your site has been configured to require some sort of authentication when accessing endpoints.  Do you have any extra plugins using any of the REST API hooks?

**Comment by WorldsEndless** [comment]
@BE-Webdesign Ah! Thanks for setting me on the right track! Going through my plugin list, it turn out to have been the [Press Permit Core](https://wordpress.org/plugins/press-permit-core/) permissions plugin causing those endpoints to return empty. I will look in to authentication and this will be fixed. Thanks very much!

**Comment by BE-Webdesign** [comment]
@WorldsEndless,

I also highly recommend using `rest_do_request()` for what you are trying to accomplish.
