### ISSUE TITLE
Issues with query parameters

### ISSUE THREAD

**Issue by redsoxfan2499** [WP-API/WP-API#2959]
With Rest API moving to Core WordPress 4.7. I cannot get my query parameters to work correctly. I am not sure where to post issues and get help. I have attempted on multiple server and local. Local is running Apache on MAMP and all of my other servers are Apache. When I try to run a filter on posts using tags I get all of my posts back. when I try filter by category I get a random number of posts. Any help would be greatly appreciated! 

so here is what I am running for reference:
http://localhost/wpdev/wp-json/wp/v2/posts?filter[category]=baseball
http://localhost/wpdev/wp-json/wp/v2/posts?filter[tag]=food 

Thanks!

**Comment by BE-Webdesign** [comment]
@redsoxfan2499,

Thank you for using the WP REST API.  The `filter` param was removed in WordPress 4.7.  I believe there is a plugin somewhere that adds it back if you need it.  The filter param was removed as it presented some potential maintainability issues along with other concerns.

You can do your queries using the ID for the terms you need to use.

```
/wp/v2/posts?categories=(id_of_baseball)
/wp/v2/posts?tags=(id_of_food)
```

Hopefully that helps out!

**Comment by kosso** [comment]
As mentioned in #2949 here's the link to the plugin to reactivate `filter` https://github.com/wp-api/rest-filter

**Comment by BE-Webdesign** [comment]
Thanks @kosso!

**Comment by redsoxfan2499** [comment]
Excellent help from everyone! 
 
Greatly appreciated! 

Darren

**Comment by redsoxfan2499** [comment]
Guys, I am using the plugin suggested by kosso. It works fine for tags but does not work for categories. Man this is flustrating. Enjoying having the API in core but moving out the filtering. I have a theme that I need to use the REST API to filter by tags and categories. So when I run this it works great. but when I try to filter categories nothing works. I get all of my posts back. I tried many different ways. by cat IDS and Cate name No Luck. Anyone has any direction?? 

Tags example: /wp/v2/posts?filter[tag]=beef  WORKS GREAT

Cat example:  nothing works
/wp/v2/posts?filter[categories]=baseball get all posts
/wp/v2/posts?filter[category]=baseball  get all posts returned
/wp/v2/posts?filter[categories]=5   get all posts returned. 

Also looking at the new documentation, I cannot find the proper way to get this information 
I disabled the plugin and tried /wp/v2/posts/categories/baseball    no route. Also tried /wp/v2/posts/categories/5   no route.   

What am I doing wrong. I need to use the REST API to get posts by a specific category.  When I run the categories endpoint it does return all my categories successfully. 

As always thanks in advanced!

Darren

**Comment by kadamwhite** [comment]
Hey there, thanks for noting the issue, we're going to work on a docs page for term queries this week. To query by taxonomies or categories by ID, use


```
/wp/v2/posts?categories=5
/wp/v2/posts?tags[]=8&tags[]=123
```
for the syntax to get posts in one or several (in OR relationship) taxonomy terms

**Comment by redsoxfan2499** [comment]
kadamwhite, 

thanks for the quick response and your help. I will give those endpoints a try and let you know if I run into any more issues. 

Question to anyone who works on the REST API. Besides the REST API Developer Handbook, is there anymore documentation for the new REST API that will also show the changes from the REST API 2 version plugin to the new REST API code in WP 4.7. 

Thanks to everyone who has contributed to this thread! 

Darren

**Comment by redsoxfan2499** [comment]
kadamwhite, 

thanks for the endpoints for filtering categories. It works great. 

Question: Will the REST API (in the future) return the both the category name and ID in one response. That way we do not have to make multiple requests? 

Thanks, 

Darren

**Comment by kosso** [comment]
Have you tried using : 

`/wp-json/wp/v2/posts?filter[taxonomy]=category&filter[term]=YOUR_CATEGORY_SLUG`  ?

 That works for me (with the extra filter plugin installed too).

**Comment by redsoxfan2499** [comment]
So here this the problem I am running into. Say I want to create a new template file that replicates the basic index.php. Where it gets the post, the post meta, author, excerpt, and Posted in Categories and Tagged tags. So in the current REST API. I have access to an endpoint (/wp/v2/posts) that gives me this information but for cats and tags, gives me only ids. Thus I have to then turn around and call 2 other endpoints, (/wp/v2/categories) to get the category name and (/wp/v2/tags) to get the tag name.  So thus my question of future REST API to return ids and names for Cats and Tags.     If anyone else has a better suggestion to get this information from the REST API, I am open to any and all suggestions. 

As always, thanks in advance! 

Darren

**Comment by BE-Webdesign** [comment]
@redsoxfan2499,

When you do your posts request add the `_embed` query parameter and you will get back `_embedded` data in the response.  `wp:term` will have the information about the terms related to that particular post. 

Closing out this issue as these are general support questions, not issues with the API. Feel free to continue discussion here.  We will still get notices of new messages and will help when we can.

**Comment by redsoxfan2499** [comment]
BE-Webdesign. Thanks for the suggestion of using the _embed query parameter. I did not know about this. I also did not know where to post this comment as in your reply above you state "Feel Free to continue discussion here"  but there is no link to another URL. Was there supposed to be a link to another page? 

Thanks for your help.

**Comment by BE-Webdesign** [comment]
@redsoxfan2499 

You posted in the right place.  We close out tickets that are not bugs/discussions regarding the API's design.  Glad the `_embed` parameter helped.

Check out the [documentation site](http://v2.wp-api.org/) or the [REST API handbook on WordPress.org](https://developer.wordpress.org/rest-api/), they will be a reasonably good source of information.

Thank you for using the WP REST API!  If you build something cool with it, open an issue about it!

**Comment by kosso** [comment]
👍  I was out when I saw a notification about this. But yes, the `_embed` parameter is the way to go. 

There's clearly room for improvement in the docs. So much just isn't there (but here).

**Comment by 8ctopotamus** [comment]
Is there any way to get this working with Custom Post Types and Custom Taxonomies?
The plugin doesn't seem to help and I am trying to query something like:

`example.com/wp-json/wp/v2/podcasts?filter[group_access]=group-name`

"group-name" is a string, not a number

**Comment by milad145** [comment]
hi guys,
can you see #3032
and help me
