### ISSUE TITLE
Exposed usernames in users endpoint

### ISSUE THREAD

**Issue by gerhardsletten** [WP-API/WP-API#2961]
Now with the wp-json api merged into Wordpress 4.7 a lot of wordpress-sites will (mayby unaware) expose all registered usernames in their site. Knowing the username makes hackers a whole lot closer to breaking in if users reuse passwords across sites or use simple, common passwords.

Maybe the users endpoint should be protected by default?

**Comment by websupporter** [comment]
Hi gerhardsletten,
all information exposed through the REST API is already exposed through the website. When you are not logged in or you do not have the right to list users in the backend, you will only see those users, who have published posts:
https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-users-controller.php#L159

The user details of these users are already present on the page itself.

**Comment by rmccue** [comment]
We're no longer handling support requests here, please [ask on the support forums](https://wordpress.org/support) or [file an issue on Trac](https://core.trac.wordpress.org/) instead.

Usernames are already exposed through themes, RSS feeds, etc, and we do not consider them a security issue. You can install a third-party plugin if you would like to limit access to this data.

**Comment by ehrig** [comment]
The following post contains two Gists, which prevent non-logged-in visitors/non-admins from accessing API endpoints: http://maddisondesigns.com/2016/12/what-you-may-not-know-about-the-wp-rest-api/

**Comment by gerhardsletten** [comment]
I ended up disabling the rest-api with a plugin, and disabling the xml-rpc api, because the boots find the usernames via rest-api, and then they starts attaching the xml-rpc with multicall.

We had about 1000 failed login-attempts every day.

The regular login-url you can change with some of the security-plugins, but as long as you want to use Jetpack you would need to keep xml-rpc open.
