### ISSUE TITLE
 Since filter has been removed, how to get posts by meta?

### ISSUE THREAD

**Issue by adminko-svk** [WP-API/WP-API#2964]
Hi, how I can get post by `?filter[meta_key]=key&filter[meta_value]=my-key` ?

**Comment by modemlooper** [comment]
There is a plugin https://github.com/WP-API/rest-filter

**Comment by adminko-svk** [comment]
@modemlooper thank you, but it is not working for meta

**Comment by martingreenwood** [comment]
Can confirm this doesn't fix the issue either... still getting the same problem after installing and activating...

**Comment by ghost** [comment]
can't get post by category

**Comment by rmccue** [comment]
Hi! We're no longer tracking support queries on GitHub, please ask on the [support forums](https://wordpress.org/support/) instead.

If you're having problems with the rest-filter plugin, file them on the [issue tracker](https://github.com/WP-API/rest-filter/issues) for that plugin instead.
