### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by marvinbik** [WP-API/WP-API#2966]
Hi,
I installed https://wordpress.org/plugins/rest-api/ on my wordpress site but it shows the below error:

Fatal error: Call to undefined function get_registered_meta_keys() in /home/content/30/8927630/html/wp-content/plugins/rest-api/lib/fields/class-wp-rest-meta-fields.php on line 244

Can you please help on it?
Thanks,

**Comment by viankakrisna** [comment]
I also have this error. any help? WP 4.5.2 using wp rest api plugin

**Comment by viankakrisna** [comment]
fixed by upgrading to 4.6
if you cannot upgrade, adding this to functions.php will fix the issue:


    if (!function_exists('get_registered_meta_keys')){
        function get_registered_meta_keys( $object_type ) {
            global $wp_meta_keys;
            if ( ! is_array( $wp_meta_keys ) || ! isset( $wp_meta_keys[ $object_type ] ) ) {
                return array();
            }
            return $wp_meta_keys[ $object_type ];
        }
    }

**Comment by rmccue** [comment]
Hi! We're no longer supporting the API on GitHub, please file support requests [on WordPress.org](https://wordpress.org/support).

Please also make sure you're using WordPress 4.7 or later, as the plugin is no longer supported for older versions.
