### ISSUE TITLE
rest_no_route when accessing wp-json index but it's fine elsewhere

### ISSUE THREAD

**Issue by ohohohoo** [WP-API/WP-API#2969]
Hello, I posted this question before at [this page](https://github.com/WP-API/WP-API/issues/1509#issuecomment-265615146), but because that is a closed issue and everyone on that page seemed to have moved on already, I decided to create a new issue instead.

So after upgrading into WP4.7 on my test machine (with wp-rest-api plugin still activated and later deactivated) I'm having this issue on my end too. I received JSON rest_no_route when accessing /wp-json/ directly, but when I tried to access it via ?rest_route=/ ... it works just fine. I can see the namespace.

Accessing custom route via /wp-json/my/own/custom/route is good. Accessing /wp-json/wp/v2/ also okay and it display all the namespace. But not /wp-json/.

Back then on WP4.6 with 2.15 Beta rest api plugin I never experienced this issue. This issue is appear after I upgraded to WP4.7.

I tried deactivating all plugins but still that didn't fix it. I also tried reenabling permalink (choose the one with query and return to usual permalink) again, but still the problem persist. And I have no idea on what to do next.

Anyone has any idea on what could cause this and any possible steps that I could try to fix this?

**Comment by rmccue** [comment]
Hi! We're no longer tracking support requests on GitHub, so please file on [WordPress.org instead](https://wordpress.org/support/).

In this case, it sounds like there may be an issue with your permalinks. The root index (`/wp-json/`) uses a different rewrite rule to the other routes, and it's this rule that might be the issue. It could be another plugin being overly aggressive with their rewrite rules.
