### ISSUE TITLE
Unauthenticated clients should be able to view (limited) user information

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#297]
Clients are currently required to have `list_users` to retrieve any user information, however this information is already via post data (and through the site itself typically). We should ensure that the view context is available for everyone, and move everything private into the edit context.

**Comment by danielbachhuber** [comment]
Related #838

**Comment by rachelbaker** [comment]
Closing this issue for v1.x of the API and #839 tracks this for v2.x
