### ISSUE TITLE
Javascript client

### ISSUE THREAD

**Issue by ibbatta** [WP-API/WP-API#2970]
Is there a way to get authentication / authorization with Angular?
I am building a js client that is fully separated from wordpress and I am not able to get users informations because I have not authorization and I really don't know what to do.

Yes: I have read the documentation (but it's not really simple to understand)

Thanks in advance for you reply (or your help)

**Comment by modemlooper** [comment]
Did you read this? https://oauth1.wp-api.org

**Comment by ibbatta** [comment]
@modemlooper yes 😞 
Assuming that i use the beta v2 version, seems I need always some kind of variables from wordpress and this is exactly the thing I don't want to.

(p.s. I apologize for my awful english)

**Comment by modemlooper** [comment]
The oauth 1 implementation in WP-API is not special. Google and learn more about oauth. Once you understand it it's not that difficult.

**Comment by ibbatta** [comment]
I'll try, but at the moment i'm stuck

**Comment by kadamwhite** [comment]
@ibbatta You should check out [this JavaScript library](https://github.com/WP-API/wordpress-rest-api-oauth-1), which provides some utilities to aid in OAuth authentication.

**Comment by ibbatta** [comment]
Thanks guys :)
