### ISSUE TITLE
How to get JSON data from tevolution plugin

### ISSUE THREAD

**Issue by sumit-youngdecade** [WP-API/WP-API#2971]
Hi ,we have directory listing site and i am using tevolution plugin.they also have some documenation but its not working.Now i just need two information
1.get all category from tevolution plugin.
2.get all post catgory wise data.

this is plugin documenation url-
https://templatic.com/docs/how-to-use-wp-rest-api-in-directory-and-child-themes/

this is all end points url

http://www.srilankatourismcatalog.com/wp-json/tevolution/v2/

Please help me on this issue,,,we need to launch app before New year.Just tell me two thing.
1.What will be end point to get all category according to plugin??
2.What will be end poindt to get all directory/post according to category ID ???

waiting for your positive reply

**Comment by modemlooper** [comment]
You should ask the plugin author since it's custom endpoints

**Comment by rmccue** [comment]
We're no longer tracking support requests on GitHub, please [file support requests on WordPress.org instead](https://wordpress.org/support/).
