### ISSUE TITLE
Creating a post with custom meta fails with a "rest_cannot_update" error

### ISSUE THREAD

**Issue by simonegiacco** [WP-API/WP-API#2972]
The creation of a post fails if you try to set some custom meta.
It fails also when the custom meta is correctly registered with "register_meta", and also if a "auth_callback" is correctly set.

The bug is in:
WP_REST_Posts_Controller::create_item( )
/lib/endpoints/class-wp-rest-posts-controller.php:432

```
$post = $this->get_post( $post_id );
if ( ! empty( $schema['properties']['meta'] ) && isset( $request['meta'] ) ) {
	$meta_update = $this->meta->update_value( $request['meta'], (int) $request['id'] ); 
	if ( is_wp_error( $meta_update ) ) {
		return $meta_update;
	}
}

```

Since we are creating a post, and not updating it, $request['id'] is always empty.
This is also evident at the beginning of the create_item() function:

```
public function create_item( $request ) {
	if ( ! empty( $request['id'] ) ) {
		return new WP_Error( 'rest_post_exists', __( 'Cannot create existing post.' ), array( 'status' => 400 ) );
	}
```

**Comment by rmccue** [comment]
Hi! We're no longer tracking issues here on GitHub, please file them on [WordPress core Trac](https://core.trac.wordpress.org/) instead.
