### ISSUE TITLE
Many Pages but i need only one. Help me Please

### ISSUE THREAD

**Issue by mrenigmabr** [WP-API/WP-API#2974]
Hi All

Sorry but my english is very bad. I'll try.
In my project i have many clhildrens and:
Every child has your page
Each page has several posts of this child's treatments
In the posts we have texts and images
And we also have the laboratories that do the remedies
On the site we have many children registered

i will create an application for each child.

How do I get the data only from a specific child?

Can u help me ?

Thanks in advantage,

**Comment by rmccue** [comment]
Hi. We're no longer tracking support requests on GitHub, please use the [WordPress forums](https://wordpress.org/support/) instead.

To get singular items, you can use `/wp/v2/posts/{id}` (replacing `{id}` with the ID of the post). This applies to all post types.
