### ISSUE TITLE
remove shortcode from meta response

### ISSUE THREAD

**Issue by packytagliaferro** [WP-API/WP-API#2975]
So far i am adding in meta data to the post response like so:

```
function slug_get_post_meta_cb( $object, $field_name, $request ) {
    return get_post_meta( $object[ 'id' ], $field_name, true );
}
 
function slug_update_post_meta_cb( $value, $object, $field_name ) {
    return update_post_meta( $object[ 'id' ], $field_name, $value );
}

add_action( 'rest_api_init', function() {
	register_api_field( 'post',
	    'ea_post_vision',
	    array(
	       'get_callback'    => 'slug_get_post_meta_cb',
	       'update_callback' => 'slug_update_post_meta_cb',
	       'schema'          => null,
	    )
	);
});
```

which works well, but the meta field has a short code in it like [embed] VIDEO LINK [/embed]. How can I remove this shorcode? I have seen `strip_shortcodes( string $content )` but I use this api through an app so the shortcodes need to be removed before the api spits them out

**Comment by rmccue** [comment]
Hi! Since the API has been merged into WordPress core, we're no longer taking support requests here, please [ask on the WordPress forums](https://wordpress.org/support) instead.

In this case, you can use `return strip_shortcodes( get_post_meta( ...` in your `slug_get_post_meta_cb` function.
