### ISSUE TITLE
GET WP REST API Information

### ISSUE THREAD

**Issue by jubari7** [WP-API/WP-API#2978]
Hi All,

How do i create WP REST API to get this data information?

Please refer to this link http://prntscr.com/dlkn2p

Thanks

**Comment by ArnaudBan** [comment]
If you check this url : http://yourinfo.id/wp-json/wp/v2
You will find every endpoint that are register for the "/wp/v2" Namespace.

I think you want to check one of those two endpoint : 
http://yourinfo.id/wp/v2/directory
http://yourinfo.id/wp/v2/directory_types

The problème is that they return a 404 status. Maybe you need to flush your rewrite rules ?

**Comment by jubari7** [comment]
Hi ArnaudBan,
Thank you for your answer.

I need to retrieve custom category tag name instead of  tag_id.
http://prntscr.com/dm1rqy
Thanks

**Comment by ArnaudBan** [comment]
Do you have the name on this endpoint : http://yourinfo.id/wp/v2/directory_types/95 ?

**Comment by jubari7** [comment]
Hi ArnaudBan,
I don't have that.. do i have to create it?

**Comment by jubari7** [comment]
http://yourinfo.id/wp/v2/directory  
Result  dispaly  =  directory_categories [95] 
95 refer to tag_id  which have tag name.

how do i retrieve the tag name?

**Comment by ArnaudBan** [comment]
Sorry but for me http://yourinfo.id/wp/v2/directory is a 404 error. I think your API is secure and you have to be logged in to view it. It is hard to help you when not seeing the result of the API.

**Comment by jubari7** [comment]
Hi ArnoudBan,

Please use below link :
http://yourinfo.id/wp-json/wp/v2/directory

**Comment by ArnaudBan** [comment]
When you register your "directory_categories" taxonomy, did you add the "show_in_rest" => true argument ?
It seems like your taxonomy doesn't have it's own endpoint.

**Comment by rmccue** [comment]
Hi there! We're no longer handling support requests on GitHub, please [use the WordPress forums](https://wordpress.org/support/) instead.
