### ISSUE TITLE
403 Cookie nonce is invalid react front end to pull revisions

### ISSUE THREAD

**Issue by BioRyse** [WP-API/WP-API#2979]
Hello,

I’ve seen a couple other forum posts relating to this, however I’ve yet to see one with a resolved status. I’m using the WP API restful plugin that is utilized by a react/redux front-end. I’ve followed the documentation to bring in the wp_create_nonce() function via the wp_localize_script.

Here is the relevant portion in the functions.php in the theme folder.

```
function c3d_scripts() {

	wp_enqueue_style(
		'ionicframework',
		'http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css'
	);
	wp_enqueue_style( 'style', get_stylesheet_uri() );

	wp_enqueue_script(
	 	'script-vendor',
		get_template_directory_uri() . '/js/vendor.js',
		array(),
		false,
		true
	); wp_enqueue_script(
	 	'script-app',
		get_template_directory_uri() . '/js/app.js',
		array(),
		false,
		true
	);
        wp_localize_script( 'script-app', 'I18N', array('lang' => substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2),));
//Allow nonces to be grabbed by JavaScript.
	wp_localize_script( 'script-app', 'wpApiSettings', array( 'root' => esc_url_raw( rest_url() ), 'nonce' => wp_create_nonce( 'wp_rest' ) ) );
} 

add_action( 'wp_enqueue_scripts', 'c3d_scripts' );
```

I then pull in the wpApiSettings through the our react code.

```
const WP_SETTINGS = get(window, 'wpApiSettings', '')
const requestHeader = {
  headers: {
        'Accept': 'application/json',
        'X-WP-Nonce': WP_SETTINGS.nonce
    }
}

class PopulatedPost extends Base {
  constructor(props) {
    super(props);
  }
  componentWillMount() {
    // console.log('Single post componentWillMount *****');
    const { item, routeParams, fetchPosts, location } = this.props;
    if (item === null) {
      const api = APIS.singularPost()
      fetchPosts(api, requestHeader)
    }
  }

```
fetchPosts above adds the requestHeader to the header and I know get this back by modifying the following rest-api.php rest_cookie_check_errors( $result ) function snippet:

```
$result = wp_verify_nonce( $nonce, 'wp_rest' );

	if ( ! $result ) {
		return new WP_Error( 'rest_cookie_invalid_nonce', __( 'Cookie nonce is invalid' ), array( 'status' => 403, 'nonce' => $nonce, 'result' => $result ) );
	}
```

This gives me the status, nonce, and result of the wp_verify_nonce() in the data of the response. The nonce is the same as what I give back, yet the result is false and hence I get the “Cookie nonce is invalid” error. This is strange to me since i’m using the wp_create_nonce( ‘wp_rest’ ) seemingly correctly.

Any insight would be greatly appreciated.

**Comment by rmccue** [comment]
Hi! We're no longer tracking issues here on GitHub, so please file support requests [on the WordPress forums](https://wordpress.org/support/).

Given the ES6 syntax here, it's possible you're using the `fetch()` API. If so, you may need to set `{ credentials: true }` when sending this request; i.e. your nonce may be correct, but you might not actually have any cookies set.

**Comment by quazZzar** [comment]
Hello,
is there a solution for this?
Found the issue on the WP Forum, no answers at all.
Please help.

**Comment by samdotme** [comment]
For those stumbling on this thread in the future, @rmccue 's suggestion was spot on for me.

If you are using the `fetch()` api, you need to add a property `credentials: 'include'`.

That would give you a request that looks something like this:
```js
fetch(`/your/target/wp/endpoint`, {
  method: 'GET',
  headers: {
    'Content-Type': 'application/json',
    'X-WP-Nonce': wpApiSettings.nonce
  },
  credentials: 'include'
}
```
