### ISSUE TITLE
Filters dont work after the last update

### ISSUE THREAD

**Issue by microdesign** [WP-API/WP-API#2980]
I have a custom posts type and custom taxonomies for them.

And my app which get these posts use links like this:

https://URL/wp-json/wp/v2/article?filter[culture]=united-kingdom&per_page=100&order=desc&orderby=title

but now I think filter just get ignored and API return just latest posts.

Is there any solution for this?
Or maybe I must back to the old working version.

**Comment by BE-Webdesign** [comment]
Hi @microdesign,

Thank you for using the WP REST API.  The `filter` param was removed from the REST API in WordPress 4.7, mostly for maintainability concerns. There are two options:

1. When registering your cultures taxonomy, add these two other values:
```php
'show_in_rest' => true,
'rest_base' => 'cultures',
```
With the taxonomy registered to the REST API, you can now do the query: `wp/v2/article?cultures=(id_of_uk_term)&per_page=100&order=desc&orderby=title`.

2. Install the [`filter` param plugin](https://github.com/WP-API/rest-filter). This will add back the filter param.

Hopefully that helps.

**Comment by microdesign** [comment]
Thank you very much - the legacy plugin help me lot because there was hundreds of ajax requests which use this filter param.

**Comment by adamsilverstein** [comment]
Closing as resolved.
