### ISSUE TITLE
Since merge to Wordpress 4.7 Comment anonymous by api is disabled

### ISSUE THREAD

**Issue by fahmi182** [WP-API/WP-API#2981]
Hi all, i want to ask?

how to enable anonymous comment by default in functions theme? like this?
`add_filter('rest_allow_anonymous_comments',false);`

https://core.trac.wordpress.org/ticket/38855

Many thanks.

**Comment by nylen** [comment]
Close - `false` is the default value for this filter.  Instead, you want to add a function that returns `true`, and WP defines such a function:  [`__return_true`](https://github.com/WordPress/wordpress-develop/blob/4.7.0/src/wp-includes/functions.php#L4775)

So here is the code snippet to enable anonymous comments:

```php
add_filter( 'rest_allow_anonymous_comments', '__return_true' );
```

@WP-API/amigos #closeme

**Comment by fahmi182** [comment]
Thank you very much my friend! 💃
