### ISSUE TITLE
Plugin does not support php 7

### ISSUE THREAD

**Issue by h-ARTS** [WP-API/WP-API#2982]
Hi everyone,

I have found out an Issue regarding this WP-REST v2 plugin. My WordPress version is 4.7 with PHP 7.1 and I use to display the datas from PHP 5.6 through AngularJS. Now the Problem is since I changed the PHP version to 7.1 the datas doesn't display anymore and the route url to json wp-json/wp/v2/posts shows this in multiple lines like:

> Notice: Trying to get property of non-object in /home/myyplace/public_html/myy.website/dlrz/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php on line 2070

or

> Warning: Cannot modify header information - headers already sent by (output started at /home/myyplace/public_html/myy.website/dlrz/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php:1737) in /home/myyplace/public_html/myy.website/dlrz/wp-includes/rest-api/class-wp-rest-server.php on line 1244

Thank you for your attention and a quick solution.

**Comment by rmccue** [comment]
Hi! We're no longer handling bug reports here on GitHub, so please file those at [core Trac](https://core.trac.wordpress.org/).

In this specific case, `get_post_type_object( $this->post_type )` is returning `null`. Assuming `$this->post_type` is correctly set to `'post'`, then it's likely another plugin doing something weird with post type registration.
