### ISSUE TITLE
Status overwrite by default when get post

### ISSUE THREAD

**Issue by gnanasekaranl** [WP-API/WP-API#2983]
when hit get post request status ($data['status']) overwrite by default. For below request

Definition
GET /wp/v2/posts/<id>
Example Request

$ curl http://demo.wp-api.org/wp-json/wp/v2/posts/<id>

**Comment by rmccue** [comment]
I'm not sure exactly what you mean, but we're also no longer tracking issues on GitHub. If this is a support issue, please ask [on the WordPress forums](https://wordpress.org/support/); if it's a bug, please file on [core Trac](https://core.trac.wordpress.org/).
