### ISSUE TITLE
Cannot get register_meta() to work with Custom Post Types

### ISSUE THREAD

**Issue by arturgithub** [WP-API/WP-API#2987]
Hi there,

It seems that register_meta() does not work with Custom Post Types. With "not working" I mean that this function is not exposing the meta the same it does when setting it to "post".

**register_meta( 'post', 'wpcf-informazioni', $args )**: Outputs the meta properly within {meta:{}} schema

**register_meta( 'my-cpt', 'wpcf-informazioni', $args )**: Does not output the wpcf-informazioni nor the meta schema. The rest of the output when hitting the endpoint is correct.

So is this a bug or I am missing something that I should be doing to get the same behavior of register_meta with my cpt?

Is **register_rest_field** the only alternative right now?

Thanks for everything!!!

**Comment by felixarntz** [comment]
Hi @arturgithub,

you are indeed right that `register_meta()` currently does not work with custom post types - more precisely it does not work with post types at all. The first parameter is not supposed to be a post type, but the general object type, which by core definitions accepts one of either 'post', 'term', 'user'  or 'comment'.

If you need to register metadata associated with a specific post type, you can't currently use this function, and `register_rest_field()` is probably the only way to do so. I also wish it supported this, but at this point it does not.

There is a WordPress Core Trac ticket to add support for separate post types (and also taxonomies and any kind of subtype) to `register_meta()`, however there is yet to be any discussion on it: https://core.trac.wordpress.org/ticket/38323

This issue can likely be closed as invalid for now, unless we want to keep it open to remind ourselves of the shortcomings of `register_meta()` and that it needs some work.

**Comment by arturgithub** [comment]
Thank you @felixarntz for your answer!

It is not big deal at all for the time being to use register_rest_field() instead.

**Comment by tharsheblows** [comment]
I think this works. `register_meta()` takes the object type eg `post` rather than the subtype eg `my-cpt`. Also when you register your custom post type, you need to explicitly allow meta by including `'supports' => array('custom-fields')`. I've commented on the trac ticket too.

**Comment by arturgithub** [comment]
Thanks @tharsheblows too, it does work :)
