### ISSUE TITLE
Custom Endpoint Not Getting Noticed

### ISSUE THREAD

**Issue by jacksonkr** [WP-API/WP-API#2988]
I copied the `rest-api/lib/endpoints/class-wp-rest-controller.php` and gutted it to make a simple class called `class-wp-rest-ratl-controller.php` which I put in the same folder (`rest-api/lib/endpoints/`)

However, I cannot reach this endpoint on my site. I've tried the following URLs:

- `http://thesite.net/wp-json/ratl`
- `http://thesite.net/wp-json/ratl/`
- `http://thesite.net/wp-json/ratl/test`
- `http://thesite.net/wp-json/ratl/test/`

```
<?php

class WP_REST_ratl_Controller extends WP_REST_Controller {

	protected $post_type;

	public function __construct( $post_type ) {
		// $this->post_type = $post_type;
		$this->namespace = 'ratl';
		// $obj = get_post_type_object( $post_type );
		// $this->rest_base = ! empty( $obj->rest_base ) ? $obj->rest_base : $obj->name;

		$this->meta = new WP_REST_Post_Meta_Fields( $this->post_type );
	}

	/**
	 * Register the routes for the objects of the controller.
	 */
	public function register_routes() {

		// register_rest_route( $this->namespace, '/' . $this->rest_base, array(
		register_rest_route( $this->namespace, '/test', array(
			array(
				'methods'		=> 'GET',
				'callback'		=> 'test',
				// 'permission_callback' => array( $this, 'get_items_permissions_check' ),
				// 'args'			=> $this->get_collection_params()
			),
			'schema' => array( $this, 'get_public_item_schema' )
		));
	}

	public function test() {
		return "tested";
	}
}

?>
```

**Comment by modemlooper** [comment]
how are you loading this class?

**Comment by jacksonkr** [comment]
@modemlooper I put it in the endpoints folder. I found no documentation on how to get the file picked up so I was hoping that the plugin would load all files in the endpoints directory.

**Comment by modemlooper** [comment]
well you shouldn't add anything to core files or folders. You should create your own plugin and load the class with hook 'rest_api_init'

**Comment by rachelbaker** [comment]
@jacksonkr The plugin doesn't autoload any file from the `/lib/endpoints` directory.  In the `plugin.php` file you can see how we include files and register the routes.  

Include statement: https://github.com/WP-API/WP-API/blob/develop/plugin.php#L25

Hook into `rest_api_init` to register our routes: https://github.com/WP-API/WP-API/blob/develop/plugin.php#L143

and...register the routes: https://github.com/WP-API/WP-API/blob/develop/plugin.php#L322

Closing this issue as it is more of a general WordPress development question and not specific to the WP REST API.
