### ISSUE TITLE
'rest_user_invalid_id' when embedding author info in posts

### ISSUE THREAD

**Issue by mikylucky** [WP-API/WP-API#2989]
Hi,
updating to the new version I cannot retrieve anymore the author data from embedding

The endpoint is 'wp-json/wp/v2/posts?_embed' and the embedded part of the author returns this:

    "_embedded":{
        "author":[{
            "code":"rest_user_invalid_id",
            "message":"ID utente non valido.",
            "data":{"status":404}
        }]
    }

Am I missing something or it's a bug?

**Comment by rmccue** [comment]
Hi! This can occur when your author isn't publicly visible (i.e. hasn't published a public post). Check that you have permission to access the author user.

**Comment by mikylucky** [comment]
The author has already published previous posts.
What do you mean with "check the permission"? In the backend or in the request?
The request is a public request, without any auth

**Comment by mikylucky** [comment]
I found the problem. The security plugin Wordfence was automatically blocking the 'user' endpoint to prevent unwantend datascraping
