### ISSUE TITLE
Trouble after updating to WP 4.7

### ISSUE THREAD

**Issue by francoismassart** [WP-API/WP-API#2990]
Hello,
I've been using the wp api v2 with advanced filtering options like custom taxonomy filtering...

Here is an example of the called URL:
`/wp-json/wp/v2/videowall?filter[activity_taxonomy]=animation,showreel`

It works like a charm but since I installed WordPress 4.7 it doesnt apply the filtering. (I get all the results instead of the filtered results)
It is due to the fact that Wordpress 4.7 provides a native REST API which is used instead of WP API v2.
It seems that the native REST API does not allow such filtering...

So it is not a bug from the WP API v2 but a side effect caused by the presence of the native REST API of 4.7.

My question is: 
is it possible to tell WordPress to use the REST API v2 while the advanced filtering is not supported ?

Thank you for your help!

**Comment by jhalvorson** [comment]
Hi @francoismassart, there is a plugin that can be used that adds the filter functionality back in: https://github.com/WP-API/rest-filter.

**Comment by francoismassart** [comment]
Good to know 👍 
Thank you for you help @jhalvorson
