### ISSUE TITLE
Cannot retrieve private post with rest api?

### ISSUE THREAD

**Issue by amtbnagios** [WP-API/WP-API#2991]
Hi!
I installed wordpress 4.7 & Application Passwords plugin( has added a Application Passwords for a admin user)

I can create or update or retrieve posts with rest api (in wordpress 4.7 core) 

But if I change a post's status to private, I can't retrieve the post with Application Passwords

Is this rest api limit or Application Passwords limit?
Could some body know & help me ,Thanks a lot!

**Comment by rmccue** [comment]
This appears to be a problem with Application Passwords, ask them rather than here. :)
