### ISSUE TITLE
Retrieve all posts within a category by category slug

### ISSUE THREAD

**Issue by CNSam** [WP-API/WP-API#2992]
Hi all,

Just wondering what the recommended way to retrieve all posts from a category just with the category slug.

I've seen the old method of using filters but I can't seem to get this method to work in V2, would I be correct in saying that the filters were removed?

Any help would be greatly appreciated.

**Comment by kadamwhite** [comment]
You are correct that filters were removed, but a more robust solution (even though it does require two steps) is to query first for the category you want on `/categories` with a `?slug=` query parameter, and then use the ID of that category with `?categories=` on the `/posts` collection. You can see an explanation of the mechanism in the comments on #2949, I hope this helps!
