### ISSUE TITLE
Can't add featured media to custom post type

### ISSUE THREAD

**Issue by dleeward** [WP-API/WP-API#2994]
I don't have any issues with adding a featured media to a "posts" post type using /posts/<id>.

When I try to add a featured media to a custom post type it fails.

When I use /posts/<id> and get this response:
```
{
  "code": "rest_post_invalid_id",
  "message": "Post id is invalid.",
  "data": {
    "status": 404
  }
}
```
When I use /custom_post_type_name/<id>, I just get a response returning information on the post as if I had sent a GET.

I'm using WP 4.6.1 with the 2.0-beta15 plugin.

**Comment by dleeward** [comment]
Just figured out my theme didn't register support for featured images for the custom post type. Fixed it using this: http://wordpress.stackexchange.com/questions/51897/how-come-featured-image-isnt-showing-up-in-my-custom-post-type

**Comment by rmccue** [comment]
Great to hear you fixed this. :) In the future, please file support requests on [WordPress.org](https://wordpress.org/support/) instead, as we're no longer handling support or issues here.
