### ISSUE TITLE
Create users

### ISSUE THREAD

**Issue by kamov** [WP-API/WP-API#2995]
I am trying to create a user via postman, but I get status 400.
I guess also if exist a PHP wrapper class which allow to work with WP Api.
Thanks

![screen shot 2017-01-05 at 17 25 34](https://cloud.githubusercontent.com/assets/2345000/21689044/570c9f18-d36f-11e6-9982-5fb88b17379e.png)

**Comment by nylen** [comment]
The REST API has been merged into WordPress core! Development and support are no longer taking place in this repository.

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

For bugs and patches, please post the issue or patch to WordPress core Trac at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

Thank you,
The REST API team
