### ISSUE TITLE
Embed category information [eg slug, name] without a 2nd call

### ISSUE THREAD

**Issue by davecarlson** [WP-API/WP-API#3000]
I want to be able have this information inline when querying /posts, rather than it be in the wp:term key, or having to get the id, then make another API call (i'm display 20 posts on a page, that could be expensive). As my response is being passed through to normalizr, the wp:term object syntax does not allow me to split out the information correctly.

**Comment by nylen** [comment]
The REST API has been merged into WordPress core! Development and support are no longer taking place in this repository.

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

For bugs and patches, please post the issue or patch to WordPress core Trac at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

Thank you,
The REST API team


:tada: Congrats on issue number 3000!
