### ISSUE TITLE
Can't get posts filtered on author

### ISSUE THREAD

**Issue by stefdelec** [WP-API/WP-API#3001]
I am trying to get all the post from one author
/wp-json/wp/v2/posts?author=admin

`"code":"rest_invalid_param"`

**Comment by nylen** [comment]
The REST API has been merged into WordPress core! Development and support are no longer taking place in this repository.

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

For bugs and patches, please post the issue or patch to WordPress core Trac at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

Thank you,
The REST API team

**Comment by kadamwhite** [comment]
Also, ?author= works by ID, not nice name -- so if the admin user is ID #2, you'd want `?author=2`

**Comment by stefdelec** [comment]
Thanks.

But It is hardly understandable how it works. There is no example:
http://mysite/wp-json/wp/v2/pages?parent=1
Should this request work ? Guessing so. But how to know parent page id? I created a parent and a child page, but I have no idea what is the id...

**Comment by stefdelec** [comment]
Yes, it does thanks. Do you know why custom fields are not displayed in json result of a page?

**Comment by Kenshino** [comment]
@stefdelec : 

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".
