### ISSUE TITLE
I use  Basic Authentication but return 401 Unauthorized  

### ISSUE THREAD

**Issue by tunxiaoqing** [WP-API/WP-API#3002]
wordpress version:4.7
WP REST API version:2.0-beta15
WP BASIC Auth version :1.1.3
I have installed WP REST API and WP BASIC Auth.I visited api http://101.96.131.178/wordpress/wp-json/wp/v2/users/me but it returned 
{
"code": "rest_not_logged_in",
"message": "You are not currently logged in.",
"data": {
"status": 401
}
}
I have add "Authorization:Basic cmVkYWN0ZWQ6cmVkYWN0ZWQ=" in the headers 
my plugins as follow:
![image](https://cloud.githubusercontent.com/assets/16894961/21881282/91c22122-d8de-11e6-98cc-4844c2e07216.png)
my http message  as follow:
![image](https://cloud.githubusercontent.com/assets/16894961/21881346/cddbfbce-d8de-11e6-8eb7-6cc48bdc1547.png)
Anything missing?
Look forward to your reply soon~
Thanks

**Comment by nylen** [comment]
The REST API has been merged into WordPress core! Development and support are no longer taking place in this repository.

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

For bugs and patches, please post the issue or patch to WordPress core Trac at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

Thank you,
The REST API team

**Comment by nem95** [comment]
i have the same issue after updating woocommerce, if you had resolve the probleme i accept your help

**Comment by tunxiaoqing** [comment]
@nem95 I have solved the problem.There is something wrong with the Basic Authentication handler plugin.Delete it and install by GIT——git clone https://github.com/WP-API/Basic-Auth.git.It can be used properly.I hope this will help you~

**Comment by nem95** [comment]
Thank you, i resolved it to like this thkx
