### ISSUE TITLE
Basic Authentication with rest api 

### ISSUE THREAD

**Issue by nem95** [WP-API/WP-API#3003]
Hello Everyone,

I'm actually creating a mobile app with ionic framework and i have to get information from Wordpress, so i use the rest api and try to login an user using basic auth but its returning me an error 401 unauthorized, 
```json
{
  "code": "rest_not_logged_in",
  "message": "Vous n'êtes pas actuellement connecté.",
"_comment": "#AKA you'r not currently logged in", 
  "data": {
    "status": 401
  }
}
```
i try with cURL and i got the same error. 

I think its because one member of the team had updated wordpress and woocommerce so if someone have any idea.

I also tried to log user with Oauth but i dont want to get the wpadmin login page I prefer use a custom login page. 

Thank you and sorry for the bad english

**Comment by nylen** [comment]
The REST API has been merged into WordPress core! Development and support are no longer taking place in this repository.

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

For bugs and patches, please post the issue or patch to WordPress core Trac at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

Thank you,
The REST API team

**Comment by nem95** [comment]
i dont have any account on this
