### ISSUE TITLE
How to use rest api with angularjs

### ISSUE THREAD

**Issue by benayah** [WP-API/WP-API#3004]
I can not figure out how to use the wp rest api plugin with angularjs please help thank you

**Comment by nylen** [comment]
The REST API has been merged into WordPress core! Development and support are no longer taking place in this repository.

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

For bugs and patches, please post the issue or patch to WordPress core Trac at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

Thank you,
The REST API team

**Comment by benayah** [comment]
oK tHANK YOU

**Comment by benayah** [comment]
i have posted my question https://wordpress.org/support/topic/how-to-use-angular-jsionic-with-wp-rest-api/
