### ISSUE TITLE
Add fields in Json Response of Posts

### ISSUE THREAD

**Issue by jhonnynho** [WP-API/WP-API#3006]
Hi.

I want to add a custom field in a response of posts, but when I add new fields after a while it is deleted from the file what I do.

The file that I modify its class-wp-rest-posts-controller.php and I add the new field in prepare_item_for_response function

Any idea why this happens?

**Comment by nylen** [comment]
The REST API has been merged into WordPress core! Development and support are no longer taking place in this repository.

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

For bugs and patches, please post the issue or patch to WordPress core Trac at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

Thank you,
The REST API team
