### ISSUE TITLE
Impossible to get posts statuses with /wp-json/wp/v2/posts

### ISSUE THREAD

**Issue by WaldenStew** [WP-API/WP-API#3007]
Hi, i’d like to get all posts by api by /wp-json/wp/v2/posts and, it works. But into the response i don’t have the status :

[0] => Array
(
[id] => 114
[date] => 2017-02-24T18:24:00
[date_gmt] => 2017-02-24T17:24:00
[guid] => Array
(
[rendered] => http://mywebsite/?p=114
)

[modified] => 2017-02-16T10:30:27
[modified_gmt] => 2017-02-16T09:30:27
[slug] => new
[type] => post
[link] => http://mywebsite/?p=114
[title] => Array
(
[rendered] => new
)

[content] => Array
(
[rendered] =>
[protected] =>
)

[excerpt] => Array
(
[rendered] =>
[protected] =>
)

[author] => 1
[featured_media] => 0
[comment_status] => open
[ping_status] => open
[sticky] =>
[template] =>
[format] => standard
[meta] => Array
(
)

[categories] => Array
(
[0] => 17
)

[tags] => Array
(
)

[_links] => Array

Is it a bug or i do something wrong?

Thanks for your help !!!

Steeve

**Comment by nylen** [comment]
The REST API has been merged into WordPress core! Development and support are no longer taking place in this repository.

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

For bugs and patches, please post the issue or patch to WordPress core Trac at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

Thank you,
The REST API team
