### ISSUE TITLE
i want deep linking in my app. how to do it?

### ISSUE THREAD

**Issue by Prabhat36** [WP-API/WP-API#3008]
i want that the content of my post/page/customPost link to pages within the app, Deep linking? is this is  implemented?
for localhost api provoids links like  http://localhost:8080/#/public/pages/430 
i want to know for devices how the above link looks like?

**Comment by nylen** [comment]
The REST API has been merged into WordPress core! Development and support are no longer taking place in this repository.

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

For bugs and patches, please post the issue or patch to WordPress core Trac at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

Thank you,
The REST API team
