### ISSUE TITLE
how to get the terms belong to custom taxonomy?

### ISSUE THREAD

**Issue by wesleyxiao** [WP-API/WP-API#3009]
Hello, i am new to v2, i use v1 for long time, currently upgrade to v2, i try to get all the terms belong to specific custom taxonomy.

In v1 i can do this to get terms
/taxonomies/location_category/terms

but in v2 i try
/taxonomies/terms  
it return json error "code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status"
:404}}

if just /taxonomies/location_category/ it didn't show anything terms belong to taxonomy.

i search the question on google for few hours didn't show any result, anyone can help please, thank you

**Comment by nylen** [comment]
The REST API has been merged into WordPress core! Development and support are no longer taking place in this repository.

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

For bugs and patches, please post the issue or patch to WordPress core Trac at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

Thank you,
The REST API team
