### ISSUE TITLE
Multisite filter error

### ISSUE THREAD

**Issue by alvacode** [WP-API/WP-API#3011]
Hi, the query http://site.com/sub-site/wp-json/wp/v2/posts?filter[name]=post-name don't work.

I have a multisite wordpress, if i query this http://site.com/sub-site/wp-json/wp/v2/posts, run ok but with filter not run.

¿What is the problem?

Thanks?

**Comment by nylen** [comment]
The REST API has been merged into WordPress core! Development and support are no longer taking place in this repository.

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

For bugs and patches, please post the issue or patch to WordPress core Trac at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

Thank you,
The REST API team

**Comment by kadamwhite** [comment]
@webdoin try http://site.com/sub-site/wp-json/wp/v2/posts?slug=post-name, and check out the new documentation site at developer.wordpress.org/rest-api
