### ISSUE TITLE
Output rendering problem

### ISSUE THREAD

**Issue by lddd** [WP-API/WP-API#3018]
Hi there,

i have the following problem. A Post title for e.g "This is my post title - online now". The " - " hyphen, is not rendered probably. 

The Json looks like:
{"ID":56714,"title":"This is my post title &#8211 online now". 

The output to my app:
This is my post title &#8211 online now. 

Thanks in advance for your kind help.

**Comment by nylen** [comment]
The REST API has been merged into WordPress core! Development and support are no longer taking place in this repository.

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

For bugs and patches, please post the issue or patch to WordPress core Trac at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

Thank you,
The REST API team
