### ISSUE TITLE
Allow for expanding of all objects (parent, post type, post status, and author) through context

### ISSUE THREAD

**Issue by tlovett1** [WP-API/WP-API#302]
In Skype I suggested we include object representations of post types and post statii like we do with author and parent. This lead to a more expanded idea of representing all these things as objects by default but allowing them to be minimized through a context switch. Slated or 2.0 since this would break back compat.

**Comment by danielbachhuber** [comment]
In `develop` you can pass `_embed` to get the embedded resources.
