### ISSUE TITLE
register_rest_field update_callback not work

### ISSUE THREAD

**Issue by raphaelnikson** [WP-API/WP-API#3020]
I'm trying to update a custom field, but when I run the route through POSTMAN it does not update the field. Creates a new record. The route is something like:
wp/v2/posts/362/meta?key=servicos_status&value=pause

![captura de tela 2017-05-25 as 23 53 07](https://cloud.githubusercontent.com/assets/260620/26478833/677cf8d0-41a5-11e7-8807-97d5aa555a84.png)

Someone help me?

**Comment by nylen** [comment]
The REST API has been merged into WordPress core! Development and support are no longer taking place in this repository.

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

For bugs and patches, please post the issue or patch to WordPress core Trac at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

Thank you,
The REST API team
