### ISSUE TITLE
Unable to post users

### ISSUE THREAD

**Issue by firedeepan** [WP-API/WP-API#3021]
I am trying to post users and I am using the JWT Authentication for WP REST API for authentication. The code I am using works perfectly on localhost. But not working in my GoDaddy. I even tried in another shared host, but getting the same issue. 

The detailed code can be found here: [https://stackoverflow.com/questions/44646889/wordpress-rest-api-create-users-not-working](https://stackoverflow.com/questions/44646889/wordpress-rest-api-create-users-not-working)

Is there any configuration to enable when I don't run on localhost?

Even the .htaccess files are identical in localhost and the one I have hosted in the internet

**Comment by nylen** [comment]
The REST API has been merged into WordPress core! Development and support are no longer taking place in this repository.

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

For bugs and patches, please post the issue or patch to WordPress core Trac at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

Thank you,
The REST API team
