### ISSUE TITLE
Get URL/File of an embedded video 

### ISSUE THREAD

**Issue by vincent-etienne** [WP-API/WP-API#3023]
I got an embedded video and I would like to get the URL or the file video.

For exemple : 
In the field Video Embedded Code I got : 
<div itemscope itemtype="http://schema.org/VideoObject"><meta itemprop="uploadDate" content="2017-07-16T15:41:53+0200" /><meta itemprop="name" content="SOME CONTENT FOR TITLE" /><meta itemprop="contentUrl" content="https://serverurl/video.mp4" /><script src="//content.jwplatform.com/players/XXXXXXXXXXXXXXX.js"></script></div>

I would like to get https://serverurl/video.mp4  or //content.jwplatform.com/players/XXXXXXXXXXXXXXX.js
with the API Rest of Wordpress.

I search on Google but I didnt find an answer, that's why i'm posting here.

For your information, this is to develop a Mobile application.

Thanks for your answers.

**Comment by nylen** [comment]
The REST API has been merged into WordPress core! Development and support are no longer taking place in this repository.

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

For bugs and patches, please post the issue or patch to WordPress core Trac at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

Thank you,
The REST API team
