### ISSUE TITLE
Custom fields and query in url

### ISSUE THREAD

**Issue by federicolucca** [WP-API/WP-API#3025]
Hi

I use the Rest API v2 with custom type and custom field, I need to filter on the GET requests a custom post type by its custom post fields.

What it is the right way to do?

Thanks
Federico

**Comment by nylen** [comment]
The REST API has been merged into WordPress core! Development and support are no longer taking place in this repository.

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

For bugs and patches, please post the issue or patch to WordPress core Trac at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

Thank you,
The REST API team
