### ISSUE TITLE
pass utf-8 characters to url

### ISSUE THREAD

**Issue by milad145** [WP-API/WP-API#3026]
hi,
i have this code 

`register_rest_route('v3', '/publicationscats/(?P<slug>[a-z0-9 .\-]+)', array('methods' => 'GET', 'callback' => 'findPublicationsByTaxonomy'));`

and i want to pass `utf-8` characters to my url like this 

> localhost/publicationscats/لوح‌-فشرده/

but i get error 

> "data":{"status":404}

how can i handle that?

**Comment by nylen** [comment]
The REST API has been merged into WordPress core! Development and support are no longer taking place in this repository.

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

For bugs and patches, please post the issue or patch to WordPress core Trac at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

Thank you,
The REST API team
