### ISSUE TITLE
call wordpress rest api using multiple tags

### ISSUE THREAD

**Issue by bramhechatejas** [WP-API/WP-API#3027]
Hello,

I was trying to fetch posts by using calling wordpress rest api. Here, I have requirement of making a call based upon multiple tags that are available to me. The response could either be in AND / OR format. I tried following call which somehow didn't work. Will anyone here please let me know, if I'm doing something wrong? or is it only this plugin which do not support this type of call? Shall appreciate help & responses.

http://10.43.13.214/wp-json/wp/v2/posts?filter[tags]=drones,career

Thanks

**Comment by nylen** [comment]
The REST API has been merged into WordPress core! Development and support are no longer taking place in this repository.

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

For bugs and patches, please post the issue or patch to WordPress core Trac at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

Thank you,
The REST API team
