### ISSUE TITLE
want to display all parent category with first level child

### ISSUE THREAD

**Issue by sujit15** [WP-API/WP-API#3031]
Hey guys,
I want to display all parent category with first level child in rest api. If I click on http://demo.wp-api.org/wp-json/wp/v2/categories
It should diplay like this:
[
{
"id": 3,
"name": "Cricket",
"slug": "cricket",
"parent": 0

         {     "id": 10,
               "name": "Doubles",
               "slug": "doubles",
                "parent": 3
          },
{
    "id": 2,
    "name": "Football",
    "slug": "football",
    "parent": 0
},
]

Can anyone please help me... i want the exact code...

thanks

**Comment by nylen** [comment]
The REST API has been merged into WordPress core! Development and support are no longer taking place in this repository.

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

For bugs and patches, please post the issue or patch to WordPress core Trac at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

Thank you,
The REST API team
