### ISSUE TITLE
unable to get url parameters

### ISSUE THREAD

**Issue by milad145** [WP-API/WP-API#3032]
hi,
i had this code 

```
function testFunction($data) {
    $data["params"] = str_replace("\\", "", $data["params"]);
    $q = json_decode($data["params"], TRUE);

    return   $q;
}

add_action('rest_api_init', function () {
    register_rest_route('v3', '/page/test', array('methods' => 'GET', 'callback' => 'testFunction'));

});

```
and when i request to 
`http://example.com/wp-json/v3/page/home?params={"year":"1396","month":"8","day":"17","page":"4"}`

I get this answer

```
{
  "year": "1396",
  "month": "8",
  "day": "17",
  "page": "4"
}

```

but after I change my site protocol to ssl, I get `null` for url parameters
my request url is : 
`https://example.com/wp-json/v3/page/home?params={"year":"1396","month":"8","day":"17","page":"4"}`

**Comment by nylen** [comment]
The REST API has been merged into WordPress core! Development and support are no longer taking place in this repository.

Please post support requests to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api".

For bugs and patches, please post the issue or patch to WordPress core Trac at https://core.trac.wordpress.org -- Be sure to include full details and reproduction steps about the issue you are experiencing.

If you are unfamiliar with Trac, you can refer to the "Opening a Ticket" user guide at https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/ for an introduction!

Thank you,
The REST API team
