### ISSUE TITLE
Post Creation with Category and/or Taxonomies

### ISSUE THREAD

**Issue by royboy789** [WP-API/WP-API#311]
I have looked through the docs and issues, and this has been brought up in ways before, but looking at the code there are not POST endpoints for /taxonomies.
https://github.com/WP-API/WP-API/blob/master/lib/class-wp-json-taxonomies.php

I'm not looking to create taxonomies, but when creating a post assign it to a taxonomy or the category taxonomy without doing any separate functionality. I know its built into wp_insert_post, and looks like it was part of the the posts endpoint (in the comments), but not seeing any further code inserting taxonomies or tags.

Am I just being blind again?

**Comment by danielbachhuber** [comment]
Follow #561 for how we'll eventually implement batch requests.
