### ISSUE TITLE
Featured image with new post.

### ISSUE THREAD

**Issue by aryanduntley** [WP-API/WP-API#322]
Currently, a featured image cannot be created with a new post.  In order for a featured image to be set, the media has to be created.  Then the post has to be created.  Then the post has to be updated 

`public function attach_thumbnail( $post, $data, $update ) {if ( ! $update ) {return;} ... `

This, in my opinion, is inefficient and requires a remote device to make three requests to the server instead of just on or two.  The - is $update - conditional should be removed?

On this same note, in order for a remote device to update meta data, the device has to call the post/post-type meta get request, then parse the available meta to obtain meta ID's and then send that data back in the form of an automatically indexed array.  

One, the meta ID is not readily available in wordpress.  So, a devloper cannot readily provide the device developer with appropriate meta key values to use for creation/updating.  I understand that accessing the meta via get request allows for all use cases, but using the id as the determining get/set value is obscure as far as typical wordpress goes.  

Two, because the array is expected to be automatically indexed, each index consisting of an associative array with keys ID, Key, and Value, if a developer needs to hook into the create/edit post to deal with meta in a specific way (such as arrays, objects or serialized data), they then have to loop through all meta and "look" for a key (or an ID, but no one will be looking for meta id, they will be using keys) manually.  This is time consuming.

The array, in my opinion, should look more like
 `$data['post_meta'] = array("key1"=>"val1", "key2" => "val2", ...) `
instead of 
`$data['post_meta'] = array(
     array("ID"=>"id1","Key"=>"key1", "Value"=>"val1), 
     array("ID"=>"id2","Key"=>"key2", "Value"=>"val2), 
);`

It makes it easier to deal with just the value you want to deal with, instead of having to loop through the entire stack (or even up to found point with break).  At the very least structuring it like this would be preferable:
`$data['post_meta'] = array(
     "ID1"=array("Key"=>"key1", "Value"=>"val1), 
    "ID2"=array("Key"=>"key2", "Value"=>"val2), 
);`

**Comment by danielbachhuber** [comment]
You can follow #561 for how we'll eventually solve batch operations.
