### ISSUE TITLE
Plugins & Theme endpoints

### ISSUE THREAD

**Issue by philipjohn** [WP-API/WP-API#323]
Is the desire to, at some point, add routes and endpoints for plugins and themes? I.e for checking currently installed plugins/themes, installing and updating?

I'm thinking about a use for this and have the following routes and endpoints in mind...

Route: /plugins

* GET: List of installed plugins, basically the output of get_plugins()

Route: /plugins/[plugin-name]

* GET: Retrieve plugin metadata
* POST: Install/activate plugin
* PUT: Update plugin
* DELETE: Delete installed plugin

Route: /themes

* GET: List of installed themes

Route: /themes/[theme-name]

* GET: Retrieve theme metadata
* POST: Install/activate theme
* PUT: Update theme
* DELETE: Delete installed theme

What do you think?

**Comment by danielbachhuber** [comment]
@WP-API/amigos For managing activation, I think we should have a `status` attribute on Plugins and Themes. This will give us `active` and `active-network`

**Comment by danielbachhuber** [comment]
Theme management is now WIP as a separate plugin https://github.com/WP-API/wp-api-plugins-themes-endpoints
