### ISSUE TITLE
/posts endpoint ignores context=edit parameter

### ISSUE THREAD

**Issue by jaredsinclair** [WP-API/WP-API#330]
Assuming:

- a custom post type of `my_custom_type`
- several custom fields like `a_custom_field` and `b_custom_field`

The following endpoint doesn't include the custom fields in the meta data:

```
/posts?type=my_custom_type&context=edit
```

Unless I'm misunderstanding the docs, the `/posts` endpoint should include custom meta data. The custom fields meta data **is** included when I try the following:

```
/posts/19?context=edit
```

**Comment by danielbachhuber** [comment]
WP-API v1.x is no longer maintained, except for critical bug fixes.
