### ISSUE TITLE
Endpoint / inclusion for User meta

### ISSUE THREAD

**Issue by aryanduntley** [WP-API/WP-API#331]
Many plugins and devs add extra user meta to user profiles.  This information needs to be accessed and I believe should be doable without having to extend or hook.  Are there plans for this already or have I missed something? Would you like me to put a first draft of what that might look like (although I believe it should follow the same format as post meta, whatever that ends up looking like in the end).

**Comment by scottopolis** [comment]
Here's how I add user meta to the current user endpoint https://gist.github.com/scottopolis/52d00e2095d1e959d2ef

**Comment by danielbachhuber** [comment]
Here's how we recommend extending endpoints going forward http://v2.wp-api.org/extending/modifying/
