### ISSUE TITLE
Allow filter or document filter in Media in order to give opportunity to manipulate file data

### ISSUE THREAD

**Issue by aryanduntley** [WP-API/WP-API#332]
You are using wp_handle_sideload and using that returned data to place the file and associated data into wp_insert_attachment.  There are no hooks here that allow a dev to access the file and perform actions based on the data.  My specific use case is that I have created a user profile image ui and I disallow the user from uploading an image that is bigger than a certain size or larger than certain dimensions.  In a remote application, if I want to use the rest api to make sure that user images have been properly sent, I cannot access the file before it is inserted into the uploads folder within the API itself.  

There is a hook in handle sidebar that allows me to access this data though:  

`$return = apply_filters( 'wp_handle_upload', array( 'file' => $new_file, 'url' => $url, 'type' => $type ), 'sideload' );`

Now, I can call that filter, access and use the data and then either pass through the array as is or add an error association to it which will stop the processing and deliver the message to the calling application.

If no filter is going to be included in the new media functions, then I believe this filter should be in the api documentation to better inform users of the access to file data via media that they have.

**Comment by danielbachhuber** [comment]
We'll handle as a part of #1167
