### ISSUE TITLE
Better solution for wp meta enpoints

### ISSUE THREAD

**Issue by aryanduntley** [WP-API/WP-API#338]
Currently, post meta is accessed via an array of ambiguous arrays each containing the keys id, key and value.

I believe the current solution has been made overly complex and can be simplified significantly.  

There are four main requests for meta just as there are those for posts; get, post, put, delete.  The problem of distinguishing between those using post parameters is unnecessary.  Each has it's own endpoint method.  There is no need in complicating it.

Now, the issue of distinguishing what type of meta value the user is attempting to place is not so difficult either.  Yes, the data can be an array, a single value, or a single value associated with a key that has multiple values.  Working with the specific meta id is one way of doing it, yes, but it is an obscure way of doing it because the WP api does not, as a general rule, work with the meta id's directly.

Getting meta should be gathered through the method associated with the get request.
Format would be output of the call request params. UR params would be (for single key with posts/{ID}/meta/{KEY}/
&single=true :: this may be unnecessary because data will be returned as serialzed string 
  anyway
&custom=true :: get_post_custom_values($key, $post_id);

Creating the meta would be a call to posts/{ID}/meta and would accept the data params
unique=true
single=true :: where single false is a text value and single true is data that is to be treated  
  as an array, if object for any reason, cast into array, then placed into add_post_meta.  
  Array will be serialized automatically.  There may be complexities with the variety of
  forms data will be received, but the data is placed into the value fields as a serialized
  string, so then parsing the data to json should not be too problematic.
key = "blah blah"
value = "blah blah" or json {blah blah}

Putting (or updating) the meta would be a call to posts/{id}/meta/{KEY} and would accept the data paras
value = "blah blah" or json {blah blah}
previous_value =  "blah blah" or json {blah blah}

Using update_post_meta.

Despite the fact that there may be a key out there somewhere that has more than one entry with identical values, update_post_meta by default says this:
 
"This function will update only the first field that matches the criteria."

So, going out of the way to update only specific id values is beyond what the majority of devs will do locally, notwithstanding the REST API.  If they want a key with multiple values, the majority of devs will not use the same key, but rather use an array.  The only benefit to using the same key with multiple values would be for searching by meta anyway. I believe that typically, the majority of devs find other ways of dealing with this.  

Despite that, however, the logic in the above is that if you have one key with multiple duplicate values, you only need to update one and it does not matter what its ID is in the database.  The same key will still hold the various values, the id's are pretty irrelevant in this case and are not needed in the API.

Deleting the meta would be a call to posts/{id}/meta/{KEY} and would accept the data and url params could be:
&previous_value = "blah blah" or json {blah blah}

Deletion would be the only problem I find in using standard WP methods.  This is because some serialized data may be very long.  However, this can simply fall on the shoulders of the dev who, when creating meta, should not have serialized data in keys that are not unique.  If this is practiced (and it is a good practice), then the delete request can be passed empty, which will omit the third parameter of delete_post_meta causing the key, in it's entirety to be removed.

This is how I would suggest dealing with meta.  It follows all the rules of REST, all the standard API usages of WP, and makes life easier for all involved when dealing with meta.

**Comment by danielbachhuber** [comment]
See http://make.wp-api.org/2014/05/12/handling-post-meta/ for background on the current implementation and why it's not likely to change. If we do change, it will be something like this #875
