### ISSUE TITLE
Unprefix everything

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#34]
When we merge in to core, we need to unprefix everything. In case you were wondering why everything was prefixed with `json_`/`WP_JSON_`, this is why.

In reality, we're not so much unprefixing as we are switching prefixes. I'd like to use `api_`/`WP_API_` for the prefix, since the API is more generic than just JSON, but this depends on what the core team thinks.

**Comment by danielbachhuber** [comment]
Related #876

**Comment by danielbachhuber** [comment]
This was addressed in #1151
