### ISSUE TITLE
Error when creating a new CPT post and not supplying "type" param

### ISSUE THREAD

**Issue by tlovett1** [WP-API/WP-API#341]
Here is the error:
Fatal error:  Call to undefined method WP_Error::set_status() in /json-rest-api/lib/class-wp-json-posts.php on line 309

The post is getting created but as a post rather than the CPT, then getting the new CPT post is causing issues. I think this should throw an error earlier not creating the post or it should just know what post type I am referring to.

**Comment by danielbachhuber** [comment]
> I think this should throw an error earlier not creating the post

This will be handled in #871
