### ISSUE TITLE
Endpoint for filtering posts by taxonomy

### ISSUE THREAD

**Issue by scottbaggett** [WP-API/WP-API#343]
First off, thank you so much for the hard work on this API. I've got a fairly simple question. Im looking to filter by taxonomy 'categories' and term 'summer'. I can't seem to find any documentation for this type of request. I checked to make sure that taxonomy and term are public query vars, so they should be available to the API call, but this doesn't return an

*I've tried variations of this:*

/wp-json/posts/?type=product&filter[taxonomy]=categories&filter[term]=4

Hoping that this is possible currently, but if not I'd love some guidance on best way to implement this.

Here's the JSON output for that term. 
https://gist.github.com/scottbaggett/9393edcaac5a261a50b6

My apologies if I should have posted this somewhere else. Thanks again!

**Comment by danielbachhuber** [comment]
This issue doesn't appear to need any further discussion.
