### ISSUE TITLE
Documentation about pagination is incorrect

### ISSUE THREAD

**Issue by pdewouters** [WP-API/WP-API#352]
> If there are more than 10, pagination will kick in and you'll have to handle this in your client.

Instead, the number of posts returned seems to depend on the "Blog pages show at most" setting under Settings > Reading

**Comment by clarenced** [comment]
Any updates about this? I still have the problem in my website. 
I am using a theme, where the default number of posts returned is always 1 when requesting 
`?filter[posts_per_page]=10`. I have to change the setting reading to have a different number of posts. 
Is this bug fixed?

**Comment by kadamwhite** [comment]
The latest version of the API uses `per_page=n` instead of `filter[posts_per_page]=n`; this isn't, to my eyes, represented in the docs yet. Leaving the note here for anyone else who comes along to this issue

**Comment by danielbachhuber** [comment]
WP-API v1.x is no longer maintained, except for critical bug fixes.
