### ISSUE TITLE
Cannot filter category terms

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/WP-API#361]
When integrating with an external system it is more convenient to refer to categories by slug than by ID, as IDs don't have meaning outside wordpress and slugs can logically be used across applications. With this in mind, I would expect to be able to filter terms collections in a manner similar to the way I can filter a collection of posts:

    /wp-json/taxonomies/category/terms?filter[slug]=category-slug

This doesn't seem to work, however. The workaround of fetching all categories and filtering down to the term I want is feasible in my use case, but the more terms in the DB te worse that workaround will become. What would need to be done to add this kind of filtering to taxonomy term collections?

**Comment by danielbachhuber** [comment]
This will be handled with a combination of #924 and #1167
