### ISSUE TITLE
Filterability everywhere possible (this instance, Taxonomy Class)

### ISSUE THREAD

**Issue by aryanduntley** [WP-API/WP-API#368]
One of the reasons that worpdress is so powerful is because of it's hooks.  I strongly believe the API should adopt this extensibility wherever possible.  I've already submitted a few specific requests for filters in areas that bulldoze the code along a certain path, disallowing data manipulation except by way of roundabout hacks.  

https://github.com/WP-API/WP-API/issues/337
https://github.com/WP-API/WP-API/issues/332
https://github.com/WP-API/WP-API/issues/324

As I begin working with a certain post type I created whereby I need to provide a list of terms for a certain taxonomy, I find that I am again forced to just deal with the way get_taxonomy_terms gets the terms with get_terms.  I am unable to pass custom args, I am unable to manipulate the data after terms are retrieved and/or after prepare_taxonomy_term prepares the individual terms in the loop.  There should be a filter before and after the prepare loop, as well as a way of passing arguments to get_terms.  There is a filter within the individual term output (inside of the prepare method), however, manipulation should be allowed for the entire result set as well.

Why this is needed should be evident.  Data will always need to be dealt with in a variety of ways.  Especially when dealing with mobile devices and their need to stay as small as possible and keep local data manipulation to a minimum.  If possible, data should be provided to them ready to use. 

 A specific example for the taxonomy object would be sorting.  If I wanted to sort the result set by some custom order meta, I would need access to it.  Beyond specific examples, again, I strongly believe that filters and hooks should be available throughout the code wherever possible to allow extensibility.  It makes less work for the developer (so we don't have to extend classes and create our own endpoints), and provides them/us with complete control over what we decide to give the requester and how we deal with data retrieved. 

Everytime a result is prepared for output or entry (as is reasonable), there should be hooks both before and after to allow full manipulation of the data.  Wordpress does this and that is why it is so versatile.  Doing so with the API (it is already being done, but as show above, there are many places where this is missing) would only be mirroring the coding practices of the foundation it's being built for.

This issue also discussed in https://github.com/WP-API/WP-API/issues/361

**Comment by NameLess--** [comment]
So, anything new here? I really need filtering for categories. Any idea?

**Comment by danielbachhuber** [comment]
We'll handle this as a part of #1167
