### ISSUE TITLE
JSONP and headers

### ISSUE THREAD

**Issue by miguelpeixe** [WP-API/WP-API#382]
JSONP request doesn't read headers. Which means, no pagination data. How about adding pagination into the json body?

I know it's bold to change the data response structure, but return array of data directly is also a bad idea. Who knows what you (or the common webz) would want to add in the future without affecting clients.

**Comment by wuntusk** [comment]
Has there been any movement on this? Adding the _api_meta would be huge to allow for a jsonp implementation ... especially if you want to do a fallback from cors...  such as http://blog.algolia.com/jsonp-still-mandatory/

**Comment by danielbachhuber** [comment]
Related #1136 .

I suspect we'll be moving the pagination headers into the response body, but no guarantees.
