### ISSUE TITLE
Add `roles` param for `GET /wp/v2/users`

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/WP-API#386]
I can get all users for a single role fairly easily, via the filter query parameter:
```
/wp-json/users?filter[role]=contributor
```
However, `filter[role]` doesn't seem to support the comma syntax that I can use in other commands:
```
// Doesn't work:
/wp-json/users?filter[role]=contributor,author
// I'd have expected it to work like this:
/wp-json/posts?filter[author]=17,4,164

```
Is there any way through the API to query for users of multiple roles? At present I'm having to do this by chaining batches of queries, and even with promises that request syntax is nasty. I'd much prefer to get them as a single collection.

Related #924

**Comment by danielbachhuber** [comment]
This landed in WP 4.4, and so v2.x can support it.

**Comment by danielbachhuber** [comment]
We'll support `role[]=foo&role[]bar`, and default to the behavior of `WP_User_Query`

**Comment by danielbachhuber** [comment]
While we can do multiple roles with the `role[]` syntax, we need to decide a syntax for `role__not_in`. Bumping to Beta11 for now.

**Comment by danielbachhuber** [comment]
Because the attribute is now `roles`, the query param should be `roles`

**Comment by BE-Webdesign** [comment]
I'll have a PR for this in a bit.

**Comment by BE-Webdesign** [comment]
Should querying by roles only be doable by an authenticated request?  Are there use cases you want to get a pool of users for a non admin user? I imagine there is a lot of management delegation going on on certain sites so is blanket use of filtering by role acceptable?

**Comment by danielbachhuber** [comment]
> Should querying by roles only be doable by an authenticated request?

Correct. If the `roles` param is present on the request but the request is unauthorized, we should return an error.

> Are there use cases you want to get a pool of users for a non admin user?

I'm not sure I follow. Unauthorized users shouldn't be able to list users based on role, because they aren't permitted to see the role of the user.

**Comment by BE-Webdesign** [comment]
Apologies for terrible grammar.  Disregard that comment as it is pretty meaningless. I was referring to how sometimes people add user management capabilities to non admin users on an install.  The PR will be checking for proper capabilities and throw if unauthorized.
