### ISSUE TITLE
Is there a way to query by post date range?

### ISSUE THREAD

**Issue by israelidanny** [WP-API/WP-API#389]
I'm trying to get all the posts between date X and Y, but can't seem to find a good solution.

@danny-Weebo

**Comment by danielbachhuber** [comment]
Related #924

**Comment by maximebj** [comment]
Hi everyone ! If someone need the URL version of the trick, you have to write it like this : 

` /wp-json/posts?filter[date_query][before]=2015-05-05T12:38:36 `

**Comment by tskharva** [comment]
@maximebj thanks for the URL it worked perfectly.

Is there a way to filter on modified date so that I can update posts that I need to?

**Comment by maximebj** [comment]
Try to add 
`&filter[date_query][column]= post_modified_gmt  `

according to date_query in [WP Query in Codex](https://codex.wordpress.org/Class_Reference/WP_Query)

**Comment by maximebj** [comment]
Everyone : It should be explained in the official doc. 

Here is the problem I had in first place : in a mobile app (imagine 9gag like app) user load first 10 posts. then he waits a lot of time. Later, he scroll down and fires a new load. But meanwhile a new post has been published : the offset is not good anymore and the last post appears again (post n°10 is now n°11).

So to avoid this, I get the first post post_date, and make a date_query to say : load posts, page 2, but only post older than the first post initially loaded. 

In a real time mobile world. This will make a lot of sense. And the WP Api need to show it can complete it easily. What do you think guys ?

**Comment by Kunal1985** [comment]
I am using just a normal AjaxUrl call to fetch blogs using WP-API. I use the date-query options as explained above but noneof it works for me.
Is there any specific version of WP-API to use so that the below queries would work ?
/wp-json/posts?filter[date_query][before]=2015-05-05T12:38:36 and
&filter[date_query][column]= post_modified_gmt

**Comment by maximebj** [comment]
Did you add the code from rnlmedia above in functions.php in order to authorize the date query to be used

**Comment by Kunal1985** [comment]
NO, i am unaware of this. can u send me a link probably what to add and where
Again I am just using the WP-API plugin in wordpress.

**Comment by maximebj** [comment]
The date query and some other params are not allowed by default in the API (for security reasons) so you have to add this in your functions.php : 
```
function add_additional_meta_json_query_vars($filters){
   array_push($filters, 'date_query');
   return $filters;
}
add_filter('json_query_vars', 'add_additional_meta_json_query_vars');
```
it will allow date_query to be called.
You can do the same with :'meta_key', 'meta_value', 'meta_compare', 'meta_query'...

**Comment by Kunal1985** [comment]
Thanks a lot in advance, let me try and check

**Comment by Kunal1985** [comment]
Resolved, i had to add just one line under the below section 
Editing json-rest-api/lib/class-wp-json-posts.php after line number 131

array_push($valid_vars, 'date_query');
Thanks again :)

**Comment by maximebj** [comment]
You should never change directly the plugin code. Hooks are made for this. ;)

**Comment by focusedonfit** [comment]
What are the security concerns with adding this query param?

**Comment by phamdacloc** [comment]
I have the same question as focusedonfit. Can someone explain the security risk of adding date_query? Am I expecting a full can of worms by enabling date_query, meta_query, meta-key, meta-value, meta-compare? If that's the case, then date_query is not the solution for before/after filtering.

**Comment by phamdacloc** [comment]
I've added these 5 lines to the bottom of my theme's functions.php file

function add_additional_meta_json_query_vars($filters){
   array_push($filters, 'date_query');
   return $filters;
}
add_filter('json_query_vars', 'add_additional_meta_json_query_vars');

BUT the before/after filter still doesn't work. What could be the problem?
http://localhost:8888/wp-json/wp/v2/posts?filter[before]=2008-08-08T22:20:17
http://localhost:8888/wp-json/wp/v2/posts?filter[after]=2008-08-08T22:20:17

**Comment by kihaki** [comment]
This is still not working for me, something is missing. Trying to get this data:

wp-json/wp/v2/posts?filter[date_query][before]=2015-05-05T12:38:36

I have added these lines to my themes functions.php:

function add_additional_meta_json_query_vars($filters){
   array_push($filters, 'date_query');
   return $filters;
}
add_filter('json_query_vars', 'add_additional_meta_json_query_vars');

**Comment by phamdacloc** [comment]
Add these to your functions.php

```php
function my_rest_query_vars( $valid_vars ) {

	$valid_vars = array_merge( $valid_vars, array( 'date_query' ) );
	return $valid_vars;
}
add_filter( 'rest_query_vars', 'my_rest_query_vars' );
```

**Comment by kihaki** [comment]
It works now, thanks a lot phamdacloc! You're the man!

**Comment by jasonhjohnson** [comment]
Hi All,

I'm having a pretty similiar problem. I've got an ACF (Advanced Custom Fields) field called "event_start_date" that I'm trying to filter my posts query on. I'd like to get all the posts where the event_start_date is BEFORE a certain date, but, it doesn't seem to be working. I tried the following:

```javascript
/**
* Add custom query values for rest queries and filters.
*/
add_filter( 'rest_query_vars', 'my_rest_query_vars' );
function my_rest_query_vars( $valid_vars ) {
    $valid_vars = array_merge( $valid_vars, array('countries', 'states', 'event_start_date' ) );
    return $valid_vars;
}
```
and then...

```javascript
var url = self.apiEndpointUrl + '/posts?status=publish' +
          '&per_page=' + perPage +
		  '&page=' + (page > 0 ? page : 0) +
	      '&filter[event_start_date][before]=01/01/2015' +
		  '&filter[orderby]=event_start_date' + 
		  '&filter[order]=ASC';
```

Any help is really appreciated!

Thanks,
Jason

**Comment by phamdacloc** [comment]
Try replacing `&filter[event_start_date][before]`  with `&filter[date_query][before]`

**Comment by jasonhjohnson** [comment]
@phamdacloc But my field name isn't "date_query." I want to filter on my custom field "event_start_date."

**Comment by maximebj** [comment]
You need to make a meta_query I think. Take a look in the ACF doc : http://www.advancedcustomfields.com/resources/query-posts-custom-fields/ (at section 4.)
it's the right way to do this, now you have to write this as parameters (something like &filter[meta_query][key]= event_start_date&filter[meta_query][compare]='<=' 

the issue here is than you can put < and = in the url so maybe you need to encode it, and I don't know how to set another key compare value (for the end date) 

it's not well explained in the doc

**Comment by arikogan** [comment]
Hi guys,
I've run into this myself and found it a little bit cumbersome to add that piece of code to the functions.php of my theme. Also, if the theme changes or gets upgraded, you can loose the functionality. This is why I wrote a very small plugin that does this for you. Simply install the plugin and start using date_query filtering. Any feedback and suggestion will be highly appreciated.

[https://wordpress.org/plugins/date-query-enabler/](https://wordpress.org/plugins/date-query-enabler/)

**Comment by Shobby** [comment]
API does not return all the order or specific order using HTTPS request its return empty array.
https://www.onetwocosmetics.com/wc-api/v3/orders/?consumer_key=comsumer_key&consumer_secret=comsumer_secrete

{"orders":[]}

any when i tried to get specific order details its generate permission issue as:

https://www.onetwocosmetics.com/wc-api/v3/orders/9853?consumer_key=comsumer_key&consumer_secret=comsumer_secrete

{"errors":[{"code":"woocommerce_api_user_cannot_read_order","message":"You do not have permission to read this order"}]}

**Comment by rmccue** [comment]
@Shobby This repository is for the WordPress REST API, **not** for the WooCommerce REST API. Please contact WooCommerce support instead. :)

**Comment by orengbasha** [comment]
10 posts only displaying afterloading same 10 posts can be showing
can you please help me
