### ISSUE TITLE
Let WP_Error implement WP_JSON_ResponseInterface

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#39]
[As discussed](http://irclogs.wordpress.org/chanlog.php?channel=wordpress-dev&day=2013-12-02&sort=asc#m741581), we might want to always return a ResponseInterface rather than allowing WP_Error be a special case here.

Let's consider after #33 is merged.

**Comment by danielbachhuber** [comment]
@rmccue I don't think this is still applicable?

**Comment by rmccue** [comment]
I think our `is_error` and `as_error` methods on the response object handle this pretty well now. Someday down the line, it'd be nice for `is_wp_error` to recognise `( $e instanceof WP_REST_Response ) && $e->is_error`, but no need to keep this in the meantime I think.

**Comment by danielbachhuber** [comment]
I agree.
