### ISSUE TITLE
Ensure meta links are always an object

### ISSUE THREAD

**Issue by mikejhale** [WP-API/WP-API#408]
Meta Links are being returned as a JSON object:

```
{
    "meta": {
        "links": {
            "self": "http://localhost:8880/guitarsweepstakes/wp-json/users/1",
            "archives": "http://localhost:8880/guitarsweepstakes/wp-json/users/1/posts"
        }
    }
}
```

However, if there are no links, it is being returned as an Empty Array:

```
"meta": {
        "links": []
    }
```

Meta Links should be returned as an array of key/value (name/link) pairs:

```
"meta": {
        "links": [
            {"self": "http://localhost:8880/guitarsweepstakes/wp-json/users/1"},
            {"archives": "http://localhost:8880/guitarsweepstakes/wp-json/users/1/posts"}
        ]
    }
```

This causes an issue when deserializing because it is either an object, or an array, depending on the results. 

Alternatively, it could return null instead of an empty array when no links are returned.

**Comment by iandunn** [comment]
The same thing happens with terms; if there are none assigned then the `terms` item on a `post` object is an empty array, but if there are then it's an object.

e.g., compare https://maine.wordcamp.org/2015/wp-json/posts/614 to https://winnipeg.wordcamp.org/2015/wp-json/posts/496

It looks like [`add_term_data()` always returns an array](https://github.com/WP-API/WP-API/blob/61495b2b7a5ea002503999083b617723756b612a/lib/class-wp-json-taxonomies.php#L311), though, so maybe there's something running later on that is converting it (and links, and possibly other things) to an object?

I don't see anything at first glance, though.

**Comment by iandunn** [comment]
Oh, actually, that's just how `json_encode()` behaves. 

Huh. I'm sure there's a reason for that, but I dunno what it is.

**Comment by danielbachhuber** [comment]
WP-API v1.x is no longer maintained, except for critical bug fixes.
