### ISSUE TITLE
Trying to get 'photos' custom post type. Returns 'post' post type instead when...

### ISSUE THREAD

**Issue by gablabelle** [WP-API/WP-API#412]
Hello,

I was trying to access my custom post type 'photos' (all of them) but when I was trying to use the http://www.domain.com/wp-json/posts?type=photos url it returned the normal 'post' post type instead.

In Wordpress' Settings > Reading Settings > Blog pages show at most	: __999__ posts

When I change this settings to __96__ posts instead of 999 posts it works and I am able to retrieve the custom post type 'photos' (96 of the them).

Please note that __96 and under works__ in my case and 97 and above will return the normal posts instead of the photos.

Many thanks for your time and help.

**Comment by danielbachhuber** [comment]
In `develop`, your custom post type will be registered as `/wp/photos` (and derivative endpoints)
