### ISSUE TITLE
Accessing data preparation methods from outside plugin context

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/WP-API#418]
This issue describes a goal I had around filtering API-delivered data, and the most intuitive (to me) solution to that goal, in order to stimulate discussion on a potential architecture change.

The filter `json_prepare_post` is called for objects of all post types, and permits filtering of that data. In my case, I have a CPT defining groups of authors, and a Pods-driven relationship field in which the author group post object can be linked to a group of authors. I needed to embed the author objects into the group object's response JSON, in order to get the data for an author category page with the minimal number of requests. I wanted to embed these authors using the same format in which they are embedded in a post.

`WP_JSON_Users::add_post_author_data` gave me an obvious internal method to call in order to get a prepared author object; however, the WP_JSON_Users instance used by the plugin is not accessible outside of the `json_api_default_filters` method in which all of the filter methods are bound between classes.

In order to access the method, even though it is just a pass-through that augments the provided arguments, this is what I did within my json_prepare_posts filter:

```php
	// This is a global created by the plugin: we need a server
	// in order to instantiate the users class
	global $wp_json_server;
	$sog_json_users = new WP_JSON_Users( $wp_json_server );

	$group_members = array();
	foreach( $group_response['group_members'] as $user_id ) {
		// Stand on top of the JSON API's internal functionality to get a user
		// object in the same format as the embedded author data
		$data = $sog_json_users->add_post_author_data(
			array(),
			array( 'post_author' => $user_id ),
			''
		);
		array_push( $group_members, $data['author'] );
	}
```
Looking aside from things like the inefficiency of creating a class every time -- in reality it was a singleton elsewhere in the plugin, I moved it in here for purposes of demonstration -- and whether this is the right function to call -- I used this instead of `prepare_user` because it did the user request for me -- this shows my naive but instinctual attempt to use the *existing* author-preparation method to augment my own objects.

Questions from this, taking it as a given that doing things like embedding authors in a consistent manner is a desirable piece of functionality for any plugin developer:

1. Should these preparatory methods be statically accessible, so that they can be called directly rather than forcing instantiation of internal classes?
2. Is there anything we can do to better expose the filters used to pass data between API classes, so that plugin developers can make use of them in their own plugins?

I also think we should assume that many people will find it satisfactory for their purposes to query for `/posts?type=blah` vs making their own endpoint, so I don't think I'll be the first person to come across this question.

**Comment by danielbachhuber** [comment]
Related #875

**Comment by danielbachhuber** [comment]
@kadamwhite I appreciate the long writeup on this issue. Can you take a look at `develop` when you have a moment to see if your concerns have been addressed? If they haven't, can you offer a suggestion?
