### ISSUE TITLE
Private taxonomy data shouldn't be exposed without appropriate capabilities

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#419]
Co-Authors Plus uses a private `author` taxonomy to manage byline relationships to posts. Each term has the `display_name`, `user_login`, and `user_email` stored in the term `description` so autocomplete can search against it.

The best thing is probably not to expose private taxonomy terms without the appropriate capability.

**Comment by joehoyle** [comment]
Even though the core implementation is buggy here - we should still change our current implementation to only show public taxonomies IMO.

**Comment by rmccue** [comment]
> Even though the core implementation is buggy here - we should still change our current implementation to only show public taxonomies IMO.

More just never implemented than buggy, but we should assume 21949 will get in; :+1: on public only.

**Comment by danielbachhuber** [comment]
Private taxonomies aren't registered by default, but can be exposed in the REST API with the `show_in_rest` parameter.
