### ISSUE TITLE
Advanced Custom fields not returned

### ISSUE THREAD

**Issue by Zeneixe** [WP-API/WP-API#433]
Why aren't Custom Fields serialized in the JSON? 

I see someone implemented this one year ago:
https://github.com/jbuchbinder/wp-api/commit/c30a975951b85d990d6bee2d933f3fb98a9b2aad

**Comment by vieillecam** [comment]
Thanks a lot @PanManAms ! Your plugin works perfectly for me !

**Comment by charleslouis** [comment]
Hey there !

What about this. It works with ACF, Repeater and Flexible content.

 ````
function json_api_prepare_post( $post_response, $post, $context ) {
  if( get_fields($post['ID']) ){
    $post_response['acf'] = get_fields($post['ID']);
    return $post_response;
  }
}
add_filter( 'json_prepare_post', 'json_api_prepare_post', 10, 3 );
````

It a kind of combination of @modemlooper and http://stackoverflow.com/questions/10132685/json-api-to-show-advanced-custom-fields-wordpress

**Comment by circlecube** [comment]
@charleslouis - this worked great for me, thanks!

**Comment by charleslouis** [comment]
You're welcome @circlecube ! I'm glad it helped you.
Alternatively, we could do the following :
````
function json_api_prepare_post( $post_response, $post, $context ) {
  if( get_fields($post['ID']) ){
    $acf_fields = get_fields($post['ID']);
    foreach ($acf_fields as $key => $value) {
        $post_response[$key] = $value;
    }
    return $post_response;
  }
}
add_filter( 'json_prepare_post', 'json_api_prepare_post', 10, 3 );
````
This would result in having ``post.my_advanced_custom_field`` instead of ``post.acf.my_advanced_custom_field``, each acf being now a property of object post, and not of post.acf. This makes more sense to me.

**Comment by rileypaulsen** [comment]
@charleslouis that is a potentially dangerous way of doing it, because it assumes that a user-created ACF field key couldn't overlap with and potentially overwrite a WP default object property (like post_status, post_date, post_title, etc.). Now obviously, most people wouldn't do that, but there's nothing stopping you from creating postmeta keys like that, so you never know.

**Comment by charleslouis** [comment]
Thanks @rileypaulsen to spot this, you're absolutely right. 
What about having a namespace such as acf_my_custom_field instead of acf.my_custom_field ? This would keep the ACF as a property of the post, while removing the overlapping risk.
What do you think ?

**Comment by circlecube** [comment]
Cool, I'm happy having it scoped to the acf property of the post object. I like that it keeps top of mind that it's a custom field and not part of core. But I can see instances where it may be nice to have at the post level, not sure it's worth the risk as you say of having an ACF field named date or type or parent though. Thanks again!

**Comment by rileypaulsen** [comment]
@circlecube the only argument I would have for keeping all the ACF fields nested under a property (as another object) is that that way you could safely iterate over all of the ACF meta for a post. For example, let's say you have employee bio information stored in ACF fields, you could write one loop to output it all (assuming you don't care about the order). But otherwise, I agree that prefixing the fields if you've got them out on the main object is a necessity.

**Comment by Komsomol** [comment]
Thanks for the plugin and support here I got ACFs to show up in my JSON response.

However it looks like nested repeater fields do not show up with this method. Does any one know how I would get nested repeater fields to show up?

**Comment by charleslouis** [comment]
Hi @Komsomol ,

I face the same issue few weeks ago. Here are my functions.php content regarding ACF.

The way I deal with repeater is not recursive and only one level deap.
With small adjustement I bet we could adapt it to flexible fields as well.

````
<?php 

// DEAL WITH RELATED POSTS OBJECTS
function enrich_related_post_with_own_acf( $related_post_ID, $original_related_post ){
  
  // Check if get_fields() exists and if there are ACFs in this post
  if ( get_fields($related_post_ID) ) {
      
    // Get the related post own ACFs
    $related_post_acf_fields = get_fields($related_post_ID);

    foreach ($related_post_acf_fields as $key => $value) {      
      // Prefix with ACF to avoid conflict with core wordpress
      $key = 'acf_' . $key;
      $related_post_acf_part[$key] = $value;
    }

    //then merge the core fields ($value)
    // and the ACFs ($related_post_acf_fields) into this post object
    $tmp_value = (object) array_merge((array) $original_related_post, (array) $related_post_acf_part);
    $original_related_post = $tmp_value;

  }

  // This is the original_related_post enriched with its own ACFs
  return $original_related_post;
}






// Inject Advance Custom Fields into the API
function json_api_prepare_post( $post_response, $post, $context ) {
  
  // Check if get_fields() exists and if there are ACFs in this post
  if( get_fields($post['ID'] ) ){

    // if so get ACFs
    $acf_fields = get_fields($post['ID']);


    foreach ($acf_fields as $key => $value) {

      // Prefix with ACF to avoid conflict with core wordpress
      $key = 'acf_' . $key;

      // As ACF related Post Object are return without their own ACFs, we need to recursively find for them

      ////////////////////////////////////////
      // SINGLE POST OBJECT
      ////////////////////////////////////////      
      if( null != $value->ID ){
        // there are godd chances we are returning a single post object
        // so let's get this posts own ACFs
        
        // temporary store $value
        $related_post = $value;
        
        $related_post_ID = $value->ID;
        $related_post = enrich_related_post_with_own_acf( $related_post_ID, $related_post );
        
        //put it back, once enriched
        $value = $related_post;
      }
      ////////////////////////////////////////
      // END of SINGLE POST OBJECT
      ////////////////////////////////////////      




      ////////////////////////////////////////
      // REPEATER of POST OBJECTS
      // Works with a Post Object returned format
      //
      // 
      //  
      // TO_DO : 
      // Make it work with a Post ID returned format
      ////////////////////////////////////////
      if( is_array($value) ){
        if ( null != $value[0]['post'] ) {        
          // there are godd chances we are returning a post object repeater
          // so let's get each posts own ACFs
          
          // temporary store $value
          $post_repeater = $value;

          // loop in the repeater
          foreach ($post_repeater as $post_key => $post_value) {
            
            // Get the post and it's ID
            $repeated_post = $post_repeater[$post_key]['post'];
            $repeated_post_ID = $repeated_post->ID;

            // Get repeated post own ACFs
            $repeated_post = enrich_related_post_with_own_acf( $repeated_post_ID, $repeated_post );
            $post_repeater[$post_key]['post'] = $repeated_post;
          }

          //put it back, once enriched
          $value = $post_repeater;
        }

      }


      ////////////////////////////////////////
      // END OF REPEATER of POST OBJECTS
      ////////////////////////////////////////

      $post_response[$key] = $value;

    }
    return $post_response;
  }
}
add_filter( 'json_prepare_post', 'json_api_prepare_post', 10, 3 );
````

**Comment by Komsomol** [comment]
@charleslouis  Thank you so much for providing this. I will implement and see!

**Comment by charleslouis** [comment]
With pleasure @Komsomol !
Glad if it helps. Let me know.

**Comment by Komsomol** [comment]
@charleslouis Oh man this is great. I like how the properties are now returned as their own acf_ prefixes instead instead the meta property.

However it looks like its not showing my nested repeater fields... Looks like my ACF dev has made a repeater field... that has another repeater field (for albums... then the track listing. But an album can have multiple CDs and thus tracks)

If you can give me some pointers to make it recursive? My speciality is in JS and not PHP :/

**Comment by charleslouis** [comment]
@Komsomol I'm happy it was helpful :)
As I've said, for now I didn't worked on a recursive version.

It is a bit dangerous, because an ACF can related to an ACF which relates back to it ... and so forth...
Don't make it recursive. 
But the principle would be the same in Php as in Js : a loop in a loop in a loop.

* just create a dedicated loop for each albums (repeater post object)
* then in each album custom post type, or each album repeater, loop in the CDs repeater
* then in each CD, loop in the songs repeater

Here is what I did for an office page that regroup every offices.
Every office as, for instance, `acf_social_links` repeater

* If you consider an office is  like an album, you'd have to loop over your album repeater to do the same for each album
* then, in each album, if the repeater is `acf_cd_repeater`, loop over the fields
* then, if the field key is `acf_songs_repeater`, loop over to get songs infos

````
      ////////////////////////////////////////
      // OFFICES : get le list of offices posts enriched with their own ACFs(gmap, adress)
      ////////////////////////////////////////
      if( $key === 'acf_offices_page' ){
        // if so get main offices page ACF
        $offices_acf = get_fields($value);
        $offices_acf = $offices_acf['offices_ordner'];
        
          // loop in the repeater
          foreach ($offices_acf as $post_key => $value) {
            
            // Get the post and it's ID
            $repeated_post = $offices_acf[$post_key]['post'];
            $repeated_post_ID = $repeated_post->ID;

            // Get repeated post own ACFs
            $repeated_post = enrich_related_post_with_own_acf( $repeated_post_ID, $repeated_post );
            $offices_acf[$post_key]['post'] = $repeated_post;
          }

          //put it back, once enriched
          $value = $offices_acf;
      }
      ////////////////////////////////////////
      // END OF OFFICES
      ////////////////////////////////////////

````

**Comment by matthewrobb** [comment]
@charleslouis I am trying to use your snippet outright but I am getting an error of this sort:
```php
Cannot use object of type WP_Post as array in
```
in reference to this portion of code:
```php
      if( is_array($value) ){
        if ( null != (array) $value[0]['post'] ) {
          // there are godd chances we are returning a post object repeater
          // so let's get each posts own ACFs

          // temporary store $value
          $post_repeater = $value;

          // loop in the repeater
          foreach ($post_repeater as $post_key => $post_value) {

            // Get the post and it's ID
            $repeated_post = $post_repeater[$post_key]['post'];
            $repeated_post_ID = $repeated_post->ID;

            // Get repeated post own ACFs
            $repeated_post = enrich_related_post_with_own_acf( $repeated_post_ID, $repeated_post );
            $post_repeater[$post_key]['post'] = $repeated_post;
          }

          //put it back, once enriched
          $value = $post_repeater;
        }

      }
```

**Comment by matthewrobb** [comment]
@charleslouis I actually figured it out right after posting, if you have the relationship locked to a single post then it will not be an array and instead it will be that one post object.

**Comment by charleslouis** [comment]
Good spot !

Maybe we can test for it doing something like :

if ( null != (array) $value[1]['post'] )

Else if ( null != (array) $value[0]['post'] )

So that both cases are covered.

**Comment by chrishutchinson** [comment]
Just to chime in I've also been supporting a ACF to WP-API plugin which works with the ACF options plugin too: http://www.github.com/times/acf-to-wp-api

**Comment by martinsookael** [comment]
The plug-in seams real nice! 

I was in the process of choosing between this and 
https://wordpress.org/plugins/json-api/

And WP-API wins in every track (better documentation, active github page etc), except custom fields implementation, which is the kicker for this project, so I'll be sticking with json-api this time. 

But pretty please - 
I shall return with a plan to write a wordpress plugin for https://github.com/jayJs/jay to enable a Wordpress Single Page App workflow. 

The current plan is to combine it with Meta Box and this relies on custom fields. 
At least in our case we use WP for the backend (including all the content creation) and that means that all we really need are GET requests.

So I'm subscribing to this in the hopes the issue gets solved soon :).

**Comment by benbabics** [comment]
@charleslouis @matthewrobb  I'm having difficulty with this. Could either of you explain what your fields look like to get the recursive acf properties to display?

I have a post that is has a Field Name of  "Related Products", Field Type of Post Object, and a Post Type of a custom post type I created called Products. I have it set as Allowed To Select Multiple Products. ![image](http://awesomescreenshot.com/0414qffhbe).

When I hit the API for this particular post, I see the property `acf_related_products`, but it seems to me that I would also see the acf properties for the acf fields I've setup on those custom post types; hence you mentioning recursion. 

Am I missing something? Any help is much appreciated. :)

**Comment by benbabics** [comment]
I ended up resolving it with:
```
// REPEATER of POST OBJECTS
if( is_array($value) ){

  if ( $value[0]->ID ) {
    foreach ($value as $post_key => $post) {
      $value[$post_key] = enrich_related_post_with_own_acf( $post->ID, $post );
    }
  }

  else if ( null != $value[0]['post'] ) {
```

**Comment by charleslouis** [comment]
Glad you resolved it @benbabics

**Comment by snstarosciak** [comment]
@chrishutchinson Hey I'm just now stumbling on this thread and I actually have added this plugin which does work, for the most part: https://wordpress.org/plugins/acf-to-wp-api/

The problem is that I have a custom taxonomy that's setup like an archive post, but it still has a bunch of ACF fields associated with it. When I view the posts in my browser, I get a "acf: false" key mapping for the custom post type, but for regular standard Wordpress posts, the ACF fields show up in the json api object. Does anyone have any clue why this would be happening? Am I missing something?
