### ISSUE TITLE
Specify which fields to return in JSON

### ISSUE THREAD

**Issue by careyestes** [WP-API/WP-API#446]
I dont think this is an issue with WP-API specifically, but I wanted to see if there was a possible alternative or solution.

If I query:

wp-json/posts?filter[posts_per_page]=-1&type[]=page&filter[order]=ASC&filter[orderby]=parent%20title

on my production box, it returns a 503 error. However, if I reduce the post limit

wp-json/posts?filter[posts_per_page]=80&type[]=page&filter[order]=ASC&filter[orderby]=parent%20title 

it works properly. I am using wpengine who claim they DO throttle queries, but this query locally is only about 1.2mB, so I am not sure why that would call for them to tank the query and push it to 503 Error.

I am combining Typeahead and WP-API in order to build a fast search autocomplete, so I need to return all pages. 

I am fairly certain, this is an issue with the host and not the API script, I just wanted to see if there was another option for returning the json object.

**Comment by lapidus** [comment]
@joanllenas or @danielbachhuber, could you provide a brief example of narrowing post results to title? Thanks.

**Comment by klihelp** [comment]
Some filters/functions to modify post response, modify to your needs
cc @lapidus 

```

/**
 * Posts per page
 */
function kli_wp_api_query_post_per_page( $query ){
    if ( defined( 'JSON_REQUEST' ) && TRUE == JSON_REQUEST ){
            $query->set( 'posts_per_page', -1);
    }
}
add_action( 'pre_get_posts', 'kli_wp_api_query_post_per_page' );



/**
 * Modify Post Response - Remove Attachments
 * @param  object $data   
 * @return object
 */
function kli_wp_api_json_prepare_post( $data ){
    /**
     * Remove featured_image field from response
     *
     */
    remove_filter( 'json_prepare_post', array( $wp_json_media, 'add_thumbnail_data' ), 10 , 3);

    return $data;
}
add_action( 'json_prepare_post', 'kli_wp_api_json_prepare_post', 5);



/**
 * Prepare post fields - Remove some fields
 * @param  object $data   
 * @return object
 */
function kli_wp_api_prepare_post( $data ){

    // var_dump($data);
    // exit;

    // Remove fields
    // !!todo - check core feature - last checked jan2015
    $fields = explode(',', 'status,author,guid,parent,date,format,'
            .'_links,'
            .'comment_status,ping_status,sticky,date_gmt,featured_image');

    // var_dump($fields);
    // var_dump(each($fields));
    // exit;
    
    foreach ($fields as $value) {
        if ( isset($data[$value]) ) {
            unset($data[$value]);
        }
    }

    return $data;
}
add_action( 'json_prepare_post', 'kli_wp_api_prepare_post', 100);


/**
 * Prepare post fields - Remove attachments fields
 * @param  object $data   
 * @return object
 */
function kli_wp_api_prepare_attachment( $data ){
    // Remove fields
    // @TODO: check core feature - updated jan2015
    $fields = explode(',', 'type,menu_order,'
            .'_links,title,link,'
            .'content,modified,slug,modified_gmt,source,is_image,');
    
    // attachment_meta fields
    $attachment_meta_fields = explode(',', 'image_meta,'
                .'width,height,file'
                );

    if (isset($fields) && count($fields)) {
        foreach ($fields as $value) {
            if ( isset($data[$value]) ) {
                unset($data[$value]);
            }
        }
    }

    if (isset($attachment_meta_fields) && count($attachment_meta_fields) && isset($data['attachment_meta'])) {
        foreach ($attachment_meta_fields as $value) {
            if ( isset($data['attachment_meta'][$value]) ) {
                unset($data['attachment_meta'][$value]);
            }
        }
    }

    return $data;
}
add_action( 'json_prepare_attachment', 'kli_wp_api_prepare_attachment', 100);


```

**Comment by sebastiaandegeus** [comment]
@klihelp looks nice, but the meta always remains. Where is it added because it looks like it's completely outside the normal `json_prepare_post` hook.

**Comment by nCrafts** [comment]
I have a made a small plugin which allows you to return only certain fields:

https://wordpress.org/plugins/wp-rest-api-filter-fields/
https://github.com/nCrafts/json-rest-api-filter-fields

**Comment by tomgantzer** [comment]
Any progress on this? Would love to see it incorporated with the 2.0 core release.

**Comment by aryeharmon** [comment]
+1

**Comment by simonh1000** [comment]
This seems useful to me for when you are creating e.g. the navbar. I need some details of my pages, but certainly not the voluminous content

**Comment by gsarig** [comment]
I believe that a temporary workaround would be to do something like: 

```
add_filter( 'rest_prepare_post', 'my_custom_json_fields', 12, 3 );
function my_custom_json_fields( $data, $post, $context ) {
    return [
        'title'    => $data->data['title']['rendered'],
        'link'     => $data->data['link'],
    ];
}
```

The above example would output only the title and the url for each post.

**Comment by xpluscal** [comment]
Any news on this topic?

**Comment by kadamwhite** [comment]
@xpluscal As noted in the issue linked above when this got closed, this is not currently on the roadmap for this plugin; at this point the root resolution to this question will need to occur within WordPress core, since filter inclusion  represents a change to the core infrastructure. We recognize that this is a common request, and plugins such as the one linked above (may be stale) or https://github.com/elyobo/wp-rest-jmespath should provide a stop-gap until a core strategy is decided.

As for the original post here, `filter[posts_per_page]=-1` has been deprecated & disabled; `?per_page=` accepts only values between 1 and 100 to prevent a single request from overloading your site. Even if we were excluding fields the number of posts that would need to be retrieved is likely the limiting factor, not the size of the response JSON.

**Comment by yenleidong** [comment]
@gsarig You save my life

**Comment by strobox** [comment]
Alternative: do it with plugin - REST Filter Response Fields

**Comment by strobox** [comment]
I recommend [WP REST JMESPath](https://wordpress.org/plugins/wp-rest-jmespath/) for fields filtering and other output modifications.

Example: `/wp-json/wp/v2/pages?_query=[0:2].{id: id, title: title.rendered}` means get last two pages; get id field; transform title.rendered --> title

**Comment by kadamwhite** [comment]
The canonical way to do this is to use the `?_fields` query parameter: `wp-json/wp/v2/posts?_filter=title,link`, `wp-json/wp/v2/posts?_fields[]=id&_fields[]=title`, _etc_.

This does not support nested paths or JMESPath, but does work with the core REST API with no plugins required.
