### ISSUE TITLE
The "json_prepare_post" filter and the priority argument

### ISSUE THREAD

**Issue by nddery** [WP-API/WP-API#451]
Hi,

Not sure if this is a bug or is done by design for some reason but I did not read anything about that in the documentation..

When using the `json_prepare_post` filter with a priority other than `10`, it seems you can't access `post` data. This is done in a theme `functions.php` file. So for example:

``` php
// Using a priority other than 10
function my_json_prepare_post_bad($_post, $post, $context) {
  if ('post' === $post['post_type']) {
    // This here is never true, post_type seems to always be attachment...
  }
  return $_post;
}
add_filter('json_prepare_post', 'my_json_prepare_post_bad', 20, 3);

// Using priority 10
function my_json_prepare_post_good($_post, $post, $context) {
  if ('post' === $post['post_type']) {
    // Good, this is working, this is a post object, do whatever...
  }
  return $_post;
}
add_filter('json_prepare_post', 'my_json_prepare_post_good', 10, 3);
```

**Comment by cristophergv** [comment]
If possible, only the examples shown in internet is:

    qod_remove_extra_data function ($ data, $ post, $ context) {
        // We only want to modify the 'view' context, for reading posts 
        if ($ context! == 'view' || is_wp_error ($ data)) {
            return $ data; 
        } 
        // Here, we unset any data we do not want to see on the front end: 
        unset ($data ['author']); 
        unset ($data ['status']); 
        // Continue unsetting whatever other fields you want return $ data;
    }
    add_filter ('json_prepare_post' 'qod remove extra_data', 12, 3);

**and right is:**

    qod_remove_extra_data function ($ data, $ post, $ context) {
        // We only want to modify the 'view' context, for reading posts 
        if ($ context! == 'view' || is_wp_error ($ data)) {
             unset ( $data->data ['excerpt']); //Example
             unset ($data->data ['content']); //Example
             unset ($data->data ['name field to remove']) 
             //or 
             unset ($data->data ['name field to remove'] ['name subfield if you only want to delete the sub-field of field' ]) 
             return $data; 
         }
    }
    add_filter ('rest_prepare_post' 'qod_remove_extra_data', 12, 3);

IMPORTANT:
Is: 
    add_filter ('**rest_prepare_post**' 'qod_remove_extra_data', 12, 3);

Not: 
    add_filter ('**json_prepare_post**' 'qod remove extra_data', 12, 3); //WRONG

If is Custom Post Type:
    add_filter ('**rest_prepare_{$post_type}**' 'qod_remove_extra_data', 12, 3);

EXAMPLE: Name post type = product; 
     add_filter ('**rest_prepare_product**' 'qod_remove_extra_data', 12, 3);


With this code can remove the fields that you want the JSON. By using rest_prepare} _ {$ post_type decide that you eliminated every post_type fields, thus only affected the post_type you want and not all.

**Comment by reema-bhandari-jabong** [comment]
Complete Funstion:

```
function qod_remove_extra_data( $data, $post, $context ) {
  // We only want to modify the 'view' context, for reading posts
  if ( $context !== 'view' || is_wp_error( $data ) ) {
// Here, we unset any data we don't want to see on the front end:
  unset( $data['author'] );
  unset( $data['meta'] );
  unset( $data['terms'] );
  unset( $data['author'] ['meta'] );
  // continue unsetting whatever other fields you want

  return $data;  
  }

}

add_filter( 'json_prepare_post', 'qod_remove_extra_data', 12, 3 );
```

 If I am using above function then it is removing values for array "0" and array "3". Rest values are same and this function is working if I am using 'rest_prepare_post' instead of 'json_prepare_post', then this is not working at all.
Output of this function is : 
![capture-2](https://cloud.githubusercontent.com/assets/11849485/12347961/0d656fba-bb89-11e5-87ee-1f5c3e36a467.PNG)
![capture](https://cloud.githubusercontent.com/assets/11849485/12347966/10ebeca4-bb89-11e5-9421-406bcaeed837.PNG)

Please look into this if i am doing some mistake.

**Comment by dajocarter** [comment]
@reema-bhandari-jabong It looks like `json_prepare_post` is for V1 of the WP REST API and `rest_prepare_post` is for V2. You also have to write your function differently. Check out this link http://jrdk.nl/blog/2015/08/advanced-custom-fields-acf-in-wp-api-2-0/
