### ISSUE TITLE
Cannot get iframe inside the post

### ISSUE THREAD

**Issue by sun2rise** [WP-API/WP-API#454]
if i have an iframe inside the post, like:
http://famousco.de/2014/08/swipesync-famo-us/
i get it as http://famousco.de/wp-json/posts?filter[s]=SwipeSync

when i get the response i cannot see the iframe inside the post while i would like to get at least the "src" value of the tag

**Comment by danielbachhuber** [comment]
Let us know if you still need help on this issue
