### ISSUE TITLE
Deleting or replacing the whole post_meta

### ISSUE THREAD

**Issue by chiastic-security** [WP-API/WP-API#464]
Am I right in thinking that there is currently no way of either replacing the whole of a post's meta with something new, or else deleting the whole of a post's meta? I've read through the docs and through #63 and I can't see anything there to help.

My use case is, I imagine, the usual one: the meta contains some key/value pairs, and I don't care about the mids. I can't just send the new meta data to overwrite the old, because it merges it, and I end up with duplicate key/value pairs. So I thought I would delete all the old meta, and then send some new meta. But I can't seem to do that. I can't `DELETE /posts/<id>/meta` because I get a 404. I can't `POST /posts/<id>` and send post_meta of `null` because it doesn't delete anything; similarly if I hit `POST /posts/<id>/meta` and send `null`.

Currently I am reduced to retrieving the meta, finding all the mids, and then deleting them one by one. This means sending a huge number of `DELETE` requests, which is very slow, and not a whole lot of fun.

Am I missing something here?

**Comment by danielbachhuber** [comment]
Closing in favor of #1425 and #561
