### ISSUE TITLE
Post Types URI

### ISSUE THREAD

**Issue by iobod** [WP-API/WP-API#467]
Playing around with your plugin (awesome) and I'm receiving the following meta with GET and there seems to be an error in the meta.links.archives where one would expect an ampersand rather than a nonsensical '?'.

"meta": {
            "links": {
                "self": "http://wp.wod.social/?json_route=/posts/types/cf_wod",
                "collection": "http://wp.wod.social/?json_route=/posts/types",
                "http://wp-api.org/1.1/collections/taxonomy/": "http://wp.wod.social/?json_route=

%2Ftaxonomies&type=cf_wod",
                "archives": "http://wp.wod.social/?json_route=/posts?type=cf_wod"
            }
        }

**Comment by danielbachhuber** [comment]
This is no longer a problem on `develop`
