### ISSUE TITLE
Large link header causing 500 Internal Server Error

### ISSUE THREAD

**Issue by d-a** [WP-API/WP-API#475]
When the Link header grows very large (i.e. when fetching a large number of posts) it may end up causing 500 Internal Server Error.

I have two development servers and they handle header sizes differently. One seems to stick with a max size of 8190 bytes for the Links header no matter how large the plugins actually sets it. The other server doesn't, so when the links-header grows past this size the 500 error appears.

Both servers are running Apache, but the server with the problem doesn't identify which version is running, nor can it be seen in the control panel provided by my host.

It may be best to limit the size of the link header and not rely on the host and hope that they've configured their server properly.

**Comment by kokarn** [comment]
For those who don't know how to fix it and need it now, you can easily just comment out the link header.

In the version that's on the WP Plugin Repo it's on line 207 of class-wp-json-posts.php

**Comment by rickycheers** [comment]
+1 on the issue.
Thanks @kokarn for the temporary solution.

**Comment by sheriffderek** [comment]
I commented out 207, but not able to get /posts, /pages, or /option --- I have access to all of the other routes. Any ideas @kokarn

**Comment by gpalin** [comment]
I can confirm this issue occurs when you use filters in the query and request more than 10 posts. I am also running ACF to WP API.

I was able to resolve it using by commenting out the link header as mentioned above. 

For anyone trying to do the same, it's the following line in class-wp-json-posts.php, 
$response->link_header( 'item', json_url( '/posts/' . $post['ID'] ), array( 'title' => $post['post_title'] ) );

**Comment by danielbachhuber** [comment]
We're moving away from link headers in `develop` #1196

**Comment by jazaeri** [comment]
same problem! (500 error for /wp-json/posts/ but /wp-json works fine ), Different solution!

1) i commented "$response->link_header( 'item', json_url( '/posts/' . $post['ID'] ), array( 'title' => $post['post_title'] ) );" in "class-wp-json-posts.php" =>still 500 error
2) deactivated all other plagins =>still 500 error
3) update permalink to "postname" =>still 500 error

finally i activate wp debug mode, error screenshot :
![capture](https://cloud.githubusercontent.com/assets/9153889/7934903/225c0550-0941-11e5-8e66-c15157d75004.PNG)
so i changed time zone to UTC+0 and everything's work fine now 
Hope this helps
(any suggestion to use my own timezone?)

**Comment by ezekg** [comment]
I'm hitting this issue on every site I build that uses this plugin. This is a huge issue.

**Comment by danielbachhuber** [comment]
This is no longer an issue on v2, as we're not sending one link per item.

**Comment by rocket2046** [comment]
@danielbachhuber v2 still 
how can i fix the issue.
wp-json/wp/v2/posts :  The server encountered an internal error or misconfiguration and was unable to complete your request.
