### ISSUE TITLE
WPML compatibility

### ISSUE THREAD

**Issue by timovanleeuwen** [WP-API/WP-API#476]
We're looking to implement the project into a new quite big website, which will be multilanguage using WPML. We've contacted WPML if they want to add support, but as long as the plugin isn't core functionality they put the responsibility into the developers hands.

They have this compatibility program:
http://wpml.org/documentation/theme-compatibility/go-global-program/

Any chance you guys can look into this?

**Comment by pedronetto** [comment]
Hey there @timovanleeuwen, would you mind sharing with us how you solve this issue? It's a shame there is no support for WPML (or the other way around), I think these plugins could work great together!

**Comment by ryuheiyokokawa** [comment]
@pedronetto I recently made a plugin that fixes your issue:
https://wordpress.org/plugins/wpml-to-wp-api/
Hope it works for you.
