### ISSUE TITLE
Filter by custom field? (ACF)

### ISSUE THREAD

**Issue by lapidus** [WP-API/WP-API#491]
I have a custom field (region) on a custom post type (country).
How do I allow filtering by region, such as:

posts?type=country&filter[region]=asia

**Comment by oskarrough** [comment]
Times flies, does WP-API 2.0 perhaps provide any way of filtering by a meta property?

**Comment by wesleyxiao** [comment]
any news on this?

**Comment by PanManAms** [comment]
I haven't worked with WP-API 2.0 yet, so I can't answer that :(
