### ISSUE TITLE
API incompatible with setup_postdata

### ISSUE THREAD

**Issue by sebastiaandegeus** [WP-API/WP-API#492]
Hello,

Using this API and setting up the results with `setup_postdata()` again in another WordPress site creates incompatibility issues on the following properties:

`post_author` versus `author`
`post_date` versus `date`
`post_content` versus `content`
`post_title` versus `title`

This means that `the_title()`, `the_content()`, etc will not work anymore.

I can understand the desire to change these ancient property names to something that makes sense but it breaks compatibility with very standard WordPress functions which most people expect to work. 

We fixed our problem by filtering `json_prepare_post` and assigning the properties.

Related closed issue. 
https://github.com/WP-API/WP-API/issues/41

**Comment by danielbachhuber** [comment]
The object schema for the API will be different than the internal WordPress database model. The API project gives us the opportunity to revisit 12 years of decisions, and make changes we think will be better for the next 12 years. Some object attributes will be similar, others will be different.

#605 is a good reference point for this on-going conversation.
