### ISSUE TITLE
Deleting a custom post type

### ISSUE THREAD

**Issue by federicovezzoli** [WP-API/WP-API#496]
I'm having an issue while trying to delete a custom post type.
The error I receive is "json_user_cannot_delete_post".

I'm making the call trough jquery ajax like this:

    var deleteRequest = WP_API_Settings.root+"/posts/"+postID;
    var dataArrayDelete = {};
    dataArrayDelete["action"] = "wp_api"; 
    dataArrayDelete["_wp_json_nonce"] =  WP_API_Settings.nonce;

    $.ajax(deleteRequest,{
        url : deleteRequest,
        type : 'DELETE',
        data : dataArrayDelete,
        cache : false
    }).done(...

My questions is: How am I supposed to authenticate? it seems that passing "data" is not parsed.
I'm using the same authentication to do posts and everything runs smoootlhy.

thanks

**Comment by danielbachhuber** [comment]
> How am I supposed to authenticate? it seems that passing "data" is not parsed.

If you haven't sorted this out already, it looks like you'll need to make sure your user authentication cookies are valid (e.g. the user is logged in).
