### ISSUE TITLE
getting 404 on http://localhost/wp-json/

### ISSUE THREAD

**Issue by asims2013** [WP-API/WP-API#497]
Hi, I’m having issues getting the plugin to work.  

For my development environment I am running windows 7 + XAMPP for Apache/MySQL.

I have tired installing and enabling the plugin on vanilla wordpress 4 & 3.9 sites but am getting a 404 errors when I ‘run through the ‘checking the api index’ in http://wp-api.org/guides/getting-started.html

i.e. 
curl -i http://localhost/wp-json/

I have built quite a few sites on this setup without any issues but could windows 7 be a problem with the plugin?

Can anybody recommend trying anything?

Cheers
Aaron

**Comment by ghost** [comment]
**Came from Google search and trying into WAMP**

Solution: Enable permalink as `Click Wamp -> Apache -> Apache Modules -> rewrite_module`
Ref: [here](http://stackoverflow.com/a/10294987/385205)

**Comment by balinux** [comment]
add index.php after your root link 

http://localhost/wordpress/index.php/wp-json/wp/v2/posts

it's work on me

**Comment by ecker00** [comment]
While this is old, people still seems to find this thread when looking for issues with 404 on `wp-json`, judging by all the emojis on the previous post. Thought I would share my solution, as my Nginx config was:
```
location / {
  try_files $uri $uri/ /index.php?$args =404;
}
```
Removing **=404** at the end solves it, but if you don't want wordpress to handle 404 pages it's better to add this in bellow:
```
location /wp-json/ { # Resolves WP Gutenberg 404 issue
  try_files $uri $uri/ /index.php;
}
```
