### ISSUE TITLE
Basic_Auth does not seem to work with Postman

### ISSUE THREAD

**Issue by dynelight** [WP-API/WP-API#509]
I tried enabling the Basic Auth plugin, and I declared the login and password headers on postman. I then proceeded to date the data variable with the following content: 

{"title":"Hello World!","content_raw":"Content","excerpt_raw":"Excerpt"}

Attached is a screen shot with the error I get and the setup I am using: 

http://imgur.com/nfBe3DQ

**Comment by mottolini** [comment]
Not sure if is Basic Auth to cause the problem or it's a wrong behaviour of Postman.
If you look at the header returned for a request such as /wp-json/users/me you can find, among others:

HTTP/1.1 302 Found
Location: http://mywebsite/wp-json/users/5

This (http://en.wikipedia.org/wiki/HTTP_302) would force any "correct" http client (such as Postman or PhpStorm Rest Client) to redirect to the location issuing a new request. Postman will do it WITHOUT sending the same basic auth header and this would cause the second request to fail.
In my opinion it doesn't make any sense to issue a redirect, given the fact that the correct json has been delivered.
Offending code is between line 243 and 249 of class-wp-json-server.php

**Comment by sinistance** [comment]
try use the packaged version of postman dude :) it works for me.

**Comment by danielbachhuber** [comment]
Postman is working fine for me.

**Comment by tlovett1** [comment]
Works fine for me too.

**Comment by quanganh206** [comment]
You should choose Raw data not form-data. Postman is working fine for me too.

**Comment by 0xpierson** [comment]
It's not working for me
![bugs](https://cloud.githubusercontent.com/assets/5254167/13910521/2f5482a4-ef56-11e5-9259-4dd1dc768f98.png)

**Comment by nishant-git** [comment]
@ndinhphi Make a GET request.

**Comment by reachtokish** [comment]
it's working for me now with postman
![image](https://cloud.githubusercontent.com/assets/10685261/23099690/ff5885f6-f692-11e6-873f-5272b282c937.png)
![image](https://cloud.githubusercontent.com/assets/10685261/23099691/05452a32-f693-11e6-8bc2-5e828e01a17e.png)
![image](https://cloud.githubusercontent.com/assets/10685261/23099692/0ce33d42-f693-11e6-8c67-561e4829138e.png)
![image](https://cloud.githubusercontent.com/assets/10685261/23099696/211b629e-f693-11e6-9d06-5db11060aec3.png)

**Comment by kosmoscentral** [comment]
Hello, when using Basic Auth, what did you input for Username and pw?  I've tried a number of combinations including,

Consumer Key = Username
Consumer Secret = Password 

See example: http://prntscr.com/eketmu

Oauth 1.0 works just fine and I get a 200 Authorized.  Unfortunately our platform only support Oauth 2.0 and we'll have to use Basic Authentication until support for Oauth 2 is in place.

**Comment by reachtokish** [comment]
@kosmoscentral use your wp-admin username and password as authorization username & pass .. It will work then

Thanks

**Comment by kosmoscentral** [comment]
Thanks Kishore, I figured it out.  Needed to use HTTPS for the URL when connecting with Basic Auth.  My example was using HTTP.  Works like a charm now!

**Comment by reachtokish** [comment]
yes you got it :+1:

**Comment by maurovanetti** [comment]
Postman on Ubuntu as a stand-alone application works.
Postman as a Chrome extension doesn't as long as you are logged in.

**Comment by pwaterz** [comment]
I'm stilling having issues with this. If I copy the curl request my request is successful, via postman, get no response at all.

**Comment by hafizc007** [comment]
i'm getting this  response with postman
i was not able find any results in google with this error. If anybody using this plugin now? please confirm
```
`{
    "code": "recaptcha_error",

    "message": "<strong>The reCAPTCHA wasn't entered correctly. Please try it again.</strong>",

   "data": null
}`
```

**Comment by test313918** [comment]
hi all,

i'm facing the access denied issue in postman service.
i,ve attached screen shot. pls check and let me know any changes.
![untitled](https://user-images.githubusercontent.com/20086664/35042402-85e801de-fbae-11e7-8dac-e8efa11ab64e.jpg)

meanwhile i'm able to access data by login in sharepoint list. but not from postman service and not from calling sharepoint rest api in C# also.

**Comment by lumayara** [comment]
I am having the same issue with SharePoint.. Did anyone find a solution?

**Comment by SnigdhaChotani** [comment]
<img width="1115" alt="screen shot 2018-08-22 at 12 56 23 pm" src="https://user-images.githubusercontent.com/9046034/44487442-2cb96a00-a60b-11e8-955d-bb1f93e1b9ec.png">


I tried the following
1. used GET method and https in URL 
2. username and password are correctly base64-encoding in the Headers.

i am still getting Authentication error. is anybody seeing the same issue?

**Comment by hafizc007** [comment]
@SnigdhaChotani : Its because probably you are using a customised version of wordpress. download from wordpress site and check. that worked for me. i was using a customised version of wordpress provided from my hosting
