### ISSUE TITLE
Always "missing parameter data"

### ISSUE THREAD

**Issue by chrisvanpatten** [WP-API/WP-API#523]
I'm trying to post some raw JSON to the JSON API to create a post.

Here's my cURL command:

`curl -H "Content-Type: application/json" -X POST -d "{'title':'test','content_raw':'hi'}" --user cvanpatten http://dev.site.com/wp-json/posts`

When I submit that (and enter my password), cURL returns this:

`[{"code":"json_missing_callback_param","message":"Missing parameter data"}]`

**EDIT:** I've tried this in Postman (using an incognito window, because cookies take priority, see #509) and it works. This must be something to do with cURL. I'll do a bit more research...

I'm using the Basic Auth handler. I looked through a few error logs on my server and didn't see anything that looked relevant.

**Comment by shaminder95014** [comment]
Pls get me solution
{
    "code": "rest_missing_callback_param",
    "message": "Missing parameter(s): name",
    "data": {
        "status": 400,
        "params": [
            "name"
        ]
    }
}
