### ISSUE TITLE
Get attached media for a single post

### ISSUE THREAD

**Issue by Jasheal** [WP-API/WP-API#525]
Is it possible to get the all the attached images/media for an individual post? I'm building a cordova app and I don't want to pull in the_content, just some custom fields and the attached media..

**Comment by crisanders** [comment]
Would love to know this also. Everything I tried doesn't work. I just need the media attached to a post

**Comment by danielbachhuber** [comment]
On v1.1.1, you can use `/media?filter[post_parent]=<id>`

You'll need to register the `post_parent` query var though:

```
add_filter( 'query_vars', function( $query_vars ) {
	$query_vars[] = 'post_parent';
	return $query_vars;
});
```
