### ISSUE TITLE
schema missing documentation

### ISSUE THREAD

**Issue by altrovideo** [WP-API/WP-API#533]
@ https://github.com/WP-API/WP-API/tree/master/docs

 the links about schema  in "Dive in deeper into the schema details" are not working

Thanks for your great job, WP-API is a great resource and I'm writing a front-end with angularjs using it
you can find it here
https://github.com/altrovideo/wordpress-angularjs

**Comment by ChrisHardie** [comment]
Same as #725

**Comment by danielbachhuber** [comment]
We're maintaining http://v2.wp-api.org/ going forward.
