### ISSUE TITLE
Paginate terms queries and limit by default

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/WP-API#534]
#347 was just fixed, providing the ability to filter the collection retrieved by `/taxonomies/<taxonomy>/terms` endpoints. With this, we now have the ability to set the `number` filter value to specify the number of terms to retrieve. 

When the number of terms is limited, we should provide pagination headers for terms collections in the same manner as we do with `query_navigation_headers` for posts collections.

Once pagination headers are available we should also limit the number of terms retrieved by default, in a manner similar to the way `/posts` defaults to the number of posts per page specified in settings. Without an imposed limit, unfiltered posts queries on sites with tons of tags, such as `http://www.wired.com/wp-json/taxonomies/post_tag/terms`, will become so large that they timeout fail when there are too many terms available.

**Comment by danielbachhuber** [comment]
We're revisiting these query params in #924

**Comment by kadamwhite** [comment]
Woo!
