### ISSUE TITLE
Paginate user endpoint and limit by default

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/WP-API#537]
The users endpoint collection should be returned with pagination headers

(This may [i.e. will] depend on WP_User_Query updates)

As with #534 for taxonomy terms, once pagination is available the users endpoint should be limited by default to a set number of users to prevent timeout errors when hitting /users on sites with many users. It may be appropriate to use the same number of posts per page specified in the admin.

**Comment by danielbachhuber** [comment]
@kadamwhite Why did you add the "Blocked on Core" label here?

**Comment by danielbachhuber** [comment]
Also we're revisiting these query params in #924

**Comment by kadamwhite** [comment]
I believe because it didn't Appear that WP user query provided the information necessary to provide pagination information -- could be wrong

**Comment by kadamwhite** [comment]
I'm referring to providing headers, specifically, not to allowing somebody to formulate their own query with an offset.
