### ISSUE TITLE
CORS missing Access-Control-Expose-Headers for pagination

### ISSUE THREAD

**Issue by matogertel** [WP-API/WP-API#542]
Need to add this in the CORS section, otherwise pagination doesn't work:
`header( 'Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages');`

**Comment by shprink** [comment]
+1
It actually took me quite some time to discover that the AngularJs Client was not the problem ;) https://www.npmjs.com/package/wp-api-angularjs

**Comment by romuloctba** [comment]
+1 CORS and mosquitos are the worst pain I face daily

2015-01-23 17:39 GMT-02:00 Julien Renaux <notifications@github.com>:

**Comment by shprink** [comment]
Pull request pending: https://github.com/WP-API/WP-API/pull/802

**Comment by asimpson** [comment]
Any reason why this isn't merged? I just spent hours trying to figure out why I wasn't getting the proper headers in the browser versus on the server.

**Comment by Chaser324** [comment]
+1. Merge this.

**Comment by aaronsmulktis** [comment]
+1 need this

**Comment by danielbachhuber** [comment]
These headers are included in core infrastructure — no longer a bug.
