### ISSUE TITLE
Consistent collection query arguments across the board

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#555]
**Currently:**

- All over the place
- Arguments typically correspond to the arguments used in core Query classes (post_status, etc.)

**Proposed:**

- Post:
   - author (int)
   - search (string)
   - status (string)
   - before
   - after
   - modified_before
   - modified_after
   - page (int)
   - per_page (int)
- User:
   - search (string)
   - page (int)
   - per_page (int)
   - order (asc|desc)
   - orderby (?)
- Comment:
   - post (int)
- Term:
   - search (string)
   - page (int)
   - per_page (int)
- Look into arguments behind design of WP_Date_Query and ensure we’re not reinventing the wheel

**Comment by danielbachhuber** [comment]
Related #924

**Comment by danielbachhuber** [comment]
This is being handled in #924
