### ISSUE TITLE
Add PHP Codesniffer to make sure we're adhering to coding standards

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#557]
To make this the best code it can be, let's sniff it out automatically.

**Comment by danielbachhuber** [comment]
@westonruter Up for taking another swing at this?

**Comment by westonruter** [comment]
Refreshed PR #558. PHPCS is still complaining, but there aren't as many issues as before: https://travis-ci.org/WP-API/WP-API/jobs/51793479

**Comment by danielbachhuber** [comment]
:ship:
