### ISSUE TITLE
Add field include/exclude parameters to change which fields are returned

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#572]
Commonly requested feature.

We're going to do this in a plugin, as suggested by @danielbachhuber.

**Comment by dsebastien** [comment]
Can you explain a bit the idea/rationale for implementing that as part of a plugin? Would that mean defining a separate API endpoint or extending the current one with more 'filtering' capabilities?

**Comment by joehoyle** [comment]
@dsebastien I think basically we didn't think this fit the 80/20 split. The thought was a simple add-on plugin could make the necessary hooks in to modify the existing endpoints to remove any fields that were not requested for any request.

**Comment by elyobo** [comment]
I've added a simple plugin which allows very flexible field selection (among other things) at https://github.com/elyobo/wp-rest-jmespath; it's very simple, just listening in before the response is sent and using [JMESPath](http://jmespath.org) to do all the heavy lifting.  JMESPath allows doing lot more than just field selection and seems like a pretty good fit for this problem to me.

**Comment by kadamwhite** [comment]
See also https://wordpress.org/plugins/wp-rest-api-filter-fields/ (from comment in #446); may be stale, hasn't been updated in a year.

**Comment by kadamwhite** [comment]
I'm moving this discussion to Trac, since this is a concern that would need to be tackled on the core infrastructure side. I believe this is important functionality to include, and agree that it should be tried out in plugins before we consider merging it into core.

Trac ticket: https://core.trac.wordpress.org/ticket/38131#ticket

**Comment by elyobo** [comment]
See also the simple jmespath plugin I added for this; a steeper learning curve (you need a little JMESPath knowledge - http://jmespath.org), but more flexible in what it allows and will work with any type of
content, including completely custom APIs.

https://wordpress.org/plugins/wp-rest-jmespath/
