### ISSUE TITLE
Write permission discoverability for endpoints

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#574]
As a client developer writing an application, I want to have my application discover which endpoints are readable / writable through response values, and without having to know the intricacies of WordPress' capabilities system.

Currently, we can't easily support this use case because capability is determined at run time. We'll need some sort of framework for a `WP_JSON_Controller` to expose permission scope for its endpoints.

**Comment by danielbachhuber** [comment]
@joehoyle what's remaining on this issue?

**Comment by joehoyle** [comment]
The initial scenario is discovering which endpoints you can write to is now implemented via the `OPTIONS` requests.  

The discussion around more granular capabilities, such as setting status to Publish when you only have access to "Pending" is also available via OPTIONS requests, however we don't have it declared for clients. I'm happy with the `OPTIONS` request being enough here however.

Anyone feel free to reopen if you disagree.
