### ISSUE TITLE
Add object type-to-route mapping to index for discoverability

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#577]
To enhance client discovery, we'd like for endpoints to be able to register a global name that will appear in the index. For instance, core will register `posts`, `users`, `comments`, `terms`. Jetpack may register `portfolio`.

Currently our index returns a list of routes, but the individual routes don't have much metadata about the *type* of resource each represents.

The degree to which we recognize these as named content objects is TBD.

**Comment by danielbachhuber** [comment]
[Pushing this to future](https://wordpress.slack.com/archives/core-restapi/p1427759475000547). It doesn't seem like we have a clear direction on it, and we need more input from client authors.

**Comment by danielbachhuber** [comment]
I want to revisit this in beta2 because I think it has real-world utility for us (e.g. documentation generation)

**Comment by danielbachhuber** [comment]
Punting to Future. #1222 should do the trick for our more immediate needs.

**Comment by rmccue** [comment]
Closing this out; namespaces are listed in the root for discoverability of extensions to the API, and schema data is exposed with `context=help`. Combined, these should let you do all the discovery your heart desires.
