### ISSUE TITLE
Address testing blind spot with route resolution / argument parsing

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#581]
Because the majority of our test coverage tests methods on the endpoints, we only occasionally test route resolution, argument parsing, etc.

For instance, in #579, my tests for `get_item()` pass, but the application fails because of #580.

We should have end to end test coverage.

**Comment by danielbachhuber** [comment]
I'm pretty happy with our testing setup now. @joehoyle @rmccue @rachelbaker Agree? Should we close?

**Comment by joehoyle** [comment]
I think we should close, doesn't seem to be much direction / proposed here. +1 for cleaning out!
