### ISSUE TITLE
Use ID instead of email address to get user's avatar

### ISSUE THREAD

**Issue by josiahgoff** [WP-API/WP-API#585]
Can we change the `json_get_avatar_url()` function to accept `$email_or_id` the same way `get_avatar()` works and then use the user's ID to get the avatar in `prepare_user()`?

I have a use case (I'm assuming others would as well) where some users don't have an email address because they were created from a twitter account. Because we're passing the email address instead of the ID, I have no way to detect what user is requesting an avatar in the `get_avatar` filter.

https://github.com/WP-API/WP-API/blob/develop/lib/class-wp-json-users.php#L282

**Comment by rachelbaker** [comment]
This is now handled in a WP Core function `get_avatar_url()`  https://core.trac.wordpress.org/changeset/31107
