### ISSUE TITLE
Custom Post Type json_no_route

### ISSUE THREAD

**Issue by stephangrobler** [WP-API/WP-API#596]
I have created a custom post type and extended the WP_JSON_CustomPostType class as in the documentation, I can see the custom type when I go to wp-json/ but as soon as I go into wp-json/quizes it gives this error, any help would be great. PS: Im new to plugin dev.

http://pastebin.com/G5VLaZ3d

**Comment by brian2000** [comment]
I tried this and ran into the following error

Catchable fatal error: Argument 1 passed to WP_JSON_CustomPostType::__construct() must implement interface WP_JSON_ResponseHandler, none given,

Did I miss something?
