### ISSUE TITLE
Add order & orderby parameters for terms query

### ISSUE THREAD

**Issue by m0g** [WP-API/WP-API#607]
Hi,

it would be really nice if we could add sorting paramaters for terms query.
Something like that would be great:

```
/taxonomies/:taxonomyName/terms?orderby=name&order=desc
```

Thanks

**Comment by sjalgeo** [comment]
@danielbachhuber Does this work on Version 1.2.1?

**Comment by danielbachhuber** [comment]
No. We're only actively developing against `develop` at this time

**Comment by sjalgeo** [comment]
@danielbachhuber So is it possible to order the terms?

**Comment by danielbachhuber** [comment]
It is, but only on 2.x versions. Not in 1.2.1

**Comment by fclaussen** [comment]
Oh. I was looking for this. My client wants to rearrange his taxonomy terms. I got this on the backend but the old order comes to when I use the api.
There is no chance of this being added for V1? This is not an enhancement. It's a bug fix.
