### ISSUE TITLE
Delete requests shouldn't return response with message body

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#618]
In the user's controller, we return this response when the delete request is successful:

```
return array( 'message' => __( 'Deleted user' ) );
```

As a matter of practice, I don't think we should *ever* return a "message" in a 2xx response. "Success" is implied by the response code, and it's inconsistent generally.

@WP-API/amigos opinions?

**Comment by rmccue** [comment]
Closing in favour of #789, bur we should keep the thinking from here.
