### ISSUE TITLE
Information about users

### ISSUE THREAD

**Issue by drag0nman** [WP-API/WP-API#633]
Hello Everybody
the route http://mysite.com/wp-json/users with authentication works.
But http://mysite.com/wp-json/users/{IDuser}/posts not works with message:
[{"code":"json_no_route","message":"No route was found matching the URL and request method"}]

Also I have another question:
is it possibile get the email of the users and the date of last activity?

Thanks

**Comment by danielbachhuber** [comment]
Closing in favor of #843
