### ISSUE TITLE
Can we do meta-parameters better?

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#634]
At the moment, we have meta-parameters that you can pass into a request. The ones we have currently:

* `_jsonp`
* `_embed`
* `_method`
* `_envelope` (#628)

We have a finite space to pack these into (query strings). They should never conflict with endpoint arguments in core, but could possibly do so in plugins registering their own. If we stick with the current method, it needs to be documented that these exist and mean something outside the endpoint.

**Comment by danielbachhuber** [comment]
[Punt](https://wordpress.slack.com/archives/core-restapi/p1427758964000494) — this hasn't come up in a long time so these are probably fine as is.
