### ISSUE TITLE
Filtering posts example?

### ISSUE THREAD

**Issue by matt-bernhardt** [WP-API/WP-API#640]
Hello, I find myself struggling to filter a list of posts, and am trying to find an example implementing the options I see in the documentation. What I see:

http://[mysite]/wp-json/posts
This returns the river of posts on the site, which is great. Unfortunately for the implementation I'm attempting, I need to pick only two posts from the river. Fishing in this manner has caused problems, so I'm trying to tweak the AJAX call to return only the posts I'm looking for.

Thus far, we've tried to make this fishing easier (and impose a central editing/approval point) by having the designated posts edited by a specific user. Unfortunately, the only documentation I can find for a filter is

http://[mysite]/wp-json/posts?filter[s]=term

However, I can't drop the user name or ID in for "term" and get anything meaningful. From the documentation, it appears that

http://[mysite]/wp-json/users/37
... is more about getting information about the user, rather than posts authored by the user. Additionally, when I try:

http://[mysite]/wp-json/posts?author[s]=37
...nothing actually gets filtered. I've gone through the documentation for filtering that I see at http://wp-api.org/#posts_retrieve-posts but nothing seems to work?

I'm about to start diving into the source code to see if I can find anything in there, but wanted to post this briefly to see whether I'm just missing something obvious.

Many thanks,

**Comment by abhijitsinha89** [comment]
Hi, I am also looking for a similar functionality, i.e filtering the list of posts for a specific author. I can see that this route works "http://[mysite]/wp-json/posts?filter[author]=37" i.e Putting the ID of the author to filter the data. However, if I want to filter using the name of the author, is it possible achieve that. eg : http://[mysite]/wp-json/posts?filter[author]='name'.

**Comment by kadamwhite** [comment]
You should be able to use `author_name` to search by an author's username, e.g. `?filter[author_name]=frankherbert`.  However, there is no way I know of to search by an author's full name, only their username or ID.

**Comment by abhijitsinha89** [comment]
Hi, thanks a lot! I tried lot of options like author_slug, author_username..those didnt work! author_name works! thanks a lot! :)

**Comment by williamle8300** [comment]
Here's how you get posts by the author's full name.

```
/posts?filter[author]=john-smith
```
