### ISSUE TITLE
Problem with BBPress and private topic/reply

### ISSUE THREAD

**Issue by drag0nman** [WP-API/WP-API#655]
Hello everybody,
My wordpress site has a BBPress forum with private area which can be accessed from the site only by the logged users in order to read topic and replies and create new topic and replies.
The problem is that with the routes:
wp-json/posts?type=topic
wp-json/posts?type=reply
I can access to read the topics and replies without basic authentication.

I would like to get the same behavior as the route:
wp-json/users
that denied to get information if the basic authentication is failed with the reply:
{
code: "json_user_cannot_list",
message: "Sorry, you are not allowed to list users."
}

Thanks to all

**Comment by danielbachhuber** [comment]
> However this brings up a bug in our current implementation

This bug is now longer applicable https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-posts-controller.php#L900
