### ISSUE TITLE
Only show sticky posts

### ISSUE THREAD

**Issue by adriancervoni** [WP-API/WP-API#658]
I have readed all the docs and tried to combine with the WP_query but I couldn't found on the docs a 'show only sticky posts' working way, I assume it should be something like that.

wp-json/posts?filter[post__in][]=get_option("sticky_posts")
wp-json/posts?filter[post__in][]=sticky_posts

It's a bug? or I didn't coded it right?

**Comment by danielbachhuber** [comment]
We're revisiting these query params in #924
