### ISSUE TITLE
Get total of posts

### ISSUE THREAD

**Issue by luizkim** [WP-API/WP-API#662]
To use pagination i need get total of posts.

Exemple:
/wp-json/posts/?filter[post_format]=post-format-gallery&count=true

On this exemple, i need the last page:
/wp-json/posts/?filter[post_format]=post-format-gallery&filter[posts_per_page]=10&page=<LASTPAGE>

**Comment by xkidro** [comment]
But how do you get it if you cache the results ? for example using https://github.com/iandunn/wp-super-cache/blob/0f24a2ac0e3b375091ba45389dbe1a92977c98b7/plugins/rest-api.php this does not save the headers.
