### ISSUE TITLE
WP_JSON_CustomPostType uses incorrect parent method names

### ISSUE THREAD

**Issue by NateWr** [WP-API/WP-API#667]
```WP_JSON_CustomPostType``` uses the method names ```get_posts``` and ```get_post```, and calls ```parent::get_posts()``` and ```parent::get_post()```. But its parent class, ```WP_JSON_Posts```, uses the method names ```get_multiple``` and ```get```.

I can prepare a PR to fix this. Should I just update the calls to the parent class methods? Or should I update the method names for ```WP_JSON_CustomPostType``` as well? I wasn't sure if this was just an "example" or if changing this would cause backwards compatibility issues.

**Comment by danielbachhuber** [comment]
No longer applicable — `WP_JSON_CustomPostType` is no more
