### ISSUE TITLE
wp_slash when saving meta keys and values

### ISSUE THREAD

**Issue by timbofield** [WP-API/WP-API#672]
Before update_metadata_by_mid is called both the key and value are passed through wp_slash.

This shouldn't happen, as wordpress as a rule does the opposite when saving meta values, the core update_metadata function for example calls wp_unslash before saving. 

So if you have values being updated via the API and via the admin things get very confusing.  

Why is wp_slash being called here? these values will be escaped before being instered into the database without doing this.

**Comment by rmccue** [comment]
Handled in #960.
