### ISSUE TITLE
Search by string in custom post types 

### ISSUE THREAD

**Issue by kazartsevalex** [WP-API/WP-API#674]
Hi, firstly - nice plugin you've made, big thanks for it!
But i can't find a way to filter my posts with custom post type 'product' by user's string.. It should be some simple ajax majic i think, but anyway can't find a solution :(

I'm searching by url like this ```'/wp-json/posts?type=product&filter[s]=' + userString;```

Actually it works but searches only in ```product.title```, not in ```product.content``` or other fields..

Can you please help me?

**Comment by danielbachhuber** [comment]
Sorry for the late reply here. Hard to say what the bug might be without having access to the codebase.
