### ISSUE TITLE
Please specify: Make sure your permalinks are set to “post name”.

### ISSUE THREAD

**Issue by dotnetCarpenter** [WP-API/WP-API#69]
I was trying to get WP-API to work for hours and actually gave up until I stumbled upon http://themergency.com/wordpress-rest-api/. I didn't know that I should **Make sure your permalinks are set to “post name”.**

Please, please note this in capital letters in the README!

You might also want to add a link to [Using Permanlinks - Choosing your permalink structure](http://codex.wordpress.org/Using_Permalinks#Choosing_your_permalink_structure) for other developers new to Wordpress.

**Comment by razorsharpshady** [comment]
@dotnetCarpenter  your post just saved my day. Thanks Man.

Other guys looking for solution:
Settings > Permalinks
Make sure your **permalinks** are set to “**post name**”.

Just for google searches : WooCommerce > Settings. You must enable pretty permalinks, as default permalinks will not work.
![woo](https://user-images.githubusercontent.com/20279966/37206869-6d3c0510-23c0-11e8-91b6-34030bfb6f70.PNG)

**Comment by loloDawit** [comment]
I almost gave until I found this page, I think this needs to be on the api documentation
