### ISSUE TITLE
Migrate post and comment author data methods from old Users Controller.

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#698]
I am not sure these are still needed, but filing this issue so I don't forget.  The `add_post_author_data()` and `add_comment_author_data()` methods existed in the old style Users class, should they be migrated to the new Users Controller?

https://github.com/WP-API/WP-API/commit/449e5a08dbd6e1e49b926780da3137986fc8d034#diff-cc13d1af83bca665c308c0d134411047L429

**Comment by danielbachhuber** [comment]
We might be able to address this with `_links` and `_embed`. Needs some discovery for b1

**Comment by rachelbaker** [comment]
Looks like this is done.  Closing issue.
