### ISSUE TITLE
Better search with relevanssi or elastic search

### ISSUE THREAD

**Issue by timovanleeuwen** [WP-API/WP-API#699]
I'm very curious, as all know, default worpress seach, and thus search through this api, is pretty crappy.

There's two great options to improve wordpress seach, or through relevanssi (https://wordpress.org/plugins/relevanssi/) or by using elastic search and the wp elasticsearch plugin (https://wordpress.org/plugins/fantastic-elasticsearch/)

Now my question is, will these plugins work directly with the api? I installed relevanssi but it doesn't seem to work. 

Do have to call upon you guys, or talk with the plugin developers?

**Comment by sxalexander** [comment]
We're interested in making sure this compatibility exists. @danielbachhuber could you elaborate on what the proper way to filter `WP_Query`'s `s` argument is for compatability with WP-API is? While its understandable that WP-API won't focus on providing shims, Relevanssi currently has a very, very wide user install base and having both plugin authors/communities work towards compatibility opens WP-API up to their install base.

**Comment by danielbachhuber** [comment]
> could you elaborate on what the proper way to filter WP_Query's `s` argument for compatibility with WP-API is?

I'm not sure where there's confusion. Can you clarify?

**Comment by rmccue** [comment]
Internally, the API uses stock standard calls to `WP_Query`. If Relevanssi hooks in to handle queries with a `s` query var, it should automagically work on the API as well without any extra changes. (I'd assume you're already doing this to work with the normal WP search page anyway?)

If you want to add extra query vars to use via the API as well, you can filter `query_vars` to add any necessary vars to WP's public query vars. (If you want to do it just for the API, the filter is `rest_query_vars` for v2 and `json_query_vars` for v1.)

**Comment by sxalexander** [comment]
@danielbachhuber @rmccue Gotcha – and thanks for the clarification.  Unfortunately, Relevanssi does some clever hooking.

**Comment by pat-hartl** [comment]
I've been working with this for the past day and Relevanssi does some non-standard hooking that is pretty wonky. You can only do a query with Relevanssi by using `relevanssi_do_query( $query_object );` which then modifies `$query_object->posts` and does not return anything. My very temporary solution for v1 of the REST API was to insert:
```php
if ( isset($query['s']) && function_exists('relevanssi_do_query') ) {
    relevanssi_do_query( $post_query );
    $posts_list = $post_query->posts;
}
```
under `$posts_list = $post_query->query( $query );` in `class-wp-json-posts.php` on line 165. This is a very hacky way of doing it, but it works. I agree that Relevanssi should be adapted to support the REST API, but as I understand it, it uses some weird workarounds and isn't really built to be a search modifier, rather a search template modifier.

Adding a hook here wouldn't be a good idea, but would there be a better way to handle this?

**Comment by danielbachhuber** [comment]
Relevanssi should properly modify the WP_Query by hooking into `the_posts` filter: https://core.trac.wordpress.org/browser/tags/4.3/src/wp-includes/query.php#L3637

**Comment by pathartl** [comment]
Note that you can use filters to disable Relevanssi from blocking search via WP API. I've created a Gist for the plugin I made:
https://gist.github.com/pathartl/f633cbf9ed0a793f3c31

It's not pretty, but it works.

**Comment by jasonhjohnson** [comment]
@pathartl Hi. Thanks for the gist. It doesn't appear to be working for me with the latest version of the rest api. Any thoughts?

**Comment by pathartl** [comment]
It probably won't work on v2/core. It could be that $wp->request doesn't start with wp-json or might not be the right thing to check for. It also might be the priority? Maybe try changing it from 11 to something higher? We haven't moved from v1 to v2/core internally yet so I haven't had the chance to play with it.

**Comment by jasonhjohnson** [comment]
@pathartl It's getting inside the if that removes the filter, it just seems the remove_filter has no affect, or perhaps it occurs before relevannsi add's it back? Here's my relevant code: http://take.ms/LuhIw

**Comment by jasonhjohnson** [comment]
@pathartl I changed the "200" number from my screenshot to "2" and that seemed to fix it.
