### ISSUE TITLE
Getting custom post type taxonomy terms

### ISSUE THREAD

**Issue by zkingdesign** [WP-API/WP-API#709]
Hi,

I have a custom post type that has a taxonomy called product-category and I'm trying to list the terms of that taxonomy and unfortunately I'm having issues.

Trying with the following http://domain.com/wp-json/taxonomies/product-category/terms

This just returns [{"code":"json_no_route","message":"No route was found matching the URL and request method"}]

http://domain.com/wp-json/taxonomies/category/terms does list the posts>category taxonomies, so that works, but custom taxonomy doesn't..

If I navigate to : http://domain.com/wp-json/posts/?type=product

Then I get all posts from the post type, part of the code: [{"ID":49,"name":"Specialty","slug":"specialty","description":"","parent":null,"count":3,"link":"http:\/\/renaware.com\/product-category\/specialty\/","meta":{"links":{"collection":"http:\/\/domain.com\/wp-json\/taxonomies\/product-category\/terms","self":"http:\/\/domain.com\/wp-json\/taxonomies\/product-category\/terms\/27"}}}]}}

Am I doing anything wrong here?

**Comment by svinqvmraka** [comment]
I can confirm having the exact same issue - taxonomies with a dash in their name return 'json_no_route' error. The taxonomies are public. 
zkingdesign's filter above fixes it.

**Comment by danielbachhuber** [comment]
This was fixed in #410, but never released as 1.2. Using the master branch of this repo should do the trick.

**Comment by toekneetone** [comment]
Where would you suggest placing this code? I am having the same issue using the Business Finder WP template.

**Comment by zkingdesign** [comment]
Create a folder in /plugins directory in the new folder create a .php file, insert the code above, and activate the plugin, and it will work automatically.

**Comment by toekneetone** [comment]
I created a new folder called 'new' and within that folder i have a file with the code in it called 'index.php' but when I go to the WP back-end to activate I don't see it in the list of installed plugins. Am I doing something wrong?

**Comment by zkingdesign** [comment]
Copy the following in the plugins/new/index.php directory

<?php
/*
Plugin Name: ONet WP API Fixer
Plugin URI: http://onetdev.com
Description: Fixes the WP API dash matchin issue
Author: Zoltan Kiraly
Author URI: http://zkingdesign.com/
Version: 0.6.1
Text Domain: onet-wpapifix
License: GPL version 2 or later - http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
*/

function ONetWPAPIDashFix ( $endpoints ) {
	$new_endpoints = array();
	foreach ( $endpoints AS $match => $data ) {
		$new_endpoints[ str_replace( '\w+', '(?:[\w\-](?<!_))+', $match ) ] = $data;
	}
	return $new_endpoints;
}

add_filter('json_endpoints','ONetWPAPIDashFix',10,1);

**Comment by toekneetone** [comment]
what would be the best way to call the listing items? /wp-json/posts

**Comment by jatin846** [comment]
Same issue with me but code or plugin not solve my problem.

Please check below link:
Web view: http://goo.gl/5ektIZ or e.g. domain/product-category/music/
Json API dataview: http://goo.gl/jPKT5I or e.g. /wp-json/taxonomies/product_cat/terms/11

json api view not showing /taxonomies/product_cat/terms/11 data
Please guide me How can I get display data?

all products display but taxonomies/ filter/sorting option pending
http://goo.gl/SH3yIQ or e.g /wp-json/posts/?type=product
