### ISSUE TITLE
Refresh documentation

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#719]
In the near future, we should do a refresh of the documentation, including:

* [ ] Our new Controller pattern, with associated Controller test pattern.
* [ ] Request class.
* [ ] Enveloping / batch requests.
* [ ] Updating all endpoint arguments.

(Feel free to edit this checklist).

**Comment by danielbachhuber** [comment]
@pollyplummer any opinions on what should be added to that list, and how we should go about this? I'm ready to kick things off

**Comment by pollyplummer** [comment]
@danielbachhuber Most of those listed seem like they'd fall under the Guides section on wp-api.org. Those are fairly easy to add as new files. The site currently uses the "master" branch of WP-API to pull from, but we probably don't want to add new guides or update the routes.md file in the master until the develop branch is pushed through to the plugin. In the meantime, we could create a new docs-develop branch in the wp-api.org repo for adding new guides that pertain to the upcoming changes to the plugin. Thoughts on this approach? @rachelbaker @rmccue

**Comment by danielbachhuber** [comment]
Documentation is now covered by the docs repo https://github.com/WP-API/docs-v2/issues
