### ISSUE TITLE
Return attachment posts in order from the WP image editor

### ISSUE THREAD

**Issue by thomastraum** [WP-API/WP-API#720]
Hey, I am trying to figure out if there is a way to return the image attachment posts of a post in the order they are arranged via drag and drop in the WP editor:
https://www.dropbox.com/s/i34f8eyex37ztmc/Screenshot%202014-12-11%2013.04.13.png?dl=0
`curl -ig "http://stage.thomastraum.com/wp-json/media?filter[post_parent]=5546" | prettyjson`

Do I need to query for a gallery there? 

Many Thanks,
T

**Comment by danielbachhuber** [comment]
Just to follow up on this...

> Is there a way to query for all post attachments to be returned in the order of the editor?

Nope. Unless the data is saved to the database in a structured way, there's no way to query by it in the API. WordPress doesn't store gallery details in a structured way. They're stored as a shortcode with comma-separated values in the shortcode attribute.
