### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by Sam-Hoult** [WP-API/WP-API#724]
There is no documentation on caching.
W3 Total Cache fails to cache (with or without query string caching).
An option to enable caching would be great.

Any help would be appreciated.

**Comment by oskarrough** [comment]
Still, would be really great with some info on how to use which caching plugins together with WP-API.

**Comment by colinory** [comment]
I'm curious if there is already a solution to this? Need caching. I'm retrieving 500+ posts with the API. This generates a 3mb JSON file and takes ages to retrieve this.... :-(

**Comment by klihelp** [comment]
Check this plugin
https://github.com/Shelob9/jp-rest-cache

**Comment by jtwee** [comment]
I have updated Josh's caching code to be a WordPress plugin not requiring composer. It's not thoroughly tested though, so be careful with it.

https://github.com/breams/wp-rest-cache

**Comment by iandunn** [comment]
FYI, we're [working on a module for WP Super Cache](https://github.com/Automattic/wp-super-cache/pull/121) that will cache endpoints. It's ready for beta testing if anyone wants to try it and post feedback to the PR.

**Comment by jtwee** [comment]
Actually, I've installed your pull request as well and was trying to work out which would be more stable to run in a production environment. @iandunn, do you have any idea if there's a timeline or roadmap for the API caching plugin being integrated into WP Super Cache? Also, are there any dev tasks that I could help with in that process?

**Comment by iandunn** [comment]
@breams: I haven't used `jp-rest-cache`, so I can't compare the stability. I would think for most people the big factor when choosing one over the other would be integration with their existing cache solutions.

If you're already using a persistent object cache, then `jp-rest-cache` would be a much better fit in most cases. If you want to use a static page caching plugin, then the new module for WP Super Cache would be a better fit.

In terms of its stability, I think it's pretty close to what it will look like when it's merged, unless any unexpected issues come up during the final rounds of testing. It hasn't had any real-world testing yet, though, so it's a judgement call on whether or not you want to install it on a production site. You'll probably be fine, especially if you test it after installation and periodically.

**Comment by jtwee** [comment]
@iandunn Thanks for that info, it really helps to work out a plan going forward. I think I'm stuck with static page caching, so I'm firmly behind the WP Super Cache module. I just wanted to have options seeing as there isn't currently anything that's plug and play.
