### ISSUE TITLE
Access Menu information via the API

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/WP-API#73]
I'm curious to know if there's any plan to support accessing WP's Menu structures via this API. I have a site where I'm interested in using a WP install to content-manage the menus, but won't be using WordPress's templating to render them—being able to get menu info via this API would be pretty cool.

If there's technical reasons not to do this, or if there's an existing path to get this information, I'd love to learn more.

**Comment by denitto** [comment]
Hey @nekojira :  thank you for your solution in the meantime.  Testing it out now.
