### ISSUE TITLE
Setting post format fails

### ISSUE THREAD

**Issue by jithujose** [WP-API/WP-API#735]
Hi everyone,

We noticed that the ```insert_post``` method of ```WP_JSON_Posts``` class doesn't attach the post format we pass through the ```$data``` array.

```wp_update_post``` and ```wp_insert_post``` functions do not do anything with the post_format parameter.

In order to set the format, there should be a call to the  ```set_post_format``` function.

**Comment by danielbachhuber** [comment]
This is now fixed on `develop`. It's an enhancement on `master`, so we won't be adding it.

**Comment by jithujose** [comment]
@danielbachhuber @rachelbaker 

We are now using the develop branch and still the post format is not getting set.

We do a POST request to /wp-json/posts.

**Comment by danielbachhuber** [comment]
Can you share an example request? [Here's how the `format` param is handled](https://github.com/WP-API/WP-API/blob/develop/lib/class-wp-json-base-posts-controller.php#L163)

**Comment by rachelbaker** [comment]
@jithujose Try sending your POST request to `/wp-json/wp/posts` that will direct you to the new endpoints where this issue has been resolved.

**Comment by jithujose** [comment]
@rachelbaker  @danielbachhuber 

That works. Thank you all.
