### ISSUE TITLE
Dynamically build the json_url in WP_JSON_Base_Posts_Controller from post_type base

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#739]
One of the incomplete items from #684.

We need to find a way to dynamically determine the route namespace and path for `_links` and other uses in WP_JSON_Base_Posts_Controller.  

Or perhaps there is a better approach?  I am hoping someone with more of an architectural eye, like @rmccue (?), would like to tackle this.

**Comment by danielbachhuber** [comment]
This has been addressed https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-posts-controller.php#L214
