### ISSUE TITLE
Posts Controller should use comments_open() instead of `comment_status` attribute

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#747]
`comments_open()` runs the `comment_status` value through a filter, which we should respect.

**Comment by rachelbaker** [comment]
@danielbachhuber What do you think of doing something like this:

```
"discussion": {
        "comments_open": true,
        "comment_status": "open",
        "pings_open": true,
        "ping_status": "open",
        "comment_count": 5
    },
```

**Comment by rmccue** [comment]
I'd be OK with that, but should we have the data more structured into types? Something like...

```json
{
    "discussion": {
        "count": 5,
        "comments": {
            "open": true,
            "status": "open"
        },
        "pings": {
            ...
        }
    }
}
```

This could allow us to handle custom comment types more nicely too.

**Comment by rachelbaker** [comment]
:cake:

**Comment by danielbachhuber** [comment]
What's the benefit, and how do we model this with JSON schema?

**Comment by danielbachhuber** [comment]
I was thinking that `count` should be an attribute of the objects in `_links` because we also need for revisions, attachments and other related resources

**Comment by danielbachhuber** [comment]
Another consideration: how do we distinguish between attributes that are editable vs those that aren't?

**Comment by rachelbaker** [comment]
@danielbachhuber How would you propose we expose whether comments and pings are open (non-editable fields)?  

Adding `count` as an attribute of the `_links` object would be fine with me.

**Comment by danielbachhuber** [comment]
I don't have a good suggestion at the moment. I think it needs more thought (and possibly discussion). I'm wary of nested data structures (title, content, and editor included in this) because they introduce more complexity. 

We also don't have a paradigm (as far as I'm aware of) for maybe read-only fields. Without an established paradigm, what's a client to do? Try to update, see a silent failure, and assume that's the expected before?

Just wanted to consider this from all angles before we make a decision.

**Comment by rachelbaker** [comment]
I know that you are still interested in using JSON Schema, and it is a feature you are very passionate about.  

Modeling responses with JSON Schema is not a consideration I believe needs to be made at this time.  I don't want to set the precedent that a possible future feature needs consideration with each PR.

**Comment by danielbachhuber** [comment]
JSON schema aside, we need to have a consistent abstraction. If we don't have a consistent abstraction, we get inconsistent behavior.

I think everyone that's ever worked with an API has horror stories about inconsistent behavior. When we make changes to the behavior of the API, it should be explainable with our larger theory of abstraction.

**Comment by danielbachhuber** [comment]
We've decided our current implementation is the correct behavior.

`POST /wp/v2/comments` correctly respects `comments_open()`. On the Post resource, `comment_status` is the database value. Because `comments_open()` is filterable, it would be incorrect to use the filtered value on the Post resource, which is intended to appropriately model the data in the .

For clients building commenting user experience, `OPTIONS /wp/v2/comments` and looking at the accepts header is the most reliable way of determining whether a Post resource accepts comments at a given time. Again, this is variable because `comments_open()` is filterable.
