### ISSUE TITLE
How to create post with taxonomy?

### ISSUE THREAD

**Issue by PanManAms** [WP-API/WP-API#749]
The "terms" or "term_names" are in the code, but not documented:
https://github.com/WP-API/WP-API/blob/master/lib/class-wp-json-posts.php#L221
Can we get an example of the object that needs to be posted? 
I tried various combinations of 
` terms - array, with taxonomy names as keys and arrays of term IDs as values `
but none work. Thanks!

**Comment by andreboekhorst** [comment]
Volgensmij is deze nog niet geimplementeerd:
https://github.com/WP-API/WP-API/blob/master/lib/class-wp-json-posts.php#L928

je zou hiervoor zelf een action aan de volgende hook kunnen hangen:
https://github.com/WP-API/WP-API/blob/master/lib/class-wp-json-posts.php#L950

**Comment by andreboekhorst** [comment]
Second look:
Hij gebruikt de array die naar wp_insert_post() wordt gestuurd. Die gebruikt als input, tags_input, ipv terms:

'tags_input'     => [ '<tag>, <tag>, ...' | array ] // Default empty.

http://codex.wordpress.org/Function_Reference/wp_insert_post

Kun je het hiermee proberen?

**Comment by andreboekhorst** [comment]
This works for custom tax:

Add this to your plugin / functions.php

function wp_api_add_tax($post, $data, $update){
    foreach( $data['custom_tax'] as $tax => $val ){
        wp_set_post_terms( $post['ID'], $val, $tax );
    }
}
add_filter('json_insert_post', 'wp_api_add_tax', 10, 3);

The JSON call should have this data:

data = {
     'title': 'Check, check check it out',
     'content_raw': 'What it\'s all about',
     'custom_tax': {
          'taxonomy': ['tax_title']
     }
}

**Comment by danielbachhuber** [comment]
We'll be handling this with batch requests #561

**Comment by dleeward** [comment]
andreboekhorst,

How would you URL encode the JSON data?
