### ISSUE TITLE
Move prepare_item_for_response method into the Base Posts Controlller

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#752]
- [ ] Refactor method to check 'post_type_supports' when preparing response fields.   Related #748 
- [ ] Move out of WP_JSON_Posts_Controller and into WP_JSON_Base_Posts_Controller

Possible supported fields:
'title'
'editor' (content)
'author'
'thumbnail' (featured image) (current theme must also support Post Thumbnails)
'excerpt'
'trackbacks'
'custom-fields'
'comments' (also will see comment count balloon on edit screen)
'revisions' (will store revisions)
'page-attributes' (template and menu order) (hierarchical must be true)
'post-formats'

**Comment by danielbachhuber** [comment]
I can pick this up — I've started in 1a77e6c

**Comment by rachelbaker** [comment]
@danielbachhuber Reassigned this to you.  Enjoy.

**Comment by rachelbaker** [comment]
Being tackled in #820
