### ISSUE TITLE
Remove featured_image field from $_post

### ISSUE THREAD

**Issue by klihelp** [WP-API/WP-API#755]
I can't remove featured_image field using json_prepare_post action?
Thanks for your help.

```
function wp_api_prepare_post( $_post ){
     unset($_post['featured_image']);
     return $_post;
  }
 add_action( 'json_prepare_post', 'wp_api_prepare_post', 10)
 add_action( 'json_prepare_post', 'wp_api_prepare_post', 99);
```

**Comment by klihelp** [comment]
This filter will remove the 'featured_image' field

```
    function wp_api_remove_field_thumbnail_data( $data ){
        global $wp_json_media;
        remove_filter( 'json_prepare_post', array( $wp_json_media, 'add_thumbnail_data' ), 10 , 3);

        return $data;
    }
    add_action( 'json_prepare_post', 'wp_api_remove_field_thumbnail_data', 5);
```

**Comment by rachelbaker** [comment]
@klihelp Looks like you solved your issue.  Anything else needed here?

**Comment by modemlooper** [comment]
I have the opposite issue, I want to keep the featured_image data but edit it. Changes do not affect response if the post has a featured image. If post does not have a featured image then you can edit the data. Below code only works if there is no featured image attached to post. 

function set_featured_image( $post_response, $post, $context ) {
	$post_response['featured_image'] = 'new image';
	return $post_response;
}
add_filter( 'json_prepare_post', 'set_featured_image', 999, 3 );

**Comment by modemlooper** [comment]
using example above this worked

function set_featured_image( $post_response, $post, $context ) {

	global $wp_json_media;
	remove_filter( 'json_prepare_post', array( $wp_json_media, 'add_thumbnail_data' ), 10 , 3);
	$post_response['featured_image'] = 'new image';
	return $post_response;

}
add_filter( 'json_prepare_post', 'set_featured_image', 5, 3 );

**Comment by klihelp** [comment]
>> Looks like you solved your issue. Anything else needed here?
What are the chances that it remains future proof with the availability of the $wp_json_media global and $wp_json_media->add_thumbnail_data method?

**Comment by danielbachhuber** [comment]
> What are the chances that it remains future proof with the availability of the $wp_json_media global and $wp_json_media->add_thumbnail_data method?

None, we've done some substantial refactoring.
