### ISSUE TITLE
401 should be returned rather than 403 if logged out (in some places)

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#757]
Right now, we return a 403 in a lot of places, but we actually should return a 401 if no authentication is provided. This doesn't apply to all 403s, but it does apply to quite a few.

I'd suggest we add a function for this, so we could simply switch to:
```php
return new WP_Error( 'error_code', __( 'Error message' ), 'status' => json_authorization_required() );
```
with something like:
```php
function json_authorization_required() {
    return is_user_logged_in() ? 403 : 401;
}
```

**Comment by rachelbaker** [comment]
+1 on this.

@rmccue think it would be worthwhile to audit all of our HTTP status codes?
