### ISSUE TITLE
Match WP Core's permission and sticky handling for post_password

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#762]
A new (created) or updated Post with a `post_password` property requires `publish` permission.  We currently only check 'edit' permission.   

A new or updated Post with a `post_password` parameter set cannot be `sticky`

**Comment by joehoyle** [comment]
@rachelbaker why does someone need `publish` to add a password to a post? Is that just a core parity thing?

We currently check `publish` permission on create post, so I think the first condition is already done.

**Comment by joehoyle** [comment]
I don't see any evidence in core that you need publish to add a password, though let me know if I'm wrong there.

**Comment by joehoyle** [comment]
I left the published cap check in - that still needs deciding

**Comment by rachelbaker** [comment]
On the Edit Posts screen, a user has to have publish permission to be able to view and set the post_password.  https://core.trac.wordpress.org/browser/tags/4.1.1/src/wp-admin/includes/meta-boxes.php#L137

Closing this for now.

**Comment by joehoyle** [comment]
Interestingly, I couldn't find the permissions checks in the submission - core security issue maybe?
