### ISSUE TITLE
Correct search parameter for Users endpoint

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#763]
The route docs currently gives `s` as the search parameter for the /users/ endpoint, but the correct parameter is `search` per WP_User_Query: http://codex.wordpress.org/Class_Reference/WP_User_Query#Search_Parameters

**Comment by rachelbaker** [comment]
Noticed by @JasonHoffmann via Twitter: https://twitter.com/jay_hoffmann/status/551933017468731392

**Comment by danielbachhuber** [comment]
This is really two things:

* [ ] We need standardize on one "search" query argument across the board. #605
* [ ] We need to auto-generate docs from our codebase.

**Comment by JasonHoffmann** [comment]
@danielbachhuber way to up the game. Definitely need to standardize search.

**Comment by dleeward** [comment]
This is also a duplicate of https://github.com/WP-API/WP-API/issues/763

**Comment by danielbachhuber** [comment]
Handing in #924
