### ISSUE TITLE
Run on an earlier action (work without WP_USE_THEMES and avoid main query)

### ISSUE THREAD

**Issue by sebastiaandegeus** [WP-API/WP-API#764]
When `WP_USE_THEMES` is `false` no output is rendered for `/wp-json'`

Why is that? 

We're building an Angular app on top of WordPress with some plugins and this json api. The theme would be completely empty as there is no use for it.

**Comment by rachelbaker** [comment]
@sebastiaandegeus 

Well, I can speak to the question of why.  That would be because the API loading functionality uses the `template_redirect` hook:

`add_action( 'template_redirect', 'json_api_loaded', -100 );`

and WordPress has the following logic in template-loader.php:

```
if ( defined('WP_USE_THEMES') && WP_USE_THEMES )
	/**
	 * Fires before determining which template to load.
	 *
	 * @since 1.5.0
	 */
	do_action( 'template_redirect' );
```

**Comment by sebastiaandegeus** [comment]
Aha, that makes sense. 

I'll check if a theme is really needed or I can just enable the `WP_USE_THEMES` without any theme present.

**Comment by kadamwhite** [comment]
We handled this by making a "theme" that was just a static, empty index.php file that triggered a redirect. Long-term it may make sense to provide alternative ways to set up the JSON API, as I believe that "themeless" API-enabled admin sites are a useful pattern when using WP as a remote admin UI.

**Comment by danielbachhuber** [comment]
I agree — you shouldn't have to have a theme in order to use the API.

**Comment by rmccue** [comment]
We should move this hook to `wp_loaded` instead, however there may be side-effects of not running `wp()`.

**Comment by sebastiaandegeus** [comment]
You could run `wp()` inside your hooked function to make sure it ran.

**Comment by danielbachhuber** [comment]
Let's land this in `beta2` and see what breaks.
