### ISSUE TITLE
Can't block read access only, also blocks the create/edit/delete capabilities

### ISSUE THREAD

**Issue by jkohlbach** [WP-API/WP-API#765]
Hi, I'm attempting to restrict the readability of objects via the API. I don't want any Joe Bloggs being able to read my Custom Post Types specifically.

I found the filter "json_check_post_{$capability}_permission" but it appears to be a bit of a shotgun filter and wipes out the ability to create/edit/delete on Posts as well (or I'm not doing it right). Further, the API doesn't return any error messages when trying to Create saying it failed (if that is indeed the case), it does give an error during Update saying you don't have permission to read the post.

```
add_filter('json_check_post_read_permission', 'adjustReadPermissions', 10, 2);
function adjustReadPermissions($permission, $post) {
    return false;
}
```

I would have expected the above to restrict "read" permissions only on all Post objects (of all types). But still be able to "create", "edit", etc.

Appreciate any guidance or a fix if this is indeed a bug.

**Comment by rachelbaker** [comment]
@jkohlbach Great question.  

In your `register_post_type()` function include an $arg that sets the `show_in_json` parameter to false.

```
$args['show_in_json'] = false;
register_post_type ( 'your_custom_posttype', $args );
```

**Comment by jkohlbach** [comment]
Hey Rachel, thanks for that.. that removes it from showing in the API which is good.

However, when I try to Create a new post the server doesn't respond at all, I get a 500 Internal Error.

This is in the logs:
PHP Fatal error:  Call to undefined method WP_Error::set_status() in /Users/josh/web/internal-sites/touchbasemvp/wp-content/plugins/json-rest-api/lib/class-wp-json-posts.php on line 236

To be clear, creation works fine when I don't have show_in_json (or using the json_check_post_read_permission filter).

Btw, this is on the master branch as I read that was the most stable atm... just fyi

**Comment by baffleinc** [comment]
Pretty sure that this is a auth error, i.e. you're not sending your nonce through correctly!

**Comment by danielbachhuber** [comment]
Related #1167
