### ISSUE TITLE
How does withcomments filter work?

### ISSUE THREAD

**Issue by Dhaulagiri** [WP-API/WP-API#766]
I [asked about this on SO](http://stackoverflow.com/questions/27771740/return-comments-with-wp-api-post-data) and didn't get much traction, so I thought I'd ask here.  How does the `withcomments` filter work?  I assumed it would be something like `filter[withcomments]=true`, but that doesn't seem to return any results.  Here are some things I've tried:

http://climbingnarc.com/wp-json/posts/24001?filter[withcomments]=1

http://climbingnarc.com/wp-json/posts/24001?filter[withcomments]=true

http://climbingnarc.com/wp-json/posts/?filter[withcomments]=true

**Comment by danielbachhuber** [comment]
We'll address this with #924

**Comment by Chelayos** [comment]
I'm trying to display posts & comments with one api call. But this doesn't work:
`https://studyhard.tk/wp-json/wp/v2/posts/75?filter[withcomments]=1

Does "withcomments" still exist? or is there another way to display post AND comments?`

**Comment by kadamwhite** [comment]
@Chelayos Try `?_embed=1` in your request; that _ought_ to bring down all embedded data, including comments, alongside the requested post

**Comment by Chelayos** [comment]
Oh I see. Thx a lot!!
