### ISSUE TITLE
custom endpoints

### ISSUE THREAD

**Issue by dingdreher** [WP-API/WP-API#767]
hey all you wp-api devs
thx for rescuing me from writing php-templates.

i got two questions:
how have you guys thought about extending the API for plugins?
i would like to have /attachments/*id
for this plugin: https://wordpress.org/plugins/post-attached-media-downloads/

second why is the meta endpoint not public? speaking of /posts/*id/meta

thx in advance

**Comment by danielbachhuber** [comment]
Hey @dingdreher 

To answer your questions...

> how have you guys thought about extending the API for plugins?

Yep, and we'll have lots of documentation in that regard in the very near future.

> second why is the meta endpoint not public? speaking of /posts/*id/meta

Because, more often than not, post meta isn't intended to be publicly exposed. We've had to default to private.
