### ISSUE TITLE
Response code on post meta creation is 200 not 201 as per docs

### ISSUE THREAD

**Issue by jkohlbach** [WP-API/WP-API#770]
Low priority but in the documentation (http://wp-api.org/#posts_create-meta-for-a-post_input) it says to expect a 201 response code after creation, I'm seeing 200 which is fine unless you have code looking for 201 :)

I think this should be a code fix not a docs fix as it makes sense to have 201.

Branch: master

**Comment by rachelbaker** [comment]
We will address this when we rewrite the Meta endpoints.

**Comment by danielbachhuber** [comment]
This is addressed on `develop` https://github.com/WP-API/WP-API/blob/develop/lib/endpoints/class-wp-rest-meta-controller.php#L379
