### ISSUE TITLE
Can't send an array for meta value

### ISSUE THREAD

**Issue by jkohlbach** [WP-API/WP-API#772]
Submitting this as an enhancement request for consideration. It would be really great to be able to send arrays of data to in the value parameter for post meta.

Storing arrays of data in meta values is not unusual I would think. I'm getting around this by wrapping it in maybe_serialize() then base64_encoding that and then base64_decode and maybe_unserialize it on the other end. Far from ideal since I have to then hook into json_insert_post (really late because the meta is saved at 10) and rewrite the meta properly.

Since it's all JSON it should be able to handle arrays no problems so it seems like a processing issue?

**Comment by rmccue** [comment]
This is intentional. There's no way to safely send these through JSON data without causing potential security or privacy issues. See #874 for more information.

**Comment by jkohlbach** [comment]
Hey Ryan,

Thanks mate, but this isn't for retrieving meta (which that doc talks about), it's for posting... still the same issue?

Perhaps the docs should be updated there as well as it appears by the current docs that you can post and it doesn't give any errors back about it at all. It just doesn't work.

Btw, this is for authenticated users.

**Comment by rmccue** [comment]
As noted under the creation and editing sections:

> Note that the access rules for metadata apply here (see [Retrieve Meta for a Post](http://wp-api.org/#posts_retrieve-meta-for-a-post) ). Any submitted data that violates an access rule (e.g. sending serialized data) will result in a 403 error.

If it's not returning an error, that's an issue, as it definitely should.

**Comment by jkohlbach** [comment]
It was returning 403 for creation of meta if you make a call specifically to create meta. But it doesn't if you create the meta as part of the call to create a Post using the post_meta parameter.

**Comment by rmccue** [comment]
Aha, thanks for clarifying. We'll fix this up ASAP. :)
