### ISSUE TITLE
wp-json not working in my environment

### ISSUE THREAD

**Issue by martman85** [WP-API/WP-API#773]
Hi, I am developing a website with the JSON REST API and this is working great. I'm using WAMP server and set the permalinks to post name in order for the plugin to be accessed throug 'http://localhost/wp-json'.

So now I have to get this to a live environment, and this is where I am having trouble. In this environment I am using linux. In this environment the plugin does not seem to work. 

So my question: is there an environment setting that needs to be applied in order for the plugin to work? I turned on 'mod_rewrite' in httpd.conf (for apache) but this does not seem to have any effect. Any suggestions?

Thanks in forward

**Comment by kadamwhite** [comment]
do you have the same permalink settings enabled on your production site as you do locally? Check to make sure you have one of the "pretty permalinks" settings enabled, and that the rest of WP's routing is working correctly (*i.e.* that posts can be accessed at some route like :year/:month/:slug vs just ?:id). Without knowing more about your specific server setup that's my best uninformed guess.

**Comment by rachelbaker** [comment]
@martman85 Were you able to figure out the cause of this issue in your environment?

**Comment by martman85** [comment]
Yes it was an .htacces file that was not configured right in the environment. So this issue can be closed.
Thanks for your help :)

**Comment by bluest-hu** [comment]
@martman85 can you tell me how to configure  `.htacces` file, thank you!
