### ISSUE TITLE
Extra elements in route URLs

### ISSUE THREAD

**Issue by josephclawrence** [WP-API/WP-API#775]
Hi, for some reason many of my routes are getting '/wp/' inserted into them, e.g. /wp-json/wp/posts...or /wp-json/wp/taxonomies...

I am trying to work with the node.js application and I don't think it is epecting anything other than just /wp-json, so I am getting 404 errors etc. I have not attempted to change the endpoint at all, and I have tried on other sites with the same result, both sites in subdirectores of a main domain, and sites running in the route of a main domain.

I see in the source that /wp/ is often used, but I can't find anything in any documentation about this...can you help?

**Comment by rachelbaker** [comment]
@josephclawrence You must be working from the `develop` branch.  The `develop` branch is undergoing substantial changes and should not be used in production. if you want stable, "master" is your branch.  Documentation has not caught up to the develop branch.
