### ISSUE TITLE
Media Return Empty

### ISSUE THREAD

**Issue by royboy789** [WP-API/WP-API#780]
Return of newly created media item, return empty

https://github.com/WP-API/WP-API/blob/develop/lib/class-wp-json-media.php#L298

**Comment by rachelbaker** [comment]
For some reason because the `context` is set to `empty` creating a new Media resource returns an empty array.  If you change the `context` to equal `view` you get the media response object.

**Comment by BE-Webdesign** [comment]
I believe this was solved at some point.  Sending an empty context param now still returns the proper response body, due to the changes in default parameter handling.
