### ISSUE TITLE
post_date and post_date_gmt aren't set during Post creation

### ISSUE THREAD

**Issue by jkohlbach** [WP-API/WP-API#781]
Hi, during Post creation I'm having trouble setting the date of the new post.

It seems that regardless of what is passed in to the date and date_gmt parameters the system always seem to default the new Post to the current date.

**Comment by danielbachhuber** [comment]
@jkohlbach Can you share an example request, and its response? To confirm, this is with all plugins deactivated, a default theme active, and any other environmental variables disabled?

**Comment by jkohlbach** [comment]
Hey Dan, I'm really sorry.. Haven't been able to get a chance to circle back to this.

I do still have the issue, are you closing this due to me not responding? Apologies!

**Comment by danielbachhuber** [comment]
> I do still have the issue, are you closing this due to me not responding? Apologies!

Yes — feel free to reopen when you circle back on it and can be responsive in the debugging process. Thanks
