### ISSUE TITLE
Get last comments

### ISSUE THREAD

**Issue by drag0nman** [WP-API/WP-API#784]
Hello everybody,
is it possible get last comments without specify the id post?

In my website, I use bbpress forum and blog area and I use this call for get all last "news":
wp-json/posts?type[]=post&type[]=topic&type[]=reply
But in this way I can't get the last comments(comments for article in the blog). I would get it within 1 call.

Thanks

**Comment by danielbachhuber** [comment]
This is coming with #693 — there will be a `wp-json/comments` endpoint
