### ISSUE TITLE
Include hashed password in User resource

### ISSUE THREAD

**Issue by tobych** [WP-API/WP-API#785]
I'm integrating a WP site with Django. I wrote the first cut of the User resource a while back; others finished it. A client wants to have Django users' passwords sync'ed from the WP site. I can do this by getting hold of the hashed WP passwords and using a Python library to validate against them. The User resource currently doesn't include the hashed password. I'll try to submit a pull request later this weekend.

**Comment by joehoyle** [comment]
Without thinking about this in great detail - this seems like somewhat insecure. Presumably you would limit this field to only administrator authenticated requests to the api, but even then passing the password as part of the response goes above any level of functionality provided to admins in say the WordPress admin. 

I could be way off and maybe it's a legitimate thing to do, do you have any examples of other APIs that supply a hashed user's password?

**Comment by danielbachhuber** [comment]
I don't think it makes sense for the API to supported this by default either — no good can come from it. Of course, you can add the data to the response on your on site.

**Comment by tobych** [comment]
Joe, yes, only administrators would have access to hashed passwords. In fact, it would be reasonable to expect even they would need extra permissions to access these. Django, the web app framework I'm using, makes hashed passwords available by default to anyone with "Staff" privileges (one step below "Superuser". As to your question about other APIs, my understanding is that in the end a website's API, RESTful or otherwise, is typically just another view on the same data available to users with given privileges. So I can understand that given that WP doesn't make the hashed password available to users by default, you might be concerned.

However, I imagine anyone could write a plugin that gets you access to hashed passwords once it's installed. So anyone with sufficient access could install such a plugin and get hashed passwords. That's my pedantic point complete! :-)

In the interest of completeness, here's an article on figuring out passwords from their hashes, for readers who might be insufficiently alarmed by my idea: https://scottlinux.com/2013/04/23/crack-wordpress-password-hashes-with-hashcat-how-to/

**Comment by danielbachhuber** [comment]
@tobych my two cents: you as a developer should be able to add hashed passwords to the User resource. WP-API shouldn't ship this by default because there isn't much reason to.

**Comment by rmccue** [comment]
This is definitely not something we want in the API core.

While the passwords themselves are hashed, exposing these hashes allows offline attacks to be performed, including brute forcing and such. While there are a number of mitigations possible for online attacks (limiting login requests, e.g.), it's not possible to do the same for offline attacks, so you need to rely on the security of the hashes themselves instead.

If you need to add this, it should be possible to do so (right now, `json_prepare_user` should let you, I think), but be very *very* careful doing so.
