### ISSUE TITLE
Normalize endpoint query parameters where needed to match response fields.

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#791]
When allowing the passage of query parameters to a collection endpoint adjust them to match our response fields.  Specifically related to `orderby` or other query args that may use an internal field.

Example GET /comments endpoint should "normalize" a passed `orderby` parameter so `date_gmt` can be provided instead of the internal prefixed property `comment_date_gmt`

related: https://github.com/WP-API/WP-API/pull/693#discussion-diff-23180420

**Comment by danielbachhuber** [comment]
Related #924

**Comment by danielbachhuber** [comment]
This is largely handled in #924
