### ISSUE TITLE
Cannot extend API. Followed guide, getting error.

### ISSUE THREAD

**Issue by brian2000** [WP-API/WP-API#792]
Hi 
I've tired to extend using your guide and I cannot seem to get past the following error:

Catchable fatal error: Argument 1 passed to WP_JSON_CustomPostType::__construct() must implement interface WP_JSON_ResponseHandler, none given,

I followed the code here (both approaches): http://wp-api.org/guides/extending.html#registering-your-endpoints

I followed the documentation exactly so this leads me to believe that something is wrong or missing in the doc or the code.

**Comment by danielbachhuber** [comment]
Hi Brian,

The documentation is out of date at the moment. In the very near future, we'll update the documentation to include a proper guide to extending our new `WP_JSON_Controller` class.

Thanks for your patience.
