### ISSUE TITLE
exposing trashed posts in the API

### ISSUE THREAD

**Issue by sebastiaandegeus** [WP-API/WP-API#795]
Right now trashed posts are excluded from public get requests. But how do I expose these hidden posts for admin/editor users?

Some background info: we will use WP to edit the content and expose the API in a private network where only the other application has access to the API endpoints.

**Comment by rmccue** [comment]
`filter[post_status]=trash` should give you access to this, assuming you have the `edit_posts` capability.

(Note that this will instead be `status=trash` on `develop`, the v2 branch.)

**Comment by sebastiaandegeus** [comment]
So requests like these should be made + auth ?

**Comment by robertglez** [comment]
@sebastiaandegeus did you manage to expose trashed posts?

I've tried what @rmccue describes but posts with trash status are not listed whether authenticated or not. Endpoint /posts/statuses does not display trash status as one of the available statuses either.

Thank you,

Robert
