### ISSUE TITLE
Can't retrieve media for a post

### ISSUE THREAD

**Issue by crisanders** [WP-API/WP-API#797]
We're using the WP API plugin to power our iOS app and we're having a hard time with some things, the most important one being the retrieval of media.

We tried to use the wp-json/media/<id> and GET /media?filter[post_parent]=<id>

but it returns a list of posts that have nothing to do with the post that I am trying to get the slideshow URLs for.

So basically we are trying to get an array of URLs so we can add the photo gallery attached to an article.

http://www.bmwblog.com/wp-json/media?filter[post_parent]=<id>

I guess do we need to add a filter 'post_parent' to json_query_vars? Or is this a known bug?

**Comment by crisanders** [comment]
Almost a month and no one has the same issue? How do you guys get the media attached to a post?

**Comment by jmca** [comment]
@crisanders I'm having the same issue trying to get parent pages. `wp-json/pages?filter[post_parent]=0` returns *all* pages. I was expecting an array of top-level pages.

**Comment by danielbachhuber** [comment]
@jmca See https://github.com/WP-API/WP-API/issues/806#issuecomment-75857698

**Comment by danielbachhuber** [comment]
We're revisiting these query params in #924
