### ISSUE TITLE
Problem with creation of new user

### ISSUE THREAD

**Issue by drag0nman** [WP-API/WP-API#798]
I have followed the documentation for creating a new user.
I called {/users} with POST verb and the JSON in input was {”username”:”newuser”,”name”:”New User”,”password”:”secret”}

I got this:
[
    {
        "code": "json_missing_callback_param",
        "message": "Missing parameter data"
    }
]

I did some debug tests, and I found in the code(lib/class-wp-json-users.php) that the required data are:  'username', 'password', 'email'. So I added the field 'email' in input JSON but I got the same error message.

In my debug test I have tried to change the error message, in row (259, lib/class-wp-json-users.php) but the message continued still not changed.

**Comment by rachelbaker** [comment]
@drag0nman Do you have the the HTTP header Content-Type: application/json ?
