### ISSUE TITLE
Filters are not working (/?json route=/posts&filter[])    ApiVersion 1.1.1

### ISSUE THREAD

**Issue by RuSTer1241** [WP-API/WP-API#799]
Filter feature doesn't work for me. 
I checked https://wordpress.org/support/topic/filter-request-returning-error
and 
http://stackoverflow.com/questions/26608048/wp-json-api-request-doesnt-accept-query-parameters
but didn't find decision.
When I used: .../?json_route=/posts&filter[search]=s
 I got: 'filter[search]' is not recognized as an internal or external command, 

When I used: /?json_route=/posts?filter[search]=s
 I got: [{"code":"json_no_route","message":"No route was found matching the URL and request method"}]

Have you any decision for this issue?

**Comment by drag0nman** [comment]
Hello,
You should use: /posts&filter[s]={SOMETHING_TO_SEARCH}

**Comment by RuSTer1241** [comment]
Hello!
request:
curl -i http://xxxxxx.com/?json_route=/posts&filter[s]={java}
Answer:
All posts content array and error:
'filter[s]' is not recognized as an internal or external command,
program or batch file.
So, it is not decided. Have any other ideas?

**Comment by drag0nman** [comment]
Sorry,
I wrote wrong.
The correct way is: /posts?filter[s]={SOMETHING_TO_SEARCH}

**Comment by RuSTer1241** [comment]
>curl -i http://*****.com/?json_route=/posts&filter[s]={java}
'filter[s]' is not recognized as an internal or external command,
operable program or batch file.

**Comment by RuSTer1241** [comment]
request:     curl -i http://interviewinit.com/?json_route=/posts?filter[s]={equal}
answer:
[{"code":"json_no_route","message":"No route was found matching the URL and request method"}]

**Comment by rmccue** [comment]
> 'filter[s]' is not recognized as an internal or external command,

You need to quote the URL when performing requests from the command line:

```
curl -i "http://example.com/?json_route=/posts&filter[s]=java"
```
