### ISSUE TITLE
All API endpoints return 404 after updating Pods

### ISSUE THREAD

**Issue by Shelob9** [WP-API/WP-API#801]
I am posting this issue here, so it will be easier for anyone affected by it to find the solution.

When updating to Pods 2.5.1, and most likely some other recent versions, /wp-json and all REST API endpoints will return 404.

A quick fix for this issue is to resave permalink settings.

We have patched this issue and the fix will be included in Pods 2.5.2.

https://github.com/pods-framework/pods/issues/2642
https://github.com/pods-framework/pods/pull/2644

**Comment by danielbachhuber** [comment]
Thanks @Shelob9
