### ISSUE TITLE
Post Properties such as slugs and authors are not set as expected during create/update

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#803]
We need to use the `wp_insert_post_data()` filter so certain post properties like `post_author` or `post_name` (slug) can be set or updated as expected.  Without this filter properties are overridden by defaults.

**Comment by rachelbaker** [comment]
Originally reported by Jared Smith via Slack: https://wordpress.slack.com/archives/core-restapi/p1421879421000715

Examples that reproduce this issue:

**Example One**
1. Create or update a post setting the post_author to 0.
2. Notice the post_author will not be 0 as expected, it will instead be the user_id of the current user.

**Example Two**
1. Create a post and publish it.
2. Update the same post with a new title and new slug.
3. Notice the title did change, but the slug (aka `post_name`) did not.  

The question is **are these oddities that we support**?  Or do we require the end user to add their own `wp_insert_post_data()` filter?

**Comment by rmccue** [comment]
> 1. Create or update a post setting the post_author to 0.
> 2. Notice the post_author will not be 0 as expected, it will instead be the user_id of the current user.

This is the same as WP core; 0 is treated as an empty value. As far as I can tell, it's not possible to set the author to 0 via `wp_insert_post`...

> 1. Create a post and publish it.
> 2. Update the same post with a new title and new slug.
> 3. Notice the title did change, but the slug (aka post_name) did not.

This is strange... I'm not sure I understand why this occurs?

**Comment by rachelbaker** [comment]
Closing this issue for now.  I figured out the cause of the post slug issue, and it was related to using a numeral in the slug, and not API related.
