### ISSUE TITLE
Get attachments

### ISSUE THREAD

**Issue by KuneStudio** [WP-API/WP-API#806]
I tried to call the post type attachment to get media with a parent ID but it always return []
Wondering why and if anyone found a way to get the attachment of a post.
Thanks !

**Comment by crisanders** [comment]
You might have the same issue I do

https://github.com/WP-API/WP-API/issues/797

**Comment by danielbachhuber** [comment]
@KuneStudio @crisanders which version of the API are you using?

**Comment by crisanders** [comment]
This one https://wordpress.org/plugins/json-rest-api/

**Comment by KuneStudio** [comment]
Same here, version 1.1.1.

**Comment by doppiaeast** [comment]
Any solution on this? I'm curious if this is possible as well.

**Comment by danielbachhuber** [comment]
Sorry about this. The problem is the same as https://github.com/WP-API/WP-API/issues/921#issuecomment-75742696

You'll need to register the query var:

```
add_filter( 'query_vars', function( $vars ){
    $vars[] = 'post_parent';
    return $vars;
});
```

**Comment by crisanders** [comment]
Do we register this in the functions.php of the theme?

**Comment by danielbachhuber** [comment]
> Do we register this in the functions.php of the theme?

Sure, that's a fine place for it.

**Comment by crisanders** [comment]
Added the filter at the bottom of functions.php

So is this the right call to get the attachments for a photo gallery?

http://bmwblog.com/wp-json/media?filter[post_parent]=150378

**Comment by danielbachhuber** [comment]
Should be — not sure why it's not working for me atm.

**Comment by crisanders** [comment]
Can you try one more time now? I refreshed the cache. 

I also tried this http://www.bmwblog.com/wp-json/media/150378

[{"code":"json_post_invalid_type","message":"Invalid post type"}]

**Comment by danielbachhuber** [comment]
> Can you try one more time now? I refreshed the cache.

Cool. Looks like it works.

**Comment by crisanders** [comment]
So one more question for you. The developer says he needs an array of urls, the previous call would return a bunch of URLs for more posts, not the one called. 

Is this good enough now?

**Comment by danielbachhuber** [comment]
> The developer says he needs an array of urls, the previous call would return a bunch of URLs for more posts, not the one called.
> 
> Is this good enough now?

Sorry, I can't comment on whether this meets your project requirements or not.

**Comment by crisanders** [comment]
It's cool. I'm sure this is fine. Thanks again for your help.

**Comment by danielbachhuber** [comment]
We're revisiting these query params in #924
