### ISSUE TITLE
Non-query API endpoints don't work with sites in subdirectories

### ISSUE THREAD

**Issue by jzellis** [WP-API/WP-API#808]
Hi there! I seem to be having trouble installing WP-API into a WordPress install that's in a subdirectory on my localhost. Querying via URL query works, but the URL rewrite seems to fail, though I've made sure I've got pretty permalinks on. For example: http://localhost/site/posts doesn't work, but http://localhost/site/?json_route=/posts does. (Though filtering doesn't seem to work with the query string, though I'm not sure if I'm just not doing it right: ?json_route=/posts&filter[post_type]=page simply returns the posts, not the pages.)

Is there something else I need to be configuring here? I'd be happy to do the Vagrant/Virtualbox/Chassis thing, but I'm running Ubuntu in chroot on a Chromebook and there's like hours of kernel compiling involved to get Virtualbox running under a chroot and frankly I don't have the inclination just to make a friggin' Wordpress installation I can do in thirty seconds with my existing LAMP stack.

Thanks!

**Comment by modemlooper** [comment]
Correct api url should be  http://localhost/site/wp-json/posts

**Comment by jzellis** [comment]
I tried that as well, no luck. Do I need to mess with my .htaccess file somehow? Or is the problem that the site's in a subdir instead of the root dir?

**Comment by rmccue** [comment]
You definitely should be able to get this working in a subdirectory; do normal pretty permalinks work for your site? Using `/wp-json/...` requires having those switched on.

> (Though filtering doesn't seem to work with the query string, though I'm not sure if I'm just not doing it right: ?json_route=/posts&filter[post_type]=page simply returns the posts, not the pages.)

The post type happens to be a special one; try `filter[s]=search+term` instead to check.

**Comment by clakeb** [comment]
I'm also experiencing this problem. I'm using VVV as my localhost and using WP in a subdirectory.

**Comment by scottopolis** [comment]
I noticed this issue in a client site, and I resaved the permalinks as day and name, then went back to post name and it started working. No idea why, or if this is a real fix, but just thought I'd post it.

**Comment by clakeb** [comment]
Maybe this has something to do with VVV as this is working in production (kind of) for me. I use a server managed with ServerPilot to test things. Maybe it has to do with their setup vs. VVV. I'll try to explore this further and come up with an explanation.

**Comment by michaelperrin** [comment]
I am using WP-API 2.0beta 4, and I have the same issue.

I have Wordpress in a subfolder at `http://mydomain.localhost.com/wordpress` and calling `http://mydomain.localhost.com/wordpress/wp-json/wp/v2/posts` returns a 404.

If I create a dedicated subdomain for wordpress (no subdirectory then), WP-API works again.

**Comment by duhaime** [comment]
In case others end up here looking to configure the WP REST API in a subdirectory, I wanted to send a quick note. I had a CentOS instance with httpd installed, and my setup looked like: 

```
└── /var/www/html/ (the web server's document root)
    ├── .htaccess (htaccess originally installed by wordpress)
    ├── index.html (client side entry point)
    ├── index.js (client side js)
    ├── index.css (client side styles)
    └── wordpress (admin wordpress subdirectory)
        ├── index.php
        ├── wp-admin
        ├── wp-content
        └── (...the rest of the top-level wordpress install files)
```

My client side application opened fine at my ip address, and the wp files opened fine at my ip address/wordpress/wp-admin, but the API sent 404 responses until I modified the .htaccess file in /var/www/html to look like this:

```
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /wordpress/index.php [L]
</IfModule>

# END WordPress
```

This change helped resolve the API's 404's, which couldn't find index.php (as it was located in the wordpress subdirectory). The change simply indicates where that index.php file can be found. I hope this helps someone else!

**Comment by jkrbrn** [comment]
Same issue, partially resolved with @duhaime's solution above, thank you for that.

However I have multiple WP instances: 

http://staging.site.com/site1
http://staging.site.com/site2
http://staging.site.com/site2

Is there a potential wildcard solution?

I have tried 

```
 # BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /(.*)/index.php [L]
</IfModule>
# END WordPress
```

with a few variations with no success. Any point in the right direction would be v.appreciated
