### ISSUE TITLE
Readme Clean-up and Improvements Placeholder

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#809]
**GOAL:** Make a good first impression and offer friendly useful advice to folks visiting the WP-API repository looking to get started with the plugin. 

Some initial ideas for discussion/feedback:

- [ ] Replace the contents of the Quick Setup with less Chasis specific language. 
- [ ] Replace Testing section with a reworked **Contributing** section.  Include a link to CONTRIBUTING.md.
- [ ] Move contents of current Testing section to the CONTRIBUTING.md file with less Chasis specific language about how to run the unit tests.  
- [ ] Create new **Authentication** section with links to authentication plugins.
- [ ] Add **Licence** section to the bottom with link to GPL (I assume?) license.

**Comment by rachelbaker** [comment]
@WP-API/amigos What do you think we can do to improve our Readme file?

**Comment by joehoyle** [comment]
I think some code examples, perhaps using cURL would be good too. Also, potentially a small section on creating custom endpoints
