### ISSUE TITLE
Post_type filter parameter not respected

### ISSUE THREAD

**Issue by joshlevinson** [WP-API/WP-API#810]
Docs state that `post_type` is allowed in the `filter` parameter of the `/posts` endpoint.
This is not respected; only the `type` (as its own parameter outside of `filter`) is used for determining post types.
For example, `wp-json/posts?filter[post_type]=page` returns the same results as `wp-json/posts?filter[post_type]=post`

I assume this is intended, and that it is the docs that need to be changed.

**Comment by romuloctba** [comment]
indeed

**Comment by danielbachhuber** [comment]
We'll be dropping filtering based on type in 2.0. Each post type will have its own endpoint. See #820 for more.

We'll update the docs when things have stabilized.
