### ISSUE TITLE
Allow for 'any' type

### ISSUE THREAD

**Issue by joshlevinson** [WP-API/WP-API#811]
Currently, the `/posts` api [does not allow](https://github.com/WP-API/WP-API/blob/develop/lib/class-wp-json-posts.php#L211-L215) for queries to be done for `any` post type, though `WP_Query` does.

I propose that this restriction be lifted.

**Comment by kadamwhite** [comment]
This tripped me up, too -- I'd be in favor of that

**Comment by danielbachhuber** [comment]
@joshlevinson @kadamwhite Can you explain in greater detail why you want multiple types of resources from one request? Use cases are helpful.

**Comment by danielbachhuber** [comment]
This won't be happening in core endpoints, although you're welcome to create your own for it.
