### ISSUE TITLE
JSON object only pulls 12 items

### ISSUE THREAD

**Issue by martman85** [WP-API/WP-API#812]
Hey Everyone,

I am using the WP-JSON plugin. This is working great except for one thing: I have a product overview with 20-something items. And I want to pull all of those items from the JSON file. In my case from 'wp-json/posts?type=product'. 
The problem is that this only displays 12 items, even when there are a lot more in the Wordpress admin. Does anyone know what could be causing this issue, and how to fix it?

Thanx in forward!

**Comment by inverse** [comment]
This is the `WP-API` plugin are you sure it's the correct one?

In this plugin the data is paginated (via link header) and you can view the total number of `posts` via the `X-WP-Total` header.

**Comment by martman85** [comment]
Thank you. This was the solution. As soon is I set the number of posts displayed to 1000, all my products show on my page.
