### ISSUE TITLE
Login / Logout using nonces throws invalid nonce error

### ISSUE THREAD

**Issue by miczed** [WP-API/WP-API#814]
Hi

I am using WP-API with an Angular JS Frontend. I am generating nonces for my request headers as described in your documentation (http://wp-api.org/guides/authentication.html):
```php
wp_localize_script(
        'smedex-js',
        'myLocalized',
        array(
            'partials' => trailingslashit( get_template_directory_uri() ) . 'partials/',
            'api_url' => get_site_url().'/wp-json/',
            'nonce' => wp_create_nonce( 'wp_json' ),
            'user' => $user
            )
    );
```
I tried to extend the WP-API so I can login and logout users by calling an API endpoint:

Login:
```php
public static function user_login($data) {
			$user = wp_signon( $data,false );
			if ( is_wp_error($user) ) {
				return new WP_Error( 'json_signon_login_failed', __( 'Login failed. Please check if username and password are correct.' ), array( 'status' => 404 ) );
			} else {
				$data = new StdClass();
				$data->user = new StdClass();
				$data->user = $user;
				$data->nonce = wp_create_nonce( 'wp_json' );
				$response = new WP_JSON_Response();
				$response->set_status( 201 );
				$response->set_data ($data);
				//$response->header( 'Location', json_url( '/posts/' . $id . '/meta/' . $result ) );
				return $response;
			}
		}
```
Logout:
```php
public static function user_logout() {
			wp_logout();
			$nonce = wp_create_nonce( 'wp_json' );
			return $nonce;
		}
```

The login / logout process is working fine, however when I try to login again after I logged out I get the following error message:

```javascript
code: "json_cookie_invalid_nonce"
message: "Cookie nonce is invalid"
```
When I reload the whole page everything works fine again.

Am I missing something? 
What's the best way to login / logout users via the WP-API?
Thank you for your help

Kind regards
Michael

**Comment by danielbachhuber** [comment]
Hm. I'm not sure how I feel about being able to log a user in or out via the API. REST interactions are [intended to be stateless](http://stackoverflow.com/questions/13916620/rest-api-login-pattern) — every request should include all of its necessary data.

By the way, nonces are just used for CSRF — cookies provide the authentication.

If you're using cookie-based authentication and your user needs their cookies, you can redirect them to a signup form where they can sign in. I think it's proper to have sign-in independent of the API.

cc @joehoyle who probably has more opinions in this matter.

**Comment by miczed** [comment]
Thank you Daniel for your reply.

So instead of signing the user in via the API I should create a standalone page, which takes care of the login process and then redirects the user to my Angular JS Frontend after he signed in?

The Angular JS Frontend then gets the nonce and the user object through wp_localize_script and WP-API knows that the user is signed in, because of the cookie authentication? 

If the user makes a call to the API and isn't logged in, I get an error response code and make a redirect from my Angular JS Frontend to my signup page?

Sorry for all the questions but I am very new to the whole RESTful API concept and need to make shure that the authentication process is secure.

**Comment by danielbachhuber** [comment]
> So instead of signing the user in via the API I should create a standalone page, which takes care of the login process and then redirects the user to my Angular JS Frontend after he signed in?

Yes, this is what I would do and recommend.

> The Angular JS Frontend then gets the nonce and the user object through wp_localize_script and WP-API knows that the user is signed in, because of the cookie authentication?
>
> If the user makes a call to the API and isn't logged in, I get an error response code and make a redirect from my Angular JS Frontend to my signup page?

Exactly.

**Comment by royboy789** [comment]
Just to put in my 2 cents.. I get the whole stateless thing, but for UX reasons if you have a certain sign-on funnel it is useful to have the login. 

I tried going Social Login -> User Login -> Create New Nonce -> Get User data, but nonce kept failing.

I solved my use case by using a JS location (or $location in Angular) redirect and passing in a variable for where to redirect to, all in AngularJS.. its not ideal, but works.

**Comment by rmccue** [comment]
Logging users in/out via the API isn't something we should add, as it encourages the use of usernames and passwords outside of the WP login screen. The only time a user should ever enter their details is on that screen, and we make conscious decisions to encourage that.

If you want to get a login URL that brings the user back, you can direct them to `wp-login?redirect_to=<url>`, however this URL *must* be on the same site. (You can get that URL in WP plugins/themes via `wp_login_url( $redirect )`)
