### ISSUE TITLE
Broken Link in Docs

### ISSUE THREAD

**Issue by zanematthew** [WP-API/WP-API#817]
Not sure if this is the right place for this, but in the [editing and creating post](http://wp-api.org/guides/getting-started.html#editing-and-creating-posts) section the link for Authentication is broken. It goes to: http://wp-api.org/authentication.html, but it should go here: http://wp-api.org/guides/authentication.html

**Comment by danielbachhuber** [comment]
Submit a pull request? https://github.com/WP-API/WP-API.github.io

I'm not quite sure which link you're referring to.

**Comment by rmccue** [comment]
Fixed in WP-API/WP-API.github.io#38

**Comment by zanematthew** [comment]
@danielbachhuber Thanks for pointing in the direction, hadn't realized that was the repo for the docs, @rmccue thanks for updating as well.
