### ISSUE TITLE
Link README to docs

### ISSUE THREAD

**Issue by franz-josef-kaiser** [WP-API/WP-API#819]
Nowhere in the docs is a link to `wp-api.org`. That should actually be a super awesome, big a$$ h1 link.

**Comment by pollyplummer** [comment]
It's in the About section of the readme - "Check out our documentation for information"

**Comment by franz-josef-kaiser** [comment]
I'd use the following as link container (aside from adding a link to the description):

# JSON REST API (WP-API)

**Comment by danielbachhuber** [comment]
I've added a link in fcbd260c11265ab06d2d16acec2729dc8967d636
