### ISSUE TITLE
In WP_JSON_Posts->prepare_post(), global $post unset before apply_filters() call

### ISSUE THREAD

**Issue by ericandrewlewis** [WP-API/WP-API#822]
I'm manipulating the post_content in a callback hooked onto `json_prepare_post`. In my callback, I apply the_content filter, but oembed doesn't seem to be running.

I traced this to the fact that `global $post` is null, which is unset before the `json_prepare_post` filter is hit([1](https://github.com/WP-API/WP-API/blob/1.1.1/lib/class-wp-json-posts.php#L841)), mixed with the fact that WordPress' oembed handling will only take place if the `$post` global is set.

I'd suggest running the filter before returning the `global $post` state to its previous.

**Comment by rachelbaker** [comment]
Leaving this issue open, to test in the new Posts Controller.

**Comment by rachelbaker** [comment]
Checked the develop branch and we aren't unsetting the $post global before the json_prepare_post filter.  
Closing issue.
