### ISSUE TITLE
Installation on WAMP

### ISSUE THREAD

**Issue by vinayakshukre** [WP-API/WP-API#828]
I am new to wordpress and installing plugins on it. I installed WP JSON API plugin on my local laptop installation of WAMP server and I am trying to access posts with URL like http://localhost/mysite/wp-json/posts  but that does not work. It says this URL is not found. Am I using right URL? if yes, then is this plugin not supported on WAMP server . I can see in wp-admin of mysite that "This plugin has not been tested with your current version of WordPress."

Suggest me documentation of minimum requirements to use this plugin? If this is not right place to ask this question then also suggest right place. Thanks a ton in advance.

**Comment by kadamwhite** [comment]
Do you have [Pretty Permalinks](http://codex.wordpress.org/Introduction_to_Blogging#Pretty_Permalinks) turned on? If not, you can check to see if the API is working by visiting e.g. `http://localhost/mysite?json_route=/posts`. Hope that helps; if not, let us know!

**Comment by vinayakshukre** [comment]
Thanks. I was using wrong URL. Thanks for correcting my URL. Probably pretty permalinks were already on. Thanks a ton.

**Comment by kadamwhite** [comment]
Happy to help! It sounds like things are working now, so I'm going to close the issue—please leave a comment if that's not the case. Thanks!

**Comment by locnguyendev** [comment]
Hi everyone, 
So, I have downloaded plugin wp-api and manual install in my local wamp server. Next, I was tried to fetch data via link as "http://localhost/mysite?json_route=/posts" but I can't get posts data unless this json data (I was change my permalink into pretty permalink , type "Day and name"):
[{
    "code": "json_no_route",
    "message": "No route was found matching the URL and request method",
    "data": 
        {     "status": 404        }
}]
Please suggest me ways to get data as document guide. Thanks a lot!
