### ISSUE TITLE
401 Unauthorized after all oauth authorizations were ok

### ISSUE THREAD

**Issue by alordiel** [WP-API/WP-API#834]
Hello,

We are building a mobile app for a WordPress site and using WP-API and Oauth1.0a for logging. 
The logging itself goes well but when we try to get to users/me it dumps 401 - Unauthorized.
This is how we try to get the current user info. 
```javascript
$(document).on('click', '#tst', function() {

    request_data = {
        url: base_url + "users/me",
        method: 'GET',
        data: {
            oauth_token: oauth_token,
        }
    };
    
    token = {
        public: oauth_token,
        secret: oauth_token_secret
    };

    $.ajax({
        url: request_data.url,
        type: request_data.method,
        headers: oauth.toHeader(oauth.authorize(request_data, token))
    }).done(function(data) {
        alert("It's Done!");
    });

});
```
Is there something that we are missing?

**Comment by danielbachhuber** [comment]
`users/me` requires the logged-in user context: https://github.com/WP-API/WP-API/blob/develop/lib/class-wp-json-users-controller.php#L74

It doesn't appear the oAuth1 client sets the user context: https://github.com/WP-API/OAuth1/search?utf8=%E2%9C%93&q=wp_set_current_user

**Comment by alordiel** [comment]
hm... that is something new or i have missed it in the documentation. So how i can add the user context. As i read some of the code ```wp_set_current_user``` has to do something with the nonce, but how can i send the nonce as well?

Here is my code in full just to have the how picture.
```javascript
$(document).on('click', '#login', function() {
    
	//oauth-1.0s.js init
    var request_data = {
        url: address + "oauth1/request",
        method: 'POST',
        data: {
            status: "request1"
        }
    };
    
    $.ajax({
        url: request_data.url,
        type: request_data.method,
        data: oauth.authorize(request_data),
        json: true
    }).done(function(data) {
        request_token = data.slice(data.indexOf("=") + 1, data.indexOf("&"));
        request_token_secret = gup('oauth_token_secret', data);
        window.open(address + "oauth1/authorize?oauth_token=" + request_token + "&oauth_callback=" + current_url, "_self");
    });  
});

if( referrer.slice(0, addressLength) === address ) {

    temp_token = gup('oauth_token', current_url);
    verifier = gup('oauth_verifier', current_url);
    
    request_data = {
        url: address + "oauth1/access",
        method: 'POST',
        data: {
            oauth_token: temp_token,
            oauth_verifier: verifier
        }
    };
    
    $.ajax({
        url: request_data.url,
        type: request_data.method,
        data: oauth.authorize(request_data)
    }).done(function(data) {
        oauth_token = data.slice(data.indexOf("=") + 1, data.indexOf("&"));
        oauth_token_secret = gup('oauth_token_secret', data);
    });
};

$(document).on('click', '#tst', function() {

    request_data = {
        url: base_url + "users/me",
        method: 'GET',
        data: {
            oauth_token: oauth_token,
        }
    };
    token = {
        public: oauth_token,
        secret: oauth_token_secret
    };

    $.ajax({
        url: request_data.url,
        type: request_data.method,
        headers: oauth.toHeader(oauth.authorize(request_data, token))
    }).done(function(data) {
        alert("It's Done!");
    });

});
```

**Comment by danielbachhuber** [comment]
I'm not 100% familiar with the code, to be honest. I'll need to get up to speed on the authorization workflow before I can comment further. Or, @rmccue or @rachelbaker might have some pointers.

**Comment by rmccue** [comment]
> I'll need to get up to speed on the authorization workflow before I can comment further.

It works via the `determine_current_user` filter, which is called via `get_currentuserinfo` to set the user (rather than overriding it later).

> The logging itself goes well but when we try to get to users/me it dumps 401 - Unauthorized.

There should be further information in the body of the response as to what error you're getting (such as `Missing OAuth parameter oauth_signature`). It's possible that the server you're speaking to strips the Authorization header out; newer versions of the OAuth plugin are more robust at pulling this out.

**Comment by alordiel** [comment]
Sorry to bringing this back for security reasons we are again trying to run the app with oAuth1.0a. And again we hit the same 401 Error. The response is:
```javascript
[{"code":"json_not_logged_in","message":"You are not currently logged in."}]
```
We get this on quering `http://sitename.com/wp-json/users/me` after we have successfully passed the
passed the authorization step (or at least we thing that we had passed it successfully) `http://sitename.com/?oauth_token=FXHzf5kCINgrla9X8LLmX8EA&oauth_verifier=qzGhCJeOzIoqn998fRsU1g5r&wp_scope=*`

**Comment by seanfisher** [comment]
I'm getting the same error on the same endpoint:

    [{"code":"json_not_logged_in","message":"You are not currently logged in."}]

even after going through the whole OAuth1.0a flow and receiving an access token. The Authorization header on the request is:

    Authorization: oauth_consumer_key="Ivwht8HgLVAj", 
        oauth_nonce="6sJKCoslvmcKMPT3QZySXAbNjaGOgj6Y", 
        oauth_timestamp="1434140543895", 
        oauth_signature_method="HMAC-SHA1", 
        oauth_token="nXkLpfPNfJsEe5zKrUPgKrem", 
        oauth_version="1.0", 
        oauth_signature="nN5gXNuDtnEi6TjrOMJKSft86Rk%3D"

Any ideas on this issue would be appreciated.
