### ISSUE TITLE
Expose basic details for users with published posts

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#839]
`GET /wp/users` currently requires a user to have `list_users` cap. We should expose all users who have any published content for public post types.

Core doesn't have a sane way to query this, me thinks :(

#838 implements this for `GET /wp/users/<id>` for published posts, but we should support all post types.

**Comment by TimothyBJacobs** [comment]
I think something like this could work, basic and untested.

````php
$types = get_post_types( array( 'public' => true ) );
$types = implode( $types, ', ' );
````
and the sql.
````sql
SELECT `post_author` FROM `wp_posts` WHERE `post_type` IN ( $types );
````

**Comment by danielbachhuber** [comment]
Another consideration: performance. Our queries should be behind some basic object cache so we don't make the same query over and over

**Comment by rmccue** [comment]
> Core doesn't have a sane way to query this, me thinks :(

Can we use `get_users( [ 'who' => 'authors' ] )` ? Not sure if that's robust enough.

**Comment by rmccue** [comment]
> Not sure if that's robust enough.

Ah, checking the source reveals that it's any user with a user level > 0, so could be too much.

**Comment by rachelbaker** [comment]
Punting to Beta 2.

**Comment by joehoyle** [comment]
Currently we allow `/users/<id>` for any author that has a published post of post_type = post. I'd recommend we use `get_posts_by_author_sql` to get those users and roll with that.

**Comment by rmccue** [comment]
Our issue is that we don't really want to do SQL queries in the API, since it doesn't belong there. What we need is a way for `WP_User_Query` to use `get_posts_by_author_sql` for the query rather than just allowing sorting by it. This also means that it works nicely with `wp_is_large_network`, any caching layers that may be in place with user query filters, etc.

**Comment by joehoyle** [comment]
Trac ticket: https://core.trac.wordpress.org/ticket/32250#comment:8 looks to be making some progress.

**Comment by rachelbaker** [comment]
Trac Ticket is making progress, but punting to Beta 3 to see how this pans out.

**Comment by johnbillion** [comment]
https://core.trac.wordpress.org/ticket/32250 is in.

**Comment by joehoyle** [comment]
Will handle a PR for this by tomorrow, so leaving in b3 for now.
