### ISSUE TITLE
Add `wp/users/{id}/posts` Route Referenced in _links[archive] 

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#843]
Add a route to match the archive link (wp/users/{id}/posts) that basically is a redirect to wp/posts?author={id}

Discussed in Slack Channel: https://wordpress.slack.com/archives/core-restapi/p1419895443001608

**Comment by danielbachhuber** [comment]
Shouldn't it be `wp/v2/users/<id>/wp/v2/posts`? Otherwise the nature of the redirect would change when the API is versioned.

**Comment by rachelbaker** [comment]
Punted to Beta 4

**Comment by danielbachhuber** [comment]
I think we should use `https://api.w.org/items` as the link.

The question is: which post types do we link to?

**Comment by danielbachhuber** [comment]
Wontfix on this for now.
