### ISSUE TITLE
Permanent build failure for PHP 5.2

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#846]
Travis no longer supports: https://github.com/travis-ci/travis-ci/issues/3152#issuecomment-72238345

**Comment by rmccue** [comment]
This has happened a few times before, and I've just jumped into their IRC room each time to chat about it. Given that WP still supports 5.2 (and it's one of the main reasons that testing is so useful), we should fix it in Travis. :)

**Comment by danielbachhuber** [comment]
Thanks Ryan

**Comment by danielbachhuber** [comment]
Should we comment out 5.2 in the interim?

**Comment by rmccue** [comment]
> Should we comment out 5.2 in the interim?

I'm OK with that, since our tests will be useless otherwise.

**Comment by rachelbaker** [comment]
Looks like PHP 5.2 support will be back tomorrow.

> We'll be rolling out a new image containing 5.2.17 on February 12th around 15:00 UTC.

https://github.com/travis-ci/travis-ci/issues/3152#issuecomment-73996867
