### ISSUE TITLE
Any relation between master branch and wp.org plugin?

### ISSUE THREAD

**Issue by vlood** [WP-API/WP-API#851]
I know this repo is related to the json-rest-api plugin, but I can't find much in common between MASTER and the code of the plugin. I know the plugin is said to be "a stable version", although it's about 7 months behind in development. DEVELOP branch is the most active, but still useless for production.

Is MASTER stable? Can it be used? Which one should we use for production and which one should we use for contributing to the project here? Some insight on these questions will be greatly appreciated :)

**Comment by danielbachhuber** [comment]
Master branch is just a few issues away from being released as 1.2: https://github.com/WP-API/WP-API/milestones/1.2

You should use `master` for production for the time being. However, `develop` is under the most active development, as you noted, and should soon be ready for everyone to start using as an alpha / contributing back to.
