### ISSUE TITLE
Order and orderby not changing results

### ISSUE THREAD

**Issue by tmyie** [WP-API/WP-API#852]
Hey,

Love the plugin.

However, I'm having trouble when sorting the results of the query (with the title of a custom taxonomy). 

Here's my query:

/wp-json/posts/type=client&filter[taxonomy]=clients&orderby=title&order=ASC&filter[posts_per_page]=-1&filter[term]=advertising

However, it's not ordering by the taxonomy title nor alphabetising anything. Any idea why, and is this possible?

**Comment by danielbachhuber** [comment]
> However, it's not ordering by the taxonomy title nor alphabetising anything. Any idea why, and is this possible?

`filter[orderby]=title` orders by post title. Ordering by taxonomy title isn't possible.
