### ISSUE TITLE
Post Meta / Authentication - Update Docs / Enable certain meta fields to be read all?

### ISSUE THREAD

**Issue by AlexOastler** [WP-API/WP-API#857]
Is there a way to define which post meta should / not be secured behind authentication?

Or is there additional doc / examples other than http://wp-api.org/guides/authentication.html regarding the use of cookie authentication?

Using v0.9 of the API I had been able to retrieve meta (intended as viewable by all) through the following in a template:
```` 
$('.capDisplay').on('click', function(e){		
	e.preventDefault();
        var capName = $(this).text();
        var capID = $(this).attr('data-id');
        var l = Ladda.create(this);
	l.start();
			
	restURL = '/wp-json/posts/' + capID;		
	$.getJSON(restURL, function(response) {

		var dataTypes = ['description', 'future_direction', 'applications', 'contacts'];		
		$.each( dataTypes, function( key, dataType ) {
			//Parse post_meta and update UI accordingly
		});
	}).always(function() { l.stop(); });

});
````

The http://wp-api.org/guides/authentication.html documentation suggests that for plugins / themes using cookie authentication is suggested format, but is a little sparse on details to be able to create equivalent as above for /wp-json/posts/ [ID] /meta

In this scenario it is not a valid expectation that a site visitor would be both registered, signed-in and have associated edit capabilities tied to their role. I'm hoping that just as get_post_meta enables presentation via theme for meta that there is a way to specific which meta fields should be accessible via the API in non-authenticated scenarios?

Thanks!

**Comment by rmccue** [comment]
I've added documentation in #874 to make it clear why meta isn't available to unauthenticated users. Take a look at the [rendered diff to see the content changes](https://github.com/WP-API/WP-API/pull/874/files?short_path=0956e91).

> In this scenario it is not a valid expectation that a site visitor would be both registered, signed-in and have associated edit capabilities tied to their role. I'm hoping that just as get_post_meta enables presentation via theme for meta that there is a way to specific which meta fields should be accessible via the API in non-authenticated scenarios?

We're [working on adding support into WordPress core](https://core.trac.wordpress.org/ticket/29786) for this, but it doesn't exist right now. The best way to handle this is to filter `json_prepare_post` and add necessary data there (make sure it's prefixed/namespaced to ensure you don't conflict with other plugins or future versions of WordPress).

Thanks for filing the issue!

**Comment by Idealien** [comment]
Thanks Ryan!

For others finding this after looking for an example of the json_prepare_post scenario - Ryan provided examples here https://wordpress.org/support/topic/custom-meta-data-2?replies=4 

If you happen to use ACF - this thread may help too - http://support.advancedcustomfields.com/forums/topic/json-rest-api-and-acf/
