### ISSUE TITLE
Raw post data is available without authenticating

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#858]
If you hit `/wp/posts?context=edit`, you can access protected post data without authenticating. This is not cool.

**Comment by danielbachhuber** [comment]
Related https://github.com/WP-API/WP-API/pull/838/files#diff-6a242a8d43b6c0aa73da8f01c1324859R59

**Comment by rmccue** [comment]
Doesn't appear as though users suffers from the same issue, however it does suffer from #861.

**Comment by danielbachhuber** [comment]
Er, related in the sense that I forced degradation of the context because, previously, if you passed `context=edit` and had `list_users`, you could access the full object.

**Comment by danielbachhuber** [comment]
Related #950, #702 

Unless #949 makes this much more elegant, I'm getting pretty close to wanting to dump contexts out the window.

**Comment by danielbachhuber** [comment]
This was solved nicely by #1049
