### ISSUE TITLE
Add endpoints to create, update and delete comments

### ISSUE THREAD

**Issue by royboy789** [WP-API/WP-API#86]
This is a bit specific to my case, but figured it would be worth sharing how I added in new comments into the API.

```
public function newComment( $id, $data ) {
		$time = current_time('mysql');
		$data = array(
			'comment_post_ID' => $data['id'],
			'comment_author' => $data['author'],
			'comment_author_email' => $data['comment_author_email'],
		    'comment_content' => $data['content'],
		    'comment_date' => $time,
		    'comment_approved' => 1
		);
		$newComment = wp_insert_comment($data);
		return $newComment;
}
```

I pass the ID into $data, but can easily just be grabbed from $id. 

I will eventually be adding in logged in vs. not logged in, but I think that will primarily just be front end to retain as much of this API function as possible for either use case.

**Comment by inverse** [comment]
@drag0nman I don't think it's available. When performing a `GET` on the root URL it should detail all of the available end points and HTTP verbs of which `POST` is not existant under `/posts/{id}/comment`

**Comment by justvanbloom** [comment]
@royboy789 but ok, they come over the api.. but we should also check here for spam or bots. not simply approve them.

**Comment by rachelbaker** [comment]
Create and Edit comments coming in #693 and v2.0

**Comment by marygooven** [comment]
Guys, what do you think of [https://www.idealsvdr.com/](url)? I want it to use for code security and different data.
