### ISSUE TITLE
Further abstraction of controller test structure

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#864]
https://github.com/WP-API/WP-API/blob/develop/tests/test-json-posts-controller.php is getting pretty meaty — ~1k lines. We should abstract it further so it's easier to read.

How about breaking the controller test pattern into separate classes for each type of operation (CRUD)?

**Comment by rmccue** [comment]
> How about breaking the controller test pattern into separate classes for each type of operation (CRUD)?

My only concern with this is making sure we avoid complexity to the tests. I intentionally try and keep tests as free of complexity (including avoiding branches) since it can make bugs super hard to find.

If we can just do a split, :+1: :)

**Comment by danielbachhuber** [comment]
Abstraction is going pretty well now. There are a couple good follow-up issues.
