### ISSUE TITLE
Include Single Post pagination _links

### ISSUE THREAD

**Issue by rachelbaker** [WP-API/WP-API#866]
Add "previous" and "next" _link objects for single pagination.

**Comment by joehoyle** [comment]
What is "next" though? By chronology? Getting a single post object (presuming what this is for) I don't know exactly what "pagination" means

**Comment by rmccue** [comment]
> What is "next" though? By chronology? Getting a single post object (presuming what this is for) I don't know exactly what "pagination" means

The same as the logic used by `get_adjacent_post_rel_link` in core, which adds `rel="next"` and `rel="prev"` to single post views in HTML (see `adjacent_posts_rel_link_wp_head`).

**Comment by rmccue** [comment]
Closing as duplicate of #783.
