### ISSUE TITLE
Create WP_JSON_Revisions_Controller

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#869]
Because the schema for Revisions will be quite different than Posts and Pages, we should just create a separate controller for it.

This way, we don't need to register `/wp/posts/<id>/revisions` and can instead use `/wp/revisions/?parent=<id>`

After #844

**Comment by danielbachhuber** [comment]
Couple things I ran into when I considered working on this over the weekend:

* Should the revisions controller have a fixed schema, or reflect that of its parent?
* Should revisions be editable or deleteable?

**Comment by danielbachhuber** [comment]
Revisions should reflect the schema of their parent, and only include revisioned fields. As such, they should be included at `/wp/posts/<id>/revisions` and similar. Revisions can be deleted, but not edited.

https://wordpress.slack.com/archives/core-restapi/p1425511999000547

**Comment by joehoyle** [comment]
> and only include revisioned fields

I'm not sure I read that in the attached log. If it only includes the changed fields, how are we sticking to a schema? Or, maybe I'm misunderstanding
