### ISSUE TITLE
Validate request arguments before passing to the controller

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#871]
If a client provides an invalid `format` when creating or updating a Post, the current behavior is to:

1. Create the post with all other supplied details.
2. Silently fail setting the post format (we create a WP_Error but don't do anything with it).

See https://github.com/WP-API/WP-API/blob/develop/lib/class-wp-json-posts-controller.php#L156

As a client developer, I'd expect my data to be validated before any data transformation happens, so I don't have to worry about my Resource only partially being updated.

This applies more broadly to other attributes too, not just post formats.

**Comment by danielbachhuber** [comment]
More thoughts from the chat:

* Post format needs to be validated against a set of potential options.
* parent_id and author_id need to be validated against their respective objects
* post_title and post_content also should check string types because saving an object would be bad
* Possible rule to follow for the API: if invalid data has been provided for a valid field, throw an error. If invalid data has been provided for an invalid field, we can silently ignore.

Need #844 to land, then we can work on a framework for validating data based on it.

**Comment by rachelbaker** [comment]
@danielbachhuber With #913 merged, is there anything left to do here?

**Comment by danielbachhuber** [comment]
Yes, we need to pre-validate all of our fields before saving any data to the database.

**Comment by danielbachhuber** [comment]
Here's how Github returns validation errors: https://developer.github.com/v3/#client-errors
