### ISSUE TITLE
Accessing non core data

### ISSUE THREAD

**Issue by Matt2012** [WP-API/WP-API#873]
Sorry if this of on the documentation but I'm not seeing anything about how to handle data from non core tables? How would I access my gravity forms tables or other plugin custom tables?

**Comment by rmccue** [comment]
> How would I access my gravity forms tables or other plugin custom tables?

You'd need to create custom endpoints for this, or petition the Gravity Forms developers to create them. The API can only deal with core data out of the box.

**Comment by Matt2012** [comment]
Is there any instructions for creating custom end points? Sorry if this is the wing place to post this.

**Comment by Matt2012** [comment]
OK found it http://wp-api.org/guides/extending.html
