### ISSUE TITLE
Automatically registering custom post types as endpoints

### ISSUE THREAD

**Issue by sebastiaandegeus** [WP-API/WP-API#877]
Right now the registering of a custom post type endpoint is a process of adding a class file and implementing class methods. 

Is there is a way to register endpoints for custom post types in a more generic way. So I can loop over an array of post types and programatically register endpoints for each?

**Comment by danielbachhuber** [comment]
> Is there is a way to register endpoints for custom post types in a more generic way.

Sure, you'll be able to register them however you'd like. For a simple example, check out: https://github.com/WP-API/WP-API/blob/develop/tests/test-json-server.php#L72

`register_json_route()` will be the API for registering routes, and will require a namespace, path, and then a bunch of endpoint arguments.

Check out https://github.com/WP-API/WP-API/pull/769/files for the more advanced pattern that the core controllers will use.

**Comment by sebastiaandegeus** [comment]
Thanks, is `register_json_route` this supported in the current 1.1.1 release or not yet?

**Comment by danielbachhuber** [comment]
> supported in the current 1.1.1 release or not yet?

Nope. It will be in a `2.x` release.

If you're open to helping us squash bugs, you could use `develop` in a production-ish environment.
