### ISSUE TITLE
?json_route=/posts limiting to 10 posts

### ISSUE THREAD

**Issue by andyf625** [WP-API/WP-API#878]
Hi, I am using this plugin and its seems to be working great to get post information
by doing:
?json_route=/posts

the only problem i am finding is that it is limiting the number of posts to 10 ? in the output json generated?

is there any way to increase this?

any help would greatly be appreciated as this is a live project,
Thanks.

**Comment by rachelbaker** [comment]
@andyf625 If you are using the .org version of the plugin, you need to use the `filter` parameter.

Example: ?json_route=/posts&filter[posts_per_page]=25

Documentation is available: http://wp-api.org/#posts_retrieve-posts

**Comment by andyf625** [comment]
bang on,
thanks!
