### ISSUE TITLE
featured_image returning bad values

### ISSUE THREAD

**Issue by sjuxax** [WP-API/WP-API#880]
Using current HEAD on develop branch (612a6094adb02387f3d64a9ef50572810b57761c), when I issue a `GET /posts`, the `featured_image` field comes back with `{}` if a feature image is set, or `null` if a feature image has not been set. I expected to get the URL of the featured image. I'm not sure if `featured_image` is expected to return the URL or the media ID, but in any case, I don't think the values I was seeing are expected.

Here's some sample output showing what I mean. The posts with `{}` for `featured_image` have a featured_image set. The posts with `null` don't.

```
$ curl https://example.com/blog/wp-json/posts?posts_per_page=5 | jsonpp | grep -i featured
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   99k    0   99k    0     0  93394      0 --:--:--  0:00:01 --:--:-- 93401
    "featured_image": {}
    "featured_image": {}
    "featured_image": {}
    "featured_image": {}
    "featured_image": {}
    "featured_image": null
    "featured_image": null
    "featured_image": null
    "featured_image": null
    "featured_image": null
```

[As a separate issue, I get too many results back for the posts_per_page parameter I specified.]

I was able to hack around this for now by doing this:

```
diff --git a/lib/class-wp-json-posts.php b/lib/class-wp-json-posts.php
index 070fb38..d950798 100644
--- a/lib/class-wp-json-posts.php
+++ b/lib/class-wp-json-posts.php
@@ -811,6 +811,9 @@ class WP_JSON_Posts {
                if ( $previous_post ) {
                        setup_postdata( $previous_post );
                }
+               $_post['featured_image'] = wp_get_attachment_url(get_post_thumbnail_id( $post['ID'] ));
                return $_post;
        }
```

which is obviously not where this is supposed to be happening, but this hack works for me for now.

**Comment by goblindegook** [comment]
I ran into this before: the `attachment` post type is missing the `show_in_json` attribute.

Fetch it with `get_post_type_object()` and set the attribute to `true`, it should fix the problem.

**Comment by danielbachhuber** [comment]
In `develop` and on 2.0, `featured_image` will be an id referencing the attachment or null. If there is an associated attachment, all of the data will be present in `_links`
