### ISSUE TITLE
Trying to work with Reactor Plugin, but Slugs are not working correctly.

### ISSUE THREAD

**Issue by clammy77** [WP-API/WP-API#881]
As title, somehow an external website cannot read our URL Slugs.

**Comment by danielbachhuber** [comment]
@clammy77 Is this a problem with WP-API, or with the Reactor plugin?

**Comment by clammy77** [comment]
AppPresser said there's an issue w/ reading our slugs, and asked us to ask for help here.

Our URLs are in Chinese, not sure if other sites would have issue reading the URL?

**Comment by rmccue** [comment]
We need more detail on what exactly you mean by "cannot read our URL Slugs". Are they being output by your site correctly?

(If possible, a link to your site would be great.)

**Comment by clammy77** [comment]
Ahhh, my bad. Here's the site: teepr.com

**Comment by rmccue** [comment]
So, looking at http://www.teepr.com/wp-json/posts it looks like the slugs are correctly output. My guess is that Reactor is unable to handle slugs with URL-encoded characters in them?

**Comment by clammy77** [comment]
Thanks Ryan, I will let them know, and see what they can do about it. The
fast response is amazing.

**Comment by modemlooper** [comment]
oops, a support miss-understanding, @rmccue is correct, issue on our end with encoding and angular http.

**Comment by clammy77** [comment]
Thanks! When can I expect the issue to resolve?

Edward

**Comment by rachelbaker** [comment]
Closing this issue as it is being handled by @modemlooper and the Reactor team.
