### ISSUE TITLE
Multiple taxonomy filter terms

### ISSUE THREAD

**Issue by chrisboakes** [WP-API/WP-API#886]
Is there a way to filter multiple custom taxonomy terms? For instance:

`http://example.com/wp-json/posts?type=event&filter[taxonomy]=event_type&filter[term]=festival&filter[term]=walk`

Or somehow pass an array to the terms?

**Comment by timkinnane** [comment]
You'd have to pass a 2D array as a query param, to use taxonomy parameters in the query filter.
See: http://codex.wordpress.org/Class_Reference/WP_Query#Taxonomy_Parameters

To pass the array of params as a single filter variable in the URL you'd probably have to serialize and encode the array. You can use a PHP function to do that, e.g.

```
$tax_query = array(
	'taxonomy' => 'event_type',
	'field'    => 'slug',
	'terms'    => array( 'festival', 'walk' )
);
echo urlencode(serialize($tax_query));
```

BUT I don't know if the API will decode the array back to be passed into the WP query, or if there's a distinct set of query vars that it looks for. Sorry I don't know enough to give conclusive advice, but it's a good enough place to start.

**Comment by danielbachhuber** [comment]
We're revisiting these query params in #924

**Comment by scottopolis** [comment]
+1 for multiple taxonomy filtering. That would be multiple categories, tags, and/or custom taxonomies.

**Comment by shprink** [comment]
+1 with @scottopolis

**Comment by equatorapps** [comment]
+1

**Comment by nharlow89** [comment]
In case anyone else stumbles upon this I came up with a solution using the rest_{post-type}_query hook to modify the query. Full explanation is here: [WP API Multiple Taxonomy Query](http://y-designs.com/blog/wp-api-multiple-taxonomy-query/).

**Comment by jdcauley** [comment]
@nharlow89 your solution is exaclty what I need.

**Comment by nharlow89** [comment]
@jdcauley glad I could help!

**Comment by jdcauley** [comment]
@nharlow89 still fighting with implementation, but I may be missing something, it isn't triggering the 'custom_rest_query' function

**Comment by nharlow89** [comment]
@jdcauley There are a couple things that need to be in place. First, make sure when you define your custom post type you include the argument `‘show_in_rest’  => true` (also may need `‘public’ => true` but don't quote me on this one). Second, make sure you are tying to the right hook `rest_{post-type}_query`. In my example I have `rest_rental_query`, where rental is my CPT. Best of luck.

**Comment by jdcauley** [comment]
@nharlow89, Which version of the plugin are you running?

Edit: My Plugin version was behind. It might be helpful in your post to date it or reference plugin version numbers with its rapid updates
