### ISSUE TITLE
AJAX: API returns 200 but errors. JSONP issue?

### ISSUE THREAD

**Issue by thenickcox** [WP-API/WP-API#887]
I'm trying to get a simple Backbone app working locally based on the posts at a separate domain. I had a feeling I'd run into a JSONP issue because of [this issue](https://github.com/WP-API/WP-API/pull/380). Because this change looks like it was slated for 1.2, and I only had the 1.1.1 version from the WordPress plugin directory, I edited lib/class-wp-json-server.php to serve a content type header of `application/javascript`. (I know it's generally a bad idea to hand-edit plugin files, but I wanted to see if I could get it working.)

This fixed the error I was getting in Chrome:

```
Refused to execute script from XXX because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.
```

So I figured I'd write a suuuuper simple Backbone collection and see if I could get the posts from the external URL in the console. In CoffeeScript:

```coffeescript
@App =
  Collections: {}
  Models: {}
  Views: {}

@App.Collections.Posts = Backbone.Collection.extend
  url: 'http://sparkflyphotography.com/wp-json/posts'

@App.Models.Post = Backbone.Collection.extend
  collection: App.posts

$ ->
  window.App.posts = new App.Collections.Posts
  window.App.posts.fetch
    type: 'GET'
    dataType: 'jsonp'
    contentType: 'application/javascript'
    success: (data, response, opts) -> console.log data, response, opts
    error: (data, response, opts) -> console.log data, response, opts
```

I know that this code works because I tried setting the `url` property on the collection to `api.github.com/users/thenickcox`, and logging some attributes of the `JSON` object returned in the response, and it worked as expected. 

When I point this to the WP-API endpoint, this code actually calls the `error` callback from `fetch`, but the server responds with a `200`, and the posts are there in the server response, I just can't get to them because they're not in the response parameter from the `error` callback. Since this worked on the GitHub API, it feels like a server issue. (I recognize this could be due to the modification I made.) What am I doing wrong?

## Edit

I should probably mention that when I say I edited the file to serve a content type of 'application/javascript', I did so by changing line 183 of `json-rest-api/lib/class-wp-json-server.php` from

```php
    $this->send_header( 'Content-Type', 'application/json; charset=' . get_option( 'blog_charset' ), true );
```

to

```php
    $this->send_header( 'Content-Type', 'application/javascript; charset=' . get_option( 'blog_charset' ), true );
```

## Edit 2

Just uploaded the `develop` branch to my plugins directory, and I can confirm that this is still an issue.

**Comment by swissspidy** [comment]
Is this still happening with 2.0 Beta 5? It seems to me that the plugin correctly sets the content type to `application/javascript`.
