### ISSUE TITLE
API for creating a post expects "parent", not "post_parent" as documented

### ISSUE THREAD

**Issue by sashagim** [WP-API/WP-API#889]
The API request for creating a new post (POST /posts) lists "post_parent" as a possible parameter. From looking at the code, the correct parameter name is "parent", not "post_parent", and I have tested that this is correct.

**Comment by danielbachhuber** [comment]
The documentation represents the master branch. This field has changed on the develop branch (and might change again to `parent_id`). We'll update the documentation when we're ready to drop develop into master.
