### ISSUE TITLE
Comment author email address probably shouldn't be exposed by default

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#893]
If we aren't exposing email address for users by default.

Only affects `develop`

**Comment by rachelbaker** [comment]
@danielbachhuber Good point.  Should we return the `email` field as `false`?  

That would match the default behavior of the `users` endpoint response, and the .com API: https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/comments/

Also needs unit tests so this "never happens again" :hammer:

**Comment by danielbachhuber** [comment]
> Should we return the email field as false?

I think it's contingent on #894

On `master`, it's nice that the author data is normalized to some degree. But it doesn't really match our other resources.

**Comment by danielbachhuber** [comment]
> But it doesn't really match our other resources.

Or, we could include `author_name`, `author_email`, and `author_avatar` as a part of the `Post` response.

**Comment by rmccue** [comment]
@rachelbaker Not sure why this one's "Blocked on Core"?

**Comment by rachelbaker** [comment]
@rmccue Me neither.  Label removed.
