### ISSUE TITLE
JSON Schema: How should we report `context` arguments adding data to a response?

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#894]
Our `context` parameter can add data to User and Post responses. We should figure out how this variable data can be communicated in the JSON Schema representation.

**Comment by danielbachhuber** [comment]
The leading idea I have right now is that we always include the fields in the response, but nullify the values when the data is supposed to be inaccessible.

**Comment by rachelbaker** [comment]
@danielbachhuber Anything still open here, or can we close this issue?

**Comment by danielbachhuber** [comment]
I still need to port Comments over, and Meta and Revisions when they're ready.

**Comment by danielbachhuber** [comment]
This has been addressed in all of our endpoints.
