### ISSUE TITLE
Problem connecting via curl

### ISSUE THREAD

**Issue by BenjaminBarnett** [WP-API/WP-API#901]
Site is a MU / multi-network instance.

curl -I http://thedigitalmosaic.com yields proper-ish header return (from http://wp-api.org/guides/getting-started.html):

```
HTTP/1.1 200 OK
Date: Thu, 19 Feb 2015 18:45:13 GMT
Server: Apache
X-Pingback: http://thedigitalmosaic.com/xmlrpc.php
Link: <http://thedigitalmosaic.com/>; rel=shortlink
Set-Cookie: invite-anyone=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/
Content-Type: text/html; charset=UTF-8
```

Subsequent curl hit to /wp-json worked(-ish) exACTly once:

```
bbarnett-mbpro:~ bbarnett$ curl -i http://thedigitalmosaic.com/wp-json
HTTP/1.1 200 OK
Date: Thu, 19 Feb 2015 18:52:57 GMT
Server: Apache
X-Pingback: http://thedigitalmosaic.com/xmlrpc.php
X-Content-Type-Options: nosniff
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8

{"name":"Digital Mosaic","description":"Everyone has a story.","URL":"http:\/\/thedigitalmosaic.com","routes":{"\/":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/thedigitalmosaic.com\/wp-json\/"}},"\/posts":{"supports":["HEAD","GET","POST"],"meta":{"self":"http:\/\/thedigitalmosaic.com\/wp-json\/posts"},"accepts_json":true},"\/posts\/<id>":{"supports":["HEAD","GET","POST","PUT","PATCH","DELETE"],"accepts_json":true},"\/posts\/<id>\/revisions":{"supports":["HEAD","GET"]},"\/posts\/<id>\/meta":{"supports":["HEAD","GET","POST"],"accepts_json":true},"\/posts\/<id>\/meta\/<mid>":{"supports":["HEAD","GET","POST","PUT","PATCH","DELETE"],"accepts_json":true},"\/posts\/<id>\/comments":{"supports":["HEAD","GET"]},"\/posts\/<id>\/comments\/<comment>":{"supports":["HEAD","GET","DELETE"]},"\/posts\/types":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/thedigitalmosaic.com\/wp-json\/posts\/types"}},"\/posts\/types\/<type>":{"supports":["HEAD","GET"]},"\/posts\/statuses":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/thedigitalmosaic.com\/wp-json\/posts\/statuses"}},"\/users":{"supports":["HEAD","GET","POST"],"meta":{"self":"http:\/\/thedigitalmosaic.com\/wp-json\/users"},"accepts_json":true},"\/users\/<id>":{"supports":["HEAD","GET","POST","PUT","PATCH","DELETE"],"accepts_json":true},"\/users\/me":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/thedigitalmosaic.com\/wp-json\/users\/me"}},"\/media":{"supports":["HEAD","GET","POST"],"meta":{"self":"http:\/\/thedigitalmosaic.com\/wp-json\/media"}},"\/media\/<id>":{"supports":["HEAD","GET","POST","PUT","PATCH","DELETE"]},"\/taxonomies":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/thedigitalmosaic.com\/wp-json\/taxonomies"}},"\/taxonomies\/<taxonomy>":{"supports":["HEAD","GET"]},"\/taxonomies\/<taxonomy>\/terms":{"supports":["HEAD","GET"]},"\/taxonomies\/<taxonomy>\/terms\/<term>":{"supports":["HEAD","GET"]},"\/pages":{"supports":["HEAD","GET","POST"],"meta":{"self":"http:\/\/thedigitalmosaic.com\/wp-json\/pages"},"accepts_json":true},"\/pages\/<id>":{"supports":["HEAD","GET","POST","PUT","PATCH","DELETE"],"accepts_json":true},"\/pages\/<id>\/revisions":{"supports":["HEAD","GET"]},"\/pages\/<id>\/comments":{"supports":["HEAD","GET"]},"\/pages\/<id>\/comments\/<comment>":{"supports":["HEAD","GET","...
```

...but then crapped out right ^THERE (at the end of that last line) and spat about 20 command-line returns (in Mac Term, I suppose I should say, if that's in any way relevant).

Next I tried to GET a list of users and was told:
```
[{"code":"json_user_cannot_list","message":"Sorry, you are not allowed to list users."}]
```

So I installed the Basic Auth plugin and tried again:
```
curl --user USERNAME:PASSWD -i http://thedigitalmosaic.com/wp-json/users
HTTP/1.1 403 Forbidden
Date: Thu, 19 Feb 2015 19:31:40 GMT
Server: Apache
X-Pingback: http://thedigitalmosaic.com/xmlrpc.php
X-Content-Type-Options: nosniff
Vary: Authorization
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8

[{"code":"json_user_cannot_list","message":"Sorry, you are not allowed to list users."}]
```

After THAT failure, every time I try to connect to /wp-json, I get:
```
curl -i http://thedigitalmosaic.com/wp-json
HTTP/1.1 404 Not Found
Date: Thu, 19 Feb 2015 19:41:00 GMT
Server: Apache
Content-Length: 324
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /wp-json was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
```

That is with and without Basic Auth enabled. Any thoughts? HELP.

**Comment by rmccue** [comment]
Is it possible that you have server-level caching enabled here?

**Comment by BenjaminBarnett** [comment]
Partially-solved the issue: Basic Auth plugin, upon install, overwrote some key MU / BP redirects in .htaccess. I restored those, but now am getting a permission-related error.

When I...
curl --user UNM:PWD -i http://thedigitalmosaic.com/wp-json/users

The server snippily goes all...
[{"code":"json_user_cannot_list","message":"Sorry, you are not allowed to list users."}]

But, this IS a valid superadmin UNM:PWD key pair. Any further thoughts?  I could set you up a temp admin key pair, if that would help.

**Comment by rmccue** [comment]
It's possible that your Authorization header isn't actually getting through to PHP. Can you check the values of `$_SERVER['PHP_AUTH_USER']`, `$_SERVER['HTTP_AUTHORIZATION']` and `getallheaders()` please?

**Comment by BenjaminBarnett** [comment]
...and, in fact, when I hit http://thedigitalmosaic.com/wp-json/users via my browser, in a logged-in state (so authenticated by cookie), I get the same error message:
[{"code":"json_user_cannot_list","message":"Sorry, you are not allowed to list users."}]

**Comment by BenjaminBarnett** [comment]
kk, we're getting somewhere, maybe.

$_SERVER['PHP_AUTH_USER']  =  jgrandma
$_SERVER['HTTP_AUTHORIZATION']  =  Basic
amdyYW5kbWE6QS1zb2xhci1zeXN0ZW0tbWlzcw==

That's NOT the user I'm passing (well, attempting to pass) via CURL, it's a
base-level user. I'm on a Mac and I'm not really expert with user
management in Term, I should say.

My build of PHP doesn't seem to support getallheaders(), alternatives?


______________________
Benjamin Barnett, co-owner
media schmedia LLC
media-schmedia.com
mightylittlewebsites.com
216-291-4313

**Comment by BenjaminBarnett** [comment]
To clarify: the first time I logged out of the site, in my browser (Mac
Safari), I got a weird (to me) message.

Modal dialog popped up, said I couldn't load the page without providing
user credentials which would be passed in the clear. I didn't want to send
a superadmin key pair, so I filled in a simple member key pair instead. Now
it seems to be held in a cookie somewhere that isn't the WordPress cookie.

Sorry to be fumbling around with this, it's actually more than a little out
of my current depth.


______________________
Benjamin Barnett, co-owner
media schmedia LLC
media-schmedia.com
mightylittlewebsites.com
216-291-4313

**Comment by BenjaminBarnett** [comment]
nope, I was just being stupid with getallheaders:

jgrandma
Basic amdyYW5kbWE6QS1zb2xhci1zeXN0ZW0tbWlzcw==


Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8

Accept-Encoding: gzip, deflate

Accept-Language: en-us

Authorization: Basic amdyYW5kbWE6QS1zb2xhci1zeXN0ZW0tbWlzcw==

Cache-Control: max-age=0

Connection: keep-alive

Cookie: __utma=255929422.71475893.1414033538.1424375385.1424395607.8; __utmc=255929422; __utmz=255929422.1414033538.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); wordpress_logged_in_65ba223300b1ac2ef8b613d5d36dfccd=v1d30--x%7C1424571261%7Cq0NVpO021GU1hdqffDBqoN3V1xgbyvk8KS8sXHbpyKL%7C51480d42a742f428662d379010a36ae66144add5ae63eb408c1ef44fc0f3ec72; bp-activity-oldestpage=1; gf_display_empty_fields=true; wp-settings-18=editor%3Dtinymce%26posts_list_mode%3Dlist; wp-settings-4=editor%3Dhtml%26siteorigin_settings_tab%3D3%26libraryContent%3Dbrowse%26hidetb%3D1; wp-settings-time-18=1418248877; wp-settings-time-23=1422307487; wp-settings-time-4=1422298249

Dnt: 1

Host: thedigitalmosaic.com

User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/7.1.3 Safari/537.85.12

**Comment by caffeinelogic** [comment]
I am having a similar issue when logged in as the admin and I hit the /users route via a browser or other rest service testing plugin. 

When I break point inside the rest call I can see that:
$_SERVER['PHP_AUTH_USER'] = null
$_SERVER['HTTP_AUTHORIZATION'] = null
getallheaders() has values

If I attempt to evaluate the wp_get_current_user() expression it returns a WP_User object with an ID of 0, which is not the current user or any user.

**Comment by rmccue** [comment]
> To clarify: the first time I logged out of the site, in my browser (Mac Safari), I got a weird (to me) message.

This isn't a cookie, it's your browser holding that value you entered and reusing it on subsequent views. Try restarting your browser.

> That's NOT the user I'm passing (well, attempting to pass) via CURL, it's a base-level user. I'm on a Mac and I'm not really expert with user management in Term, I should say.

I'm unsure what you mean here; are you getting those results back via cURL in the command line still, or is this in the browser? If it's in the command line, and that's not what you're passing, it sounds like your host could be overriding the authorization header somehow.

----

> I am having a similar issue when logged in as the admin and I hit the /users route via a browser or other rest service testing plugin.

This is a separate issue, as it's cookie authentication. Please ensure you're sending a nonce [as noted in the docs](http://wp-api.org/guides/authentication.html). If that still doesn't work, please file a new issue.

**Comment by caffeinelogic** [comment]
Gotcha, I apologize for misunderstanding. One last question and I will stop polluting this thread: I have extended the API to add a new set of routes for a custom plugin for Events and when I go to use the wp_get_current_user() inside one of the route methods it will not return the current User. Is this also a nonce issue, is it being enforced on all REST calls using WP-API default or extended?

**Comment by BenjaminBarnett** [comment]
Ryan, any insight into where my problem lies, based on the headers? Those are ofc the browser headers, but I'm getting the same choke in curl as browser. Even a suggestion on where to dig further would be of use, as I'm unclear how to proceed resolving this authentication issue so I can move forward.

I'll next need to work out how to pull users and posts from sub-sites on the MU network, and to publish new posts to select sub-sites based on user parameters.
