### ISSUE TITLE
Getting posts that belong to *both* of two categories

### ISSUE THREAD

**Issue by dstharding** [WP-API/WP-API#903]
Hi!

I'm loving the api! The only problem that I've been faced with has been daunting, so hopefully one of you smarter-than-me folks can set me right.

The problem: I have a category filter with checkboxes for each category. Right now if you select all of them, you'll see every single post because it's getting posts that have any of those categories. What I need is for it to only display posts that have ALL of those categories. So AND not OR...

Is this possible with wp-api as is? If not, what is the most prudent way for me to go about making this work. I'm wanting to avoid having to abandon this api and write my own json feed if possible.

Thank you!!
Davey

**Comment by danielbachhuber** [comment]
> Is this possible with wp-api as is?

I don't think we support multi-dimensional tax queries yet.

We're revisiting these query params in #924
