### ISSUE TITLE
Filters to allow control over transport

### ISSUE THREAD

**Issue by timothy-h** [WP-API/WP-API#920]
Would it be possible to add filters to lib/infrastructure/class-wp-json-server.php to allow the manual definition of the content type, as well as to format the data that is being returned by an endpoint? In a project I'm working on, I'm trying to generate csv files on the fly based on parameters passed along a WP API endpoint. The current api forces either application/javascript or application/json, and automatically encodes the return data as json. It would be great if I could define the content type and serialization format either in the rule declaration itself or via a filter.

**Comment by danielbachhuber** [comment]
We won't be offering filters to change the transport mechanism. Instead, the architecture will be that someone writes a CSV server (if you want CSV), and the server can use all of the endpoint controllers to serve requests to, say, `/wp-csv/`

**Comment by rmccue** [comment]
Just to expand slightly on what @danielbachhuber said here: `WP_JSON_Server` is intended to be a JSON-based server for the API. If you want to use a different serialization format, we make that possible by replacing `WP_JSON_Server` with an alternative class (check the `wp_json_server_class` filter).

In this case, you'd probably want to replicate `json_api_loaded`, but replacing with your alternative server instead. This would let the two APIs run side-by-side.
