### ISSUE TITLE
Retrieve posts - post__not_in

### ISSUE THREAD

**Issue by danielst-vccp** [WP-API/WP-API#921]
Hi, I'm trying to exclude a post from a post list, but I'm having trouble getting the post__not_in filter to work.

The documentation suggests that this filter is only available to a logged in user with the correct permissions? I've tried the following syntax without much success, both logged in and not. `filter[post__not_in]=1234` and `filter[post__not_in][]=1234` have no effect.

**Comment by danielbachhuber** [comment]
@danielst-vccp Are you using the WordPress.org plugin, `master` branch of this repo, or `develop` branch of this repo?

**Comment by danielst-vccp** [comment]
Oh hai! The plugin version 1.1.1. Thanks.

**Comment by danielbachhuber** [comment]
For logged-out users, WP-API only supports filtering by WP_Query's public query vars: https://github.com/WP-API/WP-API/blob/1.1.1/lib/class-wp-json-posts.php#L151

`post__in` and `post__not_in` are private by default. To make them work, you'd need to filter `query_vars`:

```
add_filter( 'query_vars', function( $vars ){
	$vars[] = 'post__in';
	$vars[] = 'post__not_in';
	return $vars;
});
```

**Comment by danielst-vccp** [comment]
Perfect, thanks.

**Comment by danielbachhuber** [comment]
We're revisiting these query params in #924

**Comment by mdunbavan** [comment]
Has this been rectified yet?

**Comment by JakubKontra** [comment]
Where to add this block of code?

**Comment by JakubKontra** [comment]
I got [] ... (nothing)

**Comment by JakubKontra** [comment]
Fixed. Thanks
