### ISSUE TITLE
Query params for collections

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/WP-API#924]
_If you have a bug to report relating to querying for posts, terms, users, comments, etc., please open a new issue — this issue is intended to be a master reference._

This issue is a master issue representing work on query parameters in collections. Here's a table of the currently supported parameters:

```
+----------------+-------+-------+-------+----------+------------+-------+-------+
| param          | posts | pages | media | comments | categories | tags  | users |
+----------------+-------+-------+-------+----------+------------+-------+-------+
| after          |   x   |   x   |   x   |   x      |            |       |       |
| author         |   x   |   x   |   x   |   x      |            |       |       |
| author_email   |       |       |       |   x      |            |       |       |
| author_exclude |   x   |   x   |   x   |   x      |            |       |       |
| before         |   x   |   x   |   x   |   x      |            |       |       |
| context        |   x   |   x   |   x   |   x      |   x        |   x   |   x   |
| exclude        |   x   |   x   |   x   |   x      |   x        |   x   |   x   |
| filter         |   x   |   x   |   x   |          |            |       |       |
| hide_empty     |       |       |       |          |   x        |   x   |       |
| include        |   x   |   x   |   x   |   x      |   x        |   x   |   x   |
| karma          |       |       |       |   x      |            |       |       |
| media_type     |       |       |   x   |          |            |       |       |
| menu_order     |       |   x   |       |          |            |       |       |
| mime_type      |       |       |   x   |          |            |       |       |
| offset         |   x   |   x   |   x   |   x      |            |   x   |   x   |
| order          |   x   |   x   |   x   |   x      |   x        |   x   |   x   |
| orderby        |   x   |   x   |   x   |   x      |   x        |   x   |   x   |
| page           |   x   |   x   |   x   |   x      |   x        |   x   |   x   |
| parent         |       |   x   |   x   |   x      |   x        |       |       |
| parent_exclude |       |   x   |   x   |   x      |            |       |       |
| per_page       |   x   |   x   |   x   |   x      |   x        |   x   |   x   |
| post           |       |       |       |   x      |   x        |   x   |       |
| search         |   x   |   x   |   x   |   x      |   x        |   x   |   x   |
| slug           |   x   |   x   |   x   |          |   x        |   x   |   x   |
| status         |   x   |   x   |   x   |   x      |            |       |       |
| type           |       |       |       |   x      |            |       |       |
+----------------+-------+-------+-------+----------+------------+-------+-------+
```

Related #605

**Comment by jmca** [comment]
I'm still having issues even with the suggestion from #806. In `functions.php`:

    add_filter('query_vars', function ($vars) {
      $vars[] = 'post_parent';
      return $vars;
    });

My ajax call:

    $.ajax({url: 'wp-json/pages?filter[parent_post]=0'})
      .done(function (res){
        console.log(res);
    });

Here's one of the objects in the response, note the `parent` property is `Object` and not `0`:
![image](https://cloud.githubusercontent.com/assets/2760349/6362866/685486c4-bc5f-11e4-8e91-224a507a2d70.png)

**Comment by danielbachhuber** [comment]
@jmca Please open a new issue with your question.

**Comment by rachelbaker** [comment]
Punting to Beta 2.

**Comment by rachelbaker** [comment]
Punted to Beta 4

**Comment by joehoyle** [comment]
In #1777 we added the query param `parent` which may or may not be present in the following now:
- `parent`
  - [x] media
  - [x] hierarchical posts
  - [x] terms
  - [x] comments
- `author`
  - [x] posts
  - [x] media
- `status`
  - [x] posts
  - [x] comments
- `order`
  - [x] media
  - [x] posts
  - [x] terms
  - [x] comments
- `orderby`
  - [x] media
  - [x] posts
  - [x] terms
  - [x] comments

Let's make sure all of these are covered.

**Comment by danielbachhuber** [comment]
@WP-API/amigos I [wrote a script](https://gist.github.com/danielbachhuber/cd61d10d1fa8d7651dad) to produce a table comparing query params for each endpoint, and pasted it into the description. I'll keep the description updated until we feel comfortable closing the issue.

**Comment by danielbachhuber** [comment]
Some things I need to do:
- [x] Review `WP_Query` for any additional query params we should consider supporting.
- [x] Review `WP_User_Query` for any additional query params we should consider supporting.
- [x] Review `WP_Comment_Query` for any additional query params we should consider supporting.

**Comment by davidsteinberger** [comment]
What was the specific reason to remove `menu_order` from the posts-endpoint?

**Comment by danielbachhuber** [comment]
> What was the specific reason to remove `menu_order` from the posts-endpoint?

_Posts_ don't support `menu_order`, _Pages_ do.

**Comment by davidsteinberger** [comment]
Well yes, but there are tons of plugins that do provide a _menu_order_. In the previous beta _menu_order_ was still allowed, but now it's blocked. Do you know what's the proper way for me to re-enable that again (just for myself)?

**Comment by joneslloyd** [comment]
Hey - just asking to confirm:

Right now will filtering a CPT to those with a specific parent ID not work?

For example: `http://example.com/wp-json/wp/v2/my-cpts?filter[parent]=304` ?

If not, do you know if this is something in progress? I can help achieve this if you need an extra hand

**Comment by danielbachhuber** [comment]
> Do you know what's the proper way for me to re-enable that again (just for myself)?

You should be able to use `/wp/v2/posts?filter[menu_order]`

> Right now will filtering a CPT to those with a specific parent ID not work?

It should work — the filter key is `post_parent` though: `/wp/v2/my-cpts?filter[post_parent]=304`

**Comment by joneslloyd** [comment]
@danielbachhuber Thanks fore getting back to me!

Unfortunately that doesn't seem to be working for CPTs. I've not modified the returned data (etc.) which is weird.

When I try what you've written, I just get `[]` returned

**Comment by joneslloyd** [comment]
Just to let you know, this is definitely an issue.

When trying to filter by ID (`/wp/v2/my-cpts?filter[id]=333`) it returns the full set (all posts of the CPT, unfiltered).

When trying to filter by post parent (as above in previous reply) it returns a blank array.

**Comment by BE-Webdesign** [comment]
@joneslloyd id isn't a WP_Query param nor do I believe there is an id param being added to filter as a mask for the WP_Query params.  So I am pretty sure filter[id] doesn't work causing everything to be returned. To do what you are trying to do I highly recommend this.  /wp/v2/my-cpts/333 or if you want filter it could be /wp/v2/my-cpts?filter[p]=333.

> When trying to filter by post parent (as above in previous reply) it returns a blank array.

I can check about the use of post_parent and see if I can duplicate an empty result set.  @joneslloyd please open this in a separate issue if you want it addressed though this is a master reference and not intended for these kind of discussions.

**Comment by rmccue** [comment]
We're closing this ticket out in favour of more concrete tickets instead. If you have anything you need with params, please file a new issue.
