### ISSUE TITLE
curl x/wp-json returns 404 - seems not to exist.

### ISSUE THREAD

**Issue by sheriffderek** [WP-API/WP-API#929]
basic digital ocean hosting -> unix / mysql / wordpress etc - 2015 theme / stock - Post name permalinks... wp-api plugin - just setup for testing... nothing unique has been added. I made a few posts and a few pages with filler.

I have the site setup with a sub-folder - and my domain is a newer top-level domain name.

so, http://sheriffderek.consulting/cms/wp-json/

does not return anything. (I've tried many variations)

curl -I http://sheriffderek.consulting/cms/wp-json/
HTTP/1.1 404 Not Found
Date: Thu, 26 Feb 2015 06:58:47 GMT
Server: Apache/2.4.7 (Ubuntu)
Content-Type: text/html; charset=iso-8859-1

I would be pulling data into an Ember CLI project - but just getting a curl would be a start. I see that others have had similar issues, but I've tried the htaccess and - made sure my permalinks were 'pretty' -

**Comment by danielbachhuber** [comment]
Did you flush your rewrite rules after activating the plugin? Do pretty permalinks work for your posts?

**Comment by sheriffderek** [comment]
@danielbachhuber - Flushing and checking the permalinks sent me in the right direction. For reference, I was using ubuntu 14.04, on a digital ocean droplet. Rewrite / Mod_rewrite doesn't come stock, so I added that on the server - and then changed the /etc/apache2/sitesavailable/thing.conf  as seen here... https://wordpress.org/support/topic/local-installation-permalink-problem-404-error

Not sure what was necessary or not, but everything is as expected from the docs now. Thanks for the reply. The problem was on the user/server setup side. : )
