### ISSUE TITLE
When is json_serve_request filter applied for CORS?

### ISSUE THREAD

**Issue by lancemonotone** [WP-API/WP-API#932]
I'm having trouble understanding when the `json_serve_request` filter is applied during a request. The filter is added in **json-rest-api/plugin.php:406** and points to a function called `json_send_cors_headers`, which is defined at **:694**. As far as I can tell though, at no time during the request is `apply_filters('json_serve_request')` called and as such, the CORS headers are never sent. Am I wrong about this?

**Comment by rmccue** [comment]
Hmm, I'll look into this, it may be a regression.

**Comment by rmccue** [comment]
Confirmed; we changed the filter name to `json_pre_serve_request` in fc518604381e76d1e707e93fa4d8f9edf7c496c7 (#563). Need to fix the CORS headers up.

Note that for production use, you should use the `master` branch, rather than `develop` :)
