### ISSUE TITLE
Index post types by type slug

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#934]
See https://github.com/WP-API/WP-API/pull/914#issuecomment-76316952

@danielbachhuber:
> Would the key be the json_base for the post type? Should tax and post status endpoints follow suit?

IMO, it should be the type slug itself; you'll typically be indexing by the actual type in the main use case for the post types endpoint (building editor UI).

**Comment by danielbachhuber** [comment]
My suspicion is that these informational endpoints shouldn't live at root, but on some `/site` object or similar.
