### ISSUE TITLE
Post password isn't reset after temporary set

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#938]
I believe this is related to the order tests are run in `WP_Test_JSON_Posts_Controller`:
* `test_get_post_with_password` has permission to access the post, so we set the correct cookie value to work around core behaviour.
* `test_get_post_with_password_without_permisson` (apart from being misspelt) does not have permission to access the post, however the cookie is set previously, and the password is the same, so the post can be accessed.

This is pretty crazy. Maybe we need to kill the workaround and fix core instead?

(Also, nice work setting the password to `always$inthebananastand` for both posts. :D)

**Comment by rachelbaker** [comment]
*hangs head in shame*

**Comment by rachelbaker** [comment]
Closing issue since it was resolved with #973.
