### ISSUE TITLE
Pods and custom post types

### ISSUE THREAD

**Issue by diaspar** [WP-API/WP-API#944]
Does this plugin supports http://pods.io/ ?

If there is a way to support Pods and custom post types, it would be a terrific combination.

**Comment by danielbachhuber** [comment]
> If there is a way to support Pods and custom post types, it would be a terrific combination.

There will be a standard pattern of abstraction for Pods to add new endpoints, but the functionality to actually add the endpoints will need to be included in Pods.

**Comment by danielbachhuber** [comment]
> If there is a way to support Pods and custom post types, it would be a terrific combination.

There will be a standard pattern of abstraction for Pods to add new endpoints, but the functionality to actually add the endpoints will need to be included in Pods.

**Comment by quasel** [comment]
@diaspar 
OLD one Beta based on Rest-API v1  https://github.com/pods-framework/pods-json-api
NEW one currently in development vor v2 https://github.com/pods-framework/pods-rest-api
