### ISSUE TITLE
Unit tests assume they can write to stylesheet directory

### ISSUE THREAD

**Issue by rmccue** [WP-API/WP-API#956]

**Comment by danielbachhuber** [comment]
@rmccue which line is this referring to?

**Comment by rmccue** [comment]
Specifically, `WP_Test_JSON_Pages_Controller::test_create_item_with_template` writes out a template file for testing, and causes my tests to fail every time it's run.

We should consider using a stream wrapper for the content directory instead for this test.

**Comment by BE-Webdesign** [comment]
@rmccue , @danielbachhuber Is this still relevant?  WP_Test_JSON_Pages_Controller is now REST and test_create_item_with_template looks good to me, but I probably don't understand the issue.

**Comment by danielbachhuber** [comment]
@BE-Webdesign Yes. The problem is this setup method:

```
protected function setup_test_template() {

    $contents = <<<EOT
<?php
/*
* Template Name: My Test Template
*/

EOT;

    $this->has_setup_template = get_stylesheet_directory() . '/page-my-test-template.php';
    file_put_contents( $this->has_setup_template, $contents );
    wp_get_theme()->cache_delete();
}
```

But, the `theme_page_templates` filter does what we need it to now. PR incoming.
