### ISSUE TITLE
A way to rate limit WP API

### ISSUE THREAD

**Issue by ishansharma** [WP-API/WP-API#963]
Hi, 

I am working on a site where I need to expose API without login. However, I want to prevent misuse of the API as well. 

Is there a way to rate limit a client based on number of calls etc.

**Comment by danielbachhuber** [comment]
This isn't something the API supports out of the box. You'll need to create your own rate-limiting mechanism.

**Comment by rmccue** [comment]
The best way to do this, by the way, is to hook in to `json_pre_dispatch`. This lets you send a response object back, and essentially hijack the whole request while still using the same handling mechanisms.
