### ISSUE TITLE
PUT and other RESTful HTTP not allowed

### ISSUE THREAD

**Issue by tlovett1** [WP-API/WP-API#964]
I am using the stable version of WP API in my plugin Custom Contact Forms. I am receiving many reports of people who can't use my plugin because it depends on using the PUT (and DELETE) HTTP method(s) in conjunction with WP API. This brings up some questions/thoughts:

When the API is released to the public, there will undoubtable be thousands of websites that disallow at the very least PUT. How should plugins address this? Should we just default to standard HTTP methods? Should we attempt to display a coherent "talk to your host" error message?

Also, what will Core do when it starts to use the API internally? If it uses "non-standard" HTTP methods, many users will be alienated.

At the very least, I think there should be a major attempt to prep users for this beforehand. People need to be educated on what modern hosts should support.

**Comment by tlovett1** [comment]
I think the solution to not forcing a bunch of people to upgrade their web servers is to check for the `X-HTTP-Method-Override` header and adjust accordingly.

**Comment by tlovett1** [comment]
See #967

**Comment by pento** [comment]
> undoubtable be thousands of websites

*millions.

Hoping that hosts update their rules isn't an option, we definitely need a fallback.

**Comment by rmccue** [comment]
Right now, we support the `_method` query parameter; adding support for `X-HTTP-Method-Override` is fine by me, but is there any benefit to adding it? Headers are typically harder for clients to send, so we'll need to support `_method` in any case.

(I'm not aware of any clients that support it out of the box, but even one would convince me. :) )

**Comment by tlovett1** [comment]
`X-HTTP-Method-Override` is the industry standard. Backbone sends `X-HTTP-Method-Override` out of the box.

**Comment by rmccue** [comment]
> Backbone sends X-HTTP-Method-Override out of the box.

I'm sold. :)

**Comment by rmccue** [comment]
Fixed in #967. :)
