### ISSUE TITLE
Returns unpublished posts when not authenticated

### ISSUE THREAD

**Issue by solarisfire** [WP-API/WP-API#965]
Returns posts that do not have the status published to people who are not authorised. Wordpress will not do this itself so I see this as a security flaw.

**Comment by danielbachhuber** [comment]
Hi @solarisfire, can you share a sample request? Are you using v1.1.1, `master` or `develop` branch?

**Comment by solarisfire** [comment]
It was literally just a call to /wp-json/posts?page=4, and I'm using 1.1.1 downloaded from the WordPress Plugins directory.
