### ISSUE TITLE
JSON Parse error

### ISSUE THREAD

**Issue by TheFlow95** [WP-API/WP-API#969]
Hello,

I installed your plugin but the JSON response is invalid. If I use [JSONLint](http://www.jsonlint.com) I have this result:
> Parse error on line 17:
> ...     "description": "\u00c9tudiant en \u
> -----------------------^
> Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['

**Comment by rachelbaker** [comment]
@TheFlow95 What is the 'tagline' of your site set to in the WordPress Dashboard (wp-admin/options-general.php)?

**Comment by TheFlow95** [comment]
> Le meilleur d'Apple, tout simplement..

**Comment by rmccue** [comment]
This is a valid JSON string according to [RFC 4627](http://tools.ietf.org/html/rfc4627), so it looks like JSONLint might be giving an incorrect result here.

Can you paste the entire (raw) result into a gist please?

**Comment by TheFlow95** [comment]
JSONLint is not the only one to say that...
[Here is the gist](https://gist.github.com/TheFlow95/ad43acd9bbe52caf7b4c)

**Comment by rmccue** [comment]
Aha, at the bottom of your data, there's:
```
<!-- This website is like a Rocket, isn't it ? Performance optimized by WP Rocket. Learn more: http://wp-rocket.me -->
```

This isn't valid JSON; I suspect JSONLint may be reporting the error incorrectly here. Try disabling that plugin and see if the error still occurs.

**Comment by TheFlow95** [comment]
Seems to work, I just have to find how to remove this line without disabling the whole plugin.
If you have any idea...
Else thanks for your help ! I will close the issue

**Comment by royboy789** [comment]
@TheFlow95 - having the same problem now, were you creating custom routes? Looks like they fixed all cache'ing on default WP-API routes, but not on any custom routes. I tried adding in /wp-json/[custom-route-slug] but did not help.. how did you set yours up?

**Comment by royboy789** [comment]
If anyone else stumbles on this, i just added 
`/wp-json/.*` to my do not cache
