### ISSUE TITLE
/wp-json returns data , but /wp-json/posts is 500 - seemingly out of nowhere / ideas?

### ISSUE THREAD

**Issue by sheriffderek** [WP-API/WP-API#976]
/wp-json returns json , but /wp-json/posts is 500 - seemingly out of nowhere / ideas what might have changed?

In my test case, see:

http://sheriffderek.consulting/cms/wp-json/

vs

http://sheriffderek.consulting/cms/wp-json/posts/

Thanks.

**Comment by rmccue** [comment]
99.9% certain this is a result of #475.
