### ISSUE TITLE
Attach category to post

### ISSUE THREAD

**Issue by furyscript** [WP-API/WP-API#977]
Hi, I see documentation and classes but I don't find how to attach a category to a post.
When I make request to **.../wp-json/wp/posts** I try to pass **category** or **post_category** but nothing work.
Any idea?
Also I inspect the class in the plugin...
Thank's. Bye..

**Comment by danielbachhuber** [comment]
We haven't plugged in that functionality yet. Keep an eye on #978 for when we add support.
