### ISSUE TITLE
How to include wp-api.js on client side

### ISSUE THREAD

**Issue by indefinit** [WP-API/WP-API#979]
Hello,

Sorry this is more of a forum-type post but I don't see any forum or wiki so I figured I'd post here.  How do I include wp-api.js on the client side so that I can access Backbone + WP-API ?  It looks like wpi-api.js comes with the WP-API plugin, but it's unclear to me where that file gets included.  Thanks for your help in advance.

**Comment by danielbachhuber** [comment]
You can use `wp_enqueue_script( 'wp-api' );`
