### ISSUE TITLE
Change Default Custom Post Type Ordering

### ISSUE THREAD

**Issue by danielmilner** [WP-API/WP-API#980]
Is there a way to force a custom post type to always sort by something other than the post date? Like a meta_key for example?

For front-end stuff, I'm using the pre_get_posts action to set the meta_key, orderby, and order.

**Comment by danielbachhuber** [comment]
> Is there a way to force a custom post type to always sort by something other than the post date?

You mean, outside of using the `pre_get_posts` action?

**Comment by danielmilner** [comment]
I guess I mean with `pre_get_posts`. Right now, I'm just targeting the CPT archive page. Is there a way to target the CPT and WP-API?

**Comment by danielbachhuber** [comment]
Did you try something like this?

```
add_action( 'pre_get_posts', function( $query ){
	if ( 'cpt' !== $query->get('post_type') ) {
		return;
	}
	// do whatever
});
```

**Comment by danielmilner** [comment]
Alright, that seems to do it. Thanks!
