### ISSUE TITLE
Issue with WP command to create oAuth consumer

### ISSUE THREAD

**Issue by vinayakshukre** [WP-API/WP-API#981]
Hello,
      I am trying to develop a mobile application of wordpress daily blog website using HTML5 + Javascript + phonegap combination. I want my users to download it for free and see my daily posts through that app. I also want them to post their comments. To do that I am using "JSON REST API" wordpress plugin so that wordpress exposes certain REST URLs on which I can send POST requests from my mobile app to create comments. Documentation (http://wp-api.org/guides/authentication.html) of this plugin tells me to have another plugin named oAuth server plugin and then run command "wp oauth1 add" to generate the consumer. I am not able to find oAuth1 plugin through wp-admin UI of my site. I found a similar one with name "WordPress OAuth Server". But now I dont have wp command to run "wp oauth1 add". I am trying WAMP server on my windows 7 laptop whereas my actual website is using Linux box.
      Could somebody please help me to find out right plugin and right command to generate the consumer ? Thanks a ton in advance.

**Comment by jaapboerma** [comment]
Take a look at http://wp-cli.org/  : it provides the "wp" command used in the authentication tutorial.

**Comment by dleeward** [comment]
You might be looking for this: https://github.com/WP-API/OAuth1

**Comment by vinayakshukre** [comment]
Thanks jaapboerma and dleeward for spending time on this. 

As suggested by jaapboerma , I downloaded wp cli on my laptop which gave me a phar file and used below command

php d:\wp-cli.phar oauth1 add

instead of 

wp outh1 add.

and it gave me same output as expected on http://wp-api.org/guides/authentication.html
