### ISSUE TITLE
Conflicting public_query_var with param name causes warnings

### ISSUE THREAD

**Issue by joehoyle** [WP-API/WP-API#982]
Not sure if this has been discussed before - but weird things happen if you happen to use a `public_query_var` GET param in your endpoint. For example, I have a taxonomy called `series` which has the `public_query_var` of `series` - however I also have an endpoint that has a GET param of `series` which is an array. This leads to Weirdness and Warnings (TM).

This isn't an issue confined to the WP-API but I do wonder if we'll hit it a lot, especially   as WP-API hooks on `template_redirect` which means the main query already ran with the weird/malformed query var.

Any thoughts?

**Comment by rmccue** [comment]
We should avoid running on `template_redirect` I think, as we're doing the main query right now when we shouldn't be. I think `parse_request` might be late enough for us, as we know if we're on an API page by then, but the main query hasn't been run.

**Comment by joehoyle** [comment]
`parse_request` in my case was still too late for some warnings as `parse_request` is called after the vars have been set on the `$wp` object (which expects types to match the public_query_var type (which is always scalar)

**Comment by danielbachhuber** [comment]
Closing in favor of https://core.trac.wordpress.org/ticket/34728
