### ISSUE TITLE
How to filter by post format

### ISSUE THREAD

**Issue by oskarrough** [WP-API/WP-API#984]
Hi, according to the documentation it doesn't seem possible to query posts by their format - is this true?

I assumed something like `/wp-json/posts?filter[post_format]=video`.

**Comment by sheriffderek** [comment]
I am also trying to filter by format. I've tried many combinations *just incase*, but no go. Instead of saying there is no route though, I get an `[ ]` empty object --- which seems more promising than 'no-route' etc. --- mostly just returns as normal but ignores the filter. Any thoughts?

**Comment by hijoncon** [comment]
Hi oskarrough, I went to same problem. But I figure you need to passed the slug instead of name.
/wp-json/posts/?filter[post_format]=post-format-aside.

**Comment by sheriffderek** [comment]
Hooray! I tested that out and it works. Checked with custom-post-types too: `/posts?type=project&filter[post_format]=post-format-aside`

**Comment by hijoncon** [comment]
Cool we can close this issue now. :-)

**Comment by sheriffderek** [comment]
We can certainly close this - ... or - someone could remove the redundancy and deprecate the syntax in a later release.... 

`/posts?type=project&filter[post_format]=post-format-gallery`

vs

`/posts?type=project&filter[post_format]=-gallery`

I'm just happy it works at all. : )

**Comment by cbothner** [comment]
So, after trying every variation of `post-fomat-standard` that I could think of, I read the docs to find that the "standard" post format really means that post_format is set to false.  Of course

```
/posts?filter[post_format]=false
```

doesn't work—how can we filter for the absence of a format?

**Comment by danbeo95** [comment]
I have same  issue.how to filer by post-format-standard..Help me??

**Comment by sheriffderek** [comment]
@danbeo95 That is starting to sound like a call for help found in the WordPress forum, and that's scary. It's important that we outline, in specific, what we want to accomplish and what we've tried and any ideas on a direction to find answers. @cbothner do you think this is an ember-wordpress hole, or is this related specifically to the wp-api?
