### ISSUE TITLE
WP api and WordPress Multisite

### ISSUE THREAD

**Issue by paaljoachim** [WP-API/WP-API#992]
I am thinking here...playing with this thought...

Sometime this year WP API will likely be incorporated into WordPress Core.

What if the API is used to recreate multisite before that time?
As right now multisite really needs a version 2. As the existing version seems somewhat lacking of userfriendliness. Creating an easier way to create a WP network would be really great for all those users who really need more then what the standard WP gives. Meaning an updated WP network (multisite). Kinda like skinning a new WP Network.

Anyhow have a great day!

**Comment by hamidire** [comment]
how can i use this plugin for multi site? is there any documentaion on this topic?

**Comment by vangelis183** [comment]
@hamidire Are able to get this working?

**Comment by danielbachhuber** [comment]
WP-API doesn't yet support creating sites on a multisite network, but this is something that will come in the future.
