### ISSUE TITLE
filtering custom post types by their taxonomies?

### ISSUE THREAD

**Issue by Onyx808** [WP-API/WP-API#994]
Hello,

I have a custom post types called "videos" and these posts have taxonomy called "sports" with categories (sports) like "Basketball, Baseball, etc.." so I been trying to get all the posts per their category lets say "Basketball" but I haven't been able to get it to work, I tried all kinds of calls with no luck =(
Help!
Thank you, love the plugin <3

**Comment by danielbachhuber** [comment]
In 2.0, you'll be able to do something like:

`/wp/videos?sports=baseball`

See #924
