### ISSUE TITLE
PUT /posts/<id> requires too much info

### ISSUE THREAD

**Issue by dleeward** [WP-API/WP-API#995]
In version 1.1.1, the documentation says that ID, title, and content_raw are required fields. I'm just a user (not a developer) and understand that title and content_raw are required for new WordPress posts, but why are they required for editing a post if they already exist?

Also, when trying to post without all the required fields, the empty_content error message description reports that "Content, title, and excerpt are empty." even though the excerpt_raw field is optional.

Any plans to release version 1.2 anytime soon? Is there an errata of the version 1.1.1 documentation available anywhere?

**Comment by dleeward** [comment]
Just found part of this is in issue #952 and understand this is how core does it. But I'm using a third party mashup tool rather than code and being able to edit fields without having to retrieve the post first, store the title and content, and combine it with the new data would simplify things greatly. The Jetpack API (when I can get it to work) allows this. Please also add my vote for #322 to sideload a featured image with the post.

**Comment by dleeward** [comment]
Also during my testing, I noticed that when I do provide the required fields for a custom post type, a new "post" post type is created rather than modifying the existing post. Is this expected behavior?

**Comment by danielbachhuber** [comment]
> I noticed that when I do provide the required fields for a custom post type, a new "post" post type is created rather than modifying the existing post. Is this expected behavior?

In 1.2, you need to supply a `post_type` argument in your original request, otherwise creation will default to `post`. 2.0 changes the behavior to have `/wp/posts`, `/wp/pages`, `/wp/my-cpt` endpoints.

**Comment by dleeward** [comment]
Is there separate documentation for v1.1 and v1.2?

**Comment by dleeward** [comment]
Documentation specifies a `type` argument rather than `post_type`. Does that mean the documentation is not updated for v1.2?
