### ISSUE TITLE
filter[posts_per_page]=3  Doesn't work.

### ISSUE THREAD

**Issue by antwonlee** [WP-API/WP-API#997]
I am trying to fetch only latest 3 posts and display on my Rails application, but that filter is not working.  While I can filter through category names, I can't seem to control how many data are getting fetched when I do a get request.

Here is what i have

<pre><code>http://thisismywebsitewherewordpresslives.com/wp-json/posts?filter[posts_per_page]=2&fiter[category_name]=Some Category Name I want to query&filter[order]=ASC</code></pre>

**Comment by rachelbaker** [comment]
@antwonlee `filter[posts_per_page]=2` works for me.  Which version of the plugin are you using?

The "develop" branch is undergoing substantial changes and is NOT COMPLETE OR STABLE.

The "master" branch represents a BETA of our next version release.

The latest stable version is available from the WordPress Plugin Directory.

**Comment by antwonlee** [comment]
I am using 1.1.1  Here is my query:

<pre><code>http://thriveconnection.com/wp-json/posts?filter[posts_per_page]=1</pre></code>

It still seems to fetch all...

I am trying to fetch this:

<pre><code>http://thriveconnection.com/wp-json/posts?filter[posts_per_page]=1&fiter[category_name]=30%20Days&filter[order]=ASC</pre></code>

What am I doing wrong? @rachelbaker Any suggestions will be appreciated!

**Comment by joehoyle** [comment]
@antwonlee it's possible you have a plugin that is overriding the `posts_per_page` WP_Query setting. Could you try disabling any plugins you are using to see if this then starts to function as expected.
